### PR TITLE
[LangingPage] Add  paragraph with call-to-action, sign-up button

### LINKED ISSUE #1604: Improve the landing page experience
- [x] 1. Rename 'Register' button to 'Sign Up'
- [ ] 2. Include a 'call to action' paragraph with an additional 'Sign Up' button in the content area
- [x] 3. Add a link to the 'Sign Up' in the 'Account' documentation

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #1604, step 2.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1616)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[src/components/LandingPage/index.tsx, line 87 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1616#-MyRwUBSBWkQQ5sdKvEr:-MyRwUBSBWkQQ5sdKvEs:btkaree) ([raw file](https://github.com/sillsdev/thecombine/blob/7ab88cd84b152082b8cfffcd8d1c7c2a5d808a07/src/components/LandingPage/index.tsx#L87)):*
> ```XML
> }
> 
> function SignUpButton() {
> ```

Add return type annotation?

**Comment by johnthagen** [comment]
___
*[src/components/LandingPage/index.tsx, line 87 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1616#-MyRwUBSBWkQQ5sdKvEr:-MyRwdeW6YstqRBlakDj:bobrk9g) ([raw file](https://github.com/sillsdev/thecombine/blob/7ab88cd84b152082b8cfffcd8d1c7c2a5d808a07/src/components/LandingPage/index.tsx#L87)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Add return type annotation?
</blockquote></details>

(Applies to all functions in this file)

**Comment by johnthagen** [comment]
___
*[src/resources/translations.json, line 43 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1616#-MyRwmcg5TW57YyT1SLI:-MyRwmcg5TW57YyT1SLJ:b-da0how) ([raw file](https://github.com/sillsdev/thecombine/blob/7ab88cd84b152082b8cfffcd8d1c7c2a5d808a07/src/resources/translations.json#L43)):*
> ```JSON
>     ],
>     "descriptionP4": [
>       "Are you organizing or assisting with word collection? Or do you have RWC data that needs to be cleaned up? To get started with The Combine: ",
> ```

I would add a line break before `To get started with The Combine:` (or perhaps this should be translated as a separate paragraph. The call to action and button placement currently read a little odd based on the width of the screen.

Should the button also be on its on line and centered?

**Comment by johnthagen** [comment]
___
*[src/resources/translations.json, line 43 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1616#-MyRwmcg5TW57YyT1SLI:-MyRxczxDDiNFKjI9a3f:b-a9gmew) ([raw file](https://github.com/sillsdev/thecombine/blob/7ab88cd84b152082b8cfffcd8d1c7c2a5d808a07/src/resources/translations.json#L43)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I would add a line break before `To get started with The Combine:` (or perhaps this should be translated as a separate paragraph. The call to action and button placement currently read a little odd based on the width of the screen.

Should the button also be on its on line and centered?



</blockquote></details>

Also, maybe want to make the final sentence more imperative?

"Get started with The Combine by signing up" ?

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1616)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor and @johnthagen)

___
*[src/resources/translations.json, line 43 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1616#-MyRwmcg5TW57YyT1SLI:-MyTO_vj7kgoyZMWm7Ah:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7ab88cd84b152082b8cfffcd8d1c7c2a5d808a07/src/resources/translations.json#L43)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Also, maybe want to make the final sentence more imperative?

"Get started with The Combine by signing up" ?
</blockquote></details>

Done.

**Review by johnthagen — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 2 of 4 files at r2, 7 of 7 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1616)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jasonleenaylor)

**Pull request merged**
