### PR TITLE
Fix LocalStorage reset function.

### LINKED ISSUE #848: User avatars not removed from browser after database wipe
1. Drop database
2. Create a new user
3. Add an avatar
4. Log out
5. Drop database
6. Delete ~/.CombineFiles
7. Disable cache on browser
8. Create a new user
9. Log in

You will see the original user's avatar. This might have to do with how we respond to that request or some other caching with React DOM interaction.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #848 
Adds a unit test that would have caught the underlying problem.

It seems that `for (const item in someEnum)` has some unintuitive behavior.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/866)

### CODE REVIEW

**Review by johnthagen — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/866)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Comment by johnthagen** [comment]
___
*[src/backend/localStorage.tsx, line 15 at r1](https://reviewable.io/reviews/sillsdev/thecombine/866#-MOOSHfk4U8RbS12bN5O:-MOOSHfk4U8RbS12bN5P:b5u5fob) ([raw file](https://github.com/sillsdev/thecombine/blob/fe251532e632d667adf299957c4c2cd0e9f1d2c8/src/backend/localStorage.tsx#L15)):*
> ```XML
> export function clearLocalStorage() {
>   for (const keyString in LocalStorageKey) {
>     const key = keyString as keyof typeof LocalStorageKey;
> ```

Is this worth a comment or a reference to the TypeScript docs about why this is needed?

**Comment by imnasnainaec** [comment]
> _[src/backend/localStorage.tsx, line 15 at r1](https://reviewable.io/reviews/sillsdev/thecombine/866#-MOOSHfk4U8RbS12bN5O:-MOOSHfk4U8RbS12bN5P:b5u5fob) ([raw file](https://github.com/sillsdev/thecombine/blob/fe251532e632d667adf299957c4c2cd0e9f1d2c8/src/backend/localStorage.tsx#L15)):_
> 
> > ```
> > export function clearLocalStorage() {
> >   for (const keyString in LocalStorageKey) {
> >     const key = keyString as keyof typeof LocalStorageKey;
> > ```
> 
> Is this worth a comment or a reference to the TypeScript docs about why this is needed?

@johnthagen Sadly, I didn't find clear documentation on the matter. This was the result of trial and error.

**Comment by johnthagen** [comment]
___
*[src/backend/localStorage.tsx, line 15 at r1](https://reviewable.io/reviews/sillsdev/thecombine/866#-MOOSHfk4U8RbS12bN5O:-MOQt8tKB2VkVEl3NRER:b32w0x) ([raw file](https://github.com/sillsdev/thecombine/blob/123959e0c9d580b759aa664cfe9f90893d06680d/src/backend/localStorage.tsx#L15)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

@johnthagen Sadly, I didn't find clear documentation on the matter. This was the result of trial and error. 
</blockquote></details>

OK

**Pull request merged**
