### PR TITLE
Recommend Ubuntu 20.04 for Linux development

### PR DESCRIPTION
**Pull request by johnthagen**
Encourage new contributors/developers to target Ubuntu 20.04. This makes sure the Python version is new enough for what we currently support without extra steps needed to install a new version of Python.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1169)

### CODE REVIEW

**Comment by johnthagen** [comment]
@jmgrady I specifically avoided changing anything in the deployment section, as that seems a bit tangential to development setups and also you would be much more qualified to change anything in that section.

**Review by jmgrady — COMMENTED** [review]
I think that is is good to update the development instructions for 20.04 but that does not completely change the Python release landscape.  This is mostly because the current TeamCity build agents are running Ubuntu 18.04/Python 3.6.  I will check with Greg about a Focal build agent (at least until we can move to GitHub Actions).

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1169#-:-MaEBGTI28yaI-kkBH9S:b-tbhgk5)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[README.md, line 83 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1169#-MaEAzfX1bbNZqm5dvow:-MaEAzfX1bbNZqm5dvox:bedd01n) ([raw file](https://github.com/sillsdev/thecombine/blob/7986bfa5fbdd904899548216a0c8b5478d647cf8/README.md#L83)):*
> ```
>    - [.NET Core SDK 3.1 (LTS)](https://dotnet.microsoft.com/download/dotnet-core/3.1)
> ```
.NET 5.0 is also available for Ubuntu 20.04.  Is that preferable to .NET Core 3.1?

**Comment by johnthagen** [comment]
___
*[README.md, line 83 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1169#-MaEAzfX1bbNZqm5dvow:-MaECX8rAGuoK8pUho2N:b-2gdpwv) ([raw file](https://github.com/sillsdev/thecombine/blob/7986bfa5fbdd904899548216a0c8b5478d647cf8/README.md#L83)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

> ```
>    - [.NET Core SDK 3.1 (LTS)](https://dotnet.microsoft.com/download/dotnet-core/3.1)
> ```
.NET 5.0 is also available for Ubuntu 20.04.  Is that preferable to .NET Core 3.1?
</blockquote></details>

We have yet to upgrade to .NET 5.0, so we would need to stick with .NET Core 3.1. Since .NET 5.0 is not an LTS release, we may choose to stay on 3.1 until a new LTS is released: https://dotnet.microsoft.com/platform/support/policy/dotnet-core

**Review by johnthagen — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1169)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Review by jmgrady — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1169#-:-MaF7OzU2myHRo1gquPd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Pull request merged**
