### PR TITLE
[ProjectSettings] Refactor with category tabs

### LINKED ISSUE #1176: Redesign Project Settings
The Project Settings page is unwieldy.

Use the tabs of #2415, with appropriate groupings
- [x] Convert project switch into a separate dropdown selector (#2416)
- [ ] Tabs for project... (#2569)
  - Basic (Name/Archive/Autocomplete)
  - Languages
  - Users
  - Import/Export
  - Schedule 
- [ ] ~~Could merge BaseSettings, ProjectSettings, SiteSettings into a single Settings folder with common components (and things specific to ProjectSettings and SiteSettings in respective subfolders)~~ Move ProjectUsers out from ProjectSettings, since its contents are used by both ProjectsSettings and SiteSettings (#2569)

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #1176

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2569)

### CODE REVIEW

**Comment by imnasnainaec** [comment]
Need to update tests.

**Comment by imnasnainaec** [comment]
Need to account for narrow screens.

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 17 of 21 files at r2, 2 of 4 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2569)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[`src/components/ProjectSettings/index.tsx` line 163 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2569#-NeiHYSl6tIycFqQunN6:-NeiHYSl6tIycFqQunN7:b748c07) ([raw file](https://github.com/sillsdev/TheCombine/blob/bec54200fede7a794ff5641af3b571117aafceb1/src/components/ProjectSettings/index.tsx#L163)):*
> ```XML
> 
>           {/* Autocomplete toggle */}
>           {permissions.includes(Permission.DeleteEditSettingsAndUsers) && (
> ```

This permission name surprised me, but I don't remember what our set of permissions is right now, so don't change it if DeleteEditSettingsAndUsers is currently the best for AutoComplete.
___
*[`src/components/ProjectSettings/tests/SettingsTabTypes.ts` line 1 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2569#-NeiJi6Q0O1J1YB9eXsA:-NeiJi6Q0O1J1YB9eXsB:blovarb) ([raw file](https://github.com/sillsdev/TheCombine/blob/bec54200fede7a794ff5641af3b571117aafceb1/src/components/ProjectSettings/tests/SettingsTabTypes.ts#L1)):*
> ```XML
> import { Permission } from "api/models";
> ```

This test utility file is excellent. I think each public constant and method should have a *brief* comment for the future when we have to figure out why a test started failing.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2569)* status: 23 of 24 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

___
*[`src/components/ProjectSettings/index.tsx` line 163 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2569#-NeiHYSl6tIycFqQunN6:-NeiW9e7BU3igN-OhVz1:b-eu30lf) ([raw file](https://github.com/sillsdev/TheCombine/blob/bec54200fede7a794ff5641af3b571117aafceb1/src/components/ProjectSettings/index.tsx#L163)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

This permission name surprised me, but I don't remember what our set of permissions is right now, so don't change it if DeleteEditSettingsAndUsers is currently the best for AutoComplete.
</blockquote></details>

`DeleteEditSettingsAndUsers` is short for "Delete and edit settings and delete and edit users", a bit of a catch-all, with the permission for Autocomplete falling into the "Edit settings" part.
___
*[`src/components/ProjectSettings/tests/SettingsTabTypes.ts` line 1 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2569#-NeiJi6Q0O1J1YB9eXsA:-NeiWURc8o3WaOMUAdVU:bdzxx6v) ([raw file](https://github.com/sillsdev/TheCombine/blob/bec54200fede7a794ff5641af3b571117aafceb1/src/components/ProjectSettings/tests/SettingsTabTypes.ts#L1)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

This test utility file is excellent. I think each public constant and method should have a *brief* comment for the future when we have to figure out why a test started failing.
</blockquote></details>

Thank you! :grin: I had fun writing it.
I've added a comment before each of them (not just the `export`-ed ones).

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2569)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
