### PR TITLE
Verify Kubernetes context before install

### PR DESCRIPTION
**Pull request by jmgrady**
Update the `setup_cluster.py` and `setup_combine.py` scripts to prompt the user to verify the Kubernetes context before the setup tasks are run.

If there is more than one context available, then the script will list the selected context and ask the user to verify the context or select another.

Note that there should be no prompting when run in the CI/CD pipeline.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1739)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 5 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1739)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

___
*[`deploy/scripts/aws_env.py` line 66 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1739#-NE6n0S75a3_cMqXe_M_:-NE6n0S85KGw4TmRSQcS:b6m5z16) ([raw file](https://github.com/sillsdev/thecombine/blob/247af5c70b8feafeeb8bfe19559bf67a863b45c7/deploy/scripts/aws_env.py#L66)):*
> ```Python
>         os.environ["AWS_SECRET_ACCESS_KEY"] = get_profile_var(aws_profile, "aws_secret_access_key")
>         region = get_profile_var(aws_profile, "region")
>         os.environ["AWS_DEFAULT_REGION"] = region
> ```

Looks like defining `region` creates an unnecessary extra line.



_Code quote:_
```Python
        region = get_profile_var(aws_profile, "region")
        os.environ["AWS_DEFAULT_REGION"] = region
```
___
*[`deploy/scripts/kube_env.py` line 80 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1739#-NE6lOlr75STn9AOMCFe:-NE6lOlr75STn9AOMCFf:b-druvd9) ([raw file](https://github.com/sillsdev/thecombine/blob/247af5c70b8feafeeb8bfe19559bf67a863b45c7/deploy/scripts/kube_env.py#L80)):*
> ```Python
>     Add commandline arguments that are shared between scripts calling helm.
> 
>     Sets up '--verbose' as the equivalent of '--debug'.
> ```

This vestigial `--verbose` reference can be removed. 



_Code quote:_
```Python
 Sets up '--verbose' as the equivalent of '--debug'.
```

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1739)* status: 8 of 12 files reviewed, all discussions resolved (waiting on @imnasnainaec and @jmgrady)

___
*[`deploy/scripts/aws_env.py` line 66 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1739#-NE6n0S75a3_cMqXe_M_:-NE77y6U9mNlD5SYb9fj:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/247af5c70b8feafeeb8bfe19559bf67a863b45c7/deploy/scripts/aws_env.py#L66)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Looks like defining `region` creates an unnecessary extra line.
</blockquote></details>

Done.
___
*[`deploy/scripts/kube_env.py` line 80 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1739#-NE6lOlr75STn9AOMCFe:-NE78KLT8fYiiTOWqNM8:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/247af5c70b8feafeeb8bfe19559bf67a863b45c7/deploy/scripts/kube_env.py#L80)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

This vestigial `--verbose` reference can be removed. 
</blockquote></details>

Done.

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1739)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[`deploy/scripts/kube_env.py` line 77 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1739#-NEBeU4hBWarW437Und6:-NEBkqby5YY3VDjsbiLX:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/14720b62588d3a43877c1c97f0d02a60938b5540/deploy/scripts/kube_env.py#L77)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Capital U in `KUbern...`?
</blockquote></details>

Done.
___
*[`deploy/scripts/utils.py` line 70 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1739#-NEBfQ9b-2dzMdl48eI3:-NEBmwxhCSHVJGAxqDP7:b-v3o6j0) ([raw file](https://github.com/sillsdev/thecombine/blob/14720b62588d3a43877c1c97f0d02a60938b5540/deploy/scripts/utils.py#L70)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

If `curr_selection is None` and `len(options)=1`, the present algorithm returns `None` instead of the single entry in `options`. Is that okay?
</blockquote></details>

No, it is not (and it doesn't match the description!

I have added a test for the case you mentioned at the beginning of the function:
```
    if len(options) == 1 and curr_selection is not None and curr_selection == options[0]:
       return curr_selection 
```
If this condition is not met, it will prompt the user if `len(options) >= 1` instead of strictly `>` so if the `curr_selection` is `None` the user will be prompted to select the option.  I don't want to blindly take the single option because if it is not the correct one, The Combine could be installed on the wrong Kubernetes cluster or with the wrong AWS permissions.

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1739)* status: 10 of 12 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[`deploy/scripts/utils.py` line 70 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1739#-NEBfQ9b-2dzMdl48eI3:-NEBozym9g9HSJzAH3wg:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/14720b62588d3a43877c1c97f0d02a60938b5540/deploy/scripts/utils.py#L70)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

No, it is not (and it doesn't match the description!

I have added a test for the case you mentioned at the beginning of the function:
```
    if len(options) == 1 and curr_selection is not None and curr_selection == options[0]:
       return curr_selection 
```
If this condition is not met, it will prompt the user if `len(options) >= 1` instead of strictly `>` so if the `curr_selection` is `None` the user will be prompted to select the option.  I don't want to blindly take the single option because if it is not the correct one, The Combine could be installed on the wrong Kubernetes cluster or with the wrong AWS permissions.
</blockquote></details>

Done.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1739)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

___
*[`deploy/scripts/utils.py` line 80 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1739#-NECKTT39aWIf2bdq2yk:-NECKTT39aWIf2bdq2yl:b5iymvg) ([raw file](https://github.com/sillsdev/thecombine/blob/d4e369bc7842799f7b8ca56380bc680c92a35a24/deploy/scripts/utils.py#L80)):*
> ```Python
>                 prompt_str = f"Enter {name}: "
>             else:
>                 prompt_str = f"Enter {name}(Default: {curr_selection}): "
> ```

A space between `{name}` and `(Default` might be nice.
___
*[`deploy/scripts/utils.py` line 101 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1739#-NECJww33NnDxuP_7-Xo:-NECJww33NnDxuP_7-Xp:blmhu1o) ([raw file](https://github.com/sillsdev/thecombine/blob/d4e369bc7842799f7b8ca56380bc680c92a35a24/deploy/scripts/utils.py#L101)):*
> ```Python
>                             curr_selection = None
>                     except ValueError:
>                         curr_selection = None
> ```

It looks like an invalid user selection will cause the initial default to no longer be the default. If that's the case, is that okay?

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1739)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[`deploy/scripts/utils.py` line 80 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1739#-NECKTT39aWIf2bdq2yk:-NECRCffEFOq5m1kSx9Z:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/d4e369bc7842799f7b8ca56380bc680c92a35a24/deploy/scripts/utils.py#L80)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

A space between `{name}` and `(Default` might be nice.
</blockquote></details>

Done.
___
*[`deploy/scripts/utils.py` line 101 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1739#-NECJww33NnDxuP_7-Xo:-NECS3Io7hKjVBXBimOM:b-isofri) ([raw file](https://github.com/sillsdev/thecombine/blob/d4e369bc7842799f7b8ca56380bc680c92a35a24/deploy/scripts/utils.py#L101)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

It looks like an invalid user selection will cause the initial default to no longer be the default. If that's the case, is that okay?
</blockquote></details>

I don't have a problem with that.  By entering something the first time it is safe to assume that the user does not want the default so they just need to select a valid option.  This also conforms to the usual practice that Ctrl-C will just exit completely in the case that the user does not want any of the suggestions.

I did, however, update it so that it will reprint the list if an invalid option is selected.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1739)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Pull request merged**
