### PR TITLE
Reorganize development scripts

### PR DESCRIPTION
**Pull request by johnthagen**
Currently the top level project folder is a mix of configuration files for different languages, Docker config, Git, and scripts.

This PR attempts to clean up the top level project folder a bit by organizing the developer command line scripts into a separate `scripts/` directory.

Note: The paths in the `.ts` files were not updated because when they are run using `npm run`, the current working directory is still the project root where `npm run` is executed.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/745)

### CODE REVIEW

**Review by imnasnainaec — CHANGES_REQUESTED** [review]
> Reviewed 11 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/745)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[package.json, line 16 at r2](https://reviewable.io/reviews/sillsdev/thecombine/745#-MIe3axTD3f2osx7H7ha:-MIe3axTD3f2osx7H7hb:bbpaswp) ([raw file](https://github.com/sillsdev/thecombine/blob/a5cfd1c64ba176b0897b1e731e1e4a82d507f3ed/package.json#L16)):*
> ```JSON
>     "frontend": "react-scripts start",
>     "gen-backend-coverage-report": "tsc scripts/genBackendCoverageReport.ts && node scripts/genBackendCoverageReport.js",
>     "import-sem-doms": "tsc scripts/SemanticDomains.ts && node scripts/importSemanticDomains.js",
> ```

`scripts/SemanticDomains.ts` -> `scripts/importSemanticDomains.ts`
___
*[scripts/docker_setup.py, line 12 at r2](https://reviewable.io/reviews/sillsdev/thecombine/745#-MIe2dXJB92YQHh3k9jt:-MIe2dXJB92YQHh3k9ju:bgu0op0) ([raw file](https://github.com/sillsdev/thecombine/blob/a5cfd1c64ba176b0897b1e731e1e4a82d507f3ed/scripts/docker_setup.py#L12)):*
> ```Python
>     1. Create the following directories:
>         ./nginx/scripts
>     2. Build docker-compose.yml from
> ```

`directories`->`directory` and `./nginx/scripts`->`../nginx/scripts`

**Comment by johnthagen** [comment]
___
*[package.json, line 16 at r2](https://reviewable.io/reviews/sillsdev/thecombine/745#-MIe3axTD3f2osx7H7ha:-MIeAlPq9kdSqoEU2dNP:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/a5cfd1c64ba176b0897b1e731e1e4a82d507f3ed/package.json#L16)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`scripts/SemanticDomains.ts` -> `scripts/importSemanticDomains.ts`
</blockquote></details>

Done.

**Comment by johnthagen** [comment]
___
*[scripts/docker_setup.py, line 12 at r2](https://reviewable.io/reviews/sillsdev/thecombine/745#-MIe2dXJB92YQHh3k9jt:-MIeAmvE6kC0AVKPDfiu:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/a5cfd1c64ba176b0897b1e731e1e4a82d507f3ed/scripts/docker_setup.py#L12)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`directories`->`directory` and `./nginx/scripts`->`../nginx/scripts`
</blockquote></details>

Done

**Review by johnthagen — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/745#-:-MIeAoyuCAAYTyw48yZE:bnfp4nl)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @johnthagen)

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/745)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
