### PR TITLE
Shine effect on domain button in TreeView

### LINKED ISSUE #338: It is not obvious how to get from semantic domain selection to entering words
[05/26 Requirements #3](https://docs.google.com/document/d/1A9Wv7SY_peIqdfGEBgzdl-7Pn19Dn70CDy9apVOUiak/edit#heading=h.bpnzighs5fhw):  It’s not obvious how to get to the screen for entering words, once you’ve gotten to the desired semantic domain.

### PR DESCRIPTION
**Pull request by shyung18**
Resolves #338

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/461)

### CODE REVIEW

**Comment by imnasnainaec** [comment]
The changes in package.json and package-lock.json are not sufficient for this branch to run on my machine. Are there any `npm` commands I need to execute to test this branch?

**Comment by charjhall** [comment]
*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/461#-MBZS9P923-sug6v1O5w:-MBZS9P923-sug6v1O5x:bc3q6z1) (no related file):*
I am seeing this behavior on text search. Should this only show bounce on first seeing it? 



---

**Comment by charjhall** [comment]
*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/461#-MBZS9P923-sug6v1O5w:-MBZXWmO93A0ef2X6dZV:b2o2rs0) (no related file):*
<details><summary><i>Previously, charjhall (Charles Hall) wrote…</i></summary><blockquote>

I am seeing this behavior on text search. Should this only show bounce on first seeing it? 



</blockquote></details>

[This may be helpful.](https://www.react-reveal.com/docs/when/)

---

**Comment by charjhall** [comment]
*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/461#-MBZS9P923-sug6v1O5w:-MBZYJS4AS9JBCPNi1Tn:b-o2jcrd) (no related file):*
<details><summary><i>Previously, charjhall (Charles Hall) wrote…</i></summary><blockquote>

[This may be helpful.](https://www.react-reveal.com/docs/when/)
</blockquote></details>

[As might this](https://www.react-reveal.com/docs/props/)

---

**Pull request merged**
