### PR TITLE
Correct brace style in C# style guide

### PR DESCRIPTION
**Pull request by johnthagen**
- Correct C# style guide to follow the standard C# brace and indentation style.
- Remove all .NET version-specific query args from hyperlinks

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1513)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1513)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @johnthagen)

___
*[README.md, line 720 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1513#-MsovPI62IMqZEB8h6pC:-MsovPI62IMqZEB8h6pD:bjascp1) ([raw file](https://github.com/sillsdev/thecombine/blob/e3254fb6925b5b06c444e773d943488ba72d38ff/README.md#L720)):*
> ```Markdown
> - [C#](https://www.w3schools.com/cs/default.asp)
> - [Our style guide](docs/style_guide/c_sharp_style_guide.md)
> - [ASP.NET](https://docs.microsoft.com/en-us/aspnet/core/getting-started/?view=aspnetcore-6.0)
> ```

Perhaps remove `?view=...` altogether, since it defaults to the current release.
___
*[Backend/Startup.cs, line 146 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1513#-MsovOQa4Qpxmx-XkPeE:-MsovOQa4Qpxmx-XkPeF:bjascp1) ([raw file](https://github.com/sillsdev/thecombine/blob/e3254fb6925b5b06c444e773d943488ba72d38ff/Backend/Startup.cs#L146)):*
> ```Smalltalk
> 
>             // Configure Swashbuckle OpenAPI generation.
>             // https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-6.0
> ```

Perhaps remove `?view=...` altogether, since it defaults to the current release.
___
*[docs/style_guide/c_sharp_style_guide.md, line 54 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1513#-MsouupB-7hFn5W3qKZg:-MsouupC-q_nJ2RcRTrT:bjascp1) ([raw file](https://github.com/sillsdev/thecombine/blob/e3254fb6925b5b06c444e773d943488ba72d38ff/docs/style_guide/c_sharp_style_guide.md#L54)):*
> ```Markdown
> ```
> 
> The signature of [`Range`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.range?view=net-6.0) is:
> ```

Perhaps remove `?view=...` altogether, since it defaults to the current release.

**Comment by johnthagen** [comment]
___
*[README.md, line 720 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1513#-MsovPI62IMqZEB8h6pC:-Msow-PF1gHXbUjwcbuS:b-ennubi) ([raw file](https://github.com/sillsdev/thecombine/blob/e3254fb6925b5b06c444e773d943488ba72d38ff/README.md#L720)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Perhaps remove `?view=...` altogether, since it defaults to the current release.
</blockquote></details>

@imnasnainaec My thought was that if .NET 7 releases and we don't upgrade to it immediately, this would pin our docs to the version we are actually using and prescribing to developers.

But, dealing with these links is busy work that has little value, so I'm on the fence and could go anyway.

Do you see any value at pinning to the actual version we use?

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1513)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @johnthagen)

___
*[README.md, line 720 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1513#-MsovPI62IMqZEB8h6pC:-MsowgzU080dCmCFp4VO:b-r6xd0m) ([raw file](https://github.com/sillsdev/thecombine/blob/e3254fb6925b5b06c444e773d943488ba72d38ff/README.md#L720)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

@imnasnainaec My thought was that if .NET 7 releases and we don't upgrade to it immediately, this would pin our docs to the version we are actually using and prescribing to developers.

But, dealing with these links is busy work that has little value, so I'm on the fence and could go anyway.

Do you see any value at pinning to the actual version we use?
</blockquote></details>

Definitely not for https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.range. Probably not for https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle. Perhaps just here.



_Code quote (from docs/style_guide/c_sharp_style_guide.md):_
```Markdown
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.range
```

**Comment by johnthagen** [comment]
___
*[README.md, line 720 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1513#-MsovPI62IMqZEB8h6pC:-MsoxciW2iFuONL2iRhY:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/e3254fb6925b5b06c444e773d943488ba72d38ff/README.md#L720)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Definitely not for https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.range. Probably not for https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle. Perhaps just here.
</blockquote></details>

Done.

**Comment by johnthagen** [comment]
___
*[Backend/Startup.cs, line 146 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1513#-MsovOQa4Qpxmx-XkPeE:-Msoxdf695RcnnZHPjvo:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/e3254fb6925b5b06c444e773d943488ba72d38ff/Backend/Startup.cs#L146)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Perhaps remove `?view=...` altogether, since it defaults to the current release.
</blockquote></details>

Done.

**Comment by johnthagen** [comment]
___
*[docs/style_guide/c_sharp_style_guide.md, line 54 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1513#-MsouupB-7hFn5W3qKZg:-MsoxfwXEW7v3NTv2YCw:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/e3254fb6925b5b06c444e773d943488ba72d38ff/docs/style_guide/c_sharp_style_guide.md#L54)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Perhaps remove `?view=...` altogether, since it defaults to the current release.
</blockquote></details>

Done.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1513)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Pull request merged**
