### PR TITLE
Develop statistics for admins

### PR DESCRIPTION
**Pull request by fuencui**
Hi there,
Thank you for the code review.
Thanks to everyone who wrote the detailed customer story at the Combine Kanban that help me a lot to understand customer needs.
I tried to write some code at the initial stage to help me understand the infrastructure of the project.
The new API I wrote provides statistics data returning a list of pairs that contains a Domain Tree Node and its statistics number.
If you have time Please take a look and welcome to leave any suggestions. 

AppBarComponent.test.tsx failed currently since I modified the NavigationButtons.tsx
This is a draft PR. Will be closed after review

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/1820)

### CODE REVIEW

**Comment by fuencui** [comment]
image

**Review by jasonleenaylor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/1820)* status: 0 of 23 files reviewed, 4 unresolved discussions (waiting on @fuencui, @imnasnainaec, and @jmgrady)

___
*[`Backend/Controllers/SemanticDomainController.cs` line 49 at r1](https://reviewable.io/reviews/sillsdev/TheCombine/1820#-NMFRizS730YeotGHGKS:-NMFRizS730YeotGHGKT:b-bqbkoe) ([raw file](https://github.com/sillsdev/TheCombine/blob/1d2e5a7dcdea834f637176699a8c3ba2bdfadd2b/Backend/Controllers/SemanticDomainController.cs#L49)):*
> ```Smalltalk
>         [HttpGet("domainGetAll", Name = "GetAllSemanticDomainTreeNode")]
>         [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(SemanticDomainTreeNode))]
>         public async Task<IActionResult> GetAllSemanticDomainTreeNode(string lang)
> ```

It is a small change, but I think these methods would be better as a plural 'GetAllSemanticDomainTreeNodes'
___
*[`Backend/Controllers/StatisticsController.cs` line 33 at r1](https://reviewable.io/reviews/sillsdev/TheCombine/1820#-NMFShtRCMAegSZynWHM:-NMFShtRCMAegSZynWHN:b-jfyf6g) ([raw file](https://github.com/sillsdev/TheCombine/blob/1d2e5a7dcdea834f637176699a8c3ba2bdfadd2b/Backend/Controllers/StatisticsController.cs#L33)):*
> ```Smalltalk
>         [HttpGet("GetAllStatisticsPair", Name = "GetAllStatistics")]
>         [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<KeyValuePair<SemanticDomainTreeNode, int>>))]
>         public async Task<IActionResult> GetAllStatistics(string projectId, string lang)
> ```

I think a more descriptive method name for this would be "GetSemanticDomainCounts" or "GetSemanticDomainUseCounts", I'll continue the discussion for naming in our slack channel.
___
*[`Backend/Interfaces/IStatisticsService.cs` line 9 at r1](https://reviewable.io/reviews/sillsdev/TheCombine/1820#-NMFSBiWEJLVHBPeh5pS:-NMFSBiXB-T4ppCV_EbP:b54pcgi) ([raw file](https://github.com/sillsdev/TheCombine/blob/1d2e5a7dcdea834f637176699a8c3ba2bdfadd2b/Backend/Interfaces/IStatisticsService.cs#L9)):*
> ```Smalltalk
>     public interface IStatisticsService
>     {
>         Task<List<KeyValuePair<SemanticDomainTreeNode, int>>> GetAllStatisticsKeyPair(string projectId, string lang);
> ```

This method could also use a name change, after we settle on the  name for the controller we can adjust this one.
___
*[`Backend/Services/StatisticsService.cs` line 31 at r1](https://reviewable.io/reviews/sillsdev/TheCombine/1820#-NMFU9Vs8GOuY4M_Qw04:-NMFU9Vs8GOuY4M_Qw05:bdva29j) ([raw file](https://github.com/sillsdev/TheCombine/blob/1d2e5a7dcdea834f637176699a8c3ba2bdfadd2b/Backend/Services/StatisticsService.cs#L31)):*
> ```Smalltalk
>             }
> 
>             foreach (Word word in wordList)
> ```

I think that we should return the raw counts for each domain and handle any display of totals to the front end.
If we want to display a 'rolled up' or total including sub domains on the front-end we should handle the logic on the front-end.
It is useful to show the count of 1.1 alone, without adding 1.1.1 and 1.1.2 to that total



_Code quote:_
```Smalltalk
            foreach (Word word in wordList)
            {
                foreach (Sense sense in word.Senses)
                {
                    foreach (SemanticDomain sd in sense.SemanticDomains)
                    {
                        var temp = sd.Id;
                        while (temp.Length >= 1)
                        {
                            hashMap[temp] = hashMap.GetValueOrDefault(temp, 0) + 1;
                            if (temp.Length == 1)
                            {
                                break;
                            }
                            if (temp.Length >= 3)
                            {
                                temp = temp.Substring(0, temp.Length - 2);
                            }
                        }
                    }
                }
            }
```

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 2 of 17 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/1820)* status: 2 of 24 files reviewed, 5 unresolved discussions (waiting on @fuencui and @jmgrady)

___
*[`src/components/App/AppLoggedIn.tsx` line 36 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/1820#-NMZdVnx04IeWxFzz5BU:-NMZdVnx04IeWxFzz5BV:b4dxg91) ([raw file](https://github.com/sillsdev/TheCombine/blob/737a4876c5b40300627c8dcedb8e8d89521b3446/src/components/App/AppLoggedIn.tsx#L36)):*
> ```XML
>         <Route exact path={Path.SiteSettings} component={SiteSettings} />
>         <Route exact path={Path.UserSettings} component={UserSettings} />
>         <Route exact path={Path.Statistics} component={Statistics} />
> ```

Please move `<Route exact path={Path.Statistics} component={Statistics} />` before the line for `UserSettings` (in order to maintain alphabetical order).

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 3 of 22 files at r1, 10 of 17 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/1820)* status: 15 of 46 files reviewed, 6 unresolved discussions (waiting on @fuencui and @jmgrady)

___
*[`Backend/Services/StatisticsService.cs` line 55 at r12](https://reviewable.io/reviews/sillsdev/TheCombine/1820#-NM_xFU9AQ9k3TggB0pw:-NM_xFU9AQ9k3TggB0px:b-1h4hi4) ([raw file](https://github.com/sillsdev/TheCombine/blob/dcf160918213bd00a781e6138a501ad2005f0992/Backend/Services/StatisticsService.cs#L55)):*
> ```Smalltalk
>             foreach (SemanticDomainTreeNode domainTreeNode in domainTreeNodeList)
>             {
>                 resList.Add(new KeyValuePair<SemanticDomainTreeNode, int>(domainTreeNode, hashMap.GetValueOrDefault(domainTreeNode.Id, 0)));
> ```

After looking at the front-end code consuming this API I think that it might be better to create a custom struct to hold the Pair. It would make for more pleasant and clear code reading both here and on the other end.
Lets call it SemanticDomainCount to be consistent with the API method name.



_Code quote:_
```Smalltalk
KeyValuePair
```

**Review by jasonleenaylor — CHANGES_REQUESTED** [review]
@fuencui This is looking very good! I had a few more suggestions for improvement but I like the progress so far.

> Reviewed 1 of 22 files at r1, 1 of 17 files at r3, 1 of 2 files at r4, 1 of 1 files at r9, 20 of 20 files at r11, 1 of 2 files at r12, 12 of 13 files at r13.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/1820#-:-NMiwXPQ1IkmfLJcINNi:bsh67rt)* status: 48 of 49 files reviewed, 3 unresolved discussions (waiting on @fuencui and @jmgrady)

___
*[`Backend/Services/StatisticsService.cs` line 22 at r14](https://reviewable.io/reviews/sillsdev/TheCombine/1820#-NMiu2zC12M2N8Ej_fNX:-NMiu2zC12M2N8Ej_fNY:bgw1n2j) ([raw file](https://github.com/sillsdev/TheCombine/blob/b90352f6bb26949442d0566a490442fcd741c33c/Backend/Services/StatisticsService.cs#L22)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// Get a list SemanticDomainCount
> ```

A good method comment here would be: Get the count of senses which use each semantic domain as a list of SemanticDomainCount objects



_Code quote:_
```Smalltalk
Get a list SemanticDomainCount
```
___
*[`Backend/Services/StatisticsService.cs` line 24 at r14](https://reviewable.io/reviews/sillsdev/TheCombine/1820#-NMiuPM-06Ybg4eDJC_z:-NMiuPM-06Ybg4eDJCa-:bq2mopo) ([raw file](https://github.com/sillsdev/TheCombine/blob/b90352f6bb26949442d0566a490442fcd741c33c/Backend/Services/StatisticsService.cs#L24)):*
> ```Smalltalk
>         /// Get a list SemanticDomainCount
>         /// </summary>
>         /// <returns> List of SemanticDomainCount </returns>
> ```

The summary comment is enough for this method so the <returns> can be removed.



_Code quote:_
```Smalltalk
 /// <returns> List of SemanticDomainCount </returns>
```
___
*[`src/components/Statistics/tests/Statistics.test.tsx` line 22 at r14](https://reviewable.io/reviews/sillsdev/TheCombine/1820#-NMiwHAE6KNt59_VqjIm:-NMiwHAE6KNt59_VqjIn:b-8irnto) ([raw file](https://github.com/sillsdev/TheCombine/blob/b90352f6bb26949442d0566a490442fcd741c33c/src/components/Statistics/tests/Statistics.test.tsx#L22)):*
> ```XML
> 
> const mockProject = newProject();
> const mockProjectId = "mockProject";
> ```

I would move these const declarations above the jest.mock calls to help with the code readability.



_Code quote:_
```XML
const mockGetStatisticsCounts = jest.fn();
const mockGetProject = jest.fn();
const mockGetProjectId = jest.fn();

const mockProject = newProject();
const mockProjectId = "mockProject";
```

**Comment by fuencui** [comment]
> @fuencui This is looking very good! I had a few more suggestions for improvement but I like the progress so far.
> 
> > Reviewed 1 of 22 files at r1, 1 of 17 files at r3, 1 of 2 files at r4, 1 of 1 files at r9, 20 of 20 files at r11, 1 of 2 files at r12, 12 of 13 files at r13.
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/1820#-:-NMiwXPQ1IkmfLJcINNi:bsh67rt)_ status: 48 of 49 files reviewed, 3 unresolved discussions (waiting on @fuencui and @jmgrady)
> 
> _[`Backend/Services/StatisticsService.cs` line 22 at r14](https://reviewable.io/reviews/sillsdev/TheCombine/1820#-NMiu2zC12M2N8Ej_fNX:-NMiu2zC12M2N8Ej_fNY:bgw1n2j) ([raw file](https://github.com/sillsdev/TheCombine/blob/b90352f6bb26949442d0566a490442fcd741c33c/Backend/Services/StatisticsService.cs#L22)):_
> 
> > ```smalltalk
> >         /// <summary>
> >         /// Get a list SemanticDomainCount
> > ```
> 
> A good method comment here would be: Get the count of senses which use each semantic domain as a list of SemanticDomainCount objects
> 
> _Code quote:_
> 
> ```smalltalk
> Get a list SemanticDomainCount
> ```
> 
> _[`Backend/Services/StatisticsService.cs` line 24 at r14](https://reviewable.io/reviews/sillsdev/TheCombine/1820#-NMiuPM-06Ybg4eDJC_z:-NMiuPM-06Ybg4eDJCa-:bq2mopo) ([raw file](https://github.com/sillsdev/TheCombine/blob/b90352f6bb26949442d0566a490442fcd741c33c/Backend/Services/StatisticsService.cs#L24)):_
> 
> > ```smalltalk
> >         /// Get a list SemanticDomainCount
> >         /// </summary>
> >         /// <returns> List of SemanticDomainCount </returns>
> > ```
> 
> The summary comment is enough for this method so the can be removed.
> 
> _Code quote:_
> 
> ```smalltalk
>  /// <returns> List of SemanticDomainCount </returns>
> ```
> 
> _[`src/components/Statistics/tests/Statistics.test.tsx` line 22 at r14](https://reviewable.io/reviews/sillsdev/TheCombine/1820#-NMiwHAE6KNt59_VqjIm:-NMiwHAE6KNt59_VqjIn:b-8irnto) ([raw file](https://github.com/sillsdev/TheCombine/blob/b90352f6bb26949442d0566a490442fcd741c33c/src/components/Statistics/tests/Statistics.test.tsx#L22)):_
> 
> > ```
> > const mockProject = newProject();
> > const mockProjectId = "mockProject";
> > ```
> 
> I would move these const declarations above the jest.mock calls to help with the code readability.
> 
> _Code quote:_
> 
> ```
> const mockGetStatisticsCounts = jest.fn();
> const mockGetProject = jest.fn();
> const mockGetProjectId = jest.fn();
> 
> const mockProject = newProject();
> const mockProjectId = "mockProject";
> ```

**Comment by fuencui** [comment]
@jasonleenaylor
Thank you for your code review left a comment and provide valuable suggestions for improvement!
I made some changes based on your suggestion. My front-end components are currently relatively simple presenting a set of data. How to ensure that my tests follow the standards

**Review by jasonleenaylor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/1820)* status: 44 of 50 files reviewed, 5 unresolved discussions (waiting on @fuencui and @jmgrady)

___
*[`src/components/Statistics/Statistics.tsx` line 21 at r15](https://reviewable.io/reviews/sillsdev/TheCombine/1820#-NMpB6ao4A-requKfzQU:-NMpB6ao4A-requKfzQV:bcub6sr) ([raw file](https://github.com/sillsdev/TheCombine/blob/6d573b4dca9c7b936bf86629206886619b439f64/src/components/Statistics/Statistics.tsx#L21)):*
> ```XML
>   useEffect(() => {
>     updateCurrentProject();
>     const updateStatisticList = async () => {
> ```

I'm curious why you used two different methods to call an async function in useEffect.
It seems that the way you handled updateStatisticList could also be used for the getProject call. If there is a reason to do it differently a comment would be useful.



_Code quote:_
```XML
    updateCurrentProject();
    const updateStatisticList = async () => {
```
___
*[`src/components/Statistics/tests/Statistics.test.tsx` line 57 at r15](https://reviewable.io/reviews/sillsdev/TheCombine/1820#-NMp5wtDChnn6iRtGTX-:-NMp4smHAdHc0ffc3hIF:b9upk8k) ([raw file](https://github.com/sillsdev/TheCombine/blob/6d573b4dca9c7b936bf86629206886619b439f64/src/components/Statistics/tests/Statistics.test.tsx#L57)):*
> ```XML
> 
>   it("check if getSemanticDomainCounts method called from backend", async () => {
>     const spyFn = jest.spyOn(backend, "getSemanticDomainCounts");
> ```

I would recommend handling this test in the following way:

Instead of directly calling the backend modify the setMockFunctions to add mockGetStatisticsCounts.mockResolvedValue(() giving it an array containing one SemanticDomainCount object.

Check that the mocked backend function was called once, and then verify that the testRenderer actually rendered a ListItem for that SemanticDomainCount object.

That would cover the actual logic of the Statistics class, turning the backend return value into the List items that we display.



_Code quote:_
```XML
    const spyFn = jest.spyOn(backend, "getSemanticDomainCounts");
    const returnCounts = backend.getSemanticDomainCounts();
    expect(spyFn).toHaveBeenCalled();
    expect(returnCounts).toBe(undefined);
```
___
*[`src/components/Statistics/tests/Statistics.test.tsx` line 82 at r15](https://reviewable.io/reviews/sillsdev/TheCombine/1820#-NMpAwaR7UHynFyCto1v:-NMpAwaR7UHynFyCto1w:b-5nxumg) ([raw file](https://github.com/sillsdev/TheCombine/blob/6d573b4dca9c7b936bf86629206886619b439f64/src/components/Statistics/tests/Statistics.test.tsx#L82)):*
> ```XML
>   //     });
>   //   });
>   // });
> ```

You can remove the commented out code.



_Code quote:_
```XML
  // it("useState updated", async () => {
  //   await renderer.act(async () => {
  //     testRenderer = renderer.create(<Statistics />);
  //   });
  //   const newStatistics = testRenderer.root.findAllByType(Statistics);
  //   console.log(newStatistics[0].instance.setState({}));
  //   expect(newStatistics.length).toBe(1);
  //   testHandle = newStatistics[0];

  //   const realUseState = React.useState;
  //   const setLang = jest.fn();
  //   const useLangMock: any = (lang: string) => [lang, setLang];
  //   jest.spyOn(React, "useState").mockImplementation(useLangMock);
  //   testHandle.instance.setLang({ lang: [Bcp47Code.Es] }, () => {
  //     testRenderer.root.findByType(Statistics).instance.then(() => {
  //       expect(mockGetProject).toBeCalled();
  //       expect(mockGetProjectId).toBeCalled();
  //     });
  //   });
```

**Review by jasonleenaylor — COMMENTED** [review]
:LGTM:

> Reviewed 2 of 6 files at r15, 6 of 6 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/1820#-:-NNDp0ZS2505CnsB2Ezo:bmxilld)* status: all files reviewed, 1 unresolved discussion (waiting on @fuencui and @jmgrady)

**Review by jasonleenaylor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1820)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Pull request merged**
