### PR TITLE
[TreeView] lazy load domains; store domain map in redux

### LINKED ISSUE #664: TreeView causes redux error (Converting circular structure to JSON) in console
The following redux error is logged to the console when navigating into Data Entry or when adding a semantic domain to an entry from Review Entries.

```
index.js:1 redux-persist/createPersistoid: error serializing state TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'subdomains' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'Object'
    --- property 'parentDomain' closes the circle
    at JSON.stringify (<anonymous>)
    at defaultSerialize (createPersistoid.js:117)
    at processNextKey (createPersistoid.js:63)
```

### LINKED ISSUE #1546: Improve handling of semantic domain writing systems and translations
Currently, the list of all available languages for the semantic domain data is manually maintained within https://github.com/sillsdev/TheCombine/blob/master/src/components/TreeView/TreeViewComponent.tsx. Moreover, the translation datafile for every available language is imported, rather than just the one needed for the active project. This situation is probably not ideal once we support more languages in the project.

### LINKED ISSUE #1555: Semantic Domain Language Change doesn't update in the TreeView
**Describe the bug**

In Project Settings > Languages, if you set a language for the semantic domains, then go to data entry, the domains in TreeView should match the set language.

**To Reproduce**

1. Go to "Project Settings" and scroll down to the "Languages" section.
2. In "Semantic Domains", make a selection.
3. Go to Data Entry.
4. Confirm that the semantic domains are in the assigned language.
5. Return to "Project Settings" and scroll down to the "Languages" section.
6. In "Semantic Domains", select a different language.
7. Return to Data Entry.
8. Bug: The domains are still in the first language.

**Expected behavior**
8. The domains should be in the most recently selected language.

### PR DESCRIPTION
**Pull request by jasonleenaylor**
Fixes #664
Fixes #1555 
Resolves #1546 

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1565)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryComponent.tsx, line 154 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1565#-MwCtmIA8zDU0sjepp1G:-MwCtmIA8zDU0sjepp1H:b-d26s5g) ([raw file](https://github.com/sillsdev/thecombine/blob/03ddccb036ea396d8bbc067ab1674ef2ad072a1e/src/components/DataEntry/DataEntryComponent.tsx#L154)):*
> ```XML
>         />
> 
>         <Dialog fullScreen open={!!this.props.treeIsOpen}>
> ```

One example for the reason I am hesitant these kinds of terse implicit `bool` conversions: https://stackoverflow.com/questions/784929/what-is-the-not-not-operator-in-javascript#comment19202564_10597474

In this case, the `!!` is valid, but if we were to use it pervasively I think we could lead ourselves into a scenario where we lose type safety and bugs are easier to miss at compile time.

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/tests/spellChecker.test.ts, line 20 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1565#-MwCufxO0fvh9fIi3hrL:-MwCufxO0fvh9fIi3hrM:b-iv7ock) ([raw file](https://github.com/sillsdev/thecombine/blob/7808c3dcebc014081e1abe781d0cbcfb521ac1d3/src/components/DataEntry/tests/spellChecker.test.ts#L20)):*
> ```XML
>   });
> 
>   it("correctly detects a correctly spelled word", () => {
> ```

The grammar here is off now.

**Comment by johnthagen** [comment]
___
*[src/components/TreeView/TreeDepiction.tsx, line 150 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1565#-MwCw5uj9Fnr1MJENS-p:-MwCw5uj9Fnr1MJENS-q:b54xch) ([raw file](https://github.com/sillsdev/thecombine/blob/03ddccb036ea396d8bbc067ab1674ef2ad072a1e/src/components/TreeView/TreeDepiction.tsx#L150)):*
> ```XML
>     const childIds = this.props.currentDomain.childIds;
>     const subdomains: ReactElement[] = [];
>     for (let i = 0; i < childIds.length; i++) {
> ```

This could be written cleaner with:

```ts
    childIds.forEach((childId, i) => {
      
    });
```

**Comment by johnthagen** [comment]
___
*[src/components/TreeView/TreeViewActions.ts, line 44 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1565#-MwD-sKu8Gn0OwqsJatJ:-MwD-sKvA2pePMytH5pG:buafovp) ([raw file](https://github.com/sillsdev/thecombine/blob/03ddccb036ea396d8bbc067ab1674ef2ad072a1e/src/components/TreeView/TreeViewActions.ts#L44)):*
> ```XML
>   domainMap: DomainMap,
>   parentId?: string
> ) {
> ```

Add `: void`?

**Comment by johnthagen** [comment]
___
*[src/components/TreeView/TreeViewActions.ts, line 54 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1565#-MwD04rx9brQK-25GpXK:-MwD04rx9brQK-25GpXL:b-6l3he4) ([raw file](https://github.com/sillsdev/thecombine/blob/03ddccb036ea396d8bbc067ab1674ef2ad072a1e/src/components/TreeView/TreeViewActions.ts#L54)):*
> ```XML
> }
> 
> // Parses a list of semantic domains (to be loaded from file)
> ```

Make a doc comment?

**Comment by johnthagen** [comment]
___
*[src/components/TreeView/TreeViewComponent.tsx, line 64 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1565#-MwD4cgT-gu3wJoN27wn:-MwD4cgT-gu3wJoN27wo:byd2opj) ([raw file](https://github.com/sillsdev/thecombine/blob/03ddccb036ea396d8bbc067ab1674ef2ad072a1e/src/components/TreeView/TreeViewComponent.tsx#L64)):*
> ```XML
>       const headString = props.translate("addWords.domain") as string;
>       dispatch(updateTreeLanguage(newLang, headString));
>     } // eslint-disable-next-line react-hooks/exhaustive-deps
> ```

Add comment for why suppressing this is safe?

**Comment by johnthagen** [comment]
___
*[src/components/TreeView/TreeViewHeader.tsx, line 111 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1565#-MwD5kECCzT4tyjnA8GR:-MwD5kECCzT4tyjnA8GS:btwh1rz) ([raw file](https://github.com/sillsdev/thecombine/blob/03ddccb036ea396d8bbc067ab1674ef2ad072a1e/src/components/TreeView/TreeViewHeader.tsx#L111)):*
> ```XML
>           : event.key === Key.ArrowDown &&
>             props.currentDomain.childIds.length === 1
>           ? props.domainMap[props.currentDomain.childIds[0]]
> ```

This long chain is pretty challenging to follow. Is there a way we could use a `switch (event.key)` to possibly make this easier to follow?

**Comment by johnthagen** [comment]
___
*[src/components/TreeView/TreeViewHeader.tsx, line 113 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1565#-MwD6Pkx6gbWplZIrphD:-MwD6Pkx6gbWplZIrphE:b-ig5cx7) ([raw file](https://github.com/sillsdev/thecombine/blob/03ddccb036ea396d8bbc067ab1674ef2ad072a1e/src/components/TreeView/TreeViewHeader.tsx#L113)):*
> ```XML
>           ? props.domainMap[props.currentDomain.childIds[0]]
>           : undefined;
>       if (domain) {
> ```

Consider `domain !== undefined` for clarity?

**Comment by johnthagen** [comment]
___
*[src/components/TreeView/tests/TreeViewActions.test.tsx, line 32 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1565#-MwDEF7Z3eeX2qepOCwu:-MwDEF7_6TiByDKr8QKR:bmr9rtz) ([raw file](https://github.com/sillsdev/thecombine/blob/03ddccb036ea396d8bbc067ab1674ef2ad072a1e/src/components/TreeView/tests/TreeViewActions.test.tsx#L32)):*
> ```XML
>     const subdomains = [
>       new TreeSemanticDomain("Bar", "5.1") as any,
>       new TreeSemanticDomain("Baz", "5.2") as any,
> ```

Is it possible to avoid the use of `any` here?

**Review by johnthagen — COMMENTED** [review]
> Reviewed 25 of 25 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1565)* status: 16 of 25 files reviewed, 9 unresolved discussions (waiting on @jasonleenaylor and @johnthagen)

**Comment by johnthagen** [comment]
___
*[src/components/TreeView/TreeViewComponent.tsx, line 64 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1565#-MwD4cgT-gu3wJoN27wn:-MwDGKokCJkUjm3KD9jn:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/03ddccb036ea396d8bbc067ab1674ef2ad072a1e/src/components/TreeView/TreeViewComponent.tsx#L64)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Add comment for why suppressing this is safe?
</blockquote></details>

Done.

**Review by johnthagen — COMMENTED** [review]
> Reviewed 7 of 8 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1565)* status: all files reviewed, 4 unresolved discussions (waiting on @jasonleenaylor)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1565)* status: all files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor)

___
*[src/components/DataEntry/DataEntryComponent.tsx, line 154 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1565#-MwCtmIA8zDU0sjepp1G:-MwDUE6DEs-Y-3Fp7nAo:bcet8rd) ([raw file](https://github.com/sillsdev/thecombine/blob/03ddccb036ea396d8bbc067ab1674ef2ad072a1e/src/components/DataEntry/DataEntryComponent.tsx#L154)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

One example for the reason I am hesitant these kinds of terse implicit `bool` conversions: https://stackoverflow.com/questions/784929/what-is-the-not-not-operator-in-javascript#comment19202564_10597474

In this case, the `!!` is valid, but if we were to use it pervasively I think we could lead ourselves into a scenario where we lose type safety and bugs are easier to miss at compile time.
</blockquote></details>

We have `!!` a handful of other times in the code. It could be a new issue.
___
*[src/components/TreeView/TreeViewHeader.tsx, line 113 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1565#-MwD6Pkx6gbWplZIrphD:-MwDUSdOD6HSH691_vPT:bozo27) ([raw file](https://github.com/sillsdev/thecombine/blob/03ddccb036ea396d8bbc067ab1674ef2ad072a1e/src/components/TreeView/TreeViewHeader.tsx#L113)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Consider `domain !== undefined` for clarity?
</blockquote></details>

This sort of implicit checking is currently ubiquitous in the frontend.
___
*[src/components/TreeView/tests/TreeViewActions.test.tsx, line 32 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1565#-MwDEF7Z3eeX2qepOCwu:-MwDUsBN8cBZ1GZnfWr_:b-38nse5) ([raw file](https://github.com/sillsdev/thecombine/blob/03ddccb036ea396d8bbc067ab1674ef2ad072a1e/src/components/TreeView/tests/TreeViewActions.test.tsx#L32)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Is it possible to avoid the use of `any` here?
</blockquote></details>

That's to enable deleting the `childIds`.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1565)* status: 24 of 25 files reviewed, all discussions resolved (waiting on @jasonleenaylor and @johnthagen)

___
*[src/components/TreeView/TreeViewHeader.tsx, line 111 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1565#-MwD5kECCzT4tyjnA8GR:-MwDYk_L0HsEpHC3FSCF:b-b60m61) ([raw file](https://github.com/sillsdev/thecombine/blob/03ddccb036ea396d8bbc067ab1674ef2ad072a1e/src/components/TreeView/TreeViewHeader.tsx#L111)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This long chain is pretty challenging to follow. Is there a way we could use a `switch (event.key)` to possibly make this easier to follow?
</blockquote></details>

How's this look?

**Review by johnthagen — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1565)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jasonleenaylor)

**Pull request merged**
