### PR TITLE
Create a site admin user on Kubernetes deployments of The Combine

### LINKED ISSUE #345: Create administrative login on NUC targets
The playbooks that install the combine on the NUCs need to create an initial, known login with `sudo` privileges. Requirements:

1. `playbook_nuc.yml` shall create a login user, `admin`;
1. The admin user shall have the same password across all systems;
1. The admin password shall be encrypted in the github repo (e.g. stored in an Ansible vault variable or file)

### PR DESCRIPTION
**Pull request by jmgrady**
Add an Ansible playbook that will create the site admin user on Kubernetes deployments of _The Combine_.

The playbook performs the following steps:
1. Delete any old jobs to create the admin user
2. Create a secret with the username, password and email for the admin user
3. Create a job to run the backend with environment variables set to create the admin user
4. Wait for the job to complete
5. Delete the secret with the admin user values.

Note that the job is deleted automatically 5 minutes after it has terminated.

Closes #345

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1465)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 2 of 7 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1465)* status: 7 of 12 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

___
*[deploy/playbook_kube_admin_user.yml, line 18 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1465#-Mo-Cjmd78T2jFXXYtmK:-Mo-Cjmd78T2jFXXYtmL:bd56y51) ([raw file](https://github.com/sillsdev/thecombine/blob/a052b7a58745fb6ff0f5fbe4aab0746c54135b61/deploy/playbook_kube_admin_user.yml#L18)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>   vars_prompt:
>     - name: combine_version
>       prompt: "Enter Combine version to install"
>       private: no
> ```
</details>

Why is this needed in the `*_admin_user` if this is run after the install playbook, where `combine_version` has already been specified?
___
*[deploy/roles/k8s_admin_user/tasks/main.yml, line 7 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1465#-Mo-Av5t9zR03uR5IJkh:-Mo-Av5t9zR03uR5IJki:bx5e6z5) ([raw file](https://github.com/sillsdev/thecombine/blob/a052b7a58745fb6ff0f5fbe4aab0746c54135b61/deploy/roles/k8s_admin_user/tasks/main.yml#L7)):*
> ```
> #  - env-backend configmap
> ```
Missing "-" ?
___
*[docs/deploy/README.md, line 36 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1465#-Mo-C-LTDNXjUyg5Dynp:-Mo-C-LU-eK1lMe8yF6C:b6c398s) ([raw file](https://github.com/sillsdev/thecombine/blob/a052b7a58745fb6ff0f5fbe4aab0746c54135b61/docs/deploy/README.md#L36)):*
> ```
>          2. [Installing the Kubernetes Cluster](installing-the-kubernetes-cluster)
> ```
Missing # at the start of the link.

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1465)* status: 7 of 13 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[deploy/roles/k8s_admin_user/tasks/main.yml, line 7 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1465#-Mo-Av5t9zR03uR5IJkh:-Mo-MA9jBQXEUz18qebX:b-ie513n) ([raw file](https://github.com/sillsdev/thecombine/blob/a052b7a58745fb6ff0f5fbe4aab0746c54135b61/deploy/roles/k8s_admin_user/tasks/main.yml#L7)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> #  - env-backend configmap
> ```
Missing "-" ?
</blockquote></details>

No, the resource is called `env-backend`:
```
grady@saaz:~$ kubectl -n thecombine get configmaps
NAME               DATA   AGE
aws-ecr-config     3      69d
env-backend        5      69d
env-frontend       7      69d
env-maintenance    7      69d
init-nginx-pages   4      25d
kube-root-ca.crt   1      70d
```
Would it be more helpful if the Kubernetes resource "Kind" was used?  That is, 
```
#  - env-backend ConfigMap
```
___
*[docs/deploy/README.md, line 36 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1465#-Mo-C-LTDNXjUyg5Dynp:-Mo-OWl54weqjxF9_UFm:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/a052b7a58745fb6ff0f5fbe4aab0746c54135b61/docs/deploy/README.md#L36)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>          2. [Installing the Kubernetes Cluster](installing-the-kubernetes-cluster)
> ```
Missing # at the start of the link.
</blockquote></details>

Done.
___
*[deploy/playbook_kube_admin_user.yml, line 18 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1465#-Mo-Cjmd78T2jFXXYtmK:-Mo-Fxde6DvhN0iOd2sE:b8ndugp) ([raw file](https://github.com/sillsdev/thecombine/blob/a052b7a58745fb6ff0f5fbe4aab0746c54135b61/deploy/playbook_kube_admin_user.yml#L18)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>   vars_prompt:
>     - name: combine_version
>       prompt: "Enter Combine version to install"
>       private: no
> ```
Why is this needed in the `*_admin_user` if this is run after the install playbook, where `combine_version` has already been specified?
</blockquote></details>

This is because the `combine_version` variable does not live past the previous playbook.
I will make this part of the `*_config` playbook.  Since it does not need to shut down the `backend` service, it does not interfere with _The Combine_ to just run it instead of only running it conditionally.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 2 of 7 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1465)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[deploy/roles/k8s_admin_user/tasks/main.yml, line 7 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1465#-Mo-Av5t9zR03uR5IJkh:-Mo-m39x5bW_SIc3rBNO:b-5w0et1) ([raw file](https://github.com/sillsdev/thecombine/blob/a052b7a58745fb6ff0f5fbe4aab0746c54135b61/deploy/roles/k8s_admin_user/tasks/main.yml#L7)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

No, the resource is called `env-backend`:
```
grady@saaz:~$ kubectl -n thecombine get configmaps
NAME               DATA   AGE
aws-ecr-config     3      69d
env-backend        5      69d
env-frontend       7      69d
env-maintenance    7      69d
init-nginx-pages   4      25d
kube-root-ca.crt   1      70d
```
Would it be more helpful if the Kubernetes resource "Kind" was used?  That is, 
```
#  - env-backend ConfigMap
```
</blockquote></details>

Ah, I saw a file `env-backend-configmap.yaml` and assumed it was referring to something like that. Whichever capitalization is more accurate.
___
*[deploy/roles/k8s_admin_user/templates/job-create-admin-user.yaml.j2, line 19 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1465#-Mo-nNUE6q_tFvm_MxXv:-Mo-nNUE6q_tFvm_MxXw:b-yw1vrw) ([raw file](https://github.com/sillsdev/thecombine/blob/1f58ebac291fadb369f358644a85eaf9f050a0d3/deploy/roles/k8s_admin_user/templates/job-create-admin-user.yaml.j2#L19)):*
> ```
>       imagePullSecrets:
>          - name: {{ image_pull_secret }}
> ```
There appears to be an extra space in the indent before `- name`.
___
*[deploy/roles/k8s_admin_user/templates/job-create-admin-user.yaml.j2, line 45 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1465#-Mo-ngPq2kTkURbJF_yQ:-Mo-ngPq2kTkURbJF_yR:b-duc9th) ([raw file](https://github.com/sillsdev/thecombine/blob/1f58ebac291fadb369f358644a85eaf9f050a0d3/deploy/roles/k8s_admin_user/templates/job-create-admin-user.yaml.j2#L45)):*
> ```
>           image: '{{ combine_image_backend }}'
> ```
Why are there quotes around this one?

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1465)* status: 11 of 13 files reviewed, all discussions resolved (waiting on @imnasnainaec and @jmgrady)

___
*[deploy/roles/k8s_admin_user/tasks/main.yml, line 7 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1465#-Mo-Av5t9zR03uR5IJkh:-Mo0IHs0C95dSUFgTR1n:b-sghupv) ([raw file](https://github.com/sillsdev/thecombine/blob/a052b7a58745fb6ff0f5fbe4aab0746c54135b61/deploy/roles/k8s_admin_user/tasks/main.yml#L7)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Ah, I saw a file `env-backend-configmap.yaml` and assumed it was referring to something like that. Whichever capitalization is more accurate.
</blockquote></details>

Done.
I changed it to list the resources the way Kubenetes sees them:
```
#  - deployment/database
#  - service/database
#  - configmap/env-backend
#  - secret/env-backend-secrets
```
I did not list the database `pod` as I had earlier because it is created as part of creating the deployment.  In addition, it's name is not known a priori - it will be `database-` followed by a 15 character hash, e.g. `database-794b4d956f-wnsx7`.
___
*[deploy/roles/k8s_admin_user/templates/job-create-admin-user.yaml.j2, line 19 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1465#-Mo-nNUE6q_tFvm_MxXv:-Mo0JX3Y9HgPs7h2x27X:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/a7182e0fe5a2fbfadf79358e213d3ed6b87b01a2/deploy/roles/k8s_admin_user/templates/job-create-admin-user.yaml.j2#L19)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>       imagePullSecrets:
>          - name: {{ image_pull_secret }}
> ```
There appears to be an extra space in the indent before `- name`.
</blockquote></details>

Done.
___
*[deploy/roles/k8s_admin_user/templates/job-create-admin-user.yaml.j2, line 45 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1465#-Mo-ngPq2kTkURbJF_yQ:-Mo0JacP9EMbXApudZk5:b-ebmacp) ([raw file](https://github.com/sillsdev/thecombine/blob/a7182e0fe5a2fbfadf79358e213d3ed6b87b01a2/deploy/roles/k8s_admin_user/templates/job-create-admin-user.yaml.j2#L45)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>           image: '{{ combine_image_backend }}'
> ```
Why are there quotes around this one?
</blockquote></details>

Done.
This is a Jinja 2 template so there shouldn't be quotes here.  The Ansible YAML requires quotes if the string value starts with a variable lookup.  Force of habit, I suppose.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1465)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Pull request merged**
