### PR TITLE
Get AWS ECR Credentials

### PR DESCRIPTION
**Pull request by jmgrady**
Get AWS ECR Credentials so that Kubernetes can pull images from the private AWS Elastic Container Registry.  This PR adds an additional role, `aws_login_job`, that creates a Kubernetes Job to create an image pull secret that can be used to fetch the required images.  The method will optionally create a CronJob in addition to the one-time Job so that the pull secret is refreshed before it expires.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1278)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 38 of 45 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1278)* status: 38 of 45 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

___
*[deploy/roles/aws_login_job/templates/aws-ecr-login-cronjob.yaml.j2, line 6 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1278#-MgCDtojCoVGWxZyiTVZ:-MgCDtojCoVGWxZyiTV_:b-otkz5l) ([raw file](https://github.com/sillsdev/thecombine/blob/f1b0d5b3703d046bc416eb7a0caa60f6a9dfae6b/deploy/roles/aws_login_job/templates/aws-ecr-login-cronjob.yaml.j2#L6)):*
> ```
>   annotations:
>   name: "{{ aws_ecr_login.cron_job_name }}"
>   namespace: {{ app_namespace }}
> ```
Is `annotations` empty, or are the next two lines missing indents?
___
*[deploy/roles/aws_login_job/templates/aws-ecr-login-oneshot.yaml.j2, line 6 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1278#-MgCE2OU0GeV5ASGl69B:-MgCE2OW6H6vtIilujw1:b-5ndude) ([raw file](https://github.com/sillsdev/thecombine/blob/f1b0d5b3703d046bc416eb7a0caa60f6a9dfae6b/deploy/roles/aws_login_job/templates/aws-ecr-login-oneshot.yaml.j2#L6)):*
> ```
>   annotations:
>   name: "{{ aws_ecr_login.job_name }}"
>   namespace: {{ app_namespace }}
> ```
Is `annotations` empty, or are the next two lines missing indents?
___
*[deploy/roles/k8s_config/defaults/main.yml, line 37 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1278#-MgCDCjQ9Krulxp-deTe:-MgCDCjQ9Krulxp-deTf:bigi0m) ([raw file](https://github.com/sillsdev/thecombine/blob/f1b0d5b3703d046bc416eb7a0caa60f6a9dfae6b/deploy/roles/k8s_config/defaults/main.yml#L37)):*
> ```YAML
> ingress_class: nginx
> 
> test_var: overridden
> ```

What's the `test_var` for?
___
*[deploy/roles/k8s_config/tasks/main.yml, line 28 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1278#-MgCBUGw6JDxulrN_icL:-MgCBUGx-vPVMRXFer38:by34r9w) ([raw file](https://github.com/sillsdev/thecombine/blob/24031682f103e15d8e13148c09defaa96467f6ba/deploy/roles/k8s_config/tasks/main.yml#L28)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>   with_fileglob:
>     - "templates/*.yaml.j2"
> ...
>   with_items: "{{ kube_config.files | sort(attribute='path') }}"
> ```
</details>

You've replaced these with long, explicit lists. Do we no longer have any "use all files in this directory" options available?

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1278)* status: 38 of 45 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

___
*[deploy/roles/aws_login_job/templates/aws-ecr-login-cronjob.yaml.j2, line 6 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1278#-MgCDtojCoVGWxZyiTVZ:-MgCPhUL3N8JTbYVouUe:b-gj7bye) ([raw file](https://github.com/sillsdev/thecombine/blob/f1b0d5b3703d046bc416eb7a0caa60f6a9dfae6b/deploy/roles/aws_login_job/templates/aws-ecr-login-cronjob.yaml.j2#L6)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>   annotations:
>   name: "{{ aws_ecr_login.cron_job_name }}"
>   namespace: {{ app_namespace }}
> ```
Is `annotations` empty, or are the next two lines missing indents?
</blockquote></details>

It is empty and has been removed.
___
*[deploy/roles/aws_login_job/templates/aws-ecr-login-oneshot.yaml.j2, line 6 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1278#-MgCE2OU0GeV5ASGl69B:-MgCQlHC53a0V_uT8O2b:b-gj7bye) ([raw file](https://github.com/sillsdev/thecombine/blob/f1b0d5b3703d046bc416eb7a0caa60f6a9dfae6b/deploy/roles/aws_login_job/templates/aws-ecr-login-oneshot.yaml.j2#L6)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>   annotations:
>   name: "{{ aws_ecr_login.job_name }}"
>   namespace: {{ app_namespace }}
> ```
Is `annotations` empty, or are the next two lines missing indents?
</blockquote></details>

It is empty and has been removed.
___
*[deploy/roles/k8s_config/defaults/main.yml, line 37 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1278#-MgCDCjQ9Krulxp-deTe:-MgCQmbwEsPvo3r0CM9Y:bkewb9e) ([raw file](https://github.com/sillsdev/thecombine/blob/f1b0d5b3703d046bc416eb7a0caa60f6a9dfae6b/deploy/roles/k8s_config/defaults/main.yml#L37)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

What's the `test_var` for?
</blockquote></details>

It is an error.  It should have been removed after the test.
___
*[deploy/roles/k8s_config/tasks/main.yml, line 28 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1278#-MgCBUGw6JDxulrN_icL:-MgCR-wy99bT82nPzEL1:b3teu1y) ([raw file](https://github.com/sillsdev/thecombine/blob/24031682f103e15d8e13148c09defaa96467f6ba/deploy/roles/k8s_config/tasks/main.yml#L28)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>   with_fileglob:
>     - "templates/*.yaml.j2"
> ...
>   with_items: "{{ kube_config.files | sort(attribute='path') }}"
> ```
You've replaced these with long, explicit lists. Do we no longer have any "use all files in this directory" options available?
</blockquote></details>

That is correct.  This was done to make the behavior more deterministic.  I could have added a step to clean out the directory at the beginning of each role but it is useful to be able to see which items have changed when reviewing the output of Ansible.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 45 files at r1, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1278)* status: 40 of 45 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[deploy/roles/aws_login_job/tasks/main.yml, line 42 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1278#-MgGsVBB6K50zfkxuCzU:-MgGsVBB6K50zfkxuCzV:b1zvxx9) ([raw file](https://github.com/sillsdev/thecombine/blob/4ebc768d499b275a8a9034df6dfa1bf92e797dd9/deploy/roles/aws_login_job/tasks/main.yml#L42)):*
> ```
> # - Cron job iff aws_ecr_login.cron is true
> ```
I find this a confusing way to describe `aws-ecr-login-cronjob.yaml`, since we don't actually see the conditional until the next section. It looks like that file is copied whether or not it will be used.
___
*[deploy/roles/aws_login_job/templates/aws-ecr-login-oneshot.yaml.j2, line 67 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1278#-MgGrwxS8wThBOEhBxf-:-MgGrwxS8wThBOEhBxf0:bsmbwvt) ([raw file](https://github.com/sillsdev/thecombine/blob/4ebc768d499b275a8a9034df6dfa1bf92e797dd9/deploy/roles/aws_login_job/templates/aws-ecr-login-oneshot.yaml.j2#L67)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>         resources: {}
>         securityContext:
>           capabilities: {}
> ...
>       securityContext: {}
> ```
</details>

Are these empty set declarations to satisfy required arguments, override non-empty defaults, or place-hold for potential future content?
___
*[deploy/roles/k8s_config/tasks/main.yml, line 29 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1278#-MgGojYuBOCV1ASG7XqS:-MgGojYuBOCV1ASG7XqT:bs56m1o) ([raw file](https://github.com/sillsdev/thecombine/blob/4ebc768d499b275a8a9034df6dfa1bf92e797dd9/deploy/roles/k8s_config/tasks/main.yml#L29)):*
> ```
> 60-nginx-ingress-service.yaml"
> ```
It looked like you had been removing the decade prefixes for `k8s` templates, but this reference has `60-`.

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1278)* status: 40 of 45 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[deploy/roles/aws_login_job/tasks/main.yml, line 42 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1278#-MgGsVBB6K50zfkxuCzU:-MgGuSDm3N411jWjgXjA:bsheog1) ([raw file](https://github.com/sillsdev/thecombine/blob/4ebc768d499b275a8a9034df6dfa1bf92e797dd9/deploy/roles/aws_login_job/tasks/main.yml#L42)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> # - Cron job iff aws_ecr_login.cron is true
> ```
I find this a confusing way to describe `aws-ecr-login-cronjob.yaml`, since we don't actually see the conditional until the next section. It looks like that file is copied whether or not it will be used.
</blockquote></details>

Agreed.  I have removed this part of the comment since its intent is described in the next section.
___
*[deploy/roles/aws_login_job/templates/aws-ecr-login-oneshot.yaml.j2, line 67 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1278#-MgGrwxS8wThBOEhBxf-:-MgH1LZP-NoycB1-koWc:bexbwp7) ([raw file](https://github.com/sillsdev/thecombine/blob/4ebc768d499b275a8a9034df6dfa1bf92e797dd9/deploy/roles/aws_login_job/templates/aws-ecr-login-oneshot.yaml.j2#L67)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>         resources: {}
>         securityContext:
>           capabilities: {}
> ...
>       securityContext: {}
> ```
Are these empty set declarations to satisfy required arguments, override non-empty defaults, or place-hold for potential future content?
</blockquote></details>

The one-shot and cron jobs were leveraged from https://medium.com/@damitj07/how-to-configure-and-use-aws-ecr-with-kubernetes-rancher2-0-6144c626d42c which had the empty specifications.  According to the api definition these default to empty so I have removed the redundant specification (for this and for the cron job).
___
*[deploy/roles/k8s_config/tasks/main.yml, line 29 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1278#-MgGojYuBOCV1ASG7XqS:-MgH2cHq2pjbUAtiPfGu:b-h21o18) ([raw file](https://github.com/sillsdev/thecombine/blob/4ebc768d499b275a8a9034df6dfa1bf92e797dd9/deploy/roles/k8s_config/tasks/main.yml#L29)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> 60-nginx-ingress-service.yaml"
> ```
It looked like you had been removing the decade prefixes for `k8s` templates, but this reference has `60-`.
</blockquote></details>

This task is now removed.  The setup of the NGINX Ingress service has been moved to the k8s_install role and this was a task that should have been removed then.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1278)* status: 42 of 45 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[deploy/roles/aws_login_job/templates/aws-ecr-login-cronjob.yaml.j2, line 39 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1278#-MgHXGjD--dVVQmnhVqD:-MgHXGjD--dVVQmnhVqE:b-x8txt1) ([raw file](https://github.com/sillsdev/thecombine/blob/5f3fbebd1cb82c2b334a0b44273500a693fac051/deploy/roles/aws_login_job/templates/aws-ecr-login-cronjob.yaml.j2#L39)):*
> ```Jinja
>               --docker-email="{{ combine_admin_email }}"
>               echo "Secret created by name. $SECRET_NAME"
>               kubectl -n {{ app_namespace}} patch serviceaccount default -p '{"imagePullSecrets":[{"name":"'$SECRET_NAME'"}]}'   # custom script | update the deafult servciee account
> ```

Typo: `servciee`.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1278)* status: 42 of 45 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[deploy/roles/aws_login_job/templates/aws-ecr-login-oneshot.yaml.j2, line 35 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1278#-MgHYq1X07rTecAV2YrY:-MgHYq1YDEo0WCXqFqyE:b3au0fw) ([raw file](https://github.com/sillsdev/thecombine/blob/5f3fbebd1cb82c2b334a0b44273500a693fac051/deploy/roles/aws_login_job/templates/aws-ecr-login-oneshot.yaml.j2#L35)):*
> ```
>           echo "Current user: "`whoami`
>           echo "Home Directory: ${HOME}"
> ```
I don't see these in `-cronjob.yaml`. Leftover from testing?

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1278)* status: 44 of 45 files reviewed, all discussions resolved (waiting on @jmgrady)

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1278)* status: 42 of 45 files reviewed, all discussions resolved (waiting on @imnasnainaec and @jmgrady)

___
*[deploy/roles/aws_login_job/tasks/main.yml, line 42 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1278#-MgGsVBB6K50zfkxuCzU:-MgHeqI01rmYlhi44-lL:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/4ebc768d499b275a8a9034df6dfa1bf92e797dd9/deploy/roles/aws_login_job/tasks/main.yml#L42)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

But now is`aws-ecr-login-cronjob.yaml` still supposed to be included in the `with_items`s of this section when it is conditionally covered in the next?
</blockquote></details>

Done
___
*[deploy/roles/aws_login_job/templates/aws-ecr-login-cronjob.yaml.j2, line 39 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1278#-MgHXGjD--dVVQmnhVqD:-MgHfO3d7bYg9bnqLY27:blf0n2c) ([raw file](https://github.com/sillsdev/thecombine/blob/5f3fbebd1cb82c2b334a0b44273500a693fac051/deploy/roles/aws_login_job/templates/aws-ecr-login-cronjob.yaml.j2#L39)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Typo: `servciee`.
</blockquote></details>

deafult is wrong too.  Both fixed.
___
*[deploy/roles/aws_login_job/templates/aws-ecr-login-oneshot.yaml.j2, line 35 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1278#-MgHYq1X07rTecAV2YrY:-MgHeuWi6krK75YUVo0a:b-rchc8s) ([raw file](https://github.com/sillsdev/thecombine/blob/5f3fbebd1cb82c2b334a0b44273500a693fac051/deploy/roles/aws_login_job/templates/aws-ecr-login-oneshot.yaml.j2#L35)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>           echo "Current user: "`whoami`
>           echo "Home Directory: ${HOME}"
> ```
I don't see these in `-cronjob.yaml`. Leftover from testing?
</blockquote></details>

Yes.  Removed now.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1278)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Pull request merged**
