### PR TITLE
Add NUC instance

### PR DESCRIPTION
**Pull request by jmgrady**
Add definitions for a third NUC to be setup, `nuc3`.  The NUCs are managed in this way because the production server needs to manage the creation of TLS certificates for each of the NUCs we support.

In addition, this PR adds the following enhancements:

- `aws-login` processes are no longer setup for the production server nor the NUCs; these servers only run images released to the public image repository
- Updates the public image repository alias to `public.ecr.aws/thecombine`
- Update instructions for installing Ubuntu Server

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1678)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 11 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1678)* status: 11 of 13 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

___
*[`docs/deploy/README.md` line 180 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1678#-N5p-6pN-pMRvpQDRA7y:-N5p-6pN-pMRvpQDRA7z:b5e9091) ([raw file](https://github.com/sillsdev/thecombine/blob/7b58c7256a0afba1747bb323635eae542082dcce/docs/deploy/README.md#L180)):*
> ```Markdown
> 
> 4. Set the KUBECONFIG environment variable to the location of the `kubectl` configuration file. (This is not necessary
>    if the configuration file is at `\${HOME}/.kube/config.)
> ```

\`\\${HOME}/.kube/config has an initial \` but not a final \`



_Code quote:_
```Markdown
`\${HOME}/.kube/config
```
___
*[`docs/deploy/README.md` line 324 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1678#-N5p05fcCgzI2svKSeUb:-N5p05fcCgzI2svKSeUc:bgyze6b) ([raw file](https://github.com/sillsdev/thecombine/blob/7b58c7256a0afba1747bb323635eae542082dcce/docs/deploy/README.md#L324)):*
> ```Markdown
> 7. _[Host]_ Add the NUC to your /etc/hosts:
> 
>    From the NUC, run the command `ip address` to see the current IP address of the NUC. Then edit `/etc/hosts` on your
> ```

Since this is a \_[Host]_ step, the NUC IP instruction should possibly be inserted as its own \_[NUC]_ step first.



_Code quote:_
```Markdown
   From the NUC, run the command `ip address` to see the current IP address of the NUC.
```

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1678)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1678)* status: 12 of 13 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[`docs/deploy/README.md` line 180 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1678#-N5p-6pN-pMRvpQDRA7y:-N5pw0Lb2QF53EY9yPTb:b-5n4uwx) ([raw file](https://github.com/sillsdev/thecombine/blob/7b58c7256a0afba1747bb323635eae542082dcce/docs/deploy/README.md#L180)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

What is the \ for here?
</blockquote></details>

Haste made waste.  Fixed.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1678)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Pull request merged**
