### PR TITLE
Accounts and settings: bug fixes and User Guide fill-in.

### LINKED ISSUE #888: [UserSettings] Users can change email address to one already in use.
Email addresses are used for password reset, so they need to be unique.

Also, there is no user feedback to whether SAVE was successful.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Fill in content for Account, Project, and Admin pages in the User Guide.
[SiteSettings] Disallow admins deleting other admins (part of #544).
[AvatarUpload] Allow any image type, not just `.jpg`.
[UserSettings] Add feedback on `SAVE`, and don't allow saving with taken email address (resolves #888; more to do in #894).

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/889)

### CODE REVIEW

**Comment by imnasnainaec** [comment]
Screenshots of the User Guide content:
Screen Shot 2020-12-22 at 14 49 18
Screen Shot 2020-12-22 at 14 48 57

**Comment by johnthagen** [comment]
___
*[src/components/SiteSettings/UserManagment/UserList.tsx, line 36 at r2](https://reviewable.io/reviews/sillsdev/thecombine/889#-MPsxUVU5qQoTkzyFBds:-MPsxUVVDVXzd9c4NvMf:b-34uwmq) ([raw file](https://github.com/sillsdev/thecombine/blob/1347ffa6402b098a2ff1729203f11fba18fb0d79/src/components/SiteSettings/UserManagment/UserList.tsx#L36)):*
> ```XML
> }
> 
> class UserList extends React.Component<
> ```

I realize this is a little out of scope for this PR, but could this component be converted to a functional component?

**Comment by johnthagen** [comment]
___
*[src/components/UserSettings/AvatarUpload.tsx, line 61 at r2](https://reviewable.io/reviews/sillsdev/thecombine/889#-MPsyOUB5_bpFGgnKm63:-MPsyOUB5_bpFGgnKm64:b-y49376) ([raw file](https://github.com/sillsdev/thecombine/blob/1347ffa6402b098a2ff1729203f11fba18fb0d79/src/components/UserSettings/AvatarUpload.tsx#L61)):*
> ```XML
>           <FileInputButton
>             updateFile={(file) => updateFile(file)}
>             accept="image/*"
> ```

This was a good change.

**Comment by johnthagen** [comment]
___
*[src/components/UserSettings/UserSettings.tsx, line 144 at r2](https://reviewable.io/reviews/sillsdev/thecombine/889#-MPsykK59ikxA9S7zTw_:-MPsykK64r1gxqznJf96:byqtrtz) ([raw file](https://github.com/sillsdev/thecombine/blob/1347ffa6402b098a2ff1729203f11fba18fb0d79/src/components/UserSettings/UserSettings.tsx#L144)):*
> ```XML
>       });
>     } else {
>       alert(this.props.translate("login.emailTaken"));
> ```

I don't think this is bad per se, but during registration when a username or email is already taken, it highlights the input box red and puts the error in red. In general, I think this is a better UI than alerts because it draws your attention immediately to the incorrect data location.

Can we do something like that in the User Settings?

**Comment by johnthagen** [comment]
___
*[src/resources/translations.json, line 270 at r2](https://reviewable.io/reviews/sillsdev/thecombine/889#-MPszJli9ohrDzANOEj8:-MPszJli9ohrDzANOEj9:b-vxkrct) ([raw file](https://github.com/sillsdev/thecombine/blob/1347ffa6402b098a2ff1729203f11fba18fb0d79/src/resources/translations.json#L270)):*
> ```JSON
>     "updateSuccess": [
>       "Settings successfully updated.",
>       "Settings successfully updated.",
> ```

I see many of the strings in this file aren't translated yet, but should we translate new one like this when we add them?

**Comment by johnthagen** [comment]
___
*[user_guide/docs/account.md, line 22 at r2](https://reviewable.io/reviews/sillsdev/thecombine/889#-MPszZLJAPaBNvqWuLgv:-MPszZLJAPaBNvqWuLgw:b-zdvt4q) ([raw file](https://github.com/sillsdev/thecombine/blob/1347ffa6402b098a2ff1729203f11fba18fb0d79/user_guide/docs/account.md#L22)):*
> ```Markdown
> will be sent to the email address associated with your account.
> 
> !!! note
> ```

I'd maybe choose the "important" admonition for this one.

**Comment by johnthagen** [comment]
___
*[user_guide/docs/admin.md, line 10 at r2](https://reviewable.io/reviews/sillsdev/thecombine/889#-MPszqQZ9Z4QA6OC6DwF:-MPszqQZ9Z4QA6OC6DwG:b-pt9e0r) ([raw file](https://github.com/sillsdev/thecombine/blob/1347ffa6402b098a2ff1729203f11fba18fb0d79/user_guide/docs/admin.md#L10)):*
> ```Markdown
> 
> Administrators can export or archive/restore any project. Archiving a project makes it invisible and unaccessible to all
> users, even the project creator, but any admin can restore the project.
> ```

Should we add a note stating explicitly that there is currently no way to permanently delete projects? Someone might want to know that if they were just trying it out and uploaded something they didn't mean to.

**Comment by johnthagen** [comment]
___
*[user_guide/docs/project.md, line 20 at r2](https://reviewable.io/reviews/sillsdev/thecombine/889#-MPt-Bc94i7aXOlmFNm_:-MPt-Bc94i7aXOlmFNma:b729k7k) ([raw file](https://github.com/sillsdev/thecombine/blob/1347ffa6402b098a2ff1729203f11fba18fb0d79/user_guide/docs/project.md#L20)):*
> ```Markdown
> 
> If you have linguistics data in a [LIFT](https://software.sil.org/lifttools) file (likely exported from The Combine,
> WeSay, FLEx, or Lexique Pro), you can hit the BROWSE button next to "Upload .zip project file?" to import the data into
> ```

I like that we are adding web links out to other linguistic/SIL tools, could we add links for WeSay, FLEx, and Lexique Pro?

**Review by johnthagen — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/889)* status: all files reviewed, 7 unresolved discussions (waiting on @imnasnainaec and @jasonleenaylor)

**Comment by johnthagen** [comment]
- Disallow admins deleting other admins
- don't allow saving with taken email address

Fundamentally, I believe we need to enforce this in the backend, not just in the frontend. If someone connects to our API from a client other than our frontend, they could corrupt our database.

- `UserController.Delete` or `UserApiServices.Delete` (not sure where best appropriate) I believe should be updated to enforce that admin users cannot be deleted
- I think that `UserService.Update` needs to be updated to enforce that an email address is not updated to one that already exists

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/889)* status: 9 of 12 files reviewed, 4 unresolved discussions (waiting on @imnasnainaec, @jasonleenaylor, and @johnthagen)

___
*[src/components/SiteSettings/UserManagment/UserList.tsx, line 36 at r2](https://reviewable.io/reviews/sillsdev/thecombine/889#-MPsxUVU5qQoTkzyFBds:-MPtRW6i56qsReQve2e2:bihq3ho) ([raw file](https://github.com/sillsdev/thecombine/blob/1347ffa6402b098a2ff1729203f11fba18fb0d79/src/components/SiteSettings/UserManagment/UserList.tsx#L36)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I realize this is a little out of scope for this PR, but could this component be converted to a functional component?
</blockquote></details>

The conversion of `componentDidUpdate` and `handleChange` may be nontrivial, so that's better for another pr.
___
*[src/resources/translations.json, line 270 at r2](https://reviewable.io/reviews/sillsdev/thecombine/889#-MPszJli9ohrDzANOEj8:-MPtRhMr2VycXteSv6u-:by63niy) ([raw file](https://github.com/sillsdev/thecombine/blob/1347ffa6402b098a2ff1729203f11fba18fb0d79/src/resources/translations.json#L270)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I see many of the strings in this file aren't translated yet, but should we translate new one like this when we add them?
</blockquote></details>

No, the translation process is to be done in Crowdin--Jason and I have that process mostly setup.
___
*[user_guide/docs/account.md, line 22 at r2](https://reviewable.io/reviews/sillsdev/thecombine/889#-MPszZLJAPaBNvqWuLgv:-MPtT7l_8O18XNbH_98H:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/1347ffa6402b098a2ff1729203f11fba18fb0d79/user_guide/docs/account.md#L22)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I'd maybe choose the "important" admonition for this one.
</blockquote></details>

Done.
___
*[user_guide/docs/admin.md, line 10 at r2](https://reviewable.io/reviews/sillsdev/thecombine/889#-MPszqQZ9Z4QA6OC6DwF:-MPtT4Z7D7DVdS0KylBU:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/1347ffa6402b098a2ff1729203f11fba18fb0d79/user_guide/docs/admin.md#L10)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Should we add a note stating explicitly that there is currently no way to permanently delete projects? Someone might want to know that if they were just trying it out and uploaded something they didn't mean to.
</blockquote></details>

Done.
___
*[user_guide/docs/project.md, line 20 at r2](https://reviewable.io/reviews/sillsdev/thecombine/889#-MPt-Bc94i7aXOlmFNm_:-MPtT1ImDddBl6HEN0n2:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/1347ffa6402b098a2ff1729203f11fba18fb0d79/user_guide/docs/project.md#L20)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I like that we are adding web links out to other linguistic/SIL tools, could we add links for WeSay, FLEx, and Lexique Pro?
</blockquote></details>

Done.

**Comment by johnthagen** [comment]
___
*[src/resources/translations.json, line 270 at r2](https://reviewable.io/reviews/sillsdev/thecombine/889#-MPszJli9ohrDzANOEj8:-MPtTjLL4mI-YqwJ-yeg:b-cpuqzi) ([raw file](https://github.com/sillsdev/thecombine/blob/1347ffa6402b098a2ff1729203f11fba18fb0d79/src/resources/translations.json#L270)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

No, the translation process is to be done in Crowdin--Jason and I have that process mostly setup.
</blockquote></details>

LGTM.

So are these extra strings redundant now?

**Review by johnthagen — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/889)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jasonleenaylor)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/889)* status: all files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor and @johnthagen)

___
*[src/components/UserSettings/UserSettings.tsx, line 144 at r2](https://reviewable.io/reviews/sillsdev/thecombine/889#-MPsykK59ikxA9S7zTw_:-MPtUmZB1J4DTuElixYJ:b-817jgz) ([raw file](https://github.com/sillsdev/thecombine/blob/1347ffa6402b098a2ff1729203f11fba18fb0d79/src/components/UserSettings/UserSettings.tsx#L144)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I don't think this is bad per se, but during registration when a username or email is already taken, it highlights the input box red and puts the error in red. In general, I think this is a better UI than alerts because it draws your attention immediately to the incorrect data location.

Can we do something like that in the User Settings?
</blockquote></details>

https://github.com/sillsdev/TheCombine/issues/894
___
*[src/resources/translations.json, line 270 at r2](https://reviewable.io/reviews/sillsdev/thecombine/889#-MPszJli9ohrDzANOEj8:-MPtUpTv8wYOTNpRtWdM:b-78zur1) ([raw file](https://github.com/sillsdev/thecombine/blob/1347ffa6402b098a2ff1729203f11fba18fb0d79/src/resources/translations.json#L270)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

LGTM.

So are these extra strings redundant now?
</blockquote></details>

They serve as placeholders, so that a non-English user at least gets the English phrase if it hasn't been translated yet.

**Review by johnthagen — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/889)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jasonleenaylor)

**Pull request merged**
