### PR TITLE
Add edit-version of PronunciationsCell

### LINKED ISSUE #1556: [ReviewEntries] Add/remove audio bumps out of row edit mode and loses changes
**Describe the bug**

In ReviewEntires, when editing a row/entry, if you record new audio or delete existing audio, it refreshes that entry, taking the row out of edit mode and losing any unsaved changes.

**To Reproduce**

1. Click on Data Cleanup > Review Entries
2. Click on the edit button at the left end of one of the rows to enable edit mode on that entry
  (If there are no entries, go to Data Entry and create one.)
3. Change the vernacular on the current entry
4. Add a recording for that entry
5. Observe the entry exiting edit mode and the vernacular reverting

**Expected behavior**

5. The entry should stay in edit mode, with the updated vernacular still updated but unsaved.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #1556 (but not #2616)

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2615)

### CODE REVIEW

**Comment by imnasnainaec** [comment]
Need to add PronunciationCell tests.

**Review by jasonleenaylor — APPROVED** [review]
:lgtm:

> Reviewed 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2615#-:-NfD6_zS9ZdLiOKG7YkN:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2615)* status: all files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor)

___
*[`src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/PronunciationsCell.tsx` line 29 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2615#-NfCFB53BYr3qQURMqEh:-NfD7DuW2H20jetgmFe_:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/d6e3891f088afce888cfacfc6fd65c1a0f74b0c7/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/PronunciationsCell.tsx#L29)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

This might be a little too clever... and spacer definitely seems like an inadequate name for what is going on here.
Skipping the record button in the inner Pronunciations by not passing `uploadAudio` wasn't easy for me to see. 
I think we might need to discuss this and other possible design options.
</blockquote></details>

Done.

**Review by jasonleenaylor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2615)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
