### PR TITLE
Allow developers to opt in to segment.com analytics

### LINKED ISSUE #1237: Investigate possible issue in identifying users for analytics
The analytics library is supposed to identify users after they login so that we track all a users activity to an account. This should even identify the same user if they login from multiple computers. Looking at the data that we are getting I suspect something in this is not working properly.

image

There are large clusters of users in several cities that look suspicious.

### PR DESCRIPTION
**Pull request by johnthagen**
Closes #1237 

Follow on to  #1108

## TODO

Generate two new segment.com keys and put them here:

- [x] QA 
https://github.com/sillsdev/TheCombine/blob/9a69089401205385720e136c0ef950b1e6bf2a5e/deploy/group_vars/qa/main.yml#L10

- [x] Production
https://github.com/sillsdev/TheCombine/blob/9a69089401205385720e136c0ef950b1e6bf2a5e/deploy/group_vars/server/main.yml#L10

## Developer Notes

To opt back out of the analytics after this is merged, you must delete the specific cookies for segment.com and localhost. For Chrome instructions: https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1239)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1239)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

___
*[README.md, line 136 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1239#-MgRqdMwB7FeNGIOdOKt:-MgRqdMwB7FeNGIOdOKu:b-7nvrha) ([raw file](https://github.com/sillsdev/thecombine/blob/726856d9d11105d2a0564c97c189fdab6108ed34/README.md#L136)):*
> ```Markdown
>     ```bash
>     # For Windows, use `copy`.
>     $ cp .env.local.template .env.local
> ```

So this will lose the REACT_APP_VERSION won't it?

**Comment by johnthagen** [comment]
___
*[README.md, line 136 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1239#-MgRqdMwB7FeNGIOdOKt:-MgRrXa73Z2KDPkpAnSs:bgl4sy4) ([raw file](https://github.com/sillsdev/thecombine/blob/726856d9d11105d2a0564c97c189fdab6108ed34/README.md#L136)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

So this will lose the REACT_APP_VERSION won't it?
</blockquote></details>

My understanding is that these are just overrides, so what is in `.env` should still be valid: https://create-react-app.dev/docs/adding-custom-environment-variables/#what-other-env-files-can-be-used

**Comment by johnthagen** [comment]
___
*[README.md, line 136 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1239#-MgRqdMwB7FeNGIOdOKt:-MgRsR4Q7ifEDzRbjtsf:bg61ieb) ([raw file](https://github.com/sillsdev/thecombine/blob/726856d9d11105d2a0564c97c189fdab6108ed34/README.md#L136)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

My understanding is that these are just overrides, so what is in `.env` should still be valid: https://create-react-app.dev/docs/adding-custom-environment-variables/#what-other-env-files-can-be-used
</blockquote></details>

Yes, I created `.env.local` and confirmed that when the frontend built, the version number was still shown in the User bar.

**Review by jasonleenaylor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1239)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Pull request merged**
