### PR TITLE
Reduce password reset confusion

### PR DESCRIPTION
**Pull request by StevesBro**
Allow either username or email to be submitted and check on the backend.
 Remove delay after submitting request and give confirmation
 Stop showing the token on the reset page.
 Redirect to login instead of reset page after sending email.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/685)

### CODE REVIEW

**Review by imnasnainaec — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/685)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @StevesBro)

___
*[Backend/Controllers/UserController.cs, line 41 at r3](https://reviewable.io/reviews/sillsdev/thecombine/685#-MGKXDnUEaoHAPHruHMz:-MGKXDnUEaoHAPHruHN-:b-g2sr) ([raw file](https://github.com/sillsdev/thecombine/blob/a9043ab74f618283c20e5e32e4c82d4a265c7dd0/Backend/Controllers/UserController.cs#L41)):*
> ```
>             // create password reset
>             var resetRequest = await _passwordResetService.CreatePasswordReset(data.EmailOrUsername);
> ```
https://github.com/sillsdev/TheCombine/blob/master/Backend/Services/PasswordResetService.cs#L20-L51 and https://github.com/sillsdev/TheCombine/blob/master/Backend/Models/PasswordReset.cs#L18-L42 need to be updated accordingly.
___
*[src/resources/translations.json, line 164 at r3](https://reviewable.io/reviews/sillsdev/thecombine/685#-MGKY23_4hKo81TLQzPt:-MGKY23_4hKo81TLQzPu:b-eodjwy) ([raw file](https://github.com/sillsdev/thecombine/blob/a9043ab74f618283c20e5e32e4c82d4a265c7dd0/src/resources/translations.json#L164)):*
> ```JSON
>     "submit": ["Submit", "Enviar"],
>     "resetFail": ["Password reset expired", "Error al restablecer contraseña"],
>     "emailError": [
> ```

Variable name "emailError" should probably be updated here and in RequestPage.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/685)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @StevesBro)

___
*[Backend/Controllers/UserController.cs, line 46 at r3](https://reviewable.io/reviews/sillsdev/thecombine/685#-MGKZ6U6-0xXPTNduDuz:-MGKZ6U6-0xXPTNduDv-:bqyhtd3) ([raw file](https://github.com/sillsdev/thecombine/blob/a9043ab74f618283c20e5e32e4c82d4a265c7dd0/Backend/Controllers/UserController.cs#L46)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>             // create password reset
>             var resetRequest = await _passwordResetService.CreatePasswordReset(data.EmailOrUsername);
>             // find user attached to email or username
>             var user = _userService.GetAllUsers().Result.SingleOrDefault(user =>
>                 user.Email.ToLowerInvariant().Equals(data.EmailOrUsername.ToLowerInvariant()) ||
>                 user.Username.ToLowerInvariant().Equals(data.EmailOrUsername.ToLowerInvariant()));
> ```
</details>

Something like `var requestString = data.EmailOrUsername.ToLowerInvariant()` could be used three times to clean this up a little.

**Comment by imnasnainaec** [comment]
Email delivery still works, but something is wrong with the reset:
image

**Review by StevesBro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/685)* status: 4 of 8 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @StevesBro)

___
*[Backend/Controllers/UserController.cs, line 41 at r3](https://reviewable.io/reviews/sillsdev/thecombine/685#-MGKXDnUEaoHAPHruHMz:-MGKfx6oEw0r-utjs3h1:b-25atg8) ([raw file](https://github.com/sillsdev/thecombine/blob/a9043ab74f618283c20e5e32e4c82d4a265c7dd0/Backend/Controllers/UserController.cs#L41)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>             // create password reset
>             var resetRequest = await _passwordResetService.CreatePasswordReset(data.EmailOrUsername);
> ```
https://github.com/sillsdev/TheCombine/blob/master/Backend/Services/PasswordResetService.cs#L20-L51 and https://github.com/sillsdev/TheCombine/blob/master/Backend/Models/PasswordReset.cs#L18-L42 need to be updated accordingly.
</blockquote></details>

PasswordReset Emails are now stored correctly

**Review by imnasnainaec — APPROVED** [review]
Problem fixed.

> Reviewed 1 of 1 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/685#-:-MGKk6uo5BLiH8GaW7gX:b-14prk0)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
