### PR TITLE
Refactor NewEntry: extract Dialogs from VernWithSug

### LINKED ISSUE #675: Move NewEntry dialogs out of VernWithSuggestions
Currently the dialogs that pop up when a duplicate vernacular is entered (`VernDialog` for entry selection, `SenseDialog` for sense selection) reside within the `VernWithSuggestions` component, but all props come from `NewEntry`. After the present workshop, when there are no active PRs involving DataEntry, they should be moved to simplify the code.

### PR DESCRIPTION
**Pull request by imnasnainaec**
All the logic for handling NewEntry Dialogs was being unnecessarily complicated by passing into VernWithSuggestions.

Resolves #675

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/738)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
I wonder if  we will regret the move refactor to NewEntry. Will that make it harder to handle edits in the Review Entries tool in a similar way?

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/738#-:-MI_fWoa5aXBR0ei1XtU:b-ecrnld)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
@jasonleenaylor What sort of similar edits might we have in Review Entries?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/738#-:-MIdlf5N8BIn0CcnGIM8:bjz1yen)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/738)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by imnasnainaec — COMMENTED** [review]
I think this is closer to having a dialog layer outside the input-with-suggestions, which we would want if we were to use it elsewhere.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/738#-:-MIduRVq8dgLnw_Jk7Nw:b-m4eluq)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jasonleenaylor — APPROVED** [review]
:LGTM:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/738#-:-MIzlfwmExmWYf4eoFMa:bjw1nd)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
