### PR TITLE
Email invite add notification

### LINKED ISSUE #1317: [ProjectSettings] User feedback for when email invite attempted for existing user.
When a project invite is sent to an email address of an existing user, that user is automatically added to the project and no email is sent (#1275), but it would be good for the inviter to know that this happened.

### PR DESCRIPTION
**Pull request by WeJamUS**
Closes #1317

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1374)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 3 files at r4, 4 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1374)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @JacobHaimes and @WeJamUS)

___
*[src/components/ProjectSettings/ProjectUsers/EmailInvite.tsx, line 47 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1374#-MjFe78g2WVfVvpM-B2e:-MjFe78g2WVfVvpM-B2f:btyvb5i) ([raw file](https://github.com/sillsdev/thecombine/blob/7dee8b826358149486c1a346fab750f60d50422a/src/components/ProjectSettings/ProjectUsers/EmailInvite.tsx#L47)):*
> ```
> "This user is already registered!"
> ```
Please internationalize this string.

**Review by WeJamUS — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1374)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @JacobHaimes and @jasonleenaylor)

___
*[src/components/ProjectSettings/ProjectUsers/EmailInvite.tsx, line 47 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1374#-MjFe78g2WVfVvpM-B2e:-MjFqT8-3dNTBYTiLnq_:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7dee8b826358149486c1a346fab750f60d50422a/src/components/ProjectSettings/ProjectUsers/EmailInvite.tsx#L47)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> "This user is already registered!"
> ```
Please internationalize this string.
</blockquote></details>

Done.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 1 of 2 files at r6, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1374)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @JacobHaimes)

**Review by WeJamUS — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1374#-:-MjGnY920vO6-_kOqrvl:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @WeJamUS)

**Review by WeJamUS — COMMENTED** [review]
> Reviewed 1 of 2 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1374)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @WeJamUS)

**Pull request merged**
