### PR TITLE
Enable C# 8 nullable compiler feature

### LINKED ISSUE #754: Consider enforcing nullable type system in backend
Similar to TypeScript where we use types such as `string | undefined` and the compiler checks/enforces this, we could enable nullable context project-wide on the backend:

- https://stackoverflow.com/a/61436270
- https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references#nullable-contexts

This would allow us to express a much finer control over where `null` is allowed in the backend, and open up for precisely describing which of our model fields can have `null`.

Example:

```c#
        // This attribute can be null, denoted by the ?
        [BsonElement("avatar")]
        public string? Avatar { get; set; }
```

Turning it on on the current code base results in a lot of errors that would need to be sorted out:

<details><summary>Errors</summary>

```
Models\Project.cs(161,30): error CS8765: Nullability of type of parameter 'obj' doesn't match overridden member (possibly because of nullability attributes). [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Project.cs(272,30): error CS8765: Nullability of type of parameter 'obj' doesn't match overridden member (possibly because of nullability attributes). [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\User.cs(139,30): error CS8765: Nullability of type of parameter 'obj' doesn't match overridden member (possibly because of nullability attributes). [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\UserEdit.cs(54,30): error CS8765: Nullability of type of parameter 'obj' doesn't match overridden member (possibly because of nullability attributes). [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\UserEdit.cs(84,30): error CS8765: Nullability of type of parameter 'obj' doesn't match overridden member (possibly because of nullability attributes). [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\UserEdit.cs(131,30): error CS8765: Nullability of type of parameter 'obj' doesn't match overridden member (possibly because of nullability attributes). [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\UserRole.cs(55,30): error CS8765: Nullability of type of parameter 'obj' doesn't match overridden member (possibly because of nullability attributes). [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(250,30): error CS8765: Nullability of type of parameter 'obj' doesn't match overridden member (possibly because of nullability attributes). [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(289,30): error CS8765: Nullability of type of parameter 'obj' doesn't match overridden member (possibly because of nullability attributes). [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(215,30): error CS8765: Nullability of type of parameter 'obj' doesn't match overridden member (possibly because of nullability attributes). [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(136,30): error CS8765: Nullability of type of parameter 'obj' doesn't match overridden member (possibly because of nullability attributes). [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Services\SemDomParser.cs(87,24): error CS8767: Nullability of reference types in type of parameter 'x' of 'int SemDomComparer.Compare(SemanticDomain x, SemanticDomain y)' doesn't match implicitly implemented member 'int IComparer<SemanticDomain>.Compare(SemanticDomain x, SemanticDomain y)' (possibly because
 of nullability attributes). [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Services\SemDomParser.cs(87,24): error CS8767: Nullability of reference types in type of parameter 'y' of 'int SemDomComparer.Compare(SemanticDomain x, SemanticDomain y)' doesn't match implicitly implemented member 'int IComparer<SemanticDomain>.Compare(SemanticDomain x, SemanticDomain y)' (possibly because
 of nullability attributes). [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(328,23): error CS8618: Non-nullable field 'SrcWordId' is uninitialized. Consider declaring the field as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(329,28): error CS8618: Non-nullable field 'SenseStates' is uninitialized. Consider declaring the field as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(319,21): error CS8618: Non-nullable property 'Parent' is uninitialized. Consider declaring the property as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(320,38): error CS8618: Non-nullable property 'ChildrenWords' is uninitialized. Consider declaring the property as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(321,23): error CS8618: Non-nullable property 'MergedBy' is uninitialized. Consider declaring the property as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(322,23): error CS8618: Non-nullable property 'Time' is uninitialized. Consider declaring the property as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Startup.cs(38,27): error CS8618: Non-nullable property 'ConnectionString' is uninitialized. Consider declaring the property as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Startup.cs(39,27): error CS8618: Non-nullable property 'CombineDatabase' is uninitialized. Consider declaring the property as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Startup.cs(40,27): error CS8618: Non-nullable property 'SmtpServer' is uninitialized. Consider declaring the property as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Startup.cs(42,27): error CS8618: Non-nullable property 'SmtpUsername' is uninitialized. Consider declaring the property as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Startup.cs(43,27): error CS8618: Non-nullable property 'SmtpPassword' is uninitialized. Consider declaring the property as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Startup.cs(44,27): error CS8618: Non-nullable property 'SmtpAddress' is uninitialized. Consider declaring the property as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Startup.cs(45,27): error CS8618: Non-nullable property 'SmtpFrom' is uninitialized. Consider declaring the property as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(308,26): error CS8618: Non-nullable property 'File' is uninitialized. Consider declaring the property as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(309,23): error CS8618: Non-nullable property 'Name' is uninitialized. Consider declaring the property as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(310,23): error CS8618: Non-nullable property 'FilePath' is uninitialized. Consider declaring the property as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Project.cs(212,16): error CS8618: Non-nullable property 'Id' is uninitialized. Consider declaring the property as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Project.cs(212,16): error CS8618: Non-nullable property 'Email' is uninitialized. Consider declaring the property as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Project.cs(212,16): error CS8618: Non-nullable property 'Token' is uninitialized. Consider declaring the property as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Project.cs(266,24): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Project.cs(267,25): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Project.cs(268,24): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Project.cs(199,24): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Project.cs(200,24): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Project.cs(241,22): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Project.cs(242,25): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Project.cs(243,25): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Project.cs(192,23): error CS8618: Non-nullable property 'Name' is uninitialized. Consider declaring the property as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Project.cs(193,23): error CS8618: Non-nullable property 'Type' is uninitialized. Consider declaring the property as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Project.cs(313,16): error CS8618: Non-nullable field 'UpdatedUser' is uninitialized. Consider declaring the field as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(276,24): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(277,22): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(278,31): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Project.cs(315,16): error CS8618: Non-nullable field 'UpdatedUser' is uninitialized. Consider declaring the field as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\User.cs(87,22): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\User.cs(88,26): error CS8602: Dereference of a possibly null reference. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\User.cs(90,24): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\User.cs(91,25): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\User.cs(92,25): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\User.cs(93,40): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\User.cs(95,28): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\User.cs(96,28): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\User.cs(97,26): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\User.cs(98,25): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\User.cs(105,42): error CS8604: Possible null reference argument for parameter 'key' in 'void Dictionary<string, string>.Add(string key, string value)'. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\User.cs(105,68): error CS8604: Possible null reference argument for parameter 'value' in 'void Dictionary<string, string>.Add(string key, string value)'. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\User.cs(110,40): error CS8604: Possible null reference argument for parameter 'key' in 'void Dictionary<string, string>.Add(string key, string value)'. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\User.cs(110,66): error CS8604: Possible null reference argument for parameter 'value' in 'void Dictionary<string, string>.Add(string key, string value)'. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Project.cs(79,22): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Project.cs(80,24): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Project.cs(103,43): error CS8604: Possible null reference argument for parameter 'item' in 'void List<string>.Add(string item)'. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Project.cs(107,46): error CS8604: Possible null reference argument for parameter 'item' in 'void List<string>.Add(string item)'. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Project.cs(115,38): error CS8604: Possible null reference argument for parameter 'item' in 'void List<string>.Add(string item)'. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Project.cs(119,41): error CS8604: Possible null reference argument for parameter 'item' in 'void List<string>.Add(string item)'. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Startup.cs(140,48): error CS8625: Cannot convert null literal to non-nullable reference type. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Startup.cs(144,50): error CS8625: Cannot convert null literal to non-nullable reference type. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Startup.cs(146,50): error CS8625: Cannot convert null literal to non-nullable reference type. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Startup.cs(148,49): error CS8625: Cannot convert null literal to non-nullable reference type. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Startup.cs(150,46): error CS8625: Cannot convert null literal to non-nullable reference type. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\User.cs(120,17): error CS8602: Dereference of a possibly null reference. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\User.cs(173,23): error CS8618: Non-nullable property 'Username' is uninitialized. Consider declaring the property as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\User.cs(174,23): error CS8618: Non-nullable property 'Password' is uninitialized. Consider declaring the property as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\User.cs(182,16): error CS8618: Non-nullable field 'UpdatedUser' is uninitialized. Consider declaring the field as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Controllers\UserController.cs(256,27): error CS8618: Non-nullable field 'EmailOrUsername' is uninitialized. Consider declaring the field as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Controllers\UserController.cs(257,27): error CS8618: Non-nullable field 'Token' is uninitialized. Consider declaring the field as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Controllers\UserController.cs(258,27): error CS8618: Non-nullable field 'NewPassword' is uninitialized. Consider declaring the field as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Controllers\UserController.cs(259,27): error CS8618: Non-nullable field 'Domain' is uninitialized. Consider declaring the field as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\UserEdit.cs(33,22): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\UserEdit.cs(34,29): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\UserEdit.cs(125,36): error CS8604: Possible null reference argument for parameter 'item' in 'void List<string>.Add(string item)'. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\UserRole.cs(34,22): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\UserRole.cs(35,29): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Controllers\LiftController.cs(86,47): error CS8604: Possible null reference argument for parameter 'path1' in 'string Path.Combine(string path1, string path2)'. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Controllers\LiftController.cs(92,43): error CS8604: Possible null reference argument for parameter 'path1' in 'string Path.Combine(string path1, string path2)'. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(245,28): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(246,23): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(238,23): error CS8618: Non-nullable property 'Language' is uninitialized. Consider declaring the property as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(239,23): error CS8618: Non-nullable property 'Def' is uninitialized. Consider declaring the property as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(84,22): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(86,30): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(87,26): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(88,27): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(89,28): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(90,32): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(91,30): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(92,29): error CS8601: Possible null reference assignment. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(102,33): error CS8604: Possible null reference argument for parameter 'item' in 'void List<string>.Add(string item)'. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(106,36): error CS8604: Possible null reference argument for parameter 'item' in 'void List<string>.Add(string item)'. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(110,35): error CS8604: Possible null reference argument for parameter 'item' in 'void List<string>.Add(string item)'. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(179,28): error CS8618: Non-nullable property 'Glosses' is uninitialized. Consider declaring the property as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Models\Word.cs(182,37): error CS8618: Non-nullable property 'SemanticDomains' is uninitialized. Consider declaring the property as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Controllers\ProjectController.cs(369,27): error CS8618: Non-nullable field 'EmailAddress' is uninitialized. Consider declaring the field as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Controllers\ProjectController.cs(370,27): error CS8618: Non-nullable field 'Message' is uninitialized. Consider declaring the field as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Controllers\ProjectController.cs(371,27): error CS8618: Non-nullable field 'ProjectId' is uninitialized. Consider declaring the field as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Controllers\ProjectController.cs(372,27): error CS8618: Non-nullable field 'Domain' is uninitialized. Consider declaring the field as nullable. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Services\UserApiServices.cs(117,24): error CS8603: Possible null reference return. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Services\UserApiServices.cs(124,20): error CS8603: Possible null reference return. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Services\WordApiServices.cs(87,24): error CS8603: Possible null reference return. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Services\PermissionService.cs(105,20): error CS8603: Possible null reference return. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Services\UserApiServices.cs(132,47): error CS8604: Possible null reference argument for parameter 's' in 'byte[] Encoding.GetBytes(string s)'. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Services\UserApiServices.cs(168,24): error CS8603: Possible null reference return. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Services\LiftApiServices.cs(193,65): error CS8604: Possible null reference argument for parameter 'path2' in 'string Path.Combine(string path1, string path2, string path3)'. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Services\LiftApiServices.cs(216,54): error CS8604: Possible null reference argument for parameter 'stream' in 'StreamReader.StreamReader(Stream stream, Encoding encoding)'. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Services\UserApiServices.cs(210,20): error CS8603: Possible null reference return. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Services\UserApiServices.cs(249,24): error CS8603: Possible null reference return. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Services\UserApiServices.cs(274,29): error CS8625: Cannot convert null literal to non-nullable reference type. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Services\UserApiServices.cs(275,26): error CS8625: Cannot convert null literal to non-nullable reference type. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
Services\LiftApiServices.cs(364,20): error CS8603: Possible null reference return. [C:\Users\User\GitHub\TheCombine\Backend\BackendFramework.csproj]
```

</details>

### PR DESCRIPTION
**Pull request by johnthagen**
Closes #754

`Nullable` is not yet enabled for the `Backend.Tests` project, as that would require some more work to determine how to best address and still keep unit tests concise.

Due to the large volume of code this PR touches, it deserves to be tested thoroughly.

There are also still some APIs that are marked as non-nullable, but in our code we are checking `if (result is null)`. So some further analysis might allow us to tighten up some of the definitions to make them a little more accurate.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/780)

### CODE REVIEW

**Comment by imnasnainaec** [comment]
@johnthagen In the cloning methods, we have things like `Id.Clone() as string` where you added the [null-forgiving operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-forgiving): `(Id.Clone() as string)!`. If we are asserting that the expression will not be null, then might it be better for us to [cast](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/type-testing-and-cast#cast-expression) the expression instead and so force a compile-time error if something is null that shouldn't be: `(string)Id.Clone()`?

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 22 of 36 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/780)* status: 22 of 38 files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[Backend.Tests/Services/PasswordResetServiceTests.cs, line 64 at r3](https://reviewable.io/reviews/sillsdev/thecombine/780#-MKjv6DA3j_h8oyTitJk:-MKjv6DA3j_h8oyTitJl:bji8amv) ([raw file](https://github.com/sillsdev/thecombine/blob/8c6ceeab85237395642a677ca516ce0ce8dd637b/Backend.Tests/Services/PasswordResetServiceTests.cs#L64)):*
> ```Smalltalk
>             _userService.Create(user);
> 
>             var request = _passwordResetService.CreatePasswordReset("user@domain.com").Result;
> ```

`var request = _passwordResetService.CreatePasswordReset("user@domain.com").Result;`

It looks like this `request` is never used.
___
*[Backend.Tests/Services/PasswordResetServiceTests.cs, line 67 at r3](https://reviewable.io/reviews/sillsdev/thecombine/780#-MKjucR63f_0n-1PSDIp:-MKjucR63f_0n-1PSDIq:bt7u39) ([raw file](https://github.com/sillsdev/thecombine/blob/8c6ceeab85237395642a677ca516ce0ce8dd637b/Backend.Tests/Services/PasswordResetServiceTests.cs#L67)):*
> ```
>             var res = task.Result;
>             Assert.IsFalse(res);
> ```

Why not `Assert.IsFalse(task.Result)`?

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/780)* status: 23 of 38 files reviewed, all discussions resolved (waiting on @johnthagen)

___
*[Backend/Contexts/PasswordResetContext.cs, line 32 at r3](https://reviewable.io/reviews/sillsdev/thecombine/780#-MKjxqvx7zFaqVJITWCx:-MKjxqvx7zFaqVJITWCy:b-g0u2j2) ([raw file](https://github.com/sillsdev/thecombine/blob/8c6ceeab85237395642a677ca516ce0ce8dd637b/Backend/Contexts/PasswordResetContext.cs#L32)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>         public async Task<PasswordReset?> FindByToken(string token)
>         {
>             return (await PasswordResets.FindAsync(r => r.Token == token)).SingleOrDefault();
>         }
> ```
</details>

I'm not sure why we're adding the `?` in `Task<PasswordReset?>`. I see that `FindAsync` can return `null`, but doesn't `SingleOrDefault` throw an exception in that case? Or are we allowing for `null` to be the default?

**Comment by johnthagen** [comment]
___
*[Backend.Tests/Services/PasswordResetServiceTests.cs, line 64 at r3](https://reviewable.io/reviews/sillsdev/thecombine/780#-MKjv6DA3j_h8oyTitJk:-MKtZqE483WV6TOMDIyB:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/8c6ceeab85237395642a677ca516ce0ce8dd637b/Backend.Tests/Services/PasswordResetServiceTests.cs#L64)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`var request = _passwordResetService.CreatePasswordReset("user@domain.com").Result;`

It looks like this `request` is never used.
</blockquote></details>

Done

**Comment by johnthagen** [comment]
___
*[Backend.Tests/Services/PasswordResetServiceTests.cs, line 67 at r3](https://reviewable.io/reviews/sillsdev/thecombine/780#-MKjucR63f_0n-1PSDIp:-MKtZrQv2YSSBnjRucLN:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/8c6ceeab85237395642a677ca516ce0ce8dd637b/Backend.Tests/Services/PasswordResetServiceTests.cs#L67)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>             var res = task.Result;
>             Assert.IsFalse(res);
> ```

Why not `Assert.IsFalse(task.Result)`?
</blockquote></details>

Done.

**Comment by johnthagen** [comment]
>  If we are asserting that the expression will not be null, then might it be better for us to cast the expression instead and so force a compile-time error if something is null that shouldn't be: (string)Id.Clone()?

So, this won't force a compile-time error because the compiler can't know at compile time this won't be `null` or not. 

It will actually throw an exception if it can't cast doesn't work, which is actually better than silently propagating `null` anyway. I will change to `( )` style casts.

In a related note, I don't really like how much boilerplate our `Model`s have just to make copies of themselves. I wish we could use something like a `dataclass` from Python and `copy.deepcopy()`. I looked around but could not find a clean way to do this in C# (likely because the internal structure of C# objects is a lot different than Python ones which are basically just dictionaries).

**Comment by johnthagen** [comment]
___
*[Backend/Contexts/PasswordResetContext.cs, line 32 at r3](https://reviewable.io/reviews/sillsdev/thecombine/780#-MKjxqvx7zFaqVJITWCx:-MKtf4sSAKMnIN-3Qbv4:bu63zuk) ([raw file](https://github.com/sillsdev/thecombine/blob/8c6ceeab85237395642a677ca516ce0ce8dd637b/Backend/Contexts/PasswordResetContext.cs#L32)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>         public async Task<PasswordReset?> FindByToken(string token)
>         {
>             return (await PasswordResets.FindAsync(r => r.Token == token)).SingleOrDefault();
>         }
> ```
I'm not sure why we're adding the `?` in `Task<PasswordReset?>`. I see that `FindAsync` can return `null`, but doesn't `SingleOrDefault` throw an exception in that case? Or are we allowing for `null` to be the default?
</blockquote></details>

Done.

(This must have been checked in erroneously when I was checking to see if I could apply `nullable` to the tests project. It is not included in this PR, so this should not be here. Good catch).

**Comment by johnthagen** [comment]
> If we are asserting that the expression will not be null, then might it be better for us to cast the expression instead

Done.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 7 of 36 files at r2, 7 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/780)* status: 37 of 38 files reviewed, all discussions resolved (waiting on @johnthagen)

**Comment by johnthagen** [comment]
:lgtm:

**Review by imnasnainaec — CHANGES_REQUESTED** [review]
> Reviewed 1 of 36 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/780)* status: all files reviewed, 1 unresolved discussion (waiting on @johnthagen)

*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/780#-MKuF0E-3QWrMUfeO4AI:-MKuF0E-3QWrMUfeO4AJ:b23q63a) (no related file):*
I've not identified the reason, but this pr seems to introduce several errors:
* Adding audio to an entry
* Uploading a lift file

---

**Comment by johnthagen** [comment]
*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/780#-MKuF0E-3QWrMUfeO4AI:-MKutPlZ5RRchV4Nm3n_:bvw78de) (no related file):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I've not identified the reason, but this pr seems to introduce several errors:
* Adding audio to an entry
* Uploading a lift file
</blockquote></details>

```
System.InvalidOperationException: Could not create an instance of type 'BackendFramework.Models.FileUpload'. Model bound complex types must not be abstract or value types and must have a parameterless constructor. Alternatively, give the 'fileUpload' parameter a non-null default value.
```

---

**Comment by johnthagen** [comment]
*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/780#-MKuF0E-3QWrMUfeO4AI:-MKuv_L1DIuXYPS-_HXv:bt2vr1b) (no related file):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

```
System.InvalidOperationException: Could not create an instance of type 'BackendFramework.Models.FileUpload'. Model bound complex types must not be abstract or value types and must have a parameterless constructor. Alternatively, give the 'fileUpload' parameter a non-null default value.
```
</blockquote></details>

Fixed.

---

**Comment by johnthagen** [comment]
*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/780#-MKuF0E-3QWrMUfeO4AI:-MKuvbKkDM5WGz8U69sK:b-896fix) (no related file):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

Done.

---

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 8 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/780)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
