### PR TITLE
Fix email invite.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Fix bug introduced in #1275.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1290)

### CODE REVIEW

**Comment by WeJamUS** [comment]
___
*[src/components/ProjectSettings/ProjectUsers/EmailInvite.tsx, line 44 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1290#-MgI5jGnA-T_xRUyZXt6:-MgI5jGnA-T_xRUyZXt7:b1jytpq) ([raw file](https://github.com/sillsdev/thecombine/blob/74f0dfd1d92072fa17c7c9a1d47f7d9cef366ffd/src/components/ProjectSettings/ProjectUsers/EmailInvite.tsx#L44)):*
> ```XML
>     this.setState({ loading: true });
>     await Backend.getUserByEmail(this.state.emailAddress)
>       .then((u) => this.props.addToProject(u))
> ```

I'm curious as to what bug my code was causing?

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1290)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @WeJamUS)

___
*[src/components/ProjectSettings/ProjectUsers/EmailInvite.tsx, line 44 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1290#-MgI5jGnA-T_xRUyZXt6:-MgI9YLx62Gbtln5M0TF:bvz36jg) ([raw file](https://github.com/sillsdev/thecombine/blob/74f0dfd1d92072fa17c7c9a1d47f7d9cef366ffd/src/components/ProjectSettings/ProjectUsers/EmailInvite.tsx#L44)):*
<details><summary><i>Previously, WeJamUS (James Wu) wrote…</i></summary><blockquote>

I'm curious as to what bug my code was causing?
</blockquote></details>

When the backend call failed, it didn't assign `undefined` to `user` as expected, so the dialog sat there spinning. In my review, I neglected to test it with an email address that wasn't tied to an existing account to make sure it was still working.

**Review by WeJamUS — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1290)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by WeJamUS — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1290)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
