### PR TITLE
Expand project owner capabilities

### LINKED ISSUE #1270: [ProjectSettings] Expand project owner capabilities
Things from #940 left out of #1253.

Let project owners:
- [ ] Transfer project ownership to a different project admin
- [ ] Archive/Restore the project

### PR DESCRIPTION
**Pull request by WeJamUS**
Closes #1270

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1367)

### CODE REVIEW

**Review by imnasnainaec — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1367)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @JacobHaimes and @WeJamUS)

___
*[src/components/ProjectSettings/ProjectSettingsComponent.tsx, line 23 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1367#-Mj50Uuk-he6a8-3EG3F:-Mj50UulAtgHuywcAaSr:bxk4h21) ([raw file](https://github.com/sillsdev/thecombine/blob/405b701bf459bb9737db9d44c27313bc6e17c377/src/components/ProjectSettings/ProjectSettingsComponent.tsx#L23)):*
> ```
> import ProjectButtonWithConfirmation from "components/SiteSettings/ProjectManagement/ProjectButtonWithConfirmation";
> ```
Can you move this down below "components/ProjectSettings/*" and above "types"?
___
*[src/resources/translations.json, line 438 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1367#-Mj51rWu4sVLmmPxF-2-:-Mj51rWu4sVLmmPxF-20:bicdg70) ([raw file](https://github.com/sillsdev/thecombine/blob/405b701bf459bb9737db9d44c27313bc6e17c377/src/resources/translations.json#L438)):*
> ```
>       "makeOwnerToastFaillure": [
> ```
typo

**Comment by WeJamUS** [comment]
___
*[src/resources/translations.json, line 438 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1367#-Mj51rWu4sVLmmPxF-2-:-Mj55qOeAkhIdRNzyV_k:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/405b701bf459bb9737db9d44c27313bc6e17c377/src/resources/translations.json#L438)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>       "makeOwnerToastFaillure": [
> ```
typo
</blockquote></details>

Done.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1367)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @JacobHaimes and @WeJamUS)

___
*[src/components/ProjectSettings/ProjectSettingsComponent.tsx, line 61 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1367#-Mj57v7c119sE624xoNw:-Mj57v7c119sE624xoNx:b-764eb7) ([raw file](https://github.com/sillsdev/thecombine/blob/e80269253a73a5468ab15cfd661d8e2df9c0ed4f/src/components/ProjectSettings/ProjectSettingsComponent.tsx#L61)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>   // TODO: Switch to homepage after archiving since it doesn't make sense
>   // to stay in an archived project
>   function archiveUpdate() {
>     toast(<Translate id="projectSettings.user.archiveToastSuccess" />);
>   }
> ```
</details>

Please let me know if you have any questions about what I posted in Slack for getting this part done.
___
*[src/components/ProjectSettings/ProjectSettingsComponent.tsx, line 151 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1367#-Mj57qOmDsf49fHgJCfM:-Mj57qOmDsf49fHgJCfN:b-dvuabl) ([raw file](https://github.com/sillsdev/thecombine/blob/e80269253a73a5468ab15cfd661d8e2df9c0ed4f/src/components/ProjectSettings/ProjectSettingsComponent.tsx#L151)):*
> ```
>       {/* Archive/restore project */}
> ```
In this case, only the archive functionality is present.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1367)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @JacobHaimes and @WeJamUS)

___
*[src/components/ProjectSettings/ProjectSettingsComponent.tsx, line 160 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1367#-Mj65MAnDBlzMr3J6n4t:-Mj65MAnDBlzMr3J6n4u:bk2abgz) ([raw file](https://github.com/sillsdev/thecombine/blob/46af1ce11c9cfdb4489d05e5bc67e085122eb97d/src/components/ProjectSettings/ProjectSettingsComponent.tsx#L160)):*
> ```XML
>           body={
>             <ProjectButtonWithConfirmation
>               archive={project.isActive}
> ```

This could be
```archive={true} // Project Settings are only available for active projects.```
And then you can restore the `UseSelector` only grabbing the project id.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1367)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @JacobHaimes and @WeJamUS)

*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/1367#-MjADAoxEQ7EMQuIgHFW:-MjADAoxEQ7EMQuIgHFX:bszibn0) (no related file):*
This all works great! I'm worried, though, that the Archive button in Project Settings might be confused with an Export/Download option. It would be a useful warning if that button had some red. Can you add property `warn?: bool` to ProjectButtonWithConfirmation and give its Button `color={props.warn ? "secondary" : "primary"}` and  `style={props.warn ? { color: themeColors.error } : {}}`?

---

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1367)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @JacobHaimes and @WeJamUS)

___
*[src/components/ProjectSettings/ProjectSettingsComponent.tsx, line 163 at r7](https://reviewable.io/reviews/sillsdev/thecombine/1367#-MjAi5KYBXvyGGkdgdSq:-MjAi5KZ-QV5m3jJcj0w:b1168hu) ([raw file](https://github.com/sillsdev/thecombine/blob/fd11ba8ee7a4e67d7359797b82ee906b343f7db6/src/components/ProjectSettings/ProjectSettingsComponent.tsx#L163)):*
> ```
> warn={true}
> ```
For a boolean component prop, just `warn` is a shorthand for `warn={true}`.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1367)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JacobHaimes)

**Pull request merged**
