### PR TITLE
Export semantic domains in English

### PR DESCRIPTION
**Pull request by imnasnainaec**
To-do: 
- #1569 (after #2881)
- Unit tests
- Export tests w/ FLEx
- get browser language proj when defaulting to it

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2948)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 11 of 44 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2948)* status: 12 of 47 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[`src/components/Project/ProjectActions.ts` line 48 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2948#-NrHuKXS29qRWIrWNJ6D:-NrHuKXS29qRWIrWNJ6E:bvz9x2g) ([raw file](https://github.com/sillsdev/TheCombine/blob/e1343571427331b0985e7ccda8d458561cee9859/src/components/Project/ProjectActions.ts#L48)):*
> ```XML
> 
> /** If the project's sem dom language is set to (Default to user interface language) and
>  * the UI language changes, the user must leave the project and re-enter for that change
> ```

Maybe I'm tired, but this didn't quite make sense to me.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2948)* status: 11 of 51 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jasonleenaylor)

___
*[`src/components/Project/ProjectActions.ts` line 48 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2948#-NrHuKXS29qRWIrWNJ6D:-NrLBaJvDqu8qW5YtSMn:bi77206) ([raw file](https://github.com/sillsdev/TheCombine/blob/e1343571427331b0985e7ccda8d458561cee9859/src/components/Project/ProjectActions.ts#L48)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Maybe I'm tired, but this didn't quite make sense to me.
</blockquote></details>

I've updated `UserSettings` to remove the aforecommented disfunction.

**Review by jasonleenaylor — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 18 of 44 files at r2, 27 of 28 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2948)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[`src/components/WordCard/tests/SenseCard.test.tsx` line 37 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2948#-NtvIhQt4WH8-6T96xHP:-NtvIhQt4WH8-6T96xHQ:b-v9jrk4) ([raw file](https://github.com/sillsdev/TheCombine/blob/32b2536325de4bec5f4a3ad3db8423df0398cfd3/src/components/WordCard/tests/SenseCard.test.tsx#L37)):*
> ```XML
> 
> describe("SenseCard", () => {
>   it("has an icon for non-Unspecified part of speech", async () => {
> ```

I found this not unconfusing.



_Code quote:_
```XML
non-Unspecified
```

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2948)* status: 50 of 51 files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor)

___
*[`src/components/WordCard/tests/SenseCard.test.tsx` line 37 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2948#-NtvIhQt4WH8-6T96xHP:-NtvXVlSDAOMMVdK1a4B:b-sito0p) ([raw file](https://github.com/sillsdev/TheCombine/blob/32b2536325de4bec5f4a3ad3db8423df0398cfd3/src/components/WordCard/tests/SenseCard.test.tsx#L37)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

I found this not unconfusing.
</blockquote></details>

de-un-anti-tangled

**Review by jasonleenaylor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2948#-:-Ntvwm5M58NedC_f6iCq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
