### PR TITLE
Create a specialized database container

### PR DESCRIPTION
**Pull request by jmgrady**
Create a specialized database container that initializes the `SemanticDomains` and `SemanticDomainTree` collections at start up:
 - Create a `database` folder with the `Dockerfile` to define the container
 - Add building the `database` container to `./deploy/scripts/build.py`
 - Update GitHub Actions to add build and deployment of the Combine specific `database` container.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1726)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 6 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1726)* status: 7 of 11 files reviewed, 4 unresolved discussions (waiting on @jmgrady)

*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/1726#-NBIQGns5ftIKtyx4Z4E:-NBIQGnuAZJr3TxUJvqo:b-fde7cc) (no related file):*
For brevity, could `database/docker-entrypoint-initdb.d/` be `database/init` to match `nginx/init`?

___
___
*[`database/docker-entrypoint-initdb.d/update-semantic-domains.sh` line 4 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1726#-NBIQlGI5EU30zkoO96a:-NBIQlGI5EU30zkoO96b:b-fdrjcz) ([raw file](https://github.com/sillsdev/thecombine/blob/0b7e2ed88c9322ce74e18f0900c2a344a173497c/database/docker-entrypoint-initdb.d/update-semantic-domains.sh#L4)):*
> ```Shell
> 
> mongoimport -d CombineDatabase -c SemanticDomainTree /data/semantic-domains/tree.json --mode=merge --upsertFields=id,guid,name
> mongoimport -d CombineDatabase -c SemanticDomains /data/semantic-domains/nodes.json --mode=merge --upsertFields=id,guid,name
> ```

The README has `--upsertFields=id,lang,guid`.



_Code quote:_
```Shell
mongoimport -d CombineDatabase -c SemanticDomainTree /data/semantic-domains/tree.json --mode=merge --upsertFields=id,guid,name
mongoimport -d CombineDatabase -c SemanticDomains /data/semantic-domains/nodes.json --mode=merge --upsertFields=id,guid,name
```
___
*[`deploy/helm/thecombine/charts/database/values.yaml` line 4 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1726#-NBIRPpa0CcSCWcKqCsw:-NBIRPpa0CcSCWcKqCsx:b-4clmtk) ([raw file](https://github.com/sillsdev/thecombine/blob/0b7e2ed88c9322ce74e18f0900c2a344a173497c/deploy/helm/thecombine/charts/database/values.yaml#L4)):*
> ```YAML
> # This is a YAML-formatted file.
> # Declare variables to be passed into your templates.
> ```

missing the `# Note:` about `"Override"`
___
*[`deploy/scripts/build.py` line 258 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1726#-NBIOvhI7YtzAmvbiVyD:-NBIOvhI7YtzAmvbiVyE:b-29eqsw) ([raw file](https://github.com/sillsdev/thecombine/blob/0b7e2ed88c9322ce74e18f0900c2a344a173497c/deploy/scripts/build.py#L258)):*
> ```Python
>         to_do = args.components
>     else:
>         to_do = ["backend", "database", "frontend", "maintenance"]
> ```

Can we not use `build_specs.keys()` here instead of writing an explicit list?

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1726)* status: 7 of 11 files reviewed, 3 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/1726#-NBIQGns5ftIKtyx4Z4E:-NBISx0q3ujXrj-AsUgh:b-dnlaxt) (no related file):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

For brevity, could `database/docker-entrypoint-initdb.d/` be `database/init` to match `nginx/init`?
</blockquote></details>

It certainly could.  I chose `docker-entrypoint-initdb.d` to match the required destination in the `mongo:5.0` image.  I you have a strong preference, I am glad to change it. (The name is rather long, I agree.)

___
___
*[`database/docker-entrypoint-initdb.d/update-semantic-domains.sh` line 4 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1726#-NBIQlGI5EU30zkoO96a:-NBITV3s3ISo16B3alzS:bcuko3s) ([raw file](https://github.com/sillsdev/thecombine/blob/0b7e2ed88c9322ce74e18f0900c2a344a173497c/database/docker-entrypoint-initdb.d/update-semantic-domains.sh#L4)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

The README has `--upsertFields=id,lang,guid`.
</blockquote></details>

Good catch!  Done.
___
*[`deploy/helm/thecombine/charts/database/values.yaml` line 4 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1726#-NBIRPpa0CcSCWcKqCsw:-NBIU_tPE6jz_hTpUY5y:b-bw70t1) ([raw file](https://github.com/sillsdev/thecombine/blob/0b7e2ed88c9322ce74e18f0900c2a344a173497c/deploy/helm/thecombine/charts/database/values.yaml#L4)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

missing the `# Note:` about `"Override"`
</blockquote></details>

Actually, the variables that are set to "Override" do not apply to the database chart.  They have been removed.
___
*[`deploy/scripts/build.py` line 258 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1726#-NBIOvhI7YtzAmvbiVyD:-NBITvavAZEcaBPyklay:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/0b7e2ed88c9322ce74e18f0900c2a344a173497c/deploy/scripts/build.py#L258)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Can we not use `build_specs.keys()` here instead of writing an explicit list?
</blockquote></details>

Done.

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1726)* status: 7 of 12 files reviewed, 3 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/1726#-NBIQGns5ftIKtyx4Z4E:-NBIiwPA1jIK7R_GxloD:b-czfz3r) (no related file):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

It certainly could.  I chose `docker-entrypoint-initdb.d` to match the required destination in the `mongo:5.0` image.  I you have a strong preference, I am glad to change it. (The name is rather long, I agree.)
</blockquote></details>

Never mind my last comment.  I changed the directory to `database/init` and added a comment to the `Dockerfile` explaining why the files are copied to `/docker-entrypoint-initdb.d/`.

___

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1726)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Pull request merged**
