### PR TITLE
Setup targets to pull Docker images from AWS Elastic Container Registry

### PR DESCRIPTION
**Pull request by jmgrady**
This PR setups targets so that they can pull Docker images from Amazon's Elastic Container Registry.  This changes the Ansible installation scripts to:

1. Specify access requirements for the target system, e.g. S3 read-write/read-only; ECR read-write/read-only
2. Create ansible role, `aws_access`, to:
   1. install aws-cli
   2. setup AWS access profiles for the `combine` user
3. Add the URI for SIL's Container Registry to the docker image names
4. Configure docker daemon defaults to rotate log files

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/728)

### CODE REVIEW

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 3 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/728)* status: 3 of 13 files reviewed, all discussions resolved (waiting on @jmgrady)

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 6 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/728)* status: 9 of 13 files reviewed, all discussions resolved (waiting on @jmgrady)

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 4 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/728)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[docker_deploy/playbook_target_setup.yml, line 20 at r1](https://reviewable.io/reviews/sillsdev/thecombine/728#-MI0KRt_4YDRmA0eeRoM:-MI0KRt_4YDRmA0eeRoN:b-bnrp4l) ([raw file](https://github.com/sillsdev/thecombine/blob/d28af9effbdcc33ef432edbdc3672a2525ebf833/docker_deploy/playbook_target_setup.yml#L20)):*
> ```YAML
>     - "vars/packages.yml"
>     - "vars/vault_config.yml"
>     # The aws_prefix allows us to use a different vault file to specify the
> ```

`aws_prefix` -> `ansible_credentials`

**Review by jmgrady — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/728)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
