### PR TITLE
Use dummy CAPTCHA site key in default config

### PR DESCRIPTION
**Pull request by imnasnainaec**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3332)

### CODE REVIEW

**Review by jmgrady — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3332)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[`deploy/scripts/setup_files/profiles/dev.yaml` line 17 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/3332#-O5PDA_x3CM3t51mdK9S:-O5PDA_y94wOTC8O_1fF:bxgt0og) ([raw file](https://github.com/sillsdev/TheCombine/blob/b964bca877c5c2084df362bac4ffb9f64c1522f5/deploy/scripts/setup_files/profiles/dev.yaml#L17)):*
> ```YAML
>       # has dummy secret keys for development and testing; options are
>       # invisible pass, invisible fail, visible pass, visible fail, forced interaction
>       configCaptchaSiteKey: "1x00000000000000000000AA" # visible pass
> ```

This needs to stay.  If it is removed, then when you build for your local  kubernetes cluster it set the site key to "".  As the value said in the file `./deploy/helm/thecombine/charts/frontend/values.yaml`, the value needs to be defined in the profiles.

In general, a blank value should be acceptable for any of the environment variables and should not be interpreted as though the variable was not specified.



_Code quote:_
```YAML
    frontend:
      # https://developers.cloudflare.com/turnstile/troubleshooting/testing/
      # has dummy secret keys for development and testing; options are
      # invisible pass, invisible fail, visible pass, visible fail, forced interaction
      configCaptchaSiteKey: "1x00000000000000000000AA" # visible pass
```

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3332)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[`deploy/scripts/setup_files/profiles/dev.yaml` line 17 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/3332#-O5PDA_x3CM3t51mdK9S:-O5PavMt-jXw0XzqI2My:b-h2z1pd) ([raw file](https://github.com/sillsdev/TheCombine/blob/b964bca877c5c2084df362bac4ffb9f64c1522f5/deploy/scripts/setup_files/profiles/dev.yaml#L17)):*
You make a good point with
> a blank value should be acceptable for any of the environment variables and should not be interpreted as though the variable was not specified.

Does the change to `deploy/helm/thecombine/charts/frontend/templates/env-frontend-configmap.yaml` address that?

**Review by jmgrady — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3332)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[`deploy/scripts/setup_files/profiles/dev.yaml` line 17 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/3332#-O5PDA_x3CM3t51mdK9S:-O5Po37a2d1EvYpbUSSU:bowi9tg) ([raw file](https://github.com/sillsdev/TheCombine/blob/b964bca877c5c2084df362bac4ffb9f64c1522f5/deploy/scripts/setup_files/profiles/dev.yaml#L17)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

You make a good point with
> a blank value should be acceptable for any of the environment variables and should not be interpreted as though the variable was not specified.

Does the change to `deploy/helm/thecombine/charts/frontend/templates/env-frontend-configmap.yaml` address that?
</blockquote></details>

No.  It breaks the deployment.  Please revert this change and the change in `env-frontend-config.yaml`.

**Review by jmgrady — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3332)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[`deploy/scripts/setup_files/profiles/dev.yaml` line 17 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/3332#-O5PDA_x3CM3t51mdK9S:-O5PpgNu7b3ZcYBpr7T8:b-j5kxtv) ([raw file](https://github.com/sillsdev/TheCombine/blob/b964bca877c5c2084df362bac4ffb9f64c1522f5/deploy/scripts/setup_files/profiles/dev.yaml#L17)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

No.  It breaks the deployment.  Please revert this change and the change in `env-frontend-config.yaml`.
</blockquote></details>

It also removes the ability to set the site key to "" which may be desirable when the CAPTCHA is not enabled.

**Review by jmgrady — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3332)* status: all files reviewed, 2 unresolved discussions (waiting on @imnasnainaec)

___
*[`deploy/helm/thecombine/charts/frontend/templates/env-frontend-configmap.yaml` line 14 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/3332#-O5SkiJuAHjVXrSzGAkf:-O5SkiJv6t80SS-mTvNW:bodxlts) ([raw file](https://github.com/sillsdev/TheCombine/blob/0d0117b892610db039291c1aeb38122a325ec5f9/deploy/helm/thecombine/charts/frontend/templates/env-frontend-configmap.yaml#L14)):*
> ```YAML
>   {{- if .Values.configCaptchaSiteKey }}
>   CONFIG_CAPTCHA_SITE_KEY: {{ .Values.configCaptchaSiteKey | quote }}
>   {{- end }}
> ```

Please remove these changes.  They break the deployment.  In addition, they add complexity and adding similar code to the deployment would add more complexity.



_Code quote:_
```YAML
  {{- if .Values.configCaptchaSiteKey }}
  CONFIG_CAPTCHA_SITE_KEY: {{ .Values.configCaptchaSiteKey | quote }}
  {{- end }}
```

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3332)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

___
*[`deploy/helm/thecombine/charts/frontend/templates/env-frontend-configmap.yaml` line 14 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/3332#-O5SkiJuAHjVXrSzGAkf:-O7ZaO7_AEvmFrJeBF26:b-i1xjz2) ([raw file](https://github.com/sillsdev/TheCombine/blob/bd26ff0df0fc2f1e51801a7eb6e444f10fb47a75/deploy/helm/thecombine/charts/frontend/templates/env-frontend-configmap.yaml#L14)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Please remove these changes.  They break the deployment.  In addition, they add complexity and adding similar code to the deployment would add more complexity.
</blockquote></details>

Retracted based on in-Slack conversation.
___
*[`deploy/scripts/setup_files/profiles/dev.yaml` line 17 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/3332#-O5PDA_x3CM3t51mdK9S:-O7Zaf2dAPdtSu1atGMn:b-i1xjz2) ([raw file](https://github.com/sillsdev/TheCombine/blob/b964bca877c5c2084df362bac4ffb9f64c1522f5/deploy/scripts/setup_files/profiles/dev.yaml#L17)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

It also removes the ability to set the site key to "" which may be desirable when the CAPTCHA is not enabled.
</blockquote></details>

Retracted based on in-Slack conversation.

**Review by jmgrady — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3332)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
