### PR TITLE
Frontend font support

### LINKED ISSUE #703: Make available the fonts used by the language picker
TheCombine currently uses for everything the first available font from a few san-serif fonts: Roboto, Noto Sans, Helvetica, Arial, sans-serif. However, the language picker has the user select a font to associate with each of their vernacular and analysis languages (often defaulting to Charis SIL). We store that font selection but do not actually use it.

Some scripts more urgently require font support, as their characters are showing as tofu in the app:
- Miao / Shimenkan

----

Let's support all the (non-grey, non-legacy) fonts in https://software.sil.org/fonts/

...and/or the fonts used in Mui-Language-Picker:
https://github.com/sillsdev/mui-language-picker/blob/master/src/langPicker/fontList.js#L17

----

We should be sure to ask the Audio Project Manager team about lessons they learned when they did this.
https://github.com/sillsdev/transcriber/blob/master/src/crud/fontChoice.ts#L31
https://github.com/sillsdev/transcriber/blob/master/src/components/TranscriptionShow.tsx#L6

----

There's helpful info in this README: https://github.com/sillsdev/Transcribe/tree/master/src/portable/ReactUi/react#adding-images-fonts-and-files

----

We want to lazy load the fonts so we don't include ones that are not needed for a project.

----

[https://mui.com/material-ui/customization/typography/ says](https://mui.com/material-ui/customization/typography/):
> To self-host fonts, download the font files in ttf, woff, and/or woff2 formats and import them into your code.
> This requires that you have a plugin or loader in your build process that can handle loading ttf, woff, and woff2 files. Fonts will not be embedded within your bundle. They will be loaded from your webserver instead of a CDN.

----

https://software.sil.org/fonts/webfonts/ has instructions for self-hosting SIL web fonts

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #703

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2493)

### CODE REVIEW

**Comment by imnasnainaec** [comment]
Giving the css info for all the fonts upfront is a *BAD* idea if we are supporting Internet Explorer, since it loads all the fonts even if they are not used: https://www.stevesouders.com/blog/2009/10/13/font-face-and-performance/

**Comment by imnasnainaec** [comment]
A great way to test this is with language Tangut (`tgx`), mlp font "NotoSansTangut", using text copied from https://fonts.google.com/noto/specimen/Noto+Serif+Tangut, which shows up as tofu in most default fonts: 𗀔𗼘𗁅𗔔𗀄𗀇𗦲𗤶𗊴𗼑𗀂𗧍𗙏𘏫

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 1 of 15 files at r2, 3 of 16 files at r5, 3 of 9 files at r11, 8 of 11 files at r13, 11 of 12 files at r14, 1 of 1 files at r15.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2493)* status: 27 of 68 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[`src/components/App/AppLoggedIn.tsx` line 56 at r15](https://reviewable.io/reviews/sillsdev/TheCombine/2493#-NdGbs4R2ES5-chqOiyS:-NdGbs4R2ES5-chqOiyT:b-fzsxnr) ([raw file](https://github.com/sillsdev/TheCombine/blob/18af4333e3da69ed0ef9261fd84f0505f6579996/src/components/App/AppLoggedIn.tsx#L56)):*
> ```XML
> 
>   useEffect(() => {
>     // Remove this useEffect after the backend update is finished.
> ```

Can this be removed now?

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2493)* status: 19 of 73 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @jasonleenaylor)

___
*[`src/utilities/fontCssUtilities.ts` line 95 at r15](https://reviewable.io/reviews/sillsdev/TheCombine/2493#-NdGe2tD4tzPNoBmIz6p:-NdM6xEp-GY9x-DlXaf2:b-nu57kd) ([raw file](https://github.com/sillsdev/TheCombine/blob/97546f67bf5573692c37ac9b3139f8b762332b68/src/utilities/fontCssUtilities.ts#L95)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Does something need to happen here still?
</blockquote></details>

I added a `RuntimeConfig` method to see if the device is configured to be running offline and only call `getFallbacks` if we are not offline.
I am not (yet) familiar enough with the font css files to know if something needs to be done for the offline case.

Note that I chose to not just rename the `emailServicesEnabled` in anticipation of other users installing _The Combine_ and not wanting to setup the email functions - once we have a good alternative!  Email services can be configured as off by setting the configuration value to `false` or by installing with no `COMBINE_SMTP_USERNAME` defined.

**Comment by imnasnainaec** [comment]
TODO: add the OFL into our license info

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2493)* status: 16 of 74 files reviewed, 2 unresolved discussions (waiting on @jasonleenaylor and @jmgrady)

___
*[`src/components/App/AppLoggedIn.tsx` line 56 at r15](https://reviewable.io/reviews/sillsdev/TheCombine/2493#-NdGbs4R2ES5-chqOiyS:-Ndb4shB8dAn__goLBCj:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/97546f67bf5573692c37ac9b3139f8b762332b68/src/components/App/AppLoggedIn.tsx#L56)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Can this be removed now?
</blockquote></details>

Done.

**Review by jmgrady — CHANGES_REQUESTED** [review]
> Reviewed 2 of 41 files at r3, 2 of 16 files at r5, 1 of 4 files at r23, 3 of 4 files at r24.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2493)* status: 24 of 76 files reviewed, 3 unresolved discussions (waiting on @imnasnainaec and @jasonleenaylor)

___
*[`src/components/App/AppLoggedIn.tsx` line 37 at r24](https://reviewable.io/reviews/sillsdev/TheCombine/2493#-NdeeDi68sAM-WrxFoXq:-NdeeDi7ACkwM9huB1AX:b-468dpl) ([raw file](https://github.com/sillsdev/TheCombine/blob/f751287972911a622b6b9ea79b048cb2f25a5a46/src/components/App/AppLoggedIn.tsx#L37)):*
> ```XML
>       proj1.analysisWritingSystems.length ===
>         proj2.analysisWritingSystems.length
>   );
> ```

This does not seem like a sufficient test for equality.  Shouldn't the test check the contents of the `analysisWritingSystems` arrays instead of just the length?



_Suggestion:_
```XML
      proj1.analysisWritingSystems.length ===
        proj2.analysisWritingSystems.length
```

**Review by jmgrady — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2493)* status: 24 of 76 files reviewed, 4 unresolved discussions (waiting on @imnasnainaec and @jasonleenaylor)

___
*[`src/components/DataEntry/ExistingDataTable/ImmutableExistingData.tsx` line 9 at r25](https://reviewable.io/reviews/sillsdev/TheCombine/2493#-NdetfAM5a_YCpcwB9s2:-NdetfAM5a_YCpcwB9s3:b9pm3gc) ([raw file](https://github.com/sillsdev/TheCombine/blob/3db9bdd12ddd637373c4cae939bded36592c6826/src/components/DataEntry/ExistingDataTable/ImmutableExistingData.tsx#L9)):*
> ```XML
>   vernacular: string;
>   gloss: string;
>   glossLang?: string;
> ```

This is only used once in the application code and the `glossLang` is never `undefined`.  Recommend changing to:
```
interface ImmutableExistingDataProps {
  vernacular: string;
  gloss: Gloss;
}
```



_Code quote:_
```XML
  gloss: string;
  glossLang?: string;
```

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2493)* status: 22 of 77 files reviewed, 4 unresolved discussions (waiting on @jasonleenaylor and @jmgrady)

___
*[`src/components/App/AppLoggedIn.tsx` line 37 at r24](https://reviewable.io/reviews/sillsdev/TheCombine/2493#-NdeeDi68sAM-WrxFoXq:-Ndf0eSC-tuGHyf3ePMw:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/f751287972911a622b6b9ea79b048cb2f25a5a46/src/components/App/AppLoggedIn.tsx#L37)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

This does not seem like a sufficient test for equality.  Shouldn't the test check the contents of the `analysisWritingSystems` arrays instead of just the length?
</blockquote></details>

Done.
___
*[`src/components/DataEntry/ExistingDataTable/ImmutableExistingData.tsx` line 9 at r25](https://reviewable.io/reviews/sillsdev/TheCombine/2493#-NdetfAM5a_YCpcwB9s2:-Ndf2DL75crD--QScrcS:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/3db9bdd12ddd637373c4cae939bded36592c6826/src/components/DataEntry/ExistingDataTable/ImmutableExistingData.tsx#L9)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

This is only used once in the application code and the `glossLang` is never `undefined`.  Recommend changing to:
```
interface ImmutableExistingDataProps {
  vernacular: string;
  gloss: Gloss;
}
```
</blockquote></details>

Done.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2493)* status: 73 of 77 files reviewed, 2 unresolved discussions (waiting on @jasonleenaylor and @jmgrady)

___
*[`src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/GlossCell.tsx` line 70 at r26](https://reviewable.io/reviews/sillsdev/TheCombine/2493#-Ndf7p1eA3dAvYPJxG0E:-NdfEX4bCZUSLnvw9JB6:b-a575j7) ([raw file](https://github.com/sillsdev/TheCombine/blob/9887dae3b7722ddc6851ce26cdc547f5b79a876a/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/GlossCell.tsx#L70)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Should this also use the font?
</blockquote></details>

No, as the content is UI text, not gloss text.

**Review by jmgrady — COMMENTED** [review]
> Reviewed 1 of 3 files at r30.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2493)* status: 72 of 77 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

___
*[`src/types/runtimeConfig.ts` line 80 at r26](https://reviewable.io/reviews/sillsdev/TheCombine/2493#-Ndf8RXyDmS5K1eUeBxc:-NdfbA7u16iifGCGHmOb:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/9887dae3b7722ddc6851ce26cdc547f5b79a876a/src/types/runtimeConfig.ts#L80)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

This is confusing when paired with the offline boolean in the RuntimeConfig items.
Maybe use isOffline for the method?
</blockquote></details>

Done.

**Review by jmgrady — APPROVED** [review]
> Reviewed 1 of 1 files at r29, 1 of 3 files at r30, 2 of 2 files at r31, 2 of 2 files at r32, 1 of 1 files at r33, 1 of 1 files at r34, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2493)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
