### PR TITLE
Increase backend unit test coverage

### PR DESCRIPTION
**Pull request by johnthagen**
Add unit test coverage for:

-  `User` `Model`
- `Project` `CustomField`
- `Project` `InviteTokens`
- Remove unused `UserCreatedProject.Clone()`
- Unicode punctuation for `Sanitization.MakeFriendlyForPath()`
- `Helper.Time`
- `Helper.Sanitization`

Follow on to #1271

After this PR, all `Model`s have 100% test coverage as are `Helper.Time` and `Helper.Sanitization`.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1307)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 4 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1307)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @johnthagen)

___
*[Backend.Tests/Helper/TimeTests.cs, line 24 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1307#-MhJh-IuCtK2O-HbtYOn:-MhJh-IuCtK2O-HbtYOo:b-q1ym48) ([raw file](https://github.com/sillsdev/thecombine/blob/3fa1431a3ea0d5b0eeb716ab5cdd235d519784f2/Backend.Tests/Helper/TimeTests.cs#L24)):*
> ```Smalltalk
>             Assert.That(time.Contains("T"));
>             Assert.That(time.EndsWith("Z"));
>             Assert.That(DateTime.Now, Is.EqualTo(DateTime.Parse(time)).Within(TimeSpan.FromMinutes(5)));
> ```

`FromMinutes(5)` seems like orders-of-magnitude massive overkill.
___
*[Backend.Tests/Models/ProjectTests.cs, line 91 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1307#-MhJhmpf-dVV-Cz2iBXj:-MhJhmpf-dVV-Cz2iBXk:bd87xxt) ([raw file](https://github.com/sillsdev/thecombine/blob/3fa1431a3ea0d5b0eeb716ab5cdd235d519784f2/Backend.Tests/Models/ProjectTests.cs#L91)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>             var domain = new SemanticDomain { Name = Name, Id = "1", Description = "text" };
>             project.SemanticDomains.Add(domain);
>             var customField = new CustomField { Name = Name, Type = "type" };
>             project.CustomFields.Add(customField);
> ```
</details>

Though `SemanticDomain`s and `CustomField`s both have a `Name` field, that's independent from the `Project`'s `Name`, so should we use different strings to deter cloning from coping from the wrong fields?
___
*[Backend.Tests/Models/UserTests.cs, line 46 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1307#-MhJhTtJ1grMsTfHN8GI:-MhJhTtJ1grMsTfHN8GJ:b-93493w) ([raw file](https://github.com/sillsdev/thecombine/blob/3fa1431a3ea0d5b0eeb716ab5cdd235d519784f2/Backend.Tests/Models/UserTests.cs#L46)):*
> ```
>         private const string Username = "Henry";
>         private const string Password = "Password";
> ```
These `const`s are unused.

**Comment by johnthagen** [comment]
___
*[Backend.Tests/Helper/TimeTests.cs, line 24 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1307#-MhJh-IuCtK2O-HbtYOn:-MhYPEIn7-JU6jRSEJMv:b-2m23za) ([raw file](https://github.com/sillsdev/thecombine/blob/3fa1431a3ea0d5b0eeb716ab5cdd235d519784f2/Backend.Tests/Helper/TimeTests.cs#L24)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`FromMinutes(5)` seems like orders-of-magnitude massive overkill.
</blockquote></details>

Done.

Since this test is inherently not 100% reproducible (if you were running on a computer that was extremely slow/was running other heavy processes), I was trying to ensure that the test couldn't reasonably be flaky while still smoke testing that the time was reasonable.

I've changed it to 10 seconds.

**Comment by johnthagen** [comment]
___
*[Backend.Tests/Models/ProjectTests.cs, line 91 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1307#-MhJhmpf-dVV-Cz2iBXj:-MhYRbFECGOeWZyhxpbj:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/3fa1431a3ea0d5b0eeb716ab5cdd235d519784f2/Backend.Tests/Models/ProjectTests.cs#L91)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>             var domain = new SemanticDomain { Name = Name, Id = "1", Description = "text" };
>             project.SemanticDomains.Add(domain);
>             var customField = new CustomField { Name = Name, Type = "type" };
>             project.CustomFields.Add(customField);
> ```
Though `SemanticDomain`s and `CustomField`s both have a `Name` field, that's independent from the `Project`'s `Name`, so should we use different strings to deter cloning from coping from the wrong fields?
</blockquote></details>

Done

**Comment by johnthagen** [comment]
___
*[Backend.Tests/Models/UserTests.cs, line 46 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1307#-MhJhTtJ1grMsTfHN8GI:-MhYS1pe3-u4PwTAkEeN:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/3fa1431a3ea0d5b0eeb716ab5cdd235d519784f2/Backend.Tests/Models/UserTests.cs#L46)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>         private const string Username = "Henry";
>         private const string Password = "Password";
> ```
These `const`s are unused.
</blockquote></details>

Done.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1307)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Pull request merged**
