### PR TITLE
Use absolute TS imports

### LINKED ISSUE #926: Use absolute TypeScript imports
See: https://justinnoel.dev/2019/06/18/configuring-react-absolute-imports-for-typescript/

This would allow us to use consistent, absolute paths for imports, which I think would make the code easier to follow.

An example that could be improved:

https://github.com/sillsdev/TheCombine/blob/7f06e935555e235cc4a3812bf761b891033a54ca/src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesActions.tsx#L1-L5

### PR DESCRIPTION
**Pull request by johnthagen**
Closes #926 

Other changes

- Rename `history.ts` to `browserHistory.ts` to avoid a name collision with the `history` `npm` package.
- Ensure imports are grouped into third-party and local, separated by a newline
- Rename `UserManagment` class and directory to `UserManagement` (fix typo)
- Upgrade to Prettier 2.2.1

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/929)

### CODE REVIEW

**Comment by johnthagen** [comment]
A good example of something that can be improved:

```ts
import theme from "../../../../types/theme";
import { Word } from "../../../../types/word";
import DomainCell from "../../../../goals/ReviewEntries/ReviewEntriesComponent/CellComponents/DomainCell";
import SenseCell from "../../../../goals/ReviewEntries/ReviewEntriesComponent/CellComponents/SenseCell";
import { parseWord } from "../../../../goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesTypes";
```

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 2 of 30 files at r1, 156 of 254 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/929)* status: 158 of 256 files reviewed, 9 unresolved discussions (waiting on @johnthagen)

___
*[docs/ts_style_guide.md, line 20 at r2](https://reviewable.io/reviews/sillsdev/thecombine/929#-MRez37S2iHeVcmyeT7P:-MRez37S2iHeVcmyeT7Q:b-yafi62) ([raw file](https://github.com/sillsdev/thecombine/blob/177905b3e7553e677258050ebf08117aff7172d2/docs/ts_style_guide.md#L20)):*
> ```Markdown
> - [`type` vs `interface`](#type-vs-interface)
> - [One-line `if` statements](#one-line-if-statements)
> ```

Add `imports`s to list.
___
*[src/index.tsx, line 14 at r2](https://reviewable.io/reviews/sillsdev/thecombine/929#-MRf-qAxCk4k09bJH5X_:-MRf-qAy5dq_YJQbESsu:b-g1wcve) ([raw file](https://github.com/sillsdev/thecombine/blob/177905b3e7553e677258050ebf08117aff7172d2/src/index.tsx#L14)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> import App from "components/App/component";
> import * as serviceWorker from "serviceWorker";
> import { store, persistor } from "store";
> import globalTranslations from "resources/translations.json";
> import history from "browserHistory";
> ```
</details>

*[src/components/DataEntry/index.tsx, line 4 at r2](https://reviewable.io/reviews/sillsdev/thecombine/929#-MRf0l7J3z222MSC0yRj:-MRf0l7J3z222MSC0yRk:b-7356aw) ([raw file](https://github.com/sillsdev/thecombine/blob/177905b3e7553e677258050ebf08117aff7172d2/src/components/DataEntry/index.tsx#L4)):*
> ```
> import { StoreState } from "types";
> import DataEntryComponent from "components/DataEntry/DataEntryComponent";
> ```

*[src/components/DataEntry/DataEntryHeader/DataEntryHeader.tsx, line 11 at r2](https://reviewable.io/reviews/sillsdev/thecombine/929#-MRf0xUuDEfP16kotzuJ:-MRf0xUv8JQZKTKMJ3Ax:b-metmqj) ([raw file](https://github.com/sillsdev/thecombine/blob/177905b3e7553e677258050ebf08117aff7172d2/src/components/DataEntry/DataEntryHeader/DataEntryHeader.tsx#L11)):*
> ```
> import theme from "types/theme";
> import DomainTree from "types/SemanticDomain";
> ```

*[src/components/GoalTimeline/GoalHistory/GoalHistoryComponent.tsx, line 5 at r2](https://reviewable.io/reviews/sillsdev/thecombine/929#-MRf1wza93yXErG7WNxU:-MRf1wza93yXErG7WNxV:bhv5ns7) ([raw file](https://github.com/sillsdev/thecombine/blob/177905b3e7553e677258050ebf08117aff7172d2/src/components/GoalTimeline/GoalHistory/GoalHistoryComponent.tsx#L5)):*
> ```
> import { Goal } from "types/goals";
> import BaseGoalSelect from "goals/DefaultGoal/BaseGoalWidget/BaseGoalWidget";
> ```

*[src/components/GoalTimeline/GoalHistory/index.tsx, line 5 at r2](https://reviewable.io/reviews/sillsdev/thecombine/929#-MRf21Qu-URwqx2NP1Cc:-MRf21Qu-URwqx2NP1Cd:bmsweeh) ([raw file](https://github.com/sillsdev/thecombine/blob/177905b3e7553e677258050ebf08117aff7172d2/src/components/GoalTimeline/GoalHistory/index.tsx#L5)):*
> ```
> import { StoreState } from "types";
> import { GoalHistoryState } from "types/goals";
> import GoalHistory from "components/GoalTimeline/GoalHistory/GoalHistoryComponent";
> ```

*[src/components/GoalTimeline/GoalHistory/tests/GoalHistoryComponent.test.tsx, line 8 at r2](https://reviewable.io/reviews/sillsdev/thecombine/929#-MRf29cG1E2c-0d2CL4S:-MRf29cG1E2c-0d2CL4T:bgp6spv) ([raw file](https://github.com/sillsdev/thecombine/blob/177905b3e7553e677258050ebf08117aff7172d2/src/components/GoalTimeline/GoalHistory/tests/GoalHistoryComponent.test.tsx#L8)):*
> ```
> import GoalHistory from "components/GoalTimeline/GoalHistory";
> import { defaultState } from "components/GoalTimeline/DefaultState";
> ```

*[src/components/GoalTimeline/GoalSuggestions/GoalSuggestionsComponent.tsx, line 5 at r2](https://reviewable.io/reviews/sillsdev/thecombine/929#-MRf2EU094btnkgQEfuQ:-MRf2EU094btnkgQEfuR:b-ef0yil) ([raw file](https://github.com/sillsdev/thecombine/blob/177905b3e7553e677258050ebf08117aff7172d2/src/components/GoalTimeline/GoalSuggestions/GoalSuggestionsComponent.tsx#L5)):*
> ```
> import { Goal } from "types/goals";
> import BaseGoalSelect from "goals/DefaultGoal/BaseGoalWidget/BaseGoalWidget";
> ```

Alphabetize?
___
*[src/components/ProjectScreen/ChooseProject/tests/ChooseProjectComponent.test.tsx, line 7 at r2](https://reviewable.io/reviews/sillsdev/thecombine/929#-MRf3BzL99Y3yheCbX55:-MRf3BzL99Y3yheCbX56:b-36qn1b) ([raw file](https://github.com/sillsdev/thecombine/blob/177905b3e7553e677258050ebf08117aff7172d2/src/components/ProjectScreen/ChooseProject/tests/ChooseProjectComponent.test.tsx#L7)):*
> ```
> /index
> ```
Can drop the `/index`.
___
*[src/components/ProjectSettings/ProjectImport/ProjectImport.tsx, line 12 at r2](https://reviewable.io/reviews/sillsdev/thecombine/929#-MRf3_3N7t6aI2tMi6ev:-MRf3_3N7t6aI2tMi6ew:bgrok6m) ([raw file](https://github.com/sillsdev/thecombine/blob/177905b3e7553e677258050ebf08117aff7172d2/src/components/ProjectSettings/ProjectImport/ProjectImport.tsx#L12)):*
> ```
> import { Project } from "types/project";
> import FileInputButton from "components/Buttons/FileInputButton";
> ```
Alphabetize?

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 65 of 254 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/929)* status: 223 of 256 files reviewed, 12 unresolved discussions (waiting on @johnthagen)

___
*[src/goals/CharInventoryCreation/components/CharacterDetail/CharacterWords/index.tsx, line 4 at r2](https://reviewable.io/reviews/sillsdev/thecombine/929#-MRf4xMWBmoVSk5O4HxP:-MRf4xMWBmoVSk5O4HxQ:b-6kg4r) ([raw file](https://github.com/sillsdev/thecombine/blob/177905b3e7553e677258050ebf08117aff7172d2/src/goals/CharInventoryCreation/components/CharacterDetail/CharacterWords/index.tsx#L4)):*
> ```
> import { StoreState } from "types";
> import CharacterWords from "goals/CharInventoryCreation/components/CharacterDetail/CharacterWords/CharacterWordsComponent";
> ```

*[src/goals/CharInventoryCreation/components/CharacterList/CharacterStatusText.tsx, line 6 at r2](https://reviewable.io/reviews/sillsdev/thecombine/929#-MRf57ab9jmCKmHlU2z4:-MRf57ab9jmCKmHlU2z5:bmrew86) ([raw file](https://github.com/sillsdev/thecombine/blob/177905b3e7553e677258050ebf08117aff7172d2/src/goals/CharInventoryCreation/components/CharacterList/CharacterStatusText.tsx#L6)):*
> ```
> import { accepted, rejected } from "types/theme";
> import { characterStatus } from "goals/CharInventoryCreation/CharacterInventoryReducer";
> ```

*[src/goals/DefaultGoal/BaseGoalScreen/index.tsx, line 7 at r2](https://reviewable.io/reviews/sillsdev/thecombine/929#-MRf5j9m0MwEF-GL0ID-:-MRf5j9m0MwEF-GL0ID0:bjxrg9n) ([raw file](https://github.com/sillsdev/thecombine/blob/177905b3e7553e677258050ebf08117aff7172d2/src/goals/DefaultGoal/BaseGoalScreen/index.tsx#L7)):*
> ```
> import { StoreState } from "types";
> import { Goal, GoalProps } from "types/goals";
> import BaseGoalScreen from "goals/DefaultGoal/BaseGoalScreen/BaseGoalScreen";
> ```

Alphabetize?
___
*[src/goals/MergeDupGoal/MergeDupStep/index.tsx, line 5 at r2](https://reviewable.io/reviews/sillsdev/thecombine/929#-MRf67qw-IfqySUWr_5O:-MRf67qw-IfqySUWr_5P:b74i67h) ([raw file](https://github.com/sillsdev/thecombine/blob/177905b3e7553e677258050ebf08117aff7172d2/src/goals/MergeDupGoal/MergeDupStep/index.tsx#L5)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> import {
>   asyncAdvanceStep,
>   asyncRefreshWords,
> } from "components/GoalTimeline/GoalsActions";
> ```
</details>

Move from third-party to local imports.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 17 of 254 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/929)* status: 240 of 256 files reviewed, 16 unresolved discussions (waiting on @johnthagen)

___
*[src/components/GoalTimeline/GoalSuggestions/index.tsx, line 4 at r2](https://reviewable.io/reviews/sillsdev/thecombine/929#-MRfBGz56vRL5tq3_a7t:-MRfBGz56vRL5tq3_a7u:b-cldgyf) ([raw file](https://github.com/sillsdev/thecombine/blob/177905b3e7553e677258050ebf08117aff7172d2/src/components/GoalTimeline/GoalSuggestions/index.tsx#L4)):*
> ```
> import { StoreState } from "types";
> import { GoalSuggestionsState } from "types/goals";
> import GoalSuggestions from "components/GoalTimeline/GoalSuggestions/GoalSuggestionsComponent";
> ```

*[src/components/GoalTimeline/GoalSuggestions/tests/GoalSuggestions.test.tsx, line 4 at r2](https://reviewable.io/reviews/sillsdev/thecombine/929#-MRfBLr0EQmV2ouXW00I:-MRfBLr0EQmV2ouXW00J:b-viczkq) ([raw file](https://github.com/sillsdev/thecombine/blob/177905b3e7553e677258050ebf08117aff7172d2/src/components/GoalTimeline/GoalSuggestions/tests/GoalSuggestions.test.tsx#L4)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> import configureMockStore from "redux-mock-store";
> import { Provider } from "react-redux";
> 
> import GoalSuggestions from "components/GoalTimeline/GoalSuggestions";
> import { defaultState } from "components/GoalTimeline/DefaultState";
> ```
</details>


Alphabetize?

**Review by johnthagen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/929)* status: 240 of 256 files reviewed, 16 unresolved discussions (waiting on @imnasnainaec and @johnthagen)

___
*[docs/ts_style_guide.md, line 20 at r2](https://reviewable.io/reviews/sillsdev/thecombine/929#-MRez37S2iHeVcmyeT7P:-MRfu1CFEtNpJ76CvZoo:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/177905b3e7553e677258050ebf08117aff7172d2/docs/ts_style_guide.md#L20)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Add `imports`s to list.
</blockquote></details>

Done.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 16 of 18 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/929)* status: 253 of 256 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @johnthagen)

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 18 files at r3, 2 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/929)* status: all files reviewed, 1 unresolved discussion (waiting on @johnthagen)

**Review by imnasnainaec — COMMENTED** [review]
Where is `scripts/https_server.py` from or what's it for?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/929#-:-MRfy2UM1klmC6UjFPxL:batprfo)* status: all files reviewed, 1 unresolved discussion (waiting on @johnthagen)

**Pull request merged**
