### PR TITLE
Add project owner permission

### PR DESCRIPTION
**Pull request by imnasnainaec**
Groundwork for #1253 

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1257)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[Backend/Controllers/ProjectController.cs, line 121 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1257#-MekvflT22HFiyAT1bdT:-MekvflT22HFiyAT1bdU:b-5t4h3m) ([raw file](https://github.com/sillsdev/thecombine/blob/01f214c1e21ccd3aa0d6188b74440b9abff8836d/Backend/Controllers/ProjectController.cs#L121)):*
> ```Smalltalk
>                 Permissions = new List<Permission>
>                 {
>                     Permission.Owner,
> ```

I believe we need to regenerate the frontend OpenAPI bindings. At the very least, it will update the name of the generated TS `enum` and we may need to update references to it if they are used.

**Review by johnthagen — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1257)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1257)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @johnthagen)

___
*[Backend/Controllers/ProjectController.cs, line 121 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1257#-MekvflT22HFiyAT1bdT:-MelD9qU1DEOH5q9dvi5:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/01f214c1e21ccd3aa0d6188b74440b9abff8836d/Backend/Controllers/ProjectController.cs#L121)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I believe we need to regenerate the frontend OpenAPI bindings. At the very least, it will update the name of the generated TS `enum` and we may need to update references to it if they are used.
</blockquote></details>

Done.

**Comment by johnthagen** [comment]
___
*[Backend/Models/UserRole.cs, line 78 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1257#-MepTZqj9hArozbb8r4Y:-MepTZqj9hArozbb8r4Z:b-ciz1my) ([raw file](https://github.com/sillsdev/thecombine/blob/e881b505102535bf23bce48a790c12f04c840949/Backend/Models/UserRole.cs#L78)):*
> ```Smalltalk
>     {
>         /// <summary> Project Owner by default should be given to the user who created the project </summary>
>         Owner = 6,
> ```

For completeness and to avoid drift between the two definitions, this should also be added to `deploy/roles/combine_maintenence/files/combine_app.py` `class Permission`.

**Review by johnthagen — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1257)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1257)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @johnthagen)

___
*[Backend/Models/UserRole.cs, line 78 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1257#-MepTZqj9hArozbb8r4Y:-Meq2ih2Dpar05NKRRa8:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/e881b505102535bf23bce48a790c12f04c840949/Backend/Models/UserRole.cs#L78)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

For completeness and to avoid drift between the two definitions, this should also be added to `deploy/roles/combine_maintenence/files/combine_app.py` `class Permission`.
</blockquote></details>

Done.

**Review by johnthagen — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1257)* status: all files reviewed, 1 unresolved discussion (waiting on @johnthagen)

**Review by JacobHaimes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1257)* status: all files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @johnthagen)

___
*[Backend/Services/PermissionService.cs, line 75 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1257#-Mf494Kx2HKVUNVzC2ls:-Mf494Kx2HKVUNVzC2lt:b-muccwu) ([raw file](https://github.com/sillsdev/thecombine/blob/f25cb0b6bda688af0b857a7ee33471c7970a38ed/Backend/Services/PermissionService.cs#L75)):*
> ```Smalltalk
>                 return false;
>             }
>             return user.IsAdmin;
> ```

Is there is difference between Admin and Owner or are they the same thing? If they are the same would it make sense to change for example user.IsAdmin to user.IsOwner?

**Review by jasonleenaylor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1257)* status: all files reviewed, 2 unresolved discussions (waiting on @JacobHaimes and @johnthagen)

___
*[Backend/Services/PermissionService.cs, line 75 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1257#-Mf494Kx2HKVUNVzC2ls:-Mf4Ahu46cnxNpXohG0I:b2601ck) ([raw file](https://github.com/sillsdev/thecombine/blob/f25cb0b6bda688af0b857a7ee33471c7970a38ed/Backend/Services/PermissionService.cs#L75)):*
<details><summary><i>Previously, JacobHaimes wrote…</i></summary><blockquote>

Is there is difference between Admin and Owner or are they the same thing? If they are the same would it make sense to change for example user.IsAdmin to user.IsOwner?
</blockquote></details>

There is a difference, the Owner should always be an Admin, but there can be more than one Admin (once the 3 changes underway are complete)

**Comment by imnasnainaec** [comment]
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1257)_ status: all files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @johnthagen)
> 
> _[Backend/Services/PermissionService.cs, line 75 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1257#-Mf494Kx2HKVUNVzC2ls:-Mf494Kx2HKVUNVzC2lt:b-muccwu) ([raw file](https://github.com/sillsdev/thecombine/blob/f25cb0b6bda688af0b857a7ee33471c7970a38ed/Backend/Services/PermissionService.cs#L75)):_
> 
> > ```smalltalk
> >                 return false;
> >             }
> >             return user.IsAdmin;
> > ```
> 
> Is there is difference between Admin and Owner or are they the same thing? If they are the same would it make sense to change for example user.IsAdmin to user.IsOwner?

@JacobHaimes The `IsAdmin` feature of a user refers to being a Site Admin, and is independent of project permissions.

**Pull request merged**
