### PR TITLE
[AudioPlayer] Catch 2-finger mousepad tap as right click

### PR DESCRIPTION
**Pull request by imnasnainaec**
User can change speaker of an audio recording by right-clicking on the AudioPlayer green triangle icon. However, a multi-finger click/tap on a mousepad was overlooked.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2943)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
I haven't pulled and run this, just reading the code I'd want to verify that regular mouse behavior isn't intercepted or ignored by adding the onMouseDown handling. (I would not suspect it is, but I would want to check). Otherwise :LGTM:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2943#-:-NqEGVzSBLF28cB2n9HH:br17lqu)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Comment by imnasnainaec** [comment]
> I haven't pulled and run this, just reading the code I'd want to verify that regular mouse behavior isn't intercepted or ignored by adding the onMouseDown handling. (I would not suspect it is, but I would want to check). Otherwise :LGTM:
> 
> > Reviewed 1 of 1 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2943#-:-NqEGVzSBLF28cB2n9HH:br17lqu)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

I've checked it with a one-finger tap on a mousepad, but should also check it with a traditional plug-in mouse.

**Comment by imnasnainaec** [comment]
> > I haven't pulled and run this, just reading the code I'd want to verify that regular mouse behavior isn't intercepted or ignored by adding the onMouseDown handling. (I would not suspect it is, but I would want to check). Otherwise :lgtm:
> > > Reviewed 1 of 1 files at r1, all commit messages.
> > > _[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2943#-:-NqEGVzSBLF28cB2n9HH:br17lqu)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)
> 
> I've checked it with a one-finger tap on a mousepad, but should also check it with a traditional plug-in mouse.

Just tested it out with my USB Bluetooth mouse and it works as expected.

**Review by jasonleenaylor — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2943#-:-NqT7lteAmeZdTbGu_LC:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
