### PR TITLE
[DataEntryTable, RecentEntry] Add/edit note; Confirm deletion

### LINKED ISSUE #783: Add notes during data entry
Follow-up to #755

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #783 

Since there is only one note per entry (not one per sense), notes are only available with RecentEntry and not with NewEntry to avoid conflicts in the case that NewEntry becomes a new sense of an existing entry.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/784)

### CODE REVIEW

**Comment by imnasnainaec** [comment]
Current ui: the note icon is different depending on whether there is any note text. If there is, mouse-over reveals the note text.  Click on the icon to add/edit the entry's note.
Screen Shot 2020-10-28 at 18 15 26
Screen Shot 2020-10-28 at 18 18 25

My one concern is that somebody might delete trying to delete the note. If this is a valid issue, then a popup confirmation should be added for deleting the row.

**Review by jmgrady — COMMENTED** [review]
> Reviewed 5 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/784)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[src/components/DataEntry/DataEntryTable/DataEntryTable.tsx, line 187 at r2](https://reviewable.io/reviews/sillsdev/thecombine/784#-MKowkBQ53KDvavVlfYb:-MKowkBQ53KDvavVlfYc:bkdneh) ([raw file](https://github.com/sillsdev/thecombine/blob/0eb7c7d12bad308bb118bc7a85f2f13cc1dbe67b/src/components/DataEntry/DataEntryTable/DataEntryTable.tsx#L187)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     audioURLs?: string[]
>   ) {
>     let updatedWord = await this.updateWordInBackend(wordToUpdate);
>     let updatedWordId = updatedWord.id;
>     if (audioURLs && audioURLs.length) {
> ```
</details>

These changes seem to be from another PR.
___
*[src/components/DataEntry/DataEntryTable/RecentEntry/EntryNote.tsx, line 57 at r2](https://reviewable.io/reviews/sillsdev/thecombine/784#-MKp0LMXAlikEo7HmuF9:-MKp0LMXAlikEo7HmuFA:b-yx32cf) ([raw file](https://github.com/sillsdev/thecombine/blob/0eb7c7d12bad308bb118bc7a85f2f13cc1dbe67b/src/components/DataEntry/DataEntryTable/RecentEntry/EntryNote.tsx#L57)):*
> ```
> onConfirm={this.props.updateNote}
> ```
It appears that the noteOpen state does not get set to "false" when the user presses "Confirm".  Is this correct or am I confused?

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/784)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[src/components/DataEntry/DataEntryTable/DataEntryTable.tsx, line 187 at r2](https://reviewable.io/reviews/sillsdev/thecombine/784#-MKowkBQ53KDvavVlfYb:-MKp5UfDAp7febg5-Gye:b-xdemid) ([raw file](https://github.com/sillsdev/thecombine/blob/0eb7c7d12bad308bb118bc7a85f2f13cc1dbe67b/src/components/DataEntry/DataEntryTable/DataEntryTable.tsx#L187)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

> ```
>     audioURLs?: string[]
>   ) {
>     let updatedWord = await this.updateWordInBackend(wordToUpdate);
>     let updatedWordId = updatedWord.id;
>     if (audioURLs && audioURLs.length) {
> ```
These changes seem to be from another PR.
</blockquote></details>

This was intentional, since I needed a simplified form of this function and saw a way to remove unnecessary specifications of `audioURLs` and unnecessary calls to `addAudiosToBackend`.
___
*[src/components/DataEntry/DataEntryTable/RecentEntry/EntryNote.tsx, line 57 at r2](https://reviewable.io/reviews/sillsdev/thecombine/784#-MKp0LMXAlikEo7HmuF9:-MKp6tGGB0JDT47bZ4RP:bwhesnw) ([raw file](https://github.com/sillsdev/thecombine/blob/0eb7c7d12bad308bb118bc7a85f2f13cc1dbe67b/src/components/DataEntry/DataEntryTable/RecentEntry/EntryNote.tsx#L57)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

> ```
> onConfirm={this.props.updateNote}
> ```
It appears that the noteOpen state does not get set to "false" when the user presses "Confirm".  Is this correct or am I confused?
</blockquote></details>

The function names were misleading and have been changed. Within `EditTextDialog`, there is logic handling when to update and when to close (for which I'm about to add unit tests): 
* if confirm is clicked but no changes are made or cancel is clicked, then `props.close()` is called. 
* if confirm is clicked and changes were made, then `props.updateText()` is called.

**Review by jmgrady — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/784)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/784)* status: 8 of 9 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[src/components/DataEntry/DataEntryTable/RecentEntry/EntryNote.tsx, line 57 at r2](https://reviewable.io/reviews/sillsdev/thecombine/784#-MKp0LMXAlikEo7HmuF9:-MKpazzn2NuhYG6hOZN_:b-7riskc) ([raw file](https://github.com/sillsdev/thecombine/blob/0eb7c7d12bad308bb118bc7a85f2f13cc1dbe67b/src/components/DataEntry/DataEntryTable/RecentEntry/EntryNote.tsx#L57)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

The function names were misleading and have been changed. Within `EditTextDialog`, there is logic handling when to update and when to close (for which I'm about to add unit tests): 
* if confirm is clicked but no changes are made or cancel is clicked, then `props.close()` is called. 
* if confirm is clicked and changes were made, then `props.updateText()` is called.
</blockquote></details>

I'm as yet unable to open modals/dialogs within a jest test, but I think the tests I already have are sufficient for now.

**Review by jmgrady — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/784)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by imnasnainaec** [comment]
Added button for clearing text:
Screen Shot 2020-10-29 at 15 05 02

**Review by jmgrady — APPROVED** [review]
> Reviewed 5 of 6 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/784)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[src/resources/translations.json, line 627 at r6](https://reviewable.io/reviews/sillsdev/thecombine/784#-MKtCxKeBDERbN-1bNr5:-MKtCxKeBDERbN-1bNr6:bafb7ac) ([raw file](https://github.com/sillsdev/thecombine/blob/71e5e15c7fd7e6c607a3a7c5720d258ccf18a13d/src/resources/translations.json#L627)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     "deleteWarning": [
>       "This will be permanently deleted!",
>       "¡Esto se eliminará permanentemente!",
>       "Cela sera définitivement supprimé !"
>     ],
> ```
</details>


Consider splitting out the delete warnings for the different uses and passing in the text id when the dialog is created.

Although the appropriate text for deleting the note and deleting a word can be the same in English, that may not be true for all languages, for example, might the note text be considered a plural object in some languages?  Even in English with have "Government" as singular in the U.S. and plural in Great Britain.

In addition,  it would allow us to have more meaningful text for the user:
 - This word will be permanently deleted
 - This note will be permanently deleted

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/784)* status: 8 of 12 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[src/resources/translations.json, line 627 at r6](https://reviewable.io/reviews/sillsdev/thecombine/784#-MKtCxKeBDERbN-1bNr5:-MKto5tr3jXw4oK15Oab:b-50h2qv) ([raw file](https://github.com/sillsdev/thecombine/blob/71e5e15c7fd7e6c607a3a7c5720d258ccf18a13d/src/resources/translations.json#L627)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

> ```
>     "deleteWarning": [
>       "This will be permanently deleted!",
>       "¡Esto se eliminará permanentemente!",
>       "Cela sera définitivement supprimé !"
>     ],
> ```

Consider splitting out the delete warnings for the different uses and passing in the text id when the dialog is created.

Although the appropriate text for deleting the note and deleting a word can be the same in English, that may not be true for all languages, for example, might the note text be considered a plural object in some languages?  Even in English with have "Government" as singular in the U.S. and plural in Great Britain.

In addition,  it would allow us to have more meaningful text for the user:
 - This word will be permanently deleted
 - This note will be permanently deleted
</blockquote></details>

Good points. Done.

**Review by jmgrady — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/784#-:-MKtowo82ilabtlyUUrO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/RecentEntry/EntryNote.tsx, line 21 at r7](https://reviewable.io/reviews/sillsdev/thecombine/784#-MKtpOBc95_4FQWSTncz:-MKtpOBc95_4FQWSTnd-:b99swsh) ([raw file](https://github.com/sillsdev/thecombine/blob/2e823dd635d35861563335ac537cbaa0f3d32696/src/components/DataEntry/DataEntryTable/RecentEntry/EntryNote.tsx#L21)):*
> ```XML
>  * A note adding/editing button
>  */
> export default class EntryNote extends React.Component<
> ```

This is more of a high level comment. The React team is recommending that for new code, functional components be used for a variety of reasons: https://reactjs.org/docs/hooks-intro.html#motivation

I'd recommend that going forward we try as much as possible to use functional components and hooks rather than class-based components. At work, I was able to totally convert a small React app over to functional components and didn't find a need for any class-based ones.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/784)* status: 10 of 12 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[src/components/DataEntry/DataEntryTable/RecentEntry/EntryNote.tsx, line 21 at r7](https://reviewable.io/reviews/sillsdev/thecombine/784#-MKtpOBc95_4FQWSTncz:-MKtzNMk4HsNbMppZ_Lx:bw1f6zo) ([raw file](https://github.com/sillsdev/thecombine/blob/2e823dd635d35861563335ac537cbaa0f3d32696/src/components/DataEntry/DataEntryTable/RecentEntry/EntryNote.tsx#L21)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This is more of a high level comment. The React team is recommending that for new code, functional components be used for a variety of reasons: https://reactjs.org/docs/hooks-intro.html#motivation

I'd recommend that going forward we try as much as possible to use functional components and hooks rather than class-based components. At work, I was able to totally convert a small React app over to functional components and didn't find a need for any class-based ones.
</blockquote></details>

Good point. I did that with another class in the pr, but it is fitting (and cleaner) for this one too.

**Review by johnthagen — APPROVED** [review]
> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/784)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 4 of 6 files at r3, 1 of 6 files at r5, 1 of 2 files at r6, 4 of 4 files at r7, 1 of 2 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/784)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
