### PR TITLE
Automatically en-/dis-able definitions

### LINKED ISSUE #2145: [ProjectSettings] Re-evaluate show-definitions setting
Perhaps it should turn on automatically if a project is imported with a definition.
Perhaps it should not be toggle-able.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #2145

Once deployed, something like the following should be run on the server:
```
mongosh --quiet CombineDatabase --eval "db.ProjectsCollection.updateMany({}, {\$set: {'definitionsEnabled': false}})" && mongosh --quiet CombineDatabase --eval "db.FrontierCollection.aggregate([{\$unwind:{path:'\$senses'}},{\$unwind:{path:'\$senses.Definitions'}},{\$group:{_id:'\$projectId'}}])" | grep -Eoh '[0-9a-z]{24}' | while read p || [[ -n $p ]]; do mongosh --quiet CombineDatabase --eval "db.ProjectsCollection.updateOne({_id: {\$eq: ObjectId('$p')}}, {\$set: {'definitionsEnabled': true}})"; done
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2161)

### CODE REVIEW

**Review by jmgrady — CHANGES_REQUESTED** [review]
> Reviewed 3 of 11 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2161)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[`Backend.Tests/Controllers/LiftControllerTests.cs` line 489 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2161#-NVjACAl3RiwkaJ7a1-F:-NVjACAl3RiwkaJ7a1-G:b-t78ocf) ([raw file](https://github.com/sillsdev/TheCombine/blob/5d3d3241738fd48bf9d1b7f9750b955317c6daa0/Backend.Tests/Controllers/LiftControllerTests.cs#L489)):*
> ```Smalltalk
>             Assert.That(proj.DefinitionsEnabled, Is.True);
>         }
> ```

The only difference that I can see between these two functions is the file to be imported and the expected result.  Wouldn't it be easier to maintain if there was a single function to perform this task which receives the filename and expected result as arguments?

**Review by jmgrady — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2161)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2161)* status: all files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`Backend.Tests/Controllers/LiftControllerTests.cs` line 489 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2161#-NVjACAl3RiwkaJ7a1-F:-NVjHdQ-Dcdw2weGNmWD:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/5d3d3241738fd48bf9d1b7f9750b955317c6daa0/Backend.Tests/Controllers/LiftControllerTests.cs#L489)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

The only difference that I can see between these two functions is the file to be imported and the expected result.  Wouldn't it be easier to maintain if there was a single function to perform this task which receives the filename and expected result as arguments?
</blockquote></details>

Done.

**Review by jmgrady — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2161)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
