### PR TITLE
Convert more components to functional

### PR DESCRIPTION
**Pull request by imnasnainaec**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2108)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2108)* status: all files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

___
*[`src/components/DataEntry/DataEntryHeader/tests/DataEntryHeader.test.tsx` line 53 at r1](https://reviewable.io/reviews/sillsdev/TheCombine/2108#-NUbK6-FB3F9mRo-AjGI:-NUbK6-FB3F9mRo-AjGJ:byzm308) ([raw file](https://github.com/sillsdev/TheCombine/blob/c38acece05ddfdab8e2ad93cf074794fc0b84768/src/components/DataEntry/DataEntryHeader/tests/DataEntryHeader.test.tsx#L53)):*
> ```XML
>   });
> 
>   it("Questions not visible should hide questions", () => {
> ```

Looks like this was testing something, which would have to change, but it doesn't look like it is covered anymore.
___
*[`src/components/DataEntry/DataEntryTable/tests/DataEntryTable.test.tsx` line 90 at r1](https://reviewable.io/reviews/sillsdev/TheCombine/2108#-NUbKVEl2Mm-4ay5wvae:-NUbKVEl2Mm-4ay5wvaf:b-mks5zn) ([raw file](https://github.com/sillsdev/TheCombine/blob/2a82a6b3a40e8e92843ed81130fcb4dbb1139fa3/src/components/DataEntry/DataEntryTable/tests/DataEntryTable.test.tsx#L90)):*
> ```XML
> const renderTable = async () => {
>   await renderer.act(async () => {
>     testRenderer = renderer.create(
> ```

So this call is synchronous?

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2108)* status: all files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`src/components/DataEntry/DataEntryTable/tests/DataEntryTable.test.tsx` line 90 at r1](https://reviewable.io/reviews/sillsdev/TheCombine/2108#-NUbKVEl2Mm-4ay5wvae:-NUbOGze61C6UkTHvA3q:b-usg7ti) ([raw file](https://github.com/sillsdev/TheCombine/blob/2a82a6b3a40e8e92843ed81130fcb4dbb1139fa3/src/components/DataEntry/DataEntryTable/tests/DataEntryTable.test.tsx#L90)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

So this call is synchronous?
</blockquote></details>

It _looks_ synchronous, but because the component is async (invokes `useEffect`), act treats it accordingly as async, despite the lack of any `await`.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2108)* status: 19 of 20 files reviewed, all discussions resolved (waiting on @jasonleenaylor and @jmgrady)

___
*[`src/components/DataEntry/DataEntryHeader/tests/DataEntryHeader.test.tsx` line 53 at r1](https://reviewable.io/reviews/sillsdev/TheCombine/2108#-NUbK6-FB3F9mRo-AjGI:-NUbOn31Ae_e0ZktX4sD:bb3p1fd) ([raw file](https://github.com/sillsdev/TheCombine/blob/c38acece05ddfdab8e2ad93cf074794fc0b84768/src/components/DataEntry/DataEntryHeader/tests/DataEntryHeader.test.tsx#L53)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Looks like this was testing something, which would have to change, but it doesn't look like it is covered anymore.
</blockquote></details>

Replaced.

**Review by jasonleenaylor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2108)* status: 19 of 20 files reviewed, all discussions resolved (waiting on @jmgrady)

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 19 of 20 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2108)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
