### PR TITLE
Increase backend unit test coverage

### PR DESCRIPTION
**Pull request by johnthagen**
Increase backend test coverage

- `MergeUndoId` model
- `FileStorage` ID sanitization
- `LiftService`  export with invalid Project ID
- `WordController` permissions

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1462)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1462)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Review by johnthagen — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1462)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Review by imnasnainaec — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1462)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @imnasnainaec and @johnthagen)

**Review by johnthagen — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1462)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Pull request merged**
