### PR TITLE
Update AudioPlayer hooks

### LINKED ISSUE #2118: Playing/stopping one audio file causes all on page to reload
In ReviewEntries, if you have multiple audio files loaded on the page, when you click any one of them, every other file's Pronunciations component re-renders in such a way as to refetch the audio.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Fixes #2118

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2119)

### CODE REVIEW

**Comment by imnasnainaec** [comment]
Progress toward #1385

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2119)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[`src/components/Pronunciations/AudioPlayer.tsx` line 62 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2119#-NUwN-Rq6v3T5CP6bHJq:-NUwN-Rr9iw52Opuoa_K:b-w4eq8b) ([raw file](https://github.com/sillsdev/TheCombine/blob/90d3f5df95b0aa165de16ee54260decef62c66fe/src/components/Pronunciations/AudioPlayer.tsx#L62)):*
> ```XML
>   const { t } = useTranslation();
> 
>   useEffect(() => {
> ```

The useEffect calls here could use some 'why' comments.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2119)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor)

___
*[`src/components/Pronunciations/AudioPlayer.tsx` line 62 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2119#-NUwN-Rq6v3T5CP6bHJq:-NUwTxx0B3TJ-HMEqyE1:b28u7dw) ([raw file](https://github.com/sillsdev/TheCombine/blob/90d3f5df95b0aa165de16ee54260decef62c66fe/src/components/Pronunciations/AudioPlayer.tsx#L62)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

The useEffect calls here could use some 'why' comments.
</blockquote></details>

Ah, this first `useEffect` was added before the above `useAppSelector` was fixed. Being now unnecessary, I removed it. Does the remaining `useEffect` still need a comment?

**Review by jasonleenaylor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2119)* status: 5 of 8 files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[`src/components/Pronunciations/AudioPlayer.tsx` line 62 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2119#-NUwN-Rq6v3T5CP6bHJq:-NUwh64rAdI0LR9cjwLX:behd7zp) ([raw file](https://github.com/sillsdev/TheCombine/blob/90d3f5df95b0aa165de16ee54260decef62c66fe/src/components/Pronunciations/AudioPlayer.tsx#L62)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Ah, this first `useEffect` was added before the above `useAppSelector` was fixed. Being now unnecessary, I removed it. Does the remaining `useEffect` still need a comment?
</blockquote></details>

No, I think it is pretty clear now.

**Pull request merged**
