### PR TITLE
Implement cert-client mode for the certmgr container

### LINKED ISSUE #1053: Migrate WiFi Access Point software for the NUC
The current configuration software for the NUC version of _TheCombine_ uses a copy of [oblique/create_ap](https://github.com/oblique/create_ap) to create the WiFi access point.  According to the README.me for this project, it is no longer being maintained and directs readers to [linux-wifi-hotspot](https://github.com/lakinduakash/linux-wifi-hotspot) or [linux-router](https://github.com/garywill/linux-router).

As a result, the WiFi Access Point implementation should be based off of one of these solutions.

### PR DESCRIPTION
**Pull request by jmgrady**
When the `certmgr` container runs in `cert-client` mode, it fetches the SSL certificates for the NGINX web server from an AWS S3 bucket.  The SSL certificates in the AWS S3 bucket are maintained by another instance of the `certmgr` running in `cert-server` mode.  This mode is intended for deploying _TheCombine_ on a NUC which may be used in remote areas without a connection to the internet.

This implementation assumes that when the `certmgr` is first deployed in this mode, it is connected to the internet and is able to get its certificates from the AWS S3 bucket.  If the certificates are not available, the frontend container will not start up.

`playbook_target_setup.yml` is updated to install a handler on the target system that causes the `certmgr` to check if the certificates can be renewed when the ethernet cable is plugged in.  This is only installed when `cert_mode` is set to `cert-client`.

Closes #1053.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1077)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[certmgr/scripts/entrypoint.py, line 49 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVb2VNR-6O8I5X015C0:-MVb2VNR-6O8I5X015C1:bwav8z4) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/entrypoint.py#L49)):*
> ```Python
>     if cert_obj is not None:
>         cert_obj.create()
>         usr1_signal = signal.SIGUSR1
> ```

Could we add some documentation about what/how these signals are being used and what motivates their use?

**Comment by johnthagen** [comment]
___
*[certmgr/scripts/entrypoint.py, line 49 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVb2VNR-6O8I5X015C0:-MVb34s-3WfJabfvurn5:b-xawufm) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/entrypoint.py#L49)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Could we add some documentation about what/how these signals are being used and what motivates their use?
</blockquote></details>

(Since signals are not a super-commonly used in control flow).

**Comment by johnthagen** [comment]
___
*[certmgr/scripts/entrypoint.py, line 53 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVb3cz-62JbxmLDD60i:-MVb3cz-62JbxmLDD60j:b-67tr9n) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/entrypoint.py#L53)):*
> ```Python
>         while True:
>             # check for renewal after 12 hours or SIGUSR1 received
>             got_sig = signal.sigtimedwait([usr1_signal], 60 * 12)
> ```

According to the `man` pages, it looks like the `timeout` argument is in seconds.

https://manpages.debian.org/buster/manpages-dev/sigtimedwait.2.en.html

It seems like this would wait 12 minutes rather than 12 hours.

Should this argument be changed back to `12 * 3600`? (I also think putting the units conversion on the right side makes it a little easier to understand).

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 3 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1077)* status: 3 of 14 files reviewed, 2 unresolved discussions (waiting on @jmgrady and @johnthagen)

___
*[certmgr/scripts/self_signed_cert.py, line 5 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVb2r0i72NU_NSf9PXh:-MVb2r0i72NU_NSf9PXi:b3jx3su) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/self_signed_cert.py#L5)):*
> ```Python
> 
> The SelfSignedCert creates a Self-Signed certificate that can be used:
>   1. as a temporary certificate so that NGINX will stay up while Let's ENcrypt
> ```

Typo: `ENcrypt`
___
*[deploy/vars/config_common.yml, line 44 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVb3W5E4Zator5UN-6A:-MVb3W5F83elY2i9sXzR:bmoitpq) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/deploy/vars/config_common.yml#L44)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>   - key: "CERT_PROXY_RENEWAL"
>     value: "{{ cert_proxy_renewal | default(60) }}"
>   - key: "CERT_SELF_RENEWAL"
>     value: "{{ cert_self_renewal | default(30) }}"
> ```
</details>

`cert_self_renewal` is defined in `deploy/group_vars/nuc/main.yml`. I don't see `cert_proxy_renewal` defined anywhere, but assume we want open that possibility.

**Comment by johnthagen** [comment]
___
*[certmgr/scripts/utils.py, line 53 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVb4ahJ9J6hAVbUbFa-:-MVb4ahJ9J6hAVbUbFa0:befu7y6) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/utils.py#L53)):*
> ```Python
> def update_link(src: Path, dest: Path) -> None:
>     """
>     Create/move a symbolic link at 'dest' to point to 'src'.
> ```

Not something we need to change here, but if we are going to pick a docstring format, I think the best to pick for Python (which is also fairly popular) is the Google Docstring style.

You can see an example here: https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html#type-annotations

There are a few benefits to this:
- It is a common format, so IDEs such as PyCharm can be configured to auto-populate them and do validation on them
- Documentation tools such as Sphinx can process them and automatically generate HTML docs for these doc strings
- They help us keep a consistent format when reading the code

You can see how to configure PyCharm to auto-create Google docstrings here:

https://github.com/johnthagen/python-blueprint#pycharm-configuration

See the "Settings | Search "Docstrings"" bullet

Could be something we look into in the future

**Comment by johnthagen** [comment]
___
*[certmgr/scripts/utils.py, line 37 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVb5jhe-2XrKiT3cMSA:-MVb5jhe-2XrKiT3cMSB:b-pmdrvj) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/utils.py#L37)):*
> ```Python
>     env_var -- Environment variable to be looked up.
> 
>     get_setting returns the value of the specificed environment variable.
> ```

Typo: Specified

**Comment by johnthagen** [comment]
___
*[certmgr/scripts/cert_proxy_server.py, line 19 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVb658y3CzuNvB2d3xB:-MVb658y3CzuNvB2d3xC:b4zg6pe) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/cert_proxy_server.py#L19)):*
> ```Python
> class CertProxyServer(LetsEncryptCert):
>     """
>     Manage certificates for the server and provice proxy certificate services.
> ```

Typo: provide

**Comment by johnthagen** [comment]
___
*[certmgr/scripts/utils.py, line 53 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVb4ahJ9J6hAVbUbFa-:-MVb6xiM1rW1bp0lwUnc:b24r16l) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/utils.py#L53)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Not something we need to change here, but if we are going to pick a docstring format, I think the best to pick for Python (which is also fairly popular) is the Google Docstring style.

You can see an example here: https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html#type-annotations

There are a few benefits to this:
- It is a common format, so IDEs such as PyCharm can be configured to auto-populate them and do validation on them
- Documentation tools such as Sphinx can process them and automatically generate HTML docs for these doc strings
- They help us keep a consistent format when reading the code

You can see how to configure PyCharm to auto-create Google docstrings here:

https://github.com/johnthagen/python-blueprint#pycharm-configuration

See the "Settings | Search "Docstrings"" bullet

Could be something we look into in the future
</blockquote></details>

More examples here: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

Note, that we would be using the pep484 style. We would not be repeating the type within the docstring since that is already expressed in the function signatures.

**Comment by johnthagen** [comment]
___
*[certmgr/scripts/cert_proxy_client.py, line 20 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVb7o7s6TBDiaV-OrcL:-MVb7o7s6TBDiaV-OrcM:bjt817a) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/cert_proxy_client.py#L20)):*
> ```Python
> 
> @enum.unique
> class CertState(enum.IntEnum):
> ```

In this instance we aren't actually using the values for this `Enum` so a more type-safe way to express this `Enum` would be:

```py
from enum import Enum, auto

class CertState(Enum):
    Missing = auto()
    Expired = auto()
    ...
```

This clearly communicates that the values are not meaningful. By using an `Enum` rather than an`IntEnum` we also make this more type safe. You can no longer compare an instance of this `Enum` directly to an `int`.

**Comment by johnthagen** [comment]
___
*[certmgr/scripts/cert_proxy_client.py, line 20 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVb7o7s6TBDiaV-OrcL:-MVb8REn8lr-DHGEO-3U:b-9qrpht) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/cert_proxy_client.py#L20)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

In this instance we aren't actually using the values for this `Enum` so a more type-safe way to express this `Enum` would be:

```py
from enum import Enum, auto

class CertState(Enum):
    Missing = auto()
    Expired = auto()
    ...
```

This clearly communicates that the values are not meaningful. By using an `Enum` rather than an`IntEnum` we also make this more type safe. You can no longer compare an instance of this `Enum` directly to an `int`.
</blockquote></details>

Using `auto()` also obliviates the need to use `enum.unqiue` because `auto()` will always ensure that the values are unique.

**Comment by johnthagen** [comment]
___
*[certmgr/scripts/cert_proxy_client.py, line 40 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVb8amB-sQbRwH7wcIu:-MVb8amB-sQbRwH7wcIv:buqwuv) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/cert_proxy_client.py#L40)):*
> ```Python
>         """Initialize CertProxyClient instance."""
>         # pylint: disable=too-many-instance-attributes
>         # Ten are required in this case.
> ```

I only count 6. Do we still need this `pylint` disable?

**Comment by johnthagen** [comment]
___
*[certmgr/scripts/cert_proxy_client.py, line 75 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVb8mTdBIUZw6QWTwV7:-MVb8mTdBIUZw6QWTwV8:bsku8q7) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/cert_proxy_client.py#L75)):*
> ```Python
>             print(f"stdout: {err.stdout}")
>             print(f"stderr: {err.stderr}")
>             return timedelta(0)
> ```

Should we return `None` when we don't actually get a value (similar to above if `match` is `None`). It seems like communicating through the type system that we didn't actually get an expire time could be helpful for future use.

**Comment by johnthagen** [comment]
___
*[certmgr/scripts/cert_proxy_client.py, line 68 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVbHEgo1oBaVPzxqkcv:-MVbHEgo1oBaVPzxqkcw:bg8zhjx) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/cert_proxy_client.py#L68)):*
> ```Python
>                 expires_str = match.group(1)
>                 # convert to a datetime object
>                 expires_dt: datetime = datetime.strptime(expires_str, "%b %d %H:%M:%S %Y %Z")
> ```

The `: datetime` type hint here seems redundant? I believe that can be inferred from the return type of `strptime`.

**Comment by johnthagen** [comment]
___
*[certmgr/scripts/cert_proxy_client.py, line 116 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVbHc0D0L09cZo4midI:-MVbHc0D0L09cZo4midJ:b-szs6u0) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/cert_proxy_client.py#L116)):*
> ```Python
>         Fetch the proxy certificate for this server from the AWS S3 Bucket.
> 
>         Fetches the proxy certficate that was created for this server by an
> ```

Typo: certificate

**Comment by johnthagen** [comment]
___
*[certmgr/scripts/cert_proxy_client.py, line 126 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVbHhUy3hbQ9TBCxIBx:-MVbHhUy3hbQ9TBCxIBy:bsb3f2w) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/cert_proxy_client.py#L126)):*
> ```Python
>         """Renew the certificate from the AWS S3 bucket."""
>         cert_state = self.get_cert_state()
>         if cert_state != CertState.Ready:
> ```

The idiomatic way to compare `Enum`s is using:

```
if cert_state is not CertState.Ready
```

`Enum` members are effectively singletons.

**Comment by johnthagen** [comment]
___
*[certmgr/scripts/cert_proxy_client.py, line 5 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVbI2435u80f2mxv8p_:-MVbI2435u80f2mxv8pa:b-7nnoql) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/cert_proxy_client.py#L5)):*
> ```Python
> 
> The CertProxyClient derives from LetsEncryptCert.  It fetches its certificate from
> the configured AWS S3 Bucket.  .
> ```

Extra trailing `  .`

**Review by johnthagen — CHANGES_REQUESTED** [review]
> Reviewed 13 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1077)* status: 11 of 14 files reviewed, 12 unresolved discussions (waiting on @imnasnainaec, @jmgrady, and @johnthagen)

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1077)* status: 11 of 14 files reviewed, 11 unresolved discussions (waiting on @imnasnainaec and @johnthagen)

___
*[certmgr/scripts/cert_proxy_client.py, line 5 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVbI2435u80f2mxv8p_:-MVbKIZvE-1Hc9CcTCBU:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/cert_proxy_client.py#L5)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Extra trailing `  .`
</blockquote></details>

Done.
___
*[certmgr/scripts/cert_proxy_client.py, line 20 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVb7o7s6TBDiaV-OrcL:-MVbI7oOE-6-TL5qs1eV:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/cert_proxy_client.py#L20)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Using `auto()` also obliviates the need to use `enum.unqiue` because `auto()` will always ensure that the values are unique.
</blockquote></details>

Done.
___
*[certmgr/scripts/cert_proxy_client.py, line 40 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVb8amB-sQbRwH7wcIu:-MVbIE-I6KxcHMJzZbBs:bo8vh2i) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/cert_proxy_client.py#L40)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I only count 6. Do we still need this `pylint` disable?
</blockquote></details>

Copy/paste error.
Done.
___
*[certmgr/scripts/cert_proxy_client.py, line 68 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVbHEgo1oBaVPzxqkcv:-MVbIPvQEVBe3gpTiIpG:bla0gy0) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/cert_proxy_client.py#L68)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

The `: datetime` type hint here seems redundant? I believe that can be inferred from the return type of `strptime`.
</blockquote></details>

I will check it out but if I recall correctly it did not infer it.
___
*[certmgr/scripts/cert_proxy_client.py, line 75 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVb8mTdBIUZw6QWTwV7:-MVbJjbN9lF8P5xVeylE:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/cert_proxy_client.py#L75)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Should we return `None` when we don't actually get a value (similar to above if `match` is `None`). It seems like communicating through the type system that we didn't actually get an expire time could be helpful for future use.
</blockquote></details>

Done.
___
*[certmgr/scripts/cert_proxy_client.py, line 116 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVbHc0D0L09cZo4midI:-MVbJvWZ0ygmcxl9EEci:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/cert_proxy_client.py#L116)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Typo: certificate
</blockquote></details>

Done.
___
*[certmgr/scripts/cert_proxy_client.py, line 126 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVbHhUy3hbQ9TBCxIBx:-MVbK2FX07EQkHh6JfFF:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/cert_proxy_client.py#L126)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

The idiomatic way to compare `Enum`s is using:

```
if cert_state is not CertState.Ready
```

`Enum` members are effectively singletons.
</blockquote></details>

Done.
___
*[certmgr/scripts/cert_proxy_server.py, line 19 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVb658y3CzuNvB2d3xB:-MVbKBMuALfSryNL1lbv:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/cert_proxy_server.py#L19)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Typo: provide
</blockquote></details>

Done.
___
*[certmgr/scripts/entrypoint.py, line 49 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVb2VNR-6O8I5X015C0:-MVb4P-t3U2POdiHjvNB:b4md207) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/entrypoint.py#L49)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

(Since signals are not a super-commonly used in control flow).
</blockquote></details>

Signals are used to handle asynchronous events and that is what is implemented here.  I have added the ability to trigger checking for whether the certificate needs to be renewed by sending a signal to the container.  Another option would be to use `docker-compose exec ...` to run a script to check but that adds several concurrency issues.

The driving force behind this is to be able to have the NUC check when it is plugged into the network since it will often be disconnected and not able to check for a certificate update.  The way that the `certmgr` is structured, it made sense to put this code in the `entrypoint.py` rather than just in the `cert-client` mode.  As a result, it becomes a general ability to trigger a check for renewal for all modes of operation.  I will add the documentation that you suggest but it will be general in nature since its use is not restricted to our current use.
___
*[certmgr/scripts/entrypoint.py, line 53 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVb3cz-62JbxmLDD60i:-MVb5pEg-_7HR8henPMr:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/entrypoint.py#L53)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

According to the `man` pages, it looks like the `timeout` argument is in seconds.

https://manpages.debian.org/buster/manpages-dev/sigtimedwait.2.en.html

It seems like this would wait 12 minutes rather than 12 hours.

Should this argument be changed back to `12 * 3600`? (I also think putting the units conversion on the right side makes it a little easier to understand).
</blockquote></details>

Done.
___
*[certmgr/scripts/utils.py, line 37 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVb5jhe-2XrKiT3cMSA:-MVb7Rt22KWq5-XwS_RL:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/utils.py#L37)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Typo: Specified
</blockquote></details>

Done.
___
*[certmgr/scripts/utils.py, line 53 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVb4ahJ9J6hAVbUbFa-:-MVb7ciC6jVyam_-7-qK:bciizza) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/utils.py#L53)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

More examples here: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

Note, that we would be using the pep484 style. We would not be repeating the type within the docstring since that is already expressed in the function signatures.
</blockquote></details>

I had looked at the [PEP 257 -- Docstring Conventions](https://www.python.org/dev/peps/pep-0257/) document but it looks like that is an old recommendation (or I mis-understood it).  I would like to use a standard way to document the arguments, return values, etc.

I like the Google Docstring format much better.
___
*[deploy/vars/config_common.yml, line 44 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVb3W5E4Zator5UN-6A:-MVbGx8V6jAcEnEwM6pT:b3pfwfm) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/deploy/vars/config_common.yml#L44)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>   - key: "CERT_PROXY_RENEWAL"
>     value: "{{ cert_proxy_renewal | default(60) }}"
>   - key: "CERT_SELF_RENEWAL"
>     value: "{{ cert_self_renewal | default(30) }}"
> ```
`cert_self_renewal` is defined in `deploy/group_vars/nuc/main.yml`. I don't see `cert_proxy_renewal` defined anywhere, but assume we want open that possibility.
</blockquote></details>

That is correct.  `cert_self_renewal` and `cert_proxy_renewal` allow you to override the defaults of 30 and 60 for a particular host or group of hosts.  Since `cert_proxy_renewal` is not defined anywhere it means that we are not using that capability yet.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 2 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1077)* status: 10 of 14 files reviewed, 11 unresolved discussions (waiting on @jmgrady and @johnthagen)

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1077)* status: 10 of 14 files reviewed, 11 unresolved discussions (waiting on @jmgrady and @johnthagen)

___
*[certmgr/scripts/cert_proxy_client.py, line 68 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVbHEgo1oBaVPzxqkcv:-MVbLJMQ-bJi9xKMIhNy:b-3kutwq) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/cert_proxy_client.py#L68)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

I will check it out but if I recall correctly it did not infer it.
</blockquote></details>

Done.  There is no problem running nor with `tox` when the type hint is removed.

**Comment by johnthagen** [comment]
___
*[certmgr/scripts/utils.py, line 53 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1077#-MVb4ahJ9J6hAVbUbFa-:-MVbMKwtBo2ew2wmQ6yd:b-k3x1tm) ([raw file](https://github.com/sillsdev/thecombine/blob/7774b97d6c69e45f0b1397495500292defcbce3b/certmgr/scripts/utils.py#L53)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

I had looked at the [PEP 257 -- Docstring Conventions](https://www.python.org/dev/peps/pep-0257/) document but it looks like that is an old recommendation (or I mis-understood it).  I would like to use a standard way to document the arguments, return values, etc.

I like the Google Docstring format much better.
</blockquote></details>

Yep, PEP 257 provides some guidelines, and then Google Style Docstrings takes it further on how to express the internal style of some arguments.

I would view Google Docstrings as a superset of guidelines on top of PEP 257.

**Review by johnthagen — APPROVED** [review]
> Reviewed 5 of 6 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1077)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Pull request merged**
