### PR TITLE
[tutorial] Export 1: Update times; Add Spanish CC

### PR DESCRIPTION
**Pull request by imnasnainaec**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3450)

### CODE REVIEW

**Review by jasonleenaylor — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3450#-:-ODNFY_6BZ79RVjPGSTg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by jasonleenaylor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3450)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[`docs/tutorial_subtitles/export_1_flex_to_combine/export_1_flex_to_combine.spa.txt` line 8 at r1](https://reviewable.io/reviews/sillsdev/TheCombine/3450#-ODNGHWd15GYVPmIXLwN:-ODNGHWd15GYVPmIXLwO:b1k7dyi) ([raw file](https://github.com/sillsdev/TheCombine/blob/0a8ddc4e26b7fabd612a3f1fe961a59086d3dbcf/docs/tutorial_subtitles/export_1_flex_to_combine/export_1_flex_to_combine.spa.txt#L8)):*
> ```help
> Aparece otro diálogo para que seleccione dónde se guardarán los archivos exportados.
> Necesitarás crear una nueva carpeta para los archivos.
> Voy a Desktop y hago clic en el botón “Make New Folder” para crear una carpeta Naskapi.
> ```

Could have spanish here? Evaluate

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3450)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

___
*[`docs/tutorial_subtitles/export_1_flex_to_combine/export_1_flex_to_combine.spa.txt` line 8 at r1](https://reviewable.io/reviews/sillsdev/TheCombine/3450#-ODNGHWd15GYVPmIXLwN:-ODRne0W74hxsCuphzds:bqmjwcz) ([raw file](https://github.com/sillsdev/TheCombine/blob/0a8ddc4e26b7fabd612a3f1fe961a59086d3dbcf/docs/tutorial_subtitles/export_1_flex_to_combine/export_1_flex_to_combine.spa.txt#L8)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Could have spanish here? Evaluate
</blockquote></details>

Added.

**Review by jasonleenaylor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3450#-:-ODwdPZmDGQN1Ve4K27I:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
