### PR TITLE
Support importing Lift files that are missing a top level project folder

### LINKED ISSUE #1395: Support importing Lift files that are missing a top level folder
**Is your feature request related to a problem? Please describe.**

The current Lift import logic expects a structure like this:

```
flex.zip
  | project_name
     | audio
     | WritingSystems
     | project_name.lift
     | project_name.lift-ranges
```

But users sometimes zip the structure like:

```
flex.zip
   | audio
   | WritingSystems
   | project_name.lift
   | project_name.lift-ranges
```

The backend currently returns a `BadRequest` in this instance.

**Describe the solution you'd like**

Support gracefully importing a Lift zip file even if it is missing the top level project folder.

**Acceptance Tests**

- Import LIFT files using both the previous format and new format and confirm that they import correctly.

### PR DESCRIPTION
**Pull request by johnthagen**
Closes #1395

Simplify validation of Lift import files and be more permissive to how the user zip's up the Lift file.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1396)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1396)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @johnthagen)

___
*[Backend/Controllers/LiftController.cs, line 49 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1396#-Mkx50E_Awrw0zhnl8qE:-Mkx50E_Awrw0zhnl8qF:b3s4htl) ([raw file](https://github.com/sillsdev/thecombine/blob/09ddee31b2a4a010a02ff037c82dc575b22ddf99/Backend/Controllers/LiftController.cs#L49)):*
> ```Smalltalk
>         private static List<string> FindLiftFiles(string dir)
>         {
>             return Directory.GetFiles(dir).Where(x => x.EndsWith(".lift")).ToList();
> ```

Use the two argument version of `GetFiles` unless your love of Linq is too strong.

**Comment by johnthagen** [comment]
___
*[Backend/Controllers/LiftController.cs, line 49 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1396#-Mkx50E_Awrw0zhnl8qE:-Mkx758X4o3vJdxuxei5:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/09ddee31b2a4a010a02ff037c82dc575b22ddf99/Backend/Controllers/LiftController.cs#L49)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Use the two argument version of `GetFiles` unless your love of Linq is too strong.
</blockquote></details>

Done.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1396)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Comment by MattGyverLee** [comment]
> > Reviewed 3 of 3 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1396)_ status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @johnthagen)
> 
> _[Backend/Controllers/LiftController.cs, line 49 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1396#-Mkx50E_Awrw0zhnl8qE:-Mkx50E_Awrw0zhnl8qF:b3s4htl) ([raw file](https://github.com/sillsdev/thecombine/blob/09ddee31b2a4a010a02ff037c82dc575b22ddf99/Backend/Controllers/LiftController.cs#L49)):_
> 
> > ```smalltalk
> >         private static List<string> FindLiftFiles(string dir)
> >         {
> >             return Directory.GetFiles(dir).Where(x => x.EndsWith(".lift")).ToList();
> > ```

Question, if there is a subfolder in the zip containing a LIFT file, are the folder name and .lift file name required to match? 
Directory: ./SwoDico/
File: SwoDico.lift

This seems to be an assumption that WeSay (especially) and FLEx make, but it does not seem to be specified in the LIFT standard (https://github.com/sillsdev/lift-standard/blob/master/lift_15.pdf). Another user just had a LIFT import failure, and I wonder if this may be the cause.

**Pull request merged**
