### PR TITLE
Autofocus the note text field when add note is clicked in new entry

### LINKED ISSUE #1295: Data Entry | Add Note does not focus note entry text field
1. Enter Data Entry
2. Create a new word
3. Press the Add Note Button
4. Note that you cannot begin typing immediately because the browser is not focused on the text field

This requires an extra mouse click to focus the field. For users entering lots of Words with Notes, this could add a bit of inefficiency.

### PR DESCRIPTION
**Pull request by WeJamUS**
Closes #1295

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1353)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
One question, are there places where we don't actually want the focus to go to the text field using this dialog? 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1353#-:-MicVgPC6KuFqkmEOVUY:bh8v867)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @imnasnainaec and @JacobHaimes)

**Comment by WeJamUS** [comment]
I created an optional autofocus prop of type boolean in EditTextDialog and set the autofocus prop of the TextField element equal to that prop. So I think the other existing EditTextDialog elements that are missing this autofocus prop will cause their TextField autofocus prop to evaluate to false and therefore not autofocus.

**Review by imnasnainaec — COMMENTED** [review]
I can't think of any reason to have `autoFocus={false}`. We may not even need the prop. If every use we expect for this dialog will want autofocus to the text box, we can remove the prop and have `autoFocus` instead of `autoFocus={props.autoFocus}`.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1353#-:-MicZX_a-eV7o_XmXpTa:b-k51lfq)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @JacobHaimes)

**Review by jasonleenaylor — COMMENTED** [review]
@imnasnainaec My thoughts exactly. @wejamus please just set autoFocus to true. :smile: 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1353#-:-MicdNdB5NjIiLwAM5B4:b-9suxk2)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @JacobHaimes)

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1353)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JacobHaimes and @jasonleenaylor)

**Pull request merged**
