### PR TITLE
[Tutorial Videos] Add transcripts and subtitles script

### PR DESCRIPTION
**Pull request by imnasnainaec**
Script uses ffmpeg per https://www.bannerbear.com/blog/how-to-add-subtitles-to-a-video-file-using-ffmpeg

Example videos:
- [Export Tutorial 1](https://drive.google.com/file/d/1LMnRxJlm36EO8-jpa-V7BN4uClrqhQRb)
- [Merge Tutorial 1](https://drive.google.com/file/d/1TvG5_tLRBLLYkGTieNt4mhvxynKMz3-y)

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3251)

### CODE REVIEW

**Review by jmgrady — COMMENTED** [review]
> Reviewed 3 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3251)* status: 3 of 15 files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by jmgrady — COMMENTED** [review]
> Reviewed 2 of 14 files at r1, 2 of 8 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3251)* status: 8 of 16 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[`docs/tutorial_subtitles/README.md` line 3 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/3251#-O3cn88T6t1LwW5YPgDo:-O3cn88T6t1LwW5YPgDp:b-ysgxar) ([raw file](https://github.com/sillsdev/TheCombine/blob/374865c2f303ce99de706c5b8b76425ac94047c7/docs/tutorial_subtitles/README.md#L3)):*
> ```Markdown
> This folder contains the transcripts for tutorial videos and timestamps for generating video subtitles.
> 
> The `_in_progress_transcripts_` subfolder holds transcripts that are awaiting a video recording.
> ```

Is there a reason for the leading and trailing underscores in the directory name?  I have been using filenames that start with `_` to prevent them from being added to the git repo.  In addition, leading `_`s often have special meanings in other languages (e.g. C, Python).  I can change my key for not adding files to git.

One issue I have run into is that when I tried to mention the directory in Slack, it kept showing "in_progress_transcripts" in italics!

It's not a big deal and if you have a reason you would like to keep it this way, that is fine with me.



_Code quote:_
```Markdown
_in_progress_transcripts_
```
___
*[`docs/tutorial_subtitles/export_1_flex_to_combine/times.txt` line 44 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/3251#-O3cpEb46T-eGtmBROxx:-O3cpEb589oDdCTcxYu8:bcro1cy) ([raw file](https://github.com/sillsdev/TheCombine/blob/374865c2f303ce99de706c5b8b76425ac94047c7/docs/tutorial_subtitles/export_1_flex_to_combine/times.txt#L44)):*
> ```help
> 5:13
> 5:16
> 5:19
> ```

3 seconds seems like a very short time for a caption - even one as simple as this since it may be longer in other languages.  In `merge_dups_1_basics` it's only 2 seconds.



_Code quote:_
```help
5:19
```

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3251)* status: 8 of 16 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`docs/tutorial_subtitles/README.md` line 3 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/3251#-O3cn88T6t1LwW5YPgDo:-O3cug5N9j0ymJn0Nm9X:b80ki35) ([raw file](https://github.com/sillsdev/TheCombine/blob/374865c2f303ce99de706c5b8b76425ac94047c7/docs/tutorial_subtitles/README.md#L3)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Is there a reason for the leading and trailing underscores in the directory name?  I have been using filenames that start with `_` to prevent them from being added to the git repo.  In addition, leading `_`s often have special meanings in other languages (e.g. C, Python).  I can change my key for not adding files to git.

One issue I have run into is that when I tried to mention the directory in Slack, it kept showing "in_progress_transcripts" in italics!

It's not a big deal and if you have a reason you would like to keep it this way, that is fine with me.
</blockquote></details>

I want to distinguish it from the other folders (and have it autosort to the start or end of the containing folder), but a `_` prefix may not be the best way to do that, given what you've described.
___
*[`docs/tutorial_subtitles/export_1_flex_to_combine/times.txt` line 44 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/3251#-O3cpEb46T-eGtmBROxx:-O3cv2777pWPYsF-5TMB:b-gtrikf) ([raw file](https://github.com/sillsdev/TheCombine/blob/374865c2f303ce99de706c5b8b76425ac94047c7/docs/tutorial_subtitles/export_1_flex_to_combine/times.txt#L44)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

3 seconds seems like a very short time for a caption - even one as simple as this since it may be longer in other languages.  In `merge_dups_1_basics` it's only 2 seconds.
</blockquote></details>

The times are identified to keep the caption up until the next sentence begins or the video ends. Perhaps I could try to pause a bit more between sentences in future recordings to allow for longer translations.

**Review by jmgrady — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3251)* status: 8 of 16 files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[`docs/tutorial_subtitles/README.md` line 3 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/3251#-O3cn88T6t1LwW5YPgDo:-O3dP51j-ECDQRqVZoBo:b-k9ave0) ([raw file](https://github.com/sillsdev/TheCombine/blob/374865c2f303ce99de706c5b8b76425ac94047c7/docs/tutorial_subtitles/README.md#L3)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I want to distinguish it from the other folders (and have it autosort to the start or end of the containing folder), but a `_` prefix may not be the best way to do that, given what you've described.
</blockquote></details>

That is a fine reason.  I should have been clearer - in C & Python, a leading `_` has special meaning in _identifiers_, not file names.  I'll pick something else for files I do not want tracked (in a different PR).  `_` is more of a pain to type anyway! 😉

**Review by jmgrady — COMMENTED** [review]
> Reviewed 4 of 14 files at r1, 2 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3251)* status: 14 of 16 files reviewed, 3 unresolved discussions (waiting on @imnasnainaec)

___
*[`docs/tutorial_subtitles/_in_progress_transcripts_/merge_dups_2_senses.eng.txt` line 10 at r5](https://reviewable.io/reviews/sillsdev/TheCombine/3251#-O3wprgn1ToCS8OzBG3Q:-O3wprgo1zM3583olZm_:b-gbff8l) ([raw file](https://github.com/sillsdev/TheCombine/blob/5cd00b28a345648b4353623b013a8e60f40bb14e/docs/tutorial_subtitles/_in_progress_transcripts_/merge_dups_2_senses.eng.txt#L10)):*
> ```help
> Voila! Now the correct senses are together.
> Wait a second… the two glosses of the first word are not different senses. They are the exact same idea expressed redundantly.
> To delete the unnecessary sense, click-and-drag it over the garbage icon in the bottom corner.
> ```

In `./docs/tutorial_subtitles/_in_progress_transcripts_/data_entry_1_basics.eng.txt` this same icon is called the _delete icon_. 

Perhaps use _drag it over the delete icon in the bottom corner.  It looks like a garbage can._  As an additional nit, it should be _garbage can_ - _garbage_ is what goes into the _garbage can_.



_Code quote:_
```help
garbage icon
```
___
*[`docs/tutorial_subtitles/_in_progress_transcripts_/review_entries_2_editing.eng.txt` line 7 at r5](https://reviewable.io/reviews/sillsdev/TheCombine/3251#-O3wu6Cn9ihxZ2ZYw0hN:-O3wu6Cn9ihxZ2ZYw0hO:b-laibh4) ([raw file](https://github.com/sillsdev/TheCombine/blob/5cd00b28a345648b4353623b013a8e60f40bb14e/docs/tutorial_subtitles/_in_progress_transcripts_/review_entries_2_editing.eng.txt#L7)):*
> ```help
> In this video, we look at how to edit an entry.
> Each word in your project shows up as a row in this table.
> To delete a word, click the rubbish bin icon at the right end.
> ```

This is yet a different term than is used in other tutorials for the same icon.



_Code quote:_
```help
rubbish bin icon
```
___
*[`docs/tutorial_subtitles/_in_progress_transcripts_/sem_dom_1_basics.eng.txt` line 6 at r5](https://reviewable.io/reviews/sillsdev/TheCombine/3251#-O3wwuJgEqSbnE6CulLy:-O3wwuJh46T2Gsicn5lR:b-loxwwc) ([raw file](https://github.com/sillsdev/TheCombine/blob/5cd00b28a345648b4353623b013a8e60f40bb14e/docs/tutorial_subtitles/_in_progress_transcripts_/sem_dom_1_basics.eng.txt#L6)):*
> ```help
> Let’s go to thecombine.app and log in.
> When you click on a project, the semantic domain tree appears.
> If you are doing something else in the project (such as data cleanup or project settings), you can get back to the semantic domain tree by clicking the “Data Entry” button in the top bar.
> ```

This sentence seems awkward to me.  _doing something else_ should refer to a task.  _data cleanup_ is a task but not _project settings_.  Should be something like _reviewing the project settings_ or _changing the project settings_.



_Code quote:_
```help
If you are doing something else in the project (such as data cleanup or project settings), you can get back to the semantic domain tree by clicking the “Data Entry” button in the top bar.
```
___
*[`docs/tutorial_subtitles/merge_dups_1_basics/merge_dups_1_basics.eng.txt` line 27 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/3251#-O3hZpNM7sg8G2BsCegG:-O3hZpNM7sg8G2BsCegH:b-hz8juf) ([raw file](https://github.com/sillsdev/TheCombine/blob/2b5a65d844cabc4a59b50881cd040684dbba84e2/docs/tutorial_subtitles/merge_dups_1_basics/merge_dups_1_basics.eng.txt#L27)):*
> ```help
> If we click “Yes”, it will look for more sets of potential duplicates.
> After The Combine can’t find any more words with identical vernacular form, it will suggest words with similar vernacular forms.
> This will help catch duplicates where one of the words has a typo or is using alternative spelling.
> ```

How about "an alternate" instead of "alternative"?
Alternate is an adjective (or a verb if you pronounce differently).
Alternative is generally a noun although its use as an adjective is increasing I believe.

Perhaps it's my age showing.



_Code quote:_
```help
alternative
```

**Review by jmgrady — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3251)* status: all files reviewed, 7 unresolved discussions (waiting on @imnasnainaec)

___
*[`scripts/subtitle_tutorial_video.py` line 101 at r5](https://reviewable.io/reviews/sillsdev/TheCombine/3251#-O465blG0OkCB5FPEJOk:-O465blH7hPJrqQ2iYIN:b-na16cp) ([raw file](https://github.com/sillsdev/TheCombine/blob/5cd00b28a345648b4353623b013a8e60f40bb14e/scripts/subtitle_tutorial_video.py#L101)):*
> ```Python
>         for line in file.readlines():
>             if not (line):
>                 continue
> ```

Strip the line before testing if the line exists.
```
for line in file.readlines():
  line = line.strip()
  if not line:
...
```



_Code quote:_
```Python
        for line in file.readlines():
            if not (line):
                continue
```
___
*[`scripts/subtitle_tutorial_video.py` line 104 at r5](https://reviewable.io/reviews/sillsdev/TheCombine/3251#-O464WrVDuB2Wk_o4eqJ:-O464WrW0dBkUUKhlOam:bdjzcn9) ([raw file](https://github.com/sillsdev/TheCombine/blob/5cd00b28a345648b4353623b013a8e60f40bb14e/scripts/subtitle_tutorial_video.py#L104)):*
> ```Python
>             min_sec = line.strip().split(":")  # Split into minutes and seconds
>             sec_mil = min_sec[1].split(".")  # Check for partial seconds
>             mil = sec_mil[1] if len(sec_mil) > 1 else "0"  # Compute milliseconds
> ```

I find it simpler to split on `:` or `.`
```
import re
...
times = re.split(":|\.", line)  # See comment above about strip
# now the time components can be referenced as
 min = times[0]
sec = times[1]
msec = times[2] if len(times) > 2 else 0.
```
(also use the standard abbreviation for milliseconds).



_Code quote:_
```Python
            min_sec = line.strip().split(":")  # Split into minutes and seconds
            sec_mil = min_sec[1].split(".")  # Check for partial seconds
            mil = sec_mil[1] if len(sec_mil) > 1 else "0"  # Compute milliseconds
```
___
*[`scripts/subtitle_tutorial_video.py` line 138 at r5](https://reviewable.io/reviews/sillsdev/TheCombine/3251#-O46B-16E-XtuCV_eR6u:-O46B-16E-XtuCV_eR6v:b-4k68go) ([raw file](https://github.com/sillsdev/TheCombine/blob/5cd00b28a345648b4353623b013a8e60f40bb14e/scripts/subtitle_tutorial_video.py#L138)):*
> ```Python
>             " ".join(metadata_strings),
>             f"{args.output}",
>         ]
> ```

Since you join the arguments below, you don't need to join them here (which will make it easier to read in the debugger if you need to).  Use this form instead:
```
        exec_command_parts: List[str] = [
            "ffmpeg", "-i",
            args.input] +
            i_strings +
            map_strings) +
            ["-c",
            "copy",
             "-c:s mov_text"] +
            metadata_strings,
            args.output,
        ]
```
(And use `subprocess.run` as in the following comment.  It takes an array for the command).



_Code quote:_
```Python
        exec_command_parts: List[str] = [
            "ffmpeg -i",
            f"{args.input}",
            " ".join(i_strings),
            " ".join(map_strings),
            "-c copy -c:s mov_text",
            " ".join(metadata_strings),
            f"{args.output}",
        ]
```
___
*[`scripts/subtitle_tutorial_video.py` line 141 at r5](https://reviewable.io/reviews/sillsdev/TheCombine/3251#-O46AB6Y0cha3tqsKOWE:-O46AB6Y0cha3tqsKOWF:b-lkk7gw) ([raw file](https://github.com/sillsdev/TheCombine/blob/5cd00b28a345648b4353623b013a8e60f40bb14e/scripts/subtitle_tutorial_video.py#L141)):*
> ```Python
>         exec_command = " ".join(exec_command_parts)
>         logging.info(f"Executing: {exec_command}")
>         system(exec_command)
> ```

Use `subprocess.run()` instead of `os.system()`.  It is generally considered more "Pythonic" and does not require you to join the arguments and prevents some problems quoting of arguments.

The only time I have had to resort to `os.system` is when I need to print `stdout` and `stderr` while the command is running.  It is usually sufficient to print it at the end if I want it.  (There is a way to do it with the `subprocess` module but it is cumbersome.)



_Code quote:_
```Python
        system(exec_command)
```

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3251)* status: 10 of 16 files reviewed, 4 unresolved discussions (waiting on @jmgrady)

___
*[`docs/tutorial_subtitles/_in_progress_transcripts_/merge_dups_2_senses.eng.txt` line 10 at r5](https://reviewable.io/reviews/sillsdev/TheCombine/3251#-O3wprgn1ToCS8OzBG3Q:-O46ggMD54sr0ypkqchX:bcnrejf) ([raw file](https://github.com/sillsdev/TheCombine/blob/5cd00b28a345648b4353623b013a8e60f40bb14e/docs/tutorial_subtitles/_in_progress_transcripts_/merge_dups_2_senses.eng.txt#L10)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

In `./docs/tutorial_subtitles/_in_progress_transcripts_/data_entry_1_basics.eng.txt` this same icon is called the _delete icon_. 

Perhaps use _drag it over the delete icon in the bottom corner.  It looks like a garbage can._  As an additional nit, it should be _garbage can_ - _garbage_ is what goes into the _garbage can_.
</blockquote></details>

(Discussed at standup), to avoid the various international interpretations of "trash" and "garbage", I've just gone with "delete icon" everywhere.
___
*[`docs/tutorial_subtitles/_in_progress_transcripts_/sem_dom_1_basics.eng.txt` line 6 at r5](https://reviewable.io/reviews/sillsdev/TheCombine/3251#-O3wwuJgEqSbnE6CulLy:-O46guiV78gVn1cyOoBg:b-qj92pf) ([raw file](https://github.com/sillsdev/TheCombine/blob/5cd00b28a345648b4353623b013a8e60f40bb14e/docs/tutorial_subtitles/_in_progress_transcripts_/sem_dom_1_basics.eng.txt#L6)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

This sentence seems awkward to me.  _doing something else_ should refer to a task.  _data cleanup_ is a task but not _project settings_.  Should be something like _reviewing the project settings_ or _changing the project settings_.
</blockquote></details>

Reworded.
___
*[`scripts/subtitle_tutorial_video.py` line 101 at r5](https://reviewable.io/reviews/sillsdev/TheCombine/3251#-O465blG0OkCB5FPEJOk:-O46gyRY-2WowwJW_oJG:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/5cd00b28a345648b4353623b013a8e60f40bb14e/scripts/subtitle_tutorial_video.py#L101)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Strip the line before testing if the line exists.
```
for line in file.readlines():
  line = line.strip()
  if not line:
...
```
</blockquote></details>

Done.
___
*[`scripts/subtitle_tutorial_video.py` line 104 at r5](https://reviewable.io/reviews/sillsdev/TheCombine/3251#-O464WrVDuB2Wk_o4eqJ:-O46gzJS2u5QBqPcmY8f:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/5cd00b28a345648b4353623b013a8e60f40bb14e/scripts/subtitle_tutorial_video.py#L104)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

I find it simpler to split on `:` or `.`
```
import re
...
times = re.split(":|\.", line)  # See comment above about strip
# now the time components can be referenced as
 min = times[0]
sec = times[1]
msec = times[2] if len(times) > 2 else 0.
```
(also use the standard abbreviation for milliseconds).
</blockquote></details>

Done.
___
*[`scripts/subtitle_tutorial_video.py` line 138 at r5](https://reviewable.io/reviews/sillsdev/TheCombine/3251#-O46B-16E-XtuCV_eR6u:-O46h5204TxZFzlYbbE-:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/5cd00b28a345648b4353623b013a8e60f40bb14e/scripts/subtitle_tutorial_video.py#L138)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Since you join the arguments below, you don't need to join them here (which will make it easier to read in the debugger if you need to).  Use this form instead:
```
        exec_command_parts: List[str] = [
            "ffmpeg", "-i",
            args.input] +
            i_strings +
            map_strings) +
            ["-c",
            "copy",
             "-c:s mov_text"] +
            metadata_strings,
            args.output,
        ]
```
(And use `subprocess.run` as in the following comment.  It takes an array for the command).
</blockquote></details>

Done.
___
*[`scripts/subtitle_tutorial_video.py` line 141 at r5](https://reviewable.io/reviews/sillsdev/TheCombine/3251#-O46AB6Y0cha3tqsKOWE:-O46h6Ua9D8Y-qecUI4L:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/5cd00b28a345648b4353623b013a8e60f40bb14e/scripts/subtitle_tutorial_video.py#L141)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Use `subprocess.run()` instead of `os.system()`.  It is generally considered more "Pythonic" and does not require you to join the arguments and prevents some problems quoting of arguments.

The only time I have had to resort to `os.system` is when I need to print `stdout` and `stderr` while the command is running.  It is usually sufficient to print it at the end if I want it.  (There is a way to do it with the `subprocess` module but it is cumbersome.)
</blockquote></details>

Done.

**Review by jmgrady — APPROVED** [review]
> Reviewed 5 of 6 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3251)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
