### PR TITLE
Update README per feedback from Kevin

### PR DESCRIPTION
**Pull request by imnasnainaec**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1660)

### CODE REVIEW

**Review by jmgrady — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1660)* status: all files reviewed, 2 unresolved discussions (waiting on @imnasnainaec)

___
*[`docs/user_guide/docs/goals.md` line 67 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1660#-N1jUoMo3swyHBm1jQ-b:-N1jUoMo3swyHBm1jQ-c:b1gm7pe) ([raw file](https://github.com/sillsdev/thecombine/blob/27a3abda85c9b6d1bb1ed3cb6d137c781ba176c0/docs/user_guide/docs/goals.md#L67)):*
> you can move a different sense to the top

Should this be _you can move a different sense card to the top_?
___
*[`src/resources/translations.json` line 951 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1660#-N1jVd4N248bSK-nnrT5:-N1jVd4N248bSK-nnrT6:b-4crwd2) ([raw file](https://github.com/sillsdev/thecombine/blob/27a3abda85c9b6d1bb1ed3cb6d137c781ba176c0/src/resources/translations.json#L951)):*
> ```JSON
>     ],
>     "playTooltip": [
>       "Press to play; shift click to delete.",
> ```

I realize that this is outside the scope of these changes but it seems odd to me that we say _press_ to play but shift _click_ to delete.



_Code quote:_
```JSON
Press to play; shift click to delete
```

**Review by jmgrady — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1660)* status: all files reviewed, 2 unresolved discussions (waiting on @imnasnainaec)

___
*[`src/resources/translations.json` line 951 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1660#-N1jVd4N248bSK-nnrT5:-N1jhaP7-vLEDkmlNWJQ:b59rnc0) ([raw file](https://github.com/sillsdev/thecombine/blob/27a3abda85c9b6d1bb1ed3cb6d137c781ba176c0/src/resources/translations.json#L951)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

I realize that this is outside the scope of these changes but it seems odd to me that we say _press_ to play but shift _click_ to delete.
</blockquote></details>

Also, I believe that is should be hyphenated, that is, shift-click.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1660)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`docs/user_guide/docs/goals.md` line 67 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1660#-N1jUoMo3swyHBm1jQ-b:-N1jnm6rCjqIfGFKpz_s:b-g80zpx) ([raw file](https://github.com/sillsdev/thecombine/blob/27a3abda85c9b6d1bb1ed3cb6d137c781ba176c0/docs/user_guide/docs/goals.md#L67)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

> you can move a different sense to the top

Should this be _you can move a different sense card to the top_?
</blockquote></details>

I was internally debating that. It probably should be, but then do we need "its glosses)" -> "its sense's glosses)"?

**Review by jmgrady — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1660)* status: all files reviewed, 2 unresolved discussions (waiting on @imnasnainaec)

___
*[`docs/user_guide/docs/dataEntry.md` line 32 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1660#-N1na9TT6dtPwTj8SDuw:-N1na9TT6dtPwTj8SDux:bwaxaxv) ([raw file](https://github.com/sillsdev/thecombine/blob/4f7f48ffb891d930a1cfc6aa93a0d80be2c761d2/docs/user_guide/docs/dataEntry.md#L32)):*
The circle buttons are invisible unless I hover over them.  Even so, it is not obvious that they are buttons when they are visible.  In addition, I cannot see the "square" that is mentioned in:
> To record audio, there is a red circle button with a square.
___
*[`docs/user_guide/docs/dataEntry.md` line 35 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1660#-N1naiT671id3VkSSjDt:-N1naiT671id3VkSSjDu:b-sj6ekr) ([raw file](https://github.com/sillsdev/thecombine/blob/4f7f48ffb891d930a1cfc6aa93a0d80be2c761d2/docs/user_guide/docs/dataEntry.md#L35)):*
> ```Markdown
> with a triangle.
> 
> **With a mouse:** Click-and-hold the red circle to record. Click a green circle to play its audio, or shift-click to
> ```

Should be "green triangle" (and below).

**Pull request merged**
