### PR TITLE
AppBar logo text, avatar placeholder black->white.

### LINKED ISSUE #864: Consider using white on blue for user icon
Most of our material theme uses white on blue:

top-bar
Screenshot 2020-12-11 145559

But the user icon is black on blue:

user

By changing this to white on blue, it will also better match the proposed user guide (#862):

Screenshot 2020-12-11 145702

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #864

Screen Shot 2020-12-11 at 16 39 00

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/865)

### CODE REVIEW

**Comment by imnasnainaec** [comment]
It would be nice if we also had a white-text version of the logo.

**Comment by imnasnainaec** [comment]
Voila!

Screen Shot 2020-12-11 at 16 46 57

**Comment by johnthagen** [comment]
The new white logo looks much sharper!

**Review by johnthagen — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/865)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
