### PR TITLE
Enforce unique speaker names; Use name on export

### LINKED ISSUE #3010: [Speaker] Require distinct names; Export by name instead of ID
Currently multiple speakers can have the same name, which is just confusing.

Also, speaker info and consent files use the backend speaker id, which is just obfuscating.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #3010

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3018)

### CODE REVIEW

**Comment by imnasnainaec** [comment]
This pr also deals with inconsistent `Path.ChangeExtension(path, extension)` behavior when `extension` is an empty string:
https://github.com/dotnet/runtime/issues/100687

**Review by jmgrady — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, 10 of 11 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3018)* status: all files reviewed, 2 unresolved discussions (waiting on @imnasnainaec)

___
*[`Backend/Controllers/SpeakerController.cs` line 210 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/3018#-NvbbVWU1bOlrxKmPAG8:-NvbbVWU1bOlrxKmPAG9:bwt4vci) ([raw file](https://github.com/sillsdev/TheCombine/blob/c7c18ee34a89e8e9778259159d76184c76090f00/Backend/Controllers/SpeakerController.cs#L210)):*
> ```Smalltalk
>             if (await _speakerRepo.IsSpeakerNameInProject(projectId, name))
>             {
>                 return BadRequest("projectSettings.speaker.nameTaken");
> ```

This is a duplicate of the code in `CreateSpeaker`.  Pull out into a separate function so that it is only implemented once.



_Code quote:_
```Smalltalk
            // Ensure the new name is valid
            name = name.Trim();
            if (string.IsNullOrEmpty(name))
            {
                return BadRequest("projectSettings.speaker.nameEmpty");
            }
            if (await _speakerRepo.IsSpeakerNameInProject(projectId, name))
            {
                return BadRequest("projectSettings.speaker.nameTaken");
```
___
*[`Backend/Services/LiftService.cs` line 365 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/3018#-NvbctSb9e2u5E1nysyN:-NvbctSb9e2u5E1nysyO:ba7hxvp) ([raw file](https://github.com/sillsdev/TheCombine/blob/c7c18ee34a89e8e9778259159d76184c76090f00/Backend/Services/LiftService.cs#L365)):*
> ```Smalltalk
>                 var fileExt = Path.GetExtension(src);
>                 var convertToWav = fileExt.Equals(".webm", StringComparison.OrdinalIgnoreCase);
>                 fileExt = convertToWav ? ".wav" : fileExt;
> ```

This logic seems extra complex.  I find this easier to read:
```
if (fileExt.Equals(".webm", StringComparison.OrdinalIgnoreCase)
{
      fileExt = ".wav";
}
```



_Code quote:_
```Smalltalk
                var convertToWav = fileExt.Equals(".webm", StringComparison.OrdinalIgnoreCase);
                fileExt = convertToWav ? ".wav" : fileExt;
```
___
*[`Backend/Services/LiftService.cs` line 371 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/3018#-NvbdiXlBKb_uj7Wzth7:-NvbdiXlBKb_uj7Wzth8:b-6ovvkh) ([raw file](https://github.com/sillsdev/TheCombine/blob/c7c18ee34a89e8e9778259159d76184c76090f00/Backend/Services/LiftService.cs#L371)):*
> ```Smalltalk
>                 {
>                     dest = Path.ChangeExtension(dest, fileExt);
>                 }
> ```

This should also be put into a utility function rather than having multiple copies (see below and `FileStorage.cs`.



_Code quote:_
```Smalltalk
                if (!string.IsNullOrEmpty(fileExt))
                {
                    dest = Path.ChangeExtension(dest, fileExt);
                }
```
___
*[`public/locales/en/translation.json` line 205 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/3018#-NvbyCY63ajBnqYaf80K:-NvbyCY63ajBnqYaf80L:b-jcgmyj) ([raw file](https://github.com/sillsdev/TheCombine/blob/c7c18ee34a89e8e9778259159d76184c76090f00/public/locales/en/translation.json#L205)):*
> ```JSON
>       "enterName": "Enter the name of a new speaker",
>       "nameEmpty": "Speaker name is empty",
>       "nameTaken": "Speaker name is already taken",
> ```

Would it be better to say something like: "Speaker name is already taken in this project"? (or something like that)



_Code quote:_
```JSON
      "nameTaken": "Speaker name is already taken",
```

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3018)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

___
*[`Backend/Controllers/SpeakerController.cs` line 210 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/3018#-NvbbVWU1bOlrxKmPAG8:-NvciVpg1QJ5kx-sBwj_:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/c7c18ee34a89e8e9778259159d76184c76090f00/Backend/Controllers/SpeakerController.cs#L210)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

This is a duplicate of the code in `CreateSpeaker`.  Pull out into a separate function so that it is only implemented once.
</blockquote></details>

Done.
___
*[`Backend/Services/LiftService.cs` line 365 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/3018#-NvbctSb9e2u5E1nysyN:-NvciYmY4HT-HqKt44iQ:b705bmr) ([raw file](https://github.com/sillsdev/TheCombine/blob/c7c18ee34a89e8e9778259159d76184c76090f00/Backend/Services/LiftService.cs#L365)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

This logic seems extra complex.  I find this easier to read:
```
if (fileExt.Equals(".webm", StringComparison.OrdinalIgnoreCase)
{
      fileExt = ".wav";
}
```
</blockquote></details>

The `convertToWav` was defined to avoid a double `if (fileExt.Equals(".webm", StringComparison.OrdinalIgnoreCase)` check. (Note the `if (convertToWav)` below.)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3018)* status: 10 of 15 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

___
*[`Backend/Services/LiftService.cs` line 371 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/3018#-NvbdiXlBKb_uj7Wzth7:-Nvclbqn9byLNp8a4sFr:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/c7c18ee34a89e8e9778259159d76184c76090f00/Backend/Services/LiftService.cs#L371)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

This should also be put into a utility function rather than having multiple copies (see below and `FileStorage.cs`.
</blockquote></details>

Done.

**Review by jmgrady — APPROVED** [review]
> Reviewed 2 of 2 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3018)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by jmgrady — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3018)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
