### PR TITLE
[UserMenu] Unit tests: SiteSettings only visible to admins

### LINKED ISSUE #454: User Menu / Site Settings needs unit testing
In src/components/AppBar/UserMenu.tsx:
- [ ] Test that Site Settings shows up for admin users.
- [ ] Test that Site Settings does NOT show up for non-admin users.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #454

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/641)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
___
*[src/components/AppBar/UserMenu.tsx, line 40 at r1](https://reviewable.io/reviews/sillsdev/thecombine/641#-MFaTNA-5ONA6LnFE4mk:-MFaTNA-5ONA6LnFE4ml:b-f6i6dr) ([raw file](https://github.com/sillsdev/thecombine/blob/eb7ecffa307739706ee3fb8de7e899ac4f33c110/src/components/AppBar/UserMenu.tsx#L40)):*
> ```
> React.useEffect(() => {
>     getIsAdmin();
>   }, []);
> ```
enlighten me. What exactly did this try to do before?

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/641)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @imnasnainaec and @jasonleenaylor)

___
*[src/components/AppBar/tests/UserMenu.test.tsx, line 43 at r2](https://reviewable.io/reviews/sillsdev/thecombine/641#-MHHc0eqAwhxxKePoLTU:-MHHc0eqAwhxxKePoLTV:b-m012e) ([raw file](https://github.com/sillsdev/thecombine/blob/3211dfe35001cd03f8f2bf547889f033c8014eb4/src/components/AppBar/tests/UserMenu.test.tsx#L43)):*
> ```XML
>   });
> 
>   it("should only show site settings to general users", async () => {
> ```

maybe something here or in a comment below should mention what the extra admin menu item is. :)

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/641)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/641)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

___
*[src/components/AppBar/UserMenu.tsx, line 40 at r1](https://reviewable.io/reviews/sillsdev/thecombine/641#-MFaTNA-5ONA6LnFE4mk:-MHHg9Lt9iV0muSFDEd8:b-lplijb) ([raw file](https://github.com/sillsdev/thecombine/blob/dd7d7349d0f3ec380299be797ce84bde82afa7e3/src/components/AppBar/UserMenu.tsx#L40)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> React.useEffect(() => {
>     getIsAdmin();
>   }, []);
> ```
enlighten me. What exactly did this try to do before?
</blockquote></details>

I think `useEffect` is triggered on render, and that was unnecessary in this context.
___
*[src/components/AppBar/tests/UserMenu.test.tsx, line 43 at r2](https://reviewable.io/reviews/sillsdev/thecombine/641#-MHHc0eqAwhxxKePoLTU:-MHHgFds3Jqwtt1w5u_X:b-hwjtok) ([raw file](https://github.com/sillsdev/thecombine/blob/3211dfe35001cd03f8f2bf547889f033c8014eb4/src/components/AppBar/tests/UserMenu.test.tsx#L43)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

maybe something here or in a comment below should mention what the extra admin menu item is. :)
</blockquote></details>

Ah, my description was backwards. Better?

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/641)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
