### PR TITLE
Document the canonical way to activate a Python virtual environment

### PR DESCRIPTION
**Pull request by johnthagen**
This usage also matches the macOS instructions

For reference, see: https://docs.python.org/3/tutorial/venv.html#creating-virtual-environments

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1470)

### CODE REVIEW

**Review by jmgrady — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1470)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[README.md, line 261 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1470#-MoJe-C_64z1zm6UX2VW:-MoJe-Ca9RBkN6Xb9wmV:b-z6rm43) ([raw file](https://github.com/sillsdev/thecombine/blob/b7422ae7f33b98b600382bb7ef175750c603fe79/README.md#L261)):*
I am not sure why this is considered 'canonical'.  From https://ss64.com/bash/source.html:
> source is a synonym for dot/period '.' in bash, but not in POSIX sh, so for maximum compatibility use the period.

Since this statement is specifically instructing the reader how to do this in Linux, I think we should stick with `.`

**Comment by johnthagen** [comment]
___
*[README.md, line 261 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1470#-MoJe-C_64z1zm6UX2VW:-MoJfWV_BjTIcmnPKwwN:b-y8wdje) ([raw file](https://github.com/sillsdev/thecombine/blob/b7422ae7f33b98b600382bb7ef175750c603fe79/README.md#L261)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

I am not sure why this is considered 'canonical'.  From https://ss64.com/bash/source.html:
> source is a synonym for dot/period '.' in bash, but not in POSIX sh, so for maximum compatibility use the period.

Since this statement is specifically instructing the reader how to do this in Linux, I think we should stick with `.`
</blockquote></details>

In the Python standard library this is how it is documented: https://docs.python.org/3/tutorial/venv.html

Also this is how the `virutalenv` package documents it: https://virtualenv.pypa.io/en/latest/user_guide.html#activators

I think that we should not stray from the standard way this is documented in the Python ecosystem to avoid confusion. It also allows our mac and Linux instructions to match as they do in these other Python resources.

**Review by jmgrady — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1470)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[README.md, line 261 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1470#-MoJe-C_64z1zm6UX2VW:-MoJh5fTB4rDzccoEJVF:bvzmup6) ([raw file](https://github.com/sillsdev/thecombine/blob/b7422ae7f33b98b600382bb7ef175750c603fe79/README.md#L261)):*
My point was that it does not necessarily work for Linux.  If I am using `sh`, I get:
```
grady@saaz:~/projects/sil/combine$ sh -l
$ source venv/bin/activate
sh: 1: source: not found
$ 
```
In addition, your second reference states:
> ... (the source command might vary by shell - e.g. bash is .)

**Comment by johnthagen** [comment]
___
*[README.md, line 261 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1470#-MoJe-C_64z1zm6UX2VW:-MoJjXnUA7X2TWB_X3Zr:bhoptjn) ([raw file](https://github.com/sillsdev/thecombine/blob/b7422ae7f33b98b600382bb7ef175750c603fe79/README.md#L261)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

My point was that it does not necessarily work for Linux.  If I am using `sh`, I get:
```
grady@saaz:~/projects/sil/combine$ sh -l
$ source venv/bin/activate
sh: 1: source: not found
$ 
```
In addition, your second reference states:
> ... (the source command might vary by shell - e.g. bash is .)


</blockquote></details>

Agreed there are edge cases, but I still believe it's best to mimic the standard references to ease things for the common Python contributor and what I've seen used everywhere else. I feel if it was a real practical issue, then the Python docs would have been updated.

That being said, this isn't an important issue so if you'd like I will close the PR.

**Review by jmgrady — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1470)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[README.md, line 261 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1470#-MoJe-C_64z1zm6UX2VW:-MoJkZy2C_miDv7ltNiT:bw7jb5j) ([raw file](https://github.com/sillsdev/thecombine/blob/b7422ae7f33b98b600382bb7ef175750c603fe79/README.md#L261)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Agreed there are edge cases, but I still believe it's best to mimic the standard references to ease things for the common Python contributor and what I've seen used everywhere else. I feel if it was a real practical issue, then the Python docs would have been updated.

That being said, this isn't an important issue so if you'd like I will close the PR.
</blockquote></details>

I agree.  I don't want to make a mountain out of a molehill.  I think that the documentation should be correct though.  If we change to say `Bash` instead of `Linux` I am fine with changing it to `source`.

**Comment by johnthagen** [comment]
___
*[README.md, line 261 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1470#-MoJe-C_64z1zm6UX2VW:-MoJmxusE2gGP2kdaQy8:b-34w1z) ([raw file](https://github.com/sillsdev/thecombine/blob/b7422ae7f33b98b600382bb7ef175750c603fe79/README.md#L261)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

I agree.  I don't want to make a mountain out of a molehill.  I think that the documentation should be correct though.  If we change to say `Bash` instead of `Linux` I am fine with changing it to `source`.
</blockquote></details>

How do the latest changes look?

**Review by jmgrady — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1470)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @johnthagen)

___
*[README.md, line 261 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1470#-MoJe-C_64z1zm6UX2VW:-MoJoUGE-o66s_9i_g1J:b-duzqza) ([raw file](https://github.com/sillsdev/thecombine/blob/b7422ae7f33b98b600382bb7ef175750c603fe79/README.md#L261)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

How do the latest changes look?
</blockquote></details>

Perfect!  Thank you for your patience!

**Comment by johnthagen** [comment]
___
*[README.md, line 261 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1470#-MoJe-C_64z1zm6UX2VW:-MoJorPp4rAJJFeCjpTx:b-8fx2u7) ([raw file](https://github.com/sillsdev/thecombine/blob/b7422ae7f33b98b600382bb7ef175750c603fe79/README.md#L261)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Perfect!  Thank you for your patience!
</blockquote></details>

:+1:

**Review by johnthagen — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1470)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Pull request merged**
