### PR TITLE
Have export button state when download is ready

### LINKED ISSUE #937: Improve download-ready UI
"Click “Export” button and see green circle; also need to click download arrow to download (whilst green circle is still circling). However, download arrow is not so obvious, particularly on wide screen monitor and since green circle is still circling, the user may not realise that step 1 of the process is complete and that user interaction is required for step 2."
\# 1 on https://docs.google.com/document/d/1d3Cvt4FjCC1TxlVAYyun4K1qtFL1dx3S-wv2aCcPBmU

Also: UI improvements needed for download-in-progress (for large exports).

Also: On error, more detail of why it errored or what the user should do next would be useful.

### PR DESCRIPTION
**Pull request by imnasnainaec**
... rather than having a spinning wheel, waiting for the user to notice the download button that appeared.

Resolves #937

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1230)

### CODE REVIEW

**Comment by JacobHaimes** [comment]
Overall, it seems clear as to what is going on. At first, I tried clicking on the download ready text thinking that was the button to download it but quickly realized it was the arrow to the right so it shouldn't be that big of a deal.

**Review by JacobHaimes — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1230)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @WeJamUS)

**Review by WeJamUS — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1230)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by WeJamUS — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1230)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by JacobHaimes — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1230)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
