### PR TITLE
Add liftImported field to existing projects

### PR DESCRIPTION
**Pull request by jmgrady**
New script to add liftImported field to documents in ProjectsCollection. 

Updates the `CombineDatabase` for changes to the ProjectsCollection structure that is added with PR #810.

Field is set to true if a Compressed Upload ZIP file exists for the 
project; false otherwise.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/815)

### CODE REVIEW

**Comment by imnasnainaec** [comment]
This won't be able to identify projects with lift files imported after Nov 2 (#791), so #810 would allow some recent projects to import a second lift file.

**Review by jmgrady — COMMENTED** [review]
Are there any other ways that we might be able to tell that data have been imported?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/815#-:-MMInumVDd2QLBn8NxFl:b-fzuba6)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @jmgrady)

**Review by jmgrady — COMMENTED** [review]
I will update the script to look for this instead of the .zip file.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/815#-:-MMLvkjyDfwClMRqlVk7:b-c0z3hr)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @jmgrady)

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/815)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Pull request merged**
