### PR TITLE
Try to get lgtm to stop complaining about sensitive info in localStorage

### PR DESCRIPTION
**Pull request by imnasnainaec**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/730)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[src/goals/DefaultGoal/BaseGoalScreen/tests/BaseGoalScreen.test.tsx, line 41 at r2](https://reviewable.io/reviews/sillsdev/thecombine/730#-MI4hRfZ-Z0wrdaPHm_S:-MI4hRfZ-Z0wrdaPHm_T:b684bdu) ([raw file](https://github.com/sillsdev/thecombine/blob/344d7a4ae623b3e647e841b10b9225e747db6f7f/src/goals/DefaultGoal/BaseGoalScreen/tests/BaseGoalScreen.test.tsx#L41)):*
> ```XML
> 
>   const div = document.createElement("div");
>   let user: User = new User("TestUser", "TestUsername", "password");
> ```

Was LGTM flagging this because we used the name `"password"`?

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/730)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @johnthagen)

___
*[src/goals/DefaultGoal/BaseGoalScreen/tests/BaseGoalScreen.test.tsx, line 41 at r2](https://reviewable.io/reviews/sillsdev/thecombine/730#-MI4hRfZ-Z0wrdaPHm_S:-MI4hqnX0HDtvIFL19c_:bfdphp2) ([raw file](https://github.com/sillsdev/thecombine/blob/344d7a4ae623b3e647e841b10b9225e747db6f7f/src/goals/DefaultGoal/BaseGoalScreen/tests/BaseGoalScreen.test.tsx#L41)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Was LGTM flagging this because we used the name `"password"`?
</blockquote></details>

That's my understanding.

**Review by johnthagen — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/730)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by johnthagen — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/730)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by johnthagen** [comment]
Nice clean up included in this PR too. ✔️

**Pull request merged**
