### PR TITLE
Update Deployment Documentation

### LINKED ISSUE #1687: Update deployment documentation
PR #1683 creates a Docker image to create the ability to deploy _The Combine_ to a NUC (or other bare Ubuntu Server) from Windows.

The deployment documentation, `docs/deploy/README.md`, should be updated to describe this capability.

### PR DESCRIPTION
**Pull request by jmgrady**
Update the instructions for deploying _The Combine_ in the following scenarios:
- Development
- QA Server
- Production Server
- NUC

The document describes the installation process for each scenario.  When installing on a NUC, it describes a process for installing using local tools as well as using a docker image with the required tools pre-installed.

Closes #1687

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1699)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1699)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

___
*[`docs/deploy/README.md` line 16 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1699#-N7wVMAq37obLIhPQUtK:-N7wVMAq37obLIhPQUtL:b-p04sx8) ([raw file](https://github.com/sillsdev/thecombine/blob/47361c135227b4f2c438973a782f348e67d3ebba/docs/deploy/README.md#L16)):*
> ```Markdown
> 
> 1. [System Design](#system-design)
> 2. [Host System Requirements](#host-system-requirements)
> ```

This section doesn't exist anymore. 



_Code quote:_
```Markdown
2. [Host System Requirements](#host-system-requirements)
```
___
*[`docs/deploy/README.md` line 135 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1699#-N7wYbHMDRj2Lj5712mU:-N7wYbHMDRj2Lj5712mV:b-9yzilw) ([raw file](https://github.com/sillsdev/thecombine/blob/47361c135227b4f2c438973a782f348e67d3ebba/docs/deploy/README.md#L135)):*
> ```Markdown
> - [Setup Kubectl and Environment](#setup-kubectl-and-environment)
> - [Install Helm Charts Required by _The Combine_](#install-helm-charts-required-by-the-combine)
> - [Setup _The Combine_ Environment Variables](#setup-the-combine-environment-variables)
> ```

This section doesn't exist anymore.



_Code quote:_
```Markdown
- [Setup _The Combine_ Environment Variables](#setup-the-combine-environment-variables)
```

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1699)* status: 10 of 11 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[`docs/deploy/README.md` line 16 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1699#-N7wVMAq37obLIhPQUtK:-N7yz7eVBgb3Aw49dUkY:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/47361c135227b4f2c438973a782f348e67d3ebba/docs/deploy/README.md#L16)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

This section doesn't exist anymore. 
</blockquote></details>

Done.
___
*[`docs/deploy/README.md` line 135 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1699#-N7wYbHMDRj2Lj5712mU:-N7yz9856Smay3CSPMmP:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/47361c135227b4f2c438973a782f348e67d3ebba/docs/deploy/README.md#L135)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

This section doesn't exist anymore.
</blockquote></details>

Done.

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1699)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[`docs/deploy/README.md` line 371 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1699#-N7znIKU5xY9aER8yfpE:-N7ztVnf6NV7NjOgRGRT:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/912b7ccf536d39640dcc0d312992f17090f48a81/docs/deploy/README.md#L371)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Since the `<release>` tag is optional in the script and defaults to `latest`, that seems worth mentioning here in the README.
</blockquote></details>

Done.
___
*[`docs/deploy/README.md` line 399 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1699#-N7zlo8t7jQ3DARhZ-LQ:-N7zuMYX5UViwpOefnrX:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/912b7ccf536d39640dcc0d312992f17090f48a81/docs/deploy/README.md#L399)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Missing > after "...-file"? (Also in 2. below.)
</blockquote></details>

Done.
___
*[`docs/deploy/README.md` line 431 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1699#-N7zmCw1-dNRqIElR7VH:-N7zujp6-kRqEzho76SD:bj8kt2e) ([raw file](https://github.com/sillsdev/thecombine/blob/912b7ccf536d39640dcc0d312992f17090f48a81/docs/deploy/README.md#L431)):*
Agreed.  Changed to match the structure for using local tools:

> - if using the Docker image, open a terminal window and run:
>
>  ```console
>  docker run -it -v nuc-config:/config public.ecr.aws/thecombine/combine_deploy:latest
>  check_cert.py -n thecombine
>  ```
>
>- if using local tools, open a terminal window and run:
>
>  ```console
>  cd <COMBINE>/deploy/scripts
>  ./check_cert.py -n thecombine
>  ```
___
*[`docs/deploy/README.md` line 458 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1699#-N7zqeYQ-5ckWfxvIwc4:-N7zvcke0pyZYtbWLLCR:brznfw4) ([raw file](https://github.com/sillsdev/thecombine/blob/912b7ccf536d39640dcc0d312992f17090f48a81/docs/deploy/README.md#L458)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Your first bulleted item in this list ends with ; and the rest end with .
</blockquote></details>

Done.  Also made each item have complete sentences.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1699)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Pull request merged**
