### PR TITLE
Fix email invite logic

### LINKED ISSUE #1118: Refactor return type of InviteController.ValidateTokens
Currently an anonymous `bool` array is used to represent the status response in `InviteController.ValidateTokens`:

```cs
            var status = new bool[2];
            ...

            status[0] = activeTokenExists;
            status[1] = userIsRegistered;
```

This is not very descriptive, and if the frontend does anything with this, it would have to implicitly understand what each position meant.

We should instead return an object that has meaningful names:

```ts
{
  activeTokenExists: bool,
  userIsRegistered: bool,
}
```

### PR DESCRIPTION
**Pull request by johnthagen**
Closes #1118

- Fix frontend routing for invite links

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1122)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1122)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[src/types/invite.ts, line 3 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1122#-MYzr2yL7k1uilhwWGSV:-MYzr2yL7k1uilhwWGSW:bhey0n7) ([raw file](https://github.com/sillsdev/thecombine/blob/fe86109bcdf61062a7fdd583128f793159c311af/src/types/invite.ts#L3)):*
> ```
>   IsTokenValid: boolean;
>   IsUserRegistered: boolean;
> ```
We use lowercase first letter on the frontend for properties.

**Comment by imnasnainaec** [comment]
I should probably do similarly to `CharacterChange` (https://github.com/sillsdev/TheCombine/blob/master/src/goals/CharInventoryCreation/CharacterInventoryActions.tsx#L209).

**Comment by johnthagen** [comment]
___
*[src/types/invite.ts, line 3 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1122#-MYzr2yL7k1uilhwWGSV:-MYzumVd-jHnDvnLBiVM:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/fe86109bcdf61062a7fdd583128f793159c311af/src/types/invite.ts#L3)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>   IsTokenValid: boolean;
>   IsUserRegistered: boolean;
> ```
We use lowercase first letter on the frontend for properties.
</blockquote></details>

Done

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1122)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Review by imnasnainaec — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1122#-:-MZ-9PvyEQsu_ICGqlTS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Comment by johnthagen** [comment]
I'd like to merge #1124 first so that this can be tested

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1122)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1122)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Comment by johnthagen** [comment]
Current status: registration link passes to the backend, but the actual registration seems to fail.

**Comment by johnthagen** [comment]
Okay, actually this was working, but the user **must** use the same email address when they are registering that they were invited with.  I've updated the email template to call this out explicitly to avoid confusion.

**Review by jmgrady — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1122)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @johnthagen)

___
*[Backend/Services/InviteService.cs, line 47 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1122#-MZ32V8t570T75CIk081:-MZ32V8t570T75CIk082:bebjqbr) ([raw file](https://github.com/sillsdev/thecombine/blob/985cc3b8df7525ad7f7947f00a0212c2df08935b/Backend/Services/InviteService.cs#L47)):*
> ```
>                        "During registration, you must use the email address this message was received at for your user " +
>                        "profile.\n\n" +
> ```
I am not sure that this is necessarily correct.  My alma mater provides e-mail services for alumni.  Initially, it was simply e-mail forwarding so I could enter my `cornell.edu` email when I registered as a user on the Combine but all the mail would be forwarded to my `gmail.com` account.  Although I received it at my `gmail.com` address, I believe that the e-mail I need to use is the `cornell.edu` address.

Is there a reason, for example, security/privacy concerns, why we would not put the address we expect in the e-mail?  Better yet, could it be embedded in the URL so that the user does not need to enter it?

**Comment by johnthagen** [comment]
___
*[Backend/Services/InviteService.cs, line 47 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1122#-MZ32V8t570T75CIk081:-MZ3nH2a0YHHgUmUMtpN:b-jqpc07) ([raw file](https://github.com/sillsdev/thecombine/blob/985cc3b8df7525ad7f7947f00a0212c2df08935b/Backend/Services/InviteService.cs#L47)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

> ```
>                        "During registration, you must use the email address this message was received at for your user " +
>                        "profile.\n\n" +
> ```
I am not sure that this is necessarily correct.  My alma mater provides e-mail services for alumni.  Initially, it was simply e-mail forwarding so I could enter my `cornell.edu` email when I registered as a user on the Combine but all the mail would be forwarded to my `gmail.com` account.  Although I received it at my `gmail.com` address, I believe that the e-mail I need to use is the `cornell.edu` address.

Is there a reason, for example, security/privacy concerns, why we would not put the address we expect in the e-mail?  Better yet, could it be embedded in the URL so that the user does not need to enter it?
</blockquote></details>

Done.

Made a follow on issue for the more convenient registration if we'd like to go down that path. I too thought about this while implementing this fix: https://github.com/sillsdev/TheCombine/issues/1127

**Review by jmgrady — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1122#-:-MZ409lC7lbnSzj5bkZs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Pull request merged**
