### PR TITLE
In setState, use (prevState, props) where appropriate

### PR DESCRIPTION
**Pull request by imnasnainaec**
Per https://lgtm.com/rules/1819283066/

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/740)

### CODE REVIEW

**Review by jmgrady — COMMENTED** [review]
> Reviewed 10 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/740)* status: 10 of 20 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[src/components/PasswordReset/RequestPage/component.tsx, line 63 at r1](https://reviewable.io/reviews/sillsdev/thecombine/740#-MILmSZUCBeljtItzR16:-MILmSZUCBeljtItzR17:b-j5f6c1) ([raw file](https://github.com/sillsdev/thecombine/blob/6ded83528d80423d4c3a88186d92f1348f136efe/src/components/PasswordReset/RequestPage/component.tsx#L63)):*
> ```
>  async setTextField(emailOrUsername: string) {
> ```
Why is this asynchronous?  I don't see anything that would require that.

**Review by jmgrady — APPROVED** [review]
:lgtm:

> Reviewed 10 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/740#-:-MIOwvDc3zKH0_x83XGm:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/740)* status: 19 of 20 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[src/components/PasswordReset/RequestPage/component.tsx, line 63 at r1](https://reviewable.io/reviews/sillsdev/thecombine/740#-MILmSZUCBeljtItzR16:-MIPAcP-5LpVNXnhzaJd:bss4a2b) ([raw file](https://github.com/sillsdev/thecombine/blob/6ded83528d80423d4c3a88186d92f1348f136efe/src/components/PasswordReset/RequestPage/component.tsx#L63)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

> ```
>  async setTextField(emailOrUsername: string) {
> ```
Why is this asynchronous?  I don't see anything that would require that. 
</blockquote></details>

Removed.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/740)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
