### PR TITLE
Improve lift import error messages

### PR DESCRIPTION
**Pull request by johnthagen**
Improve error messages when malformed Lift files are imported.

When #1388 is merged, these will be displayed to the users.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1394)

### CODE REVIEW

**Review by jmgrady — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1394)* status: all files reviewed, 2 unresolved discussions (waiting on @johnthagen)

___
*[Backend/Controllers/LiftController.cs, line 71 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1394#-MkvxYCT432OFSHaXR67:-MkvxYCU3QLdYfo2ioJZ:bow5kcm) ([raw file](https://github.com/sillsdev/thecombine/blob/13909ca8f25398d80a077edf60da828b25947dd6/Backend/Controllers/LiftController.cs#L71)):*
> ```
> "Malformed Lift file: "
> ```
If the error messages are to be meaningful, they should be localized - but I suppose that is a frontend function.  This would suggest that an error code should be returned to the frontend and the frontend should translate that into a localized message.

That said, I see that previous work has the error messages that are all returned in English.
___
*[Backend/Controllers/LiftController.cs, line 140 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1394#-Mkw-8X18b9PxBQ9q1oM:-Mkw-8X18b9PxBQ9q1oN:b-gik4pj) ([raw file](https://github.com/sillsdev/thecombine/blob/13909ca8f25398d80a077edf60da828b25947dd6/Backend/Controllers/LiftController.cs#L140)):*
> ```
> Your zip file structure has the wrong number of directories
> ```
It would be more helpful to tell the user what is the right number of directories.

**Comment by johnthagen** [comment]
___
*[Backend/Controllers/LiftController.cs, line 71 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1394#-MkvxYCT432OFSHaXR67:-Mkw8F8pD1P3A-GpOdwm:bj224cf) ([raw file](https://github.com/sillsdev/thecombine/blob/13909ca8f25398d80a077edf60da828b25947dd6/Backend/Controllers/LiftController.cs#L71)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

> ```
> "Malformed Lift file: "
> ```
If the error messages are to be meaningful, they should be localized - but I suppose that is a frontend function.  This would suggest that an error code should be returned to the frontend and the frontend should translate that into a localized message.

That said, I see that previous work has the error messages that are all returned in English.
</blockquote></details>

This is an interesting point that merits further discussion.

**Comment by johnthagen** [comment]
___
*[Backend/Controllers/LiftController.cs, line 140 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1394#-Mkw-8X18b9PxBQ9q1oM:-Mkw8qDP75VQkSLr4GIG:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/13909ca8f25398d80a077edf60da828b25947dd6/Backend/Controllers/LiftController.cs#L140)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

> ```
> Your zip file structure has the wrong number of directories
> ```
It would be more helpful to tell the user what is the right number of directories.
</blockquote></details>

Done.

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1394)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[Backend/Controllers/LiftController.cs, line 140 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1394#-Mkw-8X18b9PxBQ9q1oM:-Mkw9UykEjkEjczI1vsf:byskf2g) ([raw file](https://github.com/sillsdev/thecombine/blob/13909ca8f25398d80a077edf60da828b25947dd6/Backend/Controllers/LiftController.cs#L140)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The default case still says that it has the wrong number of directories.  I think that the logic could be simpler if we just check for the `__MACOSX` directory first and then:
```
if (numDirs == 1)
{
   // we're good
}
else
{
   return BadRequest($"{invalidLiftFileMessagePrefix}Zip file does not have one directory.");
}
```

**Review by jmgrady — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1394)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Pull request merged**
