### PR TITLE
[ReviewEntries] Pronunciations sort and filter

### LINKED ISSUE #716: [ReviewEntries] Filtering/sorting by Pronunciation unusable
(Mentioned by Chuck in Sep. 16 debrief.)

Typing anything into the Pronunciation filter results in "No records to display":
image

Sorting by Pronunciation has no effect:
image
image

We need to either set `filtering: false` and `sorting: false` for that column or (preferably) make it usable (e.g., filter and sort by number of recordings).

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #716 

Sort by number of pronunciations:
imageimageimage

Filter by number of pronunciations:
imageimageimage

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/721)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx, line 195 at r2](https://reviewable.io/reviews/sillsdev/thecombine/721#-MHXTFM8EqZVbfLg8nI5:-MHXTFM8EqZVbfLg8nI6:bq09uqi) ([raw file](https://github.com/sillsdev/thecombine/blob/e71fe3e1517fcaa06cff728543faa3b671e3690d/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx#L195)):*
> ```XML
>       return false;
>     },
>     customSort: (a: any, b: any): number => {
> ```

Could we give better types than `any` here?

**Comment by johnthagen** [comment]
___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx, line 266 at r2](https://reviewable.io/reviews/sillsdev/thecombine/721#-MHXTJqo12rjtvcG1mra:-MHXTJqo12rjtvcG1mrb:bae50s1) ([raw file](https://github.com/sillsdev/thecombine/blob/e71fe3e1517fcaa06cff728543faa3b671e3690d/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx#L266)):*
> ```XML
>       return parseInt(filter) === rowData.pronunciationFiles.length;
>     },
>     customSort: (a: any, b: any): number => {
> ```

It looks like `a` and `b` have concrete types (we are calling `.pronunciationFiles` on them). Could we give them a more concrete type?

**Comment by johnthagen** [comment]
Functionality works well. I worry a bit that it's a little difficult to *discover* this UI. As in, there is no UI indication that a user should put in an integer into that field and to sort by the number of recordings.

Is there anyway we can add a UI hint that says "Number of recordings" or similar?

Similar to :

Screenshot 2020-09-18 144219

**Review by johnthagen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/721)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec)

**Review by johnthagen — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/721)* status: all files reviewed, 2 unresolved discussions (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/721)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @johnthagen)

___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx, line 195 at r2](https://reviewable.io/reviews/sillsdev/thecombine/721#-MHXTFM8EqZVbfLg8nI5:-MHXgJxk7Wz_gO6TNJxw:bsgi3yj) ([raw file](https://github.com/sillsdev/thecombine/blob/e71fe3e1517fcaa06cff728543faa3b671e3690d/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx#L195)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Could we give better types than `any` here?
</blockquote></details>

Yes, but I'm leaving that change for #723 
___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx, line 266 at r2](https://reviewable.io/reviews/sillsdev/thecombine/721#-MHXTJqo12rjtvcG1mra:-MHXgZ2d2u7kx8qXffjE:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/e71fe3e1517fcaa06cff728543faa3b671e3690d/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx#L266)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

It looks like `a` and `b` have concrete types (we are calling `.pronunciationFiles` on them). Could we give them a more concrete type?
</blockquote></details>

Done

**Comment by imnasnainaec** [comment]
@johnthagen Is this sufficient (to avoid more phrases to translate)? 
image

**Review by johnthagen — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/721)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
