### PR TITLE
[AudioPlayer] Implement play-or-delete menu for touchscreen/tablet use

### LINKED ISSUE #681: No way to delete recordings from a touch screen
Deleting audio requires shift+click, which isn't accessible on a touch-screen. Perhaps implement a long-press activated menu with a delete option.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #681 

The interface trigger should be (at least) one of:
- event is long click/press
- **event is press but not click**
- device is mobile/tablet

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/710)

### CODE REVIEW

**Comment by imnasnainaec** [comment]
Testing on an Acer laptop with a touchscreen and in Chromium with a [User-Agent switcher](https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg).

**Comment by imnasnainaec** [comment]
One issue is that a long-press on a touch screen can bring up the default context menu, so we may need to intercept that.
E.g.: https://medium.com/@subalerts/https-medium-com-implementing-custom-context-menu-in-react-js-part-1-b103260c724c

**Comment by imnasnainaec** [comment]
Tried installing https://www.npmjs.com/package/react-native-device-info, but then TheCombine couldn't even compile.
Trying to use https://www.npmjs.com/package/react-device-detect, but it doesn't recognize iOS or Android spoofing by User-Agent Switcher for Chrome.

**Review by jasonleenaylor — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/710)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[src/components/Pronunciations/AudioPlayer.tsx, line 43 at r2](https://reviewable.io/reviews/sillsdev/thecombine/710#-MHNGGsi82enWcU8CaHu:-MHNGGsjDUp0J6BatreF:b-1z9ezw) ([raw file](https://github.com/sillsdev/thecombine/blob/a196e11dacff54749920e9803097ae9d0ea147c0/src/components/Pronunciations/AudioPlayer.tsx#L43)):*
> ```
> deletePlay
> ```
Not a big fan of this function name. What about deleteAudio?

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/710)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jasonleenaylor)

___
*[src/components/Pronunciations/AudioPlayer.tsx, line 43 at r2](https://reviewable.io/reviews/sillsdev/thecombine/710#-MHNGGsi82enWcU8CaHu:-MHNYwjl5ayrTkWaRNpB:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/a196e11dacff54749920e9803097ae9d0ea147c0/src/components/Pronunciations/AudioPlayer.tsx#L43)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> deletePlay
> ```
Not a big fan of this function name. What about deleteAudio?
</blockquote></details>

Done

**Review by jasonleenaylor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/710)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jasonleenaylor)

___
*[src/components/Buttons/ButtonConfirmation.tsx, line 23 at r3](https://reviewable.io/reviews/sillsdev/thecombine/710#-MHNdvqQ8ZMe4-EBgO0O:-MHNdvqQ8ZMe4-EBgO0P:bf1ju41) ([raw file](https://github.com/sillsdev/thecombine/blob/596151aebdaf7b37239be885a4d21e91291b3434/src/components/Buttons/ButtonConfirmation.tsx#L23)):*
> ```
> utton for archiving/restoring project (changing isActive)
> ```
Outdated comment

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/710)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 2 of 5 files at r2, 3 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/710)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
