### PR TITLE
Handle Skipped Merge Sets

### LINKED ISSUE #1631: Add UX and goal for handling Skipped merge sets
When a user skips an entry it is offered again the next time the merge starts. This can cause problems if a project has many sets of possible merges where the answer isn't obvious and must be dealt with later.

UX Plan: Change the word 'Skip' to 'Defer'. Deferred entries will be handled separately from the rest of the merge possibilities. When a user completes a set of possible merges and is offered the opportunity to continue or stop they will also have an option of merging deferred entries.

There will be a new goal, ~~Merge Deferred entries~~ Review Deferred Duplicates, which will be available only when the user has deferred some merge sets. ~~If there are no Deferred entries clicking on the goal will offer a message "There are no deferred merge possibilities to work on."~~

The Deferred entries goal will offer all sets of deferred entries instead of the default number.

Development Details:
The Merge Deferred Entries goal will re-use as much of the existing Merge component as possible.
A 'gray' list will be created with the deferred sets. The graylist sets will be excluded from the standard Merge goal consideration.
The graylist should be cleaned up in the same method that we currently use on the blacklist. (The blacklist we build from the use of 'Save & Continue'.)
The results of this goal (its "completed" form) should be the same as 'Merge Duplicates' in the goal history.

Acceptance test:
* Open/create an empty project
* In project settings, turn Autocomplete off
* In Data Entry, in any domain, add 7 words with the following vernacular forms (and any gloss you want): identical, identical, mixed, mixed, mixed2, similar, similar2
* Go the Data Cleanup, there should be no "Review Deferred Duplicates" button visible
* Click "Merge Duplicates", you should see "1 of 2"
* For the pair of words with vernacular form "identical" click "Save & Continue"; for the pair of words with vernacular form "mixed" click "Defer"
* Opt not to continue merging; back in Data Cleanup, there should now be a "Review Deferred Duplicate" button
* Click on "Review Deferred Duplicates" and see just one set, a pair of words with vernacular form "mixed"
* Neither save nor defer, but instead return to Data Cleanup
* Click on "Merge Duplicates"; you should see "1 of 2"
* For the three words with vernacular forms "mixed", "mixed", "mixed2" click "Save & Continue"; for the "similar", "similar2" pair click "Defer"
* Opt to continue merging; there should be no other potential duplicates
* Go to Data Cleanup and click "Review Deferred Duplicates"
* This time, the only suggested set should be the "similar", "similar2" pair
* Drag the sense from the "similar2" column into the "similar" column and click "Save & Continue"
* Back at the Data Cleanup screen, the "Review Deferred Duplicates" button should no longer be available
* In the Goal history (at right for wide screens, at the bottom for narrow screens) the first option should be a Review Deferred Duplicates with "Number of merges completed: 1"; click on it and see that the merge is clearly shown

### PR DESCRIPTION
**Pull request by Apoktieno**
Closes #1631

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2610)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2610)* status: 0 of 26 files reviewed, 5 unresolved discussions (waiting on @Apoktieno)

___
*[`Backend/Helper/DuplicateFinder.cs` line 63 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2610#-NexjBj5Cfq12SD6yR1T:-NexjBj65mjAJLGojhSo:b-x4abd4) ([raw file](https://github.com/sillsdev/TheCombine/blob/65297d313e22b951fde88aee36b75537b0fec725/Backend/Helper/DuplicateFinder.cs#L63)):*
> ```Smalltalk
>         /// each with multiple <see cref="Word"/>s having a common Vernacular and are in Graylist.
>         /// </summary>
>         public async Task<List<List<Word>>> GetIdenticalGrayVernWords(
> ```

This function `GetIdenticalGrayWords` isn't needed.
___
*[`Backend/Helper/DuplicateFinder.cs` line 124 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2610#-NexjHJ6-MPcmGmC-2YG:-NexjHJ6-MPcmGmC-2YH:bgcch0a) ([raw file](https://github.com/sillsdev/TheCombine/blob/65297d313e22b951fde88aee36b75537b0fec725/Backend/Helper/DuplicateFinder.cs#L124)):*
> ```Smalltalk
>                 // Check if set is in blacklist.
>                 var ids = new List<string> { word.Id };
>                 ids.AddRange(similarWords.Select(w => w.Item2.Id));
> ```

Here inside `GetSimilarWords`, a graylist analog to `isInBlacklist` should be added.
___
*[`Backend/Helper/DuplicateFinder.cs` line 170 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2610#-Nexj2n640W0DlJC60sq:-Nexj2n640W0DlJC60sr:b3xrc32) ([raw file](https://github.com/sillsdev/TheCombine/blob/65297d313e22b951fde88aee36b75537b0fec725/Backend/Helper/DuplicateFinder.cs#L170)):*
> ```Smalltalk
>         /// the outer list is ordered by similarity of the first two items in each inner List.
>         /// </returns>
>         public async Task<List<List<Word>>> GetSimilarGrayWords(
> ```

This function `GetSimilarGrayWords` isn't needed.
___
*[`Backend/Repositories/MergeGrayListRepository.cs` line 1 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2610#-NexiQfV6D2BIhJQeSpm:-NexiQfWDX53tXCks0SX:b4tfimm) ([raw file](https://github.com/sillsdev/TheCombine/blob/65297d313e22b951fde88aee36b75537b0fec725/Backend/Repositories/MergeGrayListRepository.cs#L1)):*
> ```Smalltalk
> using System;
> ```

This filename has a capital L `GrayList` though it's `Graylist` or `graylist` everywhere else.
___
*[`Backend/Services/MergeService.cs` line 366 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2610#-Nexatks78yN4tyjTdJu:-Nexatks78yN4tyjTdJv:bur5u6) ([raw file](https://github.com/sillsdev/TheCombine/blob/65297d313e22b951fde88aee36b75537b0fec725/Backend/Services/MergeService.cs#L366)):*
> ```Smalltalk
> 
>                 var subList = new List<Word>();
>                 subList = (entry.WordIds.Select(wordId => (frontierWords.Where(word => wordId == word.Id).ToList()[0])).ToList());
> ```

When I recommended using `Select`, I was thinking that the grey list entries had lists of words. My apologies, I had forgotten that they had lists of word ids instead. Using `Where` instead of `Select` will simplify your solution a little:
```
            var graylist = await _mergeGraylistRepo.GetAllEntries(projectId, userId);
            var frontier = await _wordRepo.GetFrontier(projectId);
            var wordLists = new List<List<Word>> { Capacity = maxLists };
            foreach (var entry in graylist)
            {
                if (wordLists.Count == maxLists) {
                    break;
                }
                wordLists.Add(frontier.Where(w => entry.WordIds.Contains(w.Id)).ToList());
            }
            return wordLists;
```

If you hover your cursor over `Capacity` in VSCode, it will tell you that isn't a hard limit, but a memory management thing, so we want a check to prevent adding more to the list.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2610)* status: 0 of 26 files reviewed, 3 unresolved discussions (waiting on @Apoktieno)

___
*[`src/components/GoalTimeline/Redux/GoalActions.ts` line 216 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2610#-NfBfM2I3qHutbgFvD50:-NfBfM2I3qHutbgFvD51:b-vg92ni) ([raw file](https://github.com/sillsdev/TheCombine/blob/8925cc53e4d9549b64ef91f94327e8f10ca78d08/src/components/GoalTimeline/Redux/GoalActions.ts#L216)):*
> ```XML
>       return await fetchMergeDupsData(5, maxNumSteps(goalType));
>     case GoalType.ReviewDeferredDups:
>       return await fetchMergeGrayDupsData(5, maxNumSteps(goalType));
> ```

The newer function `getGraylistEntries` is what we want here. Graylist functions that depend on  `maxInList` should be replaced or removed.
___
*[`src/types/goals.ts` line 59 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2610#-NfBekW75xIobmPrST7b:-NfBekW75xIobmPrST7c:bobr6f7) ([raw file](https://github.com/sillsdev/TheCombine/blob/8925cc53e4d9549b64ef91f94327e8f10ca78d08/src/types/goals.ts#L59)):*
> ```XML
>   ValidateStrWords = "validateStrWords",
>   ReviewDeferredDups = "ReviewDeferredDups",
> }
> ```

After `Default`, alphabetical order in the two above `enum`s

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 2 of 8 files at r5, 1 of 10 files at r7, 31 of 41 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2610)* status: 34 of 48 files reviewed, 7 unresolved discussions (waiting on @Apoktieno and @imnasnainaec)

___
*[`Backend/Interfaces/IMergeGraylistRepository.cs` line 14 at r8](https://reviewable.io/reviews/sillsdev/TheCombine/2610#-NfS2nj_-3oT0LjGxyy3:-NfS2nj_-3oT0LjGxyy4:bb740l2) ([raw file](https://github.com/sillsdev/TheCombine/blob/83bbea8abbdd4e983a8339e4107831268fb67a41/Backend/Interfaces/IMergeGraylistRepository.cs#L14)):*
> ```Smalltalk
>         Task<MergeWordSet> Create(MergeWordSet wordSetEntry);
>         Task<bool> Delete(string projectId, string entryId);
>         Task<bool> DeleteAllEntries(string projectId);
> ```

Sets



_Code quote:_
```Smalltalk
Entries
```
___
*[`Backend/Models/UserEdit.cs` line 188 at r8](https://reviewable.io/reviews/sillsdev/TheCombine/2610#-NfS3V5t4RmG8DtVldfm:-NfS3V5t4RmG8DtVldfn:bym17c2) ([raw file](https://github.com/sillsdev/TheCombine/blob/83bbea8abbdd4e983a8339e4107831268fb67a41/Backend/Models/UserEdit.cs#L188)):*
> ```Smalltalk
>         ValidateStrWords,
>         MergeDups,
>         SpellCheckGloss,
> ```

This change won't break old projects will it?



_Code quote:_
```Smalltalk
SpellCheckGloss
```
___
*[`Backend/Services/MergeService.cs` line 137 at r8](https://reviewable.io/reviews/sillsdev/TheCombine/2610#-NfS4Dkx0QFTx8kA4P3C:-NfS4Dkx0QFTx8kA4P3D:b-n7ixk2) ([raw file](https://github.com/sillsdev/TheCombine/blob/83bbea8abbdd4e983a8339e4107831268fb67a41/Backend/Services/MergeService.cs#L137)):*
> ```Smalltalk
>                 }
>             }
>             await RemoveFromMergeGraylist(projectId, userId, wordIds);
> ```

Oooh, good foresight.
___
*[`Backend/Services/MergeService.cs` line 153 at r8](https://reviewable.io/reviews/sillsdev/TheCombine/2610#-NfS501rBTZrx5ly_OZl:-NfS501rBTZrx5ly_OZm:b-lcv675) ([raw file](https://github.com/sillsdev/TheCombine/blob/83bbea8abbdd4e983a8339e4107831268fb67a41/Backend/Services/MergeService.cs#L153)):*
> ```Smalltalk
>             }
>             var graylist = await _mergeGraylistRepo.GetAllSets(projectId, userId);
>             foreach (var entry in graylist)
> ```

Why do we delete and recreate if we find an existing Graylist entry?
___
*[`Backend/Services/MergeService.cs` line 175 at r8](https://reviewable.io/reviews/sillsdev/TheCombine/2610#-NfS5FZx8i0WVcdJmIrR:-NfS5FZx8i0WVcdJmIrS:b-i94llk) ([raw file](https://github.com/sillsdev/TheCombine/blob/83bbea8abbdd4e983a8339e4107831268fb67a41/Backend/Services/MergeService.cs#L175)):*
> ```Smalltalk
>             }
>             var graylist = await _mergeGraylistRepo.GetAllSets(projectId, userId);
>             var removed = new List<string>();
> ```

Under what circumstances do we expect to have more than one Graylist set with the same items? Oh, I see, in the UpdateGrayList ...
___
*[`Backend/Services/MergeService.cs` line 339 at r8](https://reviewable.io/reviews/sillsdev/TheCombine/2610#-NfS6SJn2GUvmcUDyG-n:-NfS6SJn2GUvmcUDyG-o:b5y16c) ([raw file](https://github.com/sillsdev/TheCombine/blob/83bbea8abbdd4e983a8339e4107831268fb67a41/Backend/Services/MergeService.cs#L339)):*
> ```Smalltalk
>                 wordLists = await dupFinder.GetSimilarWords(
>                     collection, wordIds => IsInMergeBlacklist(projectId, wordIds, userId),
>                     wordIds => IsInMergeGraylist(projectId, wordIds, userId));
> ```

I'm surprised this isn't a compile warning.
___
*[`Backend/Interfaces/IMergeBlacklistRepository.cs` line 13 at r8](https://reviewable.io/reviews/sillsdev/TheCombine/2610#-NfS3GGICygz8YBENYZs:-NfS3GGICygz8YBENYZt:bwkrw9p) ([raw file](https://github.com/sillsdev/TheCombine/blob/83bbea8abbdd4e983a8339e4107831268fb67a41/Backend/Interfaces/IMergeBlacklistRepository.cs#L13)):*
> ```Smalltalk
>         Task<MergeWordSet?> GetSet(string projectId, string entryId);
>         Task<MergeWordSet> Create(MergeWordSet wordSetEntry);
>         Task<bool> Delete(string projectId, string entryId);
> ```

DeleteAllSets?
___
*[`Backend/Repositories/MergeGraylistRepository.cs` line 24 at r8](https://reviewable.io/reviews/sillsdev/TheCombine/2610#-NfS3ubl6a-GkkvXOVbN:-NfS3ubl6a-GkkvXOVbO:b-8jqb46) ([raw file](https://github.com/sillsdev/TheCombine/blob/83bbea8abbdd4e983a8339e4107831268fb67a41/Backend/Repositories/MergeGraylistRepository.cs#L24)):*
> ```Smalltalk
> 
>         /// <summary> Finds all <see cref="MergeWordSet"/>s for specified <see cref="Project"/>. </summary>
>         public async Task<List<MergeWordSet>> GetAllSets(string projectId, string? userId = null)
> ```

Do we actually have a use case for the `userId == null` case? I know this was copied from Blacklist, but it has me wondering.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2610)* status: 26 of 48 files reviewed, 7 unresolved discussions (waiting on @Apoktieno and @jasonleenaylor)

___
*[`Backend/Models/UserEdit.cs` line 188 at r8](https://reviewable.io/reviews/sillsdev/TheCombine/2610#-NfS3V5t4RmG8DtVldfm:-NfSWAPtBALpb7MbRxFU:bi9ssi5) ([raw file](https://github.com/sillsdev/TheCombine/blob/83bbea8abbdd4e983a8339e4107831268fb67a41/Backend/Models/UserEdit.cs#L188)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

This change won't break old projects will it?
</blockquote></details>

This whole `enum` is unused, so I removed it.
___
*[`Backend/Services/MergeService.cs` line 339 at r8](https://reviewable.io/reviews/sillsdev/TheCombine/2610#-NfS6SJn2GUvmcUDyG-n:-NfSV9nA4leA66WFxbp7:b-c8cw1m) ([raw file](https://github.com/sillsdev/TheCombine/blob/83bbea8abbdd4e983a8339e4107831268fb67a41/Backend/Services/MergeService.cs#L339)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

I'm surprised this isn't a compile warning.
</blockquote></details>

Having the same input variable name for two neighboring lambda functions?

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 1 of 7 files at r2, 3 of 41 files at r8, 8 of 8 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2610)* status: 38 of 48 files reviewed, 4 unresolved discussions (waiting on @Apoktieno and @imnasnainaec)

___
*[`Backend/Services/MergeService.cs` line 153 at r8](https://reviewable.io/reviews/sillsdev/TheCombine/2610#-NfS501rBTZrx5ly_OZl:-NfSi_M7DCyOYiHbZP-3:bmxilld) ([raw file](https://github.com/sillsdev/TheCombine/blob/83bbea8abbdd4e983a8339e4107831268fb67a41/Backend/Services/MergeService.cs#L153)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Why do we delete and recreate if we find an existing Graylist entry?
</blockquote></details>

:LGTM:
___
*[`Backend/Services/MergeService.cs` line 339 at r8](https://reviewable.io/reviews/sillsdev/TheCombine/2610#-NfS6SJn2GUvmcUDyG-n:-NfSifWA4k6W_pCj74Pt:bjj7clq) ([raw file](https://github.com/sillsdev/TheCombine/blob/83bbea8abbdd4e983a8339e4107831268fb67a41/Backend/Services/MergeService.cs#L339)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Having the same input variable name for two neighboring lambda functions?
</blockquote></details>

Yes. There are warnings for less, this is more of a 'lint' warning though.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2610)* status: 35 of 48 files reviewed, 4 unresolved discussions (waiting on @Apoktieno and @jasonleenaylor)

___
*[`Backend/Services/MergeService.cs` line 339 at r8](https://reviewable.io/reviews/sillsdev/TheCombine/2610#-NfS6SJn2GUvmcUDyG-n:-NfW4nm1B6qC5mkrhz4_:b-sw2rnk) ([raw file](https://github.com/sillsdev/TheCombine/blob/83bbea8abbdd4e983a8339e4107831268fb67a41/Backend/Services/MergeService.cs#L339)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Yes. There are warnings for less, this is more of a 'lint' warning though.
</blockquote></details>

consolidated

**Review by jasonleenaylor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 12 files at r3, 2 of 8 files at r5, 7 of 41 files at r8, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2610#-:-NfWXyAp1Cny22uKr_fR:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Apoktieno)

**Pull request merged**
