### PR TITLE
Add more linting rules; Make progress on function return types

### PR DESCRIPTION
**Pull request by imnasnainaec**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1523)

### CODE REVIEW

**Comment by johnthagen** [comment]
Do you want to go ahead and try to tackle https://github.com/sillsdev/TheCombine/issues/1223#issuecomment-902125077 as well here?

**Comment by imnasnainaec** [comment]
> @imnasnainaec Do you want to go ahead and try to tackle [#1223 (comment)](https://github.com/sillsdev/TheCombine/issues/1223#issuecomment-902125077) as well here?

There are a lot to fix for that, so I was hoping to just make some progress on it here, and finish it later.

**Comment by johnthagen** [comment]
___
*[package.json, line 157 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1523#-Msq9n-KCVrtuz6EJv1d:-Msq9n-KCVrtuz6EJv1e:bb74v9m) ([raw file](https://github.com/sillsdev/thecombine/blob/234627a0fa1506cc834b1475a658f6471ea7182e/package.json#L157)):*
> ```JSON
>       ],
>       "no-undef": "off",
>       "prefer-const": "error",
> ```

I think this could still be `"warn"`. Our CI doesn't pass if there are any warning, so it it still wouldn't be possible to let one slip through into `master`, but locally, I could see it maybe being nice not to error for something like using `let`.

Also, I'm really glad we are finally enforcing consistent use of `const` :dancer:

**Comment by johnthagen** [comment]
___
*[package.json, line 157 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1523#-Msq9n-KCVrtuz6EJv1d:-MsqAECmDqtZl1n-3tfP:b-omjhro) ([raw file](https://github.com/sillsdev/thecombine/blob/234627a0fa1506cc834b1475a658f6471ea7182e/package.json#L157)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I think this could still be `"warn"`. Our CI doesn't pass if there are any warning, so it it still wouldn't be possible to let one slip through into `master`, but locally, I could see it maybe being nice not to error for something like using `let`.

Also, I'm really glad we are finally enforcing consistent use of `const` :dancer: 
</blockquote></details>

Oh weird, maybe `"error"` is the only option? 

https://eslint.org/docs/rules/prefer-const#options

**Comment by johnthagen** [comment]
___
*[src/components/GoalTimeline/Redux/GoalActions.ts, line 190 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1523#-MsqB17XBMDWpkVrzUI5:-MsqB17XBMDWpkVrzUI6:b54vpse) ([raw file](https://github.com/sillsdev/thecombine/blob/234627a0fa1506cc834b1475a658f6471ea7182e/src/components/GoalTimeline/Redux/GoalActions.ts#L190)):*
> ```XML
>   const userEditId = getUserEditId();
>   if (userEditId) {
>     const step = goal.steps[goal.currentStep] ?? null;
> ```

Any reason to use `null` instead of `undefined` (as usually preferred by TypeScript).

**Comment by johnthagen** [comment]
___
*[src/types/goals.ts, line 17 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1523#-MsqBhBY60dmf8JjF_eQ:-MsqBhBY60dmf8JjF_eR:blbcvl9) ([raw file](https://github.com/sillsdev/thecombine/blob/234627a0fa1506cc834b1475a658f6471ea7182e/src/types/goals.ts#L17)):*
> ```XML
> 
> export type GoalData = CreateCharInvData | MergeDupData;
> export type GoalStep = CreateCharInvStepData | MergeStepData | null;
> ```

Use `undefined`?

**Comment by johnthagen** [comment]
___
*[src/types/goals.ts, line 80 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1523#-MsqBjcX-Pp51bCwEyAT:-MsqBjcX-Pp51bCwEyAU:blbcvl9) ([raw file](https://github.com/sillsdev/thecombine/blob/234627a0fa1506cc834b1475a658f6471ea7182e/src/types/goals.ts#L80)):*
> ```XML
>     type = GoalType.Default,
>     name = GoalName.Default,
>     steps: GoalStep[] = [null],
> ```

Use `undefined`?

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1523)* status: 0 of 93 files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[package.json, line 157 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1523#-Msq9n-KCVrtuz6EJv1d:-MsqNlkkD6RiKuN1xJrO:bytry7h) ([raw file](https://github.com/sillsdev/thecombine/blob/234627a0fa1506cc834b1475a658f6471ea7182e/package.json#L157)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Oh weird, maybe `"error"` is the only option? 

https://eslint.org/docs/rules/prefer-const#options
</blockquote></details>

`"warn"` works

**Review by johnthagen — APPROVED** [review]
> Reviewed 75 of 75 files at r1, 30 of 30 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1523)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by johnthagen — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1523)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
