### PR TITLE
Create service accounts for AWS & Kubernetes access

### PR DESCRIPTION
**Pull request by jmgrady**
Changes in this PR:
1. Create service accounts and roles to remove the need to mount a kubeconfig file as a secret for the following uses:
   - create AWS ECR login secret
   - run maintenance scripts, such as backup and restore tasks.

2. In order to be able to run the restore script interactively, the `combine_maint` image is running in a deployment.  This allows us to run any current and future maintenance scripts interactively and on-demand by using a `kubectl exec -it deployment/maintenance ...` command.

3. Added instructions in the `docs/deploy/README.md` for running the maintenance scripts on demand.

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1366)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1366)* status: 0 of 16 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[deploy/roles/k8s_accounts/tasks/main.yml, line 21 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1366#-Mj9rq0F3pQrLbifWw0B:-Mj9rq0F3pQrLbifWw0C:bbewg5f) ([raw file](https://github.com/sillsdev/thecombine/blob/0dce8f9cce861a8418f6c300d7ed05126ac8d31b/deploy/roles/k8s_accounts/tasks/main.yml#L21)):*
> ```
>   loop: "{{ k8s_account_templates}}"
>  ...
>   loop: "{{ k8s_account_templates}}"
> ```

Missing space before }}?
___
*[docs/deploy/README.md, line 210 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1366#-Mj9qOjaEZPJ-V85ynbr:-Mj9qOjaEZPJ-V85ynbs:b-tu5owt) ([raw file](https://github.com/sillsdev/thecombine/blob/0dce8f9cce861a8418f6c300d7ed05126ac8d31b/docs/deploy/README.md#L210)):*
> ```Markdown
> 2. You can see the script options for a script by running:
>    ```
>    kubectl [--kubeconfig=<path-to-kubernetes-file] -n thecombine exec -it deployment/maintenance -- <maintenance scripts> --help
> ```

Should this `-n thecombine` not be `[-n thecombine]` since 3. (below) applies equally to the general command (above) and its specific form in 2. (here)?
___
*[scripts/clean_aws_repo.py, line 69 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1366#-Mj9rPFZ928xaIDLf63s:-Mj9rPFZ928xaIDLf63t:b-ygm4kk) ([raw file](https://github.com/sillsdev/thecombine/blob/0dce8f9cce861a8418f6c300d7ed05126ac8d31b/scripts/clean_aws_repo.py#L69)):*
> ```Python
>     parser.add_argument("--profile", help="AWS user profile to use to connect to AWS ECR")
>     parser.add_argument("--untagged", action="store_true", help="Delete untagged images.")
>     # Although the "repo" positional argument returns a list if repositories, the argument
> ```

"list if repositories" -> "list of repositories"

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1366)* status: 0 of 16 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[deploy/roles/k8s_accounts/tasks/main.yml, line 21 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1366#-Mj9rq0F3pQrLbifWw0B:-Mj9zfOo027F6sYPElN6:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/0dce8f9cce861a8418f6c300d7ed05126ac8d31b/deploy/roles/k8s_accounts/tasks/main.yml#L21)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>   loop: "{{ k8s_account_templates}}"
>  ...
>   loop: "{{ k8s_account_templates}}"
> ```

Missing space before }}?
</blockquote></details>

Done.
___
*[docs/deploy/README.md, line 210 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1366#-Mj9qOjaEZPJ-V85ynbr:-MjA-AyE1FEHBfhlzCYi:b-1nehz4) ([raw file](https://github.com/sillsdev/thecombine/blob/0dce8f9cce861a8418f6c300d7ed05126ac8d31b/docs/deploy/README.md#L210)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Should this `-n thecombine` not be `[-n thecombine]` since 3. (below) applies equally to the general command (above) and its specific form in 2. (here)?
</blockquote></details>

Yes.  Done.
___
*[scripts/clean_aws_repo.py, line 69 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1366#-Mj9rPFZ928xaIDLf63s:-MjA-YCn8Kc_F6_0hShY:bnavjz6) ([raw file](https://github.com/sillsdev/thecombine/blob/0dce8f9cce861a8418f6c300d7ed05126ac8d31b/scripts/clean_aws_repo.py#L69)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

"list if repositories" -> "list of repositories"
</blockquote></details>

Removed the comment.  I learned about the `metavar` argument to `add_argument` that lets me specify the name to use in the auto-generated help text.  Now the variable is named `repo_list` but the help text shows:
```
usage: clean_aws_repo.py [-h] [--profile PROFILE] [--untagged] [--keep KEEP [KEEP ...]] [--remove RM_PATTERN [RM_PATTERN ...]] [--dry-run] [--verbose] repo [repo ...]
```
which is what I was trying to achieve earlier.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 2 of 16 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1366)* status: 3 of 16 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[deploy/playbook_kube_config.yml, line 52 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1366#-MjA12sk88rc5gB_Y6KF:-MjA12sk88rc5gB_Y6KG:b-a583qa) ([raw file](https://github.com/sillsdev/thecombine/blob/5ad74a51aca2cb5b334400375daeec56946f7c73/deploy/playbook_kube_config.yml#L52)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
>         - name: Setup Service Accounts
>           import_role:
>             name: k8s_accounts
>           tags:
>             - k8s_accounts
>         - name: Setup container registry credentials
>           import_role:
>             name: aws_login_job
>           tags:
>             - aws_login
> ```
</details>

Will it potentially cause any confusion to have the `import_role` `name` and the `tag` the same (as with `k8s_accounts`) or different (as with `aws_login[_job]`)?
___
*[deploy/roles/k8s_config/defaults/main.yml, line 60 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1366#-MjA1kho8UnOY6i-vndh:-MjA1kho8UnOY6i-vndi:bnwlued) ([raw file](https://github.com/sillsdev/thecombine/blob/5ad74a51aca2cb5b334400375daeec56946f7c73/deploy/roles/k8s_config/defaults/main.yml#L60)):*
> ```
> # Run every day at 10:15 UTC
> combine_backup_schedule: "15 03 * * *"
> ```
Does the comment need updating?

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1366)* status: 3 of 16 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[deploy/playbook_kube_config.yml, line 52 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1366#-MjA12sk88rc5gB_Y6KF:-MjA3BCXCsJN_KyxtD6J:b-77ds0e) ([raw file](https://github.com/sillsdev/thecombine/blob/5ad74a51aca2cb5b334400375daeec56946f7c73/deploy/playbook_kube_config.yml#L52)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>         - name: Setup Service Accounts
>           import_role:
>             name: k8s_accounts
>           tags:
>             - k8s_accounts
>         - name: Setup container registry credentials
>           import_role:
>             name: aws_login_job
>           tags:
>             - aws_login
> ```
Will it potentially cause any confusion to have the `import_role` `name` and the `tag` the same (as with `k8s_accounts`) or different (as with `aws_login[_job]`)?
</blockquote></details>

The tags allow us to run the playbook and only execute that step - useful for the debugging.  I think that aws_login is more descriptive since there may be other methods to perform the login to AWS ECR (I was looking at a couple of off the shelf solutions, for example).
___
*[deploy/roles/k8s_config/defaults/main.yml, line 60 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1366#-MjA1kho8UnOY6i-vndh:-MjA3e675oJv88Om8wxG:b-1nehz4) ([raw file](https://github.com/sillsdev/thecombine/blob/5ad74a51aca2cb5b334400375daeec56946f7c73/deploy/roles/k8s_config/defaults/main.yml#L60)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> # Run every day at 10:15 UTC
> combine_backup_schedule: "15 03 * * *"
> ```
Does the comment need updating?
</blockquote></details>

Yes.  Done.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 4 of 16 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1366)* status: 8 of 16 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[deploy/roles/k8s_config/templates/cronjob-daily-backup.yaml.j2, line 29 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1366#-MjAMiNJ0UAlwOIXesn6:-MjAMiNJ0UAlwOIXesn7:b-xh98dl) ([raw file](https://github.com/sillsdev/thecombine/blob/2f8722982dbc160efa724879a48002d2e0e5caf8/deploy/roles/k8s_config/templates/cronjob-daily-backup.yaml.j2#L29)):*
> ```
>               - exec
>               - deployment/maintenance
> ```
No `-it` required between these two?

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1366)* status: 8 of 16 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[deploy/roles/k8s_config/templates/cronjob-daily-backup.yaml.j2, line 29 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1366#-MjAMiNJ0UAlwOIXesn6:-MjAPiTA1_HAJCtoDyd5:b-3j5biy) ([raw file](https://github.com/sillsdev/thecombine/blob/2f8722982dbc160efa724879a48002d2e0e5caf8/deploy/roles/k8s_config/templates/cronjob-daily-backup.yaml.j2#L29)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>               - exec
>               - deployment/maintenance
> ```
No `-it` required between these two?
</blockquote></details>

That is correct. `-it` combines the `-i` and `-t` options.  `-i` means the program is being run interactively, that is `stdin` is passed to the container, and `-t` means that `stdin` is a `TTY`.  This is not the case for the daily backup cron job.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 6 of 16 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1366)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Pull request merged**
