### PR TITLE
Improve unexpected error handling in frontend

### LINKED ISSUE #1387: Evaluate usage of console.error
There are over a dozen instances where errors are logged to the console with `console.error()`. These are easy to miss and should probably be surfaced visually so that the user/developer knows there are errors happening rather than silently ignored.

https://github.com/sillsdev/TheCombine/search?q=console.error

Related to #1125

### PR DESCRIPTION
**Pull request by johnthagen**
Closes #1387 

- Update calls to `toast()` to explicit `toast.success()` and `toast.error()` to automatically provide a more clearer icon/color to user
  - To see the difference, see: https://fkhadra.github.io/react-toastify/introduction/
- Add missing Toast to failed microphone access and several other components
- Add SWAL alerts to errors in TypeScript files outside of the React JSX tree
- Consolidate repeated `ToastContainer` definitions into a shared component

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1484)

### CODE REVIEW

**Comment by johnthagen** [comment]
Example output when the user does not allow permission to the microphone:

On open:

Screenshot 2021-12-03 144049

When pressing the record button:


Screenshot 2021-12-03 144130

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1484)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[src/resources/translations.json, line 391 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1484#-Mq0ntDd-BG1lw68a9oi:-Mq0ntDd-BG1lw68a9oj:b-ynm2s8) ([raw file](https://github.com/sillsdev/thecombine/blob/427920b5bc168f6dc4ae5c55a195382b55219977/src/resources/translations.json#L391)):*
<details><summary><i alt="summary">Quoted 13 lines of code…</i></summary>

> ```
>         "Failed to add analysis language.",
>         "Failed to add analysis language.",
>         "Failed to add analysis language."
>       ],
>       "makeDefaultAnalysisLanguageFailed": [
>         "Failed to make default analysis language",
>         "Failed to make default analysis language",
>         "Failed to make default analysis language"
>       ],
>       "deleteAnalysisLanguageFailed": [
>         "Failed to delete analysis language.",
>         "Failed to delete analysis language.",
>         "Failed to delete analysis language."
> ```
</details>

Make period usage consistent.

**Comment by johnthagen** [comment]
___
*[src/resources/translations.json, line 391 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1484#-Mq0ntDd-BG1lw68a9oi:-Mq0onys4ijgg76MObgg:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/427920b5bc168f6dc4ae5c55a195382b55219977/src/resources/translations.json#L391)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>         "Failed to add analysis language.",
>         "Failed to add analysis language.",
>         "Failed to add analysis language."
>       ],
>       "makeDefaultAnalysisLanguageFailed": [
>         "Failed to make default analysis language",
>         "Failed to make default analysis language",
>         "Failed to make default analysis language"
>       ],
>       "deleteAnalysisLanguageFailed": [
>         "Failed to delete analysis language.",
>         "Failed to delete analysis language.",
>         "Failed to delete analysis language."
> ```
Make period usage consistent.
</blockquote></details>

Done.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 11 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1484)* status: 10 of 15 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @johnthagen)

___
*[src/backend/index.ts, line 154 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1484#-Mq0rnvH9z-xDwBzQX4Y:-Mq0rnvH9z-xDwBzQX4Z:b-bthv9w) ([raw file](https://github.com/sillsdev/thecombine/blob/427920b5bc168f6dc4ae5c55a195382b55219977/src/backend/index.ts#L154)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>   } catch (err) {
>     // Avatar fetching can fail if hasAvatar=True but the avatar path is broken.
>     console.error(err);
>     await errorToast.fire({
>       title: "Missing Avatar",
>       text: "User indicates it has avatar, but unable to fetch.",
>     });
> ```
</details>

Preferably only do this if error encountered for avatar of the current user.
___
*[src/resources/translations.json, line 381 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1484#-Mq0rOx-8kMfArzLgkgQ:-Mq0rOx0E4V-R2pa39Af:b-99ra4t) ([raw file](https://github.com/sillsdev/thecombine/blob/666a75f6b6763c6478a875b8e57582989d779b79/src/resources/translations.json#L381)):*
> ```
>         "Failed to add analysis language.",
>         "Failed to add analysis language.",
>         "Failed to add analysis language."
> ```
And delete .s here.

**Comment by johnthagen** [comment]
___
*[src/resources/translations.json, line 381 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1484#-Mq0rOx-8kMfArzLgkgQ:-Mq12yVZCgaJSHUIR2Ey:b-hfoe8k) ([raw file](https://github.com/sillsdev/thecombine/blob/666a75f6b6763c6478a875b8e57582989d779b79/src/resources/translations.json#L381)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>         "Failed to add analysis language.",
>         "Failed to add analysis language.",
>         "Failed to add analysis language."
> ```
And delete .s here.
</blockquote></details>

Done.

This was to match other translations around this, but I went ahead and removed those periods as well.

**Comment by johnthagen** [comment]
___
*[src/backend/index.ts, line 154 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1484#-Mq0rnvH9z-xDwBzQX4Y:-Mq14uEa8huakWiZS2hu:b8p9dsc) ([raw file](https://github.com/sillsdev/thecombine/blob/427920b5bc168f6dc4ae5c55a195382b55219977/src/backend/index.ts#L154)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>   } catch (err) {
>     // Avatar fetching can fail if hasAvatar=True but the avatar path is broken.
>     console.error(err);
>     await errorToast.fire({
>       title: "Missing Avatar",
>       text: "User indicates it has avatar, but unable to fetch.",
>     });
> ```
Preferably only do this if error encountered for avatar of the current user.
</blockquote></details>

Removed toast.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 3 of 3 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1484)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Pull request merged**
