### PR TITLE
NewEntry note

### PR DESCRIPTION
**Pull request by imnasnainaec**
* Allow note added to NewEntry before submission
  - Except when user selects new sense of existing word
* Add delete button on NewEntry
* Move note left, between gloss and recording
* Consolidate DataEntryTable entry components in EntryCellComponents folder

Follow-up to #784 

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/802)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 13 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/802)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[src/resources/translations.json, line 29 at r1](https://reviewable.io/reviews/sillsdev/thecombine/802#-MLiDCBb11M0NvZxb9FX:-MLiDCBb11M0NvZxb9FY:b-5zo14p) ([raw file](https://github.com/sillsdev/thecombine/blob/0c26592f14e80ad3b8ac05809f883ab0027db09e/src/resources/translations.json#L29)):*
> ```
> "Reset this entry",
> ```
Not sure about this. From a users perspective on the front end is it any different from deleting? As developers we know it is different, but we don't need to expose our users to the confusing internals.
___
*[src/components/DataEntry/DataEntryTable/EntryCellComponents/DeleteEntry.tsx, line 11 at r1](https://reviewable.io/reviews/sillsdev/thecombine/802#-MLhqzK02u6DdvaaX1qj:-MLhqzK1-D7tq4F8E_Qo:b-5f8eh2) ([raw file](https://github.com/sillsdev/thecombine/blob/0c26592f14e80ad3b8ac05809f883ab0027db09e/src/components/DataEntry/DataEntryTable/EntryCellComponents/DeleteEntry.tsx#L11)):*
> ```XML
>   removeEntry: () => void;
>   tooltipId: string;
>   confirmId?: string;
> ```

This would be a good place for a comment explaining the expected usage of confirmId.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/802)* status: 9 of 13 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

___
*[src/resources/translations.json, line 29 at r1](https://reviewable.io/reviews/sillsdev/thecombine/802#-MLiDCBb11M0NvZxb9FX:-MLpS_X_5GaxKaV-KFUW:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/0c26592f14e80ad3b8ac05809f883ab0027db09e/src/resources/translations.json#L29)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> "Reset this entry",
> ```
Not sure about this. From a users perspective on the front end is it any different from deleting? As developers we know it is different, but we don't need to expose our users to the confusing internals.
</blockquote></details>

Done
___
*[src/components/DataEntry/DataEntryTable/EntryCellComponents/DeleteEntry.tsx, line 11 at r1](https://reviewable.io/reviews/sillsdev/thecombine/802#-MLhqzK02u6DdvaaX1qj:-MLpSYZi94T0PJPI2W-X:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/0c26592f14e80ad3b8ac05809f883ab0027db09e/src/components/DataEntry/DataEntryTable/EntryCellComponents/DeleteEntry.tsx#L11)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

This would be a good place for a comment explaining the expected usage of confirmId.
</blockquote></details>

Done

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 1 of 14 files at r1, 4 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/802)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jasonleenaylor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/802)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
