### PR TITLE
Deploy user guide to GitHub Pages

### PR DESCRIPTION
**Pull request by johnthagen**
Create a GitHub Actions job to automatically build and deploy the user guide to GitHub Pages using MkDocs.

- See: https://squidfunk.github.io/mkdocs-material/publishing-your-site/#github-pages

This will allow us to have a permanent link to the user guide that developers and interested parties can read that is independent of any particular deployment.

**View the results at: https://sillsdev.github.io/TheCombine/**

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1236)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1236)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

___
*[.github/workflows/pages.yml, line 1 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1236#-Mdc2C_JDokee1VsY0z9:-Mdc2C_JDokee1VsY0zA:b-h8j375) ([raw file](https://github.com/sillsdev/thecombine/blob/398ad99d7b203ffbce8ca6f99931c0878f145998/.github/workflows/pages.yml#L1)):*
> ```YAML
> name: pages
> ```

To help future developers let's add a descriptive comment at the top of this action

**Comment by johnthagen** [comment]
___
*[.github/workflows/pages.yml, line 1 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1236#-Mdc2C_JDokee1VsY0z9:-Mdc3Kez0EQNu1QrAabY:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/398ad99d7b203ffbce8ca6f99931c0878f145998/.github/workflows/pages.yml#L1)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

To help future developers let's add a descriptive comment at the top of this action 
</blockquote></details>

Done.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1236)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

**Review by WeJamUS — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1236)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Pull request merged**
