### PR TITLE
Delete old deploy scripts

### LINKED ISSUE #953: Remove deploy/ subproject after migration to Docker
Once we fully transition to a Docker-based deployment, we should be able to:

- Remove `deploy`  folder and the previous Apache-based install
- Rename `docker_deploy` to `deploy`

### PR DESCRIPTION
**Pull request by jmgrady**
Remove the old deployment scripts in `./deploy` and move the docker installation that is in `./docker_depoy` to the `./deploy` directory.  Also removes the old documentation in the `./docs` directory.

Closes #953

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/978)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 161 of 162 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/978)* status: 161 of 162 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[.gitmodules, line 3 at r2](https://reviewable.io/reviews/sillsdev/thecombine/978#-MSiI8_j6iQIp4iV28Es:-MSiI8_kBX8Rz0ZmuFOw:by13bx1) ([raw file](https://github.com/sillsdev/thecombine/blob/b4e988b54db52154b6b0701639e228898ece93f0/.gitmodules#L3)):*
> ```gitconfig
> [submodule "deploy/roles_common"]
> 	path = deploy/roles_common
> 	url = ../ops-ansible-common-roles.git
> ```

Shouldn't we delete this file instead of having it empty?

**Review by imnasnainaec — COMMENTED** [review]
We can also delete `public/.htaccess`, no?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/978#-:-MSiMtTD0ZO0384LJ-xv:bahgkmh)* status: 161 of 162 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

**Review by jmgrady — COMMENTED** [review]
> We can also delete public/.htaccess, no?
Done.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/978#-:-MSihEWW3PsI_FL39BOh:bwxecm5)* status: 161 of 163 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[.gitmodules, line 3 at r2](https://reviewable.io/reviews/sillsdev/thecombine/978#-MSiI8_j6iQIp4iV28Es:-MSihY8mA8BG9a4BC_FK:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/b4e988b54db52154b6b0701639e228898ece93f0/.gitmodules#L3)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Shouldn't we delete this file instead of having it empty?
</blockquote></details>

Done

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/978)* status: 163 of 165 files reviewed, all discussions resolved (waiting on @jmgrady)

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/978)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/978)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
