### PR TITLE
Implement Senses column in ReviewEntriesTable.

### LINKED ISSUE #1188: [ReviewEntries] Redesign senses layout
Currently, when editing a row/entry, the button to add a new sense is in the Glosses column, and the buttons for deleting senses are in an unlabeled column between the Glosses and Domains columns.

New design:
- [x] Move unlabeled column to left of Glosses
- [x] Label as Senses column
- [x] Move button for adding sense from bottom of Glosses to bottom of Senses

### LINKED ISSUE #1192: Dragging columns on ReviewEntries more than once causes text to be typed in the incorrect field
https://user-images.githubusercontent.com/42851286/122475684-04a50d80-cf93-11eb-95ae-5894bd2ea2a0.mp4

### LINKED ISSUE #1195: [ReviewEntries] Column filtering crashes with any reg-ex special character
Filtering columns with any RegEx special character (e.g., * or \\) causes a crash.
Screen Shot 2021-06-18 at 09 10 58

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #1188
Fixes #1192 (by disabling dragging)
Fixes #1195 

Before:
Screen Shot 2021-06-17 at 14 20 51
Screen Shot 2021-06-17 at 14 21 06

After:
Screen Shot 2021-06-17 at 14 20 02
Screen Shot 2021-06-17 at 14 19 48

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1191)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
@imnasnainaec This looks like a good UX improvement. I think the ':' after the number is unnecessary and maybe unhelpful. it looks ok on single sense entries but isn't really helpful on multi-sense ones.

**Comment by JacobHaimes** [comment]
https://user-images.githubusercontent.com/42851286/122464946-6e1e1f80-cf85-11eb-8d06-b4236090b3c0.mp4

I tried running it and it seems to be working fine for the most part, however, I found a weird bug when dragging the column around. When you drag the column the first time there doesn't seem to be any issue but once it's dragged again, anything you type into the senses column ends up in the glosses. Also if there was anything typed into the column on the third drag, it becomes permanently stuck.

**Comment by WeJamUS** [comment]
Adding onto Jacob's find, I replicated the bug in the master branch when dragging around other columns. So it does seem to be a pre-existing issue.

**Review by JacobHaimes — APPROVED** [review]
Other than the pre-existing bug, the changes here are good and worked well when I ran them.

**Review by WeJamUS — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1191)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JacobHaimes and @johnthagen)

**Comment by johnthagen** [comment]
___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx, line 99 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1191#-McTuJCo1rwlGQ5jbaQ4:-McTuJCp5r2X10Ua4vnS:bf0r31u) ([raw file](https://github.com/sillsdev/thecombine/blob/2df50ea2d60e59663ad0352379beb7032632094f/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx#L99)):*
> ```XML
>       vernacularField(props, true),
>   },
>   // Sense column
> ```

Maybe unrelated to this PR, but if I press the Edit button it seems to fetch data, which was surprising to me:

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/v1/projects/60cc84a8d400641994948247/words/60cc854dd40064199494914e/audio/download/5f403352b309322d06647783.webm
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'BackendFramework.Controllers.AudioController.DownloadAudioFile (BackendFramework)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "DownloadAudioFile", controller = "Audio"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult DownloadAudioFile(System.String, System.String, System.String) on controller BackendFramework.Controllers.AudioController (BackendFramework).
info: Microsoft.AspNetCore.Mvc.Infrastructure.FileStreamResultExecutor[2]
      Executing Microsoft.AspNetCore.Mvc.FileStreamResult, sending file with download name '' ...
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action BackendFramework.Controllers.AudioController.DownloadAudioFile (BackendFramework) in 0.7972ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'BackendFramework.Controllers.AudioController.DownloadAudioFile (BackendFramework)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 1.0069ms 200 application/octet-stream
```

And then if I hit the X to cancel, it seems to download the audio again?

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/v1/projects/60cc84a8d400641994948247/words/60cc854dd40064199494914e/audio/download/5f403352b309322d06647783.webm
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'BackendFramework.Controllers.AudioController.DownloadAudioFile (BackendFramework)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "DownloadAudioFile", controller = "Audio"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult DownloadAudioFile(System.String, System.String, System.String) on controller BackendFramework.Controllers.AudioController (BackendFramework).
info: Microsoft.AspNetCore.Mvc.Infrastructure.FileStreamResultExecutor[2]
      Executing Microsoft.AspNetCore.Mvc.FileStreamResult, sending file with download name '' ...
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action BackendFramework.Controllers.AudioController.DownloadAudioFile (BackendFramework) in 0.6806ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'BackendFramework.Controllers.AudioController.DownloadAudioFile (BackendFramework)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 0.836ms 200 application/octet-stream
```

If I haven't taken any action to actually change anything, I would expect it to not need to query the backend?

**Comment by johnthagen** [comment]
___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx, line 23 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1191#-McTv9GXAzURJW2mxr3S:-McTv9GXAzURJW2mxr3T:b-f9lal0) ([raw file](https://github.com/sillsdev/thecombine/blob/2df50ea2d60e59663ad0352379beb7032632094f/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx#L23)):*
> ```XML
>   DOMAIN,
>   PRONUNCIATION,
>   //NOTETEXT,
> ```

Very minor, but if we are capitalizing these, it would be easier to read this in the future as `NOTE_TEXT`.

**Comment by johnthagen** [comment]
___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx, line 119 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1191#-McTwrlr-hJEaMoTwHkx:-McTwrlr-hJEaMoTwHky:b-cvc2ov) ([raw file](https://github.com/sillsdev/thecombine/blob/2df50ea2d60e59663ad0352379beb7032632094f/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx#L119)):*
> ```XML
>       return b.senses.length - a.senses.length;
>     },
>     editComponent: (props: FieldParameterStandard) => {
> ```

The trash can icons are not horizontally aligned with the glosses, which could make it error prone to delete, especially when there are many glosses. Could we figure out a way to align them?

**Comment by johnthagen** [comment]
___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx, line 111 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1191#-McTyPLuEhgkmv7u7PhM:-McTyPLuEhgkmv7u7PhN:b4pgp4i) ([raw file](https://github.com/sillsdev/thecombine/blob/2df50ea2d60e59663ad0352379beb7032632094f/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx#L111)):*
> ```XML
>       rowData: ReviewEntriesWord
>     ): boolean => {
>       return parseInt(filter) === rowData.senses.length;
> ```

It looks as though the Senses column number is using the incorrect font (it has serifs). Could we double check that?

Look at the `1` and `4` in the following screenshot.

**Review by johnthagen — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1191)* status: all files reviewed, 4 unresolved discussions (waiting on @imnasnainaec)

**Comment by johnthagen** [comment]
> I tried running it and it seems to be working fine for the most part, however, I found a weird bug when dragging the column around. When you drag the column the first time there doesn't seem to be any issue but once it's dragged again, anything you type into the senses column ends up in the glosses. Also if there was anything typed into the column on the third drag, it becomes permanently stuck.

Reported as #1192

**Review by imnasnainaec — COMMENTED** [review]
Fixed #1192 by disabling dragging.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1191#-:-McUCYVE0fkFQffE9uIr:b53enbk)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @johnthagen and @WeJamUS)

___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx, line 23 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1191#-McTv9GXAzURJW2mxr3S:-McUCFIq2WL64wB849ly:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/2df50ea2d60e59663ad0352379beb7032632094f/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx#L23)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Very minor, but if we are capitalizing these, it would be easier to read this in the future as `NOTE_TEXT`.
</blockquote></details>

Done.
___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx, line 99 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1191#-McTuJCo1rwlGQ5jbaQ4:-McUCGoL6aNymCSY94iv:b-tg9gzu) ([raw file](https://github.com/sillsdev/thecombine/blob/2df50ea2d60e59663ad0352379beb7032632094f/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx#L99)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Maybe unrelated to this PR, but if I press the Edit button it seems to fetch data, which was surprising to me:

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/v1/projects/60cc84a8d400641994948247/words/60cc854dd40064199494914e/audio/download/5f403352b309322d06647783.webm
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'BackendFramework.Controllers.AudioController.DownloadAudioFile (BackendFramework)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "DownloadAudioFile", controller = "Audio"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult DownloadAudioFile(System.String, System.String, System.String) on controller BackendFramework.Controllers.AudioController (BackendFramework).
info: Microsoft.AspNetCore.Mvc.Infrastructure.FileStreamResultExecutor[2]
      Executing Microsoft.AspNetCore.Mvc.FileStreamResult, sending file with download name '' ...
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action BackendFramework.Controllers.AudioController.DownloadAudioFile (BackendFramework) in 0.7972ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'BackendFramework.Controllers.AudioController.DownloadAudioFile (BackendFramework)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 1.0069ms 200 application/octet-stream
```

And then if I hit the X to cancel, it seems to download the audio again?

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/v1/projects/60cc84a8d400641994948247/words/60cc854dd40064199494914e/audio/download/5f403352b309322d06647783.webm
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'BackendFramework.Controllers.AudioController.DownloadAudioFile (BackendFramework)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "DownloadAudioFile", controller = "Audio"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult DownloadAudioFile(System.String, System.String, System.String) on controller BackendFramework.Controllers.AudioController (BackendFramework).
info: Microsoft.AspNetCore.Mvc.Infrastructure.FileStreamResultExecutor[2]
      Executing Microsoft.AspNetCore.Mvc.FileStreamResult, sending file with download name '' ...
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action BackendFramework.Controllers.AudioController.DownloadAudioFile (BackendFramework) in 0.6806ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'BackendFramework.Controllers.AudioController.DownloadAudioFile (BackendFramework)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 0.836ms 200 application/octet-stream
```

If I haven't taken any action to actually change anything, I would expect it to not need to query the backend?
</blockquote></details>

Let's make a new issue for that.
___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx, line 111 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1191#-McTyPLuEhgkmv7u7PhM:-McUCMKV3tvzqgF0x2ix:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/2df50ea2d60e59663ad0352379beb7032632094f/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx#L111)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

It looks as though the Senses column number is using the incorrect font (it has serifs). Could we double check that?

Look at the `1` and `4` in the following screenshot.



</blockquote></details>

Done.
___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx, line 119 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1191#-McTwrlr-hJEaMoTwHkx:-McUCNEXDm5p4Z_XyHJi:b9vgchd) ([raw file](https://github.com/sillsdev/thecombine/blob/2df50ea2d60e59663ad0352379beb7032632094f/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx#L119)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

The trash can icons are not horizontally aligned with the glosses, which could make it error prone to delete, especially when there are many glosses. Could we figure out a way to align them?



</blockquote></details>

I don't think it's common to have more than 2 or 3 senses, but let's make an issue for this.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1191)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @johnthagen and @WeJamUS)

___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx, line 119 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1191#-McTwrlr-hJEaMoTwHkx:-McUDhmr0DT7n5AURfdX:b-8sgikn) ([raw file](https://github.com/sillsdev/thecombine/blob/2df50ea2d60e59663ad0352379beb7032632094f/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx#L119)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I don't think it's common to have more than 2 or 3 senses, but let's make an issue for this.
</blockquote></details>

#1194

**Comment by johnthagen** [comment]
___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx, line 99 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1191#-McTuJCo1rwlGQ5jbaQ4:-McUIeY_4LlPl854X2j-:bz2ttlv) ([raw file](https://github.com/sillsdev/thecombine/blob/2df50ea2d60e59663ad0352379beb7032632094f/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx#L99)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Let's make a new issue for that.
</blockquote></details>

https://github.com/sillsdev/TheCombine/issues/1196

**Review by johnthagen — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1191)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
