### PR TITLE
Backend refactor/cleanup

### PR DESCRIPTION
**Pull request by johnthagen**
Fix potential security issue:

- Sanitize `fileName` argument to `AudioController.DownloadAudioFile`
  - Add unit tests for `SanitizeId` and `SanitizeFileName`

These changes should not change any functionality:

- Remove redundant `()` on object initialization
- Fix `PermissionServiceMock.HasProjectPermission` type signature to properly communicate that in the mock, `request` can be `null` to support unit testing
- Use `async` / `await` fully in `async` tests
- Fix spelling typos
- Fix `private` attribute naming
- Make `RoundTripObj` immutable (remove unused `set`ter properties)
- Reduce redundant `else if` nesting around `return` statements (reduces cognitive load)
   - Replace some `else` blocks with `switch` expressions to simplify
- Make `ProjectPermissions` immutable (remove unused `set`ter properties)
- Simplify expressions using `??=` operator
- Make `PasswordResetData` immutable
- Make `EmailInviteData` immutable
- Remove `null` checks that cannot happen due to new nullable type system safety

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/892)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 4 of 6 files at r1, 5 of 14 files at r2, 6 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/892)* status: 15 of 20 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @johnthagen)

___
*[Backend/Controllers/UserRoleController.cs, line 178 at r6](https://reviewable.io/reviews/sillsdev/thecombine/892#-MPt_DP27vmyqEFlTVKo:-MPt_DP27vmyqEFlTVKp:b-i58ep2) ([raw file](https://github.com/sillsdev/thecombine/blob/0414db05e40574b7cf1a864e8158e77e934e9fc1/Backend/Controllers/UserRoleController.cs#L178)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>             if (result == ResultOfUpdate.NotFound)
>             {
>                 return new NotFoundObjectResult(userRoleId);
>             }
>             if (result == ResultOfUpdate.Updated)
>             {
>                 return new OkObjectResult(userRoleId);
>             }
>             return new StatusCodeResult(304);
> ```
</details>

Why not use a `return result switch` here?
___
*[Backend/Helper/Sanitization.cs, line 24 at r6](https://reviewable.io/reviews/sillsdev/thecombine/892#-MPtXsiU0QT-J0VKzx8y:-MPtXsiU0QT-J0VKzx8z:b-yj4j18) ([raw file](https://github.com/sillsdev/thecombine/blob/0414db05e40574b7cf1a864e8158e77e934e9fc1/Backend/Helper/Sanitization.cs#L24)):*
> ```Smalltalk
>         public static bool SanitizeFileName(string fileName)
>         {
>             return fileName.All(c => char.IsLetterOrDigit(c) | c == '-' | c == '.' | c == '_');
> ```

What about comma, parentheses, and space? `| c==',' | c=='(' | c==')' | c==' '`

**Comment by johnthagen** [comment]
___
*[Backend/Controllers/UserRoleController.cs, line 178 at r6](https://reviewable.io/reviews/sillsdev/thecombine/892#-MPt_DP27vmyqEFlTVKo:-MPyIZW2EZ1a-zjeOYyq:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/0414db05e40574b7cf1a864e8158e77e934e9fc1/Backend/Controllers/UserRoleController.cs#L178)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>             if (result == ResultOfUpdate.NotFound)
>             {
>                 return new NotFoundObjectResult(userRoleId);
>             }
>             if (result == ResultOfUpdate.Updated)
>             {
>                 return new OkObjectResult(userRoleId);
>             }
>             return new StatusCodeResult(304);
> ```
Why not use a `return result switch` here?
</blockquote></details>

Done

**Comment by johnthagen** [comment]
___
*[Backend/Helper/Sanitization.cs, line 24 at r6](https://reviewable.io/reviews/sillsdev/thecombine/892#-MPtXsiU0QT-J0VKzx8y:-MPyLzOZ8rt3JSWEDhkG:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/0414db05e40574b7cf1a864e8158e77e934e9fc1/Backend/Helper/Sanitization.cs#L24)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

What about comma, parentheses, and space? `| c==',' | c=='(' | c==')' | c==' '`
</blockquote></details>

Done.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 1 of 7 files at r6, 2 of 3 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/892)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
