### PR TITLE
Port Login to use redux-toolkit

### PR DESCRIPTION
**Pull request by imnasnainaec**
Part of #1953

Uses https://jestjs.io/docs/timer-mocks

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2748)

### CODE REVIEW

**Review by jmgrady — CHANGES_REQUESTED** [review]
> Reviewed 10 of 12 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2748)* status: all files reviewed, 3 unresolved discussions (waiting on @imnasnainaec)

___
*[`src/components/Login/LoginPage/index.ts` line 19 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2748#-Ni5qTiJ0TtngaqcFySz:-Ni5qTiJ0TtngaqcFyT-:bcq7ogs) ([raw file](https://github.com/sillsdev/TheCombine/blob/e072c2c2faf86fd3e43d07a3b115c090bc0c8e59/src/components/Login/LoginPage/index.ts#L19)):*
> ```XML
>   return {
>     loginAttempt: state.loginState.loginStatus === LoginStatus.Attempt,
>     loginFailure: state.loginState.loginStatus === LoginStatus.Failure,
> ```

Since these Booleans are mutually exclusive, why not just provide the loginStatus as a property?  Is there no case where one needs to distinguish between `Default` and `Success` when both of these are `false`?



_Code quote:_
```XML
    loginAttempt: state.loginState.loginStatus === LoginStatus.Attempt,
    loginFailure: state.loginState.loginStatus === LoginStatus.Failure,
```
___
*[`src/components/Login/LoginPage/index.ts` line 26 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2748#-Ni5qBQc0cizxxiAY6lR:-Ni5qBQc0cizxxiAY6lS:b-p2jyve) ([raw file](https://github.com/sillsdev/TheCombine/blob/e072c2c2faf86fd3e43d07a3b115c090bc0c8e59/src/components/Login/LoginPage/index.ts#L26)):*
> ```XML
>   return {
>     login: (username: string, password: string) => {
>       dispatch(asyncLogIn(username, password));
> ```

`Login` is more consistent with most if not all the other uses in this component.  It's also more consistent with the change of `SignUp` to `Signup`.



_Code quote:_
```XML
LogIn
```
___
*[`src/components/Login/Redux/LoginReducer.ts` line 22 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2748#-Ni9XBCKEaLzv-rXjeGg:-Ni9XBCKEaLzv-rXjeGh:bu2dz57) ([raw file](https://github.com/sillsdev/TheCombine/blob/e072c2c2faf86fd3e43d07a3b115c090bc0c8e59/src/components/Login/Redux/LoginReducer.ts#L22)):*
> ```XML
>       state.error = action.payload;
>       state.loginStatus = LoginStatus.Failure;
>     },
> ```

Consider clearing the `username` on failure.  Leaving old data lying around can cause problems but it can also be useful to have the "last login attempt" available - especially when debugging.  I do not see anything in the current implementation where it would be a problem to not clear the `username` so it is fine to leave things as they are if you prefer.

The same applies for `setSignupFailureAction`.



_Code quote:_
```XML
      state.error = action.payload;
      state.loginStatus = LoginStatus.Failure;
    },
```
___
*[`src/components/Login/Redux/LoginReduxTypes.ts` line 6 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2748#-Ni9_QEe0KLwRuJodXwq:-Ni9_QEe0KLwRuJodXwr:b-t3pgjn) ([raw file](https://github.com/sillsdev/TheCombine/blob/e072c2c2faf86fd3e43d07a3b115c090bc0c8e59/src/components/Login/Redux/LoginReduxTypes.ts#L6)):*
> ```XML
>   Failure = "Failure",
>   Success = "Success",
> }
> ```

The status names are really actions.  As the code in `src/components/Login/SignUpPage/index.ts` suggests, better status names would be
```
export enum LoginStatus {
  Complete = "Complete",  // normally I would prefer LoggedIn but this enum is also used for SignupState
  Default = "Default",    // similarly, I would prefer LoggedOut
  Failed = "Failed",
  InProgress = "InProgress",
}

```

I don't have strong objections but am blocking so that we can discuss.



_Code quote:_
```XML
export enum LoginStatus {
  Attempt = "Attempt",
  Default = "Default",
  Failure = "Failure",
  Success = "Success",
}
```
___
*[`src/components/Login/Redux/LoginReduxTypes.ts` line 12 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2748#-Ni9YI7jAgXlLFjqtN0f:-Ni9YI7jAgXlLFjqtN0g:boroqnf) ([raw file](https://github.com/sillsdev/TheCombine/blob/e072c2c2faf86fd3e43d07a3b115c090bc0c8e59/src/components/Login/Redux/LoginReduxTypes.ts#L12)):*
> ```XML
>   loginStatus: LoginStatus;
>   signupStatus: LoginStatus;
>   username: string;
> ```

Along the lines of my comment on `src/components/Login/Redux/LoginReducer.ts`, if the `username` is not cleared on failure, it could be helpful to add a comment here that states the value is only valid in the `Attempt`, and `Success` states.



_Code quote:_
```XML
  username: string;
```
___
*[`src/components/Login/Redux/tests/LoginActions.test.tsx` line 55 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2748#-Ni9ZIs2BwqEvXBut3YO:-Ni9ZIs2BwqEvXBut3YP:b-v6o26l) ([raw file](https://github.com/sillsdev/TheCombine/blob/e072c2c2faf86fd3e43d07a3b115c090bc0c8e59/src/components/Login/Redux/tests/LoginActions.test.tsx#L55)):*
> ```XML
>       expect(loginState.loginStatus).toEqual(LoginStatus.Failure);
>       expect(loginState.signupStatus).toEqual(LoginStatus.Default);
>       expect(loginState.username).toEqual(mockUsername);
> ```

Reminder: This would need to change if `username` is cleared on failure.



_Code quote:_
```XML
      expect(loginState.username).toEqual(mockUsername);
```
___
*[`src/components/Login/Redux/tests/LoginActions.test.tsx` line 81 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2748#-Ni9ZbUS0qUxfAw1jXBa:-Ni9ZbUS0qUxfAw1jXBb:b-v6o26l) ([raw file](https://github.com/sillsdev/TheCombine/blob/e072c2c2faf86fd3e43d07a3b115c090bc0c8e59/src/components/Login/Redux/tests/LoginActions.test.tsx#L81)):*
> ```XML
>       expect(loginState.loginStatus).toEqual(LoginStatus.Default);
>       expect(loginState.signupStatus).toEqual(LoginStatus.Failure);
>       expect(loginState.username).toEqual(mockUsername);
> ```

Reminder: This would need to change if `username` is cleared on failure.



_Code quote:_
```XML
     expect(loginState.username).toEqual(mockUsername);
```

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2748)* status: 10 of 16 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

___
*[`src/components/Login/LoginPage/index.ts` line 26 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2748#-Ni5qBQc0cizxxiAY6lR:-NiAMYYv-vWHbgSoXKUK:b1dm72n) ([raw file](https://github.com/sillsdev/TheCombine/blob/e072c2c2faf86fd3e43d07a3b115c090bc0c8e59/src/components/Login/LoginPage/index.ts#L26)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

`Login` is more consistent with most if not all the other uses in this component.  It's also more consistent with the change of `SignUp` to `Signup`.
</blockquote></details>

"login"/"signup" with a lowercase "i"/"u" is a noun or adjective. I was going with `asyncLogIn`/`asyncSignUp` with capital "I"/"U" thinking of them as the verb phrases "log in" and "sign up". Though I guess I'm not consistent with that thinking everywhere.

**Review by jmgrady — APPROVED** [review]
> Reviewed 6 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2748)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2748)* status: 11 of 16 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`src/components/Login/Redux/LoginReduxTypes.ts` line 6 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2748#-Ni9_QEe0KLwRuJodXwq:-NiAXKlIBA0iMd492wF-:b-1mo2wb) ([raw file](https://github.com/sillsdev/TheCombine/blob/e072c2c2faf86fd3e43d07a3b115c090bc0c8e59/src/components/Login/Redux/LoginReduxTypes.ts#L6)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

The status names are really actions.  As the code in `src/components/Login/SignUpPage/index.ts` suggests, better status names would be
```
export enum LoginStatus {
  Complete = "Complete",  // normally I would prefer LoggedIn but this enum is also used for SignupState
  Default = "Default",    // similarly, I would prefer LoggedOut
  Failed = "Failed",
  InProgress = "InProgress",
}

```

I don't have strong objections but am blocking so that we can discuss.
</blockquote></details>

Partially done.

**Review by jmgrady — APPROVED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2748)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
