### PR TITLE
Have successful register auto-login.

### LINKED ISSUE #1186: Shouldn't have to log in after registering new user.
Upon successful registration, rather than redirect to the login page, should automatically log in.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Fixes #1186

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1187)

### CODE REVIEW

**Review by WeJamUS — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1187#-:-McK_IayB7tL45Yv1tTS:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @JacobHaimes)

___
*[src/components/Login/Redux/LoginActions.tsx, line 79 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1187#-McKZA5i5RQiajaUAyfz:-McKZA5i5RQiajaUAyg-:b8de6rd) ([raw file](https://github.com/sillsdev/thecombine/blob/4d6a66342d673598fb4230fd502333c7d01a331c/src/components/Login/Redux/LoginActions.tsx#L79)):*
> ```XML
>         setTimeout(() => {
>           dispatch(reset());
>           history.push(Path.Login);
> ```

Why might we no longer want to push the login onto the history stack when we are automatically logging the user in after they register?

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1187)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @JacobHaimes)

___
*[src/components/Login/Redux/LoginActions.tsx, line 79 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1187#-McKZA5i5RQiajaUAyfz:-McKneCR7fPYRiTqJJat:b2oxit) ([raw file](https://github.com/sillsdev/thecombine/blob/4d6a66342d673598fb4230fd502333c7d01a331c/src/components/Login/Redux/LoginActions.tsx#L79)):*
<details><summary><i>Previously, WeJamUS (James Wu) wrote…</i></summary><blockquote>

Why might we no longer want to push the login onto the history stack when we are automatically logging the user in after they register?
</blockquote></details>

Pushing something into the browserHistory's history stack is how we navigate to a new page, and we no longer want to navigate back to login upon successful registration.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1187)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @JacobHaimes)

___
*[src/components/Login/Redux/LoginActions.tsx, line 79 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1187#-McKZA5i5RQiajaUAyfz:-McKoCLpEyKHRBP6dfJT:bajkuor) ([raw file](https://github.com/sillsdev/thecombine/blob/4d6a66342d673598fb4230fd502333c7d01a331c/src/components/Login/Redux/LoginActions.tsx#L79)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Pushing something into the browserHistory's history stack is how we navigate to a new page, and we no longer want to navigate back to login upon successful registration.
</blockquote></details>

Note that `asyncLogin` above has `history.push(Path.ProjScreen)` on success.

**Review by JacobHaimes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1187)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[src/components/Login/Redux/LoginActions.tsx, line 75 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1187#-McL04PPBThescjAU4hD:-McL04PPBThescjAU4hE:b-ke6nc0) ([raw file](https://github.com/sillsdev/thecombine/blob/fddd481ff632072011124827a35c81b88098edc1/src/components/Login/Redux/LoginActions.tsx#L75)):*
> ```
> .then(() => {
> ```
Was the response("_res") removed since dispatch isn't reset? And if so, what was _res before that?

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1187)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @JacobHaimes)

___
*[src/components/Login/Redux/LoginActions.tsx, line 75 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1187#-McL04PPBThescjAU4hD:-McLEN-ICJqU2BwIFOlW:byp94zz) ([raw file](https://github.com/sillsdev/thecombine/blob/fddd481ff632072011124827a35c81b88098edc1/src/components/Login/Redux/LoginActions.tsx#L75)):*
<details><summary><i>Previously, JacobHaimes wrote…</i></summary><blockquote>

> ```
> .then(() => {
> ```
Was the response("_res") removed since dispatch isn't reset? And if so, what was _res before that?
</blockquote></details>

`_res` was probably short from `result`. If a variable must be defined (say, as a place-holder) but is never used, it's common to put a `_` at the start. In this case, we don't need to name it at all.

**Review by JacobHaimes — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1187)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by JacobHaimes — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1187)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
