### PR TITLE
Prefer using Enumerable.Range for simple loops

### PR DESCRIPTION
**Pull request by johnthagen**
Prefer to use the [`Range`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.range?view=netcore-3.1) function for simple loops in C#.

[Rendered style guide with rationale](https://github.com/sillsdev/TheCombine/blob/ae053de0adf84d7d79ebd63b0b588738667fda17/docs/style_guide/c_sharp_style_guide.md)

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1147)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1147)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor and @johnthagen)

___
*[Backend.Tests/Util.cs, line 104 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1147#-M_6qpXYElYz6wr0dgsm:-M_6qpXYElYz6wr0dgsn:b-rhhpv9) ([raw file](https://github.com/sillsdev/thecombine/blob/5ce304333299d5a38a90cb02db99533e810b6691/Backend.Tests/Util.cs#L104)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>             const int numSemanticDomains = 3;
>             foreach (var i in Range(1, numSemanticDomains))
>             {
>                 project.SemanticDomains.Add(RandomSemanticDomain($"{i}"));
>                 foreach (var j in Range(1, numSemanticDomains))
>                 {
>                     project.SemanticDomains.Add(RandomSemanticDomain($"{i}.{j}"));
>                     foreach (var k in Range(1, numSemanticDomains))
> ```
</details>

It was ranging from 1 to 3, but now it's from 1 to 2, no?
___
*[Backend.Tests/Controllers/LiftControllerTests.cs, line 18 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1147#-M_6r36F0_ICpRB6-uqS:-M_6r36F0_ICpRB6-uqT:bkg6b35) ([raw file](https://github.com/sillsdev/thecombine/blob/5ce304333299d5a38a90cb02db99533e810b6691/Backend.Tests/Controllers/LiftControllerTests.cs#L18)):*
> ```Smalltalk
> using Microsoft.Extensions.Logging;
> using NUnit.Framework;
> using static System.Linq.Enumerable;
> ```

Why not up with the other `System` ones?

**Comment by johnthagen** [comment]
___
*[Backend.Tests/Util.cs, line 104 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1147#-M_6qpXYElYz6wr0dgsm:-M_6rjiV9MidqI6xPk0j:b836xll) ([raw file](https://github.com/sillsdev/thecombine/blob/5ce304333299d5a38a90cb02db99533e810b6691/Backend.Tests/Util.cs#L104)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>             const int numSemanticDomains = 3;
>             foreach (var i in Range(1, numSemanticDomains))
>             {
>                 project.SemanticDomains.Add(RandomSemanticDomain($"{i}"));
>                 foreach (var j in Range(1, numSemanticDomains))
>                 {
>                     project.SemanticDomains.Add(RandomSemanticDomain($"{i}.{j}"));
>                     foreach (var k in Range(1, numSemanticDomains))
> ```
It was ranging from 1 to 3, but now it's from 1 to 2, no?
</blockquote></details>

`Range`'s arguments are `start`, and `count`, so as  I understand this it will be: 1, 2, 3

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 1 files at r2, 1 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1147)* status: all files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor and @johnthagen)

___
*[Backend.Tests/Util.cs, line 104 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1147#-M_6qpXYElYz6wr0dgsm:-M_6z8lt1NQ-WumCh2Co:b2o0hne) ([raw file](https://github.com/sillsdev/thecombine/blob/5ce304333299d5a38a90cb02db99533e810b6691/Backend.Tests/Util.cs#L104)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

`Range`'s arguments are `start`, and `count`, so as  I understand this it will be: 1, 2, 3
</blockquote></details>

Oops, sorry. I assumed it was like Python's `range`
___
*[Backend.Tests/Controllers/LiftControllerTests.cs, line 18 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1147#-M_6r36F0_ICpRB6-uqS:-M_6zSmZ1ArFh_0UcprI:bnxx0z1) ([raw file](https://github.com/sillsdev/thecombine/blob/5ce304333299d5a38a90cb02db99533e810b6691/Backend.Tests/Controllers/LiftControllerTests.cs#L18)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

By default Rider seems to sort `using static` imports separately. From what I've found it's defaults are pretty idiomatic, but if we can find a reference as to why this is not good we could change how we do it.
</blockquote></details>

It's good.
___
*[docs/style_guide/c_sharp_style_guide.md, line 46 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1147#-M_6zvgBBjYf6OmR_xtt:-M_6zvgBBjYf6OmR_xtu:by4gprd) ([raw file](https://github.com/sillsdev/thecombine/blob/6839ad9c89336829049219015fd1ee59645162d6/docs/style_guide/c_sharp_style_guide.md#L46)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> # Yes:
> using static System.Linq.Enumerable;
> foreach (var i in Range(0, 4))
> # No:
> for (var i = 0; i < 4; i++)
> ```
</details>

Might be nice to add another example that doesn't begin at 0.

**Comment by johnthagen** [comment]
This LGTM alert actually brings out another benefit of using `Range`. LGTM and other linters can detect if the loop variable is unused.

For `for (var i, ..., i++)` style loops, LGTM can't deduce that `i` is actually unused in the body of the loop, because it is incremented and checked in the `for` header.

**Comment by johnthagen** [comment]
___
*[Backend.Tests/Util.cs, line 104 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1147#-M_6qpXYElYz6wr0dgsm:-M_7-mGB9ibBg8WK2zTC:bqn2wl9) ([raw file](https://github.com/sillsdev/thecombine/blob/5ce304333299d5a38a90cb02db99533e810b6691/Backend.Tests/Util.cs#L104)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Oops, sorry. I assumed it was like Python's `range`
</blockquote></details>

Yes, it's slightly unfortunate that they chose a signature different than Python's `range`.

**Comment by johnthagen** [comment]
___
*[docs/style_guide/c_sharp_style_guide.md, line 46 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1147#-M_6zvgBBjYf6OmR_xtt:-M_70taaCEfcM_cTxHNU:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/6839ad9c89336829049219015fd1ee59645162d6/docs/style_guide/c_sharp_style_guide.md#L46)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> # Yes:
> using static System.Linq.Enumerable;
> foreach (var i in Range(0, 4))
> # No:
> for (var i = 0; i < 4; i++)
> ```
Might be nice to add another example that doesn't begin at 0.
</blockquote></details>

Done

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1147)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec, @jasonleenaylor, and @johnthagen)

___
*[docs/style_guide/c_sharp_style_guide.md, line 37 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1147#-M_71HKz8XSIw5hQE9g9:-M_71HL-7OiAdEg8wotx:bv2riyh) ([raw file](https://github.com/sillsdev/thecombine/blob/9983b144a8d59e0bfb543ad3b8d2b5f664789731/docs/style_guide/c_sharp_style_guide.md#L37)):*
> ```Markdown
> > [goto-fail bug](https://nakedsecurity.sophos.com/2014/02/24/anatomy-of-a-goto-fail-apples-ssl-bug-explained-plus-an-unofficial-patch/)
> 
> # Prefer `Range` for simple loop iteration
> ```

The above sections are \#\#.
___
*[docs/style_guide/c_sharp_style_guide.md, line 69 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1147#-M_71aLvEkO9gWlE40T3:-M_71aLvEkO9gWlE40T4:b-hyq9zt) ([raw file](https://github.com/sillsdev/thecombine/blob/9983b144a8d59e0bfb543ad3b8d2b5f664789731/docs/style_guide/c_sharp_style_guide.md#L69)):*
> ```
> ## Rationale
> ```
It would be good for both this "Rationale" and "Reason" in the previous section to have the same style.

**Comment by johnthagen** [comment]
___
*[docs/style_guide/c_sharp_style_guide.md, line 37 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1147#-M_71HKz8XSIw5hQE9g9:-M_72V5c0PyoTp-V8zrR:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/9983b144a8d59e0bfb543ad3b8d2b5f664789731/docs/style_guide/c_sharp_style_guide.md#L37)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

The above sections are \#\#.
</blockquote></details>

Done.

**Comment by johnthagen** [comment]
___
*[docs/style_guide/c_sharp_style_guide.md, line 69 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1147#-M_71aLvEkO9gWlE40T3:-M_72WGJBm5_lwFG0FXj:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/9983b144a8d59e0bfb543ad3b8d2b5f664789731/docs/style_guide/c_sharp_style_guide.md#L69)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> ## Rationale
> ```
It would be good for both this "Rationale" and "Reason" in the previous section to have the same style.
</blockquote></details>

Done.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1147)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jasonleenaylor)

**Pull request merged**
