### PR TITLE
Add Definitions column to ReviewEntries and project option to turn it on and off

### PR DESCRIPTION
**Pull request by imnasnainaec**
Items 3-4 of #1226

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1251)

### CODE REVIEW

**Review by JacobHaimes — APPROVED** [review]

**Comment by johnthagen** [comment]
___
*[src/components/ContextMenu/ContextMenu.tsx, line 15 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1251#-MejnYHBDQvEdRva6p37:-MejnYHBDQvEdRva6p38:b6hblhr) ([raw file](https://github.com/sillsdev/thecombine/blob/af99b4d1ecc120f64f1649cb64bd40830fcb5a33/src/components/ContextMenu/ContextMenu.tsx#L15)):*
> ```XML
> }
> 
> export const RIGHT_CLICK: string = "contextmenu";
> ```

Remove unnecessary `: string` type annotation.

**Comment by johnthagen** [comment]
___
*[src/components/ContextMenu/ContextMenu.tsx, line 15 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1251#-MejnYHBDQvEdRva6p37:-MepUPEZ9Mv8jvmmyYYy:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/af99b4d1ecc120f64f1649cb64bd40830fcb5a33/src/components/ContextMenu/ContextMenu.tsx#L15)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Remove unnecessary `: string` type annotation.
</blockquote></details>

Done

**Review by johnthagen — APPROVED** [review]
> Reviewed 23 of 25 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1251)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by WeJamUS — APPROVED** [review]
> Reviewed 22 of 25 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1251)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
