### PR TITLE
Bump version to 0.6.10-alpha.

### PR DESCRIPTION
**Pull request by imnasnainaec**
For after release 0.6.9.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1103)

### CODE REVIEW

**Review by jmgrady — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1103)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[package.json, line 3 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1103#-MXsrQg2BUKz6rHIeDV1:-MXsrQg2BUKz6rHIeDV2:b4nv7cy) ([raw file](https://github.com/sillsdev/thecombine/blob/1bec81a2affb00a0c6d3214e0adc0f9104d4a30c/package.json#L3)):*
> ```
> .10-alpha",
> ```
Should be 0.6.10-alpha.0
(and we should have a good way to bump the alpha version with each PR).

**Review by jmgrady — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1103)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1103)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[package.json, line 3 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1103#-MXsrQg2BUKz6rHIeDV1:-MXssYs-4BWzZkcaM898:b-a4wcvi) ([raw file](https://github.com/sillsdev/thecombine/blob/1bec81a2affb00a0c6d3214e0adc0f9104d4a30c/package.json#L3)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

> ```
> .10-alpha",
> ```
Should be 0.6.10-alpha.0
(and we should have a good way to bump the alpha version with each PR).
</blockquote></details>

Oops. Done.

**Review by jmgrady — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1103)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by jmgrady — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1103#-:-MY5TN5xDcU9v8Ea5G0q:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
