### PR TITLE
Increase backend test coverage

### PR DESCRIPTION
**Pull request by johnthagen**
- `EmailInvite` model
- `MergeBlacklistEntry.GetHashCode()`
- `Definition` model
- `Note.Equals()`
- `LevenshteinDistance` constructor
- `UserRole` model
- `FileStorage` (various)
- `UserEdit` related models
- `PasswordHash`

Also exclude `Context`s, `Repository`s, and `Startup` from code coverage results. This makes it easier to identify missing test coverage in namespaces we are actually unit testing.

Follow on work in:

- #1272
- #1273 
- #1274

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1271)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 16 of 24 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1271)* status: 16 of 24 files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[Backend/Helper/FileStorage.cs, line 175 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1271#-MfJxvhs9v3S1RbIKrPG:-MfJxvht3aNKTEP4biKT:b-8uhhet) ([raw file](https://github.com/sillsdev/thecombine/blob/44e8d88d828d16f9cbb5e51a39684eea22d39bc4/Backend/Helper/FileStorage.cs#L175)):*
> ```
>         /// <remarks> Exclude from coverage due to unreachable default switch arm. </remarks>
>         public static string FileTypeExtension(FileType type)
> ```
I don't see the `[ExcludeFromCodeCoverage]` tag here. Though I don't know if one branch being unreachable means we should exclude from coverage, as we probably want to cover the other branches.

**Review by jasonleenaylor — COMMENTED** [review]
So we might don't have it documented anywhere, but I generally prefer to roughly follow these guidelines for unit test naming:
https://osherove.com/blog/2005/4/3/naming-standards-for-unit-tests.html
It gives immediate insight into what the test is for, and can help point out when a test is trying to cover too much.
Sometimes it isn't as easy to name the 'unit' for a test, but the method being tested is usually good, or 'Constructor' for tests of a constructor.

> Reviewed 22 of 24 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1271#-:-MfK-bBJ2Wzhp-sqHBz7:b7bnva5)* status: 22 of 24 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @johnthagen)

___
*[Backend.Tests/Models/UserEditTests.cs, line 55 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1271#-MfJiq7qEo6MQd1nsd14:-MfJiq7qEo6MQd1nsd15:bmtqfkp) ([raw file](https://github.com/sillsdev/thecombine/blob/44e8d88d828d16f9cbb5e51a39684eea22d39bc4/Backend.Tests/Models/UserEditTests.cs#L55)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>             var wrapper = new UserEditStepWrapper(GoalIndex, StepString, StepIndex);
>             Assert.That(wrapper.Equals(new UserEditStepWrapper(GoalIndex, StepString, StepIndex)));
>             Assert.IsFalse(wrapper.Equals(new UserEditStepWrapper(99, StepString, StepIndex)));
>             Assert.IsFalse(wrapper.Equals(null));
> ```
</details>

I'd would have expected two more assertions here for full coverage of the Equals method

**Review by jasonleenaylor — COMMENTED** [review]
Another good resource on unit testing from Microsoft with similar advice on test naming: https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1271#-:-MfK2dc66JQU1C9gpsCX:b4565ig)* status: 22 of 24 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @johnthagen)

**Comment by johnthagen** [comment]
___
*[Backend/Helper/FileStorage.cs, line 175 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1271#-MfJxvhs9v3S1RbIKrPG:-MfNk8HT3cAvqQ6DBWwa:b-2xmjtu) ([raw file](https://github.com/sillsdev/thecombine/blob/44e8d88d828d16f9cbb5e51a39684eea22d39bc4/Backend/Helper/FileStorage.cs#L175)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>         /// <remarks> Exclude from coverage due to unreachable default switch arm. </remarks>
>         public static string FileTypeExtension(FileType type)
> ```
I don't see the `[ExcludeFromCodeCoverage]` tag here. Though I don't know if one branch being unreachable means we should exclude from coverage, as we probably want to cover the other branches.
</blockquote></details>

Good catch. This was an outdated comment.

**Comment by johnthagen** [comment]
___
*[Backend.Tests/Models/UserEditTests.cs, line 55 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1271#-MfJiq7qEo6MQd1nsd14:-MfNkpGO8CPo6VXr5eZB:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/44e8d88d828d16f9cbb5e51a39684eea22d39bc4/Backend.Tests/Models/UserEditTests.cs#L55)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
>             var wrapper = new UserEditStepWrapper(GoalIndex, StepString, StepIndex);
>             Assert.That(wrapper.Equals(new UserEditStepWrapper(GoalIndex, StepString, StepIndex)));
>             Assert.IsFalse(wrapper.Equals(new UserEditStepWrapper(99, StepString, StepIndex)));
>             Assert.IsFalse(wrapper.Equals(null));
> ```
I'd would have expected two more assertions here for full coverage of the Equals method
</blockquote></details>

Done.

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 2 of 24 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1271)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

___
*[Backend.Tests/Helper/PasswordHashTests.cs, line 32 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1271#-MfYlQDv1NxxMbjjmf0B:-MfYlQDv1NxxMbjjmf0C:b-ylwlde) ([raw file](https://github.com/sillsdev/thecombine/blob/895e50b29b834ef689570d703d1e7dbe41765c1c/Backend.Tests/Helper/PasswordHashTests.cs#L32)):*
> ```Smalltalk
>             var mutatedPassword = $"Z{Password}";
>             Assert.IsFalse(PasswordHash.ValidatePassword(hash, mutatedPassword));
>         }
> ```

Hmm, the truly paranoid would add a test that verifies the hashed password isn't equal to the password.

**Comment by johnthagen** [comment]
___
*[Backend.Tests/Helper/PasswordHashTests.cs, line 32 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1271#-MfYlQDv1NxxMbjjmf0B:-MfYoc5eBSxnn44Ujjie:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/895e50b29b834ef689570d703d1e7dbe41765c1c/Backend.Tests/Helper/PasswordHashTests.cs#L32)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Hmm, the truly paranoid would add a test that verifies the hashed password isn't equal to the password.
</blockquote></details>

Done.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 3 of 24 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 2 of 3 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1271)* status: all files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[Backend.Tests/Models/EmailInviteTests.cs, line 22 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1271#-Mfn2F71CfRgo8EsBlTH:-Mfn2F728syqwAB5vkVX:bjs6jar) ([raw file](https://github.com/sillsdev/thecombine/blob/c223a6871403ad24b96d77e7c8733587c671bc7d/Backend.Tests/Models/EmailInviteTests.cs#L22)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>             var orig = new EmailInvite(daysUntilExpire, email);
>             var clone = orig.Clone();
>             var invites = new[] { orig, clone };
>             foreach (var invite in invites)
>             {
>                 Assert.That(invite.Id, Is.EqualTo(""));
> ```
</details>

Might as well define `orig` to have a non-trivial id, to assure that also is cloned.
___
*[Backend.Tests/Models/MergeBlacklistEntryTests.cs, line 93 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1271#-Mfn2xZHDL854dI-9OXS:-Mfn2xZHDL854dI-9OXT:bz1esqi) ([raw file](https://github.com/sillsdev/thecombine/blob/c223a6871403ad24b96d77e7c8733587c671bc7d/Backend.Tests/Models/MergeBlacklistEntryTests.cs#L93)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>             var entryB = new MergeBlacklistEntry
>             {
>                 Id = "DifferentTestId",
>                 ProjectId = ProjId,
>                 UserId = UserId,
>                 WordIds = _idsRevd
>             };
> ```
</details>

Would a shorter `var entryB = entryA.Clone(); entryB.Id = "DifferentTestId";` be unadvisable because it depends on `Clone()` being independently tested?
___
*[Backend.Tests/Models/WordTests.cs, line 167 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1271#-Mfn46UY-vRYy79o5nXL:-Mfn46UY-vRYy79o5nXM:b-csaxy) ([raw file](https://github.com/sillsdev/thecombine/blob/c223a6871403ad24b96d77e7c8733587c671bc7d/Backend.Tests/Models/WordTests.cs#L167)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>         [Test]
>         public void TestHashCode()
>         {
>             Assert.AreNotEqual(
>                 new Definition { Language = Language, Text = Text }.GetHashCode(),
>                 new Definition { Language = Language, Text = "Different text" }.GetHashCode());
>         }
> ```
</details>

I've gotten in trouble in the past when I added a field to a model and neglected to add that to the hash code computation. When we add a hash code test, it might be worthwhile to have one assert `AreNotEqual` for each field. (Though I guess that may be more for catching past mistakes than future ones, so it's okay to ignore this comment.)

**Comment by johnthagen** [comment]
___
*[Backend.Tests/Models/EmailInviteTests.cs, line 22 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1271#-Mfn2F71CfRgo8EsBlTH:-Mfy6p7m504kk5ge4fv6:bwu7nkp) ([raw file](https://github.com/sillsdev/thecombine/blob/c223a6871403ad24b96d77e7c8733587c671bc7d/Backend.Tests/Models/EmailInviteTests.cs#L22)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>             var orig = new EmailInvite(daysUntilExpire, email);
>             var clone = orig.Clone();
>             var invites = new[] { orig, clone };
>             foreach (var invite in invites)
>             {
>                 Assert.That(invite.Id, Is.EqualTo(""));
> ```
Might as well define `orig` to have a non-trivial id, to assure that also is cloned.
</blockquote></details>

Perhaps this should be addressed in a follow on issue? I'm having a hard time figuring out what `Id` is even used for. It doesn't actually seem to be read or set by the backend.

Also this model doesn't seem to be used for database storage either.

Should `EmailInvite.Id` simply be removed?

**Comment by johnthagen** [comment]
___
*[Backend.Tests/Models/MergeBlacklistEntryTests.cs, line 93 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1271#-Mfn2xZHDL854dI-9OXS:-Mfy844E7aGqk4294Oit:bxf7z9b) ([raw file](https://github.com/sillsdev/thecombine/blob/c223a6871403ad24b96d77e7c8733587c671bc7d/Backend.Tests/Models/MergeBlacklistEntryTests.cs#L93)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>             var entryB = new MergeBlacklistEntry
>             {
>                 Id = "DifferentTestId",
>                 ProjectId = ProjId,
>                 UserId = UserId,
>                 WordIds = _idsRevd
>             };
> ```
Would a shorter `var entryB = entryA.Clone(); entryB.Id = "DifferentTestId";` be unadvisable because it depends on `Clone()` being independently tested?
</blockquote></details>

Yes, I was trying to make the test as independent of other methods as possible.

**Comment by johnthagen** [comment]
___
*[Backend.Tests/Models/WordTests.cs, line 167 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1271#-Mfn46UY-vRYy79o5nXL:-Mfy93Bz7pQIGANE1Ijz:bsyni6) ([raw file](https://github.com/sillsdev/thecombine/blob/c223a6871403ad24b96d77e7c8733587c671bc7d/Backend.Tests/Models/WordTests.cs#L167)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>         [Test]
>         public void TestHashCode()
>         {
>             Assert.AreNotEqual(
>                 new Definition { Language = Language, Text = Text }.GetHashCode(),
>                 new Definition { Language = Language, Text = "Different text" }.GetHashCode());
>         }
> ```
I've gotten in trouble in the past when I added a field to a model and neglected to add that to the hash code computation. When we add a hash code test, it might be worthwhile to have one assert `AreNotEqual` for each field. (Though I guess that may be more for catching past mistakes than future ones, so it's okay to ignore this comment.)
</blockquote></details>

Done.

I went ahead and added another assertion to this. I do think for models with lots of fields there are probably some diminishing returns here but in this case it's not very much of an extra testing goal.

Also, as a related aside Rider gives warnings about most of our HashCode implementations because the fields are mutable (not `readonly`). We can't make them `readonly` I believe due to how that interacts with the ASP.NET routes, but what this means is that the hash for these objects is inherently unsafe. A `Word` could be put into a Dictionary/HashMap, and a certain hash code would be used. If a `Word` field is mutated, it would then have a different hash code and would violate the properties of the Dictionary/Hash map. In a follow on issue we may want to think through implementing `GetHashCode()` at all for our mutable classes.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1271)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

___
*[Backend.Tests/Models/EmailInviteTests.cs, line 22 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1271#-Mfn2F71CfRgo8EsBlTH:-Mg61MHI6EwkI-lCOOB0:bteg2sp) ([raw file](https://github.com/sillsdev/thecombine/blob/c223a6871403ad24b96d77e7c8733587c671bc7d/Backend.Tests/Models/EmailInviteTests.cs#L22)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Perhaps this should be addressed in a follow on issue? I'm having a hard time figuring out what `Id` is even used for. It doesn't actually seem to be read or set by the backend.

Also this model doesn't seem to be used for database storage either.

Should `EmailInvite.Id` simply be removed?
</blockquote></details>

Yes, I think it should be removed. I'll make a new pr for that.

**Pull request merged**
