### PR TITLE
[MergeDups] Refactor frontend logic and show audio count

### PR DESCRIPTION
**Pull request by imnasnainaec**
Follows #2953, #3042

Also, fixes the following merge duplicates bug:
- Set up a pair of potential duplicates with similar vernacular forms: "vern1" (with 1 sense) and "vern2" (with 2 senses)
- Drag the one of the two senses from "vern2" column to "vern1" column.
- Drag from the "vern1" column its original sense to the "vern2" column.
- Now both columns should show "vern2" at top.
- Save and go to review entries.
- There should be two words with vernacular form "vern2" but (bug!) one of them still has "vern1".

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2893)

### CODE REVIEW

**Review by jmgrady — CHANGES_REQUESTED** [review]
> Reviewed 9 of 14 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2893)* status: all files reviewed, 2 unresolved discussions (waiting on @imnasnainaec)

___
*[`src/goals/MergeDuplicates/Redux/MergeDupsReduxTypes.ts` line 35 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2893#-NvmSEYP54pIbjCz52Fg:-NvmSEYP54pIbjCz52Fh:b303tz) ([raw file](https://github.com/sillsdev/TheCombine/blob/89c33a879e40bc07b80575af14580b91cd79ee77/src/goals/MergeDuplicates/Redux/MergeDupsReduxTypes.ts#L35)):*
> ```XML
> ): MergeSourceWord {
>   return { srcWordId, getAudio };
> }
> ```

It does not seem right to have a function in a file that is defining types.  If it were converting one type to another, it would be more reasonable here.  

In addition, it is only used in the test code so this should be moved there, for example, to `src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx`



_Code quote:_
```XML
export function newMergeSourceWord(
  srcWordId: string,
  getAudio = false
): MergeSourceWord {
  return { srcWordId, getAudio };
}
```
___
*[`src/goals/MergeDuplicates/Redux/reducerUtilities.ts` line 44 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2893#-Nvmi4xF6UwPu-79S90N:-Nvmi4xF6UwPu-79S90O:b-cq2y5m) ([raw file](https://github.com/sillsdev/TheCombine/blob/89c33a879e40bc07b80575af14580b91cd79ee77/src/goals/MergeDuplicates/Redux/reducerUtilities.ts#L44)):*
> ```XML
>       accessibility: deletedSenseGuids.includes(sense.guid)
>         ? Status.Deleted
>         : Status.Separate,
> ```

What does a status os `Separate` mean?  The word does not communicate anything to me in this context and I could not find any description.



_Code quote:_
```XML
 Status.Separate
```
___
*[`src/goals/MergeDuplicates/Redux/reducerUtilities.ts` line 82 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2893#-NvmZ_CT01GdIguYLc10:-NvmZ_CT01GdIguYLc11:b-in601x) ([raw file](https://github.com/sillsdev/TheCombine/blob/89c33a879e40bc07b80575af14580b91cd79ee77/src/goals/MergeDuplicates/Redux/reducerUtilities.ts#L82)):*
> ```XML
>   const redundantIds = mergeSenses.flatMap((senses) =>
>     senses.map((s) => s.srcWordId)
>   );
> ```

Why does this create an array of redundant ids?  It looks to me as though it will create an array of unique ids - with the redundant ones removed.



_Code quote:_
```XML
  const redundantIds = mergeSenses.flatMap((senses) =>
    senses.map((s) => s.srcWordId)
  );
```

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2893)* status: all files reviewed, 2 unresolved discussions (waiting on @imnasnainaec)

___
*[`src/goals/MergeDuplicates/Redux/reducerUtilities.ts` line 44 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2893#-Nvmi4xF6UwPu-79S90N:-NvmqXBQ06S8ko02-gCP:b22v1je) ([raw file](https://github.com/sillsdev/TheCombine/blob/89c33a879e40bc07b80575af14580b91cd79ee77/src/goals/MergeDuplicates/Redux/reducerUtilities.ts#L44)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

What does a status os `Separate` mean?  The word does not communicate anything to me in this context and I could not find any description.
</blockquote></details>

That's an artifact of the previous logic, and since I can't well answer that, I'll work on making it more clear.
___
*[`src/goals/MergeDuplicates/Redux/reducerUtilities.ts` line 82 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2893#-NvmZ_CT01GdIguYLc10:-Nvmq3GB2VVwZUy_Wsuh:b89s57u) ([raw file](https://github.com/sillsdev/TheCombine/blob/89c33a879e40bc07b80575af14580b91cd79ee77/src/goals/MergeDuplicates/Redux/reducerUtilities.ts#L82)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Why does this create an array of redundant ids?  It looks to me as though it will create an array of unique ids - with the redundant ones removed.
</blockquote></details>

The `.srcWordId` of a merge sense is the id of the word that the sense came from. Since a word can have multiple senses, the corresponding merge senses will have identical `.srcWordId`.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2893)* status: 13 of 16 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`src/goals/MergeDuplicates/Redux/reducerUtilities.ts` line 44 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2893#-Nvmi4xF6UwPu-79S90N:-Nvn-ZLlDdnipmHNFqUr:b-c36b6n) ([raw file](https://github.com/sillsdev/TheCombine/blob/89c33a879e40bc07b80575af14580b91cd79ee77/src/goals/MergeDuplicates/Redux/reducerUtilities.ts#L44)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

That's an artifact of the previous logic, and since I can't well answer that, I'll work on making it more clear.
</blockquote></details>

Does the newest pair of commits (https://github.com/sillsdev/TheCombine/pull/2893/files/89c33a879e40bc07b80575af14580b91cd79ee77..12f586b9124310e0e18b7400e0d382f412d423d3) alleviate the confusion?

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2893)* status: 13 of 16 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[`src/goals/MergeDuplicates/Redux/MergeDupsReduxTypes.ts` line 35 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2893#-NvmSEYP54pIbjCz52Fg:-Nvn2fHbE_7w-mzJTVHT:bo2mnwk) ([raw file](https://github.com/sillsdev/TheCombine/blob/89c33a879e40bc07b80575af14580b91cd79ee77/src/goals/MergeDuplicates/Redux/MergeDupsReduxTypes.ts#L35)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

It does not seem right to have a function in a file that is defining types.  If it were converting one type to another, it would be more reasonable here.  

In addition, it is only used in the test code so this should be moved there, for example, to `src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx`
</blockquote></details>

You're probably right about having functions in a types file, but it is our practice elsewhere for these create-a-default-instance-of-a-type functions, e.g., in https://github.com/sillsdev/TheCombine/blob/master/src/types/word.ts#L46-L103.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2893)* status: 14 of 16 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`src/goals/MergeDuplicates/Redux/MergeDupsReduxTypes.ts` line 35 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2893#-NvmSEYP54pIbjCz52Fg:-Nvqt0vFByc6dFIb3dWa:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/89c33a879e40bc07b80575af14580b91cd79ee77/src/goals/MergeDuplicates/Redux/MergeDupsReduxTypes.ts#L35)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Even so, this seems to be strictly test code so it should not be in the product code.  Is there a use case where this would be used in product code?  There has not been a need to date.
</blockquote></details>

Done.
___
*[`src/goals/MergeDuplicates/Redux/reducerUtilities.ts` line 82 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2893#-NvmZ_CT01GdIguYLc10:-Nvqt2he1D-wObbycB6H:b-8bu883) ([raw file](https://github.com/sillsdev/TheCombine/blob/89c33a879e40bc07b80575af14580b91cd79ee77/src/goals/MergeDuplicates/Redux/reducerUtilities.ts#L82)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

I still don't understand.  Based on the name, `redundantIds` should be a list of the ids that are duplicates of others.  It seems to me that this code is returning a list of all the `srcWordId`s with duplicates (the redundant ones) removed.
</blockquote></details>

The duplicates aren't removed until the next line:
```
const childrenIds = [...new Set(redundantIds)];
```

**Review by jmgrady — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2893)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
