### PR TITLE
Make LiftService a true transient service

### PR DESCRIPTION
**Pull request by jasonleenaylor**
* Add and use ILiftService interface
* Also set date created/modified when
  words are added/edited

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/679)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[Backend/Interfaces/ILiftService.cs, line 11 at r1](https://reviewable.io/reviews/sillsdev/thecombine/679#-MG9N1ZiCK--6Q5TOJDU:-MGOhKR66L_tEE6sOh3y:bn2fsqn) ([raw file](https://github.com/sillsdev/thecombine/blob/02787e3ed74071ec43567bb015d1180150c55438/Backend/Interfaces/ILiftService.cs#L11)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Interesting. dotnet-format didn't seem to care.
</blockquote></details>

Yeah, unfortunately `dotnet-format` is not particularly aggressive in what it formats.

**Comment by johnthagen** [comment]
___
*[Backend/Interfaces/ILiftService.cs, line 9 at r1](https://reviewable.io/reviews/sillsdev/thecombine/679#-MGOibhM1BgVUW0tKjWw:-MGOibhM1BgVUW0tKjWx:b-n8pwtq) ([raw file](https://github.com/sillsdev/thecombine/blob/02787e3ed74071ec43567bb015d1180150c55438/Backend/Interfaces/ILiftService.cs#L9)):*
> ```Smalltalk
>         void SetProject(string projectId);
>         string LiftExport(string projectId);
>         void LdmlImport(string combine, string bcp47);
> ```

The parameter names `combine` and `bcp47` do not match the names implemented in `LiftService`, which uses `filePath` and `langTag`. They should be set to match, and it seems to me that `combine` at a minimum should change as I don't know what that refers to?

**Review by johnthagen — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/679)* status: all files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor)

**Comment by johnthagen** [comment]
@jasonleenaylor FYI, I merged master into your branch for you since GitHub UI couldn't due to previous PR that was recently merged.

**Comment by jasonleenaylor** [comment]
___
*[Backend/Interfaces/ILiftService.cs, line 9 at r1](https://reviewable.io/reviews/sillsdev/thecombine/679#-MGOibhM1BgVUW0tKjWw:-MGPcNIP0Sj6yMn_KhrC:bxbnyef) ([raw file](https://github.com/sillsdev/thecombine/blob/02787e3ed74071ec43567bb015d1180150c55438/Backend/Interfaces/ILiftService.cs#L9)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

The parameter names `combine` and `bcp47` do not match the names implemented in `LiftService`, which uses `filePath` and `langTag`. They should be set to match, and it seems to me that `combine` at a minimum should change as I don't know what that refers to?
</blockquote></details>

yes, extracting interfaces automatically generates entertaining names. Should have noticed that. For reference bcp47 is the standard for language tags. I'll change the interface to match the implementation names.

**Review by jasonleenaylor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/679)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor and @johnthagen)

___
*[Backend/Interfaces/ILiftService.cs, line 11 at r1](https://reviewable.io/reviews/sillsdev/thecombine/679#-MG9N1ZiCK--6Q5TOJDU:-MGPcqIa9YGUj14HKwV6:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/02787e3ed74071ec43567bb015d1180150c55438/Backend/Interfaces/ILiftService.cs#L11)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Yeah, unfortunately `dotnet-format` is not particularly aggressive in what it formats.
</blockquote></details>

Done.

**Review by johnthagen — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/679)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
