### PR TITLE
Remove duplicated CORS attributes from Controllers

### PR DESCRIPTION
**Pull request by johnthagen**
The call in `Startup.Configure` to `app.UseCors(LocalhostCorsPolicy);` should apply CORS headers to all requests.

Remove duplicated `EnableCors[]` attributes to `Controller`s, which should not be needed.

CORS is only needed for local development outside of Docker, so that is the context that should be tested for this PR.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1356)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
I've tested everything except for the InviteController. @imnasnainaec Can you verify that one and approve if it works?

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1356#-:-MigbhfX8FKGePIRlgyL:b-pyem6j)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 9 of 11 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1356)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Review by imnasnainaec — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1356#-:-MigiBqi26gWlGNWDsTB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1356)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Pull request merged**
