### PR TITLE
[MargeDup, ReviewEntries] View glosses in all analysis langs

### LINKED ISSUE #912: Show glosses for all analysis languages in ReviewEntries, MergeDups
Presently only glosses for the first/top analysis language are visible (except perhaps in the MergeDup side tray).

### LINKED ISSUE #1034: Review Entries hangs when editing a word with no Domain specified
If one goes into Review Entries for a project and edits a word that has been entered without a Domain defined, when the :heavy_check_mark: is clicked to save the changes, the screen is stuck with the "busy" cursor.  The user can change to other screens but Review Entries is stuck.  Note, no changes are made to the database.

The Bulu03 project has a lot of entries with no domain specified.  If one adds the domain for all the glosses of the word that is being edited, then the changes are saved and the screen does not hang.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Follow-up to #1013
Resolves #912
Fixes #1034

**ReviewEntries**
* On conversion of Words to ReviewEntryWords, if a sense has two glosses with the same language code, combine them.
* Remove `analysisLang` from the ReviewEntriesState and all associated props and functions.
* Show glosses, regardless of lang:
  - When not editing a row, show as one comma-separated string, without any language indication;
  - When editing a row, on every sense, provide one language-labeled input cell per gloss, including one for the default analysis language even if no gloss present.
* Fix row-saving behavior:
  - Don't allow saving if no senses, or if any gloss has no sense or no domains;
  - Restore explanatory alert to user on failed save attempt;
  - On save, remove any duplicate domains from a sense and any deleted senses.

**MergeDuplicates**
* For each sense, show the gloss in _every_ analysis language of the project, including a blank if no gloss given for that language, but no glosses of other analysis languages.

**ProjectSettings**
* Allow deletion of non-default analysis languages
* Add magnifying-glass-icon button that, when pressed, searches through all frontier entries and lists every language tag that occurs in a gloss.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1033)

### CODE REVIEW

**Review by jasonleenaylor — CHANGES_REQUESTED** [review]
> Reviewed 10 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1033)* status: 10 of 17 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec)

___
*[src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx, line 107 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1033#-MUnh-B300QUuS4EfhiZ:-MUnh-B300QUuS4Efhi_:be3f444) ([raw file](https://github.com/sillsdev/thecombine/blob/86051704e1961442cff2a0e5e79169bfabbb080b/src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx#L107)):*
> ```
>           onClick={() => this.deleteAnalysisWritingSystem(index)}
> ```
We should discourage deleting the last analysis language, and make default should not be available on the existing default.
___
*[src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx, line 227 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1033#-MUnh_L_BvVPxtiqfFEo:-MUnh_L_BvVPxtiqfFEp:bgdq98r) ([raw file](https://github.com/sillsdev/thecombine/blob/86051704e1961442cff2a0e5e79169bfabbb080b/src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx#L227)):*
> ```
> interface IconButtonWithTooltipProps {
> ```
This should probably go in its own file, someplace where we have reusable components

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1033)* status: 10 of 17 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @jasonleenaylor)

___
*[src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx, line 107 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1033#-MUnh-B300QUuS4EfhiZ:-MUnj-y25rzh38K9GgVI:b-c22xvi) ([raw file](https://github.com/sillsdev/thecombine/blob/86051704e1961442cff2a0e5e79169bfabbb080b/src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx#L107)):*
The buttons are not available for the first/top/default one:
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>   writingSystemButtons(index: number) {
>     if (index === 0) {
>       return;
>     }
> ```
</details>

**Review by jasonleenaylor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1033)* status: 10 of 17 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx, line 107 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1033#-MUnh-B300QUuS4EfhiZ:-MUnvbTG9IdoHWZsT8qa:b-7w1gnf) ([raw file](https://github.com/sillsdev/thecombine/blob/86051704e1961442cff2a0e5e79169bfabbb080b/src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx#L107)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

The buttons are not available for the first/top/default one:
> ```
>   writingSystemButtons(index: number) {
>     if (index === 0) {
>       return;
>     }
> ```

</blockquote></details>

Yup, just saw that. :smile:

**Review by jasonleenaylor — COMMENTED** [review]
Looking good, I'll re-review once you fix the issue we discussed with the focus being lost after typing the first letter in an empty gloss field.

> Reviewed 1 of 5 files at r1, 6 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1033#-:-MUo2Ruq4gXBwSOQg63j:benu2h0)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
Focus issue fixed.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1033#-:-MUpLqpTE3Inb_MuxS7m:b9qvafi)* status: 15 of 18 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jasonleenaylor)

___
*[src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx, line 227 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1033#-MUnh_L_BvVPxtiqfFEo:-MUpLoexDe9ynd8lqZVV:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/86051704e1961442cff2a0e5e79169bfabbb080b/src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx#L227)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> interface IconButtonWithTooltipProps {
> ```
This should probably go in its own file, someplace where we have reusable components
</blockquote></details>

Done

**Review by jasonleenaylor — APPROVED** [review]
This is an excellent added feature but it comes with one bug that I've noticed. If you add a change the default, or delete an analysis language and then go to review entries it does not reflect the changes. 

You can choose to merge this and fix the bug in a follow up issue or fix it here and I'll re-review.

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1033#-:-MUsTcgT4NyMCXm3QLIl:b-nvzdtw)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
