### PR TITLE
Changed wording of Step to Merge set

### LINKED ISSUE #1316: [MergeDuplicates] Replace "step" with better word.
"Step # of #" can incorrectly imply that there will be multiple steps in merging the visible sets of words. Something like "set", "word set", "merge candidate", "possible merge", "merge set" would be more accurate.

### PR DESCRIPTION
**Pull request by JacobHaimes**
Changed "Step" to "Merge set" to increase clarity when merging.

Closes #1316

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1365)

### CODE REVIEW

**Comment by WeJamUS** [comment]
___
*[src/resources/translations.json, line 550 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1365#-Mj5A5yt5kO5oqmJtWeR:-Mj5A5yt5kO5oqmJtWeS:b5wfrwr) ([raw file](https://github.com/sillsdev/thecombine/blob/5df64616c9da21e135ab129256ce2553ffdf45ac/src/resources/translations.json#L550)):*
> ```JSON
>     "progress": {
>       "step": ["Step", "Paso", "Étape"],
>       "stepMerge": ["Merge set", "Merge set", "Merge set"],
> ```

Capitalize the "s" in "set"?

**Review by WeJamUS — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1365)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @JacobHaimes)

**Review by imnasnainaec — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1365)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @JacobHaimes)

___
*[src/goals/DefaultGoal/DisplayProgress.tsx, line 16 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1365#-MjA8u4_Bh50TlV7Dqu2:-MjA8u4a0yzrIh85T0I1:b8m1see) ([raw file](https://github.com/sillsdev/thecombine/blob/686531d6920e39f91be11af587dfcca0fe720a0b/src/goals/DefaultGoal/DisplayProgress.tsx#L16)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>   const currentGoal = useSelector(
>     (state: StoreState) => state.goalsState.currentGoal
>   );
>   const currentStep = currentGoal.currentStep;
>   const numSteps = currentGoal.numSteps;
> ```
</details>

I'm sorry, I gave you bad advice here! `currentStep` needs its own specific selector, or else the number doesn't advance in the progress bar.  The other two (`numSteps` and `goalType`) might as well have their own selectors too.

To make sure that isn't lost in the future, can you add a comment:
```
 /* We cannot use a single selector for state.goalsState.currentGoal and define everything on that;
 currentStep needs its own targeted selector for it to re-render as the user progresses. */
 const currentStep = useSelector(
    (state: StoreState) => state.goalsState.currentGoal.currentStep
  );
```
___
*[src/resources/translations.json, line 550 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1365#-Mj5A5yt5kO5oqmJtWeR:-MjAAR2t8tVK67kPO9Wl:bhambf0) ([raw file](https://github.com/sillsdev/thecombine/blob/686531d6920e39f91be11af587dfcca0fe720a0b/src/resources/translations.json#L550)):*
<details><summary><i>Previously, WeJamUS (James Wu) wrote…</i></summary><blockquote>

Capitalize the "s" in "set"?
</blockquote></details>

I'm content with either.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1365)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JacobHaimes)

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1365)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JacobHaimes)

**Pull request merged**
