### PR TITLE
[ReviewEntries] Allow filtering Domains by both number and name

### LINKED ISSUE #722: [ReviewEntries] Domains filter needs improvement
(Mentioned by Chuck in Sep. 16 debrief.)

Filtering with (e.g.) "2.1" also brings up "2.1.3" and "4.5.2.1.1". Should be able to type "2.1: Body" to limit just to 2.1, but that gives no results.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #722 

Can now type `<number>:<name>` and it shows results matching both.
Without a colon (:), it still will match to either number or name.

Features:
* Whitespace around the search terms is ingored
* The search is not case sensitive
* Everything after a second colon (:) is ignored

Example:
* "2.1 : Bod" and " 2.1:body:jkhiojoij" both bring up entries with "2.1: Body"

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/723)

### CODE REVIEW

**Comment by imnasnainaec** [comment]
Related: #721

**Review by jasonleenaylor — CHANGES_REQUESTED** [review]
I approve of the approach, and have no complaints about the code.
However, this logic is sufficiently complex to deserve a unit test and a comment.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/723#-:-MHX89Vq7wkqdXxtu7KZ:bntw2ei)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx, line 199 at r1](https://reviewable.io/reviews/sillsdev/thecombine/723#-MHX8L7hBZ6vSG76CN3w:-MHX8L7hBZ6vSG76CN3x:bmki9cg) ([raw file](https://github.com/sillsdev/thecombine/blob/84068caf5c772629d945df7a5f646bc647e7972d/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx#L199)):*
> ```XML
>               return true;
>       } else {
>         const regexNumber: RegExp = new RegExp(terms[0]);
> ```

Add a comment here explaining the desired matching behavior. We both know what this means now, but it will save us time later if there is a bug or a change required here.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/723)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jasonleenaylor)

___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx, line 199 at r1](https://reviewable.io/reviews/sillsdev/thecombine/723#-MHX8L7hBZ6vSG76CN3w:-MHXP30l5-97c3Nq3k5J:b-a1bk3n) ([raw file](https://github.com/sillsdev/thecombine/blob/84068caf5c772629d945df7a5f646bc647e7972d/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx#L199)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Add a comment here explaining the desired matching behavior. We both know what this means now, but it will save us time later if there is a bug or a change required here.
</blockquote></details>

How's the comment added at the top of the function?

**Review by jasonleenaylor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/723)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @imnasnainaec and @jasonleenaylor)

___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx, line 199 at r1](https://reviewable.io/reviews/sillsdev/thecombine/723#-MHX8L7hBZ6vSG76CN3w:-MHXq6fBCaRYOPdTg_N-:b-vs1pr4) ([raw file](https://github.com/sillsdev/thecombine/blob/84068caf5c772629d945df7a5f646bc647e7972d/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx#L199)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

How's the comment added at the top of the function?
</blockquote></details>

Looks good.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/723)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
