### PR TITLE
Remove unused variable in test

### PR DESCRIPTION
**Pull request by johnthagen**
Fixes GitHub Actions warning: https://github.com/sillsdev/TheCombine/actions/runs/285286292

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/747)

### CODE REVIEW

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/747)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by imnasnainaec — APPROVED** [review]
*[src/components/PasswordReset/tests/ResetPage.test.tsx, line 19 at r2](https://reviewable.io/reviews/sillsdev/thecombine/747#-MIzfWf37zlDqq6Acnre:-MIzfWf46YXYkj1wftt8:b-askmst) ([raw file](https://github.com/sillsdev/thecombine/blob/c1cd7d3fb477b5192d50c0d2b542148f1dfa0d38/src/components/PasswordReset/tests/ResetPage.test.tsx#L19)):*
> ```XML
>         <PasswordReset resetState={0} passwordReset={jest.fn()} />
> ```

`PasswordReset` still gives a Typescript warning because it is missing the properties of `RouteComponentProps`

**Comment by imnasnainaec** [comment]
> _[src/components/PasswordReset/tests/ResetPage.test.tsx, line 19 at r2](https://reviewable.io/reviews/sillsdev/thecombine/747#-MIzfWf37zlDqq6Acnre:-MIzfWf46YXYkj1wftt8:b-askmst) ([raw file](https://github.com/sillsdev/thecombine/blob/c1cd7d3fb477b5192d50c0d2b542148f1dfa0d38/src/components/PasswordReset/tests/ResetPage.test.tsx#L19)):_
> 
> > ```
> >         <PasswordReset resetState={0} passwordReset={jest.fn()} />
> > ```
> 
> `PasswordReset` still gives a Typescript warning because it is missing the properties of `RouteComponentProps`

I tried to resolve that using `withRouter` in a number of ways, but kept hitting dead ends, so I'm content to leave it for now.

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/747)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Pull request merged**
