### PR TITLE
Update image_repo references

### LINKED ISSUE #1679: CI/CD scripts fail to update QA/Production servers
**Describe the bug**

When a PR is merged to master, the QA server cannot be updated.  The frontend, backend, and maintenance pods have a status of `InvalidImageName` after they are updated by the CI/CD scripts.

**To Reproduce**

1. Approve an merge a PR on GitHub
2. When the triggered actions are complete, run:
    ```
    kubectl -n thecombine get pods
    ```
    Output will show the status is `InvalidImageName`, for example:
    ```
    $ kubectl -n thecombine get pods
    NAME                                READY   STATUS             RESTARTS   AGE
    backend-5d9c5fd775-vfj6q            0/1     InvalidImageName   0          155m
    database-794b4d956f-x2wtc           1/1     Running            0          8d
    frontend-54dd66cbf-wd76g            0/1     InvalidImageName   0          155m
    gha-thecombine-runner-chxhg-d9kfh   2/2     Running            0          155m
    maintenance-559899cbd-ckgtn         0/1     InvalidImageName   0          155m
    ```
    
**Expected behavior**

Pod status should be `Running`.

**Environment:**

This was observed on the Kubernetes cluster for the QA server.

### PR DESCRIPTION
**Pull request by jmgrady**
### Change

Replace references to input.image_repo with the new input names:
- image_registry, and
- image_registry_alias

### Details
PR #1677 change how AWS ECR was referenced in order to support an AWS ECR public registry.  The input to the custom git hub actions, `combine-build` and `combine-deploy-update`, that specifies the image registry to use was changed;  the single `image_repo` input was changed to `image_registry` and `image_registry_alias`.

The implementation of this change was not complete.  The required updates to the `combine-deploy-update` were missed.  This PR completes the required changes.

Closes #1679

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1680)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1680)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`.github/actions/combine-deploy-update/action.yml` line 5 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1680#-N5uYGim1qbxaqFBtIxt:-N5uYGin4tZjBSegS5E9:bb91qrl) ([raw file](https://github.com/sillsdev/thecombine/blob/33950dada18e8686b6dbbee1911050ca14f6a7ca/.github/actions/combine-deploy-update/action.yml#L5)):*
> ```YAML
> inputs:
>   image_registry:
>     description: "Docker Image Repository"
> ```

Update description too?



_Code quote:_
```YAML
"Docker Image Repository"
```

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1680)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[`.github/actions/combine-deploy-update/action.yml` line 5 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1680#-N5uYGim1qbxaqFBtIxt:-N5u_shl5W-tjhQYm5NJ:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/33950dada18e8686b6dbbee1911050ca14f6a7ca/.github/actions/combine-deploy-update/action.yml#L5)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Update description too?
</blockquote></details>

Done.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1680)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`.github/actions/combine-deploy-update/action.yml` line 36 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1680#-N5ubEGA6rSqiImPfzRw:-N5ubEGA6rSqiImPfzRx:b-b8z3f7) ([raw file](https://github.com/sillsdev/thecombine/blob/78ee21b3b0644244c6617a7f115b356b06bf47e3/.github/actions/combine-deploy-update/action.yml#L36)):*
> ```YAML
>       run: kubectl --context ${{ inputs.kube_context }}
>         set image deployment/frontend
>         frontend="${{ inputs.image_registry }}${{ inputs.image_registry_alias}}/combine_frontend:${{ inputs.image_tag }}"
> ```

So there's no / or : or anything else separating these two things?



_Code quote:_
```YAML
${{ inputs.image_registry }}${{ inputs.image_registry_alias}}
```

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1680)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[`.github/actions/combine-deploy-update/action.yml` line 36 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1680#-N5ubEGA6rSqiImPfzRw:-N5ugE7u1mRg2c0cRdnP:b-8ahfuh) ([raw file](https://github.com/sillsdev/thecombine/blob/78ee21b3b0644244c6617a7f115b356b06bf47e3/.github/actions/combine-deploy-update/action.yml#L36)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

So there's no / or : or anything else separating these two things?
</blockquote></details>

Correct.  The `/` is part of the `image_registry_alias`.  For the private registry (builds for the QA server) there is no `image_registry_alias`; for the public registry, there is one.  I did not include the alias as part of the `image_registry` because during the build process, we login to the `image_registry` so that the images can be pushed to the registry.  During the login, the alias is not part of the login command.

I have updated the description to indicate that the `/` should be in the `image_registry_alias`.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1680)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Pull request merged**
