### PR TITLE
Dependency updates for September 2024

### PR DESCRIPTION
**Pull request by jmgrady**
Merge in dependency updates recommended by `dependabot`.

Updates to react-redux 9.1.2, redux 5.0.1, and redux-thunk 3.1.0 are held back.  They are breaking changes that require non-trivial changes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3351)

### CODE REVIEW

**Review by imnasnainaec — CHANGES_REQUESTED** [review]
> Reviewed 8 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3351)* status: 8 of 17 files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor and @jmgrady)

*[a discussion](https://reviewable.io/reviews/sillsdev/TheCombine/3351#-O62QoVm-CNSRkCqetQd:-O62QoVm-CNSRkCqetQe:b-gdj48i) (no related file):*
License report update?

___
___
*[`deploy/requirements.txt` line 2 at r1](https://reviewable.io/reviews/sillsdev/TheCombine/3351#-O62QLlo0-y9XFjWFrko:-O62QLmM4zHQtGrar69w:bem8s7m) ([raw file](https://github.com/sillsdev/TheCombine/blob/96d76d0917b42f96c49f7d492c068cf5c2fad60e/deploy/requirements.txt#L2)):*
> ```help
> #
> # This file is autogenerated by pip-compile with Python 3.12
> ```

If we're starting to do things with Python 3.12, we should probably add `3.12: lint` to the `[gh-actions]` of `tox.ini`.

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3351)* status: 6 of 20 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jasonleenaylor)

*[a discussion](https://reviewable.io/reviews/sillsdev/TheCombine/3351#-O62QoVm-CNSRkCqetQd:-O67xM123vz3x6Guc-ec:b-896fix) (no related file):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

License report update?
</blockquote></details>

Done.

___
___
*[`deploy/requirements.txt` line 2 at r1](https://reviewable.io/reviews/sillsdev/TheCombine/3351#-O62QLlo0-y9XFjWFrko:-O67xRsT3kWm162PKgwV:bz2ki23) ([raw file](https://github.com/sillsdev/TheCombine/blob/96d76d0917b42f96c49f7d492c068cf5c2fad60e/deploy/requirements.txt#L2)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

If we're starting to do things with Python 3.12, we should probably add `3.12: lint` to the `[gh-actions]` of `tox.ini`.
</blockquote></details>

Done.

Changed all references to the Python version to 3.12.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 4 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3351)* status: 10 of 20 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

___
*[`deploy/requirements.txt` line 2 at r1](https://reviewable.io/reviews/sillsdev/TheCombine/3351#-O62QLlo0-y9XFjWFrko:-O6D8dmn9X_ZFIJ5UY9H:b-a7essw) ([raw file](https://github.com/sillsdev/TheCombine/blob/96d76d0917b42f96c49f7d492c068cf5c2fad60e/deploy/requirements.txt#L2)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Done.

Changed all references to the Python version to 3.12.
</blockquote></details>

`tox.ini` still needs to be updated
___
*[`docs/user_guide/assets/licenses/backend_licenses.txt` line 35 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/3351#-O6D93zU9w6bKLygUYQV:-O6D93zU9w6bKLygUYQW:b-j99ecy) ([raw file](https://github.com/sillsdev/TheCombine/blob/f5dbb15d7ae6d62f815acd37d5dd55446e233a3a/docs/user_guide/assets/licenses/backend_licenses.txt#L35)):*
> ```help
> ####################################################################################################
> Package:icu.net
> Version:2.8.1
> ```

I wonder why the icu.net version here went from `2.9.0` to `2.8.1`, especially since we're using `2.10.1-beta.5`.

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3351)* status: 10 of 21 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

___
*[`deploy/requirements.txt` line 2 at r1](https://reviewable.io/reviews/sillsdev/TheCombine/3351#-O62QLlo0-y9XFjWFrko:-O6IPolfAJdHuVdNawoK:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/96d76d0917b42f96c49f7d492c068cf5c2fad60e/deploy/requirements.txt#L2)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`tox.ini` still needs to be updated
</blockquote></details>

Done.
___
*[`docs/user_guide/assets/licenses/backend_licenses.txt` line 35 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/3351#-O6D93zU9w6bKLygUYQV:-O6ITmNcAPOmwqJj0x3y:b4szvua) ([raw file](https://github.com/sillsdev/TheCombine/blob/f5dbb15d7ae6d62f815acd37d5dd55446e233a3a/docs/user_guide/assets/licenses/backend_licenses.txt#L35)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I wonder why the icu.net version here went from `2.9.0` to `2.8.1`, especially since we're using `2.10.1-beta.5`.
</blockquote></details>

I reran `license-report-backend` (after pulling the latest changes to the branch) and now the icu.net version is correct.  There were several  libraries from Microsoft that seem to have been removed.  Since you were kind enough to do the dependabot PR last month, perhaps they are from libraries installed on your PC but not on my Ubuntu 22.04 VM.  This includes licenses for C# (which is not included in our build so that is fine).

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3351)* status: 20 of 21 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jasonleenaylor)

___
*[`docs/user_guide/assets/licenses/backend_licenses.txt` line 35 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/3351#-O6D93zU9w6bKLygUYQV:-O79p9aC7DfzOv1mChpz:b-ks612f) ([raw file](https://github.com/sillsdev/TheCombine/blob/f5dbb15d7ae6d62f815acd37d5dd55446e233a3a/docs/user_guide/assets/licenses/backend_licenses.txt#L35)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

That's another reason it'd be great for the license reports to be auto-generated.

Though I'm still puzzled why the icu.net version isn't at `2.10.1-beta.5`.
</blockquote></details>

I'm `seeing 2.10.1-beta.5`:

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3351)* status: 20 of 21 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jasonleenaylor)

___
*[`docs/user_guide/assets/licenses/backend_licenses.txt` line 35 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/3351#-O6D93zU9w6bKLygUYQV:-O79pcZh4s1g4fn50aEa:b-cickwg) ([raw file](https://github.com/sillsdev/TheCombine/blob/f5dbb15d7ae6d62f815acd37d5dd55446e233a3a/docs/user_guide/assets/licenses/backend_licenses.txt#L35)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

I'm `seeing 2.10.1-beta.5`:

</blockquote></details>

Actually, I see both:

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3351)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jasonleenaylor)

**Pull request merged**
