### PR TITLE
Add global state for whether DataEntry domain tree is open

### LINKED ISSUE #1447: [DataEntry] When in Data Entry, app-bar "Data Entry" button should return to the domain tree
If you are in Data Entry, in a specific domain, clicking the "Data Entry" button in the top App Bar doesn't do anything. Intuitively, it should return you to the domain tree.

Make it so that button does the same thing as hitting the "Exit" button.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #1447

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1460)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryComponent.tsx, line 49 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1460#-Mnk1V4z7IW-Li_ipryx:-Mnk1V4z7IW-Li_ipryy:bzbwhnp) ([raw file](https://github.com/sillsdev/thecombine/blob/ffded1172e1b243540c6182c1eceef0d45d4d335/src/components/DataEntry/DataEntryComponent.tsx#L49)):*
> ```XML
>   let domainWords: DomainWord[] = [];
>   let domainName: String = domain.name;
>   let domainMatched: Boolean = false;
> ```

Thanks for removing these. I did a quick search of the code base to see if we used `String` anywhere instead of `string` (same with `Boolean` instead of `boolean`) and I didn't find any.

We should always use lower case `string` and `boolean` for types in TS, from what I have read.

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryComponent.tsx, line 49 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1460#-Mnk1V4z7IW-Li_ipryx:-Mnk1iGg9lWd4qtvuuCV:bvm7z8d) ([raw file](https://github.com/sillsdev/thecombine/blob/ffded1172e1b243540c6182c1eceef0d45d4d335/src/components/DataEntry/DataEntryComponent.tsx#L49)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Thanks for removing these. I did a quick search of the code base to see if we used `String` anywhere instead of `string` (same with `Boolean` instead of `boolean`) and I didn't find any.

We should always use lower case `string` and `boolean` for types in TS, from what I have read.
</blockquote></details>

Resolved

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryComponent.tsx, line 56 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1460#-Mnk2mdz0I5XRZqlXq0r:-Mnk2mdz0I5XRZqlXq0s:b-olxxk5) ([raw file](https://github.com/sillsdev/thecombine/blob/b0de81abaf2ce887b1eb94ff47f81edcc65fc445/src/components/DataEntry/DataEntryComponent.tsx#L56)):*
> ```XML
>       (s) =>
>         // This is for States created before .accessibility was required in the frontend.
>         s.accessibility === State.Active || s.accessibility === undefined
> ```

`Sense.accessibility` cannot be `undefined` based on its type. Should this be refactored? This check should be impossible based on the TS compiler.

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/DataEntryTable.tsx, line 73 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1460#-Mnk4JVbB3HPOeLn3Xy6:-Mnk4JVbB3HPOeLn3Xy7:b-deppr5) ([raw file](https://github.com/sillsdev/thecombine/blob/b0de81abaf2ce887b1eb94ff47f81edcc65fc445/src/components/DataEntry/DataEntryTable/DataEntryTable.tsx#L73)):*
> ```XML
>     const updatedSenses = [...existingWord.senses];
>     updatedSenses.splice(senseIndex, 1, updatedSense);
>     const updatedWord: Word = { ...existingWord, senses: updatedSenses };
> ```

Should we simply return this directly rather than create a redundant `updatedWord` variable?

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/DataEntryTable.tsx, line 136 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1460#-Mnk4dCk8iI45YF2ZFPT:-Mnk4dCk8iI45YF2ZFPU:bc1qlin) ([raw file](https://github.com/sillsdev/thecombine/blob/b0de81abaf2ce887b1eb94ff47f81edcc65fc445/src/components/DataEntry/DataEntryTable/DataEntryTable.tsx#L136)):*
> ```XML
> 
>   /** Finished with this page of words, select new semantic domain */
>   // TODO: Implement
> ```

Is it okay that this is not implemented?

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/DataEntryTable.tsx, line 516 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1460#-Mnk5IpCEwgEvdrUKgNW:-Mnk5IpD7pXNPg31BBHx:b-blnewb) ([raw file](https://github.com/sillsdev/thecombine/blob/b0de81abaf2ce887b1eb94ff47f81edcc65fc445/src/components/DataEntry/DataEntryTable/DataEntryTable.tsx#L516)):*
> ```XML
>       const newEntryAudio = this.refNewEntry.current.state.audioFileURLs;
>       if (newEntry?.vernacular) {
>         this.addNewWord(newEntry, newEntryAudio, undefined, true);
> ```

Is it okay that we ignore the promise here? Is there a situation where we would want to `.catch()`?

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/DataEntryTable.tsx, line 506 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1460#-Mnk5Qhu6efHhiQHEUCW:-Mnk5Qhv5ot-n7wPy70D:b11fo26) ([raw file](https://github.com/sillsdev/thecombine/blob/b0de81abaf2ce887b1eb94ff47f81edcc65fc445/src/components/DataEntry/DataEntryTable/DataEntryTable.tsx#L506)):*
> ```XML
> 
>   exitGracefully() {
>     // Check if there is a new word, but the user clicked complete instead of pressing enter
> ```

Wrap line at 80 characters.

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/tests/DataEntryTable.test.tsx, line 79 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1460#-Mnk5tRA34f7ptE9XYn6:-Mnk5tRA34f7ptE9XYn7:b-5d9bec) ([raw file](https://github.com/sillsdev/thecombine/blob/b0de81abaf2ce887b1eb94ff47f81edcc65fc445/src/components/DataEntry/DataEntryTable/tests/DataEntryTable.test.tsx#L79)):*
> ```XML
> 
> describe("DataEntryTable", () => {
>   /*it("should call add word on backend when new entry has data and exit is clicked", (done) => {
> ```

Did you intend to comment these out permanently?

**Comment by johnthagen** [comment]
___
*[src/components/TreeView/TreeViewActions.ts, line 4 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1460#-Mnk69V0Ei9btekEiFmj:-Mnk69V0Ei9btekEiFmk:b-bbzp7r) ([raw file](https://github.com/sillsdev/thecombine/blob/b0de81abaf2ce887b1eb94ff47f81edcc65fc445/src/components/TreeView/TreeViewActions.ts#L4)):*
> ```XML
> 
> export enum TreeActionType {
>   CLOSE_TREE = "closeTree",
> ```

Most of our other `enum`s in the code base use `"CLOSE_TREE"` casing for the enum string values. Any particular reason to use `"closeTree"` style here?

**Comment by johnthagen** [comment]
___
*[src/components/TreeView/TreeViewComponent.tsx, line 71 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1460#-Mnk6Ri1AZUQMw_5evQC:-Mnk6Ri1AZUQMw_5evQD:bcgx6gk) ([raw file](https://github.com/sillsdev/thecombine/blob/b0de81abaf2ce887b1eb94ff47f81edcc65fc445/src/components/TreeView/TreeViewComponent.tsx#L71)):*
> ```XML
>       return new Promise((resolve) =>
>         setTimeout(() => {
>           if (domain && this.state.visible === false) {
> ```

Simplify to:

```ts
if (domain && this.state.visible) {
```

**Review by johnthagen — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1460)* status: all files reviewed, 8 unresolved discussions (waiting on @imnasnainaec)

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/DataEntryTable.tsx, line 73 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1460#-Mnk4JVbB3HPOeLn3Xy6:-MnkBHjcBRGHIDRnoH8C:b-i776zl) ([raw file](https://github.com/sillsdev/thecombine/blob/b0de81abaf2ce887b1eb94ff47f81edcc65fc445/src/components/DataEntry/DataEntryTable/DataEntryTable.tsx#L73)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Should we simply return this directly rather than create a redundant `updatedWord` variable?
</blockquote></details>

Done in #1461

**Comment by johnthagen** [comment]
___
*[src/components/TreeView/TreeViewComponent.tsx, line 71 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1460#-Mnk6Ri1AZUQMw_5evQC:-MnkBMcMAHFU_1dAjnt_:b-i776zl) ([raw file](https://github.com/sillsdev/thecombine/blob/b0de81abaf2ce887b1eb94ff47f81edcc65fc445/src/components/TreeView/TreeViewComponent.tsx#L71)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Simplify to:

```ts
if (domain && this.state.visible) {
```
</blockquote></details>

Done in #1461

**Review by johnthagen — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1460)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1460)* status: all files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[src/components/DataEntry/DataEntryComponent.tsx, line 56 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1460#-Mnk2mdz0I5XRZqlXq0r:-Mo-FvEp-8xrQwMoeFPS:b-pn20zj) ([raw file](https://github.com/sillsdev/thecombine/blob/c6f6b2f9840970cf528b576d1bcce4d3f73de654/src/components/DataEntry/DataEntryComponent.tsx#L56)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

`Sense.accessibility` cannot be `undefined` based on its type. Should this be refactored? This check should be impossible based on the TS compiler.
</blockquote></details>

Oh, as the comment indicates, there may be entries in the database without `.accessibility` defined on all its senses.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1460)* status: all files reviewed, 1 unresolved discussion (waiting on @johnthagen)

**Pull request merged**
