### PR TITLE
Add Ability to Delete Words

### PR DESCRIPTION
**Pull request by StevesBro**
Uses new accessibility word field to filter out active and deleted words.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/587)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[Backend/Controllers/FrontierController.cs, line 21 at r4](https://reviewable.io/reviews/sillsdev/thecombine/587#-MEhJ3oAA_e6iXgNeyNF:-MEhJ3oAA_e6iXgNeyNG:b-u272w) ([raw file](https://github.com/sillsdev/thecombine/blob/31de26083b1227136c15ed23a216ff58f23e075a/Backend/Controllers/FrontierController.cs#L21)):*
> ```Smalltalk
>         private readonly IPermissionService _permissionService;
> 
>         public FrontierController(IWordRepository repo, IWordService wordService, IProjectService projServ, IPermissionService permissionService)
> ```

We've been trying to wrap the backend source lines at 120 columns so make it easier to review and read side by side. Unfortunately `dotnet-format` doesn't do this automatically (like Prettier does for our TS code) so we have to manually do this.

**Comment by johnthagen** [comment]
___
*[Backend/Controllers/FrontierController.cs, line 21 at r4](https://reviewable.io/reviews/sillsdev/thecombine/587#-MEhJ3oAA_e6iXgNeyNF:-MEhJRzs7CsX6T4WNqXp:b-89d92h) ([raw file](https://github.com/sillsdev/thecombine/blob/31de26083b1227136c15ed23a216ff58f23e075a/Backend/Controllers/FrontierController.cs#L21)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

We've been trying to wrap the backend source lines at 120 columns so make it easier to review and read side by side. Unfortunately `dotnet-format` doesn't do this automatically (like Prettier does for our TS code) so we have to manually do this.
</blockquote></details>

Would it be possible to wrap these long lines at 120 characters?

**Comment by johnthagen** [comment]
___
*[Backend/Services/WordApiServices.cs, line 91 at r4](https://reviewable.io/reviews/sillsdev/thecombine/587#-MEhK5tdCyUaQtCiuQx_:-MEhK5tdCyUaQtCiuQxa:bpqlu0v) ([raw file](https://github.com/sillsdev/thecombine/blob/31de26083b1227136c15ed23a216ff58f23e075a/Backend/Services/WordApiServices.cs#L91)):*
> ```Smalltalk
>                 word.Id = "";
>                 word.ProjectId = projectId;
>                 word.Accessibility = 1;
> ```

Could the `enum` representation be used to to make this clearer?

```
word.Accessibility = (int)State.Deleted
```

**Comment by johnthagen** [comment]
___
*[Backend/Controllers/FrontierController.cs, line 98 at r4](https://reviewable.io/reviews/sillsdev/thecombine/587#-MEhL4t56t6II9d54xLh:-MEhL4t56t6II9d54xLi:b98yyw2) ([raw file](https://github.com/sillsdev/thecombine/blob/31de26083b1227136c15ed23a216ff58f23e075a/Backend/Controllers/FrontierController.cs#L98)):*
> ```Smalltalk
>             if (await _wordService.DeleteFrontierWord(projectId, wordId))
>             {
>                 return new OkObjectResult(true);
> ```

Is it okay that the success and error conditions return different types? A `boolean` vs a `string`?

**Comment by johnthagen** [comment]
___
*[Backend/Controllers/FrontierController.cs, line 98 at r4](https://reviewable.io/reviews/sillsdev/thecombine/587#-MEhL4t56t6II9d54xLh:-MEhLGecCOgZjkQT1MGp:b-u8s6kf) ([raw file](https://github.com/sillsdev/thecombine/blob/31de26083b1227136c15ed23a216ff58f23e075a/Backend/Controllers/FrontierController.cs#L98)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Is it okay that the success and error conditions return different types? A `boolean` vs a `string`?
</blockquote></details>

Looking at other examples, it looks like this happens elsewhere in the code, so maybe that's okay.

**Comment by johnthagen** [comment]
___
*[Backend/Models/Word.cs, line 35 at r4](https://reviewable.io/reviews/sillsdev/thecombine/587#-MEhLmcz411s_e1Sjhdc:-MEhLmcz411s_e1Sjhdd:bax9c01) ([raw file](https://github.com/sillsdev/thecombine/blob/31de26083b1227136c15ed23a216ff58f23e075a/Backend/Models/Word.cs#L35)):*
> ```Smalltalk
> 
>         [BsonElement("accessibility")]
>         public int Accessibility { get; set; }
> ```

This might be a breaking change at this point, but should we consider using `[JsonConverter(typeof(StringEnumConverter))]` for the `State` enum? I think this would lead to a more expressive API, and also reordering `enum` members wouldn't break the database mapping to `int`s. I think it would also allow us to remove all of the `(int)` casts when we update the `Accessibilty` of a `Model`.

This is currently done for the `AutocompleteSetting` `enum`.

**Comment by johnthagen** [comment]
___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/DeleteCell/DeleteCell.tsx, line 23 at r4](https://reviewable.io/reviews/sillsdev/thecombine/587#-MEhOjRn8mixkGQUnfxN:-MEhOjRn8mixkGQUnfxO:bnjr8fw) ([raw file](https://github.com/sillsdev/thecombine/blob/31de26083b1227136c15ed23a216ff58f23e075a/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/DeleteCell/DeleteCell.tsx#L23)):*
> ```XML
>   async deleteFrontierWord(wordId: string) {
>     await backend.deleteFrontierWord(wordId);
>     var updatedWords: ReviewEntriesWord[] = [];
> ```

Can declare this variable with `let` to limit scope.

**Comment by johnthagen** [comment]
___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/DeleteCell/DeleteCell.tsx, line 24 at r4](https://reviewable.io/reviews/sillsdev/thecombine/587#-MEhPOqe67JkLw-PENtV:-MEhPOqe67JkLw-PENtW:b-6xwzgq) ([raw file](https://github.com/sillsdev/thecombine/blob/31de26083b1227136c15ed23a216ff58f23e075a/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/DeleteCell/DeleteCell.tsx#L24)):*
> ```XML
>     await backend.deleteFrontierWord(wordId);
>     var updatedWords: ReviewEntriesWord[] = [];
>     for (var i = 0; i < this.props.words.length; i++) {
> ```

I think this loop could be simplified using a `for..of` loop:

```
    for (let word of this.props.words) {
      if (word.id !== wordId) {
        updatedWords.push(word);
      }
```

**Comment by johnthagen** [comment]
___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/tests/DomainCell.test.tsx, line 17 at r4](https://reviewable.io/reviews/sillsdev/thecombine/587#-MEhQHO2EjqzkfP3vxHM:-MEhQHO2EjqzkfP3vxHN:b-k3cc5y) ([raw file](https://github.com/sillsdev/thecombine/blob/31de26083b1227136c15ed23a216ff58f23e075a/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/tests/DomainCell.test.tsx#L17)):*
My editor shows a warning on this line:

> TS2741: Property 'sortingByDomains' is missing in type '{ rowData: ReviewEntriesWord; selectedDomain: SemanticDomain; }' but required in type 'Pick<ClassAttributes<DomainCell> & DomainCellProps, "ref" | "rowData" | "selectedDomain" | "sortingByDomains" | "editDomains" | "key">'.

But perhaps this can be safely ignored due to mocking?

**Comment by johnthagen** [comment]
In the Review Entries page, it seems like the Delete button has a grey outline around it when it shouldn't (not hovered or clicked):

delete_button

**Comment by johnthagen** [comment]
Found an issue deleting an word from the Data Entry. To reproduce:

1. Create a new project
2. Data Entry | Hot
3. Add new vernacular/gloss
4. Delete the row
5. Complete
6. Data Cleanup | Review Entries
7. Note that the deleted entry is shown (without its glosses) rather than not being shown

entry_not_deleted

**Comment by StevesBro** [comment]
___
*[Backend/Controllers/FrontierController.cs, line 21 at r4](https://reviewable.io/reviews/sillsdev/thecombine/587#-MEhJ3oAA_e6iXgNeyNF:-MEo0Kbb-bgBOuIQiLlX:b-tsh9uo) ([raw file](https://github.com/sillsdev/thecombine/blob/31de26083b1227136c15ed23a216ff58f23e075a/Backend/Controllers/FrontierController.cs#L21)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Would it be possible to wrap these long lines at 120 characters?
</blockquote></details>

Sure can

**Comment by StevesBro** [comment]
___
*[Backend/Controllers/FrontierController.cs, line 98 at r4](https://reviewable.io/reviews/sillsdev/thecombine/587#-MEhL4t56t6II9d54xLh:-MEo0sVoBVk7XuVUvTDC:b-wv8t2g) ([raw file](https://github.com/sillsdev/thecombine/blob/31de26083b1227136c15ed23a216ff58f23e075a/Backend/Controllers/FrontierController.cs#L98)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Looking at other examples, it looks like this happens elsewhere in the code, so maybe that's okay.
</blockquote></details>

I guess I could just return the wordId of the word in the database with the deleted tag

**Comment by StevesBro** [comment]
___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/tests/DomainCell.test.tsx, line 17 at r4](https://reviewable.io/reviews/sillsdev/thecombine/587#-MEhQHO2EjqzkfP3vxHM:-MEo6zZv1agkx97X4ToQ:bndyjvf) ([raw file](https://github.com/sillsdev/thecombine/blob/31de26083b1227136c15ed23a216ff58f23e075a/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/tests/DomainCell.test.tsx#L17)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

My editor shows a warning on this line:

> TS2741: Property 'sortingByDomains' is missing in type '{ rowData: ReviewEntriesWord; selectedDomain: SemanticDomain; }' but required in type 'Pick<ClassAttributes<DomainCell> & DomainCellProps, "ref" | "rowData" | "selectedDomain" | "sortingByDomains" | "editDomains" | "key">'.

But perhaps this can be safely ignored due to mocking?
</blockquote></details>

I believe that editor error already existed. I've seen it in several tests.

**Comment by StevesBro** [comment]
___
*[Backend/Models/Word.cs, line 35 at r4](https://reviewable.io/reviews/sillsdev/thecombine/587#-MEhLmcz411s_e1Sjhdc:-MEoDECP9E-CTWV_t1Pf:b-asr2h6) ([raw file](https://github.com/sillsdev/thecombine/blob/31de26083b1227136c15ed23a216ff58f23e075a/Backend/Models/Word.cs#L35)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This might be a breaking change at this point, but should we consider using `[JsonConverter(typeof(StringEnumConverter))]` for the `State` enum? I think this would lead to a more expressive API, and also reordering `enum` members wouldn't break the database mapping to `int`s. I think it would also allow us to remove all of the `(int)` casts when we update the `Accessibilty` of a `Model`.

This is currently done for the `AutocompleteSetting` `enum`.
</blockquote></details>

Great idea! I changed it and nothing obvious broke so that's a good sign.

**Comment by johnthagen** [comment]
___
*[Backend/Services/WordApiServices.cs, line 91 at r4](https://reviewable.io/reviews/sillsdev/thecombine/587#-MEhK5tdCyUaQtCiuQx_:-MEsF0Il2_PvF1ofzTWW:bb6ywmx) ([raw file](https://github.com/sillsdev/thecombine/blob/31de26083b1227136c15ed23a216ff58f23e075a/Backend/Services/WordApiServices.cs#L91)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Could the `enum` representation be used to to make this clearer?

```
word.Accessibility = (int)State.Deleted
```
</blockquote></details>

LGTM

**Comment by johnthagen** [comment]
___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/DeleteCell/DeleteCell.tsx, line 23 at r4](https://reviewable.io/reviews/sillsdev/thecombine/587#-MEhOjRn8mixkGQUnfxN:-MEsF80W2z5g0BwwUsn2:bb6ywmx) ([raw file](https://github.com/sillsdev/thecombine/blob/31de26083b1227136c15ed23a216ff58f23e075a/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/DeleteCell/DeleteCell.tsx#L23)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Can declare this variable with `let` to limit scope.
</blockquote></details>

LGTM

**Comment by johnthagen** [comment]
___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/DeleteCell/DeleteCell.tsx, line 24 at r4](https://reviewable.io/reviews/sillsdev/thecombine/587#-MEhPOqe67JkLw-PENtV:-MEsFCIkBLFr1McI0AUz:bb6ywmx) ([raw file](https://github.com/sillsdev/thecombine/blob/31de26083b1227136c15ed23a216ff58f23e075a/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/DeleteCell/DeleteCell.tsx#L24)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I think this loop could be simplified using a `for..of` loop:

```
    for (let word of this.props.words) {
      if (word.id !== wordId) {
        updatedWords.push(word);
      }
```
</blockquote></details>

LGTM

**Comment by johnthagen** [comment]
___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/tests/DomainCell.test.tsx, line 17 at r4](https://reviewable.io/reviews/sillsdev/thecombine/587#-MEhQHO2EjqzkfP3vxHM:-MEsFFeY8_k4bEVpV-jE:b32w0x) ([raw file](https://github.com/sillsdev/thecombine/blob/31de26083b1227136c15ed23a216ff58f23e075a/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/tests/DomainCell.test.tsx#L17)):*
<details><summary><i>Previously, StevesBro wrote…</i></summary><blockquote>

I believe that editor error already existed. I've seen it in several tests.
</blockquote></details>

OK

**Pull request merged**
