### PR TITLE
React router v5.1

### PR DESCRIPTION
**Pull request by jmgrady**
Update use of react-router to use features of version 5.1 in preparation of moving to v6.  The primary change was in the definition of the `<Route>` elements, changing from the form
```
<Route path={Path.PwRequest} component={PasswordRequest} />
```
to the form
```
<Route path={Path.PwRequest}>
  <PasswordRequest />
</Route>
```
When moving to this form, the `RouteComponentProps` are not passed as properties to the child components.
As a result, `ResetPage` and `ProjectInvite` needed to be changed from class components to functional components so that `useParams` can be used to extract the needed properties from the URL.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2227)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 39 of 44 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2227)* status: 39 of 44 files reviewed, 3 unresolved discussions (waiting on @jmgrady)

___
*[`src/components/App/component.tsx` line 12 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NWnBTsP7ms0wWk_jCQQ:-NWnBTsP7ms0wWk_jCQR:b-4pytww) ([raw file](https://github.com/sillsdev/TheCombine/blob/d85f8e1729cb7c66c887af9487b834971981351d/src/components/App/component.tsx#L12)):*
> ```XML
> import PageNotFound from "components/PageNotFound/component";
> import PasswordRequest from "components/PasswordReset/Request";
> import { PasswordReset } from "components/PasswordReset/ResetPage";
> ```

Why not make it the default export?
___
*[`src/components/PasswordReset/ResetPage.tsx` line 36 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NWnBD3y4sWQq0eCPF7D:-NWnBD3y4sWQq0eCPF7E:b-k3r42e) ([raw file](https://github.com/sillsdev/TheCombine/blob/d85f8e1729cb7c66c887af9487b834971981351d/src/components/PasswordReset/ResetPage.tsx#L36)):*
> ```XML
> }
> 
> export function PasswordReset(): ReactElement {
> ```

Might as well make this the default export.
___
*[`src/components/PasswordReset/tests/ResetPage.test.tsx` line 121 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NWnBiCH-E7AdbifKWsC:-NWnBiCH-E7AdbifKWsD:b-he1rlj) ([raw file](https://github.com/sillsdev/TheCombine/blob/d85f8e1729cb7c66c887af9487b834971981351d/src/components/PasswordReset/tests/ResetPage.test.tsx#L121)):*
> ```XML
>     // act(() => {
>     customRender(<PasswordReset />);
>     // });
> ```

Remove commented-out code.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2227)* status: 39 of 44 files reviewed, 4 unresolved discussions (waiting on @jmgrady)

___
*[`src/components/ProjectInvite.tsx` line 31 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NWnG-Al3sgWL5wrVlV8:-NWnG-Al3sgWL5wrVlV9:b-2m6unl) ([raw file](https://github.com/sillsdev/TheCombine/blob/d85f8e1729cb7c66c887af9487b834971981351d/src/components/ProjectInvite.tsx#L31)):*
> ```XML
>   isValidLink: boolean;
>   isAlreadyUser: boolean;
> }
> ```

`ProjectInviteState` no longer used.

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2227)* status: 40 of 44 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

___
*[`src/components/ProjectInvite.tsx` line 31 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NWnG-Al3sgWL5wrVlV8:-NWnHb8c1zt0dWBrxsZc:bss4a2b) ([raw file](https://github.com/sillsdev/TheCombine/blob/d85f8e1729cb7c66c887af9487b834971981351d/src/components/ProjectInvite.tsx#L31)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`ProjectInviteState` no longer used.
</blockquote></details>

Removed.
___
*[`src/components/ProjectInvite.tsx` line 60 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NWnH_2xA8yPX4QibDPz:-NWnJDS2A-GKB5oEn-2z:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/d85f8e1729cb7c66c887af9487b834971981351d/src/components/ProjectInvite.tsx#L60)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`: Promise<void> `
</blockquote></details>

Done.
___
*[`src/components/App/component.tsx` line 12 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NWnBTsP7ms0wWk_jCQQ:-NWnHdUM9xIzba_yIhdH:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/d85f8e1729cb7c66c887af9487b834971981351d/src/components/App/component.tsx#L12)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Why not make it the default export?
</blockquote></details>

Done.
___
*[`src/components/PasswordReset/ResetPage.tsx` line 36 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NWnBD3y4sWQq0eCPF7D:-NWnHltYBclO3rC1tiPM:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/d85f8e1729cb7c66c887af9487b834971981351d/src/components/PasswordReset/ResetPage.tsx#L36)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Might as well make this the default export.
</blockquote></details>

Done.
___
*[`src/components/PasswordReset/ResetPage.tsx` line 46 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NWnGoPHC35LjDuQW6DM:-NWnI4NC9TcVf03WI1Eq:bb6un1j) ([raw file](https://github.com/sillsdev/TheCombine/blob/d85f8e1729cb7c66c887af9487b834971981351d/src/components/PasswordReset/ResetPage.tsx#L46)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`: void `
</blockquote></details>

Done
___
*[`src/components/PasswordReset/ResetPage.tsx` line 51 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NWnGrsbD28It5Vvf2tf:-NWnICzN4C2tK5q9ImVB:bb6un1j) ([raw file](https://github.com/sillsdev/TheCombine/blob/d85f8e1729cb7c66c887af9487b834971981351d/src/components/PasswordReset/ResetPage.tsx#L51)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`: Promise<void> `
</blockquote></details>

Done
___
*[`src/components/PasswordReset/ResetPage.tsx` line 62 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NWnGxtO7ns2ypriv_En:-NWnIIbX1JbLqV-lhTqm:bb6un1j) ([raw file](https://github.com/sillsdev/TheCombine/blob/d85f8e1729cb7c66c887af9487b834971981351d/src/components/PasswordReset/ResetPage.tsx#L62)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`: void `
</blockquote></details>

Done
___
*[`src/components/PasswordReset/ResetPage.tsx` line 69 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NWnGzqS61hsE43VL19d:-NWnITdbCUy37hnlttmt:bb6un1j) ([raw file](https://github.com/sillsdev/TheCombine/blob/d85f8e1729cb7c66c887af9487b834971981351d/src/components/PasswordReset/ResetPage.tsx#L69)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`: Promise<void> `
</blockquote></details>

Done
___
*[`src/components/PasswordReset/ResetPage.tsx` line 79 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NWnH2r_8t2OH1nEohYK:-NWnIWwL4vfNxerscjDK:b-u3gbok) ([raw file](https://github.com/sillsdev/TheCombine/blob/d85f8e1729cb7c66c887af9487b834971981351d/src/components/PasswordReset/ResetPage.tsx#L79)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I've recently come to prefer `<>...</>` to `<div>...</div>`
</blockquote></details>

No problem.  I inherited this so my feelings aren't hurt. ;-)
Done.
___
*[`src/components/PasswordReset/tests/ResetPage.test.tsx` line 121 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NWnBiCH-E7AdbifKWsC:-NWnIxoD0EaUHX7Vcqb8:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/d85f8e1729cb7c66c887af9487b834971981351d/src/components/PasswordReset/tests/ResetPage.test.tsx#L121)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Remove commented-out code.
</blockquote></details>

Done.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2227)* status: 41 of 44 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`src/components/PasswordReset/ResetPage.tsx` line 82 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NWnRcne4BWmdAw81BiS:-NWnRcne4BWmdAw81BiT:b-aj63a3) ([raw file](https://github.com/sillsdev/TheCombine/blob/33e8df661e8504b6c18927fe1772fc6bb5c5a40d/src/components/PasswordReset/ResetPage.tsx#L82)):*
> ```XML
>   return (
>     <>
>       TextField
> ```

Extraneous "TextField". And without it, the `<>...</>` wrapper is unnecessary.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2227)* status: 101 of 107 files reviewed, 8 unresolved discussions (waiting on @jmgrady)

___
*[`src/components/PasswordReset/tests/ResetPage.test.tsx` line 35 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXFnVpg15x_7SqPIxNl:-NXFnVpg15x_7SqPIxNm:b-g6okg0) ([raw file](https://github.com/sillsdev/TheCombine/blob/dc7353c9e54f5293fb6164131ed9c785990af9b1/src/components/PasswordReset/tests/ResetPage.test.tsx#L35)):*
> ```XML
> 
> // This test relies on nothing in the store so mock an empty store
> const mockStore = configureMockStore([])();
> ```

The `[]` is unnecessary.
___
*[`src/components/PasswordReset/tests/ResetPage.test.tsx` line 43 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXFnZObBcl_nN790HW7:-NXFnZObBcl_nN790HW8:b9tvk7p) ([raw file](https://github.com/sillsdev/TheCombine/blob/dc7353c9e54f5293fb6164131ed9c785990af9b1/src/components/PasswordReset/tests/ResetPage.test.tsx#L43)):*
> ```XML
> afterEach(cleanup);
> 
> const ResetPageProviders = ({ children }: { children: React.ReactNode }) => {
> ```

`): ReactElement => {`
___
*[`src/components/PasswordReset/tests/ResetPage.test.tsx` line 46 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXFnexrBCTQnQDC4Aii:-NXFnexrBCTQnQDC4Aij:b-y40jfj) ([raw file](https://github.com/sillsdev/TheCombine/blob/dc7353c9e54f5293fb6164131ed9c785990af9b1/src/components/PasswordReset/tests/ResetPage.test.tsx#L46)):*
> ```XML
>   return (
>     <Provider store={mockStore}>
>       <MemoryRouter initialEntries={[`/forgot/reset/testPasswordReset`]}>
> ```

`/forgot/reset/testPasswordReset` -> `${Path.PwReset}/testPasswordReset`
___
*[`src/components/PasswordReset/tests/ResetPage.test.tsx` line 58 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXFoXr7AeDxWUrmg9Ue:-NXFoXr7AeDxWUrmg9Uf:b-do661m) ([raw file](https://github.com/sillsdev/TheCombine/blob/dc7353c9e54f5293fb6164131ed9c785990af9b1/src/components/PasswordReset/tests/ResetPage.test.tsx#L58)):*
> ```XML
>   ui: ReactElement,
>   options?: Omit<RenderOptions, "wrapper">
> ) => render(ui, { wrapper: ResetPageProviders, ...options });
> ```

`): RenderResult =>`
___
*[`src/components/PasswordReset/tests/ResetPage.test.tsx` line 71 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXFpCzPCNswsbjmqqf-:-NXFpCzPCNswsbjmqqf0:b-9ukn4k) ([raw file](https://github.com/sillsdev/TheCombine/blob/dc7353c9e54f5293fb6164131ed9c785990af9b1/src/components/PasswordReset/tests/ResetPage.test.tsx#L71)):*
> ```XML
>     );
> 
>     if (passwdField && passwdConfirm) {
> ```

Is this `if` necessary? Won't the `getByTestId` above simply throw an error if the items aren't found? (Same in the other tests.)
___
*[`src/components/PasswordReset/tests/ResetPage.test.tsx` line 144 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXFqTZH6IOFePxQTh1G:-NXFqTZH6IOFePxQTh1H:b-5y52ox) ([raw file](https://github.com/sillsdev/TheCombine/blob/dc7353c9e54f5293fb6164131ed9c785990af9b1/src/components/PasswordReset/tests/ResetPage.test.tsx#L144)):*
> ```XML
>   });
> 
>   // ------------------------------------------------------------
> ```

Is this dividing line significant?
___
*[`src/components/PasswordReset/tests/ResetPage.test.tsx` line 147 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXFqBIF0m1_tk7PzSOW:-NXFqBIF0m1_tk7PzSOX:b-ozeyoc) ([raw file](https://github.com/sillsdev/TheCombine/blob/dc7353c9e54f5293fb6164131ed9c785990af9b1/src/components/PasswordReset/tests/ResetPage.test.tsx#L147)):*
> ```XML
> 
>   it("renders with expire error", async () => {
>     await act(async () => {
> ```

Since this `act` isn't necessary in the other tests, it seems we only need it wrapping the `user.click` below.

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2227)* status: 101 of 107 files reviewed, 3 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

*[a discussion](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXFlrML99giL1r-pUqW:-NXFwNsmCaRo4dAmuBNZ:bhasbxg) (no related file):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Nice work on the "invalid token" page for the invite page. Could you add one for the password reset page as well?
</blockquote></details>

An issue has been created to track this.  See issue #2247 (Check password reset token before user attempts to reset his/her password)

___
___
*[`src/components/PasswordReset/tests/ResetPage.test.tsx` line 35 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXFnVpg15x_7SqPIxNl:-NXFwyl7Daa2SXtgVCNY:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/dc7353c9e54f5293fb6164131ed9c785990af9b1/src/components/PasswordReset/tests/ResetPage.test.tsx#L35)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

The `[]` is unnecessary.
</blockquote></details>

Done.
___
*[`src/components/PasswordReset/tests/ResetPage.test.tsx` line 43 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXFnZObBcl_nN790HW7:-NXFxNeZ0Sx-oO95Xsln:bb6un1j) ([raw file](https://github.com/sillsdev/TheCombine/blob/dc7353c9e54f5293fb6164131ed9c785990af9b1/src/components/PasswordReset/tests/ResetPage.test.tsx#L43)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`): ReactElement => {`
</blockquote></details>

Done
___
*[`src/components/PasswordReset/tests/ResetPage.test.tsx` line 46 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXFnexrBCTQnQDC4Aii:-NXFxOaG4HSa83eewEt1:bb6un1j) ([raw file](https://github.com/sillsdev/TheCombine/blob/dc7353c9e54f5293fb6164131ed9c785990af9b1/src/components/PasswordReset/tests/ResetPage.test.tsx#L46)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`/forgot/reset/testPasswordReset` -> `${Path.PwReset}/testPasswordReset`
</blockquote></details>

Done
___
*[`src/components/PasswordReset/tests/ResetPage.test.tsx` line 58 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXFoXr7AeDxWUrmg9Ue:-NXFxWm-C9YrDYUZ4NEu:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/dc7353c9e54f5293fb6164131ed9c785990af9b1/src/components/PasswordReset/tests/ResetPage.test.tsx#L58)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`): RenderResult =>`
</blockquote></details>

Done.
___
*[`src/components/PasswordReset/tests/ResetPage.test.tsx` line 71 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXFpCzPCNswsbjmqqf-:-NXFxzIRAHDh6grtJTSE:b-d1f8h6) ([raw file](https://github.com/sillsdev/TheCombine/blob/dc7353c9e54f5293fb6164131ed9c785990af9b1/src/components/PasswordReset/tests/ResetPage.test.tsx#L71)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Is this `if` necessary? Won't the `getByTestId` above simply throw an error if the items aren't found? (Same in the other tests.)
</blockquote></details>

Correct.  `if` statements removed.
___
*[`src/components/PasswordReset/tests/ResetPage.test.tsx` line 144 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXFqTZH6IOFePxQTh1G:-NXFyOeVA-15-rwg9Isp:bci5ts9) ([raw file](https://github.com/sillsdev/TheCombine/blob/dc7353c9e54f5293fb6164131ed9c785990af9b1/src/components/PasswordReset/tests/ResetPage.test.tsx#L144)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Is this dividing line significant?
</blockquote></details>

They were there from before.  I did not look at other tests and assumed they are preferred for our tests.
___
*[`src/components/PasswordReset/tests/ResetPage.test.tsx` line 147 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXFqBIF0m1_tk7PzSOW:-NXG-C2HCgLDHg8YoIWf:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/dc7353c9e54f5293fb6164131ed9c785990af9b1/src/components/PasswordReset/tests/ResetPage.test.tsx#L147)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Since this `act` isn't necessary in the other tests, it seems we only need it wrapping the `user.click` below.
</blockquote></details>

Done.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 2 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2227)* status: 103 of 107 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

___
*[`src/components/PasswordReset/tests/ResetPage.test.tsx` line 71 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXFpCzPCNswsbjmqqf-:-NXG2GPbE7zpbEaJI9oO:bc1enyf) ([raw file](https://github.com/sillsdev/TheCombine/blob/dc7353c9e54f5293fb6164131ed9c785990af9b1/src/components/PasswordReset/tests/ResetPage.test.tsx#L71)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Correct.  `if` statements removed.
</blockquote></details>

All except this one.
___
*[`src/components/PasswordReset/tests/ResetPage.test.tsx` line 144 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXFqTZH6IOFePxQTh1G:-NXG24T44p0UtnSNXwvz:bqlhj0m) ([raw file](https://github.com/sillsdev/TheCombine/blob/dc7353c9e54f5293fb6164131ed9c785990af9b1/src/components/PasswordReset/tests/ResetPage.test.tsx#L144)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

They were there from before.  I did not look at other tests and assumed they are preferred for our tests.
</blockquote></details>

This is the only frontend file with a long `--------------------` divider. A new/sub `describe` is preferred where distinguishing test groups.

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2227)* status: 103 of 107 files reviewed, all discussions resolved (waiting on @imnasnainaec and @jmgrady)

___
*[`src/components/PasswordReset/tests/ResetPage.test.tsx` line 71 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXFpCzPCNswsbjmqqf-:-NXG62tg7zWG4llrmTWV:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/dc7353c9e54f5293fb6164131ed9c785990af9b1/src/components/PasswordReset/tests/ResetPage.test.tsx#L71)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

All except this one.
</blockquote></details>

Done.
___
*[`src/components/PasswordReset/tests/ResetPage.test.tsx` line 144 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXFqTZH6IOFePxQTh1G:-NXG68ON1hfLl6Oj7xh1:bj53s51) ([raw file](https://github.com/sillsdev/TheCombine/blob/dc7353c9e54f5293fb6164131ed9c785990af9b1/src/components/PasswordReset/tests/ResetPage.test.tsx#L144)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

This is the only frontend file with a long `--------------------` divider. A new/sub `describe` is preferred where distinguishing test groups.
</blockquote></details>

Dividing line removed.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2227)* status: 104 of 107 files reviewed, 4 unresolved discussions (waiting on @jmgrady)

___
*[`src/components/PasswordReset/ResetPage.tsx` line 16 at r9](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXG5J8N6X4pIimX8uIn:-NXG5J8N6X4pIimX8uIo:brook62) ([raw file](https://github.com/sillsdev/TheCombine/blob/ac04b69e43243f32a5d6f5220b0ae2657249a9a3/src/components/PasswordReset/ResetPage.tsx#L16)):*
> ```XML
> 
> interface ResetDispatchProps {
>   passwordReset: (token: string, password: string) => void;
> ```

Unused interface.
___
*[`src/components/PasswordReset/ResetPage.tsx` line 37 at r9](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXG6UCW1qakG80MlHBz:-NXG6UCW1qakG80MlHC-:blm90jd) ([raw file](https://github.com/sillsdev/TheCombine/blob/ac04b69e43243f32a5d6f5220b0ae2657249a9a3/src/components/PasswordReset/ResetPage.tsx#L37)):*
> ```XML
> 
> export default function PasswordReset(): ReactElement {
>   const { token }: MatchParams = useParams();
> ```

I wonder if `const { token } = useParams<MatchParams>();` might be more Typescripty.... Typescriptic... Typescryptic?
___
*[`src/components/ProjectInvite/ProjectInvite.tsx` line 47 at r9](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXG3nZl32QTXBdshVIV:-NXG3nZl32QTXBdshVIW:b-ox1t4i) ([raw file](https://github.com/sillsdev/TheCombine/blob/ac04b69e43243f32a5d6f5220b0ae2657249a9a3/src/components/ProjectInvite/ProjectInvite.tsx#L47)):*
> ```XML
> 
>     if (status.isTokenValid && status.isUserRegistered) {
>       history.push(Path.Login);
> ```

Might as well move this check up to avoid unnecessary state-setting. (...or extract it as a `useEffect` with deps `[isAlreadyUser, isValidLink]`, but that's more work.)
___
*[`src/components/ProjectInvite/ProjectInvite.tsx` line 55 at r9](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXG4_O31DTvSJJ7RqV0:-NXG4_O31DTvSJJ7RqV1:bjlpk7j) ([raw file](https://github.com/sillsdev/TheCombine/blob/ac04b69e43243f32a5d6f5220b0ae2657249a9a3/src/components/ProjectInvite/ProjectInvite.tsx#L55)):*
> ```XML
> 
>   useEffect(() => {
>     validateLink().then();
> ```

Since `validateLink` doesn't return anything (but does all the state updates internally), this `.then()` is unnecessary.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2227)* status: 105 of 107 files reviewed, 4 unresolved discussions (waiting on @jmgrady)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2227)* status: 105 of 107 files reviewed, 5 unresolved discussions (waiting on @jmgrady)

___
*[`src/components/ProjectInvite/ProjectInvite.tsx` line 43 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXGA-zT7170ob7tIoX5:-NXGA-zT7170ob7tIoX6:b-ifto1s) ([raw file](https://github.com/sillsdev/TheCombine/blob/3da8b8d228a79506e1caf8faec9e4dc437e8ac85/src/components/ProjectInvite/ProjectInvite.tsx#L43)):*
> ```XML
>     }
>     if (status.isUserRegistered) {
>       setIsAlreadyUser(true);
> ```

These could be shortened to `setIsValidLink(status.isTokenValid)` and `setIsAlreadyUser(status.isUserRegistered)` without `if` checks, since the component won't re-render if the state doesn't change, but if that feels less clear, it can be left as is.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2227)* status: 105 of 107 files reviewed, 5 unresolved discussions (waiting on @jmgrady)

___
*[`src/components/ProjectInvite/ProjectInvite.tsx` line 47 at r9](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXG3nZl32QTXBdshVIV:-NXGBnCU4dnB1Es7offv:b-lavfuk) ([raw file](https://github.com/sillsdev/TheCombine/blob/ac04b69e43243f32a5d6f5220b0ae2657249a9a3/src/components/ProjectInvite/ProjectInvite.tsx#L47)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Might as well move this check up to avoid unnecessary state-setting. (...or extract it as a `useEffect` with deps `[isAlreadyUser, isValidLink]`, but that's more work.)
</blockquote></details>

If you move it up, it may need a `return;` added to avoid trying to set the state on an unmounted component.

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2227)* status: 104 of 107 files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[`src/components/PasswordReset/ResetPage.tsx` line 16 at r9](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXG5J8N6X4pIimX8uIn:-NXG9c8m-6k6ChafYl4o:bsgqv6k) ([raw file](https://github.com/sillsdev/TheCombine/blob/ac04b69e43243f32a5d6f5220b0ae2657249a9a3/src/components/PasswordReset/ResetPage.tsx#L16)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Unused interface.
</blockquote></details>

Done.  Interface removed.
___
*[`src/components/PasswordReset/ResetPage.tsx` line 37 at r9](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXG6UCW1qakG80MlHBz:-NXG9nvxBcCoR8Y3j07v:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/ac04b69e43243f32a5d6f5220b0ae2657249a9a3/src/components/PasswordReset/ResetPage.tsx#L37)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I wonder if `const { token } = useParams<MatchParams>();` might be more Typescripty.... Typescriptic... Typescryptic?
</blockquote></details>

Done.
___
*[`src/components/ProjectInvite/ProjectInvite.tsx` line 47 at r9](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXG3nZl32QTXBdshVIV:-NXG95CD8M-ZnY_fwpvX:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/ac04b69e43243f32a5d6f5220b0ae2657249a9a3/src/components/ProjectInvite/ProjectInvite.tsx#L47)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Might as well move this check up to avoid unnecessary state-setting. (...or extract it as a `useEffect` with deps `[isAlreadyUser, isValidLink]`, but that's more work.)
</blockquote></details>

Done.
___
*[`src/components/ProjectInvite/ProjectInvite.tsx` line 55 at r9](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXG4_O31DTvSJJ7RqV0:-NXG96bj2lBQvgwZ-q9D:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/ac04b69e43243f32a5d6f5220b0ae2657249a9a3/src/components/ProjectInvite/ProjectInvite.tsx#L55)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Since `validateLink` doesn't return anything (but does all the state updates internally), this `.then()` is unnecessary.
</blockquote></details>

Done.
___
*[`src/components/ProjectInvite/ProjectInvite.tsx` line 43 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXGA-zT7170ob7tIoX5:-NXGBtiRAPgjFrR6Z5vV:b-kg72i) ([raw file](https://github.com/sillsdev/TheCombine/blob/3da8b8d228a79506e1caf8faec9e4dc437e8ac85/src/components/ProjectInvite/ProjectInvite.tsx#L43)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

These could be shortened to `setIsValidLink(status.isTokenValid)` and `setIsAlreadyUser(status.isUserRegistered)` without `if` checks, since the component won't re-render if the state doesn't change, but if that feels less clear, it can be left as is.
</blockquote></details>

I like this.
Done.

More importantly, the page _will_ re-render if either of the states transition from `true` to `false`.  We miss these cases in the previous implementations.  They are unlikely scenarios but they could happen.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 3 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2227)* status: 106 of 107 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[`src/components/PasswordReset/ResetPage.tsx` line 37 at r9](https://reviewable.io/reviews/sillsdev/TheCombine/2227#-NXG6UCW1qakG80MlHBz:-NXGDv8v5vfSYmZoHfRk:buqvv93) ([raw file](https://github.com/sillsdev/TheCombine/blob/ac04b69e43243f32a5d6f5220b0ae2657249a9a3/src/components/PasswordReset/ResetPage.tsx#L37)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It's unchanged.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2227)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Pull request merged**
