### PR TITLE
Retire State.Sense, which was used somewhat redundantly to State.Active.

### LINKED ISSUE #1189: [MergeDuplicates] Clear up confusion between State.Active, State.Sense
The default `accessiblity` of a sense is `State.Active`, but `State.Sense` is used as the primary state during merging. A change in #1136 blurred the lines between the two, resulting in some post-merge words in the database having senses marked `State.Sense` instead of `State.Active`.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Follow-up to #1136 
Fixes #1189

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1190)

### CODE REVIEW

**Comment by imnasnainaec** [comment]
@jmgrady This causes problems if there are any Senses in the database with `State.Sense`. That shouldn't be an issue on the live server, since #1136 is yet to be released, but may cause issues on the qa server.

**Comment by imnasnainaec** [comment]
@jmgrady There are senses on the qa-server with `State.Sense`:
```
> db.WordsCollection.find({ senses : { $elemMatch : { accessibility : "Sense"}}}).length()
167
```
So before this is merged, we'll want to replace every `{ accessibility : "Sense"}` with `{ accessibility : "Active"}` on both the qa and live servers.

**Comment by imnasnainaec** [comment]
Accomplished locally by running the following commands multiple times:
```
> db.WordsCollection.update({ senses : { $elemMatch : { accessibility: "Sense"}}}, { $set : { "senses.$.accessibility" : "Active" }}, { multi: true})
> db.FrontierCollection.update({ senses : { $elemMatch : { accessibility: "Sense"}}}, { $set : { "senses.$.accessibility" : "Active" }}, { multi: true})
```

**Comment by jmgrady** [comment]
> Accomplished locally by running the following commands multiple times:
> 
> ```
> > db.WordsCollection.update({ senses : { $elemMatch : { accessibility: "Sense"}}}, { $set : { "senses.$.accessibility" : "Active" }}, { multi: true})
> > db.FrontierCollection.update({ senses : { $elemMatch : { accessibility: "Sense"}}}, { $set : { "senses.$.accessibility" : "Active" }}, { multi: true})
> ```

@imnasnainaec  I ran this on the qa server.  See if it impacts the export issues you saw.  Also, I ran the following variation of the commands:
```
db.WordsCollection.updateMany({ senses : { $elemMatch : { accessibility: "Sense"}}}, { $set : { "senses.$.accessibility" : "Active" }})
db.FrontierCollection.updateMany({ senses : { $elemMatch : { accessibility: "Sense"}}}, { $set : { "senses.$.accessibility" : "Active" }})
```
based on replies 2 & 3 of this [StackOverflow Post](https://stackoverflow.com/questions/36719331/what-is-the-difference-between-update-and-updatemany-method-in-mongo-db/46348284).

**Review by johnthagen — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1190)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Review by johnthagen — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1190#-:-Md2rmrECYhHJTX-ffpb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Pull request merged**
