### PR TITLE
Clean Untagged Images from AWS Container Registry

### PR DESCRIPTION
**Pull request by jmgrady**
Update deploy/bin/clean-repo.py to be able to handle untagged images in the AWS Container Registry.  By default, untagged images are not removed.  If the `--untagged` option is specified, all untagged images will be removed, including `latest`.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1007)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[deploy/bin/clean_repo.py, line 145 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1007#-MTLJ0UiD5cb2SG31VvO:-MTLJ0UiD5cb2SG31VvP:bd05jr) ([raw file](https://github.com/sillsdev/thecombine/blob/cc7d29942c01cb711b0fac2bb638325039e5848c/deploy/bin/clean_repo.py#L145)):*
> ```Python
>             if args.untagged:
>                 image_ids.append(f'imageDigest={image_struct["imageDigest"]}')
>     # Remove all the specified image(s) in blocks of 100 (AWS limit)
> ```

Can remove the duplicated `100` magic value this way:

```py
    # Remove all the specified image(s) in blocks within AWS limit
    if len(image_ids) > 0:
        aws_delete_limit = 100
        for i in range(0, len(image_ids), aws_delete_limit):
            aws_cmd = build_aws_cmd(
                args.profile,
                args.repo,
                "batch-delete-image",
                ["--image-ids"] + image_ids[i : i + aws_delete_limit],
            )
```

**Comment by johnthagen** [comment]
___
*[deploy/bin/clean_repo.py, line 76 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1007#-MTLJeyx9UiaECJqlqtV:-MTLJeyx9UiaECJqlqtW:bmv2nh1) ([raw file](https://github.com/sillsdev/thecombine/blob/cc7d29942c01cb711b0fac2bb638325039e5848c/deploy/bin/clean_repo.py#L76)):*
> ```Python
>             for fragment in result_fragments:
>                 if fragment == result_fragments[0]:
>                     print(f"STDOUT: {fragment}")
> ```

Below we print this at `stdout:`

**Comment by johnthagen** [comment]
___
*[deploy/bin/clean_repo.py, line 79 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1007#-MTLJhnh3WADHHJyTqwQ:-MTLJhnh3WADHHJyTqwR:b-tvz0va) ([raw file](https://github.com/sillsdev/thecombine/blob/cc7d29942c01cb711b0fac2bb638325039e5848c/deploy/bin/clean_repo.py#L79)):*
> ```Python
>                 else:
>                     print(f"\t{fragment}")
>             print(f"STDERR: {aws_results.stderr}")
> ```

Below we print this as `stderr:`. Could make these all match for consistency.

**Comment by johnthagen** [comment]
___
*[deploy/bin/clean_repo.py, line 66 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1007#-MTLKEjUEkyUwsL_HB9p:-MTLKEjUEkyUwsL_HB9q:b7fzr20) ([raw file](https://github.com/sillsdev/thecombine/blob/cc7d29942c01cb711b0fac2bb638325039e5848c/deploy/bin/clean_repo.py#L66)):*
> ```Python
>         aws_results = subprocess.run(
>             aws_cmd,
>             stdin=None,
> ```

According to the docs (https://docs.python.org/3/library/subprocess.html#subprocess.run) `stdin=None` is the default parameter value and is redundant.

**Review by johnthagen — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1007)* status: all files reviewed, 4 unresolved discussions (waiting on @jmgrady)

**Comment by johnthagen** [comment]
___
*[deploy/bin/clean_repo.py, line 145 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1007#-MTLJ0UiD5cb2SG31VvO:-MTLKjQ27pTlWF5nR9Dd:bk5volo) ([raw file](https://github.com/sillsdev/thecombine/blob/cc7d29942c01cb711b0fac2bb638325039e5848c/deploy/bin/clean_repo.py#L145)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Can remove the duplicated `100` magic value this way:

```py
    # Remove all the specified image(s) in blocks within AWS limit
    if len(image_ids) > 0:
        aws_delete_limit = 100
        for i in range(0, len(image_ids), aws_delete_limit):
            aws_cmd = build_aws_cmd(
                args.profile,
                args.repo,
                "batch-delete-image",
                ["--image-ids"] + image_ids[i : i + aws_delete_limit],
            )
```
</blockquote></details>

As a comment above `aws_delete_limit` could we add a link to the AWS docs where this is documented. As a new developer looking at this code, I wouldn't immediately know how I would have learned about this limit.

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1007)* status: all files reviewed, 4 unresolved discussions (waiting on @johnthagen)

___
*[deploy/bin/clean_repo.py, line 66 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1007#-MTLKEjUEkyUwsL_HB9p:-MTLSwBC6j_FedVnr0Fy:b-5qashd) ([raw file](https://github.com/sillsdev/thecombine/blob/cc7d29942c01cb711b0fac2bb638325039e5848c/deploy/bin/clean_repo.py#L66)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

According to the docs (https://docs.python.org/3/library/subprocess.html#subprocess.run) `stdin=None` is the default parameter value and is redundant.
</blockquote></details>

Done.
I had added that even though it was the default because the script ran fine from a terminal but not from TeamCity.  I found the real problem and forgot to remove this.
___
*[deploy/bin/clean_repo.py, line 76 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1007#-MTLJeyx9UiaECJqlqtV:-MTLTihXCUYxQpAS5ynF:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/cc7d29942c01cb711b0fac2bb638325039e5848c/deploy/bin/clean_repo.py#L76)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Below we print this at `stdout:`
</blockquote></details>

Done.
___
*[deploy/bin/clean_repo.py, line 79 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1007#-MTLJhnh3WADHHJyTqwQ:-MTLTj7p37_Sy7bwyHVj:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/cc7d29942c01cb711b0fac2bb638325039e5848c/deploy/bin/clean_repo.py#L79)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Below we print this as `stderr:`. Could make these all match for consistency.
</blockquote></details>

Done.
___
*[deploy/bin/clean_repo.py, line 145 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1007#-MTLJ0UiD5cb2SG31VvO:-MTLYLZn33SxMygiMoIO:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/cc7d29942c01cb711b0fac2bb638325039e5848c/deploy/bin/clean_repo.py#L145)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

As a comment above `aws_delete_limit` could we add a link to the AWS docs where this is documented. As a new developer looking at this code, I wouldn't immediately know how I would have learned about this limit.
</blockquote></details>

Done.

**Review by johnthagen — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1007)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
