### PR TITLE
Setup kubernetes

### PR DESCRIPTION
**Pull request by jmgrady**
This PR implements the initial _Ansible_ playbooks for installing and configuring _The Combine_ to run in a Kubernetes cluster.  It has been verified with the following steps:
1. Create a new AWS EC2 instance based on Ubuntu 20.04; update all packages;
2. Create a `dev.hosts.yml` file to configure the target to include `microk8s` and `cert_manager`;
3. Run `setup/docker_build.py` to build the new docker images and push them to AWS ECR with a specified tag;
4. Run the `deploy/playbook_kube_install.yml` playbook to install the kubernetes environment;
5. Run the `deploy/playbook_kube_config.yml` playbook to configure the kubernetes resources and start the deployments;
6. Open a web browser and navigate to the DNS name for the AWS EC2 instance and verify basic operation:
   1. connection is secure (valid SSL certificate)
   2. new user can be registered (communication with the backend and database)
   3. import project
   4. review entries of imported project
   5. open and browse User Guide pages
7. Installed _The Combine_ running in the docker-compose environment on a fresh installation of Ubuntu 20.04 to verify that the existing deployment model still works.

The following functions are not yet implemented in the Kubernetes environment:
- `aws-ecr-credential` manager
- Development test environment
- Store NUC certificates in an AWS S3 bucket;
- Retrieve NUC certificates from an AWS S3 bucket;
- Maintenance functions:
   - backup/restore
   - remove a project
   - add a user to a project
   - clean out old backups from AWS S3

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1177)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[Dockerfile, line 1 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1177#-MekMtzB7lxsvGMtoakC:-MekMtzB7lxsvGMtoakD:byx1a40) ([raw file](https://github.com/sillsdev/thecombine/blob/ddf0beca558b6693f1cbceaab64ad01bb76d87b2/Dockerfile#L1)):*
> ```Dockerfile
> 
> ```

Probably don't need this, just to keep the diff smaller.

**Comment by johnthagen** [comment]
___
*[scripts/development_config.py, line 4 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1177#-MekO1Dl8Kv9yPjzpzAW:-MekO1Dl8Kv9yPjzpzAX:bv9f4r6) ([raw file](https://github.com/sillsdev/thecombine/blob/ddf0beca558b6693f1cbceaab64ad01bb76d87b2/scripts/development_config.py#L4)):*
> ```Python
> Create a common definition of project configuration items.
> 
> Define the configuration items for the Docker Compose and Kubernetes set
> ```

It doesn't seem that the `docker_setup.py` script (what generates Compose config) uses this yet. Were you intending it to also pull from here?

**Comment by johnthagen** [comment]
___
*[scripts/kube_setup.py, line 6 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1177#-MekPsSg435FOzTxhZlc:-MekPsSg435FOzTxhZld:bsgvuaz) ([raw file](https://github.com/sillsdev/thecombine/blob/ddf0beca558b6693f1cbceaab64ad01bb76d87b2/scripts/kube_setup.py#L6)):*
> ```Python
> Create YAML files needed to run TheCombine in Kubernetes environment in development.
> 
> This script sets up your development environment to be able to run
> ```

Could we add what the external requirements are for the generated YAML files to be usable? e.g. microk8s, enabling Kubernetes support in Docker Desktop, etc.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 9 of 49 files at r2, 16 of 62 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1177)* status: 25 of 83 files reviewed, 3 unresolved discussions (waiting on @jmgrady)

**Comment by johnthagen** [comment]
___
*[deploy/playbook_kube_config.yml, line 13 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1177#-MekQumFE2kFQqlVRvNI:-MekQumFE2kFQqlVRvNJ:brjuj6z) ([raw file](https://github.com/sillsdev/thecombine/blob/ddf0beca558b6693f1cbceaab64ad01bb76d87b2/deploy/playbook_kube_config.yml#L13)):*
> ```YAML
>   hosts: server,qa,nuc
>   become: no
>   #  gather_facts: yes
> ```

Should this dead code be removed?

**Comment by johnthagen** [comment]
___
*[deploy/roles/docker_install/defaults/main.yml, line 5 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1177#-MekRZraAC0W5fmmbcU7:-MekRZraAC0W5fmmbcU8:bxlz2ps) ([raw file](https://github.com/sillsdev/thecombine/blob/ddf0beca558b6693f1cbceaab64ad01bb76d87b2/deploy/roles/docker_install/defaults/main.yml#L5)):*
> ```YAML
> credential_helper_version: v0.6.3
> 
> # Kubernetes/minikube is validated on Docker 19.03.x
> ```

Could you explain this comment? Does this mean 19.03.x and newer (`19.03+`) or only in that specific version?

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 2 of 48 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1177)* status: 27 of 83 files reviewed, 5 unresolved discussions (waiting on @jmgrady)

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 2 of 62 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1177)* status: 29 of 83 files reviewed, 5 unresolved discussions (waiting on @jmgrady)

___
*[deploy/roles/network_config/tasks/main.yml, line 40 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1177#-MekSkiB7JTz-x4jMJdh:-MekSkiB7JTz-x4jMJdi:b-9zd5m8) ([raw file](https://github.com/sillsdev/thecombine/blob/ddf0beca558b6693f1cbceaab64ad01bb76d87b2/deploy/roles/network_config/tasks/main.yml#L40)):*
> ```
>   when:
>     - '"microk8s" in k8s_components'
> ```
This is a one-liner `  when: '"microk8s" in k8s_components'` elsewhere.

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1177)* status: 29 of 83 files reviewed, 4 unresolved discussions (waiting on @jmgrady and @johnthagen)

___
*[Dockerfile, line 1 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1177#-MekMtzB7lxsvGMtoakC:-MekUO1C10hjw_yH_hw7:b-a2ezqz) ([raw file](https://github.com/sillsdev/thecombine/blob/ddf0beca558b6693f1cbceaab64ad01bb76d87b2/Dockerfile#L1)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Probably don't need this, just to keep the diff smaller.
</blockquote></details>

I added the blank line because Atom was complaining about a syntax error in the Dockerfile.  I prefer to use Atom since I find its Git interface much easier to use.

As I write this, I realize that the reason it is complaining about the comment is that I have the shebang-set-grammar package installed and it is saying that the syntax for the shebang is incorrect.

I can turn off the package when I am not using it but I would prefer to keep it enabled if you don't mind.
___
*[deploy/playbook_kube_config.yml, line 13 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1177#-MekQumFE2kFQqlVRvNI:-MekX4p15oTQa_CgiOoN:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/ddf0beca558b6693f1cbceaab64ad01bb76d87b2/deploy/playbook_kube_config.yml#L13)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Should this dead code be removed?
</blockquote></details>

Done.
___
*[deploy/roles/docker_install/defaults/main.yml, line 5 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1177#-MekRZraAC0W5fmmbcU7:-MekXBDBEX0N0ImMC1U0:breerx1) ([raw file](https://github.com/sillsdev/thecombine/blob/ddf0beca558b6693f1cbceaab64ad01bb76d87b2/deploy/roles/docker_install/defaults/main.yml#L5)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Could you explain this comment? Does this mean 19.03.x and newer (`19.03+`) or only in that specific version?
</blockquote></details>

According to https://kubernetes.io/docs/setup/production-environment/container-runtimes/, Docker 20.10 has now been validated.  I have created issue #1256  to update this in a future PR (so that I can do adequate testing).
___
*[deploy/roles/network_config/tasks/main.yml, line 40 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1177#-MekSkiB7JTz-x4jMJdh:-MekYM2j81QLSfyrvcQI:bzakwk0) ([raw file](https://github.com/sillsdev/thecombine/blob/ddf0beca558b6693f1cbceaab64ad01bb76d87b2/deploy/roles/network_config/tasks/main.yml#L40)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>   when:
>     - '"microk8s" in k8s_components'
> ```
This is a one-liner `  when: '"microk8s" in k8s_components'` elsewhere.
</blockquote></details>

They are equivalent.  I will change it for consistency. Done.
___
*[scripts/development_config.py, line 4 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1177#-MekO1Dl8Kv9yPjzpzAW:-MekZ6e335shKAdL103H:b2wwrwz) ([raw file](https://github.com/sillsdev/thecombine/blob/ddf0beca558b6693f1cbceaab64ad01bb76d87b2/scripts/development_config.py#L4)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

It doesn't seem that the `docker_setup.py` script (what generates Compose config) uses this yet. Were you intending it to also pull from here?
</blockquote></details>

I was intending to do that in a future PR (it's an interim PR for the Kubernetes deployment).  Now that Kubernetes works with no ethernet, perhaps this is not needed at all.
___
*[scripts/kube_setup.py, line 6 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1177#-MekPsSg435FOzTxhZlc:-MekZVb46CZfPhKAhKWK:b-svb5ul) ([raw file](https://github.com/sillsdev/thecombine/blob/ddf0beca558b6693f1cbceaab64ad01bb76d87b2/scripts/kube_setup.py#L6)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Could we add what the external requirements are for the generated YAML files to be usable? e.g. microk8s, enabling Kubernetes support in Docker Desktop, etc.
</blockquote></details>

This file is a work-in-progress and has not been tested yet.  I will add those instructions to the README.md.

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1177)* status: 29 of 83 files reviewed, 4 unresolved discussions (waiting on @jmgrady and @johnthagen)

___
*[scripts/kube_setup.py, line 6 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1177#-MekPsSg435FOzTxhZlc:-Mek_R1R7eua_IGiFOuj:bbqt92e) ([raw file](https://github.com/sillsdev/thecombine/blob/ddf0beca558b6693f1cbceaab64ad01bb76d87b2/scripts/kube_setup.py#L6)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

This file is a work-in-progress and has not been tested yet.  I will add those instructions to the README.md.
</blockquote></details>

(when the script is usable.)

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1177)* status: 30 of 83 files reviewed, 4 unresolved discussions (waiting on @jmgrady and @johnthagen)

**Comment by johnthagen** [comment]
___
*[Dockerfile, line 1 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1177#-MekMtzB7lxsvGMtoakC:-MeksNnb8RVMIorL3k2l:b-ud16hx) ([raw file](https://github.com/sillsdev/thecombine/blob/ddf0beca558b6693f1cbceaab64ad01bb76d87b2/Dockerfile#L1)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

I added the blank line because Atom was complaining about a syntax error in the Dockerfile.  I prefer to use Atom since I find its Git interface much easier to use.

As I write this, I realize that the reason it is complaining about the comment is that I have the shebang-set-grammar package installed and it is saying that the syntax for the shebang is incorrect.

I can turn off the package when I am not using it but I would prefer to keep it enabled if you don't mind.
</blockquote></details>

Yes, that sounds fine.

**Comment by johnthagen** [comment]
___
*[deploy/roles/k8s_cert_manager/tasks/install.yml, line 3 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1177#-MekxhZkC9pu9aKnj2Fm:-MekxhZkC9pu9aKnj2Fn:b62t533) ([raw file](https://github.com/sillsdev/thecombine/blob/f556d98fbf6e728bf08f74719a2e06e35366dd11/deploy/roles/k8s_cert_manager/tasks/install.yml#L3)):*
> ```YAML
> ---
> - name: Install cert-manager and CustomResourceDefinitions
>   command: kubectl --kubeconfig=kubeconfig apply -f https://github.com/jetstack/cert-manager/releases/download/{{ cert_manager_version }}/cert-manager.yaml
> ```

I also see this URL defined in `k8s_cert_manager/tasks/install.yml`. Should it be defined in a single location and referenced in both places?

**Comment by johnthagen** [comment]
___
*[deploy/roles/k8s_config/templates/30-env-backend-secrets.yaml.j2, line 9 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1177#-MekyYhn6H47zWZ8MC_l:-MekyYhn6H47zWZ8MC_m:b-jr7haw) ([raw file](https://github.com/sillsdev/thecombine/blob/f556d98fbf6e728bf08f74719a2e06e35366dd11/deploy/roles/k8s_config/templates/30-env-backend-secrets.yaml.j2#L9)):*
> ```Jinja
> type: Opaque
> data:
>   COMBINE_JWT_SECRET_KEY: {{ combine_jwt_secret_key | b64encode }}
> ```

Curious, is this b64encode to obfuscate the secrets? Since it's not true encryption and can be reversed, what purpose does this serve? Is it to allow these to have non-ASCII characters?

**Review by johnthagen — COMMENTED** [review]
> Reviewed 4 of 48 files at r1, 6 of 49 files at r2, 47 of 62 files at r3, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1177)* status: all files reviewed, 2 unresolved discussions (waiting on @jmgrady)

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1177)* status: 81 of 83 files reviewed, 2 unresolved discussions (waiting on @johnthagen)

___
*[deploy/roles/k8s_cert_manager/tasks/install.yml, line 3 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1177#-MekxhZkC9pu9aKnj2Fm:-Mel6JP74JXUTixrEBxS:by87gtu) ([raw file](https://github.com/sillsdev/thecombine/blob/f556d98fbf6e728bf08f74719a2e06e35366dd11/deploy/roles/k8s_cert_manager/tasks/install.yml#L3)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I also see this URL defined in `k8s_cert_manager/tasks/install.yml`. Should it be defined in a single location and referenced in both places?
</blockquote></details>

Actually, `k8s_cert_manager/tasks/install.yml` and `k8s_cert_manager/tasks/configure.yml` are vestiges of a previous design and should have been removed.  They are gone now.  Good catch.
___
*[deploy/roles/k8s_config/templates/30-env-backend-secrets.yaml.j2, line 9 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1177#-MekyYhn6H47zWZ8MC_l:-Mel6gEs9wzcFfTmfC2o:b-otuu0a) ([raw file](https://github.com/sillsdev/thecombine/blob/f556d98fbf6e728bf08f74719a2e06e35366dd11/deploy/roles/k8s_config/templates/30-env-backend-secrets.yaml.j2#L9)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Curious, is this b64encode to obfuscate the secrets? Since it's not true encryption and can be reversed, what purpose does this serve? Is it to allow these to have non-ASCII characters?
</blockquote></details>

No, it is not for encryption.  Kubernetes requires that secrets be base64 encoded - presumably to be able to store them as YAML files and include binary data.  The ansible scripts do not actually install the YAML files on the target - they are created locally and applied to the cluster, which can be remote.  I have not looked into how they are stored inside the cluster but you need to have access rights to the cluster to read them.

**Review by johnthagen — APPROVED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1177)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Pull request merged**
