### PR TITLE
Split frontend and backend unit testing into two scripts

### LINKED ISSUE #704: Developers could benefit from commands for running tests and coverage on specific folder
Testing and coverage available according to our README:

`npm run coverage`
* This can take a few minutes, so it would be nice to be able to run this on specific files or folders

`npm test` or `npm run test`
* This also runs `dotnet test Backend.Tests/Backend.Tests.csproj` which slows down the work of somebody just wanting to run frontend tests; maybe something like `npm run test frontend` and `npm run test backend` could be added for just one or the other
* You can add a string at the end of the command (e.g. `npm test DataEntry`) and it will only run test files with that string in the path (frontend--all backend tests still run); this should be added to the documentation. Is there an analogous method for the backend testing?

### PR DESCRIPTION
**Pull request by johnthagen**
Closes #704

- Split `npm run test` into two, one for backend and one for frontend
- Also document CLI instructions for running a subset of either set of tests

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/732)

### CODE REVIEW

**Comment by johnthagen** [comment]
@imnasnainaec I'll update TeamCity config (which will fix CI) after this is reviewed and approved to decrease the time delta of mismatched CI config between this branch and other repos (especially want to let #618 flow through first).

**Comment by imnasnainaec** [comment]
For some reason, GitHub is turning the `for`s red:
image

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/732)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @imnasnainaec)

*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/732#-MI5GDd30gVuiPuj3CwE:-MI5GDd4CerSWZgYpolD:b-lq7gqq) (no related file):*
It might be nice to still have `npm test` available to run both backend and frontend.

---

**Comment by johnthagen** [comment]
*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/732#-MI5GDd30gVuiPuj3CwE:-MI5HXNKA3Me8X5mnRD_:b-896fix) (no related file):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

It might be nice to still have `npm test` available to run both backend and frontend.
</blockquote></details>

Done.

---

**Comment by imnasnainaec** [comment]
> For some reason, GitHub is turning the `for`s red:
> ...

And unfortunately, removing `batch` from those two creates inconsistent `>` coloring on the Readme:
image

**Comment by johnthagen** [comment]
@imnasnainaec Done.

**Comment by johnthagen** [comment]
@imnasnainaec `bash` highlighting is now used everywhere in the README for consistency.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/732)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @johnthagen)

___
*[package.json, line 31 at r6](https://reviewable.io/reviews/sillsdev/thecombine/732#-MI5JvNP5vOFpm1V-GXQ:-MI5JvNP5vOFpm1V-GXR:b1yeks4) ([raw file](https://github.com/sillsdev/thecombine/blob/d8006a181e75c4c4aa37a04c86f2c2dbd0025e55/package.json#L31)):*
> ```
>     "test:debug": "react-scripts --inspect-brk test --runInBand --no-cache",
> ```
Should `test:debug` perhaps become `test-frontend:debug`?

**Comment by johnthagen** [comment]
___
*[package.json, line 31 at r6](https://reviewable.io/reviews/sillsdev/thecombine/732#-MI5JvNP5vOFpm1V-GXQ:-MI5KKH05kPnxlGyBTx-:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/d8006a181e75c4c4aa37a04c86f2c2dbd0025e55/package.json#L31)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>     "test:debug": "react-scripts --inspect-brk test --runInBand --no-cache",
> ```
Should `test:debug` perhaps become `test-frontend:debug`?
</blockquote></details>

Done

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/732)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @johnthagen)

___
*[README.md, line 181 at r7](https://reviewable.io/reviews/sillsdev/thecombine/732#-MI5Kouj34CCUdnhAvPx:-MI5Kouj34CCUdnhAvPy:bbb056j) ([raw file](https://github.com/sillsdev/thecombine/blob/59621952ddd9c3b576ffbdfac03290002b989f75/README.md#L181)):*
> ```
> #### `npm run test:debug`
> Runs Jest tests for debugging, awaiting for an attach from an IDE.
> ```
Now this needs updating.

**Comment by johnthagen** [comment]
___
*[README.md, line 181 at r7](https://reviewable.io/reviews/sillsdev/thecombine/732#-MI5Kouj34CCUdnhAvPx:-MI5L6eL0fsmqZeT9vB1:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/59621952ddd9c3b576ffbdfac03290002b989f75/README.md#L181)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> #### `npm run test:debug`
> Runs Jest tests for debugging, awaiting for an attach from an IDE.
> ```
Now this needs updating.
</blockquote></details>

Done

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/732)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @johnthagen)

**Review by johnthagen — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/732#-:-MI5LLLB2Dwh07kiQ5bU:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @johnthagen)

**Review by johnthagen — COMMENTED** [review]
> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/732)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/732)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[README.md, line 37 at r8](https://reviewable.io/reviews/sillsdev/thecombine/732#-MI5LlqvCgeb1nz08bU6:-MI5LlqvCgeb1nz08bU7:bcokp8x) ([raw file](https://github.com/sillsdev/thecombine/blob/c5ea080fbcc9d09999cae902d1702dba77250a61/README.md#L37)):*
```
>    git clone --recurse-submodules https://github.com/sillsdev/TheCombine.git
>    ```
>    If you've already cloned the repo without `--recurse-submodules`, run:
>    ```bash
>    git submodule update --init --recursive
```
Could use $ before both these `git... ` cli commands for consistency.
___
*[README.md, line 217 at r8](https://reviewable.io/reviews/sillsdev/thecombine/732#-MI5MAuA4GdDJscb-1js:-MI5MAuB735UaQciq2HQ:bgqddkn) ([raw file](https://github.com/sillsdev/thecombine/blob/c5ea080fbcc9d09999cae902d1702dba77250a61/README.md#L217)):*
> ```Markdown
> 
> ```bash
> npm run import-sem-doms -- <XML_FILE_PATH>
> ```

$ here also for consistency

**Comment by johnthagen** [comment]
@imnasnainaec To save on CI time, I'll fix those in the next PR.

**Pull request merged**
