### PR TITLE
Merge continue

### LINKED ISSUE #765: Merge blacklist, for (near) homographs, not always working.
In Data Cleanup > Merge Duplicates, when a potential duplicate is presented for merging, if the user doesn't make any changes, there are two options:
* Skip: moves to the next merge possibility to return to the skipped on later
* Save & Continue: designate the set of words as distinct, adding them to a blacklist so they won't be revisited
The latter option is not working if at least one of the words has more than one sense in it.
The word is being updated (it shouldn't be), switching the sense states from active to sense and back to active. The update causes a change in the word id, which means the addition to the blacklist is no longer relevant and the same set of words will be presented again in the future.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #765

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/766)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/766)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx, line 345 at r2](https://reviewable.io/reviews/sillsdev/thecombine/766#-MJgrakX7Pt99kVvZak_:-MJgrakX7Pt99kVvZaka:bzdpnjf) ([raw file](https://github.com/sillsdev/thecombine/blob/bdb5b9c489a5972d346cc8c79267537661501947/src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx#L345)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>     // a merge is an identity if all of its senses come from parent
>     // and it has the same number of senses as parent
>     if (!children.find((val) => val.wordID !== wordID)) {
>       if (children.length === data.words[wordID].senses.length) {
>         // if the merge is an identity don't bother sending a merge
>         return mapping;
>       }
>     }
> ```
</details>

<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
>     // a merge is an identity if all of its senses come from parent
>     // and it has the same number of senses as parent
>     if (
>       children.length === 1 &&
>       children[0].wordID === wordID &&
>       children[0].senses.length === data.words[wordID].senses.length
>     ) {
>       // if the merge is an identity don't bother sending a merge
>       return mapping;
>     }
> ```
</details>


@jasonleenaylor This is the logic change of the PR.

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/766)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @jasonleenaylor)

___
*[src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx, line 340 at r2](https://reviewable.io/reviews/sillsdev/thecombine/766#-MJgrPrjAO1BKmJI1k8s:-MJgrPrjAO1BKmJI1k8t:bv321zw) ([raw file](https://github.com/sillsdev/thecombine/blob/bdb5b9c489a5972d346cc8c79267537661501947/src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx#L340)):*
> ```
>       children.length === 1 &&
>       children[0].wordID === wordID &&
>       children[0].senses.length === data.words[wordID].senses.length
> ```
So it doesn't look like the comment and the code agree. (not that it did before)

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/766)* status: all files reviewed, 2 unresolved discussions (waiting on @imnasnainaec)

___
*[src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx, line 340 at r2](https://reviewable.io/reviews/sillsdev/thecombine/766#-MJgrPrjAO1BKmJI1k8s:-MJjMM1KBvsAuriuAoph:bdg7c55) ([raw file](https://github.com/sillsdev/thecombine/blob/bdb5b9c489a5972d346cc8c79267537661501947/src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx#L340)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
>       children.length === 1 &&
>       children[0].wordID === wordID &&
>       children[0].senses.length === data.words[wordID].senses.length
> ```
So it doesn't look like the comment and the code agree. (not that it did before)

</blockquote></details>

It was looking better, until you added the new condition. :smile:

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/766)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

___
*[src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx, line 340 at r2](https://reviewable.io/reviews/sillsdev/thecombine/766#-MJgrPrjAO1BKmJI1k8s:-MJloV0S5RCwcS2yiel4:b-80cua0) ([raw file](https://github.com/sillsdev/thecombine/blob/bdb5b9c489a5972d346cc8c79267537661501947/src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx#L340)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

It was looking better, until you added the new condition. :smile:
</blockquote></details>

Yeah... the new condition isn't as pretty, but is necessary for such cases as a merging of senses within a single word.

**Review by johnthagen — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/766)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
