### PR TITLE
Added summary views to completed goals

### LINKED ISSUE #1173: Create summary views for completed goals.
In "Data Cleanup" there is a "You've completed:" section with tiles that can be clicked on to show what changes were made.
Screen Shot 2021-05-27 at 13 21 05
Screen Shot 2021-05-27 at 13 23 27
Screen Shot 2021-05-27 at 13 23 04

We want those tiles to show more than just the goal worked on, but a concise summary of the contents they link to.
- [x] "Create Character Inventory" tiles could list of what characters were updated, colored by their new status.
- [x] "Merge Duplicates" tiles could state the number of merges completed.
- [ ] #1247

### PR DESCRIPTION
**Pull request by JacobHaimes**
Completed character changes now display changes made within the previous instance. Merge duplicated displays the total number of merges. 

Closes #1173

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1248)

### CODE REVIEW

**Review by imnasnainaec — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1248)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @JacobHaimes)

___
*[src/components/GoalTimeline/GoalList.tsx, line 140 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1248#-MeRG0rb5vPmSMR6uGU7:-MeRG0rb5vPmSMR6uGU8:b-xrx1n1) ([raw file](https://github.com/sillsdev/thecombine/blob/7df5f1c34425d91507502904f1c44b9b31ad65ea/src/components/GoalTimeline/GoalList.tsx#L140)):*
> ```XML
>         return MergesCount(goal.changes as MergesCompleted);
>       default:
>         return "nothing";
> ```

Let's have the default be blank, since other cases mean that changes aren't tracked, not that there weren't changes.
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 52 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1248#-MeRFLqF7vaUv8mD_GYJ:-MeRFLqF7vaUv8mD_GYK:b-mev19o) ([raw file](https://github.com/sillsdev/thecombine/blob/7df5f1c34425d91507502904f1c44b9b31ad65ea/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L52)):*
> ```XML
> export function MergesCount(changes: MergesCompleted) {
>   return (
>     <div>
> ```

Unnecessary `<div>`. The function immediately preceding this has one simply to wrap two things together.

**Comment by johnthagen** [comment]
___
*[src/components/GoalTimeline/GoalList.tsx, line 132 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1248#-MejCM7VEFnykcs3R8Bg:-MejCM7VEFnykcs3R8Bh:bs8mjc5) ([raw file](https://github.com/sillsdev/thecombine/blob/7df5f1c34425d91507502904f1c44b9b31ad65ea/src/components/GoalTimeline/GoalList.tsx#L132)):*
> ```XML
> }
> 
> function GoalInfo(goal: Goal) {
> ```

Should we add an explicit return type here? @imnasnainaec What's our current coding style guide for that?

**Comment by johnthagen** [comment]
___
*[src/goals/CreateCharInv/CharInvComponent/CharInvCompleted.tsx, line 48 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1248#-MejCwnx3Dg5Wym1DIbj:-MejCwnx3Dg5Wym1DIbk:b9hb70m) ([raw file](https://github.com/sillsdev/thecombine/blob/7df5f1c34425d91507502904f1c44b9b31ad65ea/src/goals/CreateCharInv/CharInvComponent/CharInvCompleted.tsx#L48)):*
> ```XML
>     return (
>       <Typography>
>         {changes.charChanges.map(CharInvChange)[0]}
> ```

Are we able to do some kind of loop here instead of duplicating the same statement four times?

We might also then be able to define `4` as a `const` and use that both in the `else if` and `for`.

**Review by johnthagen — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1248)* status: all files reviewed, 4 unresolved discussions (waiting on @JacobHaimes)

**Review by JacobHaimes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1248)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @imnasnainaec, @JacobHaimes, and @johnthagen)

___
*[src/components/GoalTimeline/GoalList.tsx, line 140 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1248#-MeRG0rb5vPmSMR6uGU7:-MfcYCtN41ZMYM3dV5ht:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7df5f1c34425d91507502904f1c44b9b31ad65ea/src/components/GoalTimeline/GoalList.tsx#L140)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Let's have the default be blank, since other cases mean that changes aren't tracked, not that there weren't changes.
</blockquote></details>

Done.
___
*[src/goals/CreateCharInv/CharInvComponent/CharInvCompleted.tsx, line 48 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1248#-MejCwnx3Dg5Wym1DIbj:-MfcYFYv73aEbSDV6AK9:bro7lts) ([raw file](https://github.com/sillsdev/thecombine/blob/7df5f1c34425d91507502904f1c44b9b31ad65ea/src/goals/CreateCharInv/CharInvComponent/CharInvCompleted.tsx#L48)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Are we able to do some kind of loop here instead of duplicating the same statement four times?

We might also then be able to define `4` as a `const` and use that both in the `else if` and `for`.
</blockquote></details>

Switched to using slice for a range instead of a loop.
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 52 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1248#-MeRFLqF7vaUv8mD_GYJ:-MfcYd4K6UeSQLYjegVF:bss4a2b) ([raw file](https://github.com/sillsdev/thecombine/blob/7df5f1c34425d91507502904f1c44b9b31ad65ea/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L52)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Unnecessary `<div>`. The function immediately preceding this has one simply to wrap two things together.
</blockquote></details>

Removed.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1248)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @JacobHaimes and @johnthagen)

___
*[src/components/GoalTimeline/GoalList.tsx, line 65 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1248#-MfcdtyGBcvi_52tPY_o:-MfcdtyGBcvi_52tPY_p:b5s2xbd) ([raw file](https://github.com/sillsdev/thecombine/blob/029070238b0d687bedfaae7690bfa4e22169376b/src/components/GoalTimeline/GoalList.tsx#L65)):*
> ```
>         props.scrollable
>           ? () => setScrollVisible(true)
>           : () => setScrollVisible(false)
> ```
How about `() => setScrollVisible(props.scrollable)`?
___
*[src/components/GoalTimeline/GoalTimelineComponent.tsx, line 120 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1248#-MfceyeRDP9CM7Y9wfYB:-MfceyeRDP9CM7Y9wfYC:bvocili) ([raw file](https://github.com/sillsdev/thecombine/blob/029070238b0d687bedfaae7690bfa4e22169376b/src/components/GoalTimeline/GoalTimelineComponent.tsx#L120)):*
> ```
>         <div style={{ ...timelineStyle.paneStyling, float: "right" } as any}>
>  ...
>         <div style={{ ...(timelineStyle.paneStyling as any), width: "60%" }}>
> ```
Both placements of `as any` seem to satisfy the type-checker, but let's be consistent, using the same in both places.
___
*[src/goals/CreateCharInv/CharInvComponent/CharInvCompleted.tsx, line 51 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1248#-MfcfK5s5mz_IvP9IHcw:-MfcfK5s5mz_IvP9IHcx:b-e8bg65) ([raw file](https://github.com/sillsdev/thecombine/blob/029070238b0d687bedfaae7690bfa4e22169376b/src/goals/CreateCharInv/CharInvComponent/CharInvCompleted.tsx#L51)):*
> ```
>         {"+"}
>         {changes.charChanges.length - 3}{" "}
> ```
``` {`+${changes.charChanges.length - 3} `}```
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 47 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1248#-Mfcftlm0v4zGooGsygK:-Mfcftlm0v4zGooGsygL:btimyb) ([raw file](https://github.com/sillsdev/thecombine/blob/029070238b0d687bedfaae7690bfa4e22169376b/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L47)):*
> ```XML
> }
> 
> export function MergesCount(changes: MergesCompleted) {
> ```

This can use `: JSX.Element` too, no?

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1248)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @JacobHaimes and @johnthagen)

___
*[src/components/GoalTimeline/GoalTimelineComponent.tsx, line 120 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1248#-MfceyeRDP9CM7Y9wfYB:-MfchUVtBIs8gkDETuzw:b-riw78u) ([raw file](https://github.com/sillsdev/thecombine/blob/029070238b0d687bedfaae7690bfa4e22169376b/src/components/GoalTimeline/GoalTimelineComponent.tsx#L120)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>         <div style={{ ...timelineStyle.paneStyling, float: "right" } as any}>
>  ...
>         <div style={{ ...(timelineStyle.paneStyling as any), width: "60%" }}>
> ```
Both placements of `as any` seem to satisfy the type-checker, but let's be consistent, using the same in both places.
</blockquote></details>

Even better, here's a fix that will allow you to get rid of all these unpleasant `as any`s: https://github.com/typestyle/typestyle/issues/281#issuecomment-535359254

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 3 of 5 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1248)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @JacobHaimes and @johnthagen)

___
*[src/components/GoalTimeline/GoalList.tsx, line 11 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1248#-MgM8bXp8VcXTfQ74PXQ:-MgM8bXp8VcXTfQ74PXR:b-3sqtns) ([raw file](https://github.com/sillsdev/thecombine/blob/b0ff8ca0fd9e7584c10f422192cef09b29757eb8/src/components/GoalTimeline/GoalList.tsx#L11)):*
> ```
> import { Goal, GoalStatus, GoalType } from "types/goals";
> ```
Let's move this to the bottom of the local imports.
___
*[src/components/GoalTimeline/GoalList.tsx, line 118 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1248#-MgMAUu55JbRuWLV-oTY:-MgMAUu55JbRuWLV-oTZ:b-ftr203) ([raw file](https://github.com/sillsdev/thecombine/blob/b0ff8ca0fd9e7584c10f422192cef09b29757eb8/src/components/GoalTimeline/GoalList.tsx#L118)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
>         <Grid container direction="column">
>           <Grid item>
>             {goal ? (
>               GoalInfo(goal)
>             ) : (
>               <Typography variant="h6">
>                 <Translate id={"goal.selector.noHistory"} />
>               </Typography>
>             )}
>           </Grid>
>         </Grid>
> ```
</details>

Are the `<Grid container...` and `<Grid item>` wrappers necessary?
___
*[src/goals/CreateCharInv/CharInvComponent/CharInvCompleted.tsx, line 39 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1248#-MgM7k0sDyhL5DNqnQpG:-MgM7k0sDyhL5DNqnQpH:b65p2aa) ([raw file](https://github.com/sillsdev/thecombine/blob/b0ff8ca0fd9e7584c10f422192cef09b29757eb8/src/goals/CreateCharInv/CharInvComponent/CharInvCompleted.tsx#L39)):*
> ```
>   const changelimit = 4;
> ```
Use `changeLimit` (camel case).
Also, let's lower this from 4 to 3, to accommodate a little for smaller screens or slightly zoomed windows.
___
*[src/goals/CreateCharInv/CharInvComponent/CharInvCompleted.tsx, line 46 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1248#-MgM7E1o9OVKsF6LCORP:-MgM7E1o9OVKsF6LCORQ:b-u63xa6) ([raw file](https://github.com/sillsdev/thecombine/blob/b0ff8ca0fd9e7584c10f422192cef09b29757eb8/src/goals/CreateCharInv/CharInvComponent/CharInvCompleted.tsx#L46)):*
> ```
> } else if (changes.charChanges?.length > changelimit) {
> ```
The `else` is unnecessary, since the previous `if` contains a `return`.
The `?` is unnecessary, since the previous `if` covers the case of `changes.charChanges` being `null | undefined`.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1248)* status: all files reviewed, 1 unresolved discussion (waiting on @johnthagen)

**Pull request merged**
