### PR TITLE
Stream all file downloads

### LINKED ISSUE #811: Reduce peak memory usage during Lift Export
Currently when the backend exports a Lift file, it:

- Generates a zip file temporarily on disk (can be many 100s of MB)
- It reads this into memory
- It base64 decodes the contents in memory (which expands it ~30%)
- It sends this to the client in an HTTP response

This leads to peak memory usage of about (export_size x 2.3). It has been observed that for a 600MB export, system memory utilization increased to 2.2GB.

One option is to use NGINX `sendfile` to allow NGINX to efficiently stream the file back to the client and not load it into the backend memory:

- https://nginx.org/en/docs/http/ngx_http_core_module.html#sendfile

### PR DESCRIPTION
**Pull request by johnthagen**
- This reduces peak/persistent memory usage of downloading a 116MB Lift export by ~116MB.

Closes #811

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/878)

### CODE REVIEW

**Comment by johnthagen** [comment]
LGTM failure is due to Nuget having infrastructure issues today:

```
[2020-12-18 19:49:43] [build]   Failed to download package 'System.Runtime.CompilerServices.Unsafe.4.5.2' from 'https://api.nuget.org/v3-flatcontainer/system.runtime.compilerservices.unsafe/4.5.2/system.runtime.compilerservices.unsafe.4.5.2.nupkg'.
[2020-12-18 19:49:43] [build]   Response status code does not indicate success: 503 (Service Unavailable).
```

**Comment by johnthagen** [comment]
Avatar display issues are unrelated to this PR: #879

**Comment by johnthagen** [comment]
Still getting nuget errors on LGTM?

```
[2020-12-19 13:58:50] [build] /opt/work/.dotnet/sdk/5.0.100/NuGet.targets(131,5): error : Failed to download package 'System.Runtime.CompilerServices.Unsafe.4.5.2' from 'https://api.nuget.org/v3-flatcontainer/system.runtime.compilerservices.unsafe/4.5.2/system.runtime.compilerservices.unsafe.4.5.2.nupkg'. [/opt/src/BackendFramework.sln]
```

**Comment by johnthagen** [comment]
This could be because LGTM is running .NET 5:

```
[2020-12-19 14:58:07] [build] [2020-12-19 14:58:07] [build] Running dotnet --info
[2020-12-19 14:58:07] [build] [2020-12-19 14:58:07] [build] .NET SDK (reflecting any global.json):
[2020-12-19 14:58:07] [build] [2020-12-19 14:58:07] [build]  Version:   5.0.100
[2020-12-19 14:58:07] [build] [2020-12-19 14:58:07] [build]  Commit:    5044b93829
[2020-12-19 14:58:07] [build] [2020-12-19 14:58:07] [build] Runtime Environment:
[2020-12-19 14:58:07] [build] [2020-12-19 14:58:07] [build]  OS Name:     ubuntu
[2020-12-19 14:58:07] [build] [2020-12-19 14:58:07] [build]  OS Version:  19.10
[2020-12-19 14:58:07] [build] [2020-12-19 14:58:07] [build]  OS Platform: Linux
[2020-12-19 14:58:07] [build] [2020-12-19 14:58:07] [build]  RID:         ubuntu.19.10-x64
[2020-12-19 14:58:07] [build] [2020-12-19 14:58:07] [build]  Base Path:   /opt/work/.dotnet/sdk/5.0.100/
[2020-12-19 14:58:07] [build] [2020-12-19 14:58:07] [build] Host (useful for support):
[2020-12-19 14:58:07] [build] [2020-12-19 14:58:07] [build]   Version: 5.0.0
[2020-12-19 14:58:07] [build] [2020-12-19 14:58:07] [build]   Commit:  cf258a14b7
[2020-12-19 14:58:07] [build] [2020-12-19 14:58:07] [build] .NET SDKs installed:
[2020-12-19 14:58:07] [build] [2020-12-19 14:58:07] [build]   2.1.802 [/opt/work/.dotnet/sdk]
[2020-12-19 14:58:07] [build] [2020-12-19 14:58:07] [build]   3.1.301 [/opt/work/.dotnet/sdk]
[2020-12-19 14:58:07] [build] [2020-12-19 14:58:07] [build]   5.0.100 [/opt/work/.dotnet/sdk]
[2020-12-19 14:58:07] [build] [2020-12-19 14:58:07] [build] .NET runtimes installed:
[2020-12-19 14:58:07] [build] [2020-12-19 14:58:07] [build]   Microsoft.AspNetCore.All 2.1.13 [/opt/work/.dotnet/shared/Microsoft.AspNetCore.All]
[2020-12-19 14:58:07] [build] [2020-12-19 14:58:07] [build]   Microsoft.AspNetCore.App 2.1.13 [/opt/work/.dotnet/shared/Microsoft.AspNetCore.App]
[2020-12-19 14:58:07] [build] [2020-12-19 14:58:07] [build]   Microsoft.AspNetCore.App 3.1.5 [/opt/work/.dotnet/shared/Microsoft.AspNetCore.App]
[2020-12-19 14:58:07] [build] [2020-12-19 14:58:07] [build]   Microsoft.AspNetCore.App 5.0.0 [/opt/work/.dotnet/shared/Microsoft.AspNetCore.App]
[2020-12-19 14:58:07] [build] [2020-12-19 14:58:07] [build]   Microsoft.NETCore.App 2.1.13 [/opt/work/.dotnet/shared/Microsoft.NETCore.App]
[2020-12-19 14:58:07] [build] [2020-12-19 14:58:07] [build]   Microsoft.NETCore.App 3.1.5 [/opt/work/.dotnet/shared/Microsoft.NETCore.App]
[2020-12-19 14:58:07] [build] [2020-12-19 14:58:07] [build]   Microsoft.NETCore.App 5.0.0 [/opt/work/.dotnet/shared/Microsoft.NETCore.App]
[2020-12-19 14:58:07] [build] [2020-12-19 14:58:07] [build] To install additional .NET runtimes or SDKs:
[2020-12-19 14:58:07] [build] [2020-12-19 14:58:07] [build]   https://aka.ms/dotnet-download
[2020-12-19 14:58:07] [build] [2020-12-19 14:58:07] [build] Exit code 0
```

**Comment by johnthagen** [comment]
LGTM build failures unrelated and tracked in #883

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 12 of 14 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/878)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jmgrady — APPROVED** [review]
:lgtm: 

> Reviewed 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/878#-:-MPAMjMR3L3-vHVkbp_U:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 3 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/878)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Pull request merged**
