### PR TITLE
[NewEntry] Refactor duplicate handling

### LINKED ISSUE #1584: [NewEntry] Note+Audio are lost when a new entry is determined to be a duplicate
Two parts:

- [x] Note
- [ ] Audio

**Describe the bug**

When a new entry is determined in the backend to be a duplicate of an existing entry, the semantic domain of the new entry is added to the existing entry and the new entry is not created. When that happens, any note or audio added before submitting the new entry is completely lost.

**To Reproduce**

1. In project settings, turn off Autocomplete.
2. Go to Data Entry and select any domain.
3. Add a new entry (e.g., "vern", "gloss") with no note or audio and press Enter
4. Add another entry with the exact same vernacular and gloss, but this time add a note and a recording before pressing Enter
5. There will be an alert that the entry you added is a duplicate, but the note and audio you made are nowhere to be found.

**Expected behavior**

The audio of a duplicate entry should be added to the entry which is being duplicated.
The note should be appended to the existing entry (;-separated?). (What do we do if the new note is in a different language than the existing note?)

### LINKED ISSUE #1586: [DataEntryTable] A duplicate new entry that updates an existing entry doesn't add it to Recent/Existing Entries
**Describe the bug**

When a new entry is a duplicate of an existing entry, the semantic domain of the new entry is added to the existing entry instead of the new entry being created. However, when that happens, the updated existing entry should be added either to the Recent Entries above the New Entry row or the the side box of Existing Entries in the domain.

**To Reproduce**

1. Go to project setting and switch Autocomplete to Off;
2. Go to Data Entry;
3. Select a domain (e.g., 1.1);
4. Submit a new entry (e.g., vernacular "Donut" and gloss "Doughnut");
5. Press "Exit" to return to the tree;
6. Select a different domain (e.g., 1.2);
7. Submit the same entry;
8. Deal with the pop-up that tells you it was a duplicate.
9. Observe that the entry is not visible (but if you click done, then click the same domain again, that entry should now be visible in Existing Entries)

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #1584 (audio)
Resolves #1586
Progress toward #1449 (for now, removes alert and gives no user feedback, since the duplicated entry is updated in the recent entries)

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1622)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[-- commits, line 29 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1622#-Mz0MjyP3ERD0HlJfRVJ):*
This is likely expected since the frontend is still in draft, but currently the UI doesn't seem to merge the duplicates into a single entry on the screen when you add a note and audio.

**Comment by johnthagen** [comment]
___
*[Backend/Services/WordService.cs, line 140 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1622#-Mz0QFUy6cqBEMdncbIi:-Mz0QFUy6cqBEMdncbIj:b1gjlt6) ([raw file](https://github.com/sillsdev/thecombine/blob/c3c10a8540c8f2e187ede89d24dfdec046504b82/Backend/Services/WordService.cs#L140)):*
> ```Smalltalk
>         /// Otherwise, returns empty string.
>         /// </summary>
>         public async Task<string> FindContainingWord(Word word)
> ```

I think it would be more type-safe if we expressed this as `string?`. If no duplicate is found, return `null`.

This allows consumers to check the type at compile time rather than check the value at runtime.

**Comment by johnthagen** [comment]
___
*[Backend/Controllers/WordController.cs, line 171 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1622#-Mz0SZgA7q3vvxXtqnlk:-Mz0SZgA7q3vvxXtqnll:bog7v8n) ([raw file](https://github.com/sillsdev/thecombine/blob/c3c10a8540c8f2e187ede89d24dfdec046504b82/Backend/Controllers/WordController.cs#L171)):*
> ```Smalltalk
>         [HttpPost("{dupId}", Name = "UpdateDuplicate")]
>         [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(string))]
>         public async Task<IActionResult> UpdateDuplicate(string projectId, string dupId, [FromBody, BindRequired] Word word)
> ```

Wrap long line.

**Comment by johnthagen** [comment]
___
*[Backend/Models/Word.cs, line 224 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1622#-Mz0T9A31VOpExiCRkqf:-Mz0T9A31VOpExiCRkqg:b29qte9) ([raw file](https://github.com/sillsdev/thecombine/blob/c3c10a8540c8f2e187ede89d24dfdec046504b82/Backend/Models/Word.cs#L224)):*
> ```Smalltalk
>         /// Plural, PartOfSpeech, Created, Modified, Accessibility, OtherField.
>         /// </summary>
>         public bool CombineContainedWord(Word other)
> ```

Maybe another name for the function could be `AppendContainedWordContents`? It's a little long but I like having the word `Append` in there because I feel like it expresses what is going on here.

Also suggest similar updates to the doc comments.

**Comment by johnthagen** [comment]
___
*[Backend/Models/Word.cs, line 224 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1622#-Mz0TdSnD6LnXxzAk--h:-Mz0TdSnD6LnXxzAk--i:b92y953) ([raw file](https://github.com/sillsdev/thecombine/blob/c3c10a8540c8f2e187ede89d24dfdec046504b82/Backend/Models/Word.cs#L224)):*
> ```Smalltalk
>         /// Plural, PartOfSpeech, Created, Modified, Accessibility, OtherField.
>         /// </summary>
>         public bool CombineContainedWord(Word other)
> ```

Document the meaning of the return value.

**Comment by johnthagen** [comment]
___
*[Backend/Models/Word.cs, line 291 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1622#-Mz0U0rg0fsogmPnXON9:-Mz0U0rg0fsogmPnXONA:byzhvkv) ([raw file](https://github.com/sillsdev/thecombine/blob/c3c10a8540c8f2e187ede89d24dfdec046504b82/Backend/Models/Word.cs#L291)):*
> ```Smalltalk
>         public bool IsBlank()
>         {
>             return string.IsNullOrWhiteSpace(Text);
> ```

Would `IsNullOrEmpty` be more precise? I guess I'm not really sure what it means to have a `Note` with only whitespace (probably an input error).

Also, it _feels_ a little weird to check a non-nullable type `IsNull` when it can't be at compile time.

Perhaps we should simply revert this line change as the previous implementation was pretty clear on semantics and type soundness?

**Comment by johnthagen** [comment]
___
*[Backend/Models/Word.cs, line 291 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1622#-Mz0U0rg0fsogmPnXON9:-Mz0UdC15gKLD4iCmj0q:b96aafg) ([raw file](https://github.com/sillsdev/thecombine/blob/c3c10a8540c8f2e187ede89d24dfdec046504b82/Backend/Models/Word.cs#L291)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Would `IsNullOrEmpty` be more precise? I guess I'm not really sure what it means to have a `Note` with only whitespace (probably an input error).

Also, it _feels_ a little weird to check a non-nullable type `IsNull` when it can't be at compile time.

Perhaps we should simply revert this line change as the previous implementation was pretty clear on semantics and type soundness?
</blockquote></details>

Oh, I see you may not want to append a whitespace-only `Note` to another note (and then have the extra `; `). In that case perhaps this change is fine as is.

But the overall `IsBlank()` name of this method is perhaps a little misleading to it's implementation?

**Comment by johnthagen** [comment]
___
*[Backend.Tests/Models/WordTests.cs, line 61 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1622#-Mz0XU_xAPeTI6SWL3-2:-Mz0XU_xAPeTI6SWL3-3:b-8llhdw) ([raw file](https://github.com/sillsdev/thecombine/blob/c3c10a8540c8f2e187ede89d24dfdec046504b82/Backend.Tests/Models/WordTests.cs#L61)):*
> ```Smalltalk
>             var diffWord = word.Clone();
>             diffWord.Senses.RemoveAt(1);
>             Assert.IsTrue(word.Contains(diffWord));
> ```

More of a philosophical question, but should we prefer `Assert.IsTrue()`, `Assert.True()` (shorter) or `Assert.That()`

https://stackoverflow.com/questions/16086870/assert-that-vs-assert-true

I think the way we have it hear is fine, it was just interesting for me to find there are multiple ways of doing this in NUnit.

**Comment by johnthagen** [comment]
___
*[Backend.Tests/Models/WordTests.cs, line 352 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1622#-Mz0YYFc58SQnlVlnc3k:-Mz0YYFd8vxsLo_rxkvQ:b87yh3b) ([raw file](https://github.com/sillsdev/thecombine/blob/c3c10a8540c8f2e187ede89d24dfdec046504b82/Backend.Tests/Models/WordTests.cs#L352)):*
> ```Smalltalk
> 
>         [Test]
>         public void TestAppendBlank()
> ```

Do we want to add a test for pure-whitespace since that is now considered blank in our implementation?

**Comment by johnthagen** [comment]
___
*[src/api/models/project.ts, line 62 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1622#-Mz0ZFYRC_WmPq9_FMNQ:-Mz0ZFYRC_WmPq9_FMNR:b-reseu1) ([raw file](https://github.com/sillsdev/thecombine/blob/c3c10a8540c8f2e187ede89d24dfdec046504b82/src/api/models/project.ts#L62)):*
> ```XML
>    * @memberof Project
>    */
>   autocompleteSetting: AutocompleteSetting;
> ```

Is this an expected change from this PR?

**Comment by johnthagen** [comment]
___
*[src/backend/index.ts, line 547 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1622#-Mz0_W-I027Xdo4KOc9_:-Mz0_W-I027Xdo4KOc9a:b-j85w0k) ([raw file](https://github.com/sillsdev/thecombine/blob/c3c10a8540c8f2e187ede89d24dfdec046504b82/src/backend/index.ts#L547)):*
> ```XML
> /* WordController.cs */
> 
> export async function createWord(
> ```

Now that this function is more complex, should we rename it? I could see the callers of this function not realizing it now does some extra duplicate/update steps?

**Review by johnthagen — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1622)* status: all files reviewed, 10 unresolved discussions (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1622)* status: 7 of 13 files reviewed, 6 unresolved discussions (waiting on @imnasnainaec and @johnthagen)

___
*[Backend/Controllers/WordController.cs, line 171 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1622#-Mz0SZgA7q3vvxXtqnlk:-MzMAtDX3i2UOPQDLAjK:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/5aeba90831ec066099444ec83945ff2f5d3d0fe4/Backend/Controllers/WordController.cs#L171)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Wrap long line.
</blockquote></details>

Done.
___
*[Backend/Models/Word.cs, line 224 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1622#-Mz0TdSnD6LnXxzAk--h:-MzMAuvR7wzBKA6Io_dn:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/5aeba90831ec066099444ec83945ff2f5d3d0fe4/Backend/Models/Word.cs#L224)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Document the meaning of the return value.
</blockquote></details>

Done.
___
*[Backend/Services/WordService.cs, line 140 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1622#-Mz0QFUy6cqBEMdncbIi:-MzMAwrRCb0Q3j7zVnga:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/5aeba90831ec066099444ec83945ff2f5d3d0fe4/Backend/Services/WordService.cs#L140)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I think it would be more type-safe if we expressed this as `string?`. If no duplicate is found, return `null`.

This allows consumers to check the type at compile time rather than check the value at runtime.
</blockquote></details>

Done.
___
*[Backend.Tests/Models/WordTests.cs, line 61 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1622#-Mz0XU_xAPeTI6SWL3-2:-MzMAxoZ3dzVTP2LiYAK:bkpvmfj) ([raw file](https://github.com/sillsdev/thecombine/blob/5aeba90831ec066099444ec83945ff2f5d3d0fe4/Backend.Tests/Models/WordTests.cs#L61)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

More of a philosophical question, but should we prefer `Assert.IsTrue()`, `Assert.True()` (shorter) or `Assert.That()`

https://stackoverflow.com/questions/16086870/assert-that-vs-assert-true

I think the way we have it hear is fine, it was just interesting for me to find there are multiple ways of doing this in NUnit.
</blockquote></details>

Jason has expressed preference for `Assert.That(...` as it produces more natural-sounding / easy-to-read output.
___
*[Backend.Tests/Models/WordTests.cs, line 352 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1622#-Mz0YYFc58SQnlVlnc3k:-MzMBPQK76Bdr9O7Ida1:b-itbmwv) ([raw file](https://github.com/sillsdev/thecombine/blob/5aeba90831ec066099444ec83945ff2f5d3d0fe4/Backend.Tests/Models/WordTests.cs#L352)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Do we want to add a test for pure-whitespace since that is now considered blank in our implementation?
</blockquote></details>

Added a whitespace-string test to `TestIsBlank`. Sufficient?
___
*[src/api/models/project.ts, line 62 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1622#-Mz0ZFYRC_WmPq9_FMNQ:-MzMBW0OAEICaHZ10KMq:bfgfc8w) ([raw file](https://github.com/sillsdev/thecombine/blob/5aeba90831ec066099444ec83945ff2f5d3d0fe4/src/api/models/project.ts#L62)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Is this an expected change from this PR?
</blockquote></details>

I think this is the consequence of a previous pr's reordering.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1622)* status: 4 of 15 files reviewed, 5 unresolved discussions (waiting on @imnasnainaec and @johnthagen)

___
*[-- commits, line 29 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1622#-Mz0MjyP3ERD0HlJfRVJ):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This is likely expected since the frontend is still in draft, but currently the UI doesn't seem to merge the duplicates into a single entry on the screen when you add a note and audio.



</blockquote></details>

Done.
___
*[src/backend/index.ts, line 547 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1622#-Mz0_W-I027Xdo4KOc9_:-MzQRCw_1djEizVQ-T6O:bqclsnc) ([raw file](https://github.com/sillsdev/thecombine/blob/5aeba90831ec066099444ec83945ff2f5d3d0fe4/src/backend/index.ts#L547)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Now that this function is more complex, should we rename it? I could see the callers of this function not realizing it now does some extra duplicate/update steps?
</blockquote></details>

That logic has been moved away from here back to where it belongs. It was temporarily here because it was causing a unit test failure in its proper place.

**Comment by johnthagen** [comment]
*[Backend.Tests/Models/WordTests.cs, line 352 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1622#-Mz0YYFc58SQnlVlnc3k:-Mz_Lnyb19vfuDasZZqG:bb6ywmx) ([raw file](https://github.com/sillsdev/thecombine/blob/5aeba90831ec066099444ec83945ff2f5d3d0fe4/Backend.Tests/Models/WordTests.cs#L352)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Added a whitespace-string test to `TestIsBlank`. Sufficient?
</blockquote></details>

LGTM

**Comment by johnthagen** [comment]
*[src/components/DataEntry/DataEntryTable/DataEntryTable.tsx, line 163 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1622#-Mz_N2GeB0A7RKWPtSRx:-Mz_N2GeB0A7RKWPtSRy:bktnq8p) ([raw file](https://github.com/sillsdev/thecombine/blob/820246ab56e67b361e85290866621593c7d421fb/src/components/DataEntry/DataEntryTable/DataEntryTable.tsx#L163)):*
> ```XML
>     const duplicatedId = await backend.getDuplicateId(wordToAdd);
>     if (duplicatedId) {
>       this.addDuplicateWord(wordToAdd, audioURLs, duplicatedId, ignoreRecent);
> ```

Add `await`?

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1622)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[src/components/DataEntry/DataEntryTable/DataEntryTable.tsx, line 163 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1622#-Mz_N2GeB0A7RKWPtSRx:-Mz_SOeR5OCEt2pNHk7U:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/820246ab56e67b361e85290866621593c7d421fb/src/components/DataEntry/DataEntryTable/DataEntryTable.tsx#L163)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Add `await`?
</blockquote></details>

Done.

**Review by johnthagen — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1622)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
