### PR TITLE
Enable seeing definitions in merging

### LINKED ISSUE #1226: Include 'Definition' as an option in The Combine
In situations outside of RWCW where The Combine is being used to merge existing data the Definition field may be used instead of or in addition to gloss.

In order to support this we will need to make several changes.

1. Add Definition as a field in the Sense model ( This should affect MongoDB, Backend, and Frontend)
1.1 Verify that existing projects handle this addition without crashing
2. Import and export Definition from LIFT
3. Add Definition column to Review Entries
4. Add a project setting for enabling the Definition field (make Review entries honor that setting)
5. Add a definition row to the Sense card in Merge entries if the Definition field is turned on
5.1 Give definition and gloss different background colors if the Definition field is turned on
5.2 Add a 'Key' or 'Sample' card to help the user discover what the background colors indicate [Note: This could be done in a follow up issue]

### PR DESCRIPTION
**Pull request by imnasnainaec**
Closes #1226 (part 5)

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1269)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 1 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1269#-MgzklDmEE8Kd2nosVxY:-MgzklDmEE8Kd2nosVxZ:be56crd) ([raw file](https://github.com/sillsdev/thecombine/blob/2a85a5d5c5545a780712a739a5ab31d8e7c96243/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L1)):*
> ```XML
> import { Card, Grid, Paper, Typography } from "@material-ui/core";
> ```

Could we update the user guide with relation to Definitions? https://sillsdev.github.io/TheCombine/project.html?h=def#definitions

**Comment by johnthagen** [comment]
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 88 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1269#-MgzlOI6EVbVNRyLn3T7:-MgzlOI6EVbVNRyLn3T8:b-qwoij) ([raw file](https://github.com/sillsdev/thecombine/blob/2a85a5d5c5545a780712a739a5ab31d8e7c96243/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L88)):*
> ```XML
>   const [word, setWord] = useState<Word | undefined>();
>   useEffect(() => {
>     getWord(props.wordId).then(setWord);
> ```

Does the fact we dropped `await` here have any impact on performance or user experience?

**Comment by johnthagen** [comment]
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 118 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1269#-MgzmLEK-Nn0sQVeU9jZ:-MgzmLEK-Nn0sQVeU9j_:bif72ls) ([raw file](https://github.com/sillsdev/thecombine/blob/2a85a5d5c5545a780712a739a5ab31d8e7c96243/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L118)):*
> ```XML
> }
> 
> function SenseCard(sense: Sense): JSX.Element {
> ```

This is probably something we want to fully do in a follow on refactor PR, but it looks like the correct return type for React function components is `ReactElement` (or `ReactElement | null` is the functional component has a branch where it doesn't render).

See: https://stackoverflow.com/a/57363438

The refactor could be part of https://github.com/sillsdev/TheCombine/issues/1223

**Comment by johnthagen** [comment]
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 118 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1269#-MgzmLEK-Nn0sQVeU9jZ:-MgznPTx2phLi5kXXd4o:bk1mut2) ([raw file](https://github.com/sillsdev/thecombine/blob/2a85a5d5c5545a780712a739a5ab31d8e7c96243/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L118)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This is probably something we want to fully do in a follow on refactor PR, but it looks like the correct return type for React function components is `ReactElement` (or `ReactElement | null` is the functional component has a branch where it doesn't render).

See: https://stackoverflow.com/a/57363438

The refactor could be part of https://github.com/sillsdev/TheCombine/issues/1223

</blockquote></details>

*if the functional component has a branch...

**Comment by johnthagen** [comment]
___
*[src/goals/MergeDupGoal/MergeDupStep/SenseCardContent.tsx, line 16 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1269#-Mgzp3hS7ziYrCKhOISE:-Mgzp3hS7ziYrCKhOISF:br5jv0t) ([raw file](https://github.com/sillsdev/thecombine/blob/2a85a5d5c5545a780712a739a5ab31d8e7c96243/src/goals/MergeDupGoal/MergeDupStep/SenseCardContent.tsx#L16)):*
> ```XML
> import theme from "types/theme";
> 
> interface senseInLanguage {
> ```

Types should start with a capital letter `SenseInLanguage`

**Comment by johnthagen** [comment]
___
*[src/goals/MergeDupGoal/MergeDupStep/SenseCardContent.tsx, line 26 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1269#-MgzpIb414brp_QvwR0K:-MgzpIb414brp_QvwR0L:b79umn6) ([raw file](https://github.com/sillsdev/thecombine/blob/2a85a5d5c5545a780712a739a5ab31d8e7c96243/src/goals/MergeDupGoal/MergeDupStep/SenseCardContent.tsx#L26)):*
> ```XML
>   includeDefinitions: boolean,
>   language: string,
>   displaySep = "; "
> ```

Add `: string` type annotation

**Comment by johnthagen** [comment]
___
*[src/goals/MergeDupGoal/MergeDupStep/SenseCardContent.tsx, line 97 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1269#-Mgzpl948d3CO7Cddv2w:-Mgzpl948d3CO7Cddv2x:b-covgnq) ([raw file](https://github.com/sillsdev/thecombine/blob/2a85a5d5c5545a780712a739a5ab31d8e7c96243/src/goals/MergeDupGoal/MergeDupStep/SenseCardContent.tsx#L97)):*
> ```XML
> 
> // Only show first sense's glosses/definitions; in merging, others deleted as duplicates.
> // Show semantic domains from all seneses.
> ```

Typo: `senses`

**Comment by johnthagen** [comment]
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 1 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1269#-MgztzSYEMKoz7Q45H4F:-MgzqQtg6Wuhc8dTFCqe:bhkihic) ([raw file](https://github.com/sillsdev/thecombine/blob/19806b797462f37871eb1c52f7004e7c7a4a00c8/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L1)):*
> ```XML
> import { Card, Grid, Paper, Typography } from "@material-ui/core";
> ```

Just an observation, but if a user imports a LIFT file with Definitions and never enables Definitions they will never see the Definitions but it will be exported when they export the project.

I think this is the correct behavior so that data isn't lost, but it also could be surprising to someone that data they never saw was exported and sent off (e.g. they also never reviewed it). Perhaps there could be a way to notify the user that Definitions exist, even if they are not being shown?

In practice this probably isn't a big issue, but just something I noticed when testing out. "Definitions Off" doesn't mean "this project has no definitions", it just means their hidden. Perhaps "On/Off" could be "Visible/Hidden"? Not sure.

**Comment by johnthagen** [comment]
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 2 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1269#-MgzuvcS2iTWwY7EMQtq:-MgzuvcS2iTWwY7EMQtr:brf6gds) ([raw file](https://github.com/sillsdev/thecombine/blob/19806b797462f37871eb1c52f7004e7c7a4a00c8/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L2)):*
> ```XML
> import { Card, Grid, Paper, Typography } from "@material-ui/core";
> import { ArrowRightAlt } from "@material-ui/icons";
> ```

Have we tested importing Combine LIFT exports that contain Definitions into another LIFT implementation, such as FLEX?

**Review by johnthagen — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1269)* status: all files reviewed, 8 unresolved discussions (waiting on @imnasnainaec)

**Comment by johnthagen** [comment]
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 3 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1269#-Mgzw-Oo440Ooq4UNAkO:-Mgzw-Oo440Ooq4UNAkP:bojexzi) ([raw file](https://github.com/sillsdev/thecombine/blob/19806b797462f37871eb1c52f7004e7c7a4a00c8/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L3)):*
> ```XML
> import { Card, Grid, Paper, Typography } from "@material-ui/core";
> import { ArrowRightAlt } from "@material-ui/icons";
> import React, { useEffect, useState } from "react";
> ```

Perhaps a follow on, but do we want to enable adding definitions during Data Entry?

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1269)* status: 2 of 10 files reviewed, 5 unresolved discussions (waiting on @imnasnainaec and @johnthagen)

___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 1 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1269#-MgzklDmEE8Kd2nosVxY:-MiaPtn73AUEMm-UBNHm:b6c33cv) ([raw file](https://github.com/sillsdev/thecombine/blob/2a85a5d5c5545a780712a739a5ab31d8e7c96243/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L1)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Could we update the user guide with relation to Definitions? https://sillsdev.github.io/TheCombine/project.html?h=def#definitions
</blockquote></details>

Updated in previous pr that enabled definitions in ReviewEntries.
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 88 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1269#-MgzlOI6EVbVNRyLn3T7:-MiaQh5TAW52diL_srDL:b1js9ld) ([raw file](https://github.com/sillsdev/thecombine/blob/2a85a5d5c5545a780712a739a5ab31d8e7c96243/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L88)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Does the fact we dropped `await` here have any impact on performance or user experience?
</blockquote></details>

We defined it in local async function, but never awaited that function, so I don't think so.
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 118 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1269#-MgzmLEK-Nn0sQVeU9jZ:-MiaQoFfCkdF19Q2IbxW:bfjrcz4) ([raw file](https://github.com/sillsdev/thecombine/blob/2a85a5d5c5545a780712a739a5ab31d8e7c96243/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L118)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

*if the functional component has a branch...
</blockquote></details>

Switched each existing JSX.Element for now.
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 1 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1269#-MgztzSYEMKoz7Q45H4F:-MiaQ9c9AgWBCHIuQlHl:b-1xqtdi) ([raw file](https://github.com/sillsdev/thecombine/blob/19806b797462f37871eb1c52f7004e7c7a4a00c8/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L1)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Just an observation, but if a user imports a LIFT file with Definitions and never enables Definitions they will never see the Definitions but it will be exported when they export the project.

I think this is the correct behavior so that data isn't lost, but it also could be surprising to someone that data they never saw was exported and sent off (e.g. they also never reviewed it). Perhaps there could be a way to notify the user that Definitions exist, even if they are not being shown?

In practice this probably isn't a big issue, but just something I noticed when testing out. "Definitions Off" doesn't mean "this project has no definitions", it just means their hidden. Perhaps "On/Off" could be "Visible/Hidden"? Not sure.
</blockquote></details>

Broader conversation on this matter ongoing...
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 2 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1269#-MgzuvcS2iTWwY7EMQtq:-MiaQIqN7H5-L10_Uvwk:b-8nlap4) ([raw file](https://github.com/sillsdev/thecombine/blob/19806b797462f37871eb1c52f7004e7c7a4a00c8/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L2)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Have we tested importing Combine LIFT exports that contain Definitions into another LIFT implementation, such as FLEX?
</blockquote></details>

Not yet.
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 3 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1269#-Mgzw-Oo440Ooq4UNAkO:-MiaQSsf0IPmxKua4bvh:byppzbc) ([raw file](https://github.com/sillsdev/thecombine/blob/19806b797462f37871eb1c52f7004e7c7a4a00c8/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L3)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Perhaps a follow on, but do we want to enable adding definitions during Data Entry?
</blockquote></details>

Not yet. Data Entry is tailored to RWC, which usually prefers glosses.
___
*[src/goals/MergeDupGoal/MergeDupStep/SenseCardContent.tsx, line 16 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1269#-Mgzp3hS7ziYrCKhOISE:-MiaQuY6-s2PjsOJbtth:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/2a85a5d5c5545a780712a739a5ab31d8e7c96243/src/goals/MergeDupGoal/MergeDupStep/SenseCardContent.tsx#L16)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Types should start with a capital letter `SenseInLanguage`
</blockquote></details>

Done.
___
*[src/goals/MergeDupGoal/MergeDupStep/SenseCardContent.tsx, line 26 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1269#-MgzpIb414brp_QvwR0K:-MiaQvBt1W5JBcam9ITv:b-y7vrkb) ([raw file](https://github.com/sillsdev/thecombine/blob/2a85a5d5c5545a780712a739a5ab31d8e7c96243/src/goals/MergeDupGoal/MergeDupStep/SenseCardContent.tsx#L26)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Add `: string` type annotation
</blockquote></details>

Isn't that implicit?
___
*[src/goals/MergeDupGoal/MergeDupStep/SenseCardContent.tsx, line 97 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1269#-Mgzpl948d3CO7Cddv2w:-MiaQxSW9acueXNs8dT1:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/2a85a5d5c5545a780712a739a5ab31d8e7c96243/src/goals/MergeDupGoal/MergeDupStep/SenseCardContent.tsx#L97)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Typo: `senses`
</blockquote></details>

Done.

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 7 of 8 files at r5, 6 of 7 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1269)* status: all files reviewed (commit messages unreviewed), 5 unresolved discussions (waiting on @johnthagen)

___
*[src/components/DataEntry/DataEntryTable/NewEntry/SenseDialog.tsx, line 29 at r7](https://reviewable.io/reviews/sillsdev/thecombine/1269#-MibYo6eElFgzw14uYcO:-MibYo6eElFgzw14uYcP:b-1k89dk) ([raw file](https://github.com/sillsdev/thecombine/blob/642ef199e2d524f7d4d4d78beb70f188aa3944a7/src/components/DataEntry/DataEntryTable/NewEntry/SenseDialog.tsx#L29)):*
> ```
> 
>         if (reason !== "backdropClick") {
> ```

What was this for?

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1269)* status: all files reviewed (commit messages unreviewed), 5 unresolved discussions (waiting on @johnthagen)

___
*[src/components/DataEntry/DataEntryTable/NewEntry/SenseDialog.tsx, line 29 at r7](https://reviewable.io/reviews/sillsdev/thecombine/1269#-MibYo6eElFgzw14uYcO:-Mib_mqX1F0A4zhn4GtF:b-3ldwr2) ([raw file](https://github.com/sillsdev/thecombine/blob/642ef199e2d524f7d4d4d78beb70f188aa3944a7/src/components/DataEntry/DataEntryTable/NewEntry/SenseDialog.tsx#L29)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> 
>         if (reason !== "backdropClick") {
> ```

What was this for?
</blockquote></details>

It was from a deprecation warning. Previously I did the exact same thing in VernDialog, but I missed it here. (Probably should've been its own pr, as it has nothing to do with the other things in this pr.)

**Review by jasonleenaylor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1269)* status: all files reviewed (commit messages unreviewed), 5 unresolved discussions (waiting on @johnthagen)

**Comment by johnthagen** [comment]
___
*[src/goals/MergeDupGoal/MergeDupStep/SenseCardContent.tsx, line 26 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1269#-MgzpIb414brp_QvwR0K:-MifLfO-6gB0TkX0Zbbq:befiign) ([raw file](https://github.com/sillsdev/thecombine/blob/2a85a5d5c5545a780712a739a5ab31d8e7c96243/src/goals/MergeDupGoal/MergeDupStep/SenseCardContent.tsx#L26)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Isn't that implicit?
</blockquote></details>

Personally, I like the consistency of always having the type annotations everywhere (even if there is a default). If we were to remove the default in the future, we might have an untyped field then?

I don't feel super strong about this though.

**Review by johnthagen — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1269)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
