### PR TITLE
Build "The Combine" Docker images in parallel

### LINKED ISSUE #1594: Build containers in parallel
**Is your feature request related to a problem? Please describe.**

The current build script, `./scripts/build.py` builds the 3 docker containers sequentially.  This is a "downgrade" from the previous build process with `docker-compose`

**Describe the solution you'd like**

Add a `--parallel` option to the build script to run the builds concurrently.

**Acceptance Tests**

Run `./scripts/build.py` with and without the `--parallel` option.  The run with the `--parallel` option should take about as long as just building the frontend (the longest build currently).

### PR DESCRIPTION
**Pull request by jmgrady**
Change the build script to build the frontend, backend, and maintenance components for _The Combine_ as parallel jobs.  By default, the build output is not shown, only the progress.

This mechanism decreases the build time for a clean build by approximately 25%.  If the image is also pushed to AWS ECR, the build time is reduced by approximately 35%.

Closes #1594.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1709)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1709)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`deploy/scripts/utils.py` line 32 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1709#-N9gFK4C-4kD0mqyWzhl:-N9gFK4C-4kD0mqyWzhm:b-dguikm) ([raw file](https://github.com/sillsdev/thecombine/blob/8f387cb12985cec380819ad4cbb4fe8809045014/deploy/scripts/utils.py#L32)):*
> ```Python
>             text=True,
>             check=check_results,
>             cwd=cwd,
> ```

I don't see this new `cwd` argument used anywhere.

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1709)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[`deploy/scripts/utils.py` line 32 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1709#-N9gFK4C-4kD0mqyWzhl:-N9gG4cC-E1-UNUdf3o2:b7hi3i) ([raw file](https://github.com/sillsdev/thecombine/blob/8f387cb12985cec380819ad4cbb4fe8809045014/deploy/scripts/utils.py#L32)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I don't see this new `cwd` argument used anywhere.
</blockquote></details>

It was added in a previous iteration of the `build.py` script.  When I moved to using `subprocess.popen`, I was no longer calling `utils.run_cmd`.  However, it seems like a useful improvement - previously I was calling `os.chdir` and this would not be needed with this addition.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1709)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`deploy/scripts/build.py` line 70 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1709#-N9gIi3J5tj5oPRhU7Bl:-N9gIi3J5tj5oPRhU7Bm:b-g691nf) ([raw file](https://github.com/sillsdev/thecombine/blob/8f387cb12985cec380819ad4cbb4fe8809045014/deploy/scripts/build.py#L70)):*
> ```Python
>             next_job = self.job_list.pop(0)
>             self.output_stream.open()
>             self.error_stream.open()
> ```

Since we open these but never explicitly close them, I assume they'll be automatically closed in cleanup.



_Code quote:_
```Python
            self.output_stream.open()
            self.error_stream.open()
```

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1709)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[`deploy/scripts/build.py` line 70 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1709#-N9gIi3J5tj5oPRhU7Bl:-N9gNybqALyMS7xKzvQ5:b-1ldy6a) ([raw file](https://github.com/sillsdev/thecombine/blob/8f387cb12985cec380819ad4cbb4fe8809045014/deploy/scripts/build.py#L70)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Since we open these but never explicitly close them, I assume they'll be automatically closed in cleanup.
</blockquote></details>

They are `NamedTemporaryFile`s.  They are closed automatically when they go out of scope.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1709)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Pull request merged**
