### PR TITLE
Add GUID for stable lift round trip

### PR DESCRIPTION
**Pull request by jasonleenaylor**
* Add GUID to word model and populate when words
  are created
* Add GUID to frontier if it is found to be missing

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/665)

### CODE REVIEW

**Comment by johnthagen** [comment]
Per discussion, just a note that this might be needed for Senses too.

**Comment by johnthagen** [comment]
___
*[Backend/Controllers/FrontierController.cs, line 51 at r1](https://reviewable.io/reviews/sillsdev/thecombine/665#-MFq1H8DE0VNN5xlOXgy:-MFq1Aa5492IrQTosKJm:b-qmbgzl) ([raw file](https://github.com/sillsdev/thecombine/blob/f316d791a4fba01ca7a21d454617e9c55d093c2e/Backend/Controllers/FrontierController.cs#L51)):*
> ```Smalltalk
>         }
> 
> 		private async Task<object> GetAndRepairFrontier(string projectId)
> ```

Minor. This part of the code is using tabs instead of spaces. `npm run dotnet-format` can fix this automatically.

Install instructions here: https://github.com/sillsdev/TheCombine#getting-started-with-development

**Comment by johnthagen** [comment]
___
*[Backend/Controllers/FrontierController.cs, line 51 at r1](https://reviewable.io/reviews/sillsdev/thecombine/665#-MFq1a5T0Sb9F2_l5dOR:-MFq-ss8D0uKyAbQFcmq:b2nm2db) ([raw file](https://github.com/sillsdev/thecombine/blob/f316d791a4fba01ca7a21d454617e9c55d093c2e/Backend/Controllers/FrontierController.cs#L51)):*
> ```Smalltalk
>         }
> 
> 		private async Task<object> GetAndRepairFrontier(string projectId)
> ```

We should add a `TODO` indicating that this code should eventually be removed when we are satisfied that legacy databases have either been upgraded or retired from new Combine installs.

**Comment by johnthagen** [comment]
___
*[Backend/Models/Word.cs, line 19 at r1](https://reviewable.io/reviews/sillsdev/thecombine/665#-MFq1rxK3-TKSrgMWB1S:-MFq1rxK3-TKSrgMWB1T:b-hqqpl5) ([raw file](https://github.com/sillsdev/thecombine/blob/f316d791a4fba01ca7a21d454617e9c55d093c2e/Backend/Models/Word.cs#L19)):*
> ```Smalltalk
> 
>         [BsonElement("guid")]
>         public Guid? Guid { get; set; }
> ```

We should add a `TODO` that states that eventually we can remove the `?` potential `null`ness of this field once legacy databases have either been upgraded or retired.

**Comment by johnthagen** [comment]
___
*[Backend/Services/LiftApiServices.cs, line 625 at r1](https://reviewable.io/reviews/sillsdev/thecombine/665#-MFq3WexELxy9m9i-i_j:-MFq3WexELxy9m9i-i_k:b-ulljaq) ([raw file](https://github.com/sillsdev/thecombine/blob/f316d791a4fba01ca7a21d454617e9c55d093c2e/Backend/Services/LiftApiServices.cs#L625)):*
> ```Smalltalk
>         public void ProcessFieldDefinition(string tag, LiftMultiText description) { }
> 
> 		/// <summary>
> ```

Minor: Tabs in use. `npm run dotnet-format` to fix.

**Comment by johnthagen** [comment]
___
*[Backend/Services/WordRepository.cs, line 59 at r1](https://reviewable.io/reviews/sillsdev/thecombine/665#-MFq3aZi3DFG9XGxc0Gk:-MFq3aZi3DFG9XGxc0Gl:b-ulljaq) ([raw file](https://github.com/sillsdev/thecombine/blob/f316d791a4fba01ca7a21d454617e9c55d093c2e/Backend/Services/WordRepository.cs#L59)):*
> ```Smalltalk
>         public async Task<Word> Create(Word word)
>         {
> 			if (word.Guid == null || Guid.Empty.Equals(word.Guid))
> ```

Minor: Tabs in use. `npm run dotnet-format` to fix.

**Comment by johnthagen** [comment]
___
*[Backend/Services/LiftApiServices.cs, line 630 at r1](https://reviewable.io/reviews/sillsdev/thecombine/665#-MFq4l8h7XeFXy43J4CU:-MFq4l8h7XeFXy43J4CV:b-27b5zt) ([raw file](https://github.com/sillsdev/thecombine/blob/f316d791a4fba01ca7a21d454617e9c55d093c2e/Backend/Services/LiftApiServices.cs#L630)):*
> ```Smalltalk
> 		/// <param name="sInput"></param>
> 		/// <returns></returns>
> 		public static string MakeSafeXmlAttribute(string sInput)
> ```

Could we simplify our code by replacing this custom function with `SecurityElement.Escape()`?

https://docs.microsoft.com/en-us/dotnet/api/system.security.securityelement.escape?view=netcore-3.1

**Comment by johnthagen** [comment]
___
*[Backend/Models/Word.cs, line 19 at r1](https://reviewable.io/reviews/sillsdev/thecombine/665#-MFq1rxK3-TKSrgMWB1S:-MFq5Od08YPZA60gcWAA:bla1r3m) ([raw file](https://github.com/sillsdev/thecombine/blob/f316d791a4fba01ca7a21d454617e9c55d093c2e/Backend/Models/Word.cs#L19)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

We should add a `TODO` that states that eventually we can remove the `?` potential `null`ness of this field once legacy databases have either been upgraded or retired.
</blockquote></details>

Might also be worth adding some documentation that this field is specifically designed to help make the data compatible once exported into other tools, so as to not confuse developers who might wonder why there is a GUID in addition to the unique mongo ID.

**Comment by johnthagen** [comment]
___
*[Backend/Models/Word.cs, line 144 at r2](https://reviewable.io/reviews/sillsdev/thecombine/665#-MFqDAh92iCAOmpvVAlQ:-MFqDAhA-YA5QCMpMgGI:b-n3surt) ([raw file](https://github.com/sillsdev/thecombine/blob/ff2e8d4ee1352e2804d312b488a1a84f5ec0d1d2/Backend/Models/Word.cs#L144)):*
> ```Smalltalk
>                     other.Id.Equals(Id) &&
>                     this.ContentEquals(other) &&
>                     other.Guid == this.Guid &&
> ```

Not sure what our convention is around `this`. Most places in the backend we infer it and don't write it explicitly, but I don't know if you have a preferred style we try to follow.

Coming from Python where it is required to use `self`, I'm used using `this`, but I know most C#/Java style guides seem to discourage it.

**Comment by johnthagen** [comment]
___
*[Backend/Services/LiftApiServices.cs, line 625 at r1](https://reviewable.io/reviews/sillsdev/thecombine/665#-MFq3WexELxy9m9i-i_j:-MFqDms92cv94AZpNyNd:bb6ywmx) ([raw file](https://github.com/sillsdev/thecombine/blob/f316d791a4fba01ca7a21d454617e9c55d093c2e/Backend/Services/LiftApiServices.cs#L625)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Minor: Tabs in use. `npm run dotnet-format` to fix.
</blockquote></details>

LGTM

**Comment by johnthagen** [comment]
___
*[Backend/Controllers/FrontierController.cs, line 51 at r1](https://reviewable.io/reviews/sillsdev/thecombine/665#-MFq1H8DE0VNN5xlOXgy:-MFqDrHP0PkpBduj6B0d:b-qeo66o) ([raw file](https://github.com/sillsdev/thecombine/blob/f316d791a4fba01ca7a21d454617e9c55d093c2e/Backend/Controllers/FrontierController.cs#L51)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Minor. This part of the code is using tabs instead of spaces. `npm run dotnet-format` can fix this automatically.

Install instructions here: https://github.com/sillsdev/TheCombine#getting-started-with-development
</blockquote></details>

One set of tabs slipped through.

**Comment by johnthagen** [comment]
___
*[Backend/Models/Word.cs, line 188 at r2](https://reviewable.io/reviews/sillsdev/thecombine/665#-MFqEoIACOq7PXvqEFWh:-MFqEoIACOq7PXvqEFWi:b9eutid) ([raw file](https://github.com/sillsdev/thecombine/blob/ff2e8d4ee1352e2804d312b488a1a84f5ec0d1d2/Backend/Models/Word.cs#L188)):*
> ```Smalltalk
> 
>         [BsonElement("guid")]
>         public Guid? Guid { get; set; }
> ```

Same comment as above to add a TODO to remove `?` when legacy data is migrated. Might even be worth also opening an issue referencing these three locations so that that can be fixed in tandem.

**Comment by johnthagen** [comment]
___
*[Backend/Controllers/FrontierController.cs, line 66 at r2](https://reviewable.io/reviews/sillsdev/thecombine/665#-MFqJOWdE651kra66aIJ:-MFqJOWdE651kra66aIK:bt26xhm) ([raw file](https://github.com/sillsdev/thecombine/blob/ff2e8d4ee1352e2804d312b488a1a84f5ec0d1d2/Backend/Controllers/FrontierController.cs#L66)):*
> ```Smalltalk
> 
>             foreach (var word in frontier)
>             {
> ```

Should we also recursively walk `word.History` and fix up all of the old saved `Word`s in the Project?

**Comment by jasonleenaylor** [comment]
___
*[Backend/Controllers/FrontierController.cs, line 66 at r2](https://reviewable.io/reviews/sillsdev/thecombine/665#-MFqJOWdE651kra66aIJ:-MFqNuiT7aOpSzl4UWl9:b-97ej9m) ([raw file](https://github.com/sillsdev/thecombine/blob/ff2e8d4ee1352e2804d312b488a1a84f5ec0d1d2/Backend/Controllers/FrontierController.cs#L66)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Should we also recursively walk `word.History` and fix up all of the old saved `Word`s in the Project?
</blockquote></details>

I don't think that is necessary since only the frontier is exported. I don't think we are going to retroactively support undo on this workshop data, so we should be safe.

**Comment by jasonleenaylor** [comment]
___
*[Backend/Models/Word.cs, line 144 at r2](https://reviewable.io/reviews/sillsdev/thecombine/665#-MFqDAh92iCAOmpvVAlQ:-MFqOtb58RzmvwKzAUwh:b-29x0wp) ([raw file](https://github.com/sillsdev/thecombine/blob/ff2e8d4ee1352e2804d312b488a1a84f5ec0d1d2/Backend/Models/Word.cs#L144)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Not sure what our convention is around `this`. Most places in the backend we infer it and don't write it explicitly, but I don't know if you have a preferred style we try to follow.

Coming from Python where it is required to use `self`, I'm used using `this`, but I know most C#/Java style guides seem to discourage it.
</blockquote></details>

Yes, I prefer not, not sure why I used it here.

**Comment by johnthagen** [comment]
I confirmed that importing projects *into* the Combine with this change already in place creates GUIDs on all Words (Frontier and History), as expected with the `Word` constructor updates in place.

**Comment by johnthagen** [comment]
___
*[Backend/Services/LiftApiServices.cs, line 630 at r1](https://reviewable.io/reviews/sillsdev/thecombine/665#-MFq4l8h7XeFXy43J4CU:-MFqRs2r2rM4U_DbxAfS:beqoixo) ([raw file](https://github.com/sillsdev/thecombine/blob/f316d791a4fba01ca7a21d454617e9c55d093c2e/Backend/Services/LiftApiServices.cs#L630)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Probably. I was working fast and looked up how we did it in some other code. But that other code is very old.
</blockquote></details>

Now that this function only calls another, should we just remove it and inline `SecurityElement.Escape` where needed?

**Comment by jasonleenaylor** [comment]
___
*[Backend/Services/LiftApiServices.cs, line 630 at r1](https://reviewable.io/reviews/sillsdev/thecombine/665#-MFq4l8h7XeFXy43J4CU:-MFqSmXw8_M_kD5Hbh9a:b-g48c9y) ([raw file](https://github.com/sillsdev/thecombine/blob/f316d791a4fba01ca7a21d454617e9c55d093c2e/Backend/Services/LiftApiServices.cs#L630)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Now that this function only calls another, should we just remove it and inline `SecurityElement.Escape` where needed?
</blockquote></details>

Actually I prefer to keep the naming for code clarity. Not everyone will recognize SecurityElement.Escape and understand it. Only us grizzled veterans.

**Comment by johnthagen** [comment]
___
*[Backend/Services/LiftApiServices.cs, line 630 at r1](https://reviewable.io/reviews/sillsdev/thecombine/665#-MFq4l8h7XeFXy43J4CU:-MFqTFpxCc6-3aHiFXvE:bb6ywmx) ([raw file](https://github.com/sillsdev/thecombine/blob/f316d791a4fba01ca7a21d454617e9c55d093c2e/Backend/Services/LiftApiServices.cs#L630)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Actually I prefer to keep the naming for code clarity. Not everyone will recognize SecurityElement.Escape and understand it. Only us grizzled veterans.
</blockquote></details>

LGTM

**Comment by johnthagen** [comment]
___
*[Backend/Controllers/FrontierController.cs, line 51 at r1](https://reviewable.io/reviews/sillsdev/thecombine/665#-MFq1H8DE0VNN5xlOXgy:-MFqV5qZ0X_gHXyrFtri:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/f316d791a4fba01ca7a21d454617e9c55d093c2e/Backend/Controllers/FrontierController.cs#L51)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

One set of tabs slipped through.
</blockquote></details>

Done

**Pull request merged**
