### PR TITLE
Install TheCombine on a NUC in Docker containers

### PR DESCRIPTION
**Pull request by jmgrady**
This PR updates the configuration and installation scripts to install TheCombine on an Intel NUC.  This PR only add the changes so that the NUC creates the WiFi access point and sets up TheCombine to be accessible through the AP.  TheCombine is setup with a self-signed certificate for the NUC - a future PR will replace this with a certificate that is downloaded from the AWS S3 service.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1050)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 7 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1050)* status: 7 of 28 files reviewed, 3 unresolved discussions (waiting on @jmgrady)

___
*[deploy/group_vars/nuc/main.yml, line 46 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUsmTIBC_-gDoGz5Q4C:-MUsmTIBC_-gDoGz5Q4D:b-ofnrd1) ([raw file](https://github.com/sillsdev/thecombine/blob/236685ff66f05e4f1ee89be3404d6a383a095de9/deploy/group_vars/nuc/main.yml#L46)):*
> ```YAML
> # ap_passphrase is defined in ./vault.yml
> ap_gateway: "10.10.10.1"
> ap_hostname: "{{ansible_hostname}}"
> ```

Where/how is `ansible_hostname` defined? It always appears in the files as `{{ansible_hostname}}` so I don't know when it's assigned.
___
*[deploy/roles/docker_install/tasks/main.yml, line 63 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUsluJ316pCf-bjrvfd:-MUsluJ47rQvkrB2YWFb:bnirv6g) ([raw file](https://github.com/sillsdev/thecombine/blob/236685ff66f05e4f1ee89be3404d6a383a095de9/deploy/roles/docker_install/tasks/main.yml#L63)):*
> ```
> - name: print compose check results
>   debug:
>     var: compose_version
> ```
Should this perhaps have an accompanying `msg` (https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html#parameters), or is the format of the printed variable sufficiently self-evident?
___
*[deploy/roles/wifi_ap/tasks/install.yml, line 13 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUsnT7H7N6bhnohCeUL:-MUsnT7IBDEGv88Y-hgs:bu5fczn) ([raw file](https://github.com/sillsdev/thecombine/blob/236685ff66f05e4f1ee89be3404d6a383a095de9/deploy/roles/wifi_ap/tasks/install.yml#L13)):*
> ```
> #- debug:
> #    var: ansible_facts.services
> ```
Perhaps delete, add a comment for when this would be uncommented, or restore with a `verbosity` parameter (https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html#parameters) so it can conditionally appear.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 3 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1050)* status: 10 of 28 files reviewed, 5 unresolved discussions (waiting on @jmgrady)

___
*[deploy/roles/wifi_ap/files/create_ap/bash_completion, line 145 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUstM1J0B0nwxInnnov:-MUstM1J0B0nwxInnnow:b-cjyfn9) ([raw file](https://github.com/sillsdev/thecombine/blob/236685ff66f05e4f1ee89be3404d6a383a095de9/deploy/roles/wifi_ap/files/create_ap/bash_completion#L145)):*
> ```
>         --dhcp-dns)
>             # Not going to implement
> ```
It looks like this has been implemented with `DHCP_DNS`, so should `# Not going to implement` become `# No Options`?
___
*[deploy/roles/wifi_ap/files/create_ap/bash_completion, line 154 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUssvh1B8vCmxlrqNiu:-MUssvh1B8vCmxlrqNiv:bgxy05j) ([raw file](https://github.com/sillsdev/thecombine/blob/236685ff66f05e4f1ee89be3404d6a383a095de9/deploy/roles/wifi_ap/files/create_ap/bash_completion#L154)):*
> ```
>         -g)
>             # Not going to implement
> ```
It looks like this has been implemented with `GATEWAY`, so should `# Not going to implement` become `# No Options`?

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1050)* status: 10 of 28 files reviewed, 5 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

___
*[deploy/group_vars/nuc/main.yml, line 46 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUsmTIBC_-gDoGz5Q4C:-MUst1uxADQUBYq9mGgY:b-5imb5w) ([raw file](https://github.com/sillsdev/thecombine/blob/236685ff66f05e4f1ee89be3404d6a383a095de9/deploy/group_vars/nuc/main.yml#L46)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Where/how is `ansible_hostname` defined? It always appears in the files as `{{ansible_hostname}}` so I don't know when it's assigned.
</blockquote></details>

It is part of the Ansible environment that Ansible builds when it gathers the facts about the target.
___
*[deploy/roles/docker_install/tasks/main.yml, line 63 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUsluJ316pCf-bjrvfd:-MUsu2lF8q168BS-4wse:b-lrssu0) ([raw file](https://github.com/sillsdev/thecombine/blob/236685ff66f05e4f1ee89be3404d6a383a095de9/deploy/roles/docker_install/tasks/main.yml#L63)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> - name: print compose check results
>   debug:
>     var: compose_version
> ```
Should this perhaps have an accompanying `msg` (https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html#parameters), or is the format of the printed variable sufficiently self-evident?
</blockquote></details>

Actually, this should be removed.  As the module name suggests, it is for debugging, not production.

As for the debug module, it can have a `var` or a `msg` - it's up to the person doing the debugging.  Normally, it's clear enough but you can make it clearer with the `msg` value and put the variable in the message, e.g.:
```
  msg: "The Docker Compose version number is {{ compose_version }}"
```
___
*[deploy/roles/wifi_ap/files/create_ap/bash_completion, line 145 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUstM1J0B0nwxInnnov:-MUsvCk27B6wa53hMH3o:b4ui5hj) ([raw file](https://github.com/sillsdev/thecombine/blob/236685ff66f05e4f1ee89be3404d6a383a095de9/deploy/roles/wifi_ap/files/create_ap/bash_completion#L145)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>         --dhcp-dns)
>             # Not going to implement
> ```
It looks like this has been implemented with `DHCP_DNS`, so should `# Not going to implement` become `# No Options`?
</blockquote></details>

This is code from https://github.com/oblique/create_ap and has not been modified
___
*[deploy/roles/wifi_ap/files/create_ap/bash_completion, line 154 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUssvh1B8vCmxlrqNiu:-MUsvIkZA5dPpRJRSc4H:b-tqv4d9) ([raw file](https://github.com/sillsdev/thecombine/blob/236685ff66f05e4f1ee89be3404d6a383a095de9/deploy/roles/wifi_ap/files/create_ap/bash_completion#L154)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>         -g)
>             # Not going to implement
> ```
It looks like this has been implemented with `GATEWAY`, so should `# Not going to implement` become `# No Options`?
</blockquote></details>

This is code from https://github.com/oblique/create_ap and has not been modified.
___
*[deploy/roles/wifi_ap/tasks/install.yml, line 13 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUsnT7H7N6bhnohCeUL:-MUsvRxH9w7kD77yw-x8:blmdd1c) ([raw file](https://github.com/sillsdev/thecombine/blob/236685ff66f05e4f1ee89be3404d6a383a095de9/deploy/roles/wifi_ap/tasks/install.yml#L13)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> #- debug:
> #    var: ansible_facts.services
> ```
Perhaps delete, add a comment for when this would be uncommented, or restore with a `verbosity` parameter (https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html#parameters) so it can conditionally appear.
</blockquote></details>

I will delete it.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 5 of 28 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1050)* status: 16 of 28 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

___
*[deploy/roles/wifi_ap/files/create_ap/create_ap.conf, line 30 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUsyEOQ91IL7KRFo2yc:-MUsyEOQ91IL7KRFo2yd:b9vpgnf) ([raw file](https://github.com/sillsdev/thecombine/blob/36c944e20da2c13932be87497643bacc065e559f/deploy/roles/wifi_ap/files/create_ap/create_ap.conf#L30)):*
> ```
> USE_PSK=0
> DOMAIN=local
> ADDN_HOSTS=/etc/create_ap/create_ap.hosts
> ```

`ADDN_HOSTS` is directly under `ETC_HOSTS` in `create_ap`.
___
*[deploy/roles/wifi_ap/files/create_ap/README.md, line 37 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUt-3gN5RkRyvPbodLw:-MUt-3gN5RkRyvPbodLx:b-r4hgl) ([raw file](https://github.com/sillsdev/thecombine/blob/36c944e20da2c13932be87497643bacc065e559f/deploy/roles/wifi_ap/files/create_ap/README.md#L37)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> ### Generic
>     git clone https://github.com/oblique/create_ap
>     cd create_ap
>     make install
> ```
</details>

Since this is not how it is installed within TheCombine, perhaps we should replace this section with a statement that it is modified from `https://github.com/oblique/create_ap`

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1050)* status: 16 of 28 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

___
*[deploy/roles/wifi_ap/files/create_ap/create_ap.conf, line 30 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUsyEOQ91IL7KRFo2yc:-MUt1B5s2oqEu9cnWbwH:b-pekyts) ([raw file](https://github.com/sillsdev/thecombine/blob/36c944e20da2c13932be87497643bacc065e559f/deploy/roles/wifi_ap/files/create_ap/create_ap.conf#L30)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`ADDN_HOSTS` is directly under `ETC_HOSTS` in `create_ap`.
</blockquote></details>

How about if I add a `.\deploy/roles/wifi_ap/files/README.md` that explains that the files in the `create_ap` directory are installed without modification from [oblique/create_ap](https://github.com/oblique/create_ap)?  I will also update the contents with the latest from `create_ap` and verify that everything still works as expected.
___
*[deploy/roles/wifi_ap/files/create_ap/README.md, line 37 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUt-3gN5RkRyvPbodLw:-MUt23yVEI6c5jQ4j3tO:b-q64pkt) ([raw file](https://github.com/sillsdev/thecombine/blob/36c944e20da2c13932be87497643bacc065e559f/deploy/roles/wifi_ap/files/create_ap/README.md#L37)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> ### Generic
>     git clone https://github.com/oblique/create_ap
>     cd create_ap
>     make install
> ```
Since this is not how it is installed within TheCombine, perhaps we should replace this section with a statement that it is modified from `https://github.com/oblique/create_ap`
</blockquote></details>

See above.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1050)* status: 16 of 28 files reviewed, 5 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

___
*[deploy/roles/wifi_ap/files/create_ap/create_ap.conf, line 1 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUt2OPEEJBQcs0czT09:-MUt2OPEEJBQcs0czT0A:bx0gcgy) ([raw file](https://github.com/sillsdev/thecombine/blob/36c944e20da2c13932be87497643bacc065e559f/deploy/roles/wifi_ap/files/create_ap/create_ap.conf#L1)):*

Do we need this file, if there is a template used to create `/etc/create_ap/create_ap.conf`?
___
*[deploy/roles/wifi_ap/files/create_ap/create_ap.conf, line 30 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUsyEOQ91IL7KRFo2yc:-MUt20Ed1ZEu6Bpl9NMI:b-5ppla5) ([raw file](https://github.com/sillsdev/thecombine/blob/36c944e20da2c13932be87497643bacc065e559f/deploy/roles/wifi_ap/files/create_ap/create_ap.conf#L30)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

How about if I add a `.\deploy/roles/wifi_ap/files/README.md` that explains that the files in the `create_ap` directory are installed without modification from [oblique/create_ap](https://github.com/oblique/create_ap)?  I will also update the contents with the latest from `create_ap` and verify that everything still works as expected.
</blockquote></details>

I thought this file was modified to add DOMAIN and ADDN_HOSTS. I was just commenting on the inconsistent order of the modification.
___
*[deploy/roles/wifi_ap/templates/etc_hosts.j2, line 2 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUt1Aa25KvONZua2j-a:-MUt1Aa25KvONZua2j-b:b-tzi163) ([raw file](https://github.com/sillsdev/thecombine/blob/36c944e20da2c13932be87497643bacc065e559f/deploy/roles/wifi_ap/templates/etc_hosts.j2#L2)):*
> ```
> 127.0.0.1	localhost
> 127.0.1.1	{{ ansible_hostname }}
> ```
Should these two lines have tabs when we have spaces everywhere else?
___
*[deploy/roles/wifi_ap/templates/etc_hosts.j2, line 9 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUt1OQs0DKGLEZl6zh7:-MUt1OQs0DKGLEZl6zh8:bxosccy) ([raw file](https://github.com/sillsdev/thecombine/blob/36c944e20da2c13932be87497643bacc065e559f/deploy/roles/wifi_ap/templates/etc_hosts.j2#L9)):*
> ```
> {{ ap_gateway }}  {{ ap_hostname }}.{{ ap_domain }} {{ ap_hostname }}
> ```
Double-space then single-space? (Also in `create_ap.hosts.j2`.)

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 4 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1050)* status: 20 of 28 files reviewed, 8 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

___
*[deploy/roles/create_admin_user/tasks/main.yml, line 50 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUtMs1B8yD7-bhkcmuV:-MUtMs1B8yD7-bhkcmuW:b-hrkyn6) ([raw file](https://github.com/sillsdev/thecombine/blob/36c944e20da2c13932be87497643bacc065e559f/deploy/roles/create_admin_user/tasks/main.yml#L50)):*
> ```
>     owner: "{{ combine_user }}"
>     group: "{{ combine_group }}"
>     mode: 0600
> ```
Are these necessary if the file already has the desired permissions?
___
*[deploy/roles/wifi_ap/defaults/main.yml, line 6 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUtN4r1DeO83OFp1OCo:-MUtN4r2-FWfvQ6BpnFE:btycb9b) ([raw file](https://github.com/sillsdev/thecombine/blob/36c944e20da2c13932be87497643bacc065e559f/deploy/roles/wifi_ap/defaults/main.yml#L6)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> ap_ssid: "{{ansible_hostname}}_ap"
> ap_passphrase: "Set a new passphrase in your vault file."
> ap_gateway: "10.10.10.1"
> ap_domain: example.com
> ap_hostname: "{{ansible_hostname}}"
> ```
</details>


For consistency, `{{ ansible_hostname }}`?
___
*[deploy/roles/wifi_ap/tasks/main.yml, line 4 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUtPSRj1yy14R9BbWpW:-MUtPSRk5RwSh4_etqIx:b-9al7dd) ([raw file](https://github.com/sillsdev/thecombine/blob/36c944e20da2c13932be87497643bacc065e559f/deploy/roles/wifi_ap/tasks/main.yml#L4)):*
> ```
> - { include: install.yml, tags: [install] }
> - meta: flush_handlers
> - { include: test.yml, tags: [test] }
> ```
`test.yml` has `tags: test` at the end of the file, but `install.yml` has no `tags`.

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1050)* status: 15 of 31 files reviewed, 6 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

___
*[deploy/roles/create_admin_user/tasks/main.yml, line 50 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUtMs1B8yD7-bhkcmuV:-MUtk2ot8U5TFjW0cem0:b-wl3aih) ([raw file](https://github.com/sillsdev/thecombine/blob/36c944e20da2c13932be87497643bacc065e559f/deploy/roles/create_admin_user/tasks/main.yml#L50)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>     owner: "{{ combine_user }}"
>     group: "{{ combine_group }}"
>     mode: 0600
> ```
Are these necessary if the file already has the desired permissions?
</blockquote></details>

This ensures that the file will have the necessary permissions.  If the file has the correct permissions, Ansible will not do anything.
___
*[deploy/roles/wifi_ap/defaults/main.yml, line 6 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUtN4r1DeO83OFp1OCo:-MUtkOY74Wyd5fO_xppf:bq0enqm) ([raw file](https://github.com/sillsdev/thecombine/blob/36c944e20da2c13932be87497643bacc065e559f/deploy/roles/wifi_ap/defaults/main.yml#L6)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> ap_ssid: "{{ansible_hostname}}_ap"
> ap_passphrase: "Set a new passphrase in your vault file."
> ap_gateway: "10.10.10.1"
> ap_domain: example.com
> ap_hostname: "{{ansible_hostname}}"
> ```

For consistency, `{{ ansible_hostname }}`?
</blockquote></details>

Done.
Not just consistency, Ansible usually complains if the spaces are not there!
___
*[deploy/roles/wifi_ap/files/create_ap/create_ap.conf, line 1 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUt2OPEEJBQcs0czT09:-MUt4w3r1Da8So5zl-cE:b-xvtwsx) ([raw file](https://github.com/sillsdev/thecombine/blob/36c944e20da2c13932be87497643bacc065e559f/deploy/roles/wifi_ap/files/create_ap/create_ap.conf#L1)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Do we need this file, if there is a template used to create `/etc/create_ap/create_ap.conf`?
</blockquote></details>

The intent was to mimic the git project.  Originally, it was a submodule of _TheCombine_ but we did not want the dependency on the external project.

As I look at the differences from our current implementation and the latest on github, I see that other changes have crept in as well.

If you agree, I will update this directory so that it is a copy of the master branch of create_ap and move the configurations to our templates, etc.
___
*[deploy/roles/wifi_ap/files/create_ap/create_ap.conf, line 30 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUsyEOQ91IL7KRFo2yc:-MUt4Sv4DkL68TsuY9AE:b4tiln1) ([raw file](https://github.com/sillsdev/thecombine/blob/36c944e20da2c13932be87497643bacc065e559f/deploy/roles/wifi_ap/files/create_ap/create_ap.conf#L30)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I thought this file was modified to add DOMAIN and ADDN_HOSTS. I was just commenting on the inconsistent order of the modification.
</blockquote></details>

That could be.  I can put it back (which is what will happen if I update with the latest).  The actual configuration is generated from `./deploy/roles/wifi_ap/templates/create_ap.conf.j2` (as you noted above).
___
*[deploy/roles/wifi_ap/tasks/main.yml, line 4 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUtPSRj1yy14R9BbWpW:-MUtm3DE0qUzAgXVteBx:b-juao1i) ([raw file](https://github.com/sillsdev/thecombine/blob/36c944e20da2c13932be87497643bacc065e559f/deploy/roles/wifi_ap/tasks/main.yml#L4)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> - { include: install.yml, tags: [install] }
> - meta: flush_handlers
> - { include: test.yml, tags: [test] }
> ```
`test.yml` has `tags: test` at the end of the file, but `install.yml` has no `tags`.
</blockquote></details>

The test tag should not be in the test.yml - that would cause it to just see if the ap interface is there without checking that the service is running first.
___
*[deploy/roles/wifi_ap/templates/etc_hosts.j2, line 2 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUt1Aa25KvONZua2j-a:-MUt7_-_6YFNVfar3Kbh:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/36c944e20da2c13932be87497643bacc065e559f/deploy/roles/wifi_ap/templates/etc_hosts.j2#L2)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> 127.0.0.1	localhost
> 127.0.1.1	{{ ansible_hostname }}
> ```
Should these two lines have tabs when we have spaces everywhere else?
</blockquote></details>

Done.
___
*[deploy/roles/wifi_ap/templates/etc_hosts.j2, line 9 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUt1OQs0DKGLEZl6zh7:-MUt8ECq5TYdKHa-4x-A:b-7qq5cr) ([raw file](https://github.com/sillsdev/thecombine/blob/36c944e20da2c13932be87497643bacc065e559f/deploy/roles/wifi_ap/templates/etc_hosts.j2#L9)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> {{ ap_gateway }}  {{ ap_hostname }}.{{ ap_domain }} {{ ap_hostname }}
> ```
Double-space then single-space? (Also in `create_ap.hosts.j2`.)
</blockquote></details>

Changed to 7 spaces to be more consistent with the results of changing the tab to spaces above.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 28 files at r1, 10 of 16 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1050)* status: 21 of 23 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[deploy/roles/wifi_ap/templates/etc_hosts.j2, line 2 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUt1Aa25KvONZua2j-a:-MUxrkcDA-yOfm6bwm0V:bkbhk5j) ([raw file](https://github.com/sillsdev/thecombine/blob/36c944e20da2c13932be87497643bacc065e559f/deploy/roles/wifi_ap/templates/etc_hosts.j2#L2)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Now the file is an odd mix of tabs and spaces.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 2 of 16 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1050)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1050)* status: 22 of 23 files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[deploy/roles/wifi_ap/templates/etc_hosts.j2, line 2 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1050#-MUt1Aa25KvONZua2j-a:-MUxuqO0AQ74y0XKyJgq:b90usui) ([raw file](https://github.com/sillsdev/thecombine/blob/36c944e20da2c13932be87497643bacc065e559f/deploy/roles/wifi_ap/templates/etc_hosts.j2#L2)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Now the file is an odd mix of tabs and spaces.
</blockquote></details>

Done.  No more tabs.  Sorry about that, chief!

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1050)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
