### PR TITLE
Create GitHub Actions to deploy The Combine

### LINKED ISSUE #1092: Move CI/CD to GitHub Actions
Investigate moving CI/CD to using GitHub Actions instead of TeamCity.  Items to consider:
- Will it give more flexibility in defining the build machine configuration?
- How do we automatically deploy to QA machines behind a firewall?

### PR DESCRIPTION
**Pull request by jmgrady**
Create GitHub actions to build and deploy _The Combine_ to QA and Live servers.  The QA Server is updated with each update of the `master` branch; the Live server is updated with each update of the `live` branch.

Closes #1092

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1490)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[.github/actions/combine-build/action.yml, line 18 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1490#-Mq_W8vl6q6VyGI0mFuC:-Mq_W8vl6q6VyGI0mFuD:bd4dgj5) ([raw file](https://github.com/sillsdev/thecombine/blob/30b14c5bfea8419a274f55f93a48c069aa280161/.github/actions/combine-build/action.yml#L18)):*
> ```YAML
>     required: true
>   aws_default_region:
>     description: "Default accessiblility zone for AWS ECR images"
> ```

Type `accessibility`

**Comment by johnthagen** [comment]
___
*[.github/actions/combine-build/action.yml, line 1 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1490#-Mq_WHfk8xviRigRQFF-:-Mq_WHfk8xviRigRQFF0:b-dic5at) ([raw file](https://github.com/sillsdev/thecombine/blob/30b14c5bfea8419a274f55f93a48c069aa280161/.github/actions/combine-build/action.yml#L1)):*
> ```YAML
> name: "Combine Build"
> ```

Is there a certain convention that GitHub prescribes to put these actions into `actions` instead of `workflows` like the others?

**Comment by johnthagen** [comment]
___
*[.github/actions/combine-deploy-update/action.yml, line 21 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1490#-Mq_XPJT6iTTzd-BH-pf:-Mq_XPJT6iTTzd-BH-pg:b-btptst) ([raw file](https://github.com/sillsdev/thecombine/blob/30b14c5bfea8419a274f55f93a48c069aa280161/.github/actions/combine-deploy-update/action.yml#L21)):*
> ```YAML
>         sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
>         kubectl version
>       shell: bash
> ```

To avoid repeating `bash` many times, it looks like you can set `bash` as a `default` for the entire action:

https://github.community/t/declaring-a-default-shell-and-environment-variables-across-all-steps-in-a-job-github-actions/16228/2

**Comment by johnthagen** [comment]
___
*[.github/actions/combine-build/action.yml, line 1 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1490#-Mq_WHfk8xviRigRQFF-:-Mq_Xdd6ABf05AP72xDQ:b5crz0y) ([raw file](https://github.com/sillsdev/thecombine/blob/30b14c5bfea8419a274f55f93a48c069aa280161/.github/actions/combine-build/action.yml#L1)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Is there a certain convention that GitHub prescribes to put these actions into `actions` instead of `workflows` like the others?
</blockquote></details>

Oh, I see. These are reusable parts of other workflows. Got it.

**Review by johnthagen — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1490)* status: all files reviewed, 3 unresolved discussions (waiting on @jmgrady)

**Comment by johnthagen** [comment]
___
*[.github/actions/combine-build/action.yml, line 18 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1490#-Mq_W8vl6q6VyGI0mFuC:-Mq_XwiG0XZCGi3lydLZ:b-z2xtsn) ([raw file](https://github.com/sillsdev/thecombine/blob/30b14c5bfea8419a274f55f93a48c069aa280161/.github/actions/combine-build/action.yml#L18)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Type `accessibility`
</blockquote></details>

Typo**

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1490)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @johnthagen)

___
*[.github/actions/combine-build/action.yml, line 1 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1490#-Mq_WHfk8xviRigRQFF-:-Mq__bD83ZN_Tm3X2wQa:bajokuz) ([raw file](https://github.com/sillsdev/thecombine/blob/30b14c5bfea8419a274f55f93a48c069aa280161/.github/actions/combine-build/action.yml#L1)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Oh, I see. These are reusable parts of other workflows. Got it.
</blockquote></details>

F.Y.I., the section of the documentation titled [Choosing a Location For Your Action](https://docs.github.com/en/actions/creating-actions/about-custom-actions#choosing-a-location-for-your-action) says it is mostly a convention - they can go anywhere in the repository.  If we think they can be used by other projects, or if we design them to, then we should put them in a separate github project.  One thing that was _not_ clear to me was that the actual definition of the action _must_ be in a file named `action.yml` or `action.yaml` (See https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions) and this YAML file must be in a directory that has the name of the action (as referenced by the workflow).
___
*[.github/actions/combine-build/action.yml, line 18 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1490#-Mq_W8vl6q6VyGI0mFuC:-Mq__EcM0WvHZxYCJ47R:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/30b14c5bfea8419a274f55f93a48c069aa280161/.github/actions/combine-build/action.yml#L18)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Typo**
</blockquote></details>

Done.
___
*[.github/actions/combine-deploy-update/action.yml, line 21 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1490#-Mq_XPJT6iTTzd-BH-pf:-Mq_s-IADDzqn-_V7kcF:b-a11f59) ([raw file](https://github.com/sillsdev/thecombine/blob/30b14c5bfea8419a274f55f93a48c069aa280161/.github/actions/combine-deploy-update/action.yml#L21)):*
I am not sure that this will work so I am going to test it by adding the `deploy_GH_actions` branch to the triggers.  Please do not approve until I have removed it!  Thanks.

The reason I think it may not work is that `defaults` is not listed as an allowed element of `runs` in the [documentation](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-actions) for the local actions.  In addition, it does not say anything about it being inherited from the calling workflow and it does say:
> runs.steps[*].shell
Optional The shell where you want to run the command. You can use any of the shells listed here. Required if run is set.

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1490)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @johnthagen)

___
*[.github/actions/combine-deploy-update/action.yml, line 21 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1490#-Mq_XPJT6iTTzd-BH-pf:-Mq_xkG1DxfWshLbOngb:b-s4a30u) ([raw file](https://github.com/sillsdev/thecombine/blob/30b14c5bfea8419a274f55f93a48c069aa280161/.github/actions/combine-deploy-update/action.yml#L21)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

I am not sure that this will work so I am going to test it by adding the `deploy_GH_actions` branch to the triggers.  Please do not approve until I have removed it!  Thanks.

The reason I think it may not work is that `defaults` is not listed as an allowed element of `runs` in the [documentation](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-actions) for the local actions.  In addition, it does not say anything about it being inherited from the calling workflow and it does say:
> runs.steps[*].shell
Optional The shell where you want to run the command. You can use any of the shells listed here. Required if run is set.

</blockquote></details>

Did not work:
```
Error: GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. /home/runner/work/TheCombine/TheCombine/./.github/actions/combine-build/action.yml (Line: 27, Col: 7): Required property is missing: shell,/home/runner/work/TheCombine/TheCombine/./.github/actions/combine-build/action.yml (Line: 31, Col: 7): Required property is missing: shell
   at GitHub.DistributedTask.ObjectTemplating.TemplateValidationErrors.Check()
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
```
I have backed out the change.

**Review by johnthagen — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1490)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Review by johnthagen — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1490)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Pull request merged**
