### PR TITLE
Port ExportProject to use redux-toolkit; Remove redux from CreateProject

### PR DESCRIPTION
**Pull request by imnasnainaec**
Parts of #1953

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2747)

### CODE REVIEW

**Review by jmgrady — APPROVED** [review]
> Reviewed 4 of 11 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2747)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[`src/components/ProjectExport/Redux/ExportProjectActions.ts` line 21 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2747#-NhrgoKL0D_Gvb5TBvpZ:-NhrgoKL0D_Gvb5TBvp_:b-ebq4nq) ([raw file](https://github.com/sillsdev/TheCombine/blob/1b112c24ac8cc0189c964a2ba9436deadfb8cec3/src/components/ProjectExport/Redux/ExportProjectActions.ts#L21)):*
> ```XML
> export function downloading(projectId: string): PayloadAction {
>   return downloadingAction(projectId);
> }
> ```

Since these names are inherited I am fine with leaving them but `exporting` and `downloading` do not sound like actions - they describe the current status of the project.  Better names might be `exportProject` and `downloadProject`.  Your call - you work with these more than I.



_Suggestion:_
```XML
export function exporting(projectId: string): PayloadAction {
  return exportingAction(projectId);
}

export function downloading(projectId: string): PayloadAction {
  return downloadingAction(projectId);
}`
```
___
*[`src/components/ProjectExport/Redux/tests/ExportProjectActions.test.tsx` line 1 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2747#-NhritBf0DHmeckal9ua:-NhritBg5mtQKfX5YA5G:bwe3k6u) ([raw file](https://github.com/sillsdev/TheCombine/blob/1b112c24ac8cc0189c964a2ba9436deadfb8cec3/src/components/ProjectExport/Redux/tests/ExportProjectActions.test.tsx#L1)):*
> ```XML
> import configureMockStore from "redux-mock-store";
> ```

I think a better test is to use the actual redux store and verify that the state changes.  This verifies that the correct action is dispatched by the dispatch methods but if you use the actual store, you can also test the action and reducer code at the same time.

You can use `setupStore()` from `store` to create the redux store.  Since you don't need to have preset values (none of the reducers depend on the current state) you won't need to create a preloaded state.  Even that is not difficult - you can see an example in `src/goals/MergeDuplicates/Redux/tests/MergeDupsReducer.test.tsx`.



_Code quote:_
```XML
import configureMockStore from "redux-mock-store";
```

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2747)* status: 13 of 15 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[`src/components/ProjectExport/Redux/ExportProjectActions.ts` line 21 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2747#-NhrgoKL0D_Gvb5TBvpZ:-Ni00wss59NjC103Eqx8:b95xeuj) ([raw file](https://github.com/sillsdev/TheCombine/blob/1b112c24ac8cc0189c964a2ba9436deadfb8cec3/src/components/ProjectExport/Redux/ExportProjectActions.ts#L21)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Since these names are inherited I am fine with leaving them but `exporting` and `downloading` do not sound like actions - they describe the current status of the project.  Better names might be `exportProject` and `downloadProject`.  Your call - you work with these more than I.
</blockquote></details>

The action is only to update the status to "exporting" or "downloading".
___
*[`src/components/ProjectExport/Redux/tests/ExportProjectActions.test.tsx` line 1 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2747#-NhritBf0DHmeckal9ua:-Ni01BjbBI4QhJ7Jozr5:bcvjgzp) ([raw file](https://github.com/sillsdev/TheCombine/blob/1b112c24ac8cc0189c964a2ba9436deadfb8cec3/src/components/ProjectExport/Redux/tests/ExportProjectActions.test.tsx#L1)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

I think a better test is to use the actual redux store and verify that the state changes.  This verifies that the correct action is dispatched by the dispatch methods but if you use the actual store, you can also test the action and reducer code at the same time.

You can use `setupStore()` from `store` to create the redux store.  Since you don't need to have preset values (none of the reducers depend on the current state) you won't need to create a preloaded state.  Even that is not difficult - you can see an example in `src/goals/MergeDuplicates/Redux/tests/MergeDupsReducer.test.tsx`.
</blockquote></details>

Good idea. Done.

**Review by jmgrady — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2747)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[`src/components/ProjectExport/Redux/tests/ExportProjectActions.test.tsx` line 33 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2747#-Ni01t1e-ku_o2cYU3s8:-Ni01t1e-ku_o2cYU3s9:b-u94ymp) ([raw file](https://github.com/sillsdev/TheCombine/blob/7badb1d71068467b9b3fb9a2ee215e4fc21be3d8/src/components/ProjectExport/Redux/tests/ExportProjectActions.test.tsx#L33)):*
> ```XML
>       const mockStore = setupStore();
>       mockDownloadList.mockResolvedValueOnce({});
>       await mockStore.dispatch<any>(asyncDownloadExport(mockProjId));
> ```

Since you are using a store with the actual type, you don't need to use `<any>` with the `dispatch` functions, i.e. can be changed to:
```
await mockStore.dispatch(asyncDownloadExport(mockProjId));
```
(and probably should be).

**Review by jmgrady — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2747)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
