### PR TITLE
Merge delete

### LINKED ISSUE #1452: [MergeDuplicates] Add trashcan to allow deleting of senses
Acceptance Tests:

1. A sense can be dragged into the trashcan and it is deleted
2. The delete can be undone in the undo merges screen
3. If the last sense of an entry is deleted the column goes away

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #1452

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1481)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[src/goals/MergeDupGoal/MergeDupStep/DragDropComponents/MergeDragDrop.tsx, line 21 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1481#-MqZupTT5_ro3PanPdHC:-MqZupTT5_ro3PanPdHD:b-3tsppe) ([raw file](https://github.com/sillsdev/thecombine/blob/247f4cb132943774b9eb78c6b8b8f76198bb9eed/src/goals/MergeDupGoal/MergeDupStep/DragDropComponents/MergeDragDrop.tsx#L21)):*
> ```XML
> export const trashId = "trash-drop";
> 
> interface MergeDragDropProps {}
> ```

Since this `interface` is now empty, should we remove this and the `props`  argument below? `props` is no longer used.

**Comment by johnthagen** [comment]
___
*[src/goals/MergeDupGoal/Redux/MergeDupActions.ts, line 163 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1481#-MqZvMiSAXiVOewURzi9:-MqZvMiSAXiVOewURziA:b-nyy5o0) ([raw file](https://github.com/sillsdev/thecombine/blob/247f4cb132943774b9eb78c6b8b8f76198bb9eed/src/goals/MergeDupGoal/Redux/MergeDupActions.ts#L163)):*
> ```XML
> 
>     // Word to be deleted if all senses deleted.
>     //To-Do
> ```

Extremely minor, but in the rest of our code base we write this as `TODO`.

**Review by johnthagen — COMMENTED** [review]
> Reviewed 3 of 7 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1481)* status: all files reviewed, 2 unresolved discussions (waiting on @imnasnainaec)

**Comment by johnthagen** [comment]
___
*[-- commits, line 41 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1481#-Mq_eDueAwU3HpsPPsGW):*
If you delete all the words in a merge set, you can no longer continue continue on with the merge (no save/skip button any longer).

**Comment by johnthagen** [comment]
___
*[-- commits, line 47 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1481#-Mq_hz6E607VHS6UHw6d):*
The Trash can icon could be a little bigger? It feels a bit small when the other cards on that page are so large.

**Comment by johnthagen** [comment]
___
*[-- commits, line 48 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1481#-Mq_i8P7AJs8tcTR3xnT):*
Should there be a confirmation when you delete something? I could see that being annoying if you are deleting lots of Words, but if you accidently do it, I could see it being nice to have a chance to catch it.

**Comment by johnthagen** [comment]
___
*[-- commits, line 49 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1481#-Mq_iVMt6sHnFmtulAi1):*
Should the trash can be aligned at the bottom of the page so it is harder to accidently drag into?

**Comment by johnthagen** [comment]
___
*[-- commits, line 43 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1481#-Mq_fGP2CK6DkKoKoAqD):*
A hover text for the trach can could be help 
("Delete Word") so it's clearer in the UI what will happen.

**Comment by johnthagen** [comment]
___
*[-- commits, line 53 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1481#-Mq_j3Y8-ZcKEfd1IpZ7):*
I think the answer is probably no, but should the Merge Duplicates Goal tell you what words you deleted during a "session"? This "history" as part of the goal "action" can't be seen afterwards like everything else.

**Comment by johnthagen** [comment]
___
*[Backend/Models/MergeWords.cs, line 20 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1481#-Mq_ljy94rh9J4nLuMS7:-Mq_ljy94rh9J4nLuMS8:bw24v4p) ([raw file](https://github.com/sillsdev/thecombine/blob/45c0fc550d8c9b2137c764c39e1600df77d6d604/Backend/Models/MergeWords.cs#L20)):*
> ```Smalltalk
>         public List<MergeSourceWord> Children { get; set; }
>         // If the children are to be deleted instead of merged, use NoParent = True.
>         public bool NoParent { get; set; }
> ```

Since we can't use `Delete` as we want. Maybe we name this `DeleteWord` instead?

**Comment by johnthagen** [comment]
___
*[Backend/Models/MergeWords.cs, line 20 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1481#-Mq_n0dSCmAlASUhzlwg:-Mq_n0dTB3E7_ebbKery:boy336s) ([raw file](https://github.com/sillsdev/thecombine/blob/45c0fc550d8c9b2137c764c39e1600df77d6d604/Backend/Models/MergeWords.cs#L20)):*
> ```Smalltalk
>         public List<MergeSourceWord> Children { get; set; }
>         // If the children are to be deleted instead of merged, use NoParent = True.
>         public bool NoParent { get; set; }
> ```

This should be marked `[Required]`

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1481)* status: 9 of 19 files reviewed, 8 unresolved discussions (waiting on @imnasnainaec and @johnthagen)

___
*[-- commits, line 47 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1481#-Mq_hz6E607VHS6UHw6d):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

The Trash can icon could be a little bigger? It feels a bit small when the other cards on that page are so large.
</blockquote></details>

Done.
___
*[-- commits, line 53 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1481#-Mq_j3Y8-ZcKEfd1IpZ7):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I think the answer is probably no, but should the Merge Duplicates Goal tell you what words you deleted during a "session"? This "history" as part of the goal "action" can't be seen afterwards like everything else.



</blockquote></details>

The deleted words (children) are on the left of the arrow and the new words (parents), if any, on the right.
___
*[Backend/Models/MergeWords.cs, line 20 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1481#-Mq_n0dSCmAlASUhzlwg:-Mq_wcTZC4z6TM_aQs_1:b-qq85np) ([raw file](https://github.com/sillsdev/thecombine/blob/45c0fc550d8c9b2137c764c39e1600df77d6d604/Backend/Models/MergeWords.cs#L20)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This should be marked `[Required]`
</blockquote></details>

I had left that off so that it would be `?: boolean` on the frontend.
___
*[src/goals/MergeDupGoal/MergeDupStep/DragDropComponents/MergeDragDrop.tsx, line 21 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1481#-MqZupTT5_ro3PanPdHC:-Mq_xCpQ-hAE3QHXomrL:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/247f4cb132943774b9eb78c6b8b8f76198bb9eed/src/goals/MergeDupGoal/MergeDupStep/DragDropComponents/MergeDragDrop.tsx#L21)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Since this `interface` is now empty, should we remove this and the `props`  argument below? `props` is no longer used.
</blockquote></details>

Done.

**Review by johnthagen — COMMENTED** [review]
> Reviewed 8 of 9 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1481)* status: all files reviewed, 6 unresolved discussions (waiting on @imnasnainaec and @johnthagen)

**Comment by johnthagen** [comment]
___
*[Backend/Models/MergeWords.cs, line 20 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1481#-Mq_n0dSCmAlASUhzlwg:-Mqa4n8M9gBJSd9t0BlU:b-22a5ph) ([raw file](https://github.com/sillsdev/thecombine/blob/45c0fc550d8c9b2137c764c39e1600df77d6d604/Backend/Models/MergeWords.cs#L20)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I had left that off so that it would be `?: boolean` on the frontend.
</blockquote></details>

My philosophy is to have APIs be as strict/rigid as possible to allow both sides to avoid as many "empty" checks as possible.

Would it be possible set this as required, but have the frontend default to `false` or similar?

**Comment by johnthagen** [comment]
___
*[-- commits, line 53 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1481#-Mq_j3Y8-ZcKEfd1IpZ7):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

The deleted words (children) are on the left of the arrow and the new words (parents), if any, on the right.
</blockquote></details>

I deleted one of the two senses for all of the words I was shown, and the UI looks as follows:



I guess to me it didn't seem obvious things were deleted?

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1481)* status: 10 of 22 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @johnthagen)

___
*[-- commits, line 41 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1481#-Mq_eDueAwU3HpsPPsGW):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

If you delete all the words in a merge set, you can no longer continue continue on with the merge (no save/skip button any longer).



</blockquote></details>

Fixed
___
*[-- commits, line 43 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1481#-Mq_fGP2CK6DkKoKoAqD):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

A hover text for the trach can could be help 
("Delete Word") so it's clearer in the UI what will happen.
</blockquote></details>

Done
___
*[-- commits, line 48 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1481#-Mq_i8P7AJs8tcTR3xnT):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Should there be a confirmation when you delete something? I could see that being annoying if you are deleting lots of Words, but if you accidently do it, I could see it being nice to have a chance to catch it.
</blockquote></details>

Done
___
*[-- commits, line 49 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1481#-Mq_iVMt6sHnFmtulAi1):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Should the trash can be aligned at the bottom of the page so it is harder to accidently drag into?
</blockquote></details>

Done
___
*[-- commits, line 53 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1481#-Mq_j3Y8-ZcKEfd1IpZ7):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I deleted one of the two senses for all of the words I was shown, and the UI looks as follows:



I guess to me it didn't seem obvious things were deleted?
</blockquote></details>

I cannot reproduce this behavior
___
*[Backend/Models/MergeWords.cs, line 20 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1481#-Mq_ljy94rh9J4nLuMS7:-Mqokq5w8OaTWcvD5rGk:b-3m13sl) ([raw file](https://github.com/sillsdev/thecombine/blob/45c0fc550d8c9b2137c764c39e1600df77d6d604/Backend/Models/MergeWords.cs#L20)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Since we can't use `Delete` as we want. Maybe we name this `DeleteWord` instead?
</blockquote></details>

Used `DeleteOnly` as agreed on in Slack.
___
*[Backend/Models/MergeWords.cs, line 20 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1481#-Mq_n0dSCmAlASUhzlwg:-Mqokxqt8oUI7CStWm_t:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/45c0fc550d8c9b2137c764c39e1600df77d6d604/Backend/Models/MergeWords.cs#L20)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

My philosophy is to have APIs be as strict/rigid as possible to allow both sides to avoid as many "empty" checks as possible.

Would it be possible set this as required, but have the frontend default to `false` or similar?
</blockquote></details>

Done

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 11 of 12 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1481)* status: 21 of 22 files reviewed, 4 unresolved discussions (waiting on @imnasnainaec and @johnthagen)

___
*[src/goals/MergeDupGoal/MergeDupStep/DragDropComponents/MergeDragDrop.tsx, line 70 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1481#-MqowL0B5FFGfNKLwmtj:-MqowL0B5FFGfNKLwmtk:bi80sej) ([raw file](https://github.com/sillsdev/thecombine/blob/3c492f88e089e88cbe7f71e7f46b1d64abc94029/src/goals/MergeDupGoal/MergeDupStep/DragDropComponents/MergeDragDrop.tsx#L70)):*
> ```
> deleteConfirm()
> ```
Maybe doDelete, performDelete, something in the name that indicates that this will execute the deletion. The name should focus on the purpose of the method, not on the handler we use it with.
___
*[src/goals/MergeDupGoal/Redux/tests/MergeDupActions.test.tsx, line 71 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1481#-MqozBkbAIHHgv9UC7PE:-MqozBkbAIHHgv9UC7PF:b-7ll08r) ([raw file](https://github.com/sillsdev/thecombine/blob/3c492f88e089e88cbe7f71e7f46b1d64abc94029/src/goals/MergeDupGoal/Redux/tests/MergeDupActions.test.tsx#L71)):*
> ```
> words
> ```
I didn't see this used outside of 'data'.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1481)* status: 19 of 22 files reviewed, 4 unresolved discussions (waiting on @jasonleenaylor and @johnthagen)

___
*[src/goals/MergeDupGoal/MergeDupStep/DragDropComponents/MergeDragDrop.tsx, line 70 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1481#-MqowL0B5FFGfNKLwmtj:-MqpBJop4Bz5GigC4q4f:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/3c492f88e089e88cbe7f71e7f46b1d64abc94029/src/goals/MergeDupGoal/MergeDupStep/DragDropComponents/MergeDragDrop.tsx#L70)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> deleteConfirm()
> ```
Maybe doDelete, performDelete, something in the name that indicates that this will execute the deletion. The name should focus on the purpose of the method, not on the handler we use it with.
</blockquote></details>

Done.
___
*[src/goals/MergeDupGoal/Redux/tests/MergeDupActions.test.tsx, line 71 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1481#-MqozBkbAIHHgv9UC7PE:-MqpBMPd-Knv44mOJED8:b-tttw7k) ([raw file](https://github.com/sillsdev/thecombine/blob/3c492f88e089e88cbe7f71e7f46b1d64abc94029/src/goals/MergeDupGoal/Redux/tests/MergeDupActions.test.tsx#L71)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> words
> ```
I didn't see this used outside of 'data'.
</blockquote></details>

Tidied.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 1 of 12 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1481)* status: all files reviewed, 2 unresolved discussions (waiting on @johnthagen)

**Review by jasonleenaylor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1481)* status: all files reviewed, 2 unresolved discussions (waiting on @johnthagen)

**Review by jasonleenaylor — APPROVED** [review]
> Dismissed @johnthagen from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1481)* status: all files reviewed, 1 unresolved discussion (waiting on @johnthagen)

**Review by jasonleenaylor — APPROVED** [review]
> Dismissed @johnthagen from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1481)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
