### PR TITLE
Remove stale docs

### PR DESCRIPTION
**Pull request by johnthagen**
- Remove stale docs that have not been updated for 1.5 years. These docs will likely continue to rot and likely the best place to get definitely information about the structure of the project and API is in the respective backend and frontend source projects where things will be current.

Question: Should we also migrate `docs/meeting_notes` and `docs/Requirements for RWC Appliance.pdf` to somewhere else such as Google Drive?

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/963)

### CODE REVIEW

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 2 of 59 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/963)* status: 2 of 59 files reviewed, all discussions resolved (waiting on @johnthagen)

**Comment by jasonleenaylor** [comment]
I think keeping the historic docs in the repo is better then losing them somewhere else. We are capturing things from user interaction in github issues now so we won't be adding to that. If we decide they are completely useless to us we can remove them.

**Comment by johnthagen** [comment]
@jasonleenaylor Did you have any thoughts about  `docs/meeting_notes` and and `docs/Requirements for RWC Appliance.pdf`? Could those be migrated somewhere else?

**Comment by jasonleenaylor** [comment]
I do want to look over those docs again to make sure we have everything important captured in issues.

**Review by johnthagen — COMMENTED** [review]
> Reviewed 59 of 59 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/963)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
