### PR TITLE
Add some button/field ids.

### LINKED ISSUE #1304: Add IDs to buttons and other interactive elements
The automated Build Verification Tests we're writing are more difficult to design and more fragile when our buttons lack stable IDs.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #1304

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1310)

### CODE REVIEW

**Comment by WeJamUS** [comment]
___
*[src/components/DataEntry/DataEntryTable/EntryCellComponents/EntryNote.tsx, line 24 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1310#-MiNJsIF8hgG_lU7Kenn:-MiNJsIF8hgG_lU7Keno:b-676xld) ([raw file](https://github.com/sillsdev/thecombine/blob/1b48372e977efbb1fef76a04c537600eb62368b7/src/components/DataEntry/DataEntryTable/EntryCellComponents/EntryNote.tsx#L24)):*
> ```XML
>       <Tooltip
>         title={
>           props.noteText ? props.noteText : <Translate id="addWords.addNote" />
> ```

Should noteText be an optional prop if it's being checked for falseyness?

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1310)* status: 0 of 57 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @WeJamUS)

___
*[src/components/DataEntry/DataEntryTable/EntryCellComponents/EntryNote.tsx, line 24 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1310#-MiNJsIF8hgG_lU7Kenn:-MiNKyTrEwUL8dsYP3Mz:by9lp65) ([raw file](https://github.com/sillsdev/thecombine/blob/1b48372e977efbb1fef76a04c537600eb62368b7/src/components/DataEntry/DataEntryTable/EntryCellComponents/EntryNote.tsx#L24)):*
<details><summary><i>Previously, WeJamUS (James Wu) wrote…</i></summary><blockquote>

Should noteText be an optional prop if it's being checked for falseyness?
</blockquote></details>

Good question. If we were only checking for `null` or `undefined` (and then we could just write `props.noteText ?? <Translate id="addWords.addNote" />`) then that would be the case. However, the check here is intended for the empty string `""` and we're not allowing `undefined` for the `prop` in the first place..

**Review by WeJamUS — COMMENTED** [review]
> Reviewed 14 of 17 files at r1, 2 of 2 files at r2, 41 of 41 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1310)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @imnasnainaec)

**Review by WeJamUS — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1310)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @imnasnainaec)

**Review by WeJamUS — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1310)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
