### PR TITLE
Functions, button to fill all empty guids.

### LINKED ISSUE #1014: Create Mongo script to determine if any projects are missing Word.Guid or Sense.Guid
As part of #1013, it would be good to create a short Mongo script to run on our active databases to check to see if any projects are missing GUIDs on their `Word`s or `Sense`s.

We need to check for the following items:

- FrontierCollection & WordCollection
  - All entities have a top level `guid` key
  - All `senses[]` have a `guid` key

An example of a **correct** entry:

```json
{
"_id":{"$oid":"60200badc239e4231ef4cfa0"},
"guid":{"$binary":"2ljEdo4ZTkyhZmWBTOrfKw==","$type":"3"},
"vernacular":"a",
"plural":"",
"senses":[{"Glosses":[{"Language":"en","Def":"n"}],"SemanticDomains":[{"Name":"Universe, creation","_id":"1","Description":""}],"accessibility":"Active","guid":{"$binary":"vBbCqfVFG0ud8hFmBqYs0g==","$type":"3"}}],
"audio":[],
"created":"2021-02-07T15:47:57.5811167Z",
"modified":"2021-02-07T15:47:57.5811317Z",
"accessibility":"Active",
"history":[],
"partOfSpeech":"",
"editedBy":[],
"otherField":"",
"projectId":"60200b88c239e4231ef4cf9d",
"note":{"Language":"en","Text":""}
}
```

I don't think this needs to be checked into the repo as it will be a one-time-use script.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Closes #1014 

Backend function for filling empty guids, using the same guid for all words in the history of a frontier/deleted word.
Hacky frontend button in SiteSettings to trigger the backend.

This is an alternative to #1014
I think this requires `Word.Guid` to be nullable, or at least not automatically filled with a random `new Guid()`, so it must be used without #1013.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1037)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1037)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[Backend/Services/WordRepository.cs, line 114 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1037#-MUQQFpQBXAF7zig34CF:-MUQQFpQBXAF7zig34CG:bp10nr) ([raw file](https://github.com/sillsdev/thecombine/blob/c028c7a3e252ddd5fb56e3f8cac6c5b11ed1b1f6/Backend/Services/WordRepository.cs#L114)):*
> ```
> return await UpdateWord(word);
> ```
Are there any consequences of calling UpdateWord if nothing has changed?

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1037)* status: all files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor)

___
*[Backend/Services/WordRepository.cs, line 114 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1037#-MUQQFpQBXAF7zig34CF:-MUQTojV11kog7sRbwp0:b3774rq) ([raw file](https://github.com/sillsdev/thecombine/blob/c028c7a3e252ddd5fb56e3f8cac6c5b11ed1b1f6/Backend/Services/WordRepository.cs#L114)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> return await UpdateWord(word);
> ```
Are there any consequences of calling UpdateWord if nothing has changed?
</blockquote></details>

It will perform an unnecessary replacement of the word with itself. There's no consequences I can think of or have seen in my tests. Still, I can have `PopulateWordGuids` return a `bool` to indicate whether anything changed, if we want to avoid unnecessary updates.

**Comment by johnthagen** [comment]
@imnasnainaec Technically, this would never need to actually be merged into `master`, correct? We could just review and then deploy the branch directly to our servers to, run the function to update everything and then re-deploy the latest release back onto it?

**Comment by imnasnainaec** [comment]
> @imnasnainaec Technically, this would never need to actually be merged into `master`, correct? We could just review and then deploy the branch directly to our servers to, run the function to update everything and then re-deploy the latest release back onto it?

Yes.

**Comment by johnthagen** [comment]
___
*[Backend/Services/WordRepository.cs, line 145 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1037#-MUTrS3qEOval5WppZ9u:-MUTrS3qEOval5WppZ9v:b-k5o97m) ([raw file](https://github.com/sillsdev/thecombine/blob/c028c7a3e252ddd5fb56e3f8cac6c5b11ed1b1f6/Backend/Services/WordRepository.cs#L145)):*
> ```Smalltalk
>             foreach (var w in frontierWords)
>             {
>                 Console.WriteLine(w.Guid);
> ```

Generally we'd take out print lines like this, but since this MR is not planned to be merged, probably not a huge deal.

**Comment by johnthagen** [comment]
___
*[Backend/Services/WordRepository.cs, line 121 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1037#-MUTreSzCIxZkt9Bj5SI:-MUTreSzCIxZkt9Bj5SJ:b-e5tbnr) ([raw file](https://github.com/sillsdev/thecombine/blob/c028c7a3e252ddd5fb56e3f8cac6c5b11ed1b1f6/Backend/Services/WordRepository.cs#L121)):*
> ```Smalltalk
>         {
>             PopulateWordGuids(word);
>             var idsToUpdate = new List<string>(word.History);
> ```

Can be simplified to `var idsToUpdate = new List<string>(word.History) {word.Id};`

**Comment by johnthagen** [comment]
> I think this requires Word.Guid to be nullable, or at least not automatically filled with a random new Guid(), so it must be used without #1013.

Yes, #1013 at a minimum removes `PopulateWordGuids()`, which is used in this PR, so we cannot merge these two together.

**Comment by johnthagen** [comment]
___
*[Backend/Services/WordRepository.cs, line 121 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1037#-MUTreSzCIxZkt9Bj5SI:-MUTswYu7Gil1xuxR7i9:b-jum7nf) ([raw file](https://github.com/sillsdev/thecombine/blob/bad4cf99ef7ffdefa2c77bce5229a81576ce14a3/Backend/Services/WordRepository.cs#L121)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Can be simplified to `var idsToUpdate = new List<string>(word.History) {word.Id};`
</blockquote></details>

This is called "collection initializer". Rider pointed it out to me.

**Comment by johnthagen** [comment]
___
*[Backend/Services/WordRepository.cs, line 162 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1037#-MUTtfFA32kxDiKzqgYq:-MUTtfFA32kxDiKzqgYr:bw8dib3) ([raw file](https://github.com/sillsdev/thecombine/blob/bad4cf99ef7ffdefa2c77bce5229a81576ce14a3/Backend/Services/WordRepository.cs#L162)):*
> ```Smalltalk
>             foreach (var w in allWords)
>             {
>                 success &= await PopulateGuidsAndUpdateWord(w);
> ```

Since this should in theory catch "all" words not in the Frontier, we don't need to worry about following the `.History`, right?

**Comment by johnthagen** [comment]
___
*[src/components/SiteSettings/SiteSettingsComponent.tsx, line 14 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1037#-MUTvC-XCyXdyG7YoChL:-MUTvC-XCyXdyG7YoChM:b-xyy9dy) ([raw file](https://github.com/sillsdev/thecombine/blob/6148c90744d1f312502fd57c2020643abbf9befd/src/components/SiteSettings/SiteSettingsComponent.tsx#L14)):*
> ```XML
>   return (
>     <Grid container justify="center" spacing={6}>
>       <Button onClick={populateAllGuids}>Populate Guids</Button>
> ```

This probably doesn't matter because this is a temporary PR, but the button was hard for me to find initially because it wasn't styled blue like other buttons.

**Review by johnthagen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1037)* status: all files reviewed, 5 unresolved discussions (waiting on @imnasnainaec and @jasonleenaylor)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1037)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @jasonleenaylor and @johnthagen)

___
*[Backend/Services/WordRepository.cs, line 121 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1037#-MUTreSzCIxZkt9Bj5SI:-MUU4bIi7Yh6pFncgPxC:b9ldnc3) ([raw file](https://github.com/sillsdev/thecombine/blob/6148c90744d1f312502fd57c2020643abbf9befd/Backend/Services/WordRepository.cs#L121)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This is called "collection initializer". Rider pointed it out to me.
</blockquote></details>

Cool, thanks.
___
*[Backend/Services/WordRepository.cs, line 145 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1037#-MUTrS3qEOval5WppZ9u:-MUU4eYACMHY9xi4A8_K:bss4a2b) ([raw file](https://github.com/sillsdev/thecombine/blob/6148c90744d1f312502fd57c2020643abbf9befd/Backend/Services/WordRepository.cs#L145)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Generally we'd take out print lines like this, but since this MR is not planned to be merged, probably not a huge deal.
</blockquote></details>

Removed.
___
*[Backend/Services/WordRepository.cs, line 162 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1037#-MUTtfFA32kxDiKzqgYq:-MUU4hmT5uO4ZkzfYV-q:bapsh8) ([raw file](https://github.com/sillsdev/thecombine/blob/6148c90744d1f312502fd57c2020643abbf9befd/Backend/Services/WordRepository.cs#L162)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Since this should in theory catch "all" words not in the Frontier, we don't need to worry about following the `.History`, right?
</blockquote></details>

We want to chase the history to try to have the same guid on all predecessors of a word.
___
*[src/components/SiteSettings/SiteSettingsComponent.tsx, line 14 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1037#-MUTvC-XCyXdyG7YoChL:-MUU4o7HAULaa3TyfYyK:bt2vr1b) ([raw file](https://github.com/sillsdev/thecombine/blob/6148c90744d1f312502fd57c2020643abbf9befd/src/components/SiteSettings/SiteSettingsComponent.tsx#L14)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This probably doesn't matter because this is a temporary PR, but the button was hard for me to find initially because it wasn't styled blue like other buttons.



</blockquote></details>

Fixed.

**Comment by johnthagen** [comment]
___
*[Backend/Controllers/WordController.cs, line 37 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1037#-MUU9dinCg56lm7MP2um:-MUU9dioE7keFxqhyUxM:bamip9f) ([raw file](https://github.com/sillsdev/thecombine/blob/31f65d15852dc9d382ab989f24c112b96e226aa3/Backend/Controllers/WordController.cs#L37)):*
> ```Smalltalk
>         public async Task<IActionResult> Get(string projectId)
>         {
>             if (projectId == "populateguids")
> ```

We need to add a TODO comment to remove this branch when no longer needed.

**Comment by johnthagen** [comment]
___
*[Backend/Services/WordRepository.cs, line 162 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1037#-MUU9rg-BmDftZDv_0sX:-MUU9rg-BmDftZDv_0sY:bvuvejc) ([raw file](https://github.com/sillsdev/thecombine/blob/31f65d15852dc9d382ab989f24c112b96e226aa3/Backend/Services/WordRepository.cs#L162)):*
> ```Smalltalk
>             }
> 
>             return success;
> ```

As discussed, it might be worth a console line output here saying "Guid population complete", so that @jmgrady can see this in his Docker logs.

**Comment by johnthagen** [comment]
___
*[src/backend/index.tsx, line 197 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1037#-MUUA12XAM-Prt82jGUT:-MUUA12XAM-Prt82jGUU:b-t3nrei) ([raw file](https://github.com/sillsdev/thecombine/blob/31f65d15852dc9d382ab989f24c112b96e226aa3/src/backend/index.tsx#L197)):*
> ```XML
> }
> 
> export async function populateAllGuids() {
> ```

Should add a comment saying this function should be removed.

**Comment by johnthagen** [comment]
___
*[src/components/SiteSettings/SiteSettingsComponent.tsx, line 14 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1037#-MUUA73R7_n9MtQlWQIp:-MUUA73R7_n9MtQlWQIq:bsy1i4d) ([raw file](https://github.com/sillsdev/thecombine/blob/31f65d15852dc9d382ab989f24c112b96e226aa3/src/components/SiteSettings/SiteSettingsComponent.tsx#L14)):*
> ```XML
>   return (
>     <Grid container justify="center" spacing={6}>
>       <Button onClick={populateAllGuids} variant="contained" color="primary">
> ```

Should add a quick comment saying this `Button` should be removed.

**Review by johnthagen — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1037)* status: all files reviewed, 5 unresolved discussions (waiting on @imnasnainaec and @jasonleenaylor)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1037)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @jasonleenaylor, @jmgrady, and @johnthagen)

___
*[Backend/Controllers/WordController.cs, line 37 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1037#-MUU9dinCg56lm7MP2um:-MUUC1Yd0aPe-H7VKdsU:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/31f65d15852dc9d382ab989f24c112b96e226aa3/Backend/Controllers/WordController.cs#L37)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

We need to add a TODO comment to remove this branch when no longer needed.
</blockquote></details>

Done.
___
*[Backend/Services/WordRepository.cs, line 162 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1037#-MUU9rg-BmDftZDv_0sX:-MUUC2p6-LH1L7WP2t3m:b-vsu6i3) ([raw file](https://github.com/sillsdev/thecombine/blob/31f65d15852dc9d382ab989f24c112b96e226aa3/Backend/Services/WordRepository.cs#L162)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

As discussed, it might be worth a console line output here saying "Guid population complete", so that @jmgrady can see this in his Docker logs.
</blockquote></details>

I put that into the controller function.
___
*[src/backend/index.tsx, line 197 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1037#-MUUA12XAM-Prt82jGUT:-MUUC9iJ5EFLCSc0Vgkb:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/31f65d15852dc9d382ab989f24c112b96e226aa3/src/backend/index.tsx#L197)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Should add a comment saying this function should be removed.
</blockquote></details>

Done.
___
*[src/components/SiteSettings/SiteSettingsComponent.tsx, line 14 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1037#-MUUA73R7_n9MtQlWQIp:-MUUCEyaCxNT9-ti9gFB:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/31f65d15852dc9d382ab989f24c112b96e226aa3/src/components/SiteSettings/SiteSettingsComponent.tsx#L14)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Should add a quick comment saying this `Button` should be removed.
</blockquote></details>

Done.

**Review by johnthagen — APPROVED** [review]
> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1037)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
