### PR TITLE
Add LGTM badges to README

### PR DESCRIPTION
**Pull request by johnthagen**
Add LGTM badges to README to encourage high code quality

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/686)

### CODE REVIEW

**Comment by imnasnainaec** [comment]
Preview: https://github.com/sillsdev/TheCombine/tree/lgtm-badges#the-combine
image

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/686)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @johnthagen)

*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/686#-MGOItfZAzwoBr1jx-eq:-MGOItfZAzwoBr1jx-er:b11rnyt) (no related file):*
What about c#?

---

**Comment by johnthagen** [comment]
*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/686#-MGOItfZAzwoBr1jx-eq:-MGOKHT1ELNrPWP2jp2f:b-o33e32) (no related file):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

What about c#?
</blockquote></details>

LGTM doesn't support code "scores" for C# yet: https://lgtm.com/projects/g/sillsdev/TheCombine/ci/

---

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/686)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
