### PR TITLE
Update deploy scripts

### LINKED ISSUE #1838: Set "Pull Policy" to "Always" for QA and Production Servers
**Describe the bug**

In the rare case where an image is updated instead of built with a new tag, restarting the deployments will not pull the new image.

**To Reproduce**

1. Delete a "bad" release from GitHub
2. Push a fix for the release
3. Recreate the release (same version number)
4. Production server still has the behavior of the "bad" release

**Expected behavior**

Re-releasing the software should update existing deployments.

**Environment:**

- OS: Kubernetes
- Browser Version: N/A

### LINKED ISSUE #2512: Script to restore from a backup starts the list of available backups with an empty entry
**Describe the bug**

```
user@maintenance-54b4977848-rld2l:~$ combine_restore.py --verbose
INFO:  1. Prepare for the restore.
Backup List:
1:  (0 bytes)
2: thecombine-app-2023-08-23-03-15-02.tar.gz (3.61 GB)
3: thecombine-app-2023-08-24-03-15-02.tar.gz (3.61 GB)
4: thecombine-app-2023-08-25-03-15-02.tar.gz (3.61 GB)
Enter the number of the backup you would like to restore (0 = None):
```
Item 1 should not be there.

**To Reproduce**

1. `kubectl -n thecombine exec -it deployment/maintenance -- /bin/bash`
2. `combine_restore.py` (may use `--verbose` option if desired)
3. Voilà!
4. Note that if item 1 is selected, the script raises and exception and exits.

**Expected behavior**

Only valid backups on AWS S3 should be listed.

**Environment:**

- OS: Any
- Browser Version: Any

### PR DESCRIPTION
**Pull request by jmgrady**
Update various scripts used in the building and maintenance of _The Combine_.

1. `build.py` will get the build tool from an environment variable, `CONTAINER_CLI` if it is available.
2. `combine_restore.py` no longer lists an empty backup at the beginning of the list - Closes #2512 
3. Adds `nuc1_qa` and `nuc2_qa` targets to allow installation of QA images on the NUC.  Normally, the NUCs only install public images and do not have the jobs running to manage the credentials needed to pull images from the AWS ECR Private repositories.
4. Sets the `imagePullPolicy` for container images on AWS ECR to `Always` for the `prod`, `staging`, and `nuc_qa` profiles.  Closes #1838

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2609)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2609)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

*[a discussion](https://reviewable.io/reviews/sillsdev/TheCombine/2609#-NesETA97SwOLKRGMuGJ:-NesETAACoAC8QdNMgJg:b-k9ikzz) (no related file):*
Should `deploy/scripts/setup_files/profiles/nuc.yaml` also have an `imagePullPolicy` specified, or is the default (https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting) satisfactory in that case?

___
___
*[`deploy/scripts/build.py` line 273 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2609#-NesCjDX5rD807GA17k7:-NesCjDX5rD807GA17k8:bc8dtcl) ([raw file](https://github.com/sillsdev/TheCombine/blob/1064379baa114fda4c0aa7b299432c446dc408ac/deploy/scripts/build.py#L273)):*
> ```Python
>     else:
>         build_cmd = [container_cli, "buildx", "build"]
>         push_cmd = [container_cli, "push"]
> ```

This should probably be either
```
    elif container_cli == "docker":
        build_cmd = [container_cli, "buildx", "build"]
        push_cmd = [container_cli, "push"]

```
or
```
    else:
        build_cmd = ["docker", "buildx", "build"]
        push_cmd = ["docker", "push"]
```
___
*[`deploy/scripts/setup_files/combine_config.yaml` line 65 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2609#-NesDdqp6s2zfy2tKhHY:-NesDdqp6s2zfy2tKhHZ:b-s0003r) ([raw file](https://github.com/sillsdev/TheCombine/blob/1064379baa114fda4c0aa7b299432c446dc408ac/deploy/scripts/setup_files/combine_config.yaml#L65)):*
> ```YAML
>         global:
>           serverName: nuc2.thecombine.app
> ```

Why no `nuc3_qa`?

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2609)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`deploy/scripts/build.py` line 276 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2609#-NesXpPS0hz6MskjHXnY:-NesXpPS0hz6MskjHXnZ:b-exqvel) ([raw file](https://github.com/sillsdev/TheCombine/blob/585ef63f7eb944570e1a31f48a749c74a138c896/deploy/scripts/build.py#L276)):*
> ```Python
>             push_cmd = [container_cli, "push"]
>         case _:
>             logging.critical(f"Container CLI {container_cli} is not supported.")
> ```

quotes around `{container_cli}` for log readability?

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2609)* status: 5 of 25 files reviewed, all discussions resolved (waiting on @jmgrady)

*[a discussion](https://reviewable.io/reviews/sillsdev/TheCombine/2609#-NesETA97SwOLKRGMuGJ:-Nesx5fs-gdg0V-VjlNw:bcf2lfp) (no related file):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Well, yes and no.  No in that it is not necessary because that is the default condition in the helper templates.  However, that is kind of klunky since I have to repeat the template for every sub-chart.  I will look into requiring the `.Values.global.imagePullPolicy` to be set for all configurations.  The template tried to set the value to `Always` if the `imageName` was set to `latest` for developers but I am not sure we want this.  For Rancher Desktop, it should be `Never` since it already has the image; I need to check on Docker Desktop.
</blockquote></details>

Done.
`imagePullPolicy` is now a global value that must be overridden by a configuration profile or command line option.

___
___
*[`deploy/scripts/build.py` line 276 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2609#-NesXpPS0hz6MskjHXnY:-Nesx1TDEIuNWNL-Iwf0:b-fu92kc) ([raw file](https://github.com/sillsdev/TheCombine/blob/585ef63f7eb944570e1a31f48a749c74a138c896/deploy/scripts/build.py#L276)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

quotes around `{container_cli}` for log readability?
</blockquote></details>

Done.
Good suggestion

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 18 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2609)* status: 24 of 25 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

*[a discussion](https://reviewable.io/reviews/sillsdev/TheCombine/2609#-Net2MnYABWdZ6kxJQGA:-Net2MnYABWdZ6kxJQGB:bc0313t) (no related file):*
`scripts/install_sem_doms.py` merits updating https://github.com/sillsdev/TheCombine/blob/master/README.md#import-semantic-domains

___

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2609)* status: 23 of 25 files reviewed, all discussions resolved (waiting on @imnasnainaec and @jmgrady)

*[a discussion](https://reviewable.io/reviews/sillsdev/TheCombine/2609#-Net2MnYABWdZ6kxJQGA:-Net5jYJAC4Hw_p8ouVt:b-896fix) (no related file):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`scripts/install_sem_doms.py` merits updating https://github.com/sillsdev/TheCombine/blob/master/README.md#import-semantic-domains
</blockquote></details>

Done.

___

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2609)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Pull request merged**
