### PR TITLE
Upgrade upstream SIL dependencies to 8.0.0

### LINKED ISSUE #471: Evaluate older pinned SIL Backend dependencies
@jasonleenaylor Could someone familiar with the SIL C# toolkit evaluate the following pinned packages and determine if they should be bumped to later verisons?

Perhaps we at least want to bump to `7.0.1-beta*` if there are breaking changes in the `8.0.0` series.

```xml
<PackageReference Include="SIL.Core" Version="7.0.0-alpha0822" />
<PackageReference Include="SIL.Core.Desktop" Version="7.0.0-alpha0822">
<PackageReference Include="SIL.DictionaryServices" Version="7.0.0-alpha0822">
<PackageReference Include="SIL.Lift" Version="7.0.0-alpha0822">
```

Note that some of these appear in both application and test dependencies, so if they are updated, they should be updated together.

Related to #469 #470

### LINKED ISSUE #927: LIFT import/export fails for dev on mac
Recreate issue:
* Follow https://github.com/sillsdev/TheCombine#getting-started-with-development on macOS 10.15
* From within the project folder, run `npm run test-backend -- --filter FullyQualifiedName~Backend.Tests.Controllers.LiftControllerTests`

```
Test run for ~/TheCombine/Backend.Tests/bin/Debug/netcoreapp3.1/Backend.Tests.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
  X TestExportDeleted [105ms]
  Error Message:
   SIL.PlatformUtilities.NativeException : An error with the number, 13, ocurred.
  Stack Trace:
     at SIL.Threading.GlobalMutex.LinuxGlobalMutexAdapter.Init(Boolean initiallyOwned)
   at SIL.Threading.GlobalMutex.Initialize()
   at SIL.WritingSystems.Sldr.Initialize(Boolean offlineMode, String sldrCachePath, DateTime embeddedAllTagsTime)
   at SIL.WritingSystems.Sldr.Initialize(Boolean offlineMode, String sldrCachePath)
   at SIL.WritingSystems.Sldr.Initialize(Boolean offlineMode)
   at BackendFramework.Services.LiftService..ctor() in ~/TheCombine/Backend/Services/LiftApiServices.cs:line 98
   at Backend.Tests.Controllers.LiftControllerTests.Setup() in ~/TheCombine/Backend.Tests/Controllers/LiftControllerTests.cs:line 39
  X TestRoundtrip(Backend.Tests.Controllers.LiftControllerTests+RoundTripObj) [2s 48ms]
  Error Message:
     Expected: True
  But was:  False

  Stack Trace:
     at Backend.Tests.Controllers.LiftControllerTests.TestRoundtrip(RoundTripObj roundTripObj) in ~/TheCombine/Backend.Tests/Controllers/LiftControllerTests.cs:line 315
```

The SIL GlobalMutex has been written for Windows and Linux, and defaults to Linux when Windows isn't detected:
https://github.com/sillsdev/libpalaso/blob/d2d16493c4680d052f940f4b0ff9afc6fc7798b5/SIL.Core/Threading/GlobalMutex.cs#L25-L35

### PR DESCRIPTION
**Pull request by johnthagen**
Closes #471 

Closes #927

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1057)

### CODE REVIEW

**Comment by johnthagen** [comment]
Going to block merging this until the next release is released successfully with #1064.

**Comment by johnthagen** [comment]
Lift export fails within Docker:

```
backend_1   | info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
backend_1   |       Executed action BackendFramework.Controllers.LiftController.ExportLiftFile (BackendFramework) in 1246.3422ms
backend_1   | info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
backend_1   |       Executed endpoint 'BackendFramework.Controllers.LiftController.ExportLiftFile (BackendFramework)'
backend_1   | fail: Microsoft.AspNetCore.Server.Kestrel[13]
backend_1   |       Connection id "0HM702OO4OE8K", Request id "0HM702OO4OE8K:00000001": An unhandled exception was thrown by the application.
backend_1   | System.DllNotFoundException: Unable to load shared library 'libdl.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl.so: cannot open shared object file: No such file or directory
backend_1   |    at Icu.NativeMethods.dlopen(String file, Int32 mode)
backend_1   |    at Icu.NativeMethods.GetIcuLibHandle(String basename, Int32 icuVersion)
backend_1   |    at Icu.NativeMethods.LoadIcuLibrary(String libraryName)
backend_1   |    at Icu.NativeMethods.get_IcuCommonLibHandle()
backend_1   |    at Icu.NativeMethods.uset_open(Char start, Char end)
backend_1   |    at Icu.UnicodeSet.ToPattern(IEnumerable`1 set)
backend_1   |    at SIL.WritingSystems.LdmlDataMapper.WriteCharactersElement(XElement charactersElem, WritingSystemDefinition ws)
backend_1   |    at SIL.WritingSystems.LdmlDataMapper.WriteLdml(XmlWriter writer, XElement element, WritingSystemDefinition ws)
backend_1   |    at SIL.WritingSystems.LdmlDataMapper.Write(String filePath, WritingSystemDefinition ws, Stream oldFile)
backend_1   |    at SIL.WritingSystems.LdmlInFolderWritingSystemRepository`1.SaveDefinition(T ws)
backend_1   |    at SIL.WritingSystems.LdmlInFolderWritingSystemRepository`1.Save()
backend_1   |    at BackendFramework.Services.LiftService.LdmlExport(String filePath, String vernacularBcp47, List`1 validChars) in /app/Services/LiftApiServices.cs:line 465
backend_1   |    at BackendFramework.Services.LiftService.LiftExport(String projectId, IWordRepository wordRepo, IProjectService projService) in /app/Services/LiftApiServices.cs:line 345
backend_1   |    at BackendFramework.Controllers.LiftController.CreateLiftExport(String projectId) in /app/Controllers/LiftController.cs:line 260
backend_1   |    at BackendFramework.Controllers.LiftController.ExportLiftFile(String projectId, String userId) in /app/Controllers/LiftController.cs:line 244
backend_1   |    at BackendFramework.Controllers.LiftController.ExportLiftFile(String projectId) in /app/Controllers/LiftController.cs:line 200
backend_1   |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
backend_1   |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
backend_1   |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
backend_1   |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
backend_1   |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
backend_1   |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
backend_1   |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
backend_1   |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
backend_1   |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
backend_1   |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
backend_1   |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
backend_1   |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
backend_1   |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
backend_1   |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
backend_1   |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
backend_1   | info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
backend_1   |       Request finished in 1271.1589ms 500
```

**Comment by johnthagen** [comment]
I was able to test lift import and export both locally in a development configuration and within the Docker Compose project.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1057)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Pull request merged**
