### PR TITLE
[ProjectSettings] Replace ProjectSwitch with a Select

### PR DESCRIPTION
**Pull request by imnasnainaec**
First part of #1176

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2416)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 4 of 7 files at r1, 3 of 3 files at r2, 3 of 3 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2416)* status: all files reviewed, 1 unresolved discussion (waiting on @Apoktieno and @imnasnainaec)

___
*[`src/components/ProjectSettings/ProjectSelect.tsx` line 33 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2416#-NalxXcQEKsA30cBaU0E:-NalxXcQEKsA30cBaU0F:bmej4kx) ([raw file](https://github.com/sillsdev/TheCombine/blob/5bf1db2a15b89d37c4ed9d78a475f0ddba53b897/src/components/ProjectSettings/ProjectSelect.tsx#L33)):*
> ```XML
>   // This prevents an out-of-range Select error while useEffect is underway.
>   const projectList = [...projList];
>   if (!projectList.find((p) => p.name === props.project.name)) {
> ```

I think I would have used .filter, and I think filter is more performant here, not that it matters that much.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2416)* status: all files reviewed, 1 unresolved discussion (waiting on @Apoktieno and @jasonleenaylor)

___
*[`src/components/ProjectSettings/ProjectSelect.tsx` line 33 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2416#-NalxXcQEKsA30cBaU0E:-Nan0mEW-M_7daB2lQoj:b-achoyg) ([raw file](https://github.com/sillsdev/TheCombine/blob/5bf1db2a15b89d37c4ed9d78a475f0ddba53b897/src/components/ProjectSettings/ProjectSelect.tsx#L33)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

I think I would have used .filter, and I think filter is more performant here, not that it matters that much.
</blockquote></details>

Do you mean replace `= [...projList]` with `= projList.filter(p => p)`, or is there a way with `filter` to add a missing item? I only know how to remove unwanted items with it.

**Review by jasonleenaylor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2416)* status: all files reviewed, 1 unresolved discussion (waiting on @Apoktieno and @imnasnainaec)

___
*[`src/components/ProjectSettings/ProjectSelect.tsx` line 33 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2416#-NalxXcQEKsA30cBaU0E:-NaoGAag02qs2D1Fvhtf:b8led1e) ([raw file](https://github.com/sillsdev/TheCombine/blob/5bf1db2a15b89d37c4ed9d78a475f0ddba53b897/src/components/ProjectSettings/ProjectSelect.tsx#L33)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Do you mean replace `= [...projList]` with `= projList.filter(p => p)`, or is there a way with `filter` to add a missing item? I only know how to remove unwanted items with it.
</blockquote></details>

:man_facepalming: 

I was apparently reading code that wasn't here. 
Not sure how I got confused, my apologies.

**Review by jasonleenaylor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2416)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Apoktieno)

**Pull request merged**
