### PR TITLE
UserSettings disable save button

### LINKED ISSUE #1534: "hasAvatar" does not always get set to "true" when an avatar is selected for a user
**Describe the bug**

Under certain conditions, when setting up a user the user's avatar file location is saved in the database but the "hasAvatar" field is not updated to "true".

**To Reproduce**

1. Register a new user and login as the user;
2. Open the _User Settings_ dialog;
3. Click on the blank avatar;
4. Click _Browse_ and select an image file to be the avatar image;
5. Click _Save_;
6. Click _Save_;
7. Login to _The Combine_ as the new user from another device;
8. Image is not displayed.

In addition, if one has access to the server, one can list the document in the database `UsersCollection`:
 - Run: `kubectl exec -it deployment/database -- mongo CombineDatabase`
 - List the document for the user that was just created:
```
> db.UsersCollection.find({username: "jmg116"}).pretty()
{
	"_id" : ObjectId("61e6da981330b361b12e5e77"),
	"avatar" : "/home/app/.CombineFiles/Avatars/61e6da981330b361b12e5e77.jpg",
	"hasAvatar" : false,
	"name" : "Me",
	"email" : "******@****.com",
	"phone" : "",
	"otherConnectionField" : "",
	"workedProjects" : {
		
	},
	"projectRoles" : {
		
	},
	"agreement" : false,
	"password" : "eitvUa+yD+sQzvCYZEwRAEHKNhwgujomRXK1qfECYj0CR5P/G3mbDAVjAlySlPxe",
	"username" : "jmg116",
	"uiLang" : "",
	"token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiI2MWU2ZGE5ODEzMzBiMzYxYjEyZTVlNzciLCJVc2VyUm9sZUluZm8iOiJbXSIsIm5iZiI6MTY0MjUxOTE5MywiZXhwIjoxNjQyNTMzNTkzLCJpYXQiOjE2NDI1MTkxOTN9.9UtaqR5H2nO2kQjumgRqhMLnfR66nvjdioU-UPohNIU",
	"isAdmin" : false
}
```   
Note the `avatar` and `hasAvatar` fields.

**Expected behavior**

_The Combine_ should display the user's avatar on all devices.

**Environment:**

Further investigation is needed but it seems to only happened when connected to _The Combine_ from an Android device using a Chromium based browser (_Chrome 97_ or _Brave 1.34_) but not Firefox 96.  The problem was see with _The Combine_ running on the Live server and running on a NUC.  The problem has not happened when connecting to _The Combine_ from an Ubuntu Desktop.

### LINKED ISSUE #2459: UserSettings disable button buggy after any change is saved.
**Describe the bug**

The UserSettings component pulls the current user from LocalStorage when it first renders, but doesn't see if that user is updated. As a consequence, the criteria for when the SAVE button is enabled/disabled can depend on old information.

Possible solution: the `onSubmit` function should refresh the component's data by pulling new data from LocalStorage.

**To Reproduce**

1. Click on the user avatar on the right side of the top blue app bar.
2. Click on User Settings.
3. Observe that the SAVE button is disabled.
4. Make a small change to (e.g.) name.
5. Observe that the SAVE button is enabled.
6. Click the SAVE button.
7. Observe that the SAVE button is still enabled.
8. Undo the previous change from step 4.
9. Observe that the SAVE button is disabled.

**Expected behavior**

7: The save button should be disabled after a change is saved.

9: The save button should be available if a user is trying to revert as change they just made.

**Environment:**

- OS: [e.g. Windows/Android]
- Browser Version [e.g. Chrome 89, Firefox 90]

### PR DESCRIPTION
**Pull request by Apoktieno**
Closes #1534
Closes #2459 

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2488)

### CODE REVIEW

**Comment by Apoktieno** [comment]
This is the best I could figure out for the moment. I used setName to update disabled. I am still relearning how React works, so I am sure there is better way to do this.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2488)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Apoktieno)

___
*[`src/components/UserSettings/UserSettings.tsx` line 86 at r1](https://reviewable.io/reviews/sillsdev/TheCombine/2488#-Nc-F9NuCf2Hsr_NTmME:-Nc-F9NuCf2Hsr_NTmMF:b-46djrk) ([raw file](https://github.com/sillsdev/TheCombine/blob/9015c83e77477a7679e680bee71b0b1839d38141/src/components/UserSettings/UserSettings.tsx#L86)):*
> ```XML
>       props.user.phone = currentUser?.phone!;
>       props.user.email = currentUser?.email!;
>       props.user.uiLang = currentUser?.uiLang!;
> ```

As a general rule, a component's incoming props are to be treated as immutable. In the current design the `default` function gets the current user from the LocalStorage and passes that to its child `UserSettings` component via the props. Rather than try to update the props from the child, we want to update the current user in the local storage and then get the parent component to update `potentialUser` from the local storage.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2488)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Apoktieno)

*[a discussion](https://reviewable.io/reviews/sillsdev/TheCombine/2488#-Nc2ZzmdE5VZ2_QaaGBb:-Nc2ZzmdE5VZ2_QaaGBc:b-c3iibp) (no related file):*
If you have the browser console open when you add/change the user avatar, you'll see the following error:
```
UserSettings.tsx:89 Uncaught (in promise) 
AxiosError {message: 'Request failed with status code 304', name: 'AxiosError', config: {…}, request: XMLHttpRequest, response: {…}}
config: {transitional: {…}, transformRequest: Array(1), transformResponse: Array(1), timeout: 0, adapter: ƒ, …}
message: "Request failed with status code 304"
name: "AxiosError"
request: XMLHttpRequest
response:
  config: {transitional: {…}, transformRequest: Array(1), transformResponse: Array(1), timeout: 0, adapter: ƒ, …}
  data: ""
  headers: {content-type: 'application/json; charset=utf-8'}
  request: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}
  status: 304
  statusText: "Not Modified"
[[Prototype]]: Object
[[Prototype]]: Error
```
The update user function is being submitted though there are no changes to submit---the avatar updated with a different backend function. So why is the user update function being submitted? We have a form (in `AvatarUpload.tsx`) within another form (in `UserSettings.tsx`). As a consequence, the `AvatarUpload` button with `type: "submit"` submits _both_ forms. To prevent this, the `upload` function in `AvatarUpload` needs `e.stopPropagation();` added.

___
___
*[`src/components/UserSettings/UserSettings.tsx` line 86 at r1](https://reviewable.io/reviews/sillsdev/TheCombine/2488#-Nc-F9NuCf2Hsr_NTmME:-Nc2W3s05GWCWvMg49xI:bwwt97k) ([raw file](https://github.com/sillsdev/TheCombine/blob/9015c83e77477a7679e680bee71b0b1839d38141/src/components/UserSettings/UserSettings.tsx#L86)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

As a general rule, a component's incoming props are to be treated as immutable. In the current design the `default` function gets the current user from the LocalStorage and passes that to its child `UserSettings` component via the props. Rather than try to update the props from the child, we want to update the current user in the local storage and then get the parent component to update `potentialUser` from the local storage.
</blockquote></details>

Looking much better!
___
*[`src/components/UserSettings/UserSettings.tsx` line 49 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2488#-Nc2Widu7tVsYb3EpfkQ:-Nc2Widu7tVsYb3EpfkR:bqruccp) ([raw file](https://github.com/sillsdev/TheCombine/blob/1752ab60e30ab5a58902e4887a01a35c7aa6a0a3/src/components/UserSettings/UserSettings.tsx#L49)):*
> ```XML
> export function UserSettings(props: {
>   user: User;
>   setUser: Function;
> ```

We can have a more specific type than `Function` here: `(user?: User) => void`

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2488)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @Apoktieno)

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2488)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Apoktieno)

**Pull request merged**
