### PR TITLE
[MergeDups] Show (read-only) note on entries with a note

### LINKED ISSUE #1343: [MergeDuplicates] See Note on each entry
In merge duplicates, user should be able to see the contents of entry notes.

---
(Issue initially from: "26. H [Merge] Need a way to make a note on an entry."
#1429 preferred to editing notes within MergeDuplicates.)

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #1343

To test:
 - create a new project (or open a project that doesn't already have a bunch of potential duplicates)
 - enter two words with identical vernacular form and a note on at least one of them
 - Data Cleanup > Merge Duplicates 

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2960)

### CODE REVIEW

**Review by jmgrady — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2960)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[`src/components/Buttons/NoteButton.tsx` line 5 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2960#-NvHvJyJ5QwsM1IVW0Ph:-NvHvJyJ5QwsM1IVW0Pi:b-76dem9) ([raw file](https://github.com/sillsdev/TheCombine/blob/8c99372fb592ddb6619629afedf80a244d5bb519/src/components/Buttons/NoteButton.tsx#L5)):*
> ```XML
> 
> import IconButtonWithTooltip from "components/Buttons/IconButtonWithTooltip";
> import EditTextDialog from "components/Dialogs/EditTextDialog";
> ```

I don't understand the reason for this change.  I thought the purpose of `components/Buttons/index.ts` was so that all buttons would be imported from this location.  If we are migrating away from that, then perhaps adding `NoteButton` to `components/Buttons/index.tx` does not make sense.

Currently, there are 19 instances (including the ones in this PR) that use this form and 43 instances that import from `"components/Buttons"`.  I personally prefer the latter because it is easier to read when there is a single import source for the buttons instead of a separate import for each button.  This is merely a preference - I would prefer to have consistent usage.

I am not proposing that you reconcile all of these differences in this PR but rather create an issue to have a common import pattern for buttons (& dialogs).  If the decision is to use `"components/Buttons/<button_name>"` then these changes can say.  Otherwise, I would prefer to revert these changes to make less work later.



_Code quote:_
```XML
import IconButtonWithTooltip from "components/Buttons/IconButtonWithTooltip";
import EditTextDialog from "components/Dialogs/EditTextDialog";
```

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2960)* status: all files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`src/components/Buttons/NoteButton.tsx` line 5 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2960#-NvHvJyJ5QwsM1IVW0Ph:-NvIOeVWCYv_sdkQSMb8:bdjym0j) ([raw file](https://github.com/sillsdev/TheCombine/blob/8c99372fb592ddb6619629afedf80a244d5bb519/src/components/Buttons/NoteButton.tsx#L5)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

I don't understand the reason for this change.  I thought the purpose of `components/Buttons/index.ts` was so that all buttons would be imported from this location.  If we are migrating away from that, then perhaps adding `NoteButton` to `components/Buttons/index.tx` does not make sense.

Currently, there are 19 instances (including the ones in this PR) that use this form and 43 instances that import from `"components/Buttons"`.  I personally prefer the latter because it is easier to read when there is a single import source for the buttons instead of a separate import for each button.  This is merely a preference - I would prefer to have consistent usage.

I am not proposing that you reconcile all of these differences in this PR but rather create an issue to have a common import pattern for buttons (& dialogs).  If the decision is to use `"components/Buttons/<button_name>"` then these changes can say.  Otherwise, I would prefer to revert these changes to make less work later.
</blockquote></details>

I prefer simply always using `from "components/Buttons/"` as well, but the issue I'm encountering is that if you use any one of the buttons, you require the imports of all of the buttons, which results in a lot more seemingly unnecessary mocking in the functions. I'd like to figure out a standard way to create one of these collective index files that exports everything in some lazy-load fashion to avoid this.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2960)* status: 5 of 16 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[`src/components/Buttons/NoteButton.tsx` line 5 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2960#-NvHvJyJ5QwsM1IVW0Ph:-NvIYBciC6YlQGJco1fu:bwn4fo0) ([raw file](https://github.com/sillsdev/TheCombine/blob/8c99372fb592ddb6619629afedf80a244d5bb519/src/components/Buttons/NoteButton.tsx#L5)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I prefer simply always using `from "components/Buttons/"` as well, but the issue I'm encountering is that if you use any one of the buttons, you require the imports of all of the buttons, which results in a lot more seemingly unnecessary mocking in the functions. I'd like to figure out a standard way to create one of these collective index files that exports everything in some lazy-load fashion to avoid this.
</blockquote></details>

I know you were "not proposing that you reconcile all of these differences in this PR", but I push commits here anyway to get your thoughts one way to do it with `@loadable/component` and to make sure the tests still pass.

**Review by jmgrady — APPROVED** [review]
> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2960)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 2 of 10 files at r1, 3 of 6 files at r2, 9 of 11 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2960)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2960)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
