### PR TITLE
[CAPTCHA] Replace ReCAPTCHA with Turnstile

### LINKED ISSUE #2407: Replace Captcha with Cloudflare Turnstile
Investigate performance of Turnstile in Africa

If performance is not worse than google captcha use Turnstile to keep bots out of our site.

https://www.cloudflare.com/products/turnstile/

We already have an organizational cloudflare account, so we may be able to generate an api key from there.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #2407

Also:
- Adds an `emailEnabled` config and implement it in `EmailService.cs`
- Adds environment variables to `Backend/Properties/launchSettings.json` and updates `README` accordingly

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3249)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3249)* status: 6 of 44 files reviewed, 9 unresolved discussions (waiting on @jmgrady)

___
*[`Backend/Startup.cs` line 182 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O20v0m2CrMjH2WZdCor:-O25CBv9B3W1UR7tS_4P:b6svgrd) ([raw file](https://github.com/sillsdev/TheCombine/blob/d805fb45c91e754a1aaf42f6f27f9e47860ea8d2/Backend/Startup.cs#L182)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I've yet to create another environment variable for "whether turnstile should be used" because environment variables are strings and I'm not sure the best way to represent a bool that won't require an arbitrary string-value check somewhere.
</blockquote></details>

I'm also wondering whether it's worthwhile to engineer that variable in the backend when the only function that uses it will never be called if its `false`.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3249)* status: 12 of 50 files reviewed, 10 unresolved discussions (waiting on @jmgrady)

___
*[`README.md` line 146 at r5](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O252U8X21X21qefy_-M:-O2APW0g9tZIph5_Iovk:bjt6twq) ([raw file](https://github.com/sillsdev/TheCombine/blob/0bb8630c684f4a48e4eaa7069efc65a710838a94/README.md#L146)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

What about setting `COMBINE_JWT_SECRET_KEY`?
</blockquote></details>

I added it to `Backend/Properties/launchSettings.json` so it's no longer needed for `npm run backend` or `npm start`. It is still required for a dev docker build, so I moved the instruction to `### Setup Environment Variables` below.
___
*[`Backend/Startup.cs` line 182 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O20v0m2CrMjH2WZdCor:-O2APtGT9fMD7yV7y7n3:be1tdjy) ([raw file](https://github.com/sillsdev/TheCombine/blob/d805fb45c91e754a1aaf42f6f27f9e47860ea8d2/Backend/Startup.cs#L182)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Sorry I was not clearer.  My point was not that the issue is that there is a mixing of data types but that there is a mixing of function.  On purpose is to enable/disable turnstile; the other is to provide the secret to make turnstile work.

As you stated, environment variables are strings and the API should be defined as: If the environment variable's value equals the string "true", then the functionality is enabled.  It is not enabled for any other value.
</blockquote></details>

Added, though it should be "True" as that is the `bool.TrueString` in C#. I also added an analogous backend config for email enabled, to make sure they are both implemented the same way.
___
*[`Backend/Startup.cs` line 246 at r5](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O2568oh7b6mk86aXMIp:-O2AQBZ1-g_XCXmEbIBG:b-rvj0yd) ([raw file](https://github.com/sillsdev/TheCombine/blob/0bb8630c684f4a48e4eaa7069efc65a710838a94/Backend/Startup.cs#L246)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Similarly, shouldn't these transients only be added when Turnstile is enabled?
</blockquote></details>

I think conditionally adding transients for Email/Turnstile contexts/services is a whole new ballgame.
___
*[`deploy/helm/thecombine/values.yaml` line 29 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O20x8bd3R3NHN1Ri4fD:-O2AQRtH34PtFLdmxh99:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/d805fb45c91e754a1aaf42f6f27f9e47860ea8d2/deploy/helm/thecombine/values.yaml#L29)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Add enable/disable variable.
</blockquote></details>

Done.
___
*[`deploy/helm/thecombine/values.yaml` line 59 at r6](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O25qauNCW4Ew8Ptm3gJ:-O2AQUJ2Cwet-OGJsdlT:bi2gzgf) ([raw file](https://github.com/sillsdev/TheCombine/blob/18cf48c6853c08d14d5750a97cf013e94c1d84f9/deploy/helm/thecombine/values.yaml#L59)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

This should be in the global variables.  I still maintain that the backend should know whether turnstile is enabled rather than assume no requests will come in - the backend should behave reasonably if it receives unexpected data.
</blockquote></details>

I added it as a backend variable separately because of different handling (bool for the frontend config and "True"/"False" for backend environment variable parsing).
___
*[`deploy/helm/thecombine/charts/backend/values.yaml` line 24 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O20xHie8VJhRJ2ZTVyK:-O2AQnNl89NEpAvNnPBv:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/d805fb45c91e754a1aaf42f6f27f9e47860ea8d2/deploy/helm/thecombine/charts/backend/values.yaml#L24)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Again, add enable/disable variable.
</blockquote></details>

Done.
___
*[`deploy/scripts/setup_files/profiles/dev.yaml` line 15 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O29zi6BDweZRcfTt5To:-O2AQpx329L2LklggWEv:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/cef2a5ea4f2360b7badd3c307b2cd7688598cdb8/deploy/scripts/setup_files/profiles/dev.yaml#L15)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

This comment would be more helpful if there were some explanation of what the URL is for.
</blockquote></details>

Done.
___
*[`nginx/init/25-combine-runtime-config.sh` line 53 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O2A-3OmAK6IjvzJVZ8a:-O2AQrDEATBRNSnlboCS:bcks5o7) ([raw file](https://github.com/sillsdev/TheCombine/blob/cef2a5ea4f2360b7badd3c307b2cd7688598cdb8/nginx/init/25-combine-runtime-config.sh#L53)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Technically, renaming CAPTCHA to Turnstile in all of the files is not necessary.  CAPTCHA stands for "Completely Automated Public Turing test to tell Computers and Humans Apart."  The Google implementation is reCAPTCHA.
</blockquote></details>

Good point. And such a fun acronym...

**Review by jmgrady — COMMENTED** [review]
> Reviewed 1 of 25 files at r1, 2 of 7 files at r2, 13 of 35 files at r8, 11 of 29 files at r9, 19 of 20 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3249)* status: all files reviewed, 12 unresolved discussions (waiting on @imnasnainaec)

___
*[`README.md` line 146 at r5](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O252U8X21X21qefy_-M:-O2F9K8S95Hbt1YWbh55:by02vbo) ([raw file](https://github.com/sillsdev/TheCombine/blob/0bb8630c684f4a48e4eaa7069efc65a710838a94/README.md#L146)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I added it to `Backend/Properties/launchSettings.json` so it's no longer needed for `npm run backend` or `npm start`. It is still required for a dev docker build, so I moved the instruction to `### Setup Environment Variables` below.
</blockquote></details>

This is a small additional scope for the PR.  It would be good to mention it in the PR description.
___
*[`Backend/Startup.cs` line 182 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O20v0m2CrMjH2WZdCor:-O2FBuxyAkGkWuh_5zDc:b-inclfk) ([raw file](https://github.com/sillsdev/TheCombine/blob/d805fb45c91e754a1aaf42f6f27f9e47860ea8d2/Backend/Startup.cs#L182)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Added, though it should be "True" as that is the `bool.TrueString` in C#. I also added an analogous backend config for email enabled, to make sure they are both implemented the same way.
</blockquote></details>

Let's discuss this in Slack so that we can have a more interactive discussion and have the same design intent to reduce the number of code changes you end up making.
___
*[`Backend/Startup.cs` line 246 at r5](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O2568oh7b6mk86aXMIp:-O2FJ1l8-tcm4FuZWfCm:b-eg9h15) ([raw file](https://github.com/sillsdev/TheCombine/blob/0bb8630c684f4a48e4eaa7069efc65a710838a94/Backend/Startup.cs#L246)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I think conditionally adding transients for Email/Turnstile contexts/services is a whole new ballgame.
</blockquote></details>

My concern is mostly why run services that are not supposed to be enabled?  It looks like the service is still needed because that is what will throw the exception that says it is not enabled.
___
*[`deploy/helm/thecombine/values.yaml` line 59 at r6](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O25qauNCW4Ew8Ptm3gJ:-O2FMMGl4C3I8kHmyPsF:bvkdxz6) ([raw file](https://github.com/sillsdev/TheCombine/blob/18cf48c6853c08d14d5750a97cf013e94c1d84f9/deploy/helm/thecombine/values.yaml#L59)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I added it as a backend variable separately because of different handling (bool for the frontend config and "True"/"False" for backend environment variable parsing).
</blockquote></details>

I see it is done.
___
*[`deploy/helm/thecombine/charts/backend/values.yaml` line 21 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O2Fq5te8lMOBQNX7YDF:-O2Fq5te8lMOBQNX7YDG:b62mfli) ([raw file](https://github.com/sillsdev/TheCombine/blob/7c30de3d894c97578af5b8d6d4fda04243ec8c35/deploy/helm/thecombine/charts/backend/values.yaml#L21)):*
> ```YAML
>   awsDefaultRegion: "Override"
>   pullSecretName: "None"
>   combineJwtSecretKey: "Override"
> ```

`captchaRequired` and `emailEnabled` need to be added to the global section.
___
*[`deploy/helm/thecombine/charts/backend/templates/backend-config-map.yaml` line 12 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O2FWecs9AlQF9qHBNfa:-O2FWecs9AlQF9qHBNfb:br2gfqc) ([raw file](https://github.com/sillsdev/TheCombine/blob/7c30de3d894c97578af5b8d6d4fda04243ec8c35/deploy/helm/thecombine/charts/backend/templates/backend-config-map.yaml#L12)):*
> ```YAML
> {{- else }}
>   COMBINE_CAPTCHA_REQUIRED: "False"
> {{- end }}
> ```

Should be:
```
COMBINE_CAPTCHA_REQUIRED: {{ .Values.global.captchaRequired | quote }}
```

`bool.Parse` is case insensitive.  As the documentation states, it tests that the string is _equivalent_ to (not _equal_ to) `bool.TrueString`.



_Code quote:_
```YAML
{{- if .Values.global.captchaRequired }}
  COMBINE_CAPTCHA_REQUIRED: "True"
{{- else }}
  COMBINE_CAPTCHA_REQUIRED: "False"
{{- end }}
```
___
*[`deploy/helm/thecombine/charts/backend/templates/backend-config-map.yaml` line 18 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O2FWr6o-NxVml782E2D:-O2FWr6pA0sZdXesu4iF:b-h34omt) ([raw file](https://github.com/sillsdev/TheCombine/blob/7c30de3d894c97578af5b8d6d4fda04243ec8c35/deploy/helm/thecombine/charts/backend/templates/backend-config-map.yaml#L18)):*
> ```YAML
> {{- else }}
>   COMBINE_EMAIL_ENABLED: "False"
> {{- end }}
> ```

Similarly, should be:
```
  COMBINE_EMAIL_ENABLED: {{ .Values.global.emailEnabled | quote }}
```



_Code quote:_
```YAML
{{- if .Values.global.emailEnabled }}
  COMBINE_EMAIL_ENABLED: "True"
{{- else }}
  COMBINE_EMAIL_ENABLED: "False"
{{- end }}
```
___
*[`deploy/scripts/install-combine.sh` line 21 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O2FYVuV4OpWdHZZq7O-:-O2FYVuV4OpWdHZZq7O0:b-xpu8wa) ([raw file](https://github.com/sillsdev/TheCombine/blob/7c30de3d894c97578af5b8d6d4fda04243ec8c35/deploy/scripts/install-combine.sh#L21)):*
> ```Shell
>     export COMBINE_CAPTCHA_REQUIRED="False"
>     export COMBINE_EMAIL_ENABLED="False"
>     export COMBINE_JWT_SECRET_KEY="${COMBINE_JWT_SECRET_KEY}"
> ```

The captcha and email enabled environment variables should not be needed.  These values should be driven by the profile.

I don't think that any of the changes for Turnstile should affect this file.



_Code quote:_
```Shell
    export AWS_DEFAULT_REGION="us-east-1"
    export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
    export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
    export COMBINE_CAPTCHA_REQUIRED="False"
    export COMBINE_EMAIL_ENABLED="False"
    export COMBINE_JWT_SECRET_KEY="${COMBINE_JWT_SECRET_KEY}"
```
___
*[`deploy/scripts/setup_files/profiles/nuc_qa.yaml` line 14 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O2F_YmY37aC9gI2Skuq:-O2F_YmY37aC9gI2Skur:b-xo5wa1) ([raw file](https://github.com/sillsdev/TheCombine/blob/7c30de3d894c97578af5b8d6d4fda04243ec8c35/deploy/scripts/setup_files/profiles/nuc_qa.yaml#L14)):*
> ```YAML
>     global:
>       awsS3Location: prod.thecombine.app
>       captchaRequired: false
> ```

We probably want these to be `true`.  The `nuc_qa` profile should not be shipped for use in a workshop.  It installs The Combine on the NUC with the QA environment, that is, it is setup to be able to pull unreleased code images from the AWS private container registry.  Normally the NUC can only install release images from the AWS Public container registry.  (Although with the annoying Google reCAPTCHA I would probably want it set to `false`!)

Of course, if you change them, then the CAPTCHA site key will need to be added.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3249)* status: 48 of 52 files reviewed, 12 unresolved discussions (waiting on @jmgrady)

___
*[`deploy/helm/thecombine/charts/backend/values.yaml` line 21 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O2Fq5te8lMOBQNX7YDF:-O2PbgCrAhr_5IMNY3Rf:bgcv18n) ([raw file](https://github.com/sillsdev/TheCombine/blob/7c30de3d894c97578af5b8d6d4fda04243ec8c35/deploy/helm/thecombine/charts/backend/values.yaml#L21)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

`captchaRequired` and `emailEnabled` need to be added to the global section.
</blockquote></details>

Aren't default values being pulled from `deploy\helm\thecombine\values.yaml`?
___
*[`deploy/helm/thecombine/charts/backend/templates/backend-config-map.yaml` line 12 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O2FWecs9AlQF9qHBNfa:-O2PbtRRAbwwGyo0zetS:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/7c30de3d894c97578af5b8d6d4fda04243ec8c35/deploy/helm/thecombine/charts/backend/templates/backend-config-map.yaml#L12)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Should be:
```
COMBINE_CAPTCHA_REQUIRED: {{ .Values.global.captchaRequired | quote }}
```

`bool.Parse` is case insensitive.  As the documentation states, it tests that the string is _equivalent_ to (not _equal_ to) `bool.TrueString`.
</blockquote></details>

Done.
___
*[`deploy/helm/thecombine/charts/backend/templates/backend-config-map.yaml` line 18 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O2FWr6o-NxVml782E2D:-O2PbuoFEHQhEmvtDJus:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/7c30de3d894c97578af5b8d6d4fda04243ec8c35/deploy/helm/thecombine/charts/backend/templates/backend-config-map.yaml#L18)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Similarly, should be:
```
  COMBINE_EMAIL_ENABLED: {{ .Values.global.emailEnabled | quote }}
```
</blockquote></details>

Done.
___
*[`deploy/scripts/install-combine.sh` line 21 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O2FYVuV4OpWdHZZq7O-:-O2PbxVO-lIbFz0OeHdX:br7rfv3) ([raw file](https://github.com/sillsdev/TheCombine/blob/7c30de3d894c97578af5b8d6d4fda04243ec8c35/deploy/scripts/install-combine.sh#L21)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

The captcha and email enabled environment variables should not be needed.  These values should be driven by the profile.

I don't think that any of the changes for Turnstile should affect this file.
</blockquote></details>

You're right about `COMBINE_CAPTCHA_REQUIRED` and `COMBINE_EMAIL_ENABLED`--I retracted those. But I think `COMBINE_SMTP_USERNAME` is no longer required with the new handling of the `emailEnabled` config.
___
*[`deploy/scripts/setup_files/profiles/nuc_qa.yaml` line 14 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O2F_YmY37aC9gI2Skuq:-O2PcK-H7kOeJqAZenI4:b-puvlvu) ([raw file](https://github.com/sillsdev/TheCombine/blob/7c30de3d894c97578af5b8d6d4fda04243ec8c35/deploy/scripts/setup_files/profiles/nuc_qa.yaml#L14)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

We probably want these to be `true`.  The `nuc_qa` profile should not be shipped for use in a workshop.  It installs The Combine on the NUC with the QA environment, that is, it is setup to be able to pull unreleased code images from the AWS private container registry.  Normally the NUC can only install release images from the AWS Public container registry.  (Although with the annoying Google reCAPTCHA I would probably want it set to `false`!)

Of course, if you change them, then the CAPTCHA site key will need to be added.
</blockquote></details>

The Turnstile site key won't work outside of the domains set for it in the Cloudflare account. Should `nuc*.thecombine.app` be added?

**Review by jmgrady — COMMENTED** [review]
> Reviewed 2 of 4 files at r11, 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3249)* status: all files reviewed, 9 unresolved discussions (waiting on @imnasnainaec)

___
*[`Backend/Properties/launchSettings.json` line 31 at r12](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O2U8SJs6YCx_5KfCiq6:-O2U8SJtC_WXrB6usNoc:b-1pnuce) ([raw file](https://github.com/sillsdev/TheCombine/blob/16775309e8414a6298dc57a31b013b3179ea0661/Backend/Properties/launchSettings.json#L31)):*
> ```JSON
>         "Key": "Value",
>         "ASPNETCORE_ENVIRONMENT": "Development",
>         "COMBINE_CAPTCHA_REQUIRED": "true",
> ```

This is not really required since it is the default, correct?



_Code quote:_
```JSON
        "COMBINE_CAPTCHA_REQUIRED": "true",
```
___
*[`deploy/scripts/setup_files/profiles/nuc_qa.yaml` line 14 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O2F_YmY37aC9gI2Skuq:-O2U9R-99gynIXeZBUz9:bv7emmd) ([raw file](https://github.com/sillsdev/TheCombine/blob/7c30de3d894c97578af5b8d6d4fda04243ec8c35/deploy/scripts/setup_files/profiles/nuc_qa.yaml#L14)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

The Turnstile site key won't work outside of the domains set for it in the Cloudflare account. Should `nuc*.thecombine.app` be added?
</blockquote></details>

It should work.  I will test it and let you know.  The domain is `thecombine.app`; `nuc*.thecombine.app` is a host in that domain.

**Review by imnasnainaec — COMMENTED** [review]
> Dismissed @github-advanced-security[bot] from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3249)* status: 48 of 52 files reviewed, 5 unresolved discussions (waiting on @jmgrady)

___
*[`Backend/Properties/launchSettings.json` line 31 at r12](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O2U8SJs6YCx_5KfCiq6:-O2UlZBSAjlIcH7CB3SD:bid6m6x) ([raw file](https://github.com/sillsdev/TheCombine/blob/16775309e8414a6298dc57a31b013b3179ea0661/Backend/Properties/launchSettings.json#L31)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

This is not really required since it is the default, correct?
</blockquote></details>

This is required for `npm start` and `npm run backend` because the Helm charts haven't been run.
___
*[`deploy/scripts/setup_files/profiles/nuc_qa.yaml` line 14 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O2F_YmY37aC9gI2Skuq:-O2UlnL27UkgpqWRGSQn:b6skrum) ([raw file](https://github.com/sillsdev/TheCombine/blob/7c30de3d894c97578af5b8d6d4fda04243ec8c35/deploy/scripts/setup_files/profiles/nuc_qa.yaml#L14)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

It should work.  I will test it and let you know.  The domain is `thecombine.app`; `nuc*.thecombine.app` is a host in that domain.
</blockquote></details>

We added both `thecombine.app` and `qa-kube.thecombine.app` explicitly in generating the keys, but it would be good to know if it works on other `*.thecombine.app` domains.

**Review by jmgrady — COMMENTED** [review]
> Reviewed 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3249)* status: all files reviewed, 4 unresolved discussions (waiting on @imnasnainaec)

___
*[`deploy/scripts/setup_files/profiles/nuc_qa.yaml` line 14 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O2F_YmY37aC9gI2Skuq:-O2UwSAr77jdaDscFlud:b-74rov3) ([raw file](https://github.com/sillsdev/TheCombine/blob/7c30de3d894c97578af5b8d6d4fda04243ec8c35/deploy/scripts/setup_files/profiles/nuc_qa.yaml#L14)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

We added both `thecombine.app` and `qa-kube.thecombine.app` explicitly in generating the keys, but it would be good to know if it works on other `*.thecombine.app` domains.
</blockquote></details>

It looks like CloudFlare is using a different scope for their domains than I would expect:

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3249)* status: all files reviewed, 3 unresolved discussions (waiting on @imnasnainaec)

___
*[`deploy/helm/thecombine/charts/backend/values.yaml` line 21 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O2Fq5te8lMOBQNX7YDF:-O2V02ER4aopCvYPrYJE:bok1bkt) ([raw file](https://github.com/sillsdev/TheCombine/blob/7c30de3d894c97578af5b8d6d4fda04243ec8c35/deploy/helm/thecombine/charts/backend/values.yaml#L21)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Aren't default values being pulled from `deploy\helm\thecombine\values.yaml`?
</blockquote></details>

I had thought that the global values needed to be re-declared in the sub-charts - similar to defining an external reference.  Perhaps that is not the case.  It seems to work correctly and is cleaner this way.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3249)* status: 51 of 52 files reviewed, 3 unresolved discussions (waiting on @jmgrady)

___
*[`.github/workflows/deploy_qa.yml` line 7 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O20rYyW-Hpc_t5oT3v7:-O2Zta9g1SUeW8-8iZAc:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/d805fb45c91e754a1aaf42f6f27f9e47860ea8d2/.github/workflows/deploy_qa.yml#L7)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

That make sense.  I will leave this unresolved until the testing is complete and this file is updated.
</blockquote></details>

Done.
___
*[`.github/workflows/deploy_qa.yml` line 98 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O20rcR4Btzyhoq2CcCc:-O2ZtcWl06pdVKahuwtV:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/d805fb45c91e754a1aaf42f6f27f9e47860ea8d2/.github/workflows/deploy_qa.yml#L98)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.
___
*[`Backend/Startup.cs` line 198 at r5](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O255OYV1xNI4xkd5JZi:-O2Zth-xAbyUQTNg102g:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/0bb8630c684f4a48e4eaa7069efc65a710838a94/Backend/Startup.cs#L198)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

These log errors if turnstile is not setup but it is a valid configuration if it is not enabled.  These errors should only be logged if Turnstile is turned on.  Perhaps `_logger.LogInformation` can be called when Turnstile is disabled.
</blockquote></details>

Done.

**Review by jmgrady — COMMENTED** [review]
> Reviewed 4 of 4 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3249)* status: all files reviewed, 2 unresolved discussions (waiting on @imnasnainaec)

___
*[`deploy/helm/thecombine/charts/frontend/values.yaml` line 17 at r15](https://reviewable.io/reviews/sillsdev/TheCombine/3249#-O2_srXPELz6ZSvrbFg0:-O2_srXPELz6ZSvrbFg1:bwn1lak) ([raw file](https://github.com/sillsdev/TheCombine/blob/68b4a310e05248804247fe030ede5a6fa0c3c383/deploy/helm/thecombine/charts/frontend/values.yaml#L17)):*
> ```YAML
>   imageRegistry: ""
>   imageTag: "latest"
>   pullSecretName: aws-login-credentials
> ```

The default `pullSecretName` should be the same for all the subcharts.  It is "aws-login-credentials" here and "None" for the backend.  This was my error.
"None" is probably the better value.  Originally, all deployments needed the image pull secrets to pull images from the AWS ECR private registry. Now the QA server is the only one that does that; the rest pull releases from the public registry.

I am fine with deferring this to a later clean up task.



_Code quote:_
```YAML
  pullSecretName: aws-login-credentials
```

**Review by jmgrady — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3249)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

**Review by jmgrady — APPROVED** [review]
> Reviewed 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3249)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
