### PR TITLE
Backup/Restore on kubernetes

### LINKED ISSUE #1285: Implement Backup/Restore for TheCombine in Kubernetes environment

### PR DESCRIPTION
**Pull request by jmgrady**
Port the existing `combine_backup.py` and `combine_restore.py` scripts replacing use of `docker-compose` with `kubectl` to access the `backend` and `database` containers.

Create a Kubernetes CronJob to run the back up once per day.

Closes #1285

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1313)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[tox.ini, line 28 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZBbD0-KfkXCxFSSKa:-MhZBbD1DP4PQIrrlHtD:b-nz04uz) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/tox.ini#L28)):*
> ```INI
>     mypy deploy scripts
>     mypy --platform linux certmgr/scripts
>     mypy --platform linux maintenance/scripts
> ```

We could simplify this to

```
mypy --platform linux certmgr/scripts maintenance/scripts
```

**Comment by johnthagen** [comment]
___
*[certmgr/Dockerfile, line 16 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZC0c215uA5vt_bZ04:-MhZC0c215uA5vt_bZ05:b-ml2833) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/certmgr/Dockerfile#L16)):*
> ```Dockerfile
> 
> 
> FROM ubuntu:focal
> ```

Did we want to use `ubuntu:20.04` style naming here as well?

**Comment by johnthagen** [comment]
___
*[deploy/roles/k8s_config/defaults/main.yml, line 59 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZDjr327SLocKpK4UV:-MhZDjr327SLocKpK4UW:b-4muzqy) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/deploy/roles/k8s_config/defaults/main.yml#L59)):*
> ```YAML
> #######################################
> # Default Backup Schedule
> combine_backup_schedule: "15 10 * * *"
> ```

For those of us who can't read `crontab` format natively :D it may be worth adding a simply comment about these crons to the effect of "runs every day at 7PM"? We'd have to make sure the comment stays in sync.

Then again, there our sites to decode: https://crontab.guru/#15_10_*_*_*

So maybe this isn't a big deal. Just something I thought of while reviewing.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 4 of 36 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1313)* status: 4 of 36 files reviewed, 3 unresolved discussions (waiting on @jmgrady)

**Comment by johnthagen** [comment]
___
*[maintenance/Dockerfile, line 1 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZPIHjAdFtEj38Psxy:-MhZPIHjAdFtEj38Psxz:bb53s72) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/maintenance/Dockerfile#L1)):*
> ```Dockerfile
> # Dockerfile to build a Combine Maintenance container.  The Maintenance image
> ```

Should we add a brief `README` to the maintenance folder that explains the purpose and function of this sub-project?

**Comment by johnthagen** [comment]
___
*[maintenance/Dockerfile, line 21 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZPW2g4zongMwi6H6d:-MhZPW2g4zongMwi6H6e:b-m3cud7) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/maintenance/Dockerfile#L21)):*
> ```Dockerfile
> WORKDIR /home/user
> 
> RUN pip3 install humanfriendly
> ```

It would make this more reproducible if we pinned `humanfriendly`, likely in a `requirements.txt` file so that if the version bumps, we can avoid breaking an older tagged version of The Combine.

**Comment by johnthagen** [comment]
___
*[maintenance/Dockerfile, line 1 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZPkNoDiNl8AjzpIvA:-MhZPkNoDiNl8AjzpIvB:btx2hya) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/maintenance/Dockerfile#L1)):*
> ```Dockerfile
> # Dockerfile to build a Combine Maintenance container.  The Maintenance image
> ```

Could we add another GitHub Actions CI job that builds this `Dockerfile`? That will help us catch any regressions or external changes that cause failure.

**Comment by johnthagen** [comment]
___
*[maintenance/scripts/aws_backup.py, line 20 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZQ3404gqQvw_awPPF:-MhZQ3404gqQvw_awPPG:b-15wb79) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/maintenance/scripts/aws_backup.py#L20)):*
> ```Python
>     def push(self, src: Path, dest: str) -> subprocess.CompletedProcess[str]:
>         """Push a file to the AWS S3 bucket."""
>         s3_uri = f"s3://{self.bucket}/{dest}"
> ```

`f"s3://{self.bucket}` is used three times. We could extract this into a small immutable private method and reuse it.

To denote a private name in Python, prefix the name with `_` by convention.

**Comment by johnthagen** [comment]
___
*[maintenance/scripts/combine_app.py, line 166 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZQiMnE8-E1bGg8vRh:-MhZQiMnE8-E1bGg8vRi:bewf4sg) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/maintenance/scripts/combine_app.py#L166)):*
> ```Python
>         """Get the list of all user roles for a project that have the requested permission set."""
>         query = f"{{projectId: '{proj_id}', permissions: {{ $all: [{perm.value}]}}}}"
>         result_fields = "{projectId: 1, permissions: 1}"
> ```

There appears to be some copy/paste errors here. Duplicated `return` statements.

**Comment by johnthagen** [comment]
___
*[maintenance/scripts/combine_restore.py, line 117 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZRNVl3ININHxI1zy2:-MhZRNVl3ININHxI1zy3:b-sioqwj) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/maintenance/scripts/combine_restore.py#L117)):*
> ```Python
> 
>         # step.print("Stop the frontend and certmgr containers.")
>         # combine.stop(["frontend", "certmgr"])
> ```

Remove dead code?

**Comment by johnthagen** [comment]
___
*[maintenance/scripts/combine_restore.py, line 177 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZRRu47LtFgi_eyyiy:-MhZRRu47LtFgi_eyyiz:b-sioqwj) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/maintenance/scripts/combine_restore.py#L177)):*
> ```Python
>         )
>         # step.print("Restart the containers.")
>         # combine.start(["certmgr", "frontend"])
> ```

Remove dead code?

**Comment by johnthagen** [comment]
___
*[maintenance/scripts/script_step.py, line 6 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZRbSW8LashsnUzxM9:-MhZRbSW8LashsnUzxMA:b-xu5vlv) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/maintenance/scripts/script_step.py#L6)):*
> ```Python
> 
> 
> class ScriptStep:
> ```

This could be re-written to be a little more succinct using a `dataclass`

```
from dataclasses import dataclass

@dataclass
class ScriptStep:
    step_num: int

    def print(self, descr: str) -> None:
        """Print the step number with its description and bump the step number."""
        logging.info("  %i. %s", self.step_num, descr)
        self.step_num += 1

```

**Comment by johnthagen** [comment]
___
*[maintenance/scripts/debug.py, line 5 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZS_lBAgLxhNSEe2MX:-MhZS_lBAgLxhNSEe2MY:bakkb94) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/maintenance/scripts/debug.py#L5)):*
> ```Python
> from combine_app import CombineApp, Permission
> 
> if __name__ == "__main__":
> ```

Should this file have been checked in? It looks like a temporary testing script.

**Comment by johnthagen** [comment]
___
*[maintenance/scripts/maint_utils.py, line 33 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZSmo20xCUmK_Thi3a:-MhZSmo20xCUmK_Thi3b:bcjlri7) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/maintenance/scripts/maint_utils.py#L33)):*
> ```Python
>     Wait until dependent deployments get to specified condition.
> 
>     deployments -- list of the deployments to wait for.  The function will
> ```

For consistency elsewhere, we could use the Google Style Doc Strings as shown here: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

**Review by johnthagen — CHANGES_REQUESTED** [review]
> Reviewed 32 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1313)* status: all files reviewed, 13 unresolved discussions (waiting on @jmgrady)

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1313)* status: 27 of 39 files reviewed, 8 unresolved discussions (waiting on @jmgrady and @johnthagen)

___
*[tox.ini, line 28 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZBbD0-KfkXCxFSSKa:-MhZX-rx5UcrCZj8R871:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/tox.ini#L28)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

We could simplify this to

```
mypy --platform linux certmgr/scripts maintenance/scripts
```
</blockquote></details>

Done.
___
*[certmgr/Dockerfile, line 16 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZC0c215uA5vt_bZ04:-MhZXDBg73qNkeqZhesK:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/certmgr/Dockerfile#L16)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Did we want to use `ubuntu:20.04` style naming here as well?
</blockquote></details>

Done.
___
*[deploy/roles/k8s_config/defaults/main.yml, line 59 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZDjr327SLocKpK4UV:-MhZXWTZ6kEWkaOFghX_:b-9aky9q) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/deploy/roles/k8s_config/defaults/main.yml#L59)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

For those of us who can't read `crontab` format natively :D it may be worth adding a simply comment about these crons to the effect of "runs every day at 7PM"? We'd have to make sure the comment stays in sync.

Then again, there our sites to decode: https://crontab.guru/#15_10_*_*_*

So maybe this isn't a big deal. Just something I thought of while reviewing.
</blockquote></details>

Done.  
I agree.  I have to look up the format every time I look at a `crontab`!
___
*[maintenance/Dockerfile, line 1 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZPIHjAdFtEj38Psxy:-MhZYkrmDZN9Gx9p4QlG:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/maintenance/Dockerfile#L1)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Should we add a brief `README` to the maintenance folder that explains the purpose and function of this sub-project?
</blockquote></details>

Done.
___
*[maintenance/Dockerfile, line 1 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZPkNoDiNl8AjzpIvA:-MhZf44g2nTyAbY6O6Jy:bmhyv62) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/maintenance/Dockerfile#L1)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Could we add another GitHub Actions CI job that builds this `Dockerfile`? That will help us catch any regressions or external changes that cause failure.
</blockquote></details>

I copied the example for the backend and created certmgr.yml and maintenance.yml.  Would it be worth having a separate workflow for the docker builds?  i.e. would that allow us to only do the full checkout once?
___
*[maintenance/Dockerfile, line 21 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZPW2g4zongMwi6H6d:-MhZZM6a0XXg3_h1P_AN:bw2p80) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/maintenance/Dockerfile#L21)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

It would make this more reproducible if we pinned `humanfriendly`, likely in a `requirements.txt` file so that if the version bumps, we can avoid breaking an older tagged version of The Combine.
</blockquote></details>

Does this run every time the container is started?  If so, that is not my intention.  It should only be installed when the container is built.  I thought it only ran during the building of the image.
___
*[maintenance/scripts/aws_backup.py, line 20 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZQ3404gqQvw_awPPF:-MhZcDo16BO2W7vdn1l9:b-9zj2wx) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/maintenance/scripts/aws_backup.py#L20)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

`f"s3://{self.bucket}` is used three times. We could extract this into a small immutable private method and reuse it.

To denote a private name in Python, prefix the name with `_` by convention.
</blockquote></details>

I just changed it so that `self.bucket` has the "s3://" prefix added.
___
*[maintenance/scripts/combine_app.py, line 166 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZQiMnE8-E1bGg8vRh:-MhZcnWj-jAQjJ7_PPhp:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/maintenance/scripts/combine_app.py#L166)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

There appears to be some copy/paste errors here. Duplicated `return` statements.
</blockquote></details>

Done.
___
*[maintenance/scripts/combine_restore.py, line 117 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZRNVl3ININHxI1zy2:-MhZd-FgBAEOkp7F-FYr:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/maintenance/scripts/combine_restore.py#L117)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Remove dead code?
</blockquote></details>

Done.
___
*[maintenance/scripts/combine_restore.py, line 177 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZRRu47LtFgi_eyyiy:-MhZd0vL8S3RInCqXmhG:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/maintenance/scripts/combine_restore.py#L177)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Remove dead code?
</blockquote></details>

Done.
___
*[maintenance/scripts/maint_utils.py, line 33 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZSmo20xCUmK_Thi3a:-MhZe4OHBAIm3nI8kve-:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/maintenance/scripts/maint_utils.py#L33)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

For consistency elsewhere, we could use the Google Style Doc Strings as shown here: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html
</blockquote></details>

Done.
___
*[maintenance/scripts/script_step.py, line 6 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZRbSW8LashsnUzxM9:-MhZeHQ_2Mz86I2b6iyE:b64jnr) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/maintenance/scripts/script_step.py#L6)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This could be re-written to be a little more succinct using a `dataclass`

```
from dataclasses import dataclass

@dataclass
class ScriptStep:
    step_num: int

    def print(self, descr: str) -> None:
        """Print the step number with its description and bump the step number."""
        logging.info("  %i. %s", self.step_num, descr)
        self.step_num += 1

```
</blockquote></details>

How does the `step_num` get initialized?
___
*[maintenance/scripts/debug.py, line 5 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZS_lBAgLxhNSEe2MX:-MhZd4R095fgUF7J2O_s:b-bpye65) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/maintenance/scripts/debug.py#L5)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Should this file have been checked in? It looks like a temporary testing script.
</blockquote></details>

No, it shouldn't.  I have removed it.

**Comment by johnthagen** [comment]
___
*[maintenance/Dockerfile, line 21 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZPW2g4zongMwi6H6d:-MhZh8QU66n7U5OGUnpv:bxll8fg) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/maintenance/Dockerfile#L21)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Does this run every time the container is started?  If so, that is not my intention.  It should only be installed when the container is built.  I thought it only ran during the building of the image.
</blockquote></details>

It only runs at build time, but because PyPI artifacts (and versions) can change, if we don't pin something that previously built might not build again (not reproducible). This can make our build process (and CI) not stable.

The way to address this is to pin dependencies, such as this.

**Comment by johnthagen** [comment]
___
*[maintenance/scripts/aws_backup.py, line 20 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZQ3404gqQvw_awPPF:-MhZhkPZ9EXlrsbcOC6J:b9flql9) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/maintenance/scripts/aws_backup.py#L20)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

I just changed it so that `self.bucket` has the "s3://" prefix added.
</blockquote></details>

Even better.

**Comment by johnthagen** [comment]
___
*[maintenance/Dockerfile, line 1 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZPkNoDiNl8AjzpIvA:-MhZi5rQEQYXSmaaOnt5:b-eqg1rh) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/maintenance/Dockerfile#L1)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

I copied the example for the backend and created certmgr.yml and maintenance.yml.  Would it be worth having a separate workflow for the docker builds?  i.e. would that allow us to only do the full checkout once?
</blockquote></details>

I think the way we have it is good, because the jobs can run in parallel and the checkout cost is probably miniscule compared to the builds themselves.

**Comment by johnthagen** [comment]
___
*[maintenance/scripts/script_step.py, line 6 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZRbSW8LashsnUzxM9:-MhZiSG79A0qXifVdKKD:b-v4zk8u) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/maintenance/scripts/script_step.py#L6)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

How does the `step_num` get initialized?
</blockquote></details>

My example should be modified slightly to take into account the default value:

```py
from dataclasses import dataclass

@dataclass
class ScriptStep:
    step_num: int = 1

    def print(self, descr: str) -> None:
        """Print the step number with its description and bump the step number."""
        logging.info("  %i. %s", self.step_num, descr)
        self.step_num += 1
```

Dataclasses automatically generate a constructor (See beginning of https://docs.python.org/3/library/dataclasses.html) so you would use the `ScriptStep` exactly how you are currently using it.

There is a little magic that happens in a `dataclass` to make the very common use case nice and concise. Because of this, their use within the Python ecosystem is exploding.

Thinking about this particular case some more, I think it's actually okay if we don't convert to a dataclass in this instance, since we don't want to expose a user being able to change `step_num` on creation. I think we can leave this as is, but in general `dataclass`es can be very powerful.

**Review by johnthagen — COMMENTED** [review]
> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1313)* status: all files reviewed, 1 unresolved discussion (waiting on @jmgrady)

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1313)* status: all files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[maintenance/Dockerfile, line 21 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZPW2g4zongMwi6H6d:-MhZo25w9R-hQpltZUOV:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/maintenance/Dockerfile#L21)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

It only runs at build time, but because PyPI artifacts (and versions) can change, if we don't pin something that previously built might not build again (not reproducible). This can make our build process (and CI) not stable.

The way to address this is to pin dependencies, such as this.
</blockquote></details>

Done.
___
*[maintenance/scripts/script_step.py, line 6 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1313#-MhZRbSW8LashsnUzxM9:-MhZpq1SDE79uHYQ2hti:bwjr6mj) ([raw file](https://github.com/sillsdev/thecombine/blob/1d97b785f327e95500041f247b68408e6b2fa59a/maintenance/scripts/script_step.py#L6)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

My example should be modified slightly to take into account the default value:

```py
from dataclasses import dataclass

@dataclass
class ScriptStep:
    step_num: int = 1

    def print(self, descr: str) -> None:
        """Print the step number with its description and bump the step number."""
        logging.info("  %i. %s", self.step_num, descr)
        self.step_num += 1
```

Dataclasses automatically generate a constructor (See beginning of https://docs.python.org/3/library/dataclasses.html) so you would use the `ScriptStep` exactly how you are currently using it.

There is a little magic that happens in a `dataclass` to make the very common use case nice and concise. Because of this, their use within the Python ecosystem is exploding.

Thinking about this particular case some more, I think it's actually okay if we don't convert to a dataclass in this instance, since we don't want to expose a user being able to change `step_num` on creation. I think we can leave this as is, but in general `dataclass`es can be very powerful.
</blockquote></details>

I like it!
Done.

**Review by johnthagen — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1313)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Pull request merged**
