### PR TITLE
[MergeDups, ReveiwEntries] Add flags to words

### LINKED ISSUE #1429: Add feature to flag senses
Especially in places like MergeDuplicates, where entry editing is limiting, it would be good to be able to flag entries that need further work.

The base of this ticket, applied to words, is handled in #1548 
This ticket is to extend that to flag senses, if deemed necessary.

Review Entries:
* A Flags column between vern and senses to find/sort by flags
* In sense column, in edit mode, add sense-specific flag(-note)s next to sense delete/trash

MergeDuplicates:
* Add flag icon to top-right of each entry (grey unflagged vs color flagged; outlined, but filled on mouse-over)
* Flag brings up dialog, with list of notes, one more input field than existing notes
* Next to each input field: option to assign the note to a sense of the word; and option to delete the flag field
* At bottom of dialog: buttons to delete all, save all
* If sense moved to a different entry, flag-notes need to move also
* If last flag-note moved away from an entry, unflag entry
* Add flags to database post-merge

### LINKED ISSUE #1528: Add entry flags to Merge Duplicates and Review Entries
First part of #1429--just flags for entries with nothing sense-specific.

Behavior to test:
1. Data Cleanup > Merge Duplicates
2. Identify flag icon/button in upper-right corner of every word
3. Test the flag button interaction:
a. Grey outline when no flag
b. Mouse-over text "Add a flag" when no flag
c. Click on flag to bring up dialog for editing flag
d. ESC closes dialog without any changes
e. "Save Flag" button turns on the flag *even if no text is added*
f. Red filled when flag added
g. Mouse-over text is flag-text when there is a flag
h. Clicking on the flag and clicking "Remove flag" removes the flag
4. Add a flag to at least one word, then press the "Save and Continue" button at the bottom-left
5. Data Cleanup > look at the "You've completed:" section
6. Click the most recent, a Merge Duplicates with at least one merge.
7. Evaluate the appearance and (lack of) behavior of the flags
a. A red filled-in flag should be present on the words with flags
b. Mouse-over the flags to see the flag text
c. Clicking the flag shouldn't do anything here
d. No flag at all (not even grey outline) on the words with no flag
8. Data Cleanup > Review Entries
9. Evaluate the "Flag" column near the right end of the table
a. Click the button to sort by flag: all the flagged entries should come to the top; mouse-over should reveal that they are sorted in alphabetical order
b. Filter by text and only rows with that text in their flag should remain
c. Clicking on flags shouldn't do anything
d. Rows with no flag should be empty in the flag column (not even grey outline)
10. Evaluate flag interaction within a row's edit mode
a. Click on the edit icon at the far-left end of a row
b. In edit mode, the flag should be interactive with exactly the same behavior as within Merge Duplicates
d. Changes to the flag only update when the row is saved

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #1528

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1548)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 8 of 16 files at r1, 38 of 38 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1548)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by jasonleenaylor — CHANGES_REQUESTED** [review]
Filters on the columns appear to be broken in this PR.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1548#-:-MvLJP3ZBfH5wOSAq4CG:bq21lro)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by jasonleenaylor — APPROVED** [review]
Filters are fixed now, thanks.

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1548#-:-MvPTVLy4F8WfWztEogM:bb9e23h)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx, line 155 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1548#-MvPRuSU-_2-zBdslmfO:-MvPRuSU-_2-zBdslmfP:b-99kh2g) ([raw file](https://github.com/sillsdev/thecombine/blob/98ed86b6bcf4c343fd55a757a6e37df5a3b96a14/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx#L155)):*
> ```XML
>           onRowDataChange={props.onRowDataChange}
>           delete={deleteSense}
>           value
> ```

I think this is working right, but I noticed that in other places we were using props.value and here it was always just turning it on. 



_Code quote:_
```XML
value
```
___
*[src/goals/ReviewEntries/ReviewEntriesComponent/tests/CellColumns.test.tsx, line 97 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1548#-MvPSbZWDcz0SEKMhFo-:-MvPSbZWDcz0SEKMhFo0:bg226u4) ([raw file](https://github.com/sillsdev/thecombine/blob/42c8525d645f5409396c2280134f0093ce9a2347/src/goals/ReviewEntries/ReviewEntriesComponent/tests/CellColumns.test.tsx#L97)):*
> ```XML
> const SORT_BY_GLOSSES = [WORD_3, WORD_1, WORD_2, WORD_0];
> const SORT_BY_DOMAINS = [WORD_2, WORD_0, WORD_3, WORD_1];
> const SORT_BY_FLAGIES = [WORD_0, WORD_2, WORD_1, WORD_3];
> ```

:laughing: 
I admire your effort to keep the alignment for code readability. 



_Code quote:_
```XML
SORT_BY_FLAGIES
```

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1548)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx, line 155 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1548#-MvPRuSU-_2-zBdslmfO:-MvPlRjq6L9VZPrO8NeT:budmdk3) ([raw file](https://github.com/sillsdev/thecombine/blob/98ed86b6bcf4c343fd55a757a6e37df5a3b96a14/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx#L155)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

I think this is working right, but I noticed that in other places we were using props.value and here it was always just turning it on. 
</blockquote></details>

That was something I accidentally did when adding the sense column last June (https://github.com/sillsdev/TheCombine/commit/41a6f7683ac98066e4b71ee817e0ea28547e41ff#diff-dac87601378be84c31e8f71b725e4afab0d795a08fea63728d8deb1e1248db74). It turns out to be a valid way to turn it on when you don't actually use the value in the component.

**Pull request merged**
