### PR TITLE
[ReviewEntriesSense] Refactor to maintain goals.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Progress toward #912

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1027)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 10 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1027)* status: 10 of 14 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec)

___
*[src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesActions.tsx, line 184 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1027#-MTkhvpD527eFcVoGta7:-MTkhvpECY44BL-l2LQ5:b3gcyig) ([raw file](https://github.com/sillsdev/thecombine/blob/1e53f915a6423f7320ba9658bf020711eae6b5f3/src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesActions.tsx#L184)):*
> ```XML
>     // Get the original word, for updating.
>     const editWord = await backend.getWord(editSource.id);
> ```

Should we set the language to the first analysis language from the project settings if it is undefined? Or perhaps make it required here and pass in the first analysis language?
___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx, line 139 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1027#-MTkK40XBTZKp3g_0T_C:-MTkK40Y4Tkuq0A_vltw:bw482i8) ([raw file](https://github.com/sillsdev/thecombine/blob/1e53f915a6423f7320ba9658bf020711eae6b5f3/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx#L139)):*
> ```XML
>       }
> 
>       for (
> ```

I think there is a tiny bug in the previous implementation of compare that you have retained.
Words with different numbers of senses that have the first sense in common will compare equal.
I think the return after the loop should be a.senses.length - b.senses.length (or vice versa)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1027)* status: 9 of 14 files reviewed, all discussions resolved (waiting on @imnasnainaec and @jasonleenaylor)

___
*[src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesActions.tsx, line 184 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1027#-MTkhvpD527eFcVoGta7:-MTlQsar4JxQAJMht1Nu:bog4f0z) ([raw file](https://github.com/sillsdev/thecombine/blob/1e53f915a6423f7320ba9658bf020711eae6b5f3/src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesActions.tsx#L184)):*
I had intentionally left `language` as optional in this function (in conjunction with the code below, from around L210) to allow for the case that all languages had been displayed.
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
>       // If there are edited glosses, replace the previous glosses with them.
>       if (displaySense.glosses.length) {
>         const newGlosses = [...displaySense.glosses];
>         // If a language was specified, add all glosses of other langauges from the original.
>         if (language) {
>           newGlosses.push(
>             ...editSense.glosses.filter((g) => g.language !== language)
>           );
>         }
>         editSense.glosses = newGlosses;
>       }
> ```
</details>

___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx, line 139 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1027#-MTkK40XBTZKp3g_0T_C:-MTlRg_b1x8f7sCk0FwP:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/1e53f915a6423f7320ba9658bf020711eae6b5f3/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx#L139)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

I think there is a tiny bug in the previous implementation of compare that you have retained.
Words with different numbers of senses that have the first sense in common will compare equal.
I think the return after the loop should be a.senses.length - b.senses.length (or vice versa)
</blockquote></details>

Done

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1027)* status: 10 of 14 files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesActions.tsx, line 184 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1027#-MTkhvpD527eFcVoGta7:-MTl_daP9_Ojjpt6dqQd:b-lizkhz) ([raw file](https://github.com/sillsdev/thecombine/blob/1e53f915a6423f7320ba9658bf020711eae6b5f3/src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesActions.tsx#L184)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I had intentionally left `language` as optional in this function (in conjunction with the code below, from around L210) to allow for the case that all languages had been displayed.

> ```
>       // If there are edited glosses, replace the previous glosses with them.
>       if (displaySense.glosses.length) {
>         const newGlosses = [...displaySense.glosses];
>         // If a language was specified, add all glosses of other langauges from the original.
>         if (language) {
>           newGlosses.push(
>             ...editSense.glosses.filter((g) => g.language !== language)
>           );
>         }
>         editSense.glosses = newGlosses;
>       }
> ```

</blockquote></details>

I think the code below is good, but should probably happen no matter what language is passed to this method. But perhaps I'm confused about how this method is called in the component. I'll look it over more carefully after lunch.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 4 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1027)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
