### PR TITLE
Improve code quality for combine maintenance scripts

### PR DESCRIPTION
**Pull request by jmgrady**
Improve the code quality of the maintenance scripts added with PR #1031.

- Use single exit code for failure
- Specify user permissions using an enumerated type
- Consistent quoting of string literals
- Improve help wording

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1041)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[deploy/roles/combine_maintenance/files/add_user_to_proj.py, line 82 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1041#-MUUHhNN3_nHvklR9ScO:-MUUHhNN3_nHvklR9ScP:b-dg0lb9) ([raw file](https://github.com/sillsdev/thecombine/blob/4f98708bd4aafb962207e170a3b5331d9d14b174/deploy/roles/combine_maintenance/files/add_user_to_proj.py#L82)):*
> ```Python
>             print(f"UserRole ID: {user_role_id}")
>         select_role = f'{{ _id: ObjectId("{user_role_id}")}}'
>         update_role = '{ $set: { "permissions" : [5,4,3,2,1]} }'
> ```

Could we refactor this so that we don't have to use the bare integer values anywhere?

Perhaps if we moved the definition of `user_permissions` up so it could be use in both branches of `if result is not None:`

**Review by johnthagen — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1041)* status: all files reviewed, 1 unresolved discussion (waiting on @jmgrady)

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1041)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[deploy/roles/combine_maintenance/files/add_user_to_proj.py, line 82 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1041#-MUUHhNN3_nHvklR9ScO:-MUUjKDN9AJmLLw2QMUQ:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/698476f3c0b34d40f02fb2a8390cf387ab875081/deploy/roles/combine_maintenance/files/add_user_to_proj.py#L82)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Could we refactor this so that we don't have to use the bare integer values anywhere?

Perhaps if we moved the definition of `user_permissions` up so it could be use in both branches of `if result is not None:`
</blockquote></details>

Done.

**Review by johnthagen — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1041)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
