### PR TITLE
Use new sem dom api

### PR DESCRIPTION
**Pull request by jasonleenaylor**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1735)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 24 of 58 files at r1, 8 of 13 files at r2, 2 of 26 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1735)* status: 34 of 68 files reviewed, 9 unresolved discussions (waiting on @imnasnainaec and @jasonleenaylor)

___
*[`Backend/Models/SemanticDomain.cs` line 26 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1735#-NCQd1Fo8excXfIFFFjL:-NCQd1Fo8excXfIFFFjM:b-2gt0nn) ([raw file](https://github.com/sillsdev/thecombine/blob/503ffb58093a68e2401ae5c830fa80b802530d09/Backend/Models/SemanticDomain.cs#L26)):*
> ```Smalltalk
>         [BsonElement("id")]
>         public string Id { get; set; }
> ```

remove extra newline
___
*[`Backend/Services/LiftService.cs` line 322 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1735#-NCQe1_42oY9nhia-qxW:-NCQe1_42oY9nhia-qxX:b1wn1mr) ([raw file](https://github.com/sillsdev/thecombine/blob/503ffb58093a68e2401ae5c830fa80b802530d09/Backend/Services/LiftService.cs#L322)):*
> ```Smalltalk
>                 foreach (var sd in proj.SemanticDomains)
>                 {
>                     WriteRangeElement(liftRangesWriter, sd.Id, Guid.NewGuid().ToString(), sd.Name);
> ```

now that `sd` will have a `.guid`, we should use that here instead of generating a new, random one
___
*[`src/i18n.ts` line 14 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1735#-NCQhCMsA8rqp1hXJYLW:-NCQhCMsA8rqp1hXJYLX:b-s36j82) ([raw file](https://github.com/sillsdev/thecombine/blob/503ffb58093a68e2401ae5c830fa80b802530d09/src/i18n.ts#L14)):*
> ```XML
>   .use(initReactI18next)
>   .init({
>     //debug: true, // Uncomment to troubleshoot// detection: options,
> ```

for readability, separate distinct pieces with new line before `// detection:...`
___
*[`src/backend/index.ts` line 96 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1735#-NCQi6AW3ezGycGLYP9N:-NCQi6AW3ezGycGLYP9O:b-hah8ck) ([raw file](https://github.com/sillsdev/thecombine/blob/503ffb58093a68e2401ae5c830fa80b802530d09/src/backend/index.ts#L96)):*
> ```XML
> const userRoleApi = new Api.UserRoleApi(config, BASE_PATH, axiosInstance);
> const wordApi = new Api.WordApi(config, BASE_PATH, axiosInstance);
> const semanticDomainApi = new Api.SemanticDomainApi(
> ```

to maintain alphabetical order, it would be nice for the new `semanticDomainApi` to go between `projectApi` and `userApi` (here and in the sections below).
___
*[`src/components/TreeView/tests/TreeSearch.test.tsx` line 7 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1735#-NCQjIme9aUTbwMjijtt:-NCQjIme9aUTbwMjijtu:bxxbm14) ([raw file](https://github.com/sillsdev/thecombine/blob/503ffb58093a68e2401ae5c830fa80b802530d09/src/components/TreeView/tests/TreeSearch.test.tsx#L7)):*
> ```XML
> import { Key } from "ts-key-enum";
> 
> import "tests/mockReactI18next";
> ```

since `import "tests/mockReactI18next";` has to come before the other internal imports (which is why it wan't sorted with the rest), it'd be nice to add a newline after it (and/or a comment explicitly stating that it has to come before the others)
___
*[`src/components/TreeView/tests/TreeViewActions.test.tsx` line 4 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1735#-NCQj8cG4LFtbxZl7Z8g:-NCQj8cG4LFtbxZl7Z8h:bjlpcf5) ([raw file](https://github.com/sillsdev/thecombine/blob/503ffb58093a68e2401ae5c830fa80b802530d09/src/components/TreeView/tests/TreeViewActions.test.tsx#L4)):*
> ```XML
> import thunk from "redux-thunk";
> 
> import { TreeActionType } from "../TreeViewReduxTypes";
> ```

absolute path for imports preferred
___
*[`src/components/TreeView/tests/TreeViewComponent.test.tsx` line 8 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1735#-NCQj1Bg5cKJL_s8emW4:-NCQj1Bg5cKJL_s8emW5:b-ax873i) ([raw file](https://github.com/sillsdev/thecombine/blob/503ffb58093a68e2401ae5c830fa80b802530d09/src/components/TreeView/tests/TreeViewComponent.test.tsx#L8)):*
> ```XML
> import configureMockStore from "redux-mock-store";
> import "tests/mockReactI18next";
> import thunk from "redux-thunk";
> ```

the `redux-thunk` import should be in the first import section
___
*[`Backend/Contexts/SemanticDomainContext.cs` line 28 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1735#-NCQb_DC80aVdgZd1hf-:-NCQb_DDBp9wSTyxEynb:b-2mv5xe) ([raw file](https://github.com/sillsdev/thecombine/blob/503ffb58093a68e2401ae5c830fa80b802530d09/Backend/Contexts/SemanticDomainContext.cs#L28)):*
> ```Smalltalk
> // Add all the IOC bits
> // ???
> // Profit!
> ```

comment cleanup



_Code quote:_
```Smalltalk
// Get Context and Model connected to DB, Update SemanticDomainService to access the context to provide what the Controller needs
// Add all the IOC bits
// ???
// Profit!
```
___
*[`Backend/Interfaces/ISemanticDomainContext.cs` line 9 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1735#-NCQcm8kEpJJkBAZateV:-NCQcm8kEpJJkBAZateW:b-nd2umg) ([raw file](https://github.com/sillsdev/thecombine/blob/503ffb58093a68e2401ae5c830fa80b802530d09/Backend/Interfaces/ISemanticDomainContext.cs#L9)):*
> ```Smalltalk
>     {
>         public IMongoCollection<SemanticDomainTreeNode> SemanticDomains { get; }
>         public IMongoCollection<SemanticDomainFull> FullSemanticDomains { get; }
> ```

we don't have `public` on similar lines in the other `I*Context.cs` files



_Code quote:_
```Smalltalk
        public IMongoCollection<SemanticDomainTreeNode> SemanticDomains { get; }
        public IMongoCollection<SemanticDomainFull> FullSemanticDomains { get; }
```

**Review by jasonleenaylor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1735)* status: 34 of 68 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jasonleenaylor)

___
*[`Backend/Services/LiftService.cs` line 322 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1735#-NCQe1_42oY9nhia-qxW:-NCQuNMa8XVUMwyrCZAZ:b7edql6) ([raw file](https://github.com/sillsdev/thecombine/blob/503ffb58093a68e2401ae5c830fa80b802530d09/Backend/Services/LiftService.cs#L322)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

now that `sd` will have a `.guid`, we should use that here instead of generating a new, random one
</blockquote></details>

Hmm, good catch. Although these domains can currently only arrive through lift import, and might not have a GUID.

**Review by imnasnainaec — CHANGES_REQUESTED** [review]
> Reviewed 1 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1735)* status: 35 of 68 files reviewed, 10 unresolved discussions (waiting on @imnasnainaec and @jasonleenaylor)

*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/1735#-NCfEIHP7v8KesQgh_kR:-NCfEIHP7v8KesQgh_kS:b-d286s2) (no related file):*
Browsing the SemanticDomain tree, there are empty left arrows for domains with no `prev`, empty right arrows for domains with no `next`, and an empty up arrow from the head domain. Tracing this back, it appears that when `parent`, `prev`, or `next` is an empty object in the database, it is populated as a no-data SemanticDomain rather than as the `null` we want. I tried to remove these fields from the database or to replace them with `null` in the database, but both result in an error.

___
___
*[`Backend/Models/SemanticDomain.cs` line 62 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1735#-NCf6Tk_-fetbCf0Swrn:-NCf6Tke89__CzsQEQ6M:b-xdnw02) ([raw file](https://github.com/sillsdev/thecombine/blob/0cd44059d0d7819576b2e93821e24b82f301c2ea/Backend/Models/SemanticDomain.cs#L62)):*
> ```Smalltalk
>         public override int GetHashCode()
>         {
>             return HashCode.Combine(Name, Id, Lang);
> ```

What about `Guid` in the HashCode? (Also, not covered in the current Tests.)
___
*[`Backend/Models/SemanticDomain.cs` line 114 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1735#-NCf6b990Y32xBCm76XR:-NCf6b990Y32xBCm76XS:bumg0r) ([raw file](https://github.com/sillsdev/thecombine/blob/0cd44059d0d7819576b2e93821e24b82f301c2ea/Backend/Models/SemanticDomain.cs#L114)):*
> ```Smalltalk
>         public override int GetHashCode()
>         {
>             return HashCode.Combine(Name, Id, Description, Questions);
> ```

What about `Lang` and `Guid` in the HashCode? (Also, not covered in the current Tests.)
___
*[`Backend/Models/SemanticDomain.cs` line 147 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1735#-NCfGS7t-UFTBhp8KaJ9:-NCfGS7t-UFTBhp8KaJA:byt7d2z) ([raw file](https://github.com/sillsdev/thecombine/blob/0cd44059d0d7819576b2e93821e24b82f301c2ea/Backend/Models/SemanticDomain.cs#L147)):*
> ```Smalltalk
>         public SemanticDomain? Parent { get; set; }
>         [BsonElement("children")]
>         public List<SemanticDomain> Children { get; set; }
> ```

Should we make `Children` to be `[Required]` since it should always exists, even if only an empty set?
___
*[`Backend/Repositories/SemanticDomainRepository.cs` line 24 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1735#-NCf7y9J9vTqbdgTY40Q:-NCf7y9J9vTqbdgTY40R:b6ipn76) ([raw file](https://github.com/sillsdev/thecombine/blob/0cd44059d0d7819576b2e93821e24b82f301c2ea/Backend/Repositories/SemanticDomainRepository.cs#L24)):*
> ```Smalltalk
>                 filterDef.Eq(x => x.Lang, lang));
> 
>             var filterEn = filterDef.Eq("Lang", "en");
> ```

Is there a reason to prefer `"Lang"` and `"id"` in some places, but `x => x.Lang` and `x => x.Id` elsewhere?



_Code quote:_
```Smalltalk
                filterDef.Eq("id", id),
                filterDef.Eq(x => x.Lang, lang));

            var filterEn = filterDef.Eq("Lang", "en");
            var filterId = filterDef.Eq("id", "1");
```
___
*[`Backend/Repositories/SemanticDomainRepository.cs` line 28 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1735#-NCf7h4VDpOBFUnxnabL:-NCf7h4VDpOBFUnxnabM:b-z4ujhs) ([raw file](https://github.com/sillsdev/thecombine/blob/0cd44059d0d7819576b2e93821e24b82f301c2ea/Backend/Repositories/SemanticDomainRepository.cs#L28)):*
> ```Smalltalk
> 
>             Console.WriteLine("Total in Lang = " + lang + ";id=" + id + ": " + _context.SemanticDomains.CountDocuments(filter: filterEn));
>             Console.WriteLine("Total in Lang = " + lang + ";id=" + id + ": " + _context.SemanticDomains.CountDocuments(filter: filterId));
> ```

Are these two `Console.WriteLine`s meant to persist?
___
*[`Backend/Repositories/SemanticDomainRepository.cs` line 58 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1735#-NCfE7YU9GKDAQ8QqZoV:-NCfE7YU9GKDAQ8QqZoW:b-uefkuh) ([raw file](https://github.com/sillsdev/thecombine/blob/0cd44059d0d7819576b2e93821e24b82f301c2ea/Backend/Repositories/SemanticDomainRepository.cs#L58)):*
> ```Smalltalk
>                 Console.WriteLine(e.Message);
>                 Console.WriteLine("****");
>                 Console.WriteLine(e.StackTrace);
> ```

These `WriteLine`s are on the first two functions but not the third.
___
*[`Backend/Services/LiftService.cs` line 324 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1735#-NCfH0I5CM-ElYtDSj7T:-NCfH0I5CM-ElYtDSj7U:bk9i7f1) ([raw file](https://github.com/sillsdev/thecombine/blob/0cd44059d0d7819576b2e93821e24b82f301c2ea/Backend/Services/LiftService.cs#L324)):*
> ```Smalltalk
>                    var guid = string.IsNullOrEmpty(sd.Guid) || sd.Guid == Guid.Empty.ToString()
> 						  ? Guid.NewGuid().ToString()
> 						  : sd.Guid.ToString();
> ```

Isn't `sd.Guid` already a string?
___
*[`src/i18n.ts` line 14 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1735#-NCQhCMsA8rqp1hXJYLW:-NCf8XtI4L47hOILqTis:bnjdgem) ([raw file](https://github.com/sillsdev/thecombine/blob/503ffb58093a68e2401ae5c830fa80b802530d09/src/i18n.ts#L14)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

for readability, separate distinct pieces with new line before `// detection:...`
</blockquote></details>

Oh, I think the newline is being removed by Prettier. Maybe `//debug: true, // Uncomment to troubleshoot` can be moved to the end of `.init({ })`.
___
*[`src/backend/index.ts` line 408 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1735#-NCf9tKjELDLpwBLCcfS:-NCf9tKjELDLpwBLCcfT:bkwgy1w) ([raw file](https://github.com/sillsdev/thecombine/blob/0cd44059d0d7819576b2e93821e24b82f301c2ea/src/backend/index.ts#L408)):*
> ```XML
>   );
>   if (response.data) {
>     return response.data;
> ```

Why is this check necessary only on this function?

**Review by jasonleenaylor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1735)* status: 35 of 69 files reviewed, 4 unresolved discussions (waiting on @imnasnainaec and @jasonleenaylor)

___
*[`Backend/Models/SemanticDomain.cs` line 147 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1735#-NCfGS7t-UFTBhp8KaJ9:-NDDpAUwBN4wP97JSISD:b1jom7f) ([raw file](https://github.com/sillsdev/thecombine/blob/0cd44059d0d7819576b2e93821e24b82f301c2ea/Backend/Models/SemanticDomain.cs#L147)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Should we make `Children` to be `[Required]` since it should always exists, even if only an empty set?
</blockquote></details>

I'm not sure if this will gain us anything, I didn't have a chance to fully evaluate it yet.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 3 of 58 files at r1, 2 of 26 files at r3, 1 of 3 files at r4, 1 of 8 files at r5, 1 of 2 files at r6, 1 of 5 files at r7, 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1735)* status: 45 of 69 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @jasonleenaylor)

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 13 files at r2, 1 of 17 files at r9.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1735)* status: 43 of 70 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 2 files at r8, 2 of 17 files at r9, 1 of 5 files at r10.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1735)* status: 46 of 70 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

**Review by jmgrady — COMMENTED** [review]
> Reviewed 14 of 58 files at r1, 1 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1735)* status: 48 of 70 files reviewed, all discussions resolved (waiting on @imnasnainaec and @jasonleenaylor)

**Review by jmgrady — APPROVED** [review]
> Reviewed 1 of 58 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1735)* status: 48 of 70 files reviewed, all discussions resolved (waiting on @imnasnainaec and @jasonleenaylor)

**Review by jmgrady — APPROVED** [review]
> Reviewed 18 of 26 files at r3, 2 of 3 files at r4, 4 of 8 files at r5, 1 of 5 files at r7, 12 of 17 files at r9, 2 of 5 files at r10, 1 of 2 files at r15, 2 of 2 files at r16.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1735)* status: 67 of 70 files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
