### PR TITLE
Version Project

### PR DESCRIPTION
**Pull request by johnthagen**
- Use frontend `package.json` as the common version for the application
  -  Version number is statically compiled into the frontend using react-app env file
  - Version is displayed in the AppBar after logging in
- Add instructions to easily query the version using `npm` and `node` for use in CI and tagging of Docker images
  - `npm run --silent version`

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/724)

### CODE REVIEW

**Comment by johnthagen** [comment]
Currently the version is displayed in the AppBar:

Screenshot 2020-09-18 134711

**Comment by johnthagen** [comment]
For potential future reference, it is then possible to extract the version from a running Docker container:

````powershell
# Remove the ` before " when running on bash rather than powershell
> docker inspect --format '{{ index .Config.Labels `"com.github.sillsdev.thecombine.version`"}}' $(docker-compose ps -q backend)
0.1.0-alpha.0
```

Or a built image:

```powershell
# Remove the ` before " when running on bash rather than powershell
> docker image inspect --format '{{ index .Config.Labels `"com.github.sillsdev.thecombine.version`"}}' thecombine_backend
0.1.0-alpha.0
```

**Comment by imnasnainaec** [comment]
Location in AppBar conflicts with #699

**Comment by johnthagen** [comment]
Latest UI looks like:

Screenshot 2020-09-18 161438

**Review by jmgrady — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/724)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @jmgrady and @johnthagen)

*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/724#-MHaF67W-DT0YwyOZwNb:-MHaF67XDvmkPCeRmGxb:b-rr0d3k) (no related file):*
I have a question about the overall method.  Why not use `npm version` to manage the version string?  Is it because `thecombine` does not exist in the npm registry?  We will need an easy method to lookup the version number so that the docker containers can be tagged with the correct version as well - it is my understanding that I cannot specify which image to pull by label, only by tag.  That is why I am asking about `npm version`.  It seems that the standard method for looking up the version would be:
```
npm view thecombine version
```

---

**Comment by johnthagen** [comment]
*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/724#-MHaF67W-DT0YwyOZwNb:-MHaIzsHE1yXlb_Fe_v3:b-wlv0y9) (no related file):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

I have a question about the overall method.  Why not use `npm version` to manage the version string?  Is it because `thecombine` does not exist in the npm registry?  We will need an easy method to lookup the version number so that the docker containers can be tagged with the correct version as well - it is my understanding that I cannot specify which image to pull by label, only by tag.  That is why I am asking about `npm version`.  It seems that the standard method for looking up the version would be:
```
npm view thecombine version
```
</blockquote></details>

Can we assume that you will have `npm` installed anywhere you need to check the version? I was originally thinking you might want to check the version on a minimal Ubuntu VM (build runner, etc). 

---

**Review by jmgrady — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/724)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @johnthagen)

*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/724#-MHaF67W-DT0YwyOZwNb:-MHaax588TNiBWcNfP8f:b-7jaykm) (no related file):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Can we assume that you will have `npm` installed anywhere you need to check the version? I was originally thinking you might want to check the version on a minimal Ubuntu VM (build runner, etc). 
</blockquote></details>

As far as the build runners go, I think that we can define what we require to do the build.  It is the servers where the software is installed that are more resource limited.  I think that what Greg was trying to communicate was that once they deploy Kubernetes we can use that to spec out our build agents and we would not require more licenses because we have required another build agent configuration.

I asked mostly because I was trying to figure out how I would get the version number when tagging the images and I found `npm version`; it seems that it does a lot of what we want and it would be nice to use an existing tool.  I don't know if there are limitations that won't work for us - you would know better than I.  If `npm version` & `npm view thecombine version` don't fit the bill, then I would request that there is a straightforward way to lookup the version.  Since it's JSON, a simple `sed` probably won't do the trick.

All that discussion aside, I just checked the build agent that we are currently using and it has Node.js 12:
node.js	 12.16.1
node.js.npm	 6.13.4
node.js.nvm	 yes

---

**Comment by johnthagen** [comment]
*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/724#-MHaF67W-DT0YwyOZwNb:-MHaJefBCzwP-uY9bhV1:b-ne13oi) (no related file):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

As far as the build runners go, I think that we can define what we require to do the build.  It is the servers where the software is installed that are more resource limited.  I think that what Greg was trying to communicate was that once they deploy Kubernetes we can use that to spec out our build agents and we would not require more licenses because we have required another build agent configuration.

I asked mostly because I was trying to figure out how I would get the version number when tagging the images and I found `npm version`; it seems that it does a lot of what we want and it would be nice to use an existing tool.  I don't know if there are limitations that won't work for us - you would know better than I.  If `npm version` & `npm view thecombine version` don't fit the bill, then I would request that there is a straightforward way to lookup the version.  Since it's JSON, a simple `sed` probably won't do the trick.

All that discussion aside, I just checked the build agent that we are currently using and it has Node.js 12:
node.js	 12.16.1
node.js.npm	 6.13.4
node.js.nvm	 yes

</blockquote></details>

Yes, I agree it will be simpler to put the version only in `package.json` and provide a convenient CLI command (`npm run version`) that the CI can use to query for the current version of the project. This can be used to tag the Docker images when built in CI.

I've removed the Dockefile `LABEL`s. I originally was hoping there was an easy way to build the version into the image and have Docker use that when tagging, but it unfortunately doesn't look like that is something that is supported (even less so in Compose vs base Docker).

The new solution should make it easy to get the version in CI as long as the build system has npm and Node, which seems like a reasonable requirement for this project.

---

**Review by jmgrady — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r1, 1 of 2 files at r2, 2 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/724)* status: all files reviewed, 2 unresolved discussions (waiting on @jmgrady and @johnthagen)

___
*[README.md, line 242 at r6](https://reviewable.io/reviews/sillsdev/thecombine/724#-MHfmhPv2bzRt2I8JRLX:-MHfmhPv2bzRt2I8JRLY:b81p3fv) ([raw file](https://github.com/sillsdev/thecombine/blob/3862011be8f7847cbfdf32035b504163a84d4ddf/README.md#L242)):*

> > npm run --silent version

When I run this command I get:
```
sh: 1: Syntax error: "(" unexpected
```
(running in a `bash` shell on Ubuntu 18.04).

**Review by jmgrady — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/724)* status: all files reviewed, 2 unresolved discussions (waiting on @jmgrady and @johnthagen)

___
*[package.json, line 29 at r6](https://reviewable.io/reviews/sillsdev/thecombine/724#-MHfnaxF3y5vPFgz_e6p:-MHfnaxF3y5vPFgz_e6q:b6g742p) ([raw file](https://github.com/sillsdev/thecombine/blob/3862011be8f7847cbfdf32035b504163a84d4ddf/package.json#L29)):*
> ```
>    "version": "node -e console.log(require('./package.json').version);"
> ```
When I run this command I get: `sh: 1: Syntax error: "(" unexpected`
(running in a bash shell on Ubuntu 18.04).
I have moved this command to a printVersion.js and changed this line to:
```
    "version": "node printVersion.js"
```
I will commit the change for your review after I publish this comment.

**Comment by johnthagen** [comment]
___
*[package.json, line 29 at r6](https://reviewable.io/reviews/sillsdev/thecombine/724#-MHfnaxF3y5vPFgz_e6p:-MHgMp7gBk3kIwa2yhUm:bvrvwr) ([raw file](https://github.com/sillsdev/thecombine/blob/3862011be8f7847cbfdf32035b504163a84d4ddf/package.json#L29)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

> ```
>    "version": "node -e console.log(require('./package.json').version);"
> ```
When I run this command I get: `sh: 1: Syntax error: "(" unexpected`
(running in a bash shell on Ubuntu 18.04).
I have moved this command to a printVersion.js and changed this line to:
```
    "version": "node printVersion.js"
```
I will commit the change for your review after I publish this comment.
</blockquote></details>

LGTM.

We generally use TypeScript for these kinds of scripts, but given this is so incredibly simple, just a JS file seems appropriate.

**Comment by johnthagen** [comment]
___
*[README.md, line 242 at r6](https://reviewable.io/reviews/sillsdev/thecombine/724#-MHfmhPv2bzRt2I8JRLX:-MHgN8o-6IAR23sYhAei:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/3862011be8f7847cbfdf32035b504163a84d4ddf/README.md#L242)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>


> > npm run --silent version

When I run this command I get:
```
sh: 1: Syntax error: "(" unexpected
```
(running in a `bash` shell on Ubuntu 18.04).
</blockquote></details>

Done

**Comment by imnasnainaec** [comment]
Could we also add a [version badge](https://shields.io/category/version) to our Readme?

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 3 of 3 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/724)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by johnthagen** [comment]
> Could we also add a version badge to our Readme?

@imnasnainaec Done.

**Review by jmgrady — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/724#-:-MHlZTA7B90_0a4Fbos9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
