### PR TITLE
Implement SignalR as middleware for project export enhancement

### PR DESCRIPTION
**Pull request by imnasnainaec**
Follow-up to #819 

TODO:

- [x] Unhardcode URL path for signal (@johnthagen)
- [x] Ensure Docker build works (@johnthagen)
  - Need to proxy to `/hub` or, perhaps better, move `/hub` to where all other backend paths are

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/817)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[Backend/Startup.cs, line 94 at r4](https://reviewable.io/reviews/sillsdev/thecombine/817#-MMav0EV4QoFxP0_D7EF:-MMav0EV4QoFxP0_D7EG:bp360v1) ([raw file](https://github.com/sillsdev/thecombine/blob/43e6b1bf9f11712e1d86cd75dcb7f31778a2fe94/Backend/Startup.cs#L94)):*
> ```Smalltalk
>                         .AllowAnyHeader()
>                         .AllowAnyMethod()
>                         .WithOrigins("http://localhost:3000")
> ```

Will this affect production? (e.g. non-`localhost` deployment)

**Review by johnthagen — COMMENTED** [review]
> Reviewed 3 of 24 files at r2, 1 of 4 files at r3, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/817)* status: 4 of 23 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @johnthagen)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/817)* status: 3 of 26 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec, @jmgrady, and @johnthagen)

___
*[Backend/Startup.cs, line 94 at r4](https://reviewable.io/reviews/sillsdev/thecombine/817#-MMav0EV4QoFxP0_D7EF:-MMb57w1DgGRr3NpbaFJ:b-zaa81t) ([raw file](https://github.com/sillsdev/thecombine/blob/43e6b1bf9f11712e1d86cd75dcb7f31778a2fe94/Backend/Startup.cs#L94)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Will this affect production? (e.g. non-`localhost` deployment)
</blockquote></details>

Oh, probably! @jmgrady How might we generalize this properly?

**Comment by johnthagen** [comment]
___
*[Backend/Startup.cs, line 94 at r4](https://reviewable.io/reviews/sillsdev/thecombine/817#-MMav0EV4QoFxP0_D7EF:-MMb7ZY41E0sS6BOjhL_:b-gymnk5) ([raw file](https://github.com/sillsdev/thecombine/blob/43e6b1bf9f11712e1d86cd75dcb7f31778a2fe94/Backend/Startup.cs#L94)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Oh, probably! @jmgrady How might we generalize this properly?
</blockquote></details>

I'll take a look at this. We have some configuration of the backend that happens via environment variables already.

**Review by johnthagen — COMMENTED** [review]
> Reviewed 1 of 2 files at r5, 2 of 2 files at r6, 3 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/817)* status: 8 of 26 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/817)* status: 7 of 27 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @johnthagen)

___
*[Backend/Startup.cs, line 94 at r4](https://reviewable.io/reviews/sillsdev/thecombine/817#-MMav0EV4QoFxP0_D7EF:-MMbO8pP1imgNhOutPXc:b-ltt8f1) ([raw file](https://github.com/sillsdev/thecombine/blob/43e6b1bf9f11712e1d86cd75dcb7f31778a2fe94/Backend/Startup.cs#L94)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I'll take a look at this. We have some configuration of the backend that happens via environment variables already.
</blockquote></details>

I am not sure.  We used to set a baseUrl configuration option that defaulted to localhost:3000. The default configuration for the frontend is now set to:
```
window['runtimeConfig'] = {
  useConnectionBaseUrlForApi: true,
  captchaRequired: {{ config_captcha_required }},
  captchaSiteKey: "{{ config_captcha_sitekey }}"
}
```
Rather than have defaults sprinkled throughout the code, we should use the RuntimeConfig type - if an item is not specified, it will use the default.  The configuration items are `scripts.config.js` which is created when the software is installed.  The defaults should be what is needed for the development environment so that it will work if no config.js exists.

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/817)* status: 7 of 27 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @johnthagen)

___
*[Backend/Startup.cs, line 94 at r4](https://reviewable.io/reviews/sillsdev/thecombine/817#-MMav0EV4QoFxP0_D7EF:-MMbPErQAZxn_ZjMOcM7:b-7ddcrn) ([raw file](https://github.com/sillsdev/thecombine/blob/43e6b1bf9f11712e1d86cd75dcb7f31778a2fe94/Backend/Startup.cs#L94)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

I am not sure.  We used to set a baseUrl configuration option that defaulted to localhost:3000. The default configuration for the frontend is now set to:
```
window['runtimeConfig'] = {
  useConnectionBaseUrlForApi: true,
  captchaRequired: {{ config_captcha_required }},
  captchaSiteKey: "{{ config_captcha_sitekey }}"
}
```
Rather than have defaults sprinkled throughout the code, we should use the RuntimeConfig type - if an item is not specified, it will use the default.  The configuration items are `scripts.config.js` which is created when the software is installed.  The defaults should be what is needed for the development environment so that it will work if no config.js exists.
</blockquote></details>

This is what is in `./src/types/runtimeConfig.tsx`:
```
  public baseUrl(): string {
    // TODO: Remove support for previous configuration solution when
    //  Docker-based installation is used in production.
    if (window.runtimeConfig.hasOwnProperty("baseUrl")) {
      return window.runtimeConfig.baseUrl;
    }

    let baseUrl = "";
    if (window.runtimeConfig.hasOwnProperty("useConnectionBaseUrlForApi")) {
      baseUrl = `${window.location.protocol}//${window.location.host}`;
    } else {
      baseUrl = defaultConfig.baseUrl;
    }
    return baseUrl;
  }
```
Does this meet your needs?

**Comment by johnthagen** [comment]
___
*[Backend/Startup.cs, line 94 at r4](https://reviewable.io/reviews/sillsdev/thecombine/817#-MMav0EV4QoFxP0_D7EF:-MMf7jnQ-KUAwUIDBna3:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/43e6b1bf9f11712e1d86cd75dcb7f31778a2fe94/Backend/Startup.cs#L94)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

This is what is in `./src/types/runtimeConfig.tsx`:
```
  public baseUrl(): string {
    // TODO: Remove support for previous configuration solution when
    //  Docker-based installation is used in production.
    if (window.runtimeConfig.hasOwnProperty("baseUrl")) {
      return window.runtimeConfig.baseUrl;
    }

    let baseUrl = "";
    if (window.runtimeConfig.hasOwnProperty("useConnectionBaseUrlForApi")) {
      baseUrl = `${window.location.protocol}//${window.location.host}`;
    } else {
      baseUrl = defaultConfig.baseUrl;
    }
    return baseUrl;
  }
```
Does this meet your needs?
</blockquote></details>

Done

**Comment by johnthagen** [comment]
___
*[src/components/App/SignalRHub.tsx, line 49 at r17](https://reviewable.io/reviews/sillsdev/thecombine/817#-MMf91-h3moQc7wiHaYz:-MMf91-h3moQc7wiHaZ-:b-umey9s) ([raw file](https://github.com/sillsdev/thecombine/blob/25a386e4e19fa6b75cb9f436e5375dd362fda20d/src/components/App/SignalRHub.tsx#L49)):*
> ```XML
>         }
>       };
>       connection
> ```

@imnasnainaec  The export works when I test it, but I do see the following error logged to the console:

```
index.js:1 Error: Cannot start a HubConnection that is not in the 'Disconnected' state.
    at HubConnection.<anonymous> (HubConnection.ts:163)
    at step (HubConnection.ts:2)
    at Object.next (HubConnection.ts:2)
    at HubConnection.ts:2
    at new Promise (<anonymous>)
    at push../node_modules/@microsoft/signalr/dist/esm/HubConnection.js.__awaiter (HubConnection.ts:2)
    at HubConnection.startWithStateTransitions (HubConnection.ts:161)
    at HubConnection.start (HubConnection.ts:157)
    at SignalRHub.tsx:49
    at commitHookEffectListMount (react-dom.development.js:19731)
    at commitPassiveHookEffects (react-dom.development.js:19769)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at flushPassiveEffectsImpl (react-dom.development.js:22853)
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushPassiveEffects (react-dom.development.js:22820)
    at performSyncWorkOnRoot (react-dom.development.js:21737)
    at react-dom.development.js:11089
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084)
    at flushSyncCallbackQueue (react-dom.development.js:11072)
    at batchedUpdates$1 (react-dom.development.js:21862)
    at Object.notify (Subscription.js:19)
    at Subscription.notifyNestedSubs (Subscription.js:92)
    at Subscription.handleChangeWrapper (Subscription.js:97)
    at Object.dispatch (redux.js:222)
    at e (<anonymous>:1:40553)
    at Object.dispatch (index.js:11)
    at dispatch (<anonymous>:1:28545)
    at ExportProjectActions.tsx:31
    at HubConnection.method (SignalRHub.tsx:45)
    at HubConnection.ts:634
    at Array.forEach (<anonymous>)
    at HubConnection.invokeClientMethod (HubConnection.ts:634)
    at HubConnection.processIncomingData (HubConnection.ts:530)
    at WebSocketTransport.HubConnection.connection.onreceive (HubConnection.ts:102)
    at WebSocket.webSocket.onmessage (WebSocketTransport.ts:94)
console.<computed> @ index.js:1
overrideMethod @ react_devtools_backend.js:2430
(anonymous) @ SignalRHub.tsx:49
Promise.catch (async)
(anonymous) @ SignalRHub.tsx:49
commitHookEffectListMount @ react-dom.development.js:19731
commitPassiveHookEffects @ react-dom.development.js:19769
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
flushPassiveEffectsImpl @ react-dom.development.js:22853
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushPassiveEffects @ react-dom.development.js:22820
performSyncWorkOnRoot @ react-dom.development.js:21737
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
batchedUpdates$1 @ react-dom.development.js:21862
notify @ Subscription.js:19
notifyNestedSubs @ Subscription.js:92
handleChangeWrapper @ Subscription.js:97
dispatch @ redux.js:222
e @ VM347:1
(anonymous) @ index.js:11
dispatch @ VM347:1
(anonymous) @ ExportProjectActions.tsx:31
method @ SignalRHub.tsx:45
(anonymous) @ HubConnection.ts:634
HubConnection.invokeClientMethod @ HubConnection.ts:634
HubConnection.processIncomingData @ HubConnection.ts:530
HubConnection.connection.onreceive @ HubConnection.ts:102
webSocket.onmessage @ WebSocketTransport.ts:94
```

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/817)* status: 6 of 29 files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor and @johnthagen)

___
*[src/components/App/SignalRHub.tsx, line 49 at r17](https://reviewable.io/reviews/sillsdev/thecombine/817#-MMf91-h3moQc7wiHaYz:-MMqDWbF0Vhtotl8eMTW:bx5ej5n) ([raw file](https://github.com/sillsdev/thecombine/blob/25a386e4e19fa6b75cb9f436e5375dd362fda20d/src/components/App/SignalRHub.tsx#L49)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

@imnasnainaec  The export works when I test it, but I do see the following error logged to the console:

```
index.js:1 Error: Cannot start a HubConnection that is not in the 'Disconnected' state.
    at HubConnection.<anonymous> (HubConnection.ts:163)
    at step (HubConnection.ts:2)
    at Object.next (HubConnection.ts:2)
    at HubConnection.ts:2
    at new Promise (<anonymous>)
    at push../node_modules/@microsoft/signalr/dist/esm/HubConnection.js.__awaiter (HubConnection.ts:2)
    at HubConnection.startWithStateTransitions (HubConnection.ts:161)
    at HubConnection.start (HubConnection.ts:157)
    at SignalRHub.tsx:49
    at commitHookEffectListMount (react-dom.development.js:19731)
    at commitPassiveHookEffects (react-dom.development.js:19769)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at flushPassiveEffectsImpl (react-dom.development.js:22853)
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushPassiveEffects (react-dom.development.js:22820)
    at performSyncWorkOnRoot (react-dom.development.js:21737)
    at react-dom.development.js:11089
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084)
    at flushSyncCallbackQueue (react-dom.development.js:11072)
    at batchedUpdates$1 (react-dom.development.js:21862)
    at Object.notify (Subscription.js:19)
    at Subscription.notifyNestedSubs (Subscription.js:92)
    at Subscription.handleChangeWrapper (Subscription.js:97)
    at Object.dispatch (redux.js:222)
    at e (<anonymous>:1:40553)
    at Object.dispatch (index.js:11)
    at dispatch (<anonymous>:1:28545)
    at ExportProjectActions.tsx:31
    at HubConnection.method (SignalRHub.tsx:45)
    at HubConnection.ts:634
    at Array.forEach (<anonymous>)
    at HubConnection.invokeClientMethod (HubConnection.ts:634)
    at HubConnection.processIncomingData (HubConnection.ts:530)
    at WebSocketTransport.HubConnection.connection.onreceive (HubConnection.ts:102)
    at WebSocket.webSocket.onmessage (WebSocketTransport.ts:94)
console.<computed> @ index.js:1
overrideMethod @ react_devtools_backend.js:2430
(anonymous) @ SignalRHub.tsx:49
Promise.catch (async)
(anonymous) @ SignalRHub.tsx:49
commitHookEffectListMount @ react-dom.development.js:19731
commitPassiveHookEffects @ react-dom.development.js:19769
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
flushPassiveEffectsImpl @ react-dom.development.js:22853
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushPassiveEffects @ react-dom.development.js:22820
performSyncWorkOnRoot @ react-dom.development.js:21737
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
batchedUpdates$1 @ react-dom.development.js:21862
notify @ Subscription.js:19
notifyNestedSubs @ Subscription.js:92
handleChangeWrapper @ Subscription.js:97
dispatch @ redux.js:222
e @ VM347:1
(anonymous) @ index.js:11
dispatch @ VM347:1
(anonymous) @ ExportProjectActions.tsx:31
method @ SignalRHub.tsx:45
(anonymous) @ HubConnection.ts:634
HubConnection.invokeClientMethod @ HubConnection.ts:634
HubConnection.processIncomingData @ HubConnection.ts:530
HubConnection.connection.onreceive @ HubConnection.ts:102
webSocket.onmessage @ WebSocketTransport.ts:94
```
</blockquote></details>

I believe that's resolved now.

**Comment by jasonleenaylor** [comment]
___
*[Backend/Controllers/LiftController.cs, line 241 at r19](https://reviewable.io/reviews/sillsdev/thecombine/817#-MMqMBcf8c872SYvyQSW:-MMqMBcf8c872SYvyQSX:b-i0275v) ([raw file](https://github.com/sillsdev/thecombine/blob/b3903e50934b8b5bc292a7fcff06cb19f516bc59/Backend/Controllers/LiftController.cs#L241)):*
> ```Smalltalk
>                 return new OkObjectResult(projectId);
>             }
>             catch
> ```

Better to catch(Exception e) and throw e;

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/817)* status: 6 of 29 files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor and @johnthagen)

___
*[Backend/Controllers/LiftController.cs, line 241 at r19](https://reviewable.io/reviews/sillsdev/thecombine/817#-MMqMBcf8c872SYvyQSW:-MMr4mCx3o56W629erfd:bzb4y9s) ([raw file](https://github.com/sillsdev/thecombine/blob/b3903e50934b8b5bc292a7fcff06cb19f516bc59/Backend/Controllers/LiftController.cs#L241)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Better to catch(Exception e) and throw e;
</blockquote></details>

That's what I'd done at first, but LGTM said it's bad practice, breaking call-stacks, and suggested this format. I assumed this way implicitly threw the error it caught.

**Comment by jasonleenaylor** [comment]
___
*[Backend/Controllers/LiftController.cs, line 241 at r19](https://reviewable.io/reviews/sillsdev/thecombine/817#-MMqMBcf8c872SYvyQSW:-MMrC2Iy8bh_PCSh8V2l:b-yzdust) ([raw file](https://github.com/sillsdev/thecombine/blob/b3903e50934b8b5bc292a7fcff06cb19f516bc59/Backend/Controllers/LiftController.cs#L241)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

That's what I'd done at first, but LGTM said it's bad practice, breaking call-stacks, and suggested this format. I assumed this way implicitly threw the error it caught.
</blockquote></details>

So it does...lgtm taught me something new today.

**Comment by jasonleenaylor** [comment]
___
*[Backend/Services/LiftApiServices.cs, line 92 at r19](https://reviewable.io/reviews/sillsdev/thecombine/817#-MMqMY_93Myu_Xovlpfq:-MMqMY_A85Hi894ksu2e:b-8wpwwg) ([raw file](https://github.com/sillsdev/thecombine/blob/b3903e50934b8b5bc292a7fcff06cb19f516bc59/Backend/Services/LiftApiServices.cs#L92)):*
> ```
>  private readonly string inProgress = "IN_PROGRESS";
> ```

For style purposes make this a const and move it to the top of the file. Unless LGTM doesn't like that either. ;)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/817)* status: 6 of 29 files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor and @johnthagen)

___
*[Backend/Services/LiftApiServices.cs, line 92 at r19](https://reviewable.io/reviews/sillsdev/thecombine/817#-MMqMY_93Myu_Xovlpfq:-MMrGRG-7_Wz9ULtmtYa:b-m7ofq7) ([raw file](https://github.com/sillsdev/thecombine/blob/b3903e50934b8b5bc292a7fcff06cb19f516bc59/Backend/Services/LiftApiServices.cs#L92)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
>  private readonly string inProgress = "IN_PROGRESS";
> ```

For style purposes make this a const and move it to the top of the file. Unless LGTM doesn't like that either. ;)
</blockquote></details>

Moved to top of class.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 9 of 24 files at r2, 1 of 4 files at r4, 1 of 6 files at r14, 1 of 2 files at r15, 1 of 3 files at r16, 1 of 3 files at r17, 7 of 9 files at r18, 2 of 2 files at r19, 1 of 1 files at r20.
> Dismissed @johnthagen from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/817)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/components/ProjectExport/ExportProjectButton.tsx, line 16 at r20](https://reviewable.io/reviews/sillsdev/thecombine/817#-MMrPAxR4NLsp6ZOb8J3:-MMrPAxS5JUjZ707P6y_:blik53) ([raw file](https://github.com/sillsdev/thecombine/blob/c69e151c42a380b0d9e493afe46038c29a7fa0fb/src/components/ProjectExport/ExportProjectButton.tsx#L16)):*
> ```
>  utto
> ```
Colony collapse disorder must be affecting your code comments.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 11 of 24 files at r2, 1 of 4 files at r4, 2 of 2 files at r6, 2 of 4 files at r7, 1 of 6 files at r14, 1 of 2 files at r15, 1 of 3 files at r16, 1 of 3 files at r17, 5 of 9 files at r18, 2 of 2 files at r19, 1 of 1 files at r20, 1 of 1 files at r21.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/817)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 2 of 2 files at r22.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/817)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
