### PR TITLE
Refactor frontend container

### LINKED ISSUE #696: Frontend Docker container can get stuck restarting repeatedly
When the combine is deployed as docker containers, sometimes the _frontend_ container will restart continually when some or all of the containers are updated with newer software.  It is unknown if the condition will resolve itself with time.  The _frontend_ container is based off of `staticfloat/nginx-certbot` and probably has to do with nginx not starting if its certificates are not available.

### PR DESCRIPTION
**Pull request by jmgrady**
Split frontend container into two - one for the frontend running Nginx as a reverse proxy and one for a certificate manager.

Closes #696

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/759)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[Dockerfile, line 14 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmn95s8GJ6q9fObKBP:-MJmn95s8GJ6q9fObKBQ:bfu24x) ([raw file](https://github.com/sillsdev/thecombine/blob/7479fa8784de5bb307e636225b11377be802c814/Dockerfile#L14)):*
> ```Dockerfile
> 
> # Production environment.
> FROM nginx:1.18
> ```

Any reason not to use the latest, `1.19.3`?

**Comment by johnthagen** [comment]
___
*[certmgr/scripts/README.md, line 1 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmnw5G444rJrSmAKUN:-MJmnw5HDXh6YhZTSvQX:bnfiqjz) ([raw file](https://github.com/sillsdev/thecombine/blob/7479fa8784de5bb307e636225b11377be802c814/certmgr/scripts/README.md#L1)):*
> ```Markdown
> # Design notes for the certbot container for TheCombine
> ```

Should this README be moved up one directory rather than being in the `scripts` folder?

**Comment by johnthagen** [comment]
___
*[certmgr/scripts/func.sh, line 1 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmqOv9Bbt1kd2wjm_W:-MJmqOv9Bbt1kd2wjm_X:b-q5fage) ([raw file](https://github.com/sillsdev/thecombine/blob/7479fa8784de5bb307e636225b11377be802c814/certmgr/scripts/func.sh#L1)):*
> ```Shell
> #! /bin/bash
> ```

I know this would be a bit of work at this point, but for the amount of logic involved in these scripts, I personally think using a full programming language like Python would make this a lot more maintainable. `bash` starts to scale poorly at this size in my opinion.

This would also have the added benefit that `certbot` image already comes with Python 3.8 and we wouldn't need to install `bash` and `curl` at all.

With Python, we can also apply more software engineering tooling to this code (linting, type checking, formatting, etc).

**Comment by johnthagen** [comment]
___
*[certmgr/scripts/entrypoint.sh, line 20 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmr0YcAOWit09EC3iz:-MJmr0YcAOWit09EC3j-:bt2vksq) ([raw file](https://github.com/sillsdev/thecombine/blob/7479fa8784de5bb307e636225b11377be802c814/certmgr/scripts/entrypoint.sh#L20)):*
> ```Shell
> esac
> 
> exit 99
> ```

Is there significance to using 99 as an exit code here?

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 2 of 15 files at r1, 3 of 19 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/759)* status: 5 of 24 files reviewed, 4 unresolved discussions (waiting on @imnasnainaec, @jmgrady, and @johnthagen)

___
*[.gitignore, line 19 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmphWZ56Tz3Q7Fa0TG:-MJmphW_AVJ6QxNOR_Zx:b53qzmq) ([raw file](https://github.com/sillsdev/thecombine/blob/7479fa8784de5bb307e636225b11377be802c814/.gitignore#L19)):*
> ```
> .env.backend
> .env.frontend
> .env.certmgr
> ```
Is `.env.*` too general to use?
___
*[scripts/docker_setup.py, line 113 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmrIjf5hFaneUt6iwt:-MJmrIjf5hFaneUt6iwu:b-lw718) ([raw file](https://github.com/sillsdev/thecombine/blob/7479fa8784de5bb307e636225b11377be802c814/scripts/docker_setup.py#L113)):*
> ```Python
>             env_var["value"] = os.environ[env_var["key"]]
> 
>     # Set backend common env_vars if they are defined for our process
> ```

This comment could use updating from "common" to "backend"
___
*[scripts/docker_setup.py, line 116 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmqq2rBWlTn3VZHF19:-MJmqq2rBWlTn3VZHF1A:b-gudna3) ([raw file](https://github.com/sillsdev/thecombine/blob/7479fa8784de5bb307e636225b11377be802c814/scripts/docker_setup.py#L116)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>     # Set backend private env_vars if they are defined for our process
>     for env_var in dev_config["combine_private_env_vars"]:
>         if env_var["key"] in os.environ:
>             env_var["value"] = os.environ[env_var["key"]]
>     # Set backend common env_vars if they are defined for our process
>     for env_var in dev_config["combine_backend_env_vars"]:
>         if env_var["key"] in os.environ:
>             env_var["value"] = os.environ[env_var["key"]]
> ```
</details>

Only `_private_` and `_backend_` are set here, but not `_frontend_` or `_cert_`... just making sure that is as it should be.

**Comment by johnthagen** [comment]
___
*[certmgr/scripts/README.md, line 31 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmriUt-sX7C5TYi8Re:-MJmriUt-sX7C5TYi8Rf:bq1vz2m) ([raw file](https://github.com/sillsdev/thecombine/blob/7479fa8784de5bb307e636225b11377be802c814/certmgr/scripts/README.md#L31)):*
> ```Markdown
> | ----------------- | ----------------------------------------------------------------------------------------------------------------------------------------------- |
> | CERT_MODE         | May be one of `self-signed`, `letsencrypt`, `cert-server`, or `cert-client` to specify which of the certificate management personalities to use |
> | CERT_EMAIL        | Set to 1 to remove old certificates first                                                                                                       |
> ```

I assume this is specified by `certbot` but the description/effect was surprisingly for `CERT_EMAIL`

**Comment by johnthagen** [comment]
___
*[certmgr/scripts/README.md, line 74 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmsMpIBx-nZD1TKHbM:-MJmsMpIBx-nZD1TKHbN:b-l47p6q) ([raw file](https://github.com/sillsdev/thecombine/blob/7479fa8784de5bb307e636225b11377be802c814/certmgr/scripts/README.md#L74)):*
> ```Markdown
> When installing TheCombine for using self-signed certificates, e.g. for the QA server
> or for development use, the following steps are required:
>   1. Build each container:
> ```

Does this mean to build them independently rather than with Docker Compose (`docker-compose build --parallel`)?

**Comment by johnthagen** [comment]
___
*[certmgr/scripts/README.md, line 40 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJms_kL0GmleAFbfNoe:-MJms_kL0GmleAFbfNof:b637wrm) ([raw file](https://github.com/sillsdev/thecombine/blob/7479fa8784de5bb307e636225b11377be802c814/certmgr/scripts/README.md#L40)):*
> ```Markdown
> ### selfsigned.sh
> `selfsigned.sh` implements the certmgr behavior when `CERT_MODE` is set to `self-signed`.
> It creates a self-signed certificate to be used by the nginx web server and enters a loop to periodically check to see if the certificate needs to be renewed/recreated.  The certificate is valid for 10 years and will be renewed when there are less than 10 days until is expires.
> ```

Not a huge deal,  but it would be easier to read this file side by side other files if the contents were wrapped to 120 characters.

**Comment by johnthagen** [comment]
___
*[.gitignore, line 19 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmphWZ56Tz3Q7Fa0TG:-MJmsnq7EJLtOnPefSlh:bjial4d) ([raw file](https://github.com/sillsdev/thecombine/blob/7479fa8784de5bb307e636225b11377be802c814/.gitignore#L19)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> .env.backend
> .env.frontend
> .env.certmgr
> ```
Is `.env.*` too general to use?
</blockquote></details>

That could work? I know we want to keep `.env` for React, but it think you're suggestion could work.

**Comment by johnthagen** [comment]
___
*[docker_deploy/group_vars/server/main.yml, line 20 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmt4_YDAa1hLmHDqlC:-MJmt4_YDAa1hLmHDqlD:bkw3rhj) ([raw file](https://github.com/sillsdev/thecombine/blob/7479fa8784de5bb307e636225b11377be802c814/docker_deploy/group_vars/server/main.yml#L20)):*
> ```YAML
> # SSL cert variables specific to Server targets
> cert_mode: "letsencrypt"
> cert_email: "jimgrady.jg@gmail.com"
> ```

Do we want your personal email committed into the repo?

**Comment by johnthagen** [comment]
___
*[certmgr/scripts/selfsigned.sh, line 18 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmv0N3CWrjHoNHLIsk:-MJmv0N3CWrjHoNHLIsl:b-o8tg0y) ([raw file](https://github.com/sillsdev/thecombine/blob/7479fa8784de5bb307e636225b11377be802c814/certmgr/scripts/selfsigned.sh#L18)):*
> ```Shell
> while true; do
>   renew_selfsigned_cert
>   sleep 60 &
> ```

I think we could slow this down. Self-signed certs are mostly going to be used for development, but checking this often leaves a good amount of logs in `docker-compose logs -f`. Perhaps we could slow this down to 1 day?

**Review by imnasnainaec — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/759)* status: 5 of 24 files reviewed, 9 unresolved discussions (waiting on @jmgrady and @johnthagen)

**Review by johnthagen — CHANGES_REQUESTED** [review]
> Reviewed 3 of 15 files at r1, 17 of 19 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/759)* status: all files reviewed, 9 unresolved discussions (waiting on @jmgrady)

___
*[certmgr/scripts/README.md, line 40 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJms_kL0GmleAFbfNoe:-MJmu_5SEceho4zKSmN5:be7jlpw) ([raw file](https://github.com/sillsdev/thecombine/blob/7479fa8784de5bb307e636225b11377be802c814/certmgr/scripts/README.md#L40)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Not a huge deal,  but it would be easier to read this file side by side other files if the contents were wrapped to 120 characters.
</blockquote></details>

As for the 10 years part, don't browsers only accept certificates that are valid for 1 year now? Perhaps we should reduce the validity of the cert life to make it match typical certs, especially if we are going to auto-renew.

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/759)* status: all files reviewed, 9 unresolved discussions (waiting on @johnthagen)

___
*[.gitignore, line 19 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmphWZ56Tz3Q7Fa0TG:-MJmsflk7jjfeLWQ1h6V:b-xelgx8) ([raw file](https://github.com/sillsdev/thecombine/blob/ee1a3cfcff1486fc2c07043aa1b942626722a342/.gitignore#L19)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

That could work? I know we want to keep `.env` for React, but it think you're suggestion could work.
</blockquote></details>

I thought that is the usual pattern for docker-compose.  c.f. https://docs.docker.com/compose/environment-variables/
Let me know if you prefer a different naming convention.
___
*[Dockerfile, line 14 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmn95s8GJ6q9fObKBP:-MJmsugQDvjAKPv52ppY:bu4n7oj) ([raw file](https://github.com/sillsdev/thecombine/blob/ee1a3cfcff1486fc2c07043aa1b942626722a342/Dockerfile#L14)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Any reason not to use the latest, `1.19.3`?
</blockquote></details>

1.18 is listed as the stable version on https://hub.docker.com/_/nginx
___
*[certmgr/scripts/entrypoint.sh, line 20 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmr0YcAOWit09EC3iz:-MJmt5jw8C72TMbqkw09:b-66o0lm) ([raw file](https://github.com/sillsdev/thecombine/blob/ee1a3cfcff1486fc2c07043aa1b942626722a342/certmgr/scripts/entrypoint.sh#L20)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Is there significance to using 99 as an exit code here?
</blockquote></details>

None at all but it should never get here so I wanted an obvious indication of that (at least to me).
___
*[certmgr/scripts/func.sh, line 1 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmqOv9Bbt1kd2wjm_W:-MJmtZGbEc-bkdmxm71G:blbmq86) ([raw file](https://github.com/sillsdev/thecombine/blob/ee1a3cfcff1486fc2c07043aa1b942626722a342/certmgr/scripts/func.sh#L1)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I know this would be a bit of work at this point, but for the amount of logic involved in these scripts, I personally think using a full programming language like Python would make this a lot more maintainable. `bash` starts to scale poorly at this size in my opinion.

This would also have the added benefit that `certbot` image already comes with Python 3.8 and we wouldn't need to install `bash` and `curl` at all.

With Python, we can also apply more software engineering tooling to this code (linting, type checking, formatting, etc).
</blockquote></details>

Perhaps but I don't think that the logic is very complex.  In addition, Python would require running simple commands to be replaced by more cumbersome subprocess calls.
___
*[certmgr/scripts/README.md, line 1 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmnw5G444rJrSmAKUN:-MJmvXuk7ncXUw3ZBDkb:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/ee1a3cfcff1486fc2c07043aa1b942626722a342/certmgr/scripts/README.md#L1)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Should this README be moved up one directory rather than being in the `scripts` folder?
</blockquote></details>

Done.
___
*[certmgr/scripts/README.md, line 31 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmriUt-sX7C5TYi8Re:-MJmvbTW7a2CodGobDLp:b-hhl4w0) ([raw file](https://github.com/sillsdev/thecombine/blob/ee1a3cfcff1486fc2c07043aa1b942626722a342/certmgr/scripts/README.md#L31)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I assume this is specified by `certbot` but the description/effect was surprisingly for `CERT_EMAIL`
</blockquote></details>

No.  I was rearranging the table and missed that.  Done.
___
*[certmgr/scripts/README.md, line 40 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJms_kL0GmleAFbfNoe:-MJmw8JMAVfUyb8dXWF0:b-n9u8wb) ([raw file](https://github.com/sillsdev/thecombine/blob/ee1a3cfcff1486fc2c07043aa1b942626722a342/certmgr/scripts/README.md#L40)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

As for the 10 years part, don't browsers only accept certificates that are valid for 1 year now? Perhaps we should reduce the validity of the cert life to make it match typical certs, especially if we are going to auto-renew.
</blockquote></details>

Looks fine in Atom. ;-)  
Done - except for the table - Markdown table specs make it difficult to do that and keep the table. (at least with my knowledge)

Browsers don't accept self-signed certs anyway.  You have to override it to get to the website.
___
*[certmgr/scripts/README.md, line 74 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmsMpIBx-nZD1TKHbM:-MJmxgrA6vUJ3CBL4JQn:b-nq5xxv) ([raw file](https://github.com/sillsdev/thecombine/blob/ee1a3cfcff1486fc2c07043aa1b942626722a342/certmgr/scripts/README.md#L74)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Does this mean to build them independently rather than with Docker Compose (`docker-compose build --parallel`)?
</blockquote></details>

Yes because they are not built on the targets.  But perhaps I'm making a bad assumption.  I suppose I can build them on the TeamCity server using docker-compose and then push them to AWS ECR without trying to run them on the build agent.
___
*[certmgr/scripts/selfsigned.sh, line 18 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmv0N3CWrjHoNHLIsk:-MJmyHNS6le8Ip8PxYKC:bynzyer) ([raw file](https://github.com/sillsdev/thecombine/blob/ee1a3cfcff1486fc2c07043aa1b942626722a342/certmgr/scripts/selfsigned.sh#L18)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I think we could slow this down. Self-signed certs are mostly going to be used for development, but checking this often leaves a good amount of logs in `docker-compose logs -f`. Perhaps we could slow this down to 1 day?
</blockquote></details>

Done.

Note that nothing gets logged unless you set verbose to 1 or the certificate gets renewed (10 years from now).
___
*[docker_deploy/group_vars/server/main.yml, line 20 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmt4_YDAa1hLmHDqlC:-MJmynid0pfzeU9QL3hT:b-rondv9) ([raw file](https://github.com/sillsdev/thecombine/blob/ee1a3cfcff1486fc2c07043aa1b942626722a342/docker_deploy/group_vars/server/main.yml#L20)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Do we want your personal email committed into the repo?
</blockquote></details>

I really want an SIL email.  I will move it to the vault.
___
*[scripts/docker_setup.py, line 113 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmrIjf5hFaneUt6iwt:-MJmzexX5FZh87LlMPxp:b3jfw9u) ([raw file](https://github.com/sillsdev/thecombine/blob/ee1a3cfcff1486fc2c07043aa1b942626722a342/scripts/docker_setup.py#L113)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

This comment could use updating from "common" to "backend"
</blockquote></details>

There are two types of environment variables for the backend.  "Common" which are defined in vars/common_config.yml, and "private" which are defined in the encrypted vars/vault_config.yml file.  At least that is the intent.  Currently there are no common variables defined for the backend.
___
*[scripts/docker_setup.py, line 116 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmqq2rBWlTn3VZHF19:-MJn-wf14-i--wZxUZEe:b-hutlz9) ([raw file](https://github.com/sillsdev/thecombine/blob/ee1a3cfcff1486fc2c07043aa1b942626722a342/scripts/docker_setup.py#L116)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>     # Set backend private env_vars if they are defined for our process
>     for env_var in dev_config["combine_private_env_vars"]:
>         if env_var["key"] in os.environ:
>             env_var["value"] = os.environ[env_var["key"]]
>     # Set backend common env_vars if they are defined for our process
>     for env_var in dev_config["combine_backend_env_vars"]:
>         if env_var["key"] in os.environ:
>             env_var["value"] = os.environ[env_var["key"]]
> ```
Only `_private_` and `_backend_` are set here, but not `_frontend_` or `_cert_`... just making sure that is as it should be.
</blockquote></details>

This is correct.  What this is doing is looking up the values in your environment variables if they are defined.  For the backend, most of these environment variable values are secrets that we don't want to put into the Python script.  Most developers will have these environment variables defined so that `npm start` will work.  This saves you from having to manually edit the environment variable file manually to add the secrets.

**Comment by johnthagen** [comment]
___
*[.gitignore, line 19 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmphWZ56Tz3Q7Fa0TG:-MJn2BY2BQNpISsk9d2P:b-j2m54p) ([raw file](https://github.com/sillsdev/thecombine/blob/ee1a3cfcff1486fc2c07043aa1b942626722a342/.gitignore#L19)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

I thought that is the usual pattern for docker-compose.  c.f. https://docs.docker.com/compose/environment-variables/
Let me know if you prefer a different naming convention.
</blockquote></details>

I think @imnasnainaec  was saying that perhaps we could generalize the .gitignore lines into one, but not change the actual file names.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/759)* status: 21 of 25 files reviewed, 9 unresolved discussions (waiting on @jmgrady and @johnthagen)

___
*[.gitignore, line 19 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmphWZ56Tz3Q7Fa0TG:-MJn2Sds9_G_pKehPSAN:bo6apac) ([raw file](https://github.com/sillsdev/thecombine/blob/ee1a3cfcff1486fc2c07043aa1b942626722a342/.gitignore#L19)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I think @imnasnainaec  was saying that perhaps we could generalize the .gitignore lines into one, but not change the actual file names.
</blockquote></details>

Indeed.

**Comment by johnthagen** [comment]
___
*[Dockerfile, line 14 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmn95s8GJ6q9fObKBP:-MJn2OmM7BIjl91FZ7v0:b-94b0pe) ([raw file](https://github.com/sillsdev/thecombine/blob/ee1a3cfcff1486fc2c07043aa1b942626722a342/Dockerfile#L14)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

1.18 is listed as the stable version on https://hub.docker.com/_/nginx
</blockquote></details>

Huh, I hadn't noticed that before. According to this post, mainline is recommended though? https://serverfault.com/a/715126

**Comment by johnthagen** [comment]
___
*[certmgr/scripts/README.md, line 74 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmsMpIBx-nZD1TKHbM:-MJn2sIm-kNVGBIZrEma:b-kimsik) ([raw file](https://github.com/sillsdev/thecombine/blob/ee1a3cfcff1486fc2c07043aa1b942626722a342/certmgr/scripts/README.md#L74)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Yes because they are not built on the targets.  But perhaps I'm making a bad assumption.  I suppose I can build them on the TeamCity server using docker-compose and then push them to AWS ECR without trying to run them on the build agent.
</blockquote></details>

Yeah, seems like it would be safest to build them using compose just so that we are consistently using that same configuration as much as we can.

**Comment by johnthagen** [comment]
___
*[certmgr/scripts/entrypoint.sh, line 20 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmr0YcAOWit09EC3iz:-MJn30uuAQbeCNPztEZZ:bvdbbum) ([raw file](https://github.com/sillsdev/thecombine/blob/ee1a3cfcff1486fc2c07043aa1b942626722a342/certmgr/scripts/entrypoint.sh#L20)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

None at all but it should never get here so I wanted an obvious indication of that (at least to me).
</blockquote></details>

Could we add a comment stating that it should never reach this point?

**Comment by johnthagen** [comment]
___
*[certmgr/scripts/func.sh, line 1 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmqOv9Bbt1kd2wjm_W:-MJn3P5E7WXmaHbKa7lE:b-jggz8s) ([raw file](https://github.com/sillsdev/thecombine/blob/ee1a3cfcff1486fc2c07043aa1b942626722a342/certmgr/scripts/func.sh#L1)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Perhaps but I don't think that the logic is very complex.  In addition, Python would require running simple commands to be replaced by more cumbersome subprocess calls.
</blockquote></details>

To really streamline, you can use `os.system("command")` to do the equivalent of bash and not do any checking/piping of values.

**Review by johnthagen — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/759)* status: all files reviewed, 2 unresolved discussions (waiting on @jmgrady)

**Comment by johnthagen** [comment]
___
*[Dockerfile, line 14 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmn95s8GJ6q9fObKBP:-MJn6-ep8JapIo3O0PaY:b-5jn0d5) ([raw file](https://github.com/sillsdev/thecombine/blob/ee1a3cfcff1486fc2c07043aa1b942626722a342/Dockerfile#L14)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Huh, I hadn't noticed that before. According to this post, mainline is recommended though? https://serverfault.com/a/715126
</blockquote></details>

Here they recommend mainline in general: https://www.nginx.com/blog/nginx-1-6-1-7-released/#Which-Version-Should-I-Use

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/759)* status: all files reviewed, 2 unresolved discussions (waiting on @johnthagen)

___
*[.gitignore, line 19 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmphWZ56Tz3Q7Fa0TG:-MJn6s-02VKZmc3RyAMb:byb7qgf) ([raw file](https://github.com/sillsdev/thecombine/blob/ee1a3cfcff1486fc2c07043aa1b942626722a342/.gitignore#L19)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Indeed.
</blockquote></details>

Sorry.  I was being a little dense.  So, I would specify .env.* so that .env can be kept for React, correct?
___
*[Dockerfile, line 14 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmn95s8GJ6q9fObKBP:-MJn7A1NCtMPMhlQsnh9:b-yilija) ([raw file](https://github.com/sillsdev/thecombine/blob/ee1a3cfcff1486fc2c07043aa1b942626722a342/Dockerfile#L14)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Here they recommend mainline in general: https://www.nginx.com/blog/nginx-1-6-1-7-released/#Which-Version-Should-I-Use
</blockquote></details>

OK.  That works for me.  I can specify 1.19 and get the latest of 1.19.x, correct?
___
*[certmgr/scripts/entrypoint.sh, line 20 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmr0YcAOWit09EC3iz:-MJn7uaXBGZJezVfGvDU:b-4wijdt) ([raw file](https://github.com/sillsdev/thecombine/blob/ee1a3cfcff1486fc2c07043aa1b942626722a342/certmgr/scripts/entrypoint.sh#L20)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Could we add a comment stating that it should never reach this point?
</blockquote></details>

Actually, it will get there if you specify a mode that is not implemented yet or does not exist.  I can pick a different return code if you prefer.
___
*[certmgr/scripts/README.md, line 74 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmsMpIBx-nZD1TKHbM:-MJn7PDODOYTer0vWuNZ:b1z443r) ([raw file](https://github.com/sillsdev/thecombine/blob/ee1a3cfcff1486fc2c07043aa1b942626722a342/certmgr/scripts/README.md#L74)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Yeah, seems like it would be safest to build them using compose just so that we are consistently using that same configuration as much as we can.
</blockquote></details>

The other problem is that the docker-compose.yml is not installed on the build agents.  The docker-compose.yml should not influence the build of the container - it should just use the Dockerfile.

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/759)* status: 23 of 25 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @johnthagen)

___
*[Dockerfile, line 14 at r2](https://reviewable.io/reviews/sillsdev/thecombine/759#-MJmn95s8GJ6q9fObKBP:-MJnRJe12dNLpCjTKzw7:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/ee1a3cfcff1486fc2c07043aa1b942626722a342/Dockerfile#L14)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

OK.  That works for me.  I can specify 1.19 and get the latest of 1.19.x, correct?
</blockquote></details>

Done

**Review by johnthagen — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/759)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
