### PR TITLE
[CharInv] Refactor components

### PR DESCRIPTION
**Pull request by imnasnainaec**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2167)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2167)* status: all files reviewed, 2 unresolved discussions (waiting on @imnasnainaec)

___
*[`src/goals/CharInventoryCreation/components/CharacterDetail/CharacterInfo.tsx` line 23 at r1](https://reviewable.io/reviews/sillsdev/TheCombine/2167#-NVeL_OI6D_KKOtHIaIn:-NVeL_OI6D_KKOtHIaIo:b-i0cj0z) ([raw file](https://github.com/sillsdev/TheCombine/blob/42cbb267ac6f89fa320199b20753e92ca80114e0/src/goals/CharInventoryCreation/components/CharacterDetail/CharacterInfo.tsx#L23)):*
> ```XML
>       <Typography variant="body1">{charToHexValue(props.character)}</Typography>
>       <Typography variant="body1">
>         {t("charInventory.characterSet.charDetails")}
> ```

Was the details label dropped on purpose?
___
*[`src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx` line 53 at r1](https://reviewable.io/reviews/sillsdev/TheCombine/2167#-NVeMPTvAaLSBiyzLjxd:-NVeMPTvAaLSBiyzLjxe:b-kbkllc) ([raw file](https://github.com/sillsdev/TheCombine/blob/0ac2756d9196add7fca1a0afdba2388f88312678/src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx#L53)):*
> ```XML
>           <Trans i18nKey="charInventory.characterSet.replaceAllWith">
>             FillerText<strong>{{ val: props.dialogReplaceValue }}</strong>
>           </Trans>
> ```

Why did you prefer this?



_Code quote:_
```XML
          <Trans i18nKey="charInventory.characterSet.replaceAll">
            FillerText<strong>{{ val: props.dialogFindValue }}</strong>
          </Trans>
          <br />
          <Trans i18nKey="charInventory.characterSet.replaceAllWith">
            FillerText<strong>{{ val: props.dialogReplaceValue }}</strong>
          </Trans>
```

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2167)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[`src/goals/CharInventoryCreation/components/CharacterDetail/CharacterInfo.tsx` line 23 at r1](https://reviewable.io/reviews/sillsdev/TheCombine/2167#-NVeL_OI6D_KKOtHIaIn:-NVj5BHNElutoKkXdTT5:b-h8y3av) ([raw file](https://github.com/sillsdev/TheCombine/blob/42cbb267ac6f89fa320199b20753e92ca80114e0/src/goals/CharInventoryCreation/components/CharacterDetail/CharacterInfo.tsx#L23)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Was the details label dropped on purpose?
</blockquote></details>

Yes, as it was just a parenthetical statement that character details haven't been implemented, but there's no other indication in the ui that character details would be expected there.
___
*[`src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx` line 53 at r1](https://reviewable.io/reviews/sillsdev/TheCombine/2167#-NVeMPTvAaLSBiyzLjxd:-NVj5Vx_47udYCAdKhUh:brphx14) ([raw file](https://github.com/sillsdev/TheCombine/blob/0ac2756d9196add7fca1a0afdba2388f88312678/src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx#L53)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Why did you prefer this?
</blockquote></details>

Making it a formatted string allows rtl variants. Using `Trans` allows the formatting within the translated string.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2167)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 19 of 22 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2167)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
