### PR TITLE
Port backend to .NET Core 3.1

### LINKED ISSUE #323: Port to .NET Core 3.1
Port to the latest LTS version of .NET Core.

### PR DESCRIPTION
**Pull request by johnthagen**
Closes #323

- Bump to C# 8.0 ([expected default for .NET Core 2.1 and 3.1](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version))

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/324)

### CODE REVIEW

**Comment by johnthagen** [comment]
Can log in, but when trying to create a project:

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 OPTIONS https://localhost:5001/v1/projects/
info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
      CORS policy execution successful.
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 0.8141ms 204
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 POST https://localhost:5001/v1/projects/ application/json;charset=UTF-8 253
info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
      CORS policy execution successful.
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
      Successfully validated the token.
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'BackendFramework.Controllers.ProjectController.Post (BackendFramework)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "Post", controller = "Project"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Post(BackendFramework.Models.Project) on controll
er BackendFramework.Controllers.ProjectController (BackendFramework).
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action BackendFramework.Controllers.ProjectController.Post (BackendFramework) in 2.0843ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'BackendFramework.Controllers.ProjectController.Post (BackendFramework)'
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.ArgumentNullException: Value cannot be null. (Parameter 'document')
   at MongoDB.Driver.Core.Misc.Ensure.IsNotNull[T](T value, String paramName)
   at MongoDB.Driver.MongoCollectionBase`1.InsertOneAsync(TDocument document, InsertOneOptions options, Func`3 bulkWriteAsync)
   at BackendFramework.Services.ProjectService.Create(Project project) in C:\Users\User\GitHub\TheCombine\Backend\Services\ProjectApiServices.cs:line 50
   at BackendFramework.Controllers.ProjectController.Post(Project project) in C:\Users\User\GitHub\TheCombine\Backend\Controllers\ProjectController.cs:line 105
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 5.0551ms 500 text/plain
```

**Comment by johnthagen** [comment]
In this method:

https://github.com/sillsdev/TheCombine/blob/0152bf13debda34b7b89a4c24402ce451444f81d/Backend/Controllers/ProjectController.cs#L103

`project` is being passed in as `null`. I suspect something with the `Startup` configuration is not correct.

**Comment by johnthagen** [comment]
Potentially the problem could be with CORS?

- https://docs.microsoft.com/en-us/aspnet/core/migration/21-to-22?view=aspnetcore-3.1&tabs=visual-studio#update-cors-policy

**Comment by johnthagen** [comment]
@jasonleenaylor I think this PR is close. Everything builds and runs and passes all tests under .NET Core 3.1, but something is wrong with creating new projects (https://github.com/sillsdev/TheCombine/pull/324#issuecomment-632889202), perhaps someone who's had experience porting to .NET 3.1 Core might have an idea of what is going on? Otherwise, I'll keep trying to take a look.

**Comment by jasonleenaylor** [comment]
___
*[Backend/Startup.cs, line 153 at r5](https://reviewable.io/reviews/sillsdev/thecombine/324#-M8Gbqz3BMCu0CGRzyRP:-M8Gbqz452LZVrnVyWAo:b-97nv2m) ([raw file](https://github.com/sillsdev/thecombine/blob/60357fea56afc4714b9b080cc5997a1e9e688d49/Backend/Startup.cs#L153)):*
> ```Smalltalk
> 
>             app.UseAuthentication();
>             app.UseAuthorization();
> ```

So what drove this change? (I haven't looked into it yet.)

**Comment by johnthagen** [comment]
___
*[Backend/Startup.cs, line 153 at r5](https://reviewable.io/reviews/sillsdev/thecombine/324#-M8Gbqz3BMCu0CGRzyRP:-M8NXl7O9Oe_Yb7WLYya:b-9np8ox) ([raw file](https://github.com/sillsdev/thecombine/blob/60357fea56afc4714b9b080cc5997a1e9e688d49/Backend/Startup.cs#L153)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

So what drove this change? (I haven't looked into it yet.)
</blockquote></details>

I was trying to follow examples I found on 3.1 porting guides. Specifically https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-3.1#the-startup-class and https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#startup-changes. But it's very possible it's not needed as I'm not intimately familiar with this startup process yet.

**Comment by johnthagen** [comment]
___
*[Backend/Startup.cs, line 153 at r5](https://reviewable.io/reviews/sillsdev/thecombine/324#-M8Gbqz3BMCu0CGRzyRP:-M8Nk38V1JrpqM4Wh9TG:b-pl3yno) ([raw file](https://github.com/sillsdev/thecombine/blob/60357fea56afc4714b9b080cc5997a1e9e688d49/Backend/Startup.cs#L153)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I was trying to follow examples I found on 3.1 porting guides. Specifically https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-3.1#the-startup-class and https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#startup-changes. But it's very possible it's not needed as I'm not intimately familiar with this startup process yet.
</blockquote></details>

I tried removing the call to `app.UserAuthorization()`, but that causes all API calls to fail:

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 POST https://localhost:5001/v1/users/authenticate application/json;charset=UTF-8 41
info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
      CORS policy execution successful.
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Endpoint BackendFramework.Controllers.UserController.Authenticate (BackendFramework) contains authorization metadata, but a middleware was not found that supports authorization.
Configure your application startup by adding app.UseAuthorization() inside the call to Configure(..) in the application startup code. The call to app.UseAuthorization() must appear between app.UseRouting() and app.UseEndpoints(...).
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.ThrowMissingAuthMiddlewareException(Endpoint endpoint)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 1.3494ms 500 text/plain
```

**Comment by johnthagen** [comment]
Possible reasons for `null` POST bodies:

- https://dev.to/wattengard/why-your-posted-models-may-stop-working-after-upgrading-to-asp-net-core-3-1-4ekp
 - https://stackoverflow.com/questions/60535734/when-posting-to-an-asp-net-core-3-1-web-app-frombodymyclass-data-is-often-n
- https://stackoverflow.com/questions/58542164/jsonpatchdocument-is-null-after-migration-to-net-core-3

**Pull request merged**
