### PR TITLE
ExportProject actions/reducer/state

### PR DESCRIPTION
**Pull request by imnasnainaec**
* Implement redux actions, reducer, and state for ExportProject
* Remove unnecessary layer in MergeDup reducer
* Organize reducers and states
* Split the frontend export project function into two parts: export to zip, download zip
  - At present, the export function is a placeholder and the download function does all the work
  - The functionality still needs to be split in the backend, and the frontend functions updated to match

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/812)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[src/rootReducer.tsx, line 22 at r1](https://reviewable.io/reviews/sillsdev/thecombine/812#-MM2FTME7JVdBpwcqi84:-MM2FTME7JVdBpwcqi85:bvi6krt) ([raw file](https://github.com/sillsdev/thecombine/blob/b45635e1ecc15c8243115b3dfce26eef7257cc18/src/rootReducer.tsx#L22)):*
> ```XML
>   localize: localizeReducer,
> 
>   //login
> ```

Super minor, but the convention I've seen most is to place one space after `//` before a comment if we want to try to stay consistent across all of our code bases.

**Comment by johnthagen** [comment]
___
*[src/backend/index.tsx, line 332 at r1](https://reviewable.io/reviews/sillsdev/thecombine/812#-MM2H4OO6X1kiODTwjww:-MM2H4OO6X1kiODTwjwx:b-g5malx) ([raw file](https://github.com/sillsdev/thecombine/blob/b45635e1ecc15c8243115b3dfce26eef7257cc18/src/backend/index.tsx#L332)):*
> ```XML
> export async function exportLift(projectId?: string) {
>   let projectIdToExport = projectId ? projectId : LocalStorage.getProjectId();
>   // ToDo: Once the create and download functions are split in the backend,
> ```

Super minor, but I've usually seen it written `TODO` for what it's worth.

**Comment by johnthagen** [comment]
___
*[src/backend/index.tsx, line 331 at r1](https://reviewable.io/reviews/sillsdev/thecombine/812#-MM2HJS-238nRMHQDi4P:-MM2HJS-238nRMHQDi4Q:b-6h2gmf) ([raw file](https://github.com/sillsdev/thecombine/blob/b45635e1ecc15c8243115b3dfce26eef7257cc18/src/backend/index.tsx#L331)):*
> ```XML
> // Tell the backend to create a LIFT file for the project
> export async function exportLift(projectId?: string) {
>   let projectIdToExport = projectId ? projectId : LocalStorage.getProjectId();
> ```

`LocalStorage.getProjectId()` returns `""` if there is no project. Would it be more type safe if it returned `undef` so that we could check for if it exists? Not sure what would happen if you try to query for a blank project (probably a silent error to user)?

**Comment by johnthagen** [comment]
___
*[src/components/ProjectSettings/ProjectExport/ExportProjectActions.tsx, line 18 at r1](https://reviewable.io/reviews/sillsdev/thecombine/812#-MM2I5g026ljao3J0XQM:-MM2I5g026ljao3J0XQN:b-pm39zl) ([raw file](https://github.com/sillsdev/thecombine/blob/b45635e1ecc15c8243115b3dfce26eef7257cc18/src/components/ProjectSettings/ProjectExport/ExportProjectActions.tsx#L18)):*
> ```XML
> }
> 
> export function asyncExportProject(projectId?: string) {
> ```

These all take `projectId?`. What should happen if `undef` gets passed in here?

Is there anyway to ensure `undef` isn't passed in at a higher level and handled once to make the signatures on these functions tighter?

**Comment by johnthagen** [comment]
___
*[src/components/ProjectSettings/ProjectExport/ExportProjectReducer.tsx, line 10 at r1](https://reviewable.io/reviews/sillsdev/thecombine/812#-MM2Ins1DILi_rVrqzHb:-MM2Ins1DILi_rVrqzHc:bpizdjf) ([raw file](https://github.com/sillsdev/thecombine/blob/b45635e1ecc15c8243115b3dfce26eef7257cc18/src/components/ProjectSettings/ProjectExport/ExportProjectReducer.tsx#L10)):*
> ```XML
> 
> export const defaultState: ExportProjectState = {
>   projectId: "",
> ```

Another instance of a `""` project ID. It's not clear to me what this means. Should it instead be `projectId?: undef` so we can handle missing ID via the type system?

**Review by johnthagen — DISMISSED** [review]
> Reviewed 19 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/812)* status: all files reviewed, 5 unresolved discussions (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/812)* status: all files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[src/rootReducer.tsx, line 22 at r1](https://reviewable.io/reviews/sillsdev/thecombine/812#-MM2FTME7JVdBpwcqi84:-MM2bkka71TztehCDBPL:bjxvqta) ([raw file](https://github.com/sillsdev/thecombine/blob/b45635e1ecc15c8243115b3dfce26eef7257cc18/src/rootReducer.tsx#L22)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Super minor, but the convention I've seen most is to place one space after `//` before a comment if we want to try to stay consistent across all of our code bases.
</blockquote></details>

I matched the dominant format within the file. Could more global consistency be another pr?
___
*[src/backend/index.tsx, line 331 at r1](https://reviewable.io/reviews/sillsdev/thecombine/812#-MM2HJS-238nRMHQDi4P:-MM2bz1Y75iOUuLbZBsA:b-cx8us1) ([raw file](https://github.com/sillsdev/thecombine/blob/b45635e1ecc15c8243115b3dfce26eef7257cc18/src/backend/index.tsx#L331)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

`LocalStorage.getProjectId()` returns `""` if there is no project. Would it be more type safe if it returned `undef` so that we could check for if it exists? Not sure what would happen if you try to query for a blank project (probably a silent error to user)?
</blockquote></details>

That would probably be be better. A later pr perhaps, since there's already so much in this one?
___
*[src/backend/index.tsx, line 332 at r1](https://reviewable.io/reviews/sillsdev/thecombine/812#-MM2H4OO6X1kiODTwjww:-MM2cA5Y2rnDV1h9FK0s:bqroz8j) ([raw file](https://github.com/sillsdev/thecombine/blob/b45635e1ecc15c8243115b3dfce26eef7257cc18/src/backend/index.tsx#L332)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Super minor, but I've usually seen it written `TODO` for what it's worth.
</blockquote></details>

I've usually seen it that way too, but having Spanish-speaking collaborators in the past, I started using ToDo to minimize confusion ("todo" is Spanish for "everything").
___
*[src/components/ProjectSettings/ProjectExport/ExportProjectActions.tsx, line 18 at r1](https://reviewable.io/reviews/sillsdev/thecombine/812#-MM2I5g026ljao3J0XQM:-MM2cTC_6M2j6kTKMC0A:b-bgwwct) ([raw file](https://github.com/sillsdev/thecombine/blob/b45635e1ecc15c8243115b3dfce26eef7257cc18/src/components/ProjectSettings/ProjectExport/ExportProjectActions.tsx#L18)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

These all take `projectId?`. What should happen if `undef` gets passed in here?

Is there anyway to ensure `undef` isn't passed in at a higher level and handled once to make the signatures on these functions tighter?
</blockquote></details>

It's okay for that function to receive an undefined or "", because the function it calls checks the local storage for the current project if no project id is supplied (intentional decision).
___
*[src/components/ProjectSettings/ProjectExport/ExportProjectReducer.tsx, line 10 at r1](https://reviewable.io/reviews/sillsdev/thecombine/812#-MM2Ins1DILi_rVrqzHb:-MM2cprS0N4s1-i6TUaN:b-y4r8pt) ([raw file](https://github.com/sillsdev/thecombine/blob/b45635e1ecc15c8243115b3dfce26eef7257cc18/src/components/ProjectSettings/ProjectExport/ExportProjectReducer.tsx#L10)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Another instance of a `""` project ID. It's not clear to me what this means. Should it instead be `projectId?: undef` so we can handle missing ID via the type system?
</blockquote></details>

That would perhaps be the best thing long term, to do along-side your first request (re. local storage).

**Comment by johnthagen** [comment]
___
*[src/rootReducer.tsx, line 22 at r1](https://reviewable.io/reviews/sillsdev/thecombine/812#-MM2FTME7JVdBpwcqi84:-MM61PxD5QoaB32UkjDv:b4cv6zq) ([raw file](https://github.com/sillsdev/thecombine/blob/2f8e37cb4e6a8d4e3c13b67cddd17af78293a2d8/src/rootReducer.tsx#L22)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I matched the dominant format within the file. Could more global consistency be another pr?
</blockquote></details>

Sure thing.

**Comment by johnthagen** [comment]
___
*[src/backend/index.tsx, line 331 at r1](https://reviewable.io/reviews/sillsdev/thecombine/812#-MM2HJS-238nRMHQDi4P:-MM61TDABHsr8Dq13SBB:b4cv6zq) ([raw file](https://github.com/sillsdev/thecombine/blob/2f8e37cb4e6a8d4e3c13b67cddd17af78293a2d8/src/backend/index.tsx#L331)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

That would probably be be better. A later pr perhaps, since there's already so much in this one?
</blockquote></details>

Sure thing.

**Comment by johnthagen** [comment]
I didn't find any issues with this PR, but would feel more comfortable if @jasonleenaylor reviewed and gave final approval due to the number of changes and me being relatively less familiar with the overall frontend design.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 15 of 19 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/812)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
