### PR TITLE
Add environment variable instruction for Mac

### PR DESCRIPTION
**Pull request by imnasnainaec**
The rest of the setup/installation instructions work for Mac.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/752)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[README.md, line 74 at r1](https://reviewable.io/reviews/sillsdev/thecombine/752#-MJC6MslBfCqUwE5UxEq:-MJC6MslBfCqUwE5UxEr:b-10pxys) ([raw file](https://github.com/sillsdev/thecombine/blob/fa2d8442cba8179f60b32f724b1fd0cd6e45e2d1/README.md#L74)):*
> ```Markdown
> 4. Set the environment variable `COMBINE_JWT_SECRET_KEY` to a string
>    **containing at least 16 characters**, such as _This is a secret key_. Set
>    it in your `.profile` (Linux or Mac 10.14-), your `.zprofile` (Mac 10.15+), or the _System_ app (Windows).
> ```

For what it's worth, I actually usually recommend `.bashrc` and `.zshrc` for setting these kinds of  environment variables, but `.*profile` is fine too.

**Review by johnthagen — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/752)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

**Review by johnthagen — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/752)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/752)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[README.md, line 74 at r1](https://reviewable.io/reviews/sillsdev/thecombine/752#-MJC6MslBfCqUwE5UxEq:-MJCfC8I4kfT1st5j4mE:b-ejpfy9) ([raw file](https://github.com/sillsdev/thecombine/blob/c68a8540f64e3074e4c9de4cb5ac93c0df0f5dc5/README.md#L74)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

For what it's worth, I actually usually recommend `.bashrc` and `.zshrc` for setting these kinds of  environment variables, but `.*profile` is fine too.
</blockquote></details>

`.*rc` makes it available more immediately (without having to `source` or log out and in again), but with how readily people share their `.*rc`, I feel more comfortable putting sensitive things in`.*profile`.

**Pull request merged**
