### PR TITLE
Generate Helm Chart.yaml files from Jinja templates

### PR DESCRIPTION
**Pull request by jmgrady**
As a first step toward having unique version number for each commit to `master` and having them managed through GitHub actions, this PR changes the versions for the Helm `Chart.yaml` files are managed.  With this PR, the `Chart.yaml` files are generated from Jinja2 templates when the charts are installed on the target.  As part of the chart generation, the version number is filled-in with the version in `package.json`.

This approach provides two benefits:
1. it greatly decreases the maintenance work required for each release; and
2. it will eliminate most of the merge conflicts when we implement unique version numbers for each commit to `master`.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1668)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 9 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1668)* status: 9 of 12 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`.gitignore` line 80 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1668#-N2vxWItDH8RdMQcHRC4:-N2vxWItDH8RdMQcHRC5:b-qmyph9) ([raw file](https://github.com/sillsdev/thecombine/blob/057f6ae5ab2c79e048ec710a82f72e6752308025/.gitignore#L80)):*
> ```ignore
> # Helm charts - generated from templates
> **/Chart.yaml
> **/Chart.lock
> ```

Is `deploy/helm/thecombine/Chart.lock` intentionally committed?



_Code quote:_
```ignore
**/Chart.lock
```

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1668)* status: 9 of 12 files reviewed, 4 unresolved discussions (waiting on @jmgrady)

___
*[`deploy/scripts/combine_charts.py` line 9 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1668#-N2w07kU7m_hM6E-DatJ:-N2w07kVDuCfXknwRfT4:b-fjorea) ([raw file](https://github.com/sillsdev/thecombine/blob/057f6ae5ab2c79e048ec710a82f72e6752308025/deploy/scripts/combine_charts.py#L9)):*
> ```Python
> from pathlib import Path
> 
> from jinja2 import Environment, PackageLoader, select_autoescape
> ```

Why a newline between these imports?



_Code quote:_
```Python
from pathlib import Path

from jinja2 import Environment, PackageLoader, select_autoescape
```
___
*[`deploy/scripts/combine_charts.py` line 42 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1668#-N2vzIzaBZqrzSqMj_-m:-N2vzIzaBZqrzSqMj_-n:bd1jvf7) ([raw file](https://github.com/sillsdev/thecombine/blob/057f6ae5ab2c79e048ec710a82f72e6752308025/deploy/scripts/combine_charts.py#L42)):*
> ```Python
> 
> 
> def generate(version: str, aws_login_version: str = "0.2.0") -> None:
> ```

Can this default to `--aws` so that the default value doesn't have to be updated in two places?



_Code quote:_
```Python
aws_login_version: str = "0.2.0"
```
___
*[`deploy/scripts/combine_charts.py` line 50 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1668#-N2vzit18hlhOwcFC0LR:-N2vzit18hlhOwcFC0LS:b7cv0p3) ([raw file](https://github.com/sillsdev/thecombine/blob/057f6ae5ab2c79e048ec710a82f72e6752308025/deploy/scripts/combine_charts.py#L50)):*
> ```Python
>             "cert_proxy_client": f"v{version}",
>             "cert_proxy_server": f"v{version}",
>             "create_admin_user": f"v{version}",
> ```

The chart version numbers didn't used to begin with "v". What motivates it here?



_Code quote:_
```Python
            "aws_login": f"v{aws_login_version}",
            "thecombine": f"v{version}",
            "cert_proxy_client": f"v{version}",
            "cert_proxy_server": f"v{version}",
            "create_admin_user": f"v{version}",
```

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1668)* status: 9 of 14 files reviewed, 3 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

___
*[`.gitignore` line 80 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1668#-N2vxWItDH8RdMQcHRC4:-N2w9Cnd7e-nyfRvmFU_:bjmol04) ([raw file](https://github.com/sillsdev/thecombine/blob/057f6ae5ab2c79e048ec710a82f72e6752308025/.gitignore#L80)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Is `deploy/helm/thecombine/Chart.lock` intentionally committed?
</blockquote></details>

No.  The Chart.lock files are created when running `deploy/scripts/setup_combine.py`.  I have removed them.
___
*[`deploy/scripts/combine_charts.py` line 9 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1668#-N2w07kU7m_hM6E-DatJ:-N2wAjzB4uzx8FmIsdZv:b-j1xc7w) ([raw file](https://github.com/sillsdev/thecombine/blob/057f6ae5ab2c79e048ec710a82f72e6752308025/deploy/scripts/combine_charts.py#L9)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Why a newline between these imports?
</blockquote></details>

`tox -e fmt` does that.  `pathlib` is part of the standard Python modules; `jinja2` must be installed first with `pip`.
___
*[`deploy/scripts/combine_charts.py` line 42 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1668#-N2vzIzaBZqrzSqMj_-m:-N2wEGZGErUTNCIj9XtQ:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/057f6ae5ab2c79e048ec710a82f72e6752308025/deploy/scripts/combine_charts.py#L42)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Can this default to `--aws` so that the default value doesn't have to be updated in two places?
</blockquote></details>

Done.
___
*[`deploy/scripts/combine_charts.py` line 50 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1668#-N2vzit18hlhOwcFC0LR:-N2wEINX5VT16V0y3tqz:b-wtq3t9) ([raw file](https://github.com/sillsdev/thecombine/blob/057f6ae5ab2c79e048ec710a82f72e6752308025/deploy/scripts/combine_charts.py#L50)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

The chart version numbers didn't used to begin with "v". What motivates it here?
</blockquote></details>

I was my impression that this is standard for Helm Charts in general.  I did some more checking and found that is not the case.  The `v` has been removed.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 12 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1668)* status: 12 of 14 files reviewed, all discussions resolved (waiting on @jmgrady)

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1668)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`deploy/scripts/combine_charts.py` line 33 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1668#-N2wRdgh7uqQ8_1q-C8f:-N2wRdgh7uqQ8_1q-C8g:b-rujyil) ([raw file](https://github.com/sillsdev/thecombine/blob/a058cf2ab420a031cfeef53b0baa123358a6da0c/deploy/scripts/combine_charts.py#L33)):*
> ```Python
>     # Parse user command line arguments
>     parser = argparse.ArgumentParser(
>         description="Update the version and appVersions for the Helm charts.",
> ```

singular "version" yet plural "appVersions"?



_Code quote:_
```Python
version and appVersions
```

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1668)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[`deploy/scripts/combine_charts.py` line 33 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1668#-N2wRdgh7uqQ8_1q-C8f:-N2wUP009GS4dRrRsV0U:bdjwc82) ([raw file](https://github.com/sillsdev/thecombine/blob/a058cf2ab420a031cfeef53b0baa123358a6da0c/deploy/scripts/combine_charts.py#L33)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

singular "version" yet plural "appVersions"?
</blockquote></details>

Changed to `"Update version and appVersion occurrences for the Helm charts."` since each chart will have a `version` and `appVersion` field but there may be additions `version` fields in the dependencies.

**Review by imnasnainaec — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1668)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Pull request merged**
