### PR TITLE
Implement StoreStateDispatch type for all dispatches.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Follow up on #915

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/916)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
___
*[src/components/GoalTimeline/GoalsActions.tsx, line 57 at r1](https://reviewable.io/reviews/sillsdev/thecombine/916#-MR6Qgny4HWzJPfj1akN:-MR6Qgny4HWzJPfj1akO:b-wvwcx6) ([raw file](https://github.com/sillsdev/thecombine/blob/664cb0bce101660530e0c10dffc57eb7d9fe7825/src/components/GoalTimeline/GoalsActions.tsx#L57)):*
> ```
> Dispatch<GoalAction>
> ```
So, this wasn't a thunk dispatch before...

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/916)* status: 0 of 32 files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[src/components/GoalTimeline/GoalsActions.tsx, line 57 at r1](https://reviewable.io/reviews/sillsdev/thecombine/916#-MR6Qgny4HWzJPfj1akN:-MR6R9F831_CeYAE6HkQ:b-lna8hf) ([raw file](https://github.com/sillsdev/thecombine/blob/664cb0bce101660530e0c10dffc57eb7d9fe7825/src/components/GoalTimeline/GoalsActions.tsx#L57)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> Dispatch<GoalAction>
> ```
So, this wasn't a thunk dispatch before...
</blockquote></details>

I'm under the impression that ThunkDispatch encompasses all our dispatches, but I welcome clarification.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 32 of 32 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/916)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/components/GoalTimeline/GoalsActions.tsx, line 57 at r1](https://reviewable.io/reviews/sillsdev/thecombine/916#-MR6Qgny4HWzJPfj1akN:-MR6Ry7JDBGGJj_7Loav:b-w62h9y) ([raw file](https://github.com/sillsdev/thecombine/blob/664cb0bce101660530e0c10dffc57eb7d9fe7825/src/components/GoalTimeline/GoalsActions.tsx#L57)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I'm under the impression that ThunkDispatch encompasses all our dispatches, but I welcome clarification.
</blockquote></details>

Yes, it should, as I thought further on this the real question is why wasn't it one before.

**Review by jasonleenaylor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/916#-:-MR6SEek5xVrATVcBwb6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
