### PR TITLE
Refactor backend file storage paths

### LINKED ISSUE #789: Refactor file storage paths
There are many duplicated magic strings related to where files are stored in the backend. Search for the following terms to see the duplicates:

- `.CombineFiles`
- `ExtractedLocation`

Further, the current solution seems to mix temporary files (such as those used during Lift import and export) and permanent files, such as audio into the same directories, which makes it more difficult to prune temporary directories (#786) and can lead to strange edge-case bugs (#788).

It would be best to use `/tmp` file locations as much as possible.

### PR DESCRIPTION
**Pull request by johnthagen**
Closes #789

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/845)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/845)* status: 3 of 12 files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 8 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/845)* status: 9 of 14 files reviewed, all discussions resolved (waiting on @imnasnainaec and @johnthagen)

___
*[Backend/Helper/FileStorage.cs, line 84 at r5](https://reviewable.io/reviews/sillsdev/thecombine/845#-MNjTyME3q6tth81rwYw:-MNjTyME3q6tth81rwYx:b-9c7gif) ([raw file](https://github.com/sillsdev/thecombine/blob/4c2564d960ea460e006649424a87544066c088aa/Backend/Helper/FileStorage.cs#L84)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>             return GenerateProjectDirPath(projectId, "Export", createDir);
>         }
>         /// <summary>
>         /// Generate the path to where Avatar images are stored.
>         /// </summary>
>         public static string GenerateAvatarFilePath(string userId)
>         {
>             return GenerateFilePath("Avatars", userId, FileType.Avatar);
> ```
</details>

Perhaps the export and avatar suffixes should go up at the top of the class with the `private static readonly string`s.
___
*[Backend/Helper/FileStorage.cs, line 106 at r5](https://reviewable.io/reviews/sillsdev/thecombine/845#-MNjUEDX7DCV_c_yYIO2:-MNjUEDX7DCV_c_yYIO3:b-3gitdi) ([raw file](https://github.com/sillsdev/thecombine/blob/4c2564d960ea460e006649424a87544066c088aa/Backend/Helper/FileStorage.cs#L106)):*
> ```
>             return Path.Combine(GetHomePath(), ".CombineFiles");
> ```
ditto
___
*[Backend/Services/WordApiServices.cs, line 288 at r5](https://reviewable.io/reviews/sillsdev/thecombine/845#-MNjW6IlCKqEL_z4dHPf:-MNjW6Im5p4Ej3an2okz:bqfeghi) ([raw file](https://github.com/sillsdev/thecombine/blob/4c2564d960ea460e006649424a87544066c088aa/Backend/Services/WordApiServices.cs#L288)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>         public string GetAudioFilePath(string projectId, string wordId, string fileName)
>         {
>             // TODO: Migrate this to a new FileService service.
>             return FileStorage.GenerateAudioFilePath(projectId, fileName);
>         }
> ```
</details>

Why not delete this function and directly call `FileStorage.GenerateAudioFilePath` the one place this function is used in `AudioController`?
___
*[Backend.Tests/Util.cs, line 10 at r6](https://reviewable.io/reviews/sillsdev/thecombine/845#-MNjWoe5AgwWkkSrx1nY:-MNjWoe5AgwWkkSrx1nZ:b4fcneb) ([raw file](https://github.com/sillsdev/thecombine/blob/3edfe8b08f4c09229ac8c92634fe8ab40bf4cf38/Backend.Tests/Util.cs#L10)):*
> ```
>         /// <summary> Path to Asserts directory from debugging folder </summary>
> ```
Asserts or Assets?

**Comment by johnthagen** [comment]
___
*[Backend/Helper/FileStorage.cs, line 84 at r5](https://reviewable.io/reviews/sillsdev/thecombine/845#-MNjTyME3q6tth81rwYw:-MNjYPCgAVrSU3DG-TFo:biioup4) ([raw file](https://github.com/sillsdev/thecombine/blob/4c2564d960ea460e006649424a87544066c088aa/Backend/Helper/FileStorage.cs#L84)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>             return GenerateProjectDirPath(projectId, "Export", createDir);
>         }
>         /// <summary>
>         /// Generate the path to where Avatar images are stored.
>         /// </summary>
>         public static string GenerateAvatarFilePath(string userId)
>         {
>             return GenerateFilePath("Avatars", userId, FileType.Avatar);
> ```
Perhaps the export and avatar suffixes should go up at the top of the class with the `private static readonly string`s.
</blockquote></details>

Originally I was thinking of reducing the scope, but I think it is nice to have all of the constants in once place to view too.

Done

**Comment by johnthagen** [comment]
___
*[Backend/Helper/FileStorage.cs, line 106 at r5](https://reviewable.io/reviews/sillsdev/thecombine/845#-MNjUEDX7DCV_c_yYIO2:-MNjY_8o0MYeIIUlZg61:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/4c2564d960ea460e006649424a87544066c088aa/Backend/Helper/FileStorage.cs#L106)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>             return Path.Combine(GetHomePath(), ".CombineFiles");
> ```
ditto
</blockquote></details>

Done.

**Comment by johnthagen** [comment]
___
*[Backend.Tests/Util.cs, line 10 at r6](https://reviewable.io/reviews/sillsdev/thecombine/845#-MNjWoe5AgwWkkSrx1nY:-MNjYgHZ84WjSQLr6mQk:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/3edfe8b08f4c09229ac8c92634fe8ab40bf4cf38/Backend.Tests/Util.cs#L10)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>         /// <summary> Path to Asserts directory from debugging folder </summary>
> ```
Asserts or Assets?
</blockquote></details>

Done.

**Comment by johnthagen** [comment]
___
*[Backend/Services/WordApiServices.cs, line 288 at r5](https://reviewable.io/reviews/sillsdev/thecombine/845#-MNjW6IlCKqEL_z4dHPf:-MNjZMwP-KxOHuA1Pebm:b-3t3nlq) ([raw file](https://github.com/sillsdev/thecombine/blob/4c2564d960ea460e006649424a87544066c088aa/Backend/Services/WordApiServices.cs#L288)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>         public string GetAudioFilePath(string projectId, string wordId, string fileName)
>         {
>             // TODO: Migrate this to a new FileService service.
>             return FileStorage.GenerateAudioFilePath(projectId, fileName);
>         }
> ```
Why not delete this function and directly call `FileStorage.GenerateAudioFilePath` the one place this function is used in `AudioController`?
</blockquote></details>

Done.

I had originally thought I wasn't going to get as far in this PR as I did. Good catch.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 2 of 4 files at r6, 6 of 6 files at r7.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/845)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
