### PR TITLE
Fix handling case if audio file is missing

### PR DESCRIPTION
**Pull request by johnthagen**
Previously, we were testing `if file is null`, but the compiler enforces that it cannot be `null`. In fact, the way `OpenRead` signals that the file does not exist is to throw an `Exception`.

This change will properly return a `BadRequest` in the event the file has been deleted or moved rather than allowing an uncaught exception to bubble into a 500 server error.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1357)

### CODE REVIEW

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1357)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Review by imnasnainaec — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1357)* status: all files reviewed, 1 unresolved discussion (waiting on @johnthagen)

*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/1357#-MigUo9j3rirFv4jaz_B:-MigUo9k-CBOgJkwBl_w:bsogtm4) (no related file):*
Sorry, there's an issue.

---

**Review by imnasnainaec — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1357)* status: all files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[Backend/Controllers/AudioController.cs, line 54 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1357#-MigVKkO1stxU5SxGBsu:-MigVKkO1stxU5SxGBsv:bt0qjo4) ([raw file](https://github.com/sillsdev/thecombine/blob/384d3827844705caa966915cf97e301f0c2ffda1/Backend/Controllers/AudioController.cs#L54)):*
> ```Smalltalk
> 
>             var filePath = FileStorage.GenerateAudioFilePath(projectId, fileName);
>             if (!System.IO.File.Exists(fileName))
> ```

This should be `filePath` not `fileName`.

**Comment by johnthagen** [comment]
___
*[Backend/Controllers/AudioController.cs, line 54 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1357#-MigVKkO1stxU5SxGBsu:-MigbISP7zhnyYRlbkvQ:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/384d3827844705caa966915cf97e301f0c2ffda1/Backend/Controllers/AudioController.cs#L54)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

This should be `filePath` not `fileName`.
</blockquote></details>

Done.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1357)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Pull request merged**
