### PR TITLE
[ProjectLanguages] Add new analysis language or select new default

### LINKED ISSUE #712: [ProjectSettings] Modify list of analysis languages
The vernacular language of a project should not change, but we should allow for multiple analysis languages.

Features needed:
- [ ] Add a new analysis language
- [ ] Change the default/active analysis language (e.g., move it to the top of the list)
- [ ] (Maybe) Delete an analysis language
    - Possible restrictions: if not default; if not in any glosses in the project
- [ ] (Maybe) change the font associated with vernacular or analysis languages

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #712 (or at least the first two items).

Projects have 1 analysis language on creation. In project setting, this pr adds a + button to reveal the language picker and add a secondary analysis language.
Screen Shot 2020-11-24 at 14 34 02
Screen Shot 2020-11-24 at 14 34 54

The top language in the list is the primary/default associated with new entries, so this pr also adds a ↑ button by all secondary analysis languages allow it to be selected as the new default.
Screen Shot 2020-11-24 at 14 53 53
Screen Shot 2020-11-24 at 14 35 20

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/751)

### CODE REVIEW

**Comment by imnasnainaec** [comment]
Need unit tests.

**Comment by jasonleenaylor** [comment]
___
*[src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx, line 55 at r5](https://reviewable.io/reviews/sillsdev/thecombine/751#-MObGC2t1l5-45cyaTVr:-MObGC2t1l5-45cyaTVs:b-xwclhz) ([raw file](https://github.com/sillsdev/thecombine/blob/07b82655ad0a72346f79b5cd3e7fba694be73544/src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx#L55)):*
> ```XML
>       font: this.state.font,
>     };
>     this.props.project.analysisWritingSystems.push(ws);
> ```

I think we need to handle the case where a user accidentally adds a language they already have.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/751)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor)

___
*[src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx, line 55 at r5](https://reviewable.io/reviews/sillsdev/thecombine/751#-MObGC2t1l5-45cyaTVr:-MObMn9iDtnFGAoH64gA:b-eqfj7o) ([raw file](https://github.com/sillsdev/thecombine/blob/07b82655ad0a72346f79b5cd3e7fba694be73544/src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx#L55)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

I think we need to handle the case where a user accidentally adds a language they already have.
</blockquote></details>

The submit button is disabled if `isNewWritingSystem` (below) returns false. Let me know if you want redundant safe-guards, in this function or via a comment somewhere.

**Comment by jasonleenaylor** [comment]
___
*[src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx, line 55 at r5](https://reviewable.io/reviews/sillsdev/thecombine/751#-MObGC2t1l5-45cyaTVr:-MObRu0s84xaakhRBuN-:bsxu3j1) ([raw file](https://github.com/sillsdev/thecombine/blob/07b82655ad0a72346f79b5cd3e7fba694be73544/src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx#L55)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

The submit button is disabled if `isNewWritingSystem` (below) returns false. Let me know if you want redundant safe-guards, in this function or via a comment somewhere.
</blockquote></details>

Sorry that I didn't see that. We don't need the redundant safeguard, but we should have a unit test for it.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/751)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor)

___
*[src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx, line 55 at r5](https://reviewable.io/reviews/sillsdev/thecombine/751#-MObGC2t1l5-45cyaTVr:-MObisbeErtfNHXOlTzP:bqmjwcz) ([raw file](https://github.com/sillsdev/thecombine/blob/07b82655ad0a72346f79b5cd3e7fba694be73544/src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx#L55)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Sorry that I didn't see that. We don't need the redundant safeguard, but we should have a unit test for it.
</blockquote></details>

Added.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 2 of 3 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/751)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
