### PR TITLE
Vernacular Autocomplete

### PR DESCRIPTION
**Pull request by charjhall**
Closing #494

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/516)

### CODE REVIEW

**Comment by imnasnainaec** [comment]
Also closes #484

**Comment by imnasnainaec** [comment]
Resolves #478 ?

**Comment by charjhall** [comment]
> Resolves #478 ?

I will not be resolving #478 in this PR, it can be done separately.

**Comment by stevendyk** [comment]
[Testing Notes 7/10/2020, Vernacular autocomplete options (similar words) are not always all visible](https://docs.google.com/document/d/1njDXI6dkj8G1vJMoxdpFWwNGwJz_RklWS5AdC07_AcI/edit#heading=h.h8xlfpgurhyb)

**Comment by stevendyk** [comment]
#357 closed, but did not pass user tests. Reference [7/10 Testing Notes](url)
Related to #494

**Comment by imnasnainaec** [comment]
Replaced by #585

**Pull request closed without merging**
