### PR TITLE
Set a minimum backend unit test coverage value

### PR DESCRIPTION
**Pull request by johnthagen**
- Set a minimum value for the backend unit test coverage. The backend tests will fail if code coverage dropped below a threshold. This ensures that if new code is added to the backend, it is unit tested unless the team explicitly opts into lowering the threshold
  - The threshold is applied to line, branch, and method coverage. The current lowest value is branch coverage.
- Increase `WordController` coverage to 100%
- Increase `UserRoleController` coverage
- Increase `UserEditController` coverage
- Fix bug in `UserEditRepositoryMock::Delete` that would throw an exception rather than return `false` on error

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1469)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1469)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[Backend.Tests/Controllers/WordControllerTests.cs, line 23 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1469#-MoJuzH321ShS24Sq-BE:-MoJuzH321ShS24Sq-BF:bm4tfz5) ([raw file](https://github.com/sillsdev/thecombine/blob/130a8a1abf5d907b7517acda2afd7e1b1dbb357f/Backend.Tests/Controllers/WordControllerTests.cs#L23)):*
> ```Smalltalk
> 
>         private string _projId = null!;
>         private const string MissingId = "INVALID_PROJECT_ID";
> ```

`"INVALID_PROJECT_ID"` is no longer a fitting string for a general-purpose `MissingId` variable.

**Comment by johnthagen** [comment]
___
*[Backend.Tests/Controllers/WordControllerTests.cs, line 23 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1469#-MoJuzH321ShS24Sq-BE:-MoK6z6e3z4Am3599ELl:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/adc48597e559902525baef4c28775979cedc6f24/Backend.Tests/Controllers/WordControllerTests.cs#L23)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`"INVALID_PROJECT_ID"` is no longer a fitting string for a general-purpose `MissingId` variable.
</blockquote></details>

Done.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, 2 of 2 files at r3, 1 of 1 files at r8, 1 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1469)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @johnthagen)

___
*[package.json, line 31 at r9](https://reviewable.io/reviews/sillsdev/thecombine/1469#-MoL3KfZ6wIrWaTcIvWQ:-MoL3KfZ6wIrWaTcIvWR:b-r7dd3t) ([raw file](https://github.com/sillsdev/thecombine/blob/345c7427da24f0e067e5f1eb733537dcd5ab13a2/package.json#L31)):*
> ```JSON
>     "test": "npm run test-backend && npm run test-frontend",
>     "test-backend": "dotnet test Backend.Tests/Backend.Tests.csproj",
>     "test-backend:coverage": "dotnet test Backend.Tests/Backend.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:Threshold=77",
> ```

The percent calculation is somewhat variable. Three consecutive runs of `npm run test-backend:coverage` give me:
```
+------------------+--------+--------+--------+
| Module           | Line   | Branch | Method |
+------------------+--------+--------+--------+
| BackendFramework | 79.66% | 78.12% | 84.81% |
+------------------+--------+--------+--------+

+------------------+--------+--------+--------+
| BackendFramework | 79.66% | 78.03% | 84.81% |
+------------------+--------+--------+--------+

+------------------+--------+--------+--------+
| BackendFramework | 79.96% | 78.48% | 84.81% |
+------------------+--------+--------+--------+
```

So it's probably good that we're setting the threshold at least .5 lower then the min of a given run.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1469)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Pull request merged**
