### PR TITLE
Implement sorting users by email and reverse alphabetical sorting 

### LINKED ISSUE #1227: [ProjectSettings, SiteSettings] Enhancing user list sorting
It would be a nice feature to allow sorting user lists by email, but only admins should have access to this sorting order due to privacy concerns.
It would also be convenient to allow sorting by reverse alphabetical order although the feature does not have to be very discoverable since those seeking to use it will likely be able to find it.

- [ ] allow project owners/site admins to sort user lists by email
- [ ] allow sorting user lists by reverse alphabetical order (ideally implemented as a subtle portion of the interface such as clicking an already-selected sorting order again to achieve reverse alphabetical sorting)

### PR DESCRIPTION
**Pull request by WeJamUS**
closes #1227

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1276)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 3 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1276)* status: 3 of 8 files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 40 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1276#-MfZAR0J3t0nN_XJdBSK:-MfZAR0J3t0nN_XJdBSL:boahafg) ([raw file](https://github.com/sillsdev/thecombine/blob/23f2b503b68db1ce68893e054bbfe7cf635bc16c/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L40)):*
> ```
> alphabeticalUserOrder
> ```
This variable name could use some work. Since we can sort by Name, Username, and Email this state doesn't quite match up with the usage. `alphabeticalOrder` is better, but what does `!alphabeticalOrder` mean.  Something like `reverseSorting` (you'd have to reverse the logic as well) .

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 5 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1276)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1276)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[Backend/Controllers/UserController.cs, line 144 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1276#-MfcHWeF4pLjoCdrt1SR:-MfcHWeF4pLjoCdrt1SS:byz9fri) ([raw file](https://github.com/sillsdev/thecombine/blob/adec677ec65c019081e734955719830922a0b32e/Backend/Controllers/UserController.cs#L144)):*
> ```Smalltalk
>         public async Task<IActionResult> GetUserByEmail(string email)
>         {
>             var user = await _userRepo.GetUserByEmail(email);
> ```

Looking back over this with an eye to security I think that this method should only be available to project owners and site admins. See the DeleteUser as an example of how to restrict it.

**Comment by jasonleenaylor** [comment]
Ok, after you add a unit test then this will be good to go. :)

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1276)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1276)* status: all files reviewed, 1 unresolved discussion (waiting on @WeJamUS)

___
*[Backend/Controllers/UserController.cs, line 144 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1276#-Mfhdizn47VfSfupriAc:-Mfhdizn47VfSfupriAd:bdaa405) ([raw file](https://github.com/sillsdev/thecombine/blob/10f6e1a874fa352154e40829bcde9400f63c6cfc/Backend/Controllers/UserController.cs#L144)):*
> ```Smalltalk
>         public async Task<IActionResult> GetUserByEmail(string email)
>         {
>             if (!await _permissionService.IsSiteAdmin(HttpContext) || !await _permissionService.HasProjectPermission(HttpContext, Permission.Owner))
> ```

`await _permissionService.HasProjectPermission(HttpContext, ...)` has a check for site admin built in, so `!await _permissionService.IsSiteAdmin(HttpContext) ||` is unnecessary.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 2 of 8 files at r1, 1 of 2 files at r4, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1276)* status: all files reviewed, 1 unresolved discussion (waiting on @WeJamUS)

___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 15 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1276#-MfhoX7DDeZOuOjSwOyy:-MfhoX7DDeZOuOjSwOyz:b-sxk1f4) ([raw file](https://github.com/sillsdev/thecombine/blob/86016be4d8db0e4050c4c992069c1a06ee0a515f/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L15)):*
> ```
> import MoreVertIcon from "@material-ui/icons/MoreVert";
> import SortByAlphaIcon from "@material-ui/icons/SortByAlpha";
> ```
Can combine: `import {MoreVertIcon, SortByAlphaIcon} from "@material-ui/icons";`

**Comment by WeJamUS** [comment]
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 15 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1276#-MfhoX7DDeZOuOjSwOyy:-MfhqyuNAmLT_Wbuu_aT:bh6ta6j) ([raw file](https://github.com/sillsdev/thecombine/blob/86016be4d8db0e4050c4c992069c1a06ee0a515f/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L15)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> import MoreVertIcon from "@material-ui/icons/MoreVert";
> import SortByAlphaIcon from "@material-ui/icons/SortByAlpha";
> ```
Can combine: `import {MoreVertIcon, SortByAlphaIcon} from "@material-ui/icons";`
</blockquote></details>

I previously tried that because I thought what I currently had was redundant, but it gives me an error for both icon imports saying "Module '"@material-ui/icons"' has no exported member 'SortByAlphaIcon'".

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1276)* status: all files reviewed, 1 unresolved discussion (waiting on @WeJamUS)

___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 15 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1276#-MfhoX7DDeZOuOjSwOyy:-MfhsU1P6BFrcVJznDJE:bu9a8za) ([raw file](https://github.com/sillsdev/thecombine/blob/86016be4d8db0e4050c4c992069c1a06ee0a515f/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L15)):*
<details><summary><i>Previously, WeJamUS (James Wu) wrote…</i></summary><blockquote>

I previously tried that because I thought what I currently had was redundant, but it gives me an error for both icon imports saying "Module '"@material-ui/icons"' has no exported member 'SortByAlphaIcon'".
</blockquote></details>

Oh, it's probably just `import {MoreVert, SortByAlpha} from "@material-ui/icons";`

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1276)* status: all files reviewed, 2 unresolved discussions (waiting on @WeJamUS)

___
*[src/components/SiteSettings/UserManagement/UserList.tsx, line 161 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1276#-MfhtPqS694wyXTQqmN3:-MfhtPqS694wyXTQqmN4:bgwmqaj) ([raw file](https://github.com/sillsdev/thecombine/blob/10f6e1a874fa352154e40829bcde9400f63c6cfc/src/components/SiteSettings/UserManagement/UserList.tsx#L161)):*
> ```
> <ListItemText primary={`${user.name} (${user.username})`} />
> ```
We probably want to expand this to ```{`${user.name} (${user.username} | ${user.email})`}``` now that sorting by email is available. And also add ` | ${user.email}` in project settings if the user is the project owner.

**Comment by WeJamUS** [comment]
___
*[src/components/SiteSettings/UserManagement/UserList.tsx, line 161 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1276#-MfhtPqS694wyXTQqmN3:-Mfi3ZyI9hjOjAq2F7Zc:b-hkpcgr) ([raw file](https://github.com/sillsdev/thecombine/blob/10f6e1a874fa352154e40829bcde9400f63c6cfc/src/components/SiteSettings/UserManagement/UserList.tsx#L161)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> <ListItemText primary={`${user.name} (${user.username})`} />
> ```
We probably want to expand this to ```{`${user.name} (${user.username} | ${user.email})`}``` now that sorting by email is available. And also add ` | ${user.email}` in project settings if the user is the project owner.
</blockquote></details>

Could you explain a bit more about the adding | ${user.email} in project settings part? I'm stuck on how to start on that.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1276)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec, @jasonleenaylor, and @WeJamUS)

___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 180 at r7](https://reviewable.io/reviews/sillsdev/thecombine/1276#-MfiBLLE8ICC79_AaDeP:-MfiBLLE8ICC79_AaDeQ:b-u9t6ct) ([raw file](https://github.com/sillsdev/thecombine/blob/fda97d41532fe45af34e13325a7a070fb767dd87/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L180)):*
> ```
>           <ListItemText primary={`${user.name} (${user.username})`} />
> ```
For one approach to your question from SiteSettings, this line can be replaced with:
`<ListItemText primary={displayString} />` with the following added right before `userList.push(...`:
```
      const displayString =
        currentUserIsProjectOwner || currentUser.isAdmin
          ? `${user.name} (${user.username} | ${user.email})`
          : `${user.name} (${user.username})`;
```

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1276)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec, @jasonleenaylor, and @WeJamUS)

___
*[src/components/SiteSettings/UserManagement/UserList.tsx, line 162 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1276#-MfiTXob-P-6ruLiEgCZ:-MfiTXob-P-6ruLiEgC_:b-gwybug) ([raw file](https://github.com/sillsdev/thecombine/blob/bb239d6881b5c1254106f4372bf8d4ebfca6e1c5/src/components/SiteSettings/UserManagement/UserList.tsx#L162)):*
> ```XML
>                 />
>                 <ListItemText
>                   primary={`${user.name} (${user.username}) | ${user.email})`}
> ```

Now there's an extraneous ) after `...username}`

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1276)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @WeJamUS)

**Pull request merged**
