### PR TITLE
Add SemDomWritingSystem to project settings

### LINKED ISSUE #1542: Add a project setting to allow the user to choose the language for the semantic domain questions
There needs to be a new setting in the Project settings screen which offers the existing translations of the semantic domain data and lets the project administrator choose the one to use. The default will be English.

**Acceptance Tests**

1. The project administrator chooses French for a project where English is the analysis.
2. Another user opens the Data Entry tool. 
3. The domain description and questions appear in French.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #1542

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1545)

### CODE REVIEW

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1545)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[src/components/TreeView/TreeViewComponent.tsx, line 11 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1545#-MuSSiwF-R0lPfoXjzbu:-MuSSiwF-R0lPfoXjzbv:b-6k2u0) ([raw file](https://github.com/sillsdev/thecombine/blob/5588c915f73406e46a22b6c5abac97a17e7a4f0b/src/components/TreeView/TreeViewComponent.tsx#L11)):*
> ```XML
> import TreeSemanticDomain from "components/TreeView/TreeSemanticDomain";
> import { createDomains } from "components/TreeView/TreeViewReducer";
> import en from "resources/semantic-domains/en.json";
> ```

Do we have an issue created to improve this yet?



_Code quote:_
```XML
import en from "resources/semantic-domains/en.json";
import es from "resources/semantic-domains/es.json";
import fr from "resources/semantic-domains/fr.json";
```
___
*[src/components/TreeView/TreeViewComponent.tsx, line 52 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1545#-MuSSxZa5MJ7O_bAaf9S:-MuSSxZa5MJ7O_bAaf9T:b-jfq9f) ([raw file](https://github.com/sillsdev/thecombine/blob/5588c915f73406e46a22b6c5abac97a17e7a4f0b/src/components/TreeView/TreeViewComponent.tsx#L52)):*
> ```XML
>     this.animate = this.animate.bind(this);
> 
>     /* Select the language used for the semantic domains.
> ```

Nice commenting.



_Code quote:_
```XML
    /* Select the language used for the semantic domains.
     * Primary: Has it been specified for the project?
     * Secondary: What is the current browser/ui language?
     * Default: English. */
    const lang =
      getSemDomWritingSystem(props.semDomWritingSystem)?.bcp47 ??
      props.activeLanguage?.code;
    // Use ? after props.activeLanguage, since it's not defined in unit tests.
```

**Comment by johnthagen** [comment]
___
*[src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx, line 246 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1545#-MuW-6BSBjh01tEItFGe:-MuW-6BSBjh01tEItFGf:b-hddryx) ([raw file](https://github.com/sillsdev/thecombine/blob/5588c915f73406e46a22b6c5abac97a17e7a4f0b/src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx#L246)):*
> ```XML
>         <Select
>           id="semantic-domains-language"
>           value={this.props.project.semDomWritingSystem?.bcp47 ?? ""}
> ```

This `?` seems unnecessary since `Project.semDomWritingSystem` is not optional.

If we are worried about this field not being there on old projects, I would suggest that a database migration script be required before this is deployed. This would allow us to remove this small technical debt of an extraneous `?`.

**Comment by johnthagen** [comment]
___
*[src/components/TreeView/TreeViewComponent.tsx, line 11 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1545#-MuSSiwF-R0lPfoXjzbu:-MuW0vLI-bR6JFzH-Dd7:b-mc40ek) ([raw file](https://github.com/sillsdev/thecombine/blob/5588c915f73406e46a22b6c5abac97a17e7a4f0b/src/components/TreeView/TreeViewComponent.tsx#L11)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Do we have an issue created to improve this yet?
</blockquote></details>

Out of curiosity, what is the problem with this?

**Comment by johnthagen** [comment]
___
*[src/components/TreeView/TreeViewComponent.tsx, line 59 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1545#-MuW282E4pbP3rUmb7BF:-MuW282E4pbP3rUmb7BG:bdybtd) ([raw file](https://github.com/sillsdev/thecombine/blob/5588c915f73406e46a22b6c5abac97a17e7a4f0b/src/components/TreeView/TreeViewComponent.tsx#L59)):*
> ```XML
>       getSemDomWritingSystem(props.semDomWritingSystem)?.bcp47 ??
>       props.activeLanguage?.code;
>     // Use ? after props.activeLanguage, since it's not defined in unit tests.
> ```

Having the production code become a little less understandable seems non-ideal if it can be avoided.

Can the unit tests simply be updated to respect  the correct types?

**Comment by johnthagen** [comment]
___
*[src/components/TreeView/TreeViewComponent.tsx, line 78 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1545#-MuW3Iq99-V0DgrpQXlg:-MuW3Iq99-V0DgrpQXlh:bog7v8n) ([raw file](https://github.com/sillsdev/thecombine/blob/5588c915f73406e46a22b6c5abac97a17e7a4f0b/src/components/TreeView/TreeViewComponent.tsx#L78)):*
> ```XML
>     } else {
>       const newDomain = createDomains(domains);
>       // If the current domain is the default then set the name to the translation of "Semantic Domain"
> ```

Wrap long line.

**Comment by johnthagen** [comment]
___
*[src/components/TreeView/TreeViewComponent.tsx, line 73 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1545#-MuW3MwT-dzjDXPrLaJU:-MuW3MwT-dzjDXPrLaJV:bog7v8n) ([raw file](https://github.com/sillsdev/thecombine/blob/5588c915f73406e46a22b6c5abac97a17e7a4f0b/src/components/TreeView/TreeViewComponent.tsx#L73)):*
> ```XML
>     }
> 
>     // If the state has the current domain defined then use that in the navigateTree call
> ```

Wrap long line.

**Comment by johnthagen** [comment]
___
*[src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx, line 252 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1545#-MuW50Wu1BDBxf6sbVRw:-MuW50Wu1BDBxf6sbVRx:bple7f) ([raw file](https://github.com/sillsdev/thecombine/blob/5588c915f73406e46a22b6c5abac97a17e7a4f0b/src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx#L252)):*
> ```XML
>         >
>           <MenuItem value={""}>
>             <Translate id="projectSettings.language.semanticDomainsDefault" />
> ```

My initial reaction was that I was confused why this section was blank at first. I had to expand the menu to visually see what the default setting was.



In the default case, should the drop down show `(Browser Language)`? I think that possibly the `default to` portion could be dropped, since that is really an implementation detail and to the user it will be implicitly the default for new projects, just like the Autocomplete, etc. have defaults. We don't label the defaults as "default" in the UI, though, we just use it as the default.

I would suggest that `Browser Language` be shown by default here.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1545)* status: 9 of 14 files reviewed, 5 unresolved discussions (waiting on @imnasnainaec, @jasonleenaylor, and @johnthagen)

___
*[src/components/TreeView/TreeViewComponent.tsx, line 11 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1545#-MuSSiwF-R0lPfoXjzbu:-MuWXYtWAaSPQRlInU7n:b-8sgfq4) ([raw file](https://github.com/sillsdev/thecombine/blob/5588c915f73406e46a22b6c5abac97a17e7a4f0b/src/components/TreeView/TreeViewComponent.tsx#L11)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Out of curiosity, what is the problem with this?
</blockquote></details>

#1546
___
*[src/components/TreeView/TreeViewComponent.tsx, line 59 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1545#-MuW282E4pbP3rUmb7BF:-MuWXgz01dbXV4bXyzZP:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/5588c915f73406e46a22b6c5abac97a17e7a4f0b/src/components/TreeView/TreeViewComponent.tsx#L59)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Having the production code become a little less understandable seems non-ideal if it can be avoided.

Can the unit tests simply be updated to respect  the correct types?
</blockquote></details>

Done.
___
*[src/components/TreeView/TreeViewComponent.tsx, line 73 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1545#-MuW3MwT-dzjDXPrLaJU:-MuWXiaD5RT63lJsEVJv:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/5588c915f73406e46a22b6c5abac97a17e7a4f0b/src/components/TreeView/TreeViewComponent.tsx#L73)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Wrap long line.
</blockquote></details>

Done.
___
*[src/components/TreeView/TreeViewComponent.tsx, line 78 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1545#-MuW3Iq99-V0DgrpQXlg:-MuWXj5e-ty_E9k6AgrA:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/5588c915f73406e46a22b6c5abac97a17e7a4f0b/src/components/TreeView/TreeViewComponent.tsx#L78)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Wrap long line.
</blockquote></details>

Done.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1545)* status: 8 of 14 files reviewed, 5 unresolved discussions (waiting on @imnasnainaec, @jasonleenaylor, and @johnthagen)

___
*[src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx, line 252 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1545#-MuW50Wu1BDBxf6sbVRw:-MuWaotICzFC5xxkHrzG:bos8hnz) ([raw file](https://github.com/sillsdev/thecombine/blob/5588c915f73406e46a22b6c5abac97a17e7a4f0b/src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx#L252)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

My initial reaction was that I was confused why this section was blank at first. I had to expand the menu to visually see what the default setting was.



In the default case, should the drop down show `(Browser Language)`? I think that possibly the `default to` portion could be dropped, since that is really an implementation detail and to the user it will be implicitly the default for new projects, just like the Autocomplete, etc. have defaults. We don't label the defaults as "default" in the UI, though, we just use it as the default.

I would suggest that `Browser Language` be shown by default here.
</blockquote></details>

I'm hesitant to use something minimal like "Browser Language" as the top item, because I don't want users to mistakenly think they are making a selection *for* the browser language. It needs to indicate that they don't have to make a selection, and if they don't, it defaults to whatever language each project user's browser is in.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1545)* status: 8 of 14 files reviewed, 5 unresolved discussions (waiting on @imnasnainaec, @jasonleenaylor, and @johnthagen)

___
*[src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx, line 252 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1545#-MuW50Wu1BDBxf6sbVRw:-MuWenjoANgUzjbC6OTU:b-mywj98) ([raw file](https://github.com/sillsdev/thecombine/blob/5588c915f73406e46a22b6c5abac97a17e7a4f0b/src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx#L252)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I'm hesitant to use something minimal like "Browser Language" as the top item, because I don't want users to mistakenly think they are making a selection *for* the browser language. It needs to indicate that they don't have to make a selection, and if they don't, it defaults to whatever language each project user's browser is in.
</blockquote></details>

Awkward work-around implemented for not having a blank menu on the default value.

**Review by johnthagen — APPROVED** [review]
> Reviewed 5 of 5 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1545)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
