### PR TITLE
Consolidate language and writing system definitions

### LINKED ISSUE #1547: Refactor duplicated usages of analysis language
There are multiple places where strings like `"en"` and `"English"` are referenced.

https://github.com/sillsdev/TheCombine/blob/c4c155fc01d94d8207df378d7aa94757c181bd49/src/components/DataEntry/DataEntryTable/DataEntryTable.tsx#L105-L106

https://github.com/sillsdev/TheCombine/blob/c4c155fc01d94d8207df378d7aa94757c181bd49/src/components/DataEntry/DataEntryTable/DataEntryTable.tsx#L131

https://github.com/sillsdev/TheCombine/blob/c4c155fc01d94d8207df378d7aa94757c181bd49/src/components/DataEntry/spellChecker.ts#L8

https://github.com/sillsdev/TheCombine/blob/c4c155fc01d94d8207df378d7aa94757c181bd49/src/index.tsx#L16

https://github.com/sillsdev/TheCombine/blob/c4c155fc01d94d8207df378d7aa94757c181bd49/src/index.tsx#L23

(More usages in tests).

Should search the project for these types of duplicated strings and define them in a single place to avoid typos and DRY issues.

### PR DESCRIPTION
**Pull request by johnthagen**
Closes #1547

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1553)

### CODE REVIEW

**Comment by imnasnainaec** [comment]
I'd like to take this one step further, with #1546 in mind. I envision migrating writing-system-related definitions and lists out of https://github.com/sillsdev/TheCombine/blob/master/src/components/TreeView/TreeViewComponent.tsx so that any supported languages' writing systems are in the `types` for reference from the test files. Since Jason is actively working in related TreeView data loading, perhaps we can put this pr into draft until that is done.

**Comment by imnasnainaec** [comment]
The crux of this pr is https://github.com/sillsdev/TheCombine/blob/english-ws-const/src/types/writingSystem.ts

**Comment by johnthagen** [comment]
___
*[src/types/writingSystem.ts, line 3 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1553#-MxL3gp_3gGCpwJ4CCJc:-MxL3gp_3gGCpwJ4CCJd:b-z9h2kv) ([raw file](https://github.com/sillsdev/thecombine/blob/c4b3a0815125c8e2f0a8816192c13c9dd7dc1f75/src/types/writingSystem.ts#L3)):*
> ```XML
> import { WritingSystem } from "api/models";
> 
> export enum langCode {
> ```

Our style is to capitalize `enum`s:

```
export enum LangCode
```

**Comment by johnthagen** [comment]
___
*[src/types/writingSystem.ts, line 3 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1553#-MxL42L-70TKKBKY1xA8:-MxL42L00tUe5DVvAe_O:b-x63g08) ([raw file](https://github.com/sillsdev/thecombine/blob/c4b3a0815125c8e2f0a8816192c13c9dd7dc1f75/src/types/writingSystem.ts#L3)):*
> ```XML
> import { WritingSystem } from "api/models";
> 
> export enum langCode {
> ```

Should we add a doc comment that these are BCP47 codes?

**Comment by johnthagen** [comment]
___
*[src/types/writingSystem.ts, line 3 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1553#-MxL42L-70TKKBKY1xA8:-MxL49ka-ksNeLPXwSDa:b-xywakp) ([raw file](https://github.com/sillsdev/thecombine/blob/c4b3a0815125c8e2f0a8816192c13c9dd7dc1f75/src/types/writingSystem.ts#L3)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Should we add a doc comment that these are BCP47 codes?
</blockquote></details>

Perhaps even changing the `enum` name to `Bcp47Code` ?

**Review by johnthagen — COMMENTED** [review]
> Reviewed 1 of 5 files at r2, 21 of 21 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1553)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by jmgrady — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1553)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
