### PR TITLE
Add segment.com analytics tracking to The Combine

### PR DESCRIPTION
**Pull request by jasonleenaylor**
Our goal is to get a sense of how many users The Combine sees and what features they are using. Also we will eventually track app stability by tracking errors versus launches. This commit introduces [Segment.com](https://segment.com/docs/getting-started/01-what-is-segment/) to The Combine.

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1108)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[.env, line 2 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1108#-MYQ70EiEM8GCQvwvMhF:-MYQ70EjA7D7vHyU3Tlw:bvdp6gu) ([raw file](https://github.com/sillsdev/thecombine/blob/9861aa4f54fbfadb62f526c5ef46f481ce7faa2c/.env#L2)):*
> ```Shell
> REACT_APP_VERSION=$npm_package_version
> REACT_APP_ANALYTICS_WRITE_KEY=WoE6Qf2AeEUdQMQZBd0PpqSztHQYWRxj
> ```

Is it okay that this is public and static? (e.g. if someone copies this value can they do anything disruptivee?)

**Comment by johnthagen** [comment]
___
*[deploy/group_vars/qa/main.yml, line 8 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1108#-MYQ7CMU6cniK9Az4r6H:-MYQ7CMU6cniK9Az4r6I:bw5mpg7) ([raw file](https://github.com/sillsdev/thecombine/blob/9861aa4f54fbfadb62f526c5ef46f481ce7faa2c/deploy/group_vars/qa/main.yml#L8)):*
> ```YAML
> #################################################
> 
> config_analytics_write_key: "WoE6Qf2AeEUdQMQZBd0PpqSztHQYWRxj"
> ```

Is it okay  that this value is public and static?

**Comment by johnthagen** [comment]
___
*[deploy/group_vars/server/main.yml, line 8 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1108#-MYQ7J0i6rOxmZN6R6pu:-MYQ7J0i6rOxmZN6R6pv:b-fs2esv) ([raw file](https://github.com/sillsdev/thecombine/blob/9861aa4f54fbfadb62f526c5ef46f481ce7faa2c/deploy/group_vars/server/main.yml#L8)):*
> ```YAML
> #################################################
> 
> config_analytics_write_key: "WoE6Qf2AeEUdQMQZBd0PpqSztHQYWRxj"
> ```

Is it okay that this is public?

**Comment by johnthagen** [comment]
___
*[public/index.html, line 9 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1108#-MYQ8L6Z5dqY0QGD86to:-MYQ8L6Z5dqY0QGD86tp:b-qxjpf4) ([raw file](https://github.com/sillsdev/thecombine/blob/9861aa4f54fbfadb62f526c5ef46f481ce7faa2c/public/index.html#L9)):*
> ```HTML
>     <meta name="theme-color" content="#000000" />
>     <script src="%PUBLIC_URL%/scripts/config.js"></script>
>     
> ```

Could we have a reference to the docs where this code is copied from, so that if/when the recommended code changes it's easier to find where to pull it in from?

**Comment by johnthagen** [comment]
___
*[src/browserHistory.ts, line 1 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1108#-MYQ9RoL2k2yTIJvtoJZ:-MYQ9RoL2k2yTIJvtoJ_:b-v9x46y) ([raw file](https://github.com/sillsdev/thecombine/blob/9861aa4f54fbfadb62f526c5ef46f481ce7faa2c/src/browserHistory.ts#L1)):*
> ```XML
> import { createBrowserHistory } from "history";
> ```

A meta-comment, but do we need to disclose at all that we are sending user data/metrics to a third-party service?

Made me think of [GDRP](https://gdpr-info.eu/).

**Comment by johnthagen** [comment]
___
*[src/browserHistory.ts, line 12 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1108#-MYQ9wpA0LktA5EYHf0o:-MYQ9wpA0LktA5EYHf0p:b-d2cc0y) ([raw file](https://github.com/sillsdev/thecombine/blob/9861aa4f54fbfadb62f526c5ef46f481ce7faa2c/src/browserHistory.ts#L12)):*
> ```XML
> let history = createBrowserHistory();
> // set up analytics for page navigation
> let prevPath = "";
> ```

I think it's okay, but just to clarify, `prevPath` is a mutable Global variable? Is this something we want to track in Redux instead?

**Review by jasonleenaylor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1108)* status: 0 of 13 files reviewed, 6 unresolved discussions (waiting on @imnasnainaec, @jasonleenaylor, and @johnthagen)

___
*[.env, line 2 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1108#-MYQ70EiEM8GCQvwvMhF:-MYQ8Gf070p3Fgr6P1i6:b-y9ijxd) ([raw file](https://github.com/sillsdev/thecombine/blob/9861aa4f54fbfadb62f526c5ef46f481ce7faa2c/.env#L2)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Is it okay that this is public and static? (e.g. if someone copies this value can they do anything disruptivee?)
</blockquote></details>

Yes, it is ok. Someone could technically send a bunch of junk through our analytics, but this key will eventually be used only for our development account. I have been pondering how closely we need to keep the key that we use for production (right now everything is using the same key). Many other projects using segment have made no effort to hide this key. In a worst case scenario someone malicious could use this key to generate a large number of tracking events with different users and disrupt our analytics forcing us to generate a new key and get more serious about keeping it secret.

**Comment by johnthagen** [comment]
___
*[src/components/Login/LoginActions.tsx, line 7 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1108#-MYQBAG_AXs_DXq1BhJe:-MYQBAG_AXs_DXq1BhJf:b-xn11v6) ([raw file](https://github.com/sillsdev/thecombine/blob/9861aa4f54fbfadb62f526c5ef46f481ce7faa2c/src/components/Login/LoginActions.tsx#L7)):*
> ```XML
> import { StoreStateDispatch } from "types/actions";
> import { User } from "types/user";
> import hash from "crypto";
> ```

Where is this dependency listed/pinned? I can't find it in `package.json`.

When I navigate to the module via Rider, I see `node/crypto.d.ts`. Is this something `node` brings? If so, how does this get bundled for the client?

**Comment by johnthagen** [comment]
___
*[src/components/Login/LoginActions.tsx, line 7 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1108#-MYQBAG_AXs_DXq1BhJe:-MYQEymW02Nzfy9QRgzQ:bdlipoz) ([raw file](https://github.com/sillsdev/thecombine/blob/9861aa4f54fbfadb62f526c5ef46f481ce7faa2c/src/components/Login/LoginActions.tsx#L7)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Where is this dependency listed/pinned? I can't find it in `package.json`.

When I navigate to the module via Rider, I see `node/crypto.d.ts`. Is this something `node` brings? If so, how does this get bundled for the client?
</blockquote></details>

I want to make sure we aren't relying on a transitive dependency that might only be installed as a side effect of something else.

**Review by johnthagen — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 6 of 6 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1108)* status: all files reviewed, 7 unresolved discussions (waiting on @imnasnainaec, @jasonleenaylor, and @johnthagen)

**Review by jasonleenaylor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1108)* status: all files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @johnthagen)

___
*[public/index.html, line 9 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1108#-MYQ8L6Z5dqY0QGD86to:-MYQUPEU7RvK0OviSp5W:b6fbbmk) ([raw file](https://github.com/sillsdev/thecombine/blob/9861aa4f54fbfadb62f526c5ef46f481ce7faa2c/public/index.html#L9)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Could we have a reference to the docs where this code is copied from, so that if/when the recommended code changes it's easier to find where to pull it in from?
</blockquote></details>

Yes, I'll add that.
___
*[src/browserHistory.ts, line 1 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1108#-MYQ9RoL2k2yTIJvtoJZ:-MYQUY5w4Az_XKOLeQbM:b-185f5e) ([raw file](https://github.com/sillsdev/thecombine/blob/9861aa4f54fbfadb62f526c5ef46f481ce7faa2c/src/browserHistory.ts#L1)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

A meta-comment, but do we need to disclose at all that we are sending user data/metrics to a third-party service?

Made me think of [GDRP](https://gdpr-info.eu/).
</blockquote></details>

Yeah, I've been thinking that through also.  I had planned to cover that through a privacy link to the landing page that Danny will be working on soon.
___
*[src/browserHistory.ts, line 12 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1108#-MYQ9wpA0LktA5EYHf0o:-MYRNLYiDQtEtX5g1WJI:b-xlt5qj) ([raw file](https://github.com/sillsdev/thecombine/blob/9861aa4f54fbfadb62f526c5ef46f481ce7faa2c/src/browserHistory.ts#L12)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I think it's okay, but just to clarify, `prevPath` is a mutable Global variable? Is this something we want to track in Redux instead?
</blockquote></details>

I suppose we could. That does seem a bit more principled, I'll look into it some more on Monday. 
___
*[src/components/Login/LoginActions.tsx, line 7 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1108#-MYQBAG_AXs_DXq1BhJe:-MYQUy-i8KeQuKgaJ9mo:b-b74qf) ([raw file](https://github.com/sillsdev/thecombine/blob/9861aa4f54fbfadb62f526c5ef46f481ce7faa2c/src/components/Login/LoginActions.tsx#L7)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I want to make sure we aren't relying on a transitive dependency that might only be installed as a side effect of something else.
</blockquote></details>

https://nodejs.org/api/crypto.html

**Comment by johnthagen** [comment]
___
*[src/components/Login/LoginActions.tsx, line 7 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1108#-MYQBAG_AXs_DXq1BhJe:-MYUvtNVEW0YeXyljyxH:b-5f4x7k) ([raw file](https://github.com/sillsdev/thecombine/blob/9861aa4f54fbfadb62f526c5ef46f481ce7faa2c/src/components/Login/LoginActions.tsx#L7)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

https://nodejs.org/api/crypto.html
</blockquote></details>

Is `node` an implicit dependency of everything that is built with `npm`? I'm still haven't a difficult time finding how this is actually included in our project. I see ` "@types/node": "^14.14.25"` but not `node` or `node/crypto` itself. Mostly curious to learn how this is working.

**Review by jasonleenaylor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1108)* status: 3 of 13 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @johnthagen)

___
*[public/index.html, line 9 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1108#-MYQ8L6Z5dqY0QGD86to:-MYpQItlCwD-A0ckTCBq:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/9861aa4f54fbfadb62f526c5ef46f481ce7faa2c/public/index.html#L9)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Yes, I'll add that.
</blockquote></details>

Done.
___
*[src/browserHistory.ts, line 12 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1108#-MYQ9wpA0LktA5EYHf0o:-MYpQKPT1UUF2fM-FmaO:b-b61osr) ([raw file](https://github.com/sillsdev/thecombine/blob/9861aa4f54fbfadb62f526c5ef46f481ce7faa2c/src/browserHistory.ts#L12)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

I suppose we could. That does seem a bit more principled, I'll look into it some more on Monday. 
</blockquote></details>

This change points out a problem with how we have combined our type definitions and reducer functions. It has triggered a major refactor that will come in a follow up commit.
___
*[src/components/Login/LoginActions.tsx, line 7 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1108#-MYQBAG_AXs_DXq1BhJe:-MYpQXOG8tTyJVjpjpDC:bjs9rm7) ([raw file](https://github.com/sillsdev/thecombine/blob/9861aa4f54fbfadb62f526c5ef46f481ce7faa2c/src/components/Login/LoginActions.tsx#L7)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Is `node` an implicit dependency of everything that is built with `npm`? I'm still haven't a difficult time finding how this is actually included in our project. I see ` "@types/node": "^14.14.25"` but not `node` or `node/crypto` itself. Mostly curious to learn how this is working.
</blockquote></details>

Hmm, you're right it is interesting. We should do some research and make sure we aren't setting up for future failures.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 5 of 6 files at r5, 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1108)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @jmgrady and @johnthagen)

___
*[public/index.html, line 9 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1108#-MYQ8L6Z5dqY0QGD86to:-MYpW78cBfoJazyquZwv:b-vn3zvd) ([raw file](https://github.com/sillsdev/thecombine/blob/9861aa4f54fbfadb62f526c5ef46f481ce7faa2c/public/index.html#L9)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/quickstart/#step-2-copy-the-segment-snippet ?

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1108)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[public/index.html, line 9 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1108#-MYQ8L6Z5dqY0QGD86to:-MYqDfVDBNuYzMaq3WSh:bry7u3n) ([raw file](https://github.com/sillsdev/thecombine/blob/9861aa4f54fbfadb62f526c5ef46f481ce7faa2c/public/index.html#L9)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/quickstart/#step-2-copy-the-segment-snippet ?
</blockquote></details>

Consider adding text that the code is modified to get the key form `window.runtimeConfig` if it exists.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1108)* status: all files reviewed, 1 unresolved discussion (waiting on @johnthagen)

**Review by jmgrady — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1108#-:-MYur-1aB2g49yr9qXRA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @johnthagen)

**Review by jmgrady — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1108)* status: all files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[public/index.html, line 9 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1108#-MYQ8L6Z5dqY0QGD86to:-MYur51s9dybqrpr5Su0:bb6ywmx) ([raw file](https://github.com/sillsdev/thecombine/blob/9861aa4f54fbfadb62f526c5ef46f481ce7faa2c/public/index.html#L9)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Consider adding text that the code is modified to get the key form `window.runtimeConfig` if it exists.
</blockquote></details>

LGTM

**Review by jasonleenaylor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1108)* status: all files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[public/index.html, line 9 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1108#-MYQ8L6Z5dqY0QGD86to:-MYugbJa3nG6lgtt9eYO:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/9861aa4f54fbfadb62f526c5ef46f481ce7faa2c/public/index.html#L9)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Consider adding text that the code is modified to get the key form `window.runtimeConfig` if it exists.
</blockquote></details>

Done.

**Pull request merged**
