### PR TITLE
[Review Entries] Refactor table with `material-react-table`

### LINKED ISSUE #2875: [ReviewEntries] Refactor table with Material React Table
Switch from `@material-table/core` to `material-react-table`, which is better maintained and more customizable. Also, the usage of the latter is just surpassing that of the former.

This refactor clears up a backlog of issues with the `ReviewEntriesTable`:
- [x] #1076
- [x] #1421
- [x] #1199 & #1725 
  - [x]  In view mode, separate with semicolons rather than horizontal lines, to avoid the problem of unaligned subrows
  - [x]  In edit mode, use modal editing with a different editable item for each sense
- [x] #1939 
- [x] #2616 
- [x] #2642 
- [x] #2674

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #2875

Requires #2876 

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2881)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
*[`src/goals/ReviewEntries/ReviewEntriesTable/index.tsx` line 36 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2881#-NujeO2W4axStdcw17MG:-NujeO2W4axStdcw17MH:b-dg2oci) ([raw file](https://github.com/sillsdev/TheCombine/blob/8854d7309ab4925181e6db67904d65faf042cf47/src/goals/ReviewEntries/ReviewEntriesTable/index.tsx#L36)):*
> ```XML
>   switch (lang) {
>     case "ar":
>       return (await import("material-react-table/locales/ar"))
> ```

Consider if we can or want to use i18next getResource here just to keep our localizations all in one place and usable by crowdin.

**Comment by jasonleenaylor** [comment]
*[`src/goals/ReviewEntries/ReviewEntriesTable/index.tsx` line 36 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2881#-NujeO2W4axStdcw17MG:-Nv2SgIn0B_Ff01G6aIT:byma0uc) ([raw file](https://github.com/sillsdev/TheCombine/blob/8854d7309ab4925181e6db67904d65faf042cf47/src/goals/ReviewEntries/ReviewEntriesTable/index.tsx#L36)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

The way `material-react-table` uses localization data (e.g., https://github.com/KevinVandy/material-react-table/blob/v2/packages/material-react-table/src/components/menus/MRT_RowActionMenu.tsx#L62), it seems that if we did load their localizations into `i18n`, we'd then have to extract them from `i18n` to manually feed into the table's `localization` prop.
</blockquote></details>

Yes, that is what I was seeing as well. It seems that what you have here is probably the cleanest choice.

**Comment by jasonleenaylor** [comment]
*[`src/goals/ReviewEntries/ReviewEntriesTable/Cells/EditCell/EditSenseDialog.tsx` line 143 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2881#-Nv2UqgsEcEwrrcRJN_H:-Nv2Uqgt9nwak54rc8Z1:b-hlfc06) ([raw file](https://github.com/sillsdev/TheCombine/blob/8854d7309ab4925181e6db67904d65faf042cf47/src/goals/ReviewEntries/ReviewEntriesTable/Cells/EditCell/EditSenseDialog.tsx#L143)):*
> ```XML
>     const cleanedSense = cleanSense(newSense);
>     if (!cleanedSense || typeof cleanedSense === "string") {
>       toast.error(t(cleanedSense ?? ""));
> ```

I'm not sure I like the multiple return type approach. 
Another option is to have cleanSense take two functions, one to execute on error and one to execute on success.

There are probably others. The current choice has us checking conditions twice, checking the state to choose a return type and checking the return type to determine the action.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2881)* status: 85 of 86 files reviewed, 2 unresolved discussions (waiting on @jasonleenaylor)

___
*[`src/goals/ReviewEntries/ReviewEntriesTable/Cells/EditCell/EditSenseDialog.tsx` line 143 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2881#-Nv2UqgsEcEwrrcRJN_H:-Nv75-D_AYKNwCNN18pF:b3t8aka) ([raw file](https://github.com/sillsdev/TheCombine/blob/8854d7309ab4925181e6db67904d65faf042cf47/src/goals/ReviewEntries/ReviewEntriesTable/Cells/EditCell/EditSenseDialog.tsx#L143)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

I'm not sure I like the multiple return type approach. 
Another option is to have cleanSense take two functions, one to execute on error and one to execute on success.

There are probably others. The current choice has us checking conditions twice, checking the state to choose a return type and checking the return type to determine the action.
</blockquote></details>

This logic was carried over from the old functions, but I'll look into updating it.
___
*[`src/goals/ReviewEntries/ReviewEntriesTable/Cells/EditCell/index.tsx` line 10 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2881#-Nv2WY7m6yQp0nrl-wHG:-Nv766ko46pUJ5HNxi1v:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/8854d7309ab4925181e6db67904d65faf042cf47/src/goals/ReviewEntries/ReviewEntriesTable/Cells/EditCell/index.tsx#L10)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

So, DeleteCell returns an Edit cell...
</blockquote></details>

Done.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2881)* status: 85 of 86 files reviewed, 2 unresolved discussions (waiting on @jasonleenaylor)

___
*[`src/goals/ReviewEntries/ReviewEntriesTable/Cells/EditCell/EditDialog.tsx` line 135 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2881#-Nv2ITPT7EWPnBTEabCz:-Nv79BB4BHFBKff8XwQ0:bdmz1ej) ([raw file](https://github.com/sillsdev/TheCombine/blob/8854d7309ab4925181e6db67904d65faf042cf47/src/goals/ReviewEntries/ReviewEntriesTable/Cells/EditCell/EditDialog.tsx#L135)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

There are some pros and cons to doing this here, I think I like it though. The con is a possible delay between the user change and the state updating, make sure there is no race condition on a keyboard change and accept.
</blockquote></details>

Oh, good consideration! To accept changes with the keyboard, one has to tab to the check button and then press Enter. With no async updates in this dialog, I don't see keyboard race conditions as an issue.

**Review by jasonleenaylor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2881#-:-Nv7bcvgBva2o7g1ncqt:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[`src/goals/ReviewEntries/ReviewEntriesTable/Cells/EditCell/EditSenseDialog.tsx` line 143 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2881#-Nv2UqgsEcEwrrcRJN_H:-Nv7bLib5zlAix-PmbkA:b-bdcu5i) ([raw file](https://github.com/sillsdev/TheCombine/blob/8854d7309ab4925181e6db67904d65faf042cf47/src/goals/ReviewEntries/ReviewEntriesTable/Cells/EditCell/EditSenseDialog.tsx#L143)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

This logic was carried over from the old functions, but I'll look into updating it.
</blockquote></details>

This can be handled in a follow up PR since it was pre-existing code.

**Pull request merged**
