### PR TITLE
Allow upgrades to docker-compose

### LINKED ISSUE #562: Upgrade docker-compose when new version required
Currently `docker-compose` is not maintained in an ubuntu software repository nor in a PPA so Ansible can only detect whether it is installed or not.  The playbooks need to be updated to check the version of the installed `docker-compose` and force an update if warranted.

### PR DESCRIPTION
**Pull request by jmgrady**
Also, bump the following versions:
 - docker-compose: 1.28.4
 - aws-cli: 2.1.28

Closes #562

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1048)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[deploy/vars/packages.yml, line 12 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1048#-MUV7WZv3WS-fvFgUZCm:-MUV7WZv3WS-fvFgUZCn:bt3i410) ([raw file](https://github.com/sillsdev/thecombine/blob/ef09ba96bdbf9365677e44c276471ca8201cc467/deploy/vars/packages.yml#L12)):*
> ```YAML
> 
> # Packages installed by playbook_docker.yml
> docker_compose_version: 1.28.4
> ```

It looks like there is a `1.28.5` out: https://github.com/docker/compose/releases

**Review by johnthagen — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1048)* status: all files reviewed, 1 unresolved discussion (waiting on @jmgrady)

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1048)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[deploy/vars/packages.yml, line 12 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1048#-MUV7WZv3WS-fvFgUZCm:-MUV9r1-1ul6t8z5_MoT:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/5e14ae3614c6afcaa2cba305e8dcfefd1efb0be8/deploy/vars/packages.yml#L12)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

It looks like there is a `1.28.5` out: https://github.com/docker/compose/releases
</blockquote></details>

Done.

**Review by johnthagen — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1048)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
