### PR TITLE
Upgrade backend to .NET 5

### LINKED ISSUE #1149: Migrate away from deprecated Newtonsoft JSON serializer
When we upgraded to .NET Core 3.x (#324), the app failed to work under the new default JSON serializer included with ASP .NET Core (`System.Text.JSON`). This was likely due to actual bugs in how the frontend was sending data.

https://github.com/sillsdev/TheCombine/blob/e5d9e67dc031c60bcf86c8106b4862d434770365/Backend/BackendFramework.csproj#L16

https://github.com/sillsdev/TheCombine/blob/e5d9e67dc031c60bcf86c8106b4862d434770365/Backend/Startup.cs#L140-L145

This should be removed and we should migrate back to the default JSON serializer.

### LINKED ISSUE #1200: Upgrade backend to .NET 5
Update backend to .NET 5, targeting this for late July.

This will also allow for C# 9.0 and new language features like `obj is not null`.

### PR DESCRIPTION
**Pull request by johnthagen**
Closes #1200 
Closes #1149 

- Update to C# 9.0
  - Use new `is not null` syntax
- Disable ASP.NET Razor page configuration by switching to `AddControllersWithViews()`, which is not used by The Combine, as recommended for ASP.NET Core 3+ (https://stackoverflow.com/questions/62251347)
- Remove SetCompatibilityVersion no-op (https://stackoverflow.com/a/59748346)
- Port to `System.Text.Json` for all JSON serialization into and out of API endpoints (default for ASP.NET Core 3.0+) (#1149)
- Set some class attributes used for serialization to properties (`get`/`set`) to enable proper discovery during OpenAPI schema generation
- Replace C# LGTM usage with a GitHub Action that uses the same underlying [CodeQL engine](https://github.com/github/codeql-action)

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1198)

### CODE REVIEW

**Comment by johnthagen** [comment]
Out of the box, three Models did not get generated after switching to the new default JSON seriazlier:

- `EmailInviteStatus`
- `SemanticDomainWithSubdomains`
- `MergeSourceWord`

**Comment by johnthagen** [comment]
.NET 5 has an improved JSON Serializer: #1200

This would allow us to avoid some limitations with the current serializer:

```
System.NotSupportedException: Deserialization of reference types without parameterless constructor is not supported. Type 'BackendFramework.Models.UserEditStepWrapper'
```

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 10 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1198)* status: 10 of 13 files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[docs/user_guide/docs/licenses/backend_licenses.txt, line 92 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1198#-McVFrLc-awpPPYjOmkT:-McVFrLc-awpPPYjOmkU:b-bbwppu) ([raw file](https://github.com/sillsdev/thecombine/blob/3df26713f7286eca49d68c604caeae21bdc82838/docs/user_guide/docs/licenses/backend_licenses.txt#L92)):*
> ```
> Version:2.1.0
> ```

Hmm, this is confusing a couple of ways.
1. Just above we are including the license for version 2.2.0 Given my experience with .Net assembly references we almost certainly aren't using both.
2. I guess the package versions here don't actually match the asp.net version? So these new ones presumably appeared from the use of `System.Text.Json.Serialization`?

**Comment by johnthagen** [comment]
___
*[docs/user_guide/docs/licenses/backend_licenses.txt, line 92 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1198#-McVFrLc-awpPPYjOmkT:-McVIHCR-2o5pxrfjYBe:bu0rkgp) ([raw file](https://github.com/sillsdev/thecombine/blob/3df26713f7286eca49d68c604caeae21bdc82838/docs/user_guide/docs/licenses/backend_licenses.txt#L92)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> Version:2.1.0
> ```

Hmm, this is confusing a couple of ways.
1. Just above we are including the license for version 2.2.0 Given my experience with .Net assembly references we almost certainly aren't using both.
2. I guess the package versions here don't actually match the asp.net version? So these new ones presumably appeared from the use of `System.Text.Json.Serialization`?

</blockquote></details>

We're including `--include-transitive` in the `dotnet-project-licenses` command, so that might have something to do with it? Due to how the dependencies are described in C# packages, it might be difficult for a license checker looking from the side to know how the final linking happens. Perhaps that is why there is duplication?

**Comment by jasonleenaylor** [comment]
___
*[Backend/Controllers/UserController.cs, line 41 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1198#-McVTNeF-xT8H64kZpfu:-McVTNeGCtNfgaBd97o5:bhchms2) ([raw file](https://github.com/sillsdev/thecombine/blob/42fe6bbf7d42e3be2874e49b441cbd0b38aea51d/Backend/Controllers/UserController.cs#L41)):*
> ```
> [ProducesResponseType(StatusCodes.Status200OK)]
> ``

Do we need to add 404 here now?

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 5 of 16 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1198)* status: 14 of 27 files reviewed, all discussions resolved (waiting on @imnasnainaec and @jasonleenaylor)

___
*[docs/user_guide/docs/licenses/backend_licenses.txt, line 92 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1198#-McVFrLc-awpPPYjOmkT:-McVTsQd46BZ3U2v2JM0:bnptxvm) ([raw file](https://github.com/sillsdev/thecombine/blob/3df26713f7286eca49d68c604caeae21bdc82838/docs/user_guide/docs/licenses/backend_licenses.txt#L92)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

We're including `--include-transitive` in the `dotnet-project-licenses` command, so that might have something to do with it? Due to how the dependencies are described in C# packages, it might be difficult for a license checker looking from the side to know how the final linking happens. Perhaps that is why there is duplication?
</blockquote></details>

Perhaps, and the change to 5.0 didn't really change this. :man_shrugging:

**Comment by johnthagen** [comment]
___
*[Backend/Controllers/UserController.cs, line 41 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1198#-McVTNeF-xT8H64kZpfu:-McVXfqO-RAjqEn6U-kr:b-7ej6p8) ([raw file](https://github.com/sillsdev/thecombine/blob/42fe6bbf7d42e3be2874e49b441cbd0b38aea51d/Backend/Controllers/UserController.cs#L41)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> [ProducesResponseType(StatusCodes.Status200OK)]
> ``

Do we need to add 404 here now?
</blockquote></details>

Per discussions with @imnasnainaec documenting non-200 responses is of pretty low value because it doesn't change the generated type script code. It ends up being a bunch of bookkeeping without any real value.

@imnasnainaec Please correct me if I'm mischaracterizing our conclusion about this.

**Comment by johnthagen** [comment]
Some LGTM logs:

```
[2021-06-18 18:55:19] [build-stdout]   /usr/lib/mono/msbuild/Current/bin/NuGet.targets(128,5): error : Package SIL.Core.Desktop 8.0.0 is not compatible with net5.0 (.NETCoreApp,Version=v5.0). Package SIL.Core.Desktop 8.0.0 supports: net461 (.NETFramework,Version=v4.6.1) [/opt/src/BackendFramework.sln]
[2021-06-18 18:55:19] [build-stdout]   /usr/lib/mono/msbuild/Current/bin/NuGet.targets(128,5): error : Package SIL.DictionaryServices 8.0.0 is not compatible with net5.0 (.NETCoreApp,Version=v5.0). Package SIL.DictionaryServices 8.0.0 supports: net461 (.NETFramework,Version=v4.6.1) [/opt/src/BackendFramework.sln]
[2021-06-18 18:55:19] [build-stdout]   /usr/lib/mono/msbuild/Current/bin/NuGet.targets(128,5): error : Package SIL.Lift 8.0.0 is not compatible with net5.0 (.NETCoreApp,Version=v5.0). Package SIL.Lift 8.0.0 supports: net461 (.NETFramework,Version=v4.6.1) [/opt/src/BackendFramework.sln]
[2021-06-18 18:55:19] [build-stdout]   /usr/lib/mono/msbuild/Current/bin/NuGet.targets(128,5): error : Package SIL.Core.Desktop 8.0.0 is not compatible with net5.0 (.NETCoreApp,Version=v5.0). Package SIL.Core.Desktop 8.0.0 supports: net461 (.NETFramework,Version=v4.6.1) [/opt/src/BackendFramework.sln]
[2021-06-18 18:55:19] [build-stdout]   /usr/lib/mono/msbuild/Current/bin/NuGet.targets(128,5): error : Package SIL.DictionaryServices 8.0.0 is not compatible with net5.0 (.NETCoreApp,Version=v5.0). Package SIL.DictionaryServices 8.0.0 supports: net461 (.NETFramework,Version=v4.6.1) [/opt/src/BackendFramework.sln]
[2021-06-18 18:55:19] [build-stdout]   /usr/lib/mono/msbuild/Current/bin/NuGet.targets(128,5): error : Package SIL.Lift 8.0.0 is not compatible with net5.0 (.NETCoreApp,Version=v5.0). Package SIL.Lift 8.0.0 supports: net461 (.NETFramework,Version=v4.6.1) [/opt/src/BackendFramework.sln]
[2021-06-18 18:55:19] [build-stdout]     0 Warning(s)
[2021-06-18 18:55:19] [build-stdout]     6 Error(s)
```

**Comment by johnthagen** [comment]
@jasonleenaylor If we decide to accept this PR, the following administrative steps will need to be performed:

- [ ] Disable C# LGTM analysis: https://help.semmle.com/lgtm-enterprise/admin/help/disabling-analysis-language.html
- [ ] Disable LGTM C# as a required PR check. Settings | Branches | Branch Protection Rules | Status checks that are required | Remove LGTM analysis: C#
  - (I can do this if granted temporary admin of TheCombine)

**Comment by johnthagen** [comment]
We may want to include some of the additional queries that CodeQL supports, but this does risk having more false positives:

<html>
<body>


security-extended | Queries of lower severity and precision than the default queries
-- | --
security-and-quality | Queries from security-extended, plus maintainability and reliability queries


</body>
</html>

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 1 of 13 files at r3, 10 of 16 files at r4, 2 of 2 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1198)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1198)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
