### PR TITLE
Run prettier on the docs folder and on md files.

### PR DESCRIPTION
**Pull request by imnasnainaec**
The meat of this pr is the change to `fmt-frontend` and `fmt-frontend-check` in `package.json`--the other files were modified as a consequence.

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/829)

### CODE REVIEW

**Review by jmgrady — APPROVED** [review]
> Reviewed 14 of 15 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/829)* status: all files reviewed, 4 unresolved discussions (waiting on @imnasnainaec)

___
*[package.json, line 15 at r2](https://reviewable.io/reviews/sillsdev/thecombine/829#-MNPSOe_4FUom5dPa-Af:-MNPSOe_4FUom5dPa-Ag:bhl5dkl) ([raw file](https://github.com/sillsdev/thecombine/blob/be1526b2a89f01c86b08b05b33e0987575b55e69/package.json#L15)):*
> ```
>     "fmt-frontend": "prettier --write \"./{.vscode,docs,public,scripts,src}/**/*.{js,jsx,ts,tsx,json,md}\"",
>     "fmt-frontend-check": "prettier --check \"./{.vscode,docs,public,scripts,src}/**/*.{js,jsx,ts,tsx,json,md}\"",
> ```
It appears to me that this will not format/check the main project Read Me document, `./README.md`
___
*[docs/api/projects/user_edits/goal_type.md, line 16 at r2](https://reviewable.io/reviews/sillsdev/thecombine/829#-MNPT4rLB1tj-0vZxdx8:-MNPT4rLB1tj-0vZxdx9:b1rgtis) ([raw file](https://github.com/sillsdev/thecombine/blob/be1526b2a89f01c86b08b05b33e0987575b55e69/docs/api/projects/user_edits/goal_type.md#L16)):*
> ```
>    HandleFlags
> ```
Why did _prettier_ add a trailing comma to the last enumeration item in `ts_style_guide.md` but not here?
___
*[docs/api/projects/words/sense.md, line 3 at r2](https://reviewable.io/reviews/sillsdev/thecombine/829#-MNPUOBD43v2wTLE8IaC:-MNPUOBD43v2wTLE8IaD:bt7gje) ([raw file](https://github.com/sillsdev/thecombine/blob/be1526b2a89f01c86b08b05b33e0987575b55e69/docs/api/projects/words/sense.md#L3)):*
> ```Markdown
> # Sense
> 
> A word have multiple senses, like the word bank,
> ```

Shouldn't this be "A word _may_ have multiple senses..."?
___
*[docs/docker_deploy/README.md, line 168 at r2](https://reviewable.io/reviews/sillsdev/thecombine/829#-MNPVDuXEh4BUq8_qhKQ:-MNPVDuXEh4BUq8_qhKR:brz2umi) ([raw file](https://github.com/sillsdev/thecombine/blob/be1526b2a89f01c86b08b05b33e0987575b55e69/docs/docker_deploy/README.md#L168)):*
> ```Markdown
> If the ansible variables `backup_hours` and `backup_minutes` are defined for a
> target, then `cron` will be setup to create a backup of _TheCombine_ database and
> backend files every day at the specified times. The hours/minutes can be set to
> ```

I disagree with the collapse of 2 spaces to 1 following a period.  That is standard practice with a typewriter and, in my opinion, makes the source (which looks like a typed page) easier to read.  The page renderer should format it according to typography rules.  Is it possible to configure prettier to ignore this?  I also prefer the *italic* to _italic_ but I am fine with either.

**Review by jmgrady — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/829#-:-MNPguFH5TLhA3Scxhug:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/829)* status: 14 of 15 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[package.json, line 15 at r2](https://reviewable.io/reviews/sillsdev/thecombine/829#-MNPSOe_4FUom5dPa-Af:-MNPq0yj32zuG2iVXMbS:b-3ij3r1) ([raw file](https://github.com/sillsdev/thecombine/blob/989138df801b6c44471c35c521804797fa5726c2/package.json#L15)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

> ```
>     "fmt-frontend": "prettier --write \"./{.vscode,docs,public,scripts,src}/**/*.{js,jsx,ts,tsx,json,md}\"",
>     "fmt-frontend-check": "prettier --check \"./{.vscode,docs,public,scripts,src}/**/*.{js,jsx,ts,tsx,json,md}\"",
> ```
It appears to me that this will not format/check the main project Read Me document, `./README.md`
</blockquote></details>

Correct. There are some folders that we don't want to check, so this simple pattern hasn't been applied to the root folder where our main README resides.
___
*[docs/api/projects/user_edits/goal_type.md, line 16 at r2](https://reviewable.io/reviews/sillsdev/thecombine/829#-MNPT4rLB1tj-0vZxdx8:-MNPpSNj830EcauYRxmA:b9r535x) ([raw file](https://github.com/sillsdev/thecombine/blob/989138df801b6c44471c35c521804797fa5726c2/docs/api/projects/user_edits/goal_type.md#L16)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

> ```
>    HandleFlags
> ```
Why did _prettier_ add a trailing comma to the last enumeration item in `ts_style_guide.md` but not here?
</blockquote></details>

Maybe because those are named enums? I'm not sure.
___
*[docs/api/projects/words/sense.md, line 3 at r2](https://reviewable.io/reviews/sillsdev/thecombine/829#-MNPUOBD43v2wTLE8IaC:-MNPprxiByau346d-TmX:bt2vr1b) ([raw file](https://github.com/sillsdev/thecombine/blob/989138df801b6c44471c35c521804797fa5726c2/docs/api/projects/words/sense.md#L3)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Shouldn't this be "A word _may_ have multiple senses..."?
</blockquote></details>

Fixed.
___
*[docs/docker_deploy/README.md, line 168 at r2](https://reviewable.io/reviews/sillsdev/thecombine/829#-MNPVDuXEh4BUq8_qhKQ:-MNPptsUDL6g15nKPBJ1:byomk6v) ([raw file](https://github.com/sillsdev/thecombine/blob/989138df801b6c44471c35c521804797fa5726c2/docs/docker_deploy/README.md#L168)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

I disagree with the collapse of 2 spaces to 1 following a period.  That is standard practice with a typewriter and, in my opinion, makes the source (which looks like a typed page) easier to read.  The page renderer should format it according to typography rules.  Is it possible to configure prettier to ignore this?  I also prefer the *italic* to _italic_ but I am fine with either.
</blockquote></details>

The double-space is ignored by the markdown rendering, so it really is extraneous whitespace in the code.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 13 of 15 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/829)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
