### PR TITLE
Docker log with rsyslog

### PR DESCRIPTION
**Pull request by jmgrady**
Create ability to configure TheCombine to use `rsyslog` and `logrotate` for logging.

The Ansible scripts are updated so that if the variable `combine_use_syslog` is set to `true`, then TheCombine will be setup on the target machine to log all data using `rsyslog`.  The logs are stored in `/var/log/combine`. There is one log file, `dockerd.log`, for log messages from the docker engine; there is a separate log file for each container named `combine-<service>.log` where `<service>` is the name of the service in the `docker-compose.yml` file, for example:
```
nuc2:/var/log/combine$ ls -l
total 36
-rw-r--r-- 1 syslog adm  1281 Mar  4 20:22 combine-backend.log
-rw-r--r-- 1 syslog adm  9105 Mar  4 20:22 combine-database.log
-rw-r--r-- 1 syslog adm  1400 Mar  4 20:22 combine-frontend.log
-rw-r--r-- 1 syslog adm 14224 Mar  4 20:22 dockerd.log
```

In addition, `logrotate` is configured to rotate all log files in `/var/log/combine`.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1055)

### CODE REVIEW

**Comment by johnthagen** [comment]
Docker Compose `logging` configuration documentation: https://github.com/compose-spec/compose-spec/blob/master/spec.md#logging

**Comment by johnthagen** [comment]
___
*[deploy/roles/docker_install/tasks/main.yml, line 58 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1055#-MV1VGH-6TAa1L9SkdKw:-MV1VFUN45aZ7ylwn0je:bi2jtb2) ([raw file](https://github.com/sillsdev/thecombine/blob/727d3da8b7c909ed4d93cdb21404674c2e5bb4e6/deploy/roles/docker_install/tasks/main.yml#L58)):*
> ```YAML
>   template:
>     src: combine-log.conf.j2
>     dest: /etc/rsyslog.d/30-docker.conf
> ```

What is the significance of the `30-` prefix in this file name?

**Review by johnthagen — APPROVED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1055)* status: all files reviewed, 1 unresolved discussion (waiting on @jmgrady)

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1055)* status: all files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[deploy/roles/docker_install/tasks/main.yml, line 58 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1055#-MV1VGH-6TAa1L9SkdKw:-MV1dhY6CpN485kQL8TE:b-rnpzso) ([raw file](https://github.com/sillsdev/thecombine/blob/727d3da8b7c909ed4d93cdb21404674c2e5bb4e6/deploy/roles/docker_install/tasks/main.yml#L58)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

What is the significance of the `30-` prefix in this file name?
</blockquote></details>

The default logging rules are specified in `/etc/rsyslog.d/50-default.conf`.  `rsyslog` will process the configuration files in order so the `30-` causes the docker configuration to be processed before the default.  In this way, the `& ~` (stop) at the end of the docker configuration will prevent the docker logs from being duplicated in `/var/log/syslog`.

**Comment by johnthagen** [comment]
___
*[deploy/roles/docker_install/tasks/main.yml, line 58 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1055#-MV1VGH-6TAa1L9SkdKw:-MV1eyNl66gbYq5QTvML:b-8e4hz8) ([raw file](https://github.com/sillsdev/thecombine/blob/727d3da8b7c909ed4d93cdb21404674c2e5bb4e6/deploy/roles/docker_install/tasks/main.yml#L58)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

The default logging rules are specified in `/etc/rsyslog.d/50-default.conf`.  `rsyslog` will process the configuration files in order so the `30-` causes the docker configuration to be processed before the default.  In this way, the `& ~` (stop) at the end of the docker configuration will prevent the docker logs from being duplicated in `/var/log/syslog`.
</blockquote></details>

Sounds good. Might be worth a short comment (as it wasn't something that was immediately obvious to me as someone new looking at this).

**Review by johnthagen — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1055)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
