### PR TITLE
Create script to migrate SemanticDomains lists in the CombineDatabase

### PR DESCRIPTION
**Pull request by jmgrady**
Adds a Python script to the `maintenance` container that will update the documents in the `WordsCollection` and the `FrontierCollection`.  The update involves changing the structure of the list of `SemanticDomains` for each of the `senses` in each document.  The structure changes from, for example,:
```
SemanticDomains: [ 
   {
      Name: 'Container', 
      _id: '6.7.7',
      Description: ''
   }
]
```
to
```
SemanticDomains: [ 
   {
      name: 'Container',
      id: '6.7.7',
      guid: Binary(Buffer.from("eca46133c3504573a3499b7ce11b6fa8", "hex"), 3),
      lang: ''
   }
]
```

The script is to be run manually by connecting to the Kubenetes pod with `kubectl exec` and then calling the script.  It can be used in development by running against a local database.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1738)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1738)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`deploy/scripts/build.py` line 156 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1738#-NCzGHnFDuFNQ-TrYfT1:-NCzGHnFDuFNQ-TrYfT2:b-g533u4) ([raw file](https://github.com/sillsdev/thecombine/blob/22d4672af929d4e98d55d60a2c8c2b0581b5ef89/deploy/scripts/build.py#L156)):*
> ```Python
>     "maintenance": BuildSpec(
>         project_dir / "maintenance", "maint", no_op, no_op
>     ),
> ```

This can go back to 1 line.



_Code quote:_
```Python
    "maintenance": BuildSpec(
        project_dir / "maintenance", "maint", no_op, no_op
    ),
```

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1738)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`maintenance/scripts/db_update_sem_dom_in_senses.py` line 121 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1738#-NCzITzG0fEC7lKqXokm:-NCzITzH5f5FZrQYv2yx:b-9b1h3c) ([raw file](https://github.com/sillsdev/thecombine/blob/45168e508d3daee649eaeff4cbd6b7211fae09f4/maintenance/scripts/db_update_sem_dom_in_senses.py#L121)):*
> ```Python
>             if found_updates:
>                 updates[ObjectId(word["_id"])] = word
>         # apply the updates
> ```

How about adding `logging.info(f"Updating {len(updates)}/{num_docs} documents.")` here and changing "Updating" above to something like "Checking"?

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1738)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[`maintenance/scripts/db_update_sem_dom_in_senses.py` line 121 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1738#-NCzITzG0fEC7lKqXokm:-NCzL6iDCg4d7QOvKzQ1:b-gbckko) ([raw file](https://github.com/sillsdev/thecombine/blob/45168e508d3daee649eaeff4cbd6b7211fae09f4/maintenance/scripts/db_update_sem_dom_in_senses.py#L121)):*
> logging.info(f"Updating {len(updates)}/{num_docs} documents.")
Good idea.  Done.
___
*[`deploy/scripts/build.py` line 156 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1738#-NCzGHnFDuFNQ-TrYfT1:-NCzMrdd2UBIHD0nllj8:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/22d4672af929d4e98d55d60a2c8c2b0581b5ef89/deploy/scripts/build.py#L156)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

This can go back to 1 line.
</blockquote></details>

Done.

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1738)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

___
*[`maintenance/scripts/db_update_sem_dom_in_senses.py` line 117 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1738#-NCzMMlf7kZYzyAP5DFK:-NCzNsYf0hqk-yAuYKj8:b-bi6qwe) ([raw file](https://github.com/sillsdev/thecombine/blob/45168e508d3daee649eaeff4cbd6b7211fae09f4/maintenance/scripts/db_update_sem_dom_in_senses.py#L117)):*
I thought I had tested that.  According to this SO post (https://stackoverflow.com/questions/11277432/how-can-i-remove-a-key-from-a-python-dictionary) the 2 argument form of `pop` will work as shown here:
```
$ python3
Python 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> test_dict = { "foo": "somestring" }
>>> print(test_dict)
{'foo': 'somestring'}
>>> del test_dict['bar']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'bar'
>>> test_dict.pop('bar', None)
>>> 


```

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1738)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Pull request merged**
