### PR TITLE
Update Kubernetes deployment scripts for NUCs

### PR DESCRIPTION
**Pull request by jmgrady**
Fix the following issues for deploying _The Combine_ on the NUCs:
- Change the `dnsPolicy` from `ClusterFirst` to `Default`.  Although the Kubernetes documents state that the default value is `ClusterFirst`, the behavior is different.
- Fix the TLS secret name in the `Ingress` for the main application to match the secret that is created by the `update-cert-cronjob`.
- Change the service definition for the `k3s` Kubernetes engine.  The default configuration allows `k3s` to be updated without affecting the running containers.  This adds 90 seconds to the shutdown time and is not needed for our use model - `k3s` will only be updated when it is not being used in a workshop.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1517)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[deploy/roles/aws_login_job/templates/aws-ecr-login-oneshot.yaml.j2, line 8 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1517#-Msq-GiKACPbp0DdydZT:-Msq-GiKACPbp0DdydZU:blro2uq) ([raw file](https://github.com/sillsdev/thecombine/blob/804e1ab25851f61a6155eeb8400d6abae63820aa/deploy/roles/aws_login_job/templates/aws-ecr-login-oneshot.yaml.j2#L8)):*
> ```Jinja
>   namespace: {{ aws_namespace }}
> spec:
>   ttlSecondsAfterFinished: 86400
> ```

This looks to be 24 hours now. Maybe a comment about why this value is set this way?

**Review by johnthagen — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1517)* status: all files reviewed, 1 unresolved discussion (waiting on @jmgrady)

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1517)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @johnthagen)

___
*[deploy/roles/aws_login_job/templates/aws-ecr-login-oneshot.yaml.j2, line 8 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1517#-Msq-GiKACPbp0DdydZT:-Msq1nccDWA736VauFFN:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/804e1ab25851f61a6155eeb8400d6abae63820aa/deploy/roles/aws_login_job/templates/aws-ecr-login-oneshot.yaml.j2#L8)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This looks to be 24 hours now. Maybe a comment about why this value is set this way?
</blockquote></details>

Done.

**Review by johnthagen — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1517)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Pull request merged**
