### PR TITLE
Centralize the AppBar; Remove extraneous component wrappers

### PR DESCRIPTION
**Pull request by imnasnainaec**
In the routing of `src/App/component.tsx`, separate out all pages that can only be accessed after login under a new `AppLoggedIn.tsx`, and place a single global `AppBar` within this new component, so we don't have to maintain a new instance within every page within the app.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/807)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[src/history.ts, line 13 at r2](https://reviewable.io/reviews/sillsdev/thecombine/807#-MM289eS-z6musTn4Y3o:-MM289eS-z6musTn4Y3p:bvy9zkm) ([raw file](https://github.com/sillsdev/thecombine/blob/993aa0ae009e9cd4f5887e2c9bbdf3305196a446/src/history.ts#L13)):*
> ```XML
> export default history;
> 
> export enum path {
> ```

I'm not sure this needs to change, but when I first say a lowercased item like this, I think it was a built in (like `string`, etc).

Could this be renamed to `Path` so it's a little more obvious this is a custom type?

Also, I think canonically, on the web these things are called "routes" rather than "paths".

So maybe: `Route` or `AppRoute` to make it really clear?

**Comment by johnthagen** [comment]
___
*[src/components/AppBar/AppBarComponent.tsx, line 16 at r2](https://reviewable.io/reviews/sillsdev/thecombine/807#-MM28w7X1pn93V4glVc4:-MM28w7X1pn93V4glVc5:bs0md0h) ([raw file](https://github.com/sillsdev/thecombine/blob/993aa0ae009e9cd4f5887e2c9bbdf3305196a446/src/components/AppBar/AppBarComponent.tsx#L16)):*
> ```XML
> }
> 
> /** An app bar shown at the top of almost every page of The Combine */
> ```

Could rephrase to say: "Shown on all logged in pages" or equivalent.

**Comment by johnthagen** [comment]
___
*[src/history.ts, line 14 at r2](https://reviewable.io/reviews/sillsdev/thecombine/807#-MM29H_V2Fmpn6jcF-pT:-MM29H_V2Fmpn6jcF-pU:b-ojt7u5) ([raw file](https://github.com/sillsdev/thecombine/blob/993aa0ae009e9cd4f5887e2c9bbdf3305196a446/src/history.ts#L14)):*
> ```XML
> 
> export enum path {
>   dataEntry = "/app/data-entry",
> ```

It also looks like TypeScript prefers `UpperCamelCase` for enum members: https://www.typescriptlang.org/docs/handbook/enums.html

**Comment by johnthagen** [comment]
___
*[src/history.ts, line 13 at r2](https://reviewable.io/reviews/sillsdev/thecombine/807#-MM289eS-z6musTn4Y3o:-MM29SJvDou_40wGexe5:b-ca4p6h) ([raw file](https://github.com/sillsdev/thecombine/blob/993aa0ae009e9cd4f5887e2c9bbdf3305196a446/src/history.ts#L13)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I'm not sure this needs to change, but when I first say a lowercased item like this, I think it was a built in (like `string`, etc).

Could this be renamed to `Path` so it's a little more obvious this is a custom type?

Also, I think canonically, on the web these things are called "routes" rather than "paths".

So maybe: `Route` or `AppRoute` to make it really clear?
</blockquote></details>

I see that other parts of React already have `Route`, so maybe something like `AppRoute` would be the best here.

**Comment by johnthagen** [comment]
___
*[src/goals/DefaultGoal/BaseGoalScreen/BaseGoalScreen.tsx, line 55 at r2](https://reviewable.io/reviews/sillsdev/thecombine/807#-MM2AyBoC_xaT_nhsRVr:-MM2AyBp6h12SZK15Lbl:b-zi294q) ([raw file](https://github.com/sillsdev/thecombine/blob/993aa0ae009e9cd4f5887e2c9bbdf3305196a446/src/goals/DefaultGoal/BaseGoalScreen/BaseGoalScreen.tsx#L55)):*
> ```XML
>  * based on the current step in the goal
>  */
> export default class BaseGoalScreen extends React.Component<GoalProps> {
> ```

Could this become a functional component while we are here?

**Review by johnthagen — CHANGES_REQUESTED** [review]
> Reviewed 17 of 19 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/807)* status: all files reviewed, 4 unresolved discussions (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/807)* status: 8 of 37 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @johnthagen)

___
*[src/history.ts, line 13 at r2](https://reviewable.io/reviews/sillsdev/thecombine/807#-MM289eS-z6musTn4Y3o:-MM2Il-c6zIFrNrjX57_:b-og9jzy) ([raw file](https://github.com/sillsdev/thecombine/blob/993aa0ae009e9cd4f5887e2c9bbdf3305196a446/src/history.ts#L13)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I see that other parts of React already have `Route`, so maybe something like `AppRoute` would be the best here.
</blockquote></details>

`Path` implemented
___
*[src/components/AppBar/AppBarComponent.tsx, line 16 at r2](https://reviewable.io/reviews/sillsdev/thecombine/807#-MM28w7X1pn93V4glVc4:-MM2ItZr-ZCouxhhh-DP:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/993aa0ae009e9cd4f5887e2c9bbdf3305196a446/src/components/AppBar/AppBarComponent.tsx#L16)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Could rephrase to say: "Shown on all logged in pages" or equivalent.
</blockquote></details>

Done
___
*[src/goals/DefaultGoal/BaseGoalScreen/BaseGoalScreen.tsx, line 55 at r2](https://reviewable.io/reviews/sillsdev/thecombine/807#-MM2AyBoC_xaT_nhsRVr:-MM2Iv2s8a6Par2IT9Ip:b-zi40gs) ([raw file](https://github.com/sillsdev/thecombine/blob/993aa0ae009e9cd4f5887e2c9bbdf3305196a446/src/goals/DefaultGoal/BaseGoalScreen/BaseGoalScreen.tsx#L55)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Could this become a functional component while we are here?
</blockquote></details>

I had tried that, but it doesn't play well with `BaseGoalScreen/index.tsx`

**Comment by johnthagen** [comment]
___
*[src/history.ts, line 14 at r3](https://reviewable.io/reviews/sillsdev/thecombine/807#-MM2JruG3vaCjktV0nml:-MM2JruG3vaCjktV0nmm:bnv8neg) ([raw file](https://github.com/sillsdev/thecombine/blob/ef0fdacfb3ce3a4d94c4ce178333d66dd84916f5/src/history.ts#L14)):*
> ```XML
> 
> export enum Path {
>   dataEntry = "/app/data-entry",
> ```

`enum` members should start with a capital letter: https://www.typescriptlang.org/docs/handbook/enums.html

`DataEntry = ...`

**Review by johnthagen — CHANGES_REQUESTED** [review]
> Reviewed 29 of 29 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/807)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/807)* status: 10 of 42 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @johnthagen)

___
*[src/history.ts, line 14 at r3](https://reviewable.io/reviews/sillsdev/thecombine/807#-MM2JruG3vaCjktV0nml:-MM2QHIj6Zx6piE487Sm:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/ef0fdacfb3ce3a4d94c4ce178333d66dd84916f5/src/history.ts#L14)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

`enum` members should start with a capital letter: https://www.typescriptlang.org/docs/handbook/enums.html

`DataEntry = ...`
</blockquote></details>

Done.

**Review by johnthagen — APPROVED** [review]
> Reviewed 1 of 32 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/807)* status: 11 of 42 files reviewed, all discussions resolved (waiting on @johnthagen)

**Review by johnthagen — APPROVED** [review]
> Reviewed 31 of 32 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/807)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
