### PR TITLE
Add explicit default formatters by language

### PR DESCRIPTION
**Pull request by imnasnainaec**
A recent VSCode update created a need for formatters to be specified language by language: https://github.com/microsoft/vscode/issues/108447#issuecomment-718032544

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/808)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[package.json, line 16 at r1](https://reviewable.io/reviews/sillsdev/thecombine/808#-MM0cjPw2LB7sUT9QRR3:-MM0cjPw2LB7sUT9QRR4:bbsyi39) ([raw file](https://github.com/sillsdev/thecombine/blob/30f8a193535fbc9a30ea0a691efe354e4b6b4735/package.json#L16)):*
> ```JSON
>     "fmt-frontend": "prettier --write \"./src/**/*.{js,jsx,ts,tsx,json}\"",
>     "fmt-frontend-check": "prettier --check \"./src/**/*.{js,jsx,ts,tsx,json}\"",
>     "fmt-project": "prettier --write \"./{.vscode,public,scripts}/**/*.{js,jsx,ts,tsx,json}\"",
> ```

Can this be merged into `fmt-frontend` since it's mostly a duplication? I see the distinction, perhaps we should call it `fmt-js` for (format JavaScript family? including JS, TS, JSON)?

**Review by johnthagen — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/808)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

**Comment by johnthagen** [comment]
___
*[package.json, line 16 at r1](https://reviewable.io/reviews/sillsdev/thecombine/808#-MM0cjPw2LB7sUT9QRR3:-MM0jwtT0uBwbE-PrneH:b-tmecv9) ([raw file](https://github.com/sillsdev/thecombine/blob/30f8a193535fbc9a30ea0a691efe354e4b6b4735/package.json#L16)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Can this be merged into `fmt-frontend` since it's mostly a duplication? I see the distinction, perhaps we should call it `fmt-js` for (format JavaScript family? including JS, TS, JSON)?
</blockquote></details>

Specifically, if we want to validate that everything is formatted properly, we'd need to add a `fmt-project-check` as well. I'd suggest we just include these extra files in `fmt-frontend` / `fmt-frontend-check`. Basically all of these files are part of the `frontend` project, even though in the Combine we have sorta mashed a lot of projects (including backend) into the top level folder.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/808)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @johnthagen)

___
*[package.json, line 16 at r1](https://reviewable.io/reviews/sillsdev/thecombine/808#-MM0cjPw2LB7sUT9QRR3:-MM15YRj64CNjS1wNPAm:b-o6t9rl) ([raw file](https://github.com/sillsdev/thecombine/blob/26227b7b9a44644c9333a7acef3254fec25d75f8/package.json#L16)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Specifically, if we want to validate that everything is formatted properly, we'd need to add a `fmt-project-check` as well. I'd suggest we just include these extra files in `fmt-frontend` / `fmt-frontend-check`. Basically all of these files are part of the `frontend` project, even though in the Combine we have sorta mashed a lot of projects (including backend) into the top level folder.
</blockquote></details>

It's just a few files, so I think it's simplest to add them in with `fmt-frontend[-check]`.

**Review by johnthagen — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/808)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by johnthagen — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/808)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
