### PR TITLE
Fix Storage/Import of Word Creation and Modified Fields

### PR DESCRIPTION
**Pull request by johnthagen**
Subtask of #960

- Use ISO 8601 date time format to allow for reliable round tripping of date times through database
- Set `Word.Modified` to creation time when `Word` is created
- Properly import `Creation` and `Modified` date times during Lift import

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/962)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
___
*[Backend/Helper/Time.cs, line 8 at r3](https://reviewable.io/reviews/sillsdev/thecombine/962#-MSEanD7EgPiFn6-pNzS:-MSEanD7EgPiFn6-pNzT:b-kbick2) ([raw file](https://github.com/sillsdev/thecombine/blob/06f8c729f98952749e203c09bff79d145d7476a6/Backend/Helper/Time.cs#L8)):*
> ```
> ad
> ```
Where are we going? :car:

**Comment by johnthagen** [comment]
___
*[Backend/Helper/Time.cs, line 8 at r3](https://reviewable.io/reviews/sillsdev/thecombine/962#-MSEanD7EgPiFn6-pNzS:-MSEc7I2-YBUN_Vly83n:bmbf9bq) ([raw file](https://github.com/sillsdev/thecombine/blob/06f8c729f98952749e203c09bff79d145d7476a6/Backend/Helper/Time.cs#L8)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> ad
> ```
Where are we going? :car: 
</blockquote></details>

haha. Round trip into and out of the database.

**Comment by johnthagen** [comment]
___
*[Backend/Helper/Time.cs, line 8 at r3](https://reviewable.io/reviews/sillsdev/thecombine/962#-MSEanD7EgPiFn6-pNzS:-MSEciEk3t9uczsfaFvv:bhttv9d) ([raw file](https://github.com/sillsdev/thecombine/blob/06f8c729f98952749e203c09bff79d145d7476a6/Backend/Helper/Time.cs#L8)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

haha. Round trip into and out of the database.
</blockquote></details>

Oh, I see. Typo. :)

**Comment by johnthagen** [comment]
___
*[Backend/Helper/Time.cs, line 8 at r3](https://reviewable.io/reviews/sillsdev/thecombine/962#-MSEanD7EgPiFn6-pNzS:-MSEcqjw3SKrU7bTEN0b:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/06f8c729f98952749e203c09bff79d145d7476a6/Backend/Helper/Time.cs#L8)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Oh, I see. Typo. :)
</blockquote></details>

Done

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/962)* status: 1 of 5 files reviewed, all discussions resolved (waiting on @johnthagen)

___
*[Backend/Helper/Time.cs, line 8 at r3](https://reviewable.io/reviews/sillsdev/thecombine/962#-MSEanD7EgPiFn6-pNzS:-MSEcSe897NIgnBuF7nO:bq8uarg) ([raw file](https://github.com/sillsdev/thecombine/blob/06f8c729f98952749e203c09bff79d145d7476a6/Backend/Helper/Time.cs#L8)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Done
</blockquote></details>

Oh good, jokes aren't as funny when you have to explain them. :wink:

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/962)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jasonleenaylor — APPROVED** [review]
:LGTM:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/962#-:-MSEezZo8t920tJ908ye:bjw1nd)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
