### PR TITLE
Refactor several frontend files

### PR DESCRIPTION
**Pull request by johnthagen**
Refactor some frontend files based on code analysis from JetBrains Rider. Refactors include:

- Adding some missing `await`'s
- Removing some redundant local variables
- Remove some usages of `var`
- Remove explicit `=== false`

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1461)

### CODE REVIEW

**Review by imnasnainaec — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1461)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[src/components/GoalTimeline/Redux/GoalActions.ts, line 80 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1461#-MnkjKvDCCQYb3IZMQZs:-MnkjKvEEkM--ODvik0n:b9h1ua4) ([raw file](https://github.com/sillsdev/thecombine/blob/7c73439d282cf3daa1f9a76e98a79af40d91bc8b/src/components/GoalTimeline/Redux/GoalActions.ts#L80)):*
> ```
>         // Load the new goal, but don't await, to allow a loading screen.
>         await dispatch(asyncLoadNewGoal(goal, userEditId));
> ```
This one is explicitly and intentionally *not* awaited.

**Comment by johnthagen** [comment]
___
*[src/components/GoalTimeline/Redux/GoalActions.ts, line 80 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1461#-MnkjKvDCCQYb3IZMQZs:-Mnkk0HA09RCFjD2_kJN:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7c73439d282cf3daa1f9a76e98a79af40d91bc8b/src/components/GoalTimeline/Redux/GoalActions.ts#L80)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>         // Load the new goal, but don't await, to allow a loading screen.
>         await dispatch(asyncLoadNewGoal(goal, userEditId));
> ```
This one is explicitly and intentionally *not* awaited.
</blockquote></details>

Done.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1461)* status: 4 of 16 files reviewed, all discussions resolved (waiting on @johnthagen)

**Review by johnthagen — COMMENTED** [review]
> Reviewed 5 of 7 files at r1, 1 of 1 files at r2, 5 of 7 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1461)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Review by imnasnainaec — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1461)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Pull request merged**
