### PR TITLE
Implement Pronunciations state/actions/reducer.

### LINKED ISSUE #330: Can play multiple recordings simultaneously
This has been tested in Ubuntu 18.04 on Firefox and Chromium and in Windows 10 on Chrome and Firefox.

In both Data Entry and Review Entries, multiple recordings (for the same entry or different entries) can be played simultaneously. You can even add a new recording while another recording is playing. It would be good to have the press of a play or record button cut off any active playback.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Extract recording from ReviewEntries state and expand with playing for stand-alone Pronunciations state.
With this pr, clicking any play or record icon will halt an active recording.

Resolves #330

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/847)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[src/components/Pronunciations/AudioPlayer.tsx, line 81 at r1](https://reviewable.io/reviews/sillsdev/thecombine/847#-MNjOsSE-Rd4hvSuh9G5:-MNjOsSE-Rd4hvSuh9G6:baczl1g) ([raw file](https://github.com/sillsdev/thecombine/blob/7c15e878ed6ca851a413f60df0ef3c1c3ad70fa6/src/components/Pronunciations/AudioPlayer.tsx#L81)):*
> ```XML
>     setIsPlaying(true);
>     audio.addEventListener("ended", () => dispatch(reset()));
>     audio.play();
> ```

Rider noticed a `Promise` here is ignored. Is that okay? Anything `async` we want to do here?

**Comment by johnthagen** [comment]
___
*[src/components/Pronunciations/AudioPlayer.tsx, line 47 at r1](https://reviewable.io/reviews/sillsdev/thecombine/847#-MNjP726Cpzm9b1q3s4j:-MNjP726Cpzm9b1q3s4k:blyvygi) ([raw file](https://github.com/sillsdev/thecombine/blob/7c15e878ed6ca851a413f60df0ef3c1c3ad70fa6/src/components/Pronunciations/AudioPlayer.tsx#L47)):*
> ```XML
>   const dispatch = useDispatch();
>   const [audio] = useState<HTMLAudioElement>(new Audio(props.pronunciationUrl));
>   const [anchor, setAnchor] = useState<HTMLElement | null>(null);
> ```

Do we want to be using `undef` everywhere in TypeScript, or is there a reason we need `null` in this case?

`undef` plays nicer with `?`

**Comment by johnthagen** [comment]
___
*[src/components/Pronunciations/AudioPlayer.tsx, line 181 at r1](https://reviewable.io/reviews/sillsdev/thecombine/847#-MNjPxuq4prLsAEVwlMl:-MNjPxuq4prLsAEVwlMm:bxj1jeo) ([raw file](https://github.com/sillsdev/thecombine/blob/7c15e878ed6ca851a413f60df0ef3c1c3ad70fa6/src/components/Pronunciations/AudioPlayer.tsx#L181)):*
> ```XML
>         onClose={() => setDeleteConf(false)}
>         onConfirm={deleteAudio}
>       ></ButtonConfirmation>
> ```

This could be simplified to:


```
      <ButtonConfirmation
        open={deleteConf}
        textId="buttons.deletePermanently"
        titleId="pronunciations.deleteRecording"
        onClose={() => setDeleteConf(false)}
        onConfirm={deleteAudio}
      />
```

**Comment by johnthagen** [comment]
___
*[src/components/Pronunciations/PronunciationsReducer.tsx, line 22 at r1](https://reviewable.io/reviews/sillsdev/thecombine/847#-MNjQSLo16gkRRw6ZSBZ:-MNjQSLo16gkRRw6ZSB_:b-z447ib) ([raw file](https://github.com/sillsdev/thecombine/blob/7c15e878ed6ca851a413f60df0ef3c1c3ad70fa6/src/components/Pronunciations/PronunciationsReducer.tsx#L22)):*
> ```XML
> ): PronunciationsState => {
>   switch (action.type) {
>     case PronunciationsStatus.Playing:
> ```

I'm not sure how we feel about fall-through `case`s, but this could be simplified to:

```
    case PronunciationsStatus.Playing:
    case PronunciationsStatus.Recording:
      return {
        ...defaultState,
        ...action,
      };
```

**Comment by johnthagen** [comment]
___
*[src/components/Pronunciations/PronunciationsReducer.tsx, line 32 at r1](https://reviewable.io/reviews/sillsdev/thecombine/847#-MNjQsvf4UhsxdzSD-qf:-MNjQsvf4UhsxdzSD-qg:bkot2u2) ([raw file](https://github.com/sillsdev/thecombine/blob/7c15e878ed6ca851a413f60df0ef3c1c3ad70fa6/src/components/Pronunciations/PronunciationsReducer.tsx#L32)):*
> ```XML
>         ...action,
>       };
>     case PronunciationsStatus.Default:
> ```

Same down here with `Default` and `RESET`.

**Comment by johnthagen** [comment]
Functionally, this worked well and I didn't experience the issues from #330.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/847)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @johnthagen)

___
*[src/components/Pronunciations/AudioPlayer.tsx, line 47 at r1](https://reviewable.io/reviews/sillsdev/thecombine/847#-MNjP726Cpzm9b1q3s4j:-MNjZmNx3cUEJh9uM4sv:bb7f2mf) ([raw file](https://github.com/sillsdev/thecombine/blob/7c15e878ed6ca851a413f60df0ef3c1c3ad70fa6/src/components/Pronunciations/AudioPlayer.tsx#L47)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Do we want to be using `undef` everywhere in TypeScript, or is there a reason we need `null` in this case?

`undef` plays nicer with `?`
</blockquote></details>

done
___
*[src/components/Pronunciations/AudioPlayer.tsx, line 81 at r1](https://reviewable.io/reviews/sillsdev/thecombine/847#-MNjOsSE-Rd4hvSuh9G5:-MNjZsm73x-j054Mn3-9:bb7f2mf) ([raw file](https://github.com/sillsdev/thecombine/blob/7c15e878ed6ca851a413f60df0ef3c1c3ad70fa6/src/components/Pronunciations/AudioPlayer.tsx#L81)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Rider noticed a `Promise` here is ignored. Is that okay? Anything `async` we want to do here?
</blockquote></details>

done
___
*[src/components/Pronunciations/AudioPlayer.tsx, line 181 at r1](https://reviewable.io/reviews/sillsdev/thecombine/847#-MNjPxuq4prLsAEVwlMl:-MNjZzvz97kkDnjVpe6N:bb7f2mf) ([raw file](https://github.com/sillsdev/thecombine/blob/7c15e878ed6ca851a413f60df0ef3c1c3ad70fa6/src/components/Pronunciations/AudioPlayer.tsx#L181)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This could be simplified to:


```
      <ButtonConfirmation
        open={deleteConf}
        textId="buttons.deletePermanently"
        titleId="pronunciations.deleteRecording"
        onClose={() => setDeleteConf(false)}
        onConfirm={deleteAudio}
      />
```
</blockquote></details>

done
___
*[src/components/Pronunciations/PronunciationsReducer.tsx, line 22 at r1](https://reviewable.io/reviews/sillsdev/thecombine/847#-MNjQSLo16gkRRw6ZSBZ:-MNjZxia7-fRp6KAABYa:bb7f2mf) ([raw file](https://github.com/sillsdev/thecombine/blob/7c15e878ed6ca851a413f60df0ef3c1c3ad70fa6/src/components/Pronunciations/PronunciationsReducer.tsx#L22)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I'm not sure how we feel about fall-through `case`s, but this could be simplified to:

```
    case PronunciationsStatus.Playing:
    case PronunciationsStatus.Recording:
      return {
        ...defaultState,
        ...action,
      };
```
</blockquote></details>

done
___
*[src/components/Pronunciations/PronunciationsReducer.tsx, line 32 at r1](https://reviewable.io/reviews/sillsdev/thecombine/847#-MNjQsvf4UhsxdzSD-qf:-MNjZyXt1KJDlzik9x0h:bb7f2mf) ([raw file](https://github.com/sillsdev/thecombine/blob/7c15e878ed6ca851a413f60df0ef3c1c3ad70fa6/src/components/Pronunciations/PronunciationsReducer.tsx#L32)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Same down here with `Default` and `RESET`.
</blockquote></details>

done

**Review by johnthagen — APPROVED** [review]
> Reviewed 12 of 12 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/847)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
