### PR TITLE
Add links to sign up and login pages from user guide

### LINKED ISSUE #1604: Improve the landing page experience
- [x] 1. Rename 'Register' button to 'Sign Up'
- [ ] 2. Include a 'call to action' paragraph with an additional 'Sign Up' button in the content area
- [x] 3. Add a link to the 'Sign Up' in the 'Account' documentation

### PR DESCRIPTION
**Pull request by johnthagen**
Subtask of #1604, steps 1 & 3.

> To test these links, use the Docker Compose development instructions

- Also, rename "Register" to "Sign Up" throughout the application

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1611)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1611)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[src/browserHistory.ts, line 39 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1611#-Mxt_BQE5hKIQ3uL8HGm:-Mxt_BQF15MEPHMAOl8m:b-10o17o) ([raw file](https://github.com/sillsdev/thecombine/blob/30340c26955c1c0f5ea49d2a3c5248bd058a3632/src/browserHistory.ts#L39)):*
> ```XML
>   PwReset = "/forgot/reset",
>   SignUp = "/sign-up",
>   Root = "/",
> ```

alphabetize



_Code quote:_
```XML
  SignUp = "/sign-up",
  Root = "/",
```

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1611)* status: 0 of 14 files reviewed, 3 unresolved discussions (waiting on @johnthagen)

___
*[docs/user_guide/docs/account.md, line 9 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1611#-MxtlFxS0tEEy42HKcFp:-MxtlFxS0tEEy42HKcFq:buzb7zx) ([raw file](https://github.com/sillsdev/thecombine/blob/30340c26955c1c0f5ea49d2a3c5248bd058a3632/docs/user_guide/docs/account.md#L9)):*
> ```Markdown
> ## Register
> 
> To create a new account, click the [SIGN UP](../../sign-up) button on the Login page.
> ```

Only one `../` is necessary.
___
*[docs/user_guide/docs/account.md, line 17 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1611#-MxtlK432UU6iA8GudP-:-MxtlK432UU6iA8GudP0:buzb7zx) ([raw file](https://github.com/sillsdev/thecombine/blob/30340c26955c1c0f5ea49d2a3c5248bd058a3632/docs/user_guide/docs/account.md#L17)):*
> ```Markdown
> ## Login
> 
> [Login](../../login) to The Combine with the username and password given at registration.
> ```

Only one `../` is necessary.

**Comment by johnthagen** [comment]
___
*[src/browserHistory.ts, line 39 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1611#-Mxt_BQE5hKIQ3uL8HGm:-MxtqODK2dlGYHE_QkKD:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/30340c26955c1c0f5ea49d2a3c5248bd058a3632/src/browserHistory.ts#L39)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

alphabetize
</blockquote></details>

Done.

**Comment by johnthagen** [comment]
___
*[docs/user_guide/docs/account.md, line 17 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1611#-MxtlK432UU6iA8GudP-:-MxtqQ929SKgBcXLIzE2:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/30340c26955c1c0f5ea49d2a3c5248bd058a3632/docs/user_guide/docs/account.md#L17)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Only one `../` is necessary.
</blockquote></details>

Done.

**Review by imnasnainaec — CHANGES_REQUESTED** [review]
> Reviewed 4 of 14 files at r1, 1 of 2 files at r2, 1 of 2 files at r3, 5 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1611)* status: 11 of 16 files reviewed, 8 unresolved discussions (waiting on @johnthagen)

___
*[docs/user_guide/docs/account.md, line 3 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1611#-Mxtv4lH-PnJocW-QxN2:-Mxtv4lJAtb2KLf2zr-f:bg8fxh6) ([raw file](https://github.com/sillsdev/thecombine/blob/cc4e534b8b82b08a86146a2f611f541e0733b793/docs/user_guide/docs/account.md#L3)):*
> ```Markdown
> # Account
> 
> How to register, login, and edit your account.
> ```

"How to sign up,..."
___
*[docs/user_guide/docs/account.md, line 7 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1611#-MxttYDVBJ10VoWWPKXJ:-MxttYDVBJ10VoWWPKXK:bdz1rz7) ([raw file](https://github.com/sillsdev/thecombine/blob/cc4e534b8b82b08a86146a2f611f541e0733b793/docs/user_guide/docs/account.md#L7)):*
> ```Markdown
> Login{ .center }
> 
> ## Register
> ```

## Sign Up
___
*[src/components/Login/LoginPage/LoginComponent.tsx, line 201 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1611#-MxtvMivB8uJyVSC6lCt:-MxtvMivB8uJyVSC6lCu:b-vtg3lz) ([raw file](https://github.com/sillsdev/thecombine/blob/cc4e534b8b82b08a86146a2f611f541e0733b793/src/components/Login/LoginPage/LoginComponent.tsx#L201)):*
> ```XML
>               )}
> 
>               {/* User Guide, Register, and Login buttons */}
> ```

, Sign Up, 
___
*[src/components/Login/tests/LoginActions.test.tsx, line 93 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1611#-MxtwSEXAkMr-sHE1Wih:-MxtwSEXAkMr-sHE1Wii:b-nxe5sl) ([raw file](https://github.com/sillsdev/thecombine/blob/cc4e534b8b82b08a86146a2f611f541e0733b793/src/components/Login/tests/LoginActions.test.tsx#L93)):*
> ```XML
>   });
> 
>   describe("asyncRegister", () => {
> ```

`"asyncSignUp"`
___
*[src/components/Login/SignUpPage/SignUpComponent.tsx, line 294 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1611#-Mxtvc6x1grKQ2fSTXzu:-Mxtvc6y7Gk_Y-vmYGE-:b-vujdxo) ([raw file](https://github.com/sillsdev/thecombine/blob/cc4e534b8b82b08a86146a2f611f541e0733b793/src/components/Login/SignUpPage/SignUpComponent.tsx#L294)):*
> ```XML
>               )}
> 
>               {/* Register and Login buttons */}
> ```

{/* Sign Up and ...
___
*[src/components/Login/SignUpPage/tests/SignUpComponent.test.tsx, line 18 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1611#-Mxtw3cq48vt90acJrAy:-Mxtw3cq48vt90acJrAz:b-w9fzzs) ([raw file](https://github.com/sillsdev/thecombine/blob/cc4e534b8b82b08a86146a2f611f541e0733b793/src/components/Login/SignUpPage/tests/SignUpComponent.test.tsx#L18)):*
> ```XML
> }));
> 
> const REGISTER = jest.fn();
> ```

Maybe `mockReset` instead of `REGISTER`.
___
*[src/components/Login/SignUpPage/tests/SignUpComponent.test.tsx, line 48 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1611#-Mxtw8VB4KvDkMS2Scqw:-Mxtw8VB4KvDkMS2Scqx:b-2dajhl) ([raw file](https://github.com/sillsdev/thecombine/blob/cc4e534b8b82b08a86146a2f611f541e0733b793/src/components/Login/SignUpPage/tests/SignUpComponent.test.tsx#L48)):*
> ```XML
> 
>   // These test whether various combinations of registration data should result in errors
>   test("Register: no data", () => {
> ```

Many of the test descriptions in this file still have "Register"
___
*[src/components/Login/SignUpPage/tests/SignUpComponent.test.tsx, line 95 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1611#-MxtwK20DymLTq9zPhpE:-MxtwK20DymLTq9zPhpF:b-m9b2cl) ([raw file](https://github.com/sillsdev/thecombine/blob/cc4e534b8b82b08a86146a2f611f541e0733b793/src/components/Login/SignUpPage/tests/SignUpComponent.test.tsx#L95)):*
> ```XML
> });
> 
> async function testRegister(
> ```

`testSignUp`

**Comment by johnthagen** [comment]
___
*[docs/user_guide/docs/account.md, line 3 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1611#-Mxtv4lH-PnJocW-QxN2:-MxtxYNH96o6nXFetAAe:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/cc4e534b8b82b08a86146a2f611f541e0733b793/docs/user_guide/docs/account.md#L3)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

"How to sign up,..."
</blockquote></details>

Done.

**Comment by johnthagen** [comment]
___
*[docs/user_guide/docs/account.md, line 7 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1611#-MxttYDVBJ10VoWWPKXJ:-Mxtx_AA5Krvq_33gxus:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/cc4e534b8b82b08a86146a2f611f541e0733b793/docs/user_guide/docs/account.md#L7)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

## Sign Up
</blockquote></details>

Done.

**Comment by johnthagen** [comment]
___
*[src/components/Login/LoginPage/LoginComponent.tsx, line 201 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1611#-MxtvMivB8uJyVSC6lCt:-MxtxdcU80Bx3fkYDf8f:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/cc4e534b8b82b08a86146a2f611f541e0733b793/src/components/Login/LoginPage/LoginComponent.tsx#L201)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

, Sign Up, 
</blockquote></details>

Done.

**Comment by johnthagen** [comment]
___
*[src/components/Login/SignUpPage/SignUpComponent.tsx, line 294 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1611#-Mxtvc6x1grKQ2fSTXzu:-MxtxhJj0k73tcWKBeU4:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/cc4e534b8b82b08a86146a2f611f541e0733b793/src/components/Login/SignUpPage/SignUpComponent.tsx#L294)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

{/* Sign Up and ...
</blockquote></details>

Done.

**Comment by johnthagen** [comment]
___
*[src/components/Login/SignUpPage/tests/SignUpComponent.test.tsx, line 48 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1611#-Mxtw8VB4KvDkMS2Scqw:-Mxty0_T-nwYKBo4uWsu:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/cc4e534b8b82b08a86146a2f611f541e0733b793/src/components/Login/SignUpPage/tests/SignUpComponent.test.tsx#L48)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Many of the test descriptions in this file still have "Register"
</blockquote></details>

Done.

**Comment by johnthagen** [comment]
___
*[src/components/Login/SignUpPage/tests/SignUpComponent.test.tsx, line 95 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1611#-MxtwK20DymLTq9zPhpE:-Mxty2Hq5F3Ov_8RxGkJ:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/cc4e534b8b82b08a86146a2f611f541e0733b793/src/components/Login/SignUpPage/tests/SignUpComponent.test.tsx#L95)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`testSignUp`
</blockquote></details>

Done.

**Comment by johnthagen** [comment]
___
*[src/components/Login/tests/LoginActions.test.tsx, line 93 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1611#-MxtwSEXAkMr-sHE1Wih:-Mxty6Zm-nUFryLF-D2c:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/cc4e534b8b82b08a86146a2f611f541e0733b793/src/components/Login/tests/LoginActions.test.tsx#L93)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`"asyncSignUp"`
</blockquote></details>

Done.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1611)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Pull request merged**
