### PR TITLE
Use nullable compiler option for backend test project

### LINKED ISSUE #850: Enable nullable compiler option on BackendTests project
Currently, the `nullable` compiler option is only enabled on the make Backend project, not the test project. This means there are slight differences in the API's exposed by the Backend and what is used in tests. Ideally, `nullable` should be enabled for the test project as well to better sync them at the type system level.

Follow on to #754

### PR DESCRIPTION
**Pull request by johnthagen**
Closes #850

Follow on planned in #882 

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/881)

### CODE REVIEW

**Comment by johnthagen** [comment]
LGTM build failures unrelated and tracked in #883

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 12 of 14 files at r1, 10 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/881)* status: 22 of 24 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @johnthagen)

___
*[Backend/Services/ProjectApiServices.cs, line 50 at r2](https://reviewable.io/reviews/sillsdev/thecombine/881#-MP5CO0d6vwPcuzRwhm6:-MP5CO0d6vwPcuzRwhm7:bw7u4hk) ([raw file](https://github.com/sillsdev/thecombine/blob/9c217cb8492b521b47c06de1ea3a3edc4e388a7c/Backend/Services/ProjectApiServices.cs#L50)):*
> ```Smalltalk
> 
>             var projectList = await _projectDatabase.Projects.FindAsync(filter);
>             return await projectList.FirstAsync();
> ```

Does `FirstAsync` return null in the case of an empty list or throw an exception?

**Review by jmgrady — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/881)* status: 23 of 24 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @johnthagen)

___
*[Backend/Services/ProjectApiServices.cs, line 50 at r2](https://reviewable.io/reviews/sillsdev/thecombine/881#-MP5CO0d6vwPcuzRwhm6:-MP5_2xwBBj4ZhsEFcrg:b-oe9ljs) ([raw file](https://github.com/sillsdev/thecombine/blob/9c217cb8492b521b47c06de1ea3a3edc4e388a7c/Backend/Services/ProjectApiServices.cs#L50)):*
https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.queryableextensions.firstasync?view=entity-framework-6.2.0 states

> Exceptions
> ...
> InvalidOperationException
> No element satisfies the condition in predicate .

but this assumes that IAsyncCursorSourceExtensions works as a _QueryableExtension_

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/881)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Review by jmgrady — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/881)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jmgrady — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/881#-:-MP5tDTl9AG0hEOVnF9O:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
