### PR TITLE
[NewEntry] If duplicate, add note to existing

### PR DESCRIPTION
**Pull request by imnasnainaec**
The "Note" part of #1584

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1615)

### CODE REVIEW

**Comment by johnthagen** [comment]
Hit #1579 while testing this issue.

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/DataEntryTable.tsx, line 167 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MyS495m8mv_8ySy95kG:-MyS495nBVvfaKSN7jmb:b-6teu5o) ([raw file](https://github.com/sillsdev/thecombine/blob/0e279783fb29056e64f5c42a52d66c99a4f67b71/src/components/DataEntry/DataEntryTable/DataEntryTable.tsx#L167)):*
> ```XML
>       return;
>     }
>     // TODO: add the audio even if the word is a duplicate
> ```

The frontend does not update the existing field in the Data Entry if a note is added this way. This may be an edge case that is not super important if this is complex to fix.

In the following screenshot, I added another `x`/`y` entry with a note. I got the alert that it exists in the database, and the Note is added in the backend, but the frontend UI doesn't show that the Note exists (i.e. the note icon doesn't change and its hover text doesn't display the note).

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/DataEntryTable.tsx, line 167 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MyS495m8mv_8ySy95kG:-MyS4vYd-XKe66JqWxGc:bdf53ed) ([raw file](https://github.com/sillsdev/thecombine/blob/0e279783fb29056e64f5c42a52d66c99a4f67b71/src/components/DataEntry/DataEntryTable/DataEntryTable.tsx#L167)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

The frontend does not update the existing field in the Data Entry if a note is added this way. This may be an edge case that is not super important if this is complex to fix.

In the following screenshot, I added another `x`/`y` entry with a note. I got the alert that it exists in the database, and the Note is added in the backend, but the frontend UI doesn't show that the Note exists (i.e. the note icon doesn't change and its hover text doesn't display the note).



</blockquote></details>

In review entries, I _do_ see the note added (confirming that the backend is doing the correct thing in the background).

**Comment by imnasnainaec** [comment]
> _[src/components/DataEntry/DataEntryTable/DataEntryTable.tsx, line 167 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MyS495m8mv_8ySy95kG:-MyS495nBVvfaKSN7jmb:b-6teu5o) ([raw file](https://github.com/sillsdev/thecombine/blob/0e279783fb29056e64f5c42a52d66c99a4f67b71/src/components/DataEntry/DataEntryTable/DataEntryTable.tsx#L167)):_
> 
> > ```
> >       return;
> >     }
> >     // TODO: add the audio even if the word is a duplicate
> > ```
> 
> The frontend does not update the existing field in the Data Entry if a note is added this way. This may be an edge case that is not super important if this is complex to fix.
> 
> In the following screenshot, I added another `x`/`y` entry with a note. I got the alert that it exists in the database, and the Note is added in the backend, but the frontend UI doesn't show that the Note exists (i.e. the note icon doesn't change and its hover text doesn't display the note).

That's may fall in the realm of #1586

**Comment by johnthagen** [comment]
___
*[Backend/Models/Word.cs, line 247 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MyS5O0Y15j9BT2W4rzo:-MyS5O0Y15j9BT2W4rzp:b-hgh7gw) ([raw file](https://github.com/sillsdev/thecombine/blob/0e279783fb29056e64f5c42a52d66c99a4f67b71/Backend/Models/Word.cs#L247)):*
> ```Smalltalk
> 
>         /// <summary> Add another note to the existing note. </summary>
>         public void Add(Note note)
> ```

Perhaps a more explicit name would be `Append`?

**Comment by johnthagen** [comment]
___
*[Backend/Models/Word.cs, line 261 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MyS5TWo37VVI3xoZm03:-MyS5TWo37VVI3xoZm04:b-jgoei3) ([raw file](https://github.com/sillsdev/thecombine/blob/0e279783fb29056e64f5c42a52d66c99a4f67b71/Backend/Models/Word.cs#L261)):*
> ```Smalltalk
>                     if (Language != note.Language)
>                     {
>                         Text += String.Format("[{0}] ", note.Language);
> ```

This can be simplified to:

```cs
Text += $"[{note.Language}] ";
```

**Comment by johnthagen** [comment]
___
*[Backend/Models/Word.cs, line 261 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MyS5TWo37VVI3xoZm03:-MyS6O7O1k_hO4S2Liq0:bqmqsi5) ([raw file](https://github.com/sillsdev/thecombine/blob/0e279783fb29056e64f5c42a52d66c99a4f67b71/Backend/Models/Word.cs#L261)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This can be simplified to:

```cs
Text += $"[{note.Language}] ";
```
</blockquote></details>

I would actually simplify the entire `else` to:

```cs
                    var langTag = Language != note.Language ? "" : $"[{note.Language}] " ;
                    Text += $"; {langTag}{note.Text}";
```

**Comment by johnthagen** [comment]
___
*[Backend/Models/Word.cs, line 261 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MyS5TWo37VVI3xoZm03:-MyS6htK4fztZgCAQkNu:b-h8slg) ([raw file](https://github.com/sillsdev/thecombine/blob/0e279783fb29056e64f5c42a52d66c99a4f67b71/Backend/Models/Word.cs#L261)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I would actually simplify the entire `else` to:

```cs
                    var langTag = Language != note.Language ? "" : $"[{note.Language}] " ;
                    Text += $"; {langTag}{note.Text}";
```
</blockquote></details>

To refactor the whole function to reduce nesting:

```cs
        public void Add(Note note)
        {
            if (note.IsBlank() || Equals(note))
            {
                return;
            }

            if (IsBlank())
            {
                Language = note.Language;
                Text = note.Text;
            }
            else
            {
                var langTag = Language != note.Language ? "" : $"[{note.Language}] ";
                Text += $"; {langTag}{note.Text}";
            }
        }
```

**Comment by johnthagen** [comment]
___
*[Backend/Services/WordService.cs, line 1 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MyS6vItEb9A7x4gJI6y:-MyS6vItEb9A7x4gJI6z:bpy5xz8) ([raw file](https://github.com/sillsdev/thecombine/blob/0e279783fb29056e64f5c42a52d66c99a4f67b71/Backend/Services/WordService.cs#L1)):*
> ```Smalltalk
> using System;
> ```

Unused import.

**Comment by johnthagen** [comment]
___
*[Backend/Services/WordService.cs, line 186 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MyS76xz7Z5H8Wi-7Rs7:-MyS76xz7Z5H8Wi-7Rs8:b-ypl2tm) ([raw file](https://github.com/sillsdev/thecombine/blob/0e279783fb29056e64f5c42a52d66c99a4f67b71/Backend/Services/WordService.cs#L186)):*
> ```Smalltalk
>                             matchingVern.EditedBy = matchingVern.EditedBy.Distinct().ToList();
> 
>                             // Add note
> ```

This comment is not very useful as it duplicates the same information that exists in the next line. Could it be improved or removed?

**Comment by johnthagen** [comment]
___
*[Backend.Tests/Models/WordTests.cs, line 132 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MyS7ZSzCshJ_wPvvQJf:-MyS7ZSzCshJ_wPvvQJg:bif37zz) ([raw file](https://github.com/sillsdev/thecombine/blob/0e279783fb29056e64f5c42a52d66c99a4f67b71/Backend.Tests/Models/WordTests.cs#L132)):*
> ```Smalltalk
>             oldNote.Add(newNote);
>             var expectedNote = note.Clone();
>             expectedNote.Text += "; " + newText;
> ```

Simplify to

```cs
expectedNote.Text += $"; {newText}";
```

**Comment by johnthagen** [comment]
___
*[Backend.Tests/Models/WordTests.cs, line 146 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MyS7eB6ANudOrQSly7w:-MyS7eB6ANudOrQSly7x:b-m1o37f) ([raw file](https://github.com/sillsdev/thecombine/blob/0e279783fb29056e64f5c42a52d66c99a4f67b71/Backend.Tests/Models/WordTests.cs#L146)):*
> ```Smalltalk
>             oldNote.Add(newNote);
>             var expectedNote = note.Clone();
>             expectedNote.Text += "; [" + newLanguage + "] " + newNote.Text;
> ```

Simplify to 

```cs
expectedNote.Text += $"; [{newLanguage}] {newNote.Text}";
```

**Comment by johnthagen** [comment]
___
*[Backend/Services/WordService.cs, line 187 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MyS7ywd36cmeywpIv06:-MyS7ywd36cmeywpIv07:b1w9v09) ([raw file](https://github.com/sillsdev/thecombine/blob/0e279783fb29056e64f5c42a52d66c99a4f67b71/Backend/Services/WordService.cs#L187)):*
> ```Smalltalk
> 
>                             // Add note
>                             matchingVern.Note.Add(word.Note);
> ```

Can we add a test(s) to `WordServiceTests.cs` to ensure that the `Service` itself actually adds the Note as expected (i.e. test `WordIsUnique`)?

Another thing that feels a little odd semantically is that `WordIsUnique` seems like a read-only checking function, but in reality it is now (or maybe it was before as well?) mutating the `Word` that is being checked.

This seems like too much going on in one function. We should probably at least change the name to make it obvious that mutation is happening, or (ideally) pull the mutation logic out into a separate function that runs after uniqueness is checked (e.g. `UpdateUniqueWord` etc.)

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/DataEntryTable.tsx, line 167 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MyS495m8mv_8ySy95kG:-MyS8rRq1sLZ7ymEQAqE:bniix9p) ([raw file](https://github.com/sillsdev/thecombine/blob/0e279783fb29056e64f5c42a52d66c99a4f67b71/src/components/DataEntry/DataEntryTable/DataEntryTable.tsx#L167)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

That may fall in the realm of #1586 
</blockquote></details>

Agreed. I added a note to the issue with this condition.

**Review by johnthagen — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1615)* status: 2 of 4 files reviewed, 8 unresolved discussions (waiting on @imnasnainaec and @johnthagen)

**Comment by johnthagen** [comment]
___
*[Backend/Models/Word.cs, line 247 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MyS5O0Y15j9BT2W4rzo:-MySEDe4BA5QgYcKSigZ:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/0e279783fb29056e64f5c42a52d66c99a4f67b71/Backend/Models/Word.cs#L247)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Perhaps a more explicit name would be `Append`?
</blockquote></details>

Done.

**Comment by johnthagen** [comment]
___
*[Backend/Models/Word.cs, line 261 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MyS5TWo37VVI3xoZm03:-MySEFqhB4-i-BVfHGYV:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/0e279783fb29056e64f5c42a52d66c99a4f67b71/Backend/Models/Word.cs#L261)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

To refactor the whole function to reduce nesting:

```cs
        public void Add(Note note)
        {
            if (note.IsBlank() || Equals(note))
            {
                return;
            }

            if (IsBlank())
            {
                Language = note.Language;
                Text = note.Text;
            }
            else
            {
                var langTag = Language != note.Language ? "" : $"[{note.Language}] ";
                Text += $"; {langTag}{note.Text}";
            }
        }
```
</blockquote></details>

Done.

**Comment by johnthagen** [comment]
___
*[Backend/Services/WordService.cs, line 1 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MyS6vItEb9A7x4gJI6y:-MySEHVJ39xgCzIzI6uw:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/0e279783fb29056e64f5c42a52d66c99a4f67b71/Backend/Services/WordService.cs#L1)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Unused import.
</blockquote></details>

Done.

**Comment by johnthagen** [comment]
___
*[Backend/Services/WordService.cs, line 186 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MyS76xz7Z5H8Wi-7Rs7:-MySEIXO5tJlz02-i79x:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/0e279783fb29056e64f5c42a52d66c99a4f67b71/Backend/Services/WordService.cs#L186)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This comment is not very useful as it duplicates the same information that exists in the next line. Could it be improved or removed?
</blockquote></details>

Done.

**Comment by johnthagen** [comment]
___
*[Backend.Tests/Models/WordTests.cs, line 128 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MyS7Qj_5jZcHiMqHLkL:-MySELSg9HEzFWE6Nx9k:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/0e279783fb29056e64f5c42a52d66c99a4f67b71/Backend.Tests/Models/WordTests.cs#L128)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Can be `const`
</blockquote></details>

Done.

**Comment by johnthagen** [comment]
___
*[Backend.Tests/Models/WordTests.cs, line 132 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MyS7ZSzCshJ_wPvvQJf:-MySEMj_8oaVlC648d5m:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/0e279783fb29056e64f5c42a52d66c99a4f67b71/Backend.Tests/Models/WordTests.cs#L132)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Simplify to

```cs
expectedNote.Text += $"; {newText}";
```
</blockquote></details>

Done.

**Comment by johnthagen** [comment]
___
*[Backend.Tests/Models/WordTests.cs, line 146 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MyS7eB6ANudOrQSly7w:-MySEOQi483myxYgRhg4:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/0e279783fb29056e64f5c42a52d66c99a4f67b71/Backend.Tests/Models/WordTests.cs#L146)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Simplify to 

```cs
expectedNote.Text += $"; [{newLanguage}] {newNote.Text}";
```
</blockquote></details>

Done.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1615)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[Backend/Models/Word.cs, line 261 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MyS5TWo37VVI3xoZm03:-MySBLCt8sjB0AUtYejz:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/0e279783fb29056e64f5c42a52d66c99a4f67b71/Backend/Models/Word.cs#L261)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

To refactor the whole function to reduce nesting:

```cs
        public void Add(Note note)
        {
            if (note.IsBlank() || Equals(note))
            {
                return;
            }

            if (IsBlank())
            {
                Language = note.Language;
                Text = note.Text;
            }
            else
            {
                var langTag = Language != note.Language ? "" : $"[{note.Language}] ";
                Text += $"; {langTag}{note.Text}";
            }
        }
```
</blockquote></details>

Done.
___
*[Backend/Services/WordService.cs, line 1 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MyS6vItEb9A7x4gJI6y:-MySBMQl1xF_DSHK5IYK:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/0e279783fb29056e64f5c42a52d66c99a4f67b71/Backend/Services/WordService.cs#L1)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Unused import.
</blockquote></details>

Done.
___
*[Backend/Services/WordService.cs, line 187 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MyS7ywd36cmeywpIv06:-MySEB4-DtHVD16Vm9b4:b-38sq0e) ([raw file](https://github.com/sillsdev/thecombine/blob/0e279783fb29056e64f5c42a52d66c99a4f67b71/Backend/Services/WordService.cs#L187)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Can we add a test(s) to `WordServiceTests.cs` to ensure that the `Service` itself actually adds the Note as expected (i.e. test `WordIsUnique`)?

Another thing that feels a little odd semantically is that `WordIsUnique` seems like a read-only checking function, but in reality it is now (or maybe it was before as well?) mutating the `Word` that is being checked.

This seems like too much going on in one function. We should probably at least change the name to make it obvious that mutation is happening, or (ideally) pull the mutation logic out into a separate function that runs after uniqueness is checked (e.g. `UpdateUniqueWord` etc.)
</blockquote></details>

Improved comments. Since the "Audio" side of #1584 will require a refactor of `WordIsUnique` (to return more than a boolean, at the very least), splitting the identification of a duplicate and the mutation of the word being duplicated into two functions could be added to that task.
___
*[Backend.Tests/Models/WordTests.cs, line 128 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MyS7Qj_5jZcHiMqHLkL:-MySBOqS7G4QmtZXLn3z:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/0e279783fb29056e64f5c42a52d66c99a4f67b71/Backend.Tests/Models/WordTests.cs#L128)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Can be `const`
</blockquote></details>

Done.
___
*[Backend.Tests/Models/WordTests.cs, line 132 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MyS7ZSzCshJ_wPvvQJf:-MySBQT6A-m2Zw61HjsD:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/0e279783fb29056e64f5c42a52d66c99a4f67b71/Backend.Tests/Models/WordTests.cs#L132)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Simplify to

```cs
expectedNote.Text += $"; {newText}";
```
</blockquote></details>

Done.
___
*[Backend.Tests/Models/WordTests.cs, line 146 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MyS7eB6ANudOrQSly7w:-MySBSik-ypaE5o_EReZ:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/0e279783fb29056e64f5c42a52d66c99a4f67b71/Backend.Tests/Models/WordTests.cs#L146)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Simplify to 

```cs
expectedNote.Text += $"; [{newLanguage}] {newNote.Text}";
```
</blockquote></details>

Done.

**Comment by johnthagen** [comment]
___
*[Backend/Services/WordService.cs, line 187 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MyS7ywd36cmeywpIv06:-MySFGJp3L_u6DSHIFZT:bitck3q) ([raw file](https://github.com/sillsdev/thecombine/blob/0e279783fb29056e64f5c42a52d66c99a4f67b71/Backend/Services/WordService.cs#L187)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Improved comments. Since the "Audio" side of #1584 will require a refactor of `WordIsUnique` (to return more than a boolean, at the very least), splitting the identification of a duplicate and the mutation of the word being duplicated into two functions could be added to that task.
</blockquote></details>

Sounds good.

I added a comment to #1584 about this thread.

**Comment by johnthagen** [comment]
___
*[Backend/Services/WordService.cs, line 184 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MySFQfwD-irgEX37j_o:-MySFQfwD-irgEX37j_p:bd7wvae) ([raw file](https://github.com/sillsdev/thecombine/blob/c91c18ce34b805cf709c8c28469809d671beaf96/Backend/Services/WordService.cs#L184)):*
> ```Smalltalk
>                             foundDuplicateSense = true;
> 
>                             oldSense.SemanticDomains.AddRange(newSense.SemanticDomains);
> ```

@imnasnainaec Could we still add a test for `WordServices` that ensures the that the `Note` is appended by the service?

**Review by johnthagen — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1615)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1615)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @johnthagen)

___
*[Backend/Services/WordService.cs, line 184 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1615#-MySFQfwD-irgEX37j_o:-MySIvBy32lIQZjmQRWL:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/c91c18ce34b805cf709c8c28469809d671beaf96/Backend/Services/WordService.cs#L184)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

@imnasnainaec Could we still add a test for `WordServices` that ensures the that the `Note` is appended by the service?
</blockquote></details>

Done.

**Review by johnthagen — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1615)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
