### PR TITLE
Automatically extract languages from import data

### LINKED ISSUE #1336: [CreateProject] When importing, auto-select language from data
Also, disable language selection if file selected.

"18. L [Create Project] If importing from LIFT, should not ask for WS info.  It needs to get that from the LIFT project, so they will be sure to match."

### LINKED ISSUE #1644: Character Inventory Not Importing
**Describe the bug**

The character inventory of an exported project is not maintained when the lift file is re-imported in a fresh project.

**To Reproduce**

1. Open a project, and in Data Cleanup, click Create Character Inventory
2. Accept at least one character, and click Save at the bottom
3. Go to project settings, scroll down to Export Project, and click the Export button
4. Once the export is saved to your computer, click on The Combine logo in the upper-left corner to go to the Select Project / Create Project screen
5. In Create Project on the right, browse for the .zip file just exported (fill in anything for project name and languages)
6. Click the Create Project button, then Data Entry > Create Character Inventory
7. Observe that the character Accepted before export is now Undecided.

**Expected behavior**

Importing should preserve any character inventory that is exported.

**Current behavior**

See how we [import](https://github.com/sillsdev/TheCombine/blob/master/Backend/Services/LiftService.cs#L159-L164) and [export](https://github.com/sillsdev/TheCombine/blob/master/Backend/Services/LiftService.cs#L466-L472) the Character Inventory.

**UPDATE**

The accepted characters are imported, but only if the language code for the importing project's vernacular language matches the ldml filename in the LIFT import `WritingSystems/[lang-tag].ldml`. Thus this issue is related to #1336 and #2101.

### LINKED ISSUE #2101: Improve handling of importing a project with multiple vernacular writing systems
Currently, a user must choose a single vernacular writing system for their project, and the language tag for that writing system is automatically applied to all new word. When a project is imported, if a word has multiple vernacular writing systems in use, just the first one on the list is selected for import and the rest are ignored.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #1336 
Resolves #1644
Resolves #2101 

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2306)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2306)* status: 0 of 23 files reviewed, 1 unresolved discussion (waiting on @github-code-scanning[bot] and @imnasnainaec)

___
*[`Backend/Controllers/LiftController.cs` line 224 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2306#gh-1237787176:-NYrkwA-1eI__1IGVYxZ:bf9p29g) ([raw file](https://github.com/sillsdev/TheCombine/blob/5fe0500482a342626e8acc5cb556b078e16b142f/Backend/Controllers/LiftController.cs#L224)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Log entries created from user input

This log entry depends on a [user-provided value](1).
This log entry depends on a [user-provided value](2).

[Show more details](https://github.com/sillsdev/TheCombine/security/code-scanning/132)
</blockquote></details>

False positive, since we make sure `projectId` is sanitized at the top of the function.

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 4 of 19 files at r3, 2 of 3 files at r6, 1 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2306)* status: 7 of 23 files reviewed, 2 unresolved discussions (waiting on @github-code-scanning[bot] and @imnasnainaec)

___
*[`Backend/Helper/Language.cs` line 43 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2306#-NYtQiVY0du5G-aCj5hD:-NYtQiVZ6vQktx75xZ3B:bmpuweo) ([raw file](https://github.com/sillsdev/TheCombine/blob/83e529af867f0b79c3ecdd56c72daac28a472a22/Backend/Helper/Language.cs#L43)):*
> ```Smalltalk
>         /// Extract <see cref="WritingSystem"/>s from .ldml files in a directory or its WritingSystems subdirectory.
>         /// </summary>
>         public static IEnumerable<WritingSystem> GetVernacularWritingSystems(string dirPath)
> ```

This function name is misleading since the .ldml files will be both vernacular and analysis.

**Review by jasonleenaylor — COMMENTED** [review]
I wonder if we might have a new address needed in the harden-runner for running the backend tests now that you are initializing the SLDR?

> Reviewed 1 of 10 files at r2, 1 of 19 files at r3, 1 of 3 files at r6, 1 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2306#-:-NYxMwglCMPw6cQT-RU8:b-kcvcew)* status: 11 of 23 files reviewed, 2 unresolved discussions (waiting on @github-code-scanning[bot] and @imnasnainaec)

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 1 of 10 files at r2, 3 of 19 files at r3, 3 of 5 files at r4, 2 of 4 files at r5, 3 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2306)* status: all files reviewed, 2 unresolved discussions (waiting on @github-code-scanning[bot] and @imnasnainaec)

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2306)* status: all files reviewed, 2 unresolved discussions (waiting on @github-code-scanning[bot])

**Review by imnasnainaec — COMMENTED** [review]
> Dismissed @github-code-scanning[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2306)* status: all files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor)

**Pull request merged**
