### PR TITLE
Fix backend LGTM issues and organize unit tests

### PR DESCRIPTION
**Pull request by johnthagen**
- Fix backend LGTM issues
- Organize backend unit test files by namespace to declutter namespace and make it easier to see what things are and aren't tested
- Add Model unit test files
- Increase test coverage of Model classes

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/687)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 14 of 31 files at r1, 2 of 2 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/687)* status: 22 of 32 files reviewed, all discussions resolved (waiting on @johnthagen)

___
*[Backend/Models/Project.cs, line 285 at r3](https://reviewable.io/reviews/sillsdev/thecombine/687#-MGOOXqx3MSLpfwtGE_y:-MGOOXqx3MSLpfwtGE_z:bkjph67) ([raw file](https://github.com/sillsdev/thecombine/blob/64145fe34df5b3f55c1dc5ebf48dd772e4633f65/Backend/Models/Project.cs#L285)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>         public override bool Equals(object obj)
>         {
>             if (obj == null || !GetType().Equals(obj.GetType()))
>             {
>                 return false;
>             }
>             else
>             {
>                 var ws = obj as WritingSystem;
> ```
</details>

Should this be rewritten in the same style as the `Equals()` in the `class Project` above?

**Comment by johnthagen** [comment]
___
*[Backend/Models/Project.cs, line 285 at r3](https://reviewable.io/reviews/sillsdev/thecombine/687#-MGOOXqx3MSLpfwtGE_y:-MGOVH4uA5vMOg28vLqg:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/64145fe34df5b3f55c1dc5ebf48dd772e4633f65/Backend/Models/Project.cs#L285)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>         public override bool Equals(object obj)
>         {
>             if (obj == null || !GetType().Equals(obj.GetType()))
>             {
>                 return false;
>             }
>             else
>             {
>                 var ws = obj as WritingSystem;
> ```
Should this be rewritten in the same style as the `Equals()` in the `class Project` above?
</blockquote></details>

Done

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 4 of 31 files at r1, 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/687)* status: 27 of 32 files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[Backend/Models/UserEdit.cs, line 65 at r5](https://reviewable.io/reviews/sillsdev/thecombine/687#-MGOa1kIAYKb5yvMVkDu:-MGOa1kJ55kLt6LERJdz:b85ud5q) ([raw file](https://github.com/sillsdev/thecombine/blob/7a05a620db737aebe44159538450961937278b77/Backend/Models/UserEdit.cs#L65)):*
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>

> ```
>         public override bool Equals(object obj)
>         {
>             if (obj == null || !GetType().Equals(obj.GetType()))
>             {
>                 return false;
>             }
>             else
>             {
>                 var other = obj as UserEdit;
>                 return other.Id.Equals(Id) && ContentEquals(other);
>             }
>         }
> ```
</details>

Last one.
___
*[Backend.Tests/Models/WordTests.cs, line 28 at r5](https://reviewable.io/reviews/sillsdev/thecombine/687#-MGOaQNH-1i3pOC_SmtF:-MGOaQNH-1i3pOC_SmtG:bnoylgg) ([raw file](https://github.com/sillsdev/thecombine/blob/7a05a620db737aebe44159538450961937278b77/Backend.Tests/Models/WordTests.cs#L28)):*
<details><summary><i alt="summary">Quoted 17 lines of code…</i></summary>

> ```
>         private const string Vernacular = "Fr";
>         [Test]
>         public void TestEquals()
>         {
>             var word = new Word { Vernacular = Vernacular };
>             Assert.That(word.Equals(new Word { Vernacular = Vernacular }));
>         }
>         [Test]
>         public void TestEqualsNull()
>         {
>             var word = new Word { Vernacular = Vernacular };
>             Assert.IsFalse(word.Equals(null));
>         }
>     }
>     public class GlossTests
>     {
>         private const string Language = "Fr";
> ```
</details>

A more realistic language string is "fr", but that hardly matters for the test.

**Comment by johnthagen** [comment]
___
*[Backend/Models/UserEdit.cs, line 65 at r5](https://reviewable.io/reviews/sillsdev/thecombine/687#-MGOa1kIAYKb5yvMVkDu:-MGOh6Wb3QYK2lv43XTx:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7a05a620db737aebe44159538450961937278b77/Backend/Models/UserEdit.cs#L65)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>         public override bool Equals(object obj)
>         {
>             if (obj == null || !GetType().Equals(obj.GetType()))
>             {
>                 return false;
>             }
>             else
>             {
>                 var other = obj as UserEdit;
>                 return other.Id.Equals(Id) && ContentEquals(other);
>             }
>         }
> ```
Last one.
</blockquote></details>

Done.

**Comment by johnthagen** [comment]
___
*[Backend.Tests/Models/WordTests.cs, line 28 at r5](https://reviewable.io/reviews/sillsdev/thecombine/687#-MGOaQNH-1i3pOC_SmtF:-MGOh7khB7L0ZaQJj51K:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/7a05a620db737aebe44159538450961937278b77/Backend.Tests/Models/WordTests.cs#L28)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>         private const string Vernacular = "Fr";
>         [Test]
>         public void TestEquals()
>         {
>             var word = new Word { Vernacular = Vernacular };
>             Assert.That(word.Equals(new Word { Vernacular = Vernacular }));
>         }
>         [Test]
>         public void TestEqualsNull()
>         {
>             var word = new Word { Vernacular = Vernacular };
>             Assert.IsFalse(word.Equals(null));
>         }
>     }
>     public class GlossTests
>     {
>         private const string Language = "Fr";
> ```
A more realistic language string is "fr", but that hardly matters for the test.
</blockquote></details>

Done

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 3 of 31 files at r1, 1 of 3 files at r5, 2 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/687)* status: 31 of 32 files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[Backend.Tests/Models/WordTests.cs, line 28 at r5](https://reviewable.io/reviews/sillsdev/thecombine/687#-MGOaQNH-1i3pOC_SmtF:-MGOhtzGD5fz4xduXibP:b2jcpp9) ([raw file](https://github.com/sillsdev/thecombine/blob/7a05a620db737aebe44159538450961937278b77/Backend.Tests/Models/WordTests.cs#L28)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Done
</blockquote></details>

Sorry, but now you have "fr" in one place and "Fr" in another. (I probably shouldn't've said anything in the first place, but now that they are different...)

**Comment by johnthagen** [comment]
___
*[Backend.Tests/Models/WordTests.cs, line 28 at r5](https://reviewable.io/reviews/sillsdev/thecombine/687#-MGOaQNH-1i3pOC_SmtF:-MGOjWDd7UEv-ENUCpI1:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/7a05a620db737aebe44159538450961937278b77/Backend.Tests/Models/WordTests.cs#L28)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Sorry, but now you have "fr" in one place and "Fr" in another. (I probably shouldn't've said anything in the first place, but now that they are different...)
</blockquote></details>

Done

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 3 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/687)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by imnasnainaec — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/687#-:-MGOjYdF2ZIXeqMqK4Ay:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
