### PR TITLE
Site Settings | Project Management

### LINKED ISSUE #455: Site Settings needs fixes/improvements to project management
Site Settings has a partially implemented list of all projects. Currently, if you click on a project, that project is activated and a button appears that allows you to export the project. The administrative user shouldn't have to click on any of the projects to export or delete them.

image

ToDo:
- [x] Implement a functional export button by every project.
  -  The `exportLift` function in `src/backend/index.tsx` has already been generalized for this purpose, but `src/components/ProjectSettings/ProjectExport/ExportProjectButton.tsx` needs to be generalized.
- [ ] Unit tests for the export buttons
  - Perhaps one test that checking that a mocked backend export function is called and another testing that every button is linked to a unique project
- [x] Implement a functional delete button for each project after the import button.
  - Make sure there is a warning popup for the admin user to confirm deletion.
- [ ] Unit tests for the delete buttons
  - Same as for the export but also with a test or two for the popup
- [x] Remove the button functionality on the project names, so project selection is no longer required.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #455
Replaces #464 

ToDo:
- [x] Add "Active" to projects in the backend and "active" in frontend (both default true)
- [x] Export-by-project-id button
- [x] Delete-by-project-id and Restore-by-project-id buttons
- [x] Format project names: remove button; change color for deleted projects
- [x] Refresh Site Settings project list when project is deleted/restored
- [x] Fix project list generation for users
   - Ignore errors (e.g., when project doesn't exist or is corrupted)
   - Ignore projects with active=false (i.e., deleted)
- [x] Front-end unit tests
- [x] Scripts for updating old projects (mark as active)

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/489)

### CODE REVIEW

**Comment by imnasnainaec** [comment]
This update will not work with old projects, so only try it if you are willing to flush your mongo database.

**Comment by imnasnainaec** [comment]
Having changed a property of projects in the backend, does anything need to be done differently for importing projects?

**Comment by imnasnainaec** [comment]
To add `active: true` to all previous projects from the command-line:
$ `mongo CombineDatabase`
\> `db.ProjectsCollection.update({active: {$exists: false}}, {$set: {"active": true}}, {multi: true})`

**Comment by johnthagen** [comment]
___
*[Backend/Models/Project.cs, line 21 at r2](https://reviewable.io/reviews/sillsdev/thecombine/489#-MBt_50N33geoMTGpqJx:-MBt_50N33geoMTGpqJy:b-6vcrk8) ([raw file](https://github.com/sillsdev/thecombine/blob/67036446753a4de0cd705368645476e233bb4dce/Backend/Models/Project.cs#L21)):*
> ```Smalltalk
> 
>         [BsonElement("active")]
>         public bool Active { get; set; }
> ```

I think `IsActive` might be a bit more descriptive? We have something similar in `User.IsAdmin`.

**Comment by johnthagen** [comment]
Permissions-wise, this looks good 👍 . In order to perform an update and change `Active`, the user needs `Permission.DeleteEditSettingsAndUsers` which seems totally appropriate (the user already has permission to *actually* delete the project after all). This is enforced in the `ProjectController`.

**Comment by johnthagen** [comment]
___
*[src/types/project.tsx, line 30 at r2](https://reviewable.io/reviews/sillsdev/thecombine/489#-MBtbbzK8RnUonHL1hUb:-MBtbbzL1Hfj9mNO5MDf:bjfsk9u) ([raw file](https://github.com/sillsdev/thecombine/blob/67036446753a4de0cd705368645476e233bb4dce/src/types/project.tsx#L30)):*
> ```XML
>   id: "",
>   name: "",
>   active: true,
> ```

Similar to my comment in the backend, I think `isActive` would read a bit better for a `bool` type.

**Comment by johnthagen** [comment]
___
*[src/types/project.tsx, line 30 at r2](https://reviewable.io/reviews/sillsdev/thecombine/489#-MBtbbzK8RnUonHL1hUb:-MBtbmaI7EKhuaWWglE4:bq0qn6) ([raw file](https://github.com/sillsdev/thecombine/blob/9ce3188b4755a41507769ab4102cb0455f95b2b6/src/types/project.tsx#L30)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Similar to my comment in the backend, I think `isActive` would read a bit better for a `bool` type.
</blockquote></details>

(same for the `interface` above)

**Comment by johnthagen** [comment]
___
*[src/backend/index.tsx, line 230 at r2](https://reviewable.io/reviews/sillsdev/thecombine/489#-MBtc-Yt41NL0wdr-NGN:-MBtc-Yt41NL0wdr-NGO:bkqm4xh) ([raw file](https://github.com/sillsdev/thecombine/blob/9ce3188b4755a41507769ab4102cb0455f95b2b6/src/backend/index.tsx#L230)):*
> ```XML
> }
> 
> export async function deleteProject(id: string) {
> ```

Someone who didn't know the internals of how this worked would probably think `delete` actually meant `delete`. Perhaps we should use "archived"/"restored", or "deactivate"/"reactivate"?

**Comment by johnthagen** [comment]
___
*[src/components/SiteSettings/ProjectManagement/RestoreProjectButton.tsx, line 24 at r2](https://reviewable.io/reviews/sillsdev/thecombine/489#-MBtfxqB2kgu7TTT5HZ_:-MBtfxqB2kgu7TTT5HZa:b-57v04a) ([raw file](https://github.com/sillsdev/thecombine/blob/9ce3188b4755a41507769ab4102cb0455f95b2b6/src/components/SiteSettings/ProjectManagement/RestoreProjectButton.tsx#L24)):*
> ```XML
>  * Button for restoring a deleted project (setting active=true)
>  */
> export default function ExportProjectButton(
> ```

Was this a copy-paste mistake? Should it be `RestoreProjectButton`?

**Comment by johnthagen** [comment]
___
*[src/components/SiteSettings/ProjectManagement/tests/ProjectManagement.test.tsx, line 12 at r2](https://reviewable.io/reviews/sillsdev/thecombine/489#-MBtgF4Y3uk-sqGUAGBH:-MBtgF4Y3uk-sqGUAGBI:byai5ew) ([raw file](https://github.com/sillsdev/thecombine/blob/9ce3188b4755a41507769ab4102cb0455f95b2b6/src/components/SiteSettings/ProjectManagement/tests/ProjectManagement.test.tsx#L12)):*
> ```XML
> import DeleteProjectButton from "../DeleteProjectButton";
> import ProjectManagement from "../ProjectManagement";
> import RestoreProjectButton from "../RestoreProjectButton";
> ```

Thank you for sorting and grouping your imports.

**Comment by johnthagen** [comment]
___
*[src/types/AutoComplete.tsx, line 7 at r2](https://reviewable.io/reviews/sillsdev/thecombine/489#-MBtgnDpB6ZpXAYTR3aQ:-MBtgnDpB6ZpXAYTR3aR:by3fp8j) ([raw file](https://github.com/sillsdev/thecombine/blob/9ce3188b4755a41507769ab4102cb0455f95b2b6/src/types/AutoComplete.tsx#L7)):*
> ```XML
> }
> 
> export function randomAutoComplete(): AutoComplete {
> ```

Could a doc comment be added to explain the purpose/function of this function?

**Comment by johnthagen** [comment]
___
*[addIsActivePropToAllProjects.ts, line 1 at r3](https://reviewable.io/reviews/sillsdev/thecombine/489#-MBu6a8x0HZn2WxVfLnS:-MBu6a8x0HZn2WxVfLnT:be4bo6x) ([raw file](https://github.com/sillsdev/thecombine/blob/7631764fd80348c8048c9f77f0d30e9fa0f10fee/addIsActivePropToAllProjects.ts#L1)):*
> ```XML
> import { spawnSync } from "child_process";
> ```

We probably want to add a note some where to remove this script eventually so as to not clutter up the repo. I almost wonder if this should be outside this PR and supplied to Jim in a branch or something else we don't merge. Hopefully this script is only ever used once by Jim and we move on.

**Comment by johnthagen** [comment]
___
*[README.md, line 145 at r3](https://reviewable.io/reviews/sillsdev/thecombine/489#-MBu6ylR87_4_YT5tWUr:-MBu6ylR87_4_YT5tWUs:b9rny9h) ([raw file](https://github.com/sillsdev/thecombine/blob/7631764fd80348c8048c9f77f0d30e9fa0f10fee/README.md#L145)):*
> ```Markdown
> ```
> 
> ### Add property `isActive: true` to every project in the database
> ```

Same comment as before. I'm not sure we want to commit these backwards-compatibility shims to master, but supply them in some other way to Jim as he's the only person that should need them. Maybe the Project's GitHub wiki could have a page for this?

**Comment by johnthagen** [comment]
___
*[package.json, line 6 at r3](https://reviewable.io/reviews/sillsdev/thecombine/489#-MBu7hKL68ILup0s0imF:-MBu7hKM1ClFLUnW0kKU:bgjia81) ([raw file](https://github.com/sillsdev/thecombine/blob/7631764fd80348c8048c9f77f0d30e9fa0f10fee/package.json#L6)):*
> ```JSON
>   "private": true,
>   "scripts": {
>     "add-isactive-property-to-all-projects": "tsc addIsActivePropToAllProjects.ts && node addIsActivePropToAllProjects.js",
> ```

Same comment as other similar ones, I don't think we want to commit this into master. We should check with Jim if needs this or if just showing him the `mongo` command is sufficient.

**Comment by johnthagen** [comment]
___
*[README.md, line 59 at r3](https://reviewable.io/reviews/sillsdev/thecombine/489#-MBu7zva2vN9MT_oei7j:-MBu7zva2vN9MT_oei7k:b-izd0br) ([raw file](https://github.com/sillsdev/thecombine/blob/7631764fd80348c8048c9f77f0d30e9fa0f10fee/README.md#L59)):*
> ```Markdown
> 
> > Note: To avoid browser tabs from being opened automatically every time the frontend is launched, set
> > [`BROWSER=none`](https://create-react-app.dev/docs/advanced-configuration/) environment variable.
> ```

I've always wonder what the right convention is here, since all the Markdown renderers I've used support both. Your way is probably more correct. :+1:

**Comment by johnthagen** [comment]
Someone other than me should probably review the frontend changes as I don't feel particularly qualified.

**Comment by charjhall** [comment]
___
*[src/components/SiteSettings/ProjectManagement/ProjectManagement.tsx, line 30 at r5](https://reviewable.io/reviews/sillsdev/thecombine/489#-MCCaOez30MjJyYIqWWZ:-MCCaOez30MjJyYIqWW_:biy4d1t) ([raw file](https://github.com/sillsdev/thecombine/blob/e5014b9472ecd8123694ce4ed745d1b76e6f648c/src/components/SiteSettings/ProjectManagement/ProjectManagement.tsx#L30)):*
> ```
> setProjectId("");
> ```
This clears the current project, but when you are in the Site Settings screen, Data Entry and Data Cleanup are still available. Navigating to these from the Site Settings screen results in these screens rendering without a selected project

**Pull request merged**
