### PR TITLE
Dictionary splitting

### PR DESCRIPTION
**Pull request by imnasnainaec**
Part of #487

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2484)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 9 of 195 files at r1, 13 of 120 files at r2, 9 of 20 files at r3, 10 of 64 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2484)* status: 35 of 250 files reviewed, 3 unresolved discussions (waiting on @imnasnainaec)

___
*[`src/utilities/dictionaryLoader.ts` line 28 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2484#-NcY79k7DBMfEPXaRsmH:-NcY79k7DBMfEPXaRsmI:b-4lwybv) ([raw file](https://github.com/sillsdev/TheCombine/blob/1af88a3eee7c15e37787dab28ca2ac2cff7320bd/src/utilities/dictionaryLoader.ts#L28)):*
> ```XML
>     while (true) {
>       startCase = startArray.join("-");
>       if (!startCase || this.keys.includes(startCase)) {
> ```

Add a method comment that describes the algorithm and what start is expected to be.
___
*[`src/utilities/spellChecker.ts` line 53 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2484#-NcYAIYUAtMNYiGUkblt:-NcYAIYUAtMNYiGUkblu:bdkdt3x) ([raw file](https://github.com/sillsdev/TheCombine/blob/1af88a3eee7c15e37787dab28ca2ac2cff7320bd/src/utilities/spellChecker.ts#L53)):*
> ```XML
> 
>   // If the word string is multiple words (separated by spaces)
>   // find spelling suggestions for the last word.
> ```

Why the last?
___
*[`src/utilities/spellChecker.ts` line 62 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2484#-NcY9qK67lR4zKNcZBD4:-NcY9qK67lR4zKNcZBD5:bu8qxlf) ([raw file](https://github.com/sillsdev/TheCombine/blob/1af88a3eee7c15e37787dab28ca2ac2cff7320bd/src/utilities/spellChecker.ts#L62)):*
> ```XML
>     // Use of \p{L}\p{M}\p{N} here matches that in split_dictionary.py.
>     // Cf. https://en.wikipedia.org/wiki/Unicode_character_property
>     word = word.trimStart().replace(/[^\p{L}\p{M}\p{N}]*$/u, "");
> ```

Are you sure these regex unicode values are working?
I have had bad luck with javascript and unicode regex in the past. It didn't give an error, it just didn't work.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2484)* status: 35 of 250 files reviewed, 3 unresolved discussions (waiting on @jasonleenaylor)

___
*[`src/utilities/spellChecker.ts` line 53 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2484#-NcYAIYUAtMNYiGUkblt:-NcYES30AnIL1gCw8qVf:bjfad3c) ([raw file](https://github.com/sillsdev/TheCombine/blob/1af88a3eee7c15e37787dab28ca2ac2cff7320bd/src/utilities/spellChecker.ts#L53)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Why the last?
</blockquote></details>

That was what we decided previously: if the user is typing a multi-word gloss, only give suggestions for the current word, assuming they're satisfied with the previous words. It avoids more relevant suggestions from being pushed out be others that the user already ignored.
___
*[`src/utilities/spellChecker.ts` line 62 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2484#-NcY9qK67lR4zKNcZBD4:-NcYEFbc1xZgC_jxg5Gz:bhmwnt0) ([raw file](https://github.com/sillsdev/TheCombine/blob/1af88a3eee7c15e37787dab28ca2ac2cff7320bd/src/utilities/spellChecker.ts#L62)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Are you sure these regex unicode values are working?
I have had bad luck with javascript and unicode regex in the past. It didn't give an error, it just didn't work.
</blockquote></details>

I experimented with them first in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Unicode_character_class_escape but should probably write a test to confirm.

**Review by jasonleenaylor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2484)* status: 35 of 250 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec)

___
*[`src/utilities/spellChecker.ts` line 53 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2484#-NcYAIYUAtMNYiGUkblt:-NcYFzmF8RC_v-7Y_o7M:b-8fx2u7) ([raw file](https://github.com/sillsdev/TheCombine/blob/1af88a3eee7c15e37787dab28ca2ac2cff7320bd/src/utilities/spellChecker.ts#L53)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

That was what we decided previously: if the user is typing a multi-word gloss, only give suggestions for the current word, assuming they're satisfied with the previous words. It avoids more relevant suggestions from being pushed out be others that the user already ignored.
</blockquote></details>

:+1:

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2484)* status: 30 of 251 files reviewed, 2 unresolved discussions (waiting on @jasonleenaylor)

___
*[`src/utilities/dictionaryLoader.ts` line 28 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2484#-NcY79k7DBMfEPXaRsmH:-NcZMNIs6yYixQ6hAUO_:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/1af88a3eee7c15e37787dab28ca2ac2cff7320bd/src/utilities/dictionaryLoader.ts#L28)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Add a method comment that describes the algorithm and what start is expected to be.
</blockquote></details>

Done.
___
*[`src/utilities/spellChecker.ts` line 62 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2484#-NcY9qK67lR4zKNcZBD4:-NcZMSYWD-lmZNyldbx1:b-wj4ea6) ([raw file](https://github.com/sillsdev/TheCombine/blob/1af88a3eee7c15e37787dab28ca2ac2cff7320bd/src/utilities/spellChecker.ts#L62)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I experimented with them first in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Unicode_character_class_escape but should probably write a test to confirm.
</blockquote></details>

Tests added.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 3 of 6 files at r5, 6 of 29 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2484)* status: 36 of 251 files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
