### PR TITLE
Fix aws s3 push

### PR DESCRIPTION
**Pull request by jmgrady**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/890)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/890)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/890)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @imnasnainaec and @jmgrady)

___
*[certmgr/scripts/utils.py, line 49 at r2](https://reviewable.io/reviews/sillsdev/thecombine/890#-MQXrPkECxgxQd8N-YK8:-MQXrHSk6wyCC3-YRltL:b32sdf4) ([raw file](https://github.com/sillsdev/thecombine/blob/ee3027133da162a433ffee0d5c215a1ed62d9136/certmgr/scripts/utils.py#L49)):*
> ```
>     If dest already exists and is not a link, it is deleted first.
> ```
Does this comment still correctly describe `update_link`?

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/890)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @imnasnainaec and @jmgrady)

___
*[certmgr/scripts/utils.py, line 49 at r2](https://reviewable.io/reviews/sillsdev/thecombine/890#-MQXrPkECxgxQd8N-YK8:-MQYBnRH6VqeOlA2cShX:b7d23wm) ([raw file](https://github.com/sillsdev/thecombine/blob/ee3027133da162a433ffee0d5c215a1ed62d9136/certmgr/scripts/utils.py#L49)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>     If dest already exists and is not a link, it is deleted first.
> ```
Does this comment still correctly describe `update_link`?
</blockquote></details>

No, it does not.  It's fixed now.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/890)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by imnasnainaec — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/890#-:-MQYTI9n9jy7qDy8j57l:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
