### PR TITLE
Protect words/senses imported with data The Combine doesn't handle

### LINKED ISSUE #1761: Allow merging/deleting of 'safe' Lift imported words and senses
We want to allow users to clean up existing FLEx data without putting that data at risk.

Add a flag to entries and senses that we import which have data other than 'Lexeme Form', 'Citation Form', 'Gloss', 'Definition', or 'Semantic Domains'.

Disable deletion or merging away of those entries and senses.

Acceptance Tests:
Merge works when it should and not when it shouldn't
All 'safe' fields are handled properly when merged in The Combine
Import into FLEx demonstrates success

Addresses #1750

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #1761

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2019)

### CODE REVIEW

**Comment by imnasnainaec** [comment]
Still to-do:
- [ ] tests & comments
- [ ] user feedback in MergeDup to explain why protected words/senses are preventing some action
- [ ] prevent final sense from leaving protected word
- [ ] determine whether protected senses should be allowed to leave unprotected words

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 2 of 7 files at r1, 21 of 30 files at r2, 10 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2019)* status: 31 of 33 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[`src/components/DataEntry/DataEntryComponent.tsx` line 61 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2019#-NT0TC0oCzcncAAhQVt6:-NT0TC0oCzcncAAhQVt7:bcy1rdu) ([raw file](https://github.com/sillsdev/TheCombine/blob/e5b1d136f91aacca5c3341bc87281719424beecb/src/components/DataEntry/DataEntryComponent.tsx#L61)):*
> ```XML
>     const senses = currentWord.senses.filter((s) =>
>       [Status.Active, Status.Protected, undefined].includes(s.accessibility)
>     );
> ```

We should either retain the comment about why undefined is allowed, or remove it if we can prove it is now obsolete.



_Code quote:_
```XML
    const senses = currentWord.senses.filter((s) =>
      [Status.Active, Status.Protected, undefined].includes(s.accessibility)
    );
```
___
*[`src/components/DataEntry/tests/DataEntryComponent.test.tsx` line 39 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2019#-NT0Ti_F4r3Gjd5VkFfh:-NT0Ti_F4r3Gjd5VkFfi:bhok2tx) ([raw file](https://github.com/sillsdev/TheCombine/blob/e5b1d136f91aacca5c3341bc87281719424beecb/src/components/DataEntry/tests/DataEntryComponent.test.tsx#L39)):*
> ```XML
>         {
>           ...mockWord,
>           senses: [{ ...newSense(), accessibility: Status.Protected }],
> ```

I can't tell from just this code if the test is valid. Does newSense contain an Active sense, and does that impact this logic?
It is probably fine, just checking.



_Code quote:_
```XML
senses: [{ ...newSense(), accessibility: Status.Protected }],
```
___
*[`src/goals/MergeDupGoal/MergeDupStep/SenseCardContent.tsx` line 134 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2019#-NT0UawH2se_f2R6GCqT:-NT0UawH2se_f2R6GCqU:b-4wvjl9) ([raw file](https://github.com/sillsdev/TheCombine/blob/e5b1d136f91aacca5c3341bc87281719424beecb/src/goals/MergeDupGoal/MergeDupStep/SenseCardContent.tsx#L134)):*
> ```XML
>     ),
>   ];
>   // If props.languages is undefined, this is a sidebar sense and needs no warning.
> ```

I'm not sure if I like relying on this to determine if it is a sidebar sense. It seems fragile. Maybe we should have a property to specifically indicate the sidebar senses?



_Code quote:_
```XML
  // If props.languages is undefined, this is a sidebar sense and needs no warning.
  const protectedWarning =
    props.languages !== undefined &&
```

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2019)* status: 27 of 33 files reviewed, all discussions resolved (waiting on @imnasnainaec and @jasonleenaylor)

___
*[`src/components/DataEntry/DataEntryComponent.tsx` line 61 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2019#-NT0TC0oCzcncAAhQVt6:-NTEPnB89PRcE77RzG6_:b-bvwhm5) ([raw file](https://github.com/sillsdev/TheCombine/blob/e5b1d136f91aacca5c3341bc87281719424beecb/src/components/DataEntry/DataEntryComponent.tsx#L61)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

We should either retain the comment about why undefined is allowed, or remove it if we can prove it is now obsolete.
</blockquote></details>

Restored.
___
*[`src/components/DataEntry/tests/DataEntryComponent.test.tsx` line 39 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2019#-NT0Ti_F4r3Gjd5VkFfh:-NTEPRC3DVSNfhgpAkpU:b4i5y2s) ([raw file](https://github.com/sillsdev/TheCombine/blob/e5b1d136f91aacca5c3341bc87281719424beecb/src/components/DataEntry/tests/DataEntryComponent.test.tsx#L39)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

I can't tell from just this code if the test is valid. Does newSense contain an Active sense, and does that impact this logic?
It is probably fine, just checking.
</blockquote></details>

`newSense()` does have `accessibility=Status.Active`, which is explicitly overridden here.
___
*[`src/goals/MergeDupGoal/MergeDupStep/SenseCardContent.tsx` line 134 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2019#-NT0UawH2se_f2R6GCqT:-NTEPd4TBu8vYHbZEzLv:bqiua8b) ([raw file](https://github.com/sillsdev/TheCombine/blob/e5b1d136f91aacca5c3341bc87281719424beecb/src/goals/MergeDupGoal/MergeDupStep/SenseCardContent.tsx#L134)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

I'm not sure if I like relying on this to determine if it is a sidebar sense. It seems fragile. Maybe we should have a property to specifically indicate the sidebar senses?
</blockquote></details>

Silly of me. Fixed.

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 1 of 30 files at r2, 1 of 11 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2019)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Comment by jasonleenaylor** [comment]
*[`Backend/Helper/LiftHelper.cs` line 14 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2019#-NTFIXZO0zSihzyPJURI:-NTFIXZO0zSihzyPJURJ:bjcub98) ([raw file](https://github.com/sillsdev/TheCombine/blob/80864eef515f467875d4c7566a3a716d37bef87b/Backend/Helper/LiftHelper.cs#L14)):*
> ```Smalltalk
>         {
>             return entry.Annotations.Count > 0 || entry.Etymologies.Count > 0 || entry.Fields.Count > 0 ||
>                 entry.Pronunciations.Count > 0 || entry.Relations.Count > 0 || entry.Traits.Count > 0 ||
> ```

Ok, this will need some work. I just used the Collect Words tool in FLEx to generate a couple of entries.
and `<trait name="morph-type" value="stem" />` was present on the entries.



_Code quote:_
```Smalltalk
entry.Traits.Count > 0 ||
```

**Comment by jasonleenaylor** [comment]
*[`Backend/Helper/LiftHelper.cs` line 25 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2019#-NTFLnE36l_5PpgdTXEr:-NTFLnE36l_5PpgdTXEs:b-mex1a6) ([raw file](https://github.com/sillsdev/TheCombine/blob/80864eef515f467875d4c7566a3a716d37bef87b/Backend/Helper/LiftHelper.cs#L25)):*
> ```Smalltalk
>             return sense.Examples.Count > 0 || sense.Fields.Count > 0 || sense.GramInfo != null ||
>                 sense.Illustrations.Count > 0 || sense.Relations.Count > 0 || sense.Reversals.Count > 0 ||
>                 sense.Subsenses.Count > 0 || (sense.Traits.Find(t => !t.Name.StartsWith("semantic-domain")) != null);
> ```

Could you use `Sense.Traits.Any(t => !t.Name.StartsWith("semantic-domain")`?



_Code quote:_
```Smalltalk
(sense.Traits.Find(t => !t.Name.StartsWith("semantic-domain")) != null
```

**Comment by jasonleenaylor** [comment]
*[`Backend/Helper/LiftHelper.cs` line 13 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2019#-NTFMpjBAMxSNRPNp2Ff:-NTFMpjBAMxSNRPNp2Fg:b-3sjoam) ([raw file](https://github.com/sillsdev/TheCombine/blob/80864eef515f467875d4c7566a3a716d37bef87b/Backend/Helper/LiftHelper.cs#L13)):*
> ```Smalltalk
>         public static bool IsProtected(LiftEntry entry)
>         {
>             return entry.Annotations.Count > 0 || entry.Etymologies.Count > 0 || entry.Fields.Count > 0 ||
> ```

Ok, looking at some lift files I found <reversal> and <illustration> tags which we will also want to protect.

**Comment by jasonleenaylor** [comment]
*[`Backend/Helper/LiftHelper.cs` line 13 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2019#-NTFMpjBAMxSNRPNp2Ff:-NTFN44oE31hT5gfvCvw:bgln813) ([raw file](https://github.com/sillsdev/TheCombine/blob/80864eef515f467875d4c7566a3a716d37bef87b/Backend/Helper/LiftHelper.cs#L13)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Ok, looking at some lift files I found <reversal> and <illustration> tags which we will also want to protect.
</blockquote></details>

Hmm, let's try that again. I found `<illustration>` and `<reversal>` tags that we will also want to protect.

**Comment by jasonleenaylor** [comment]
*[`Backend/Helper/LiftHelper.cs` line 13 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2019#-NTFMpjBAMxSNRPNp2Ff:-NTFOo_z4PWLRkqzyj3h:b81dbo3) ([raw file](https://github.com/sillsdev/TheCombine/blob/80864eef515f467875d4c7566a3a716d37bef87b/Backend/Helper/LiftHelper.cs#L13)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Hmm, let's try that again. I found `<illustration>` and `<reversal>` tags that we will also want to protect.
</blockquote></details>

Note with a "type" other than empty probably should also cause protection.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2019)* status: 32 of 33 files reviewed, 2 unresolved discussions (waiting on @jasonleenaylor)

___
*[`Backend/Helper/LiftHelper.cs` line 13 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2019#-NTFMpjBAMxSNRPNp2Ff:-NTG34HZDwK697tb6lck:b-kq4cjn) ([raw file](https://github.com/sillsdev/TheCombine/blob/80864eef515f467875d4c7566a3a716d37bef87b/Backend/Helper/LiftHelper.cs#L13)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Note with a "type" other than empty probably should also cause protection. 
</blockquote></details>

Note protections added.
___
*[`Backend/Helper/LiftHelper.cs` line 14 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2019#-NTFIXZO0zSihzyPJURI:-NTG38BgAc1bN9LoUhre:b-brvvwh) ([raw file](https://github.com/sillsdev/TheCombine/blob/80864eef515f467875d4c7566a3a716d37bef87b/Backend/Helper/LiftHelper.cs#L14)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Ok, this will need some work. I just used the Collect Words tool in FLEx to generate a couple of entries.
and `<trait name="morph-type" value="stem" />` was present on the entries.
</blockquote></details>

"stem" Trait protection removed.
___
*[`Backend/Helper/LiftHelper.cs` line 25 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2019#-NTFLnE36l_5PpgdTXEr:-NTG3DLH14O3vJ4zpP6L:bb7f2mf) ([raw file](https://github.com/sillsdev/TheCombine/blob/80864eef515f467875d4c7566a3a716d37bef87b/Backend/Helper/LiftHelper.cs#L25)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Could you use `Sense.Traits.Any(t => !t.Name.StartsWith("semantic-domain")`?
</blockquote></details>

done

**Comment by jasonleenaylor** [comment]
*[`Backend/Helper/LiftHelper.cs` line 15 at r5](https://reviewable.io/reviews/sillsdev/TheCombine/2019#-NTG3GUV5iFacyyw7MOk:-NTG3GUV5iFacyyw7MOl:b-vs6il6) ([raw file](https://github.com/sillsdev/TheCombine/blob/b2f1cd39a8129593f3c2221ea05736a0c0282c83/Backend/Helper/LiftHelper.cs#L15)):*
> ```Smalltalk
>         {
>             return entry.Annotations.Count > 0 || entry.Etymologies.Count > 0 || entry.Fields.Count > 0 ||
>                 (entry.Notes.Count == 1 && String.IsNullOrEmpty(entry.Notes.First().Type)) ||
> ```

I think you have the logic inverted on the nullorempty check here.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2019)* status: 32 of 33 files reviewed, 2 unresolved discussions (waiting on @jasonleenaylor)

___
*[`Backend/Helper/LiftHelper.cs` line 15 at r5](https://reviewable.io/reviews/sillsdev/TheCombine/2019#-NTG3GUV5iFacyyw7MOk:-NTGC-9TBXRcfLhro9iL:bmrzl5p) ([raw file](https://github.com/sillsdev/TheCombine/blob/b2f1cd39a8129593f3c2221ea05736a0c0282c83/Backend/Helper/LiftHelper.cs#L15)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

I think you have the logic inverted on the nullorempty check here.
</blockquote></details>

flipped

**Review by jasonleenaylor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2019#-:-NTHewJrBkCfHu7-YOJJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
