### PR TITLE
MergeTree refactor

### LINKED ISSUE #459: MergeDup sidebar allows dropping that breaks The Combine
When you drop a card onto another card in Merge Duplicates, it crates a single combined card, and a sidebar pops up on the right that allows you to pull apart the cards you just merged. However, the side-bar also allows you to drop in cards (including the card itself) which results in irreversible errors.
Screenshot from 2020-06-25 13-41-31
In the above image, the middle placard had two cards, for "man" and "husband". I dropped the latter into the former, creating a single card "man" with two senses, and causing the right side-bar to appear. Then I dragged that same "man" card and dropped it in the right sidebar, causing the crash. The expected behavior is that it shouldn't accept the drop.
Screenshot from 2020-06-25 13-45-25

### LINKED ISSUE #605: In Merge Duplicates, improve or eliminate the breakout box
The side bar showing the senses that are being merged and its relationship to the sense in the entry card was not obvious to all users.

Improve this by highlighting the sense in the card when the side bar is opened. Also consider other icons to use for opening and closing the side bar.

This traces back to the user experience documented below by implementing the highlight suggestion #8.

We choose not to address #6 because it could easily get unwieldy to handle more than two duplicate senses inside the card.
If there was a card with 4 senses and the 4th sense had 3 duplicates we would probably end up with vertical scrolling on this view and that should be avoided at all cost.

[08/03 #6](https://docs.google.com/document/d/1qvi7sQXW800gPwsMN3WOAc4REfKR8JGliZZbc1SHBdY/edit#heading=h.a6tmena8kd4z) Display all information on the card in Merge Duplicates, without the need for the break-out window on the right
[08/03 #8](https://docs.google.com/document/d/1qvi7sQXW800gPwsMN3WOAc4REfKR8JGliZZbc1SHBdY/edit#heading=h.a6tmena8kd4z) If Merge Duplicates break-out window is maintained, highlight the card for which it provides details

### LINKED ISSUE #907: Using MergeDup to split a word results in a word without a vernacular.
Related: #143 #410 

Make two words (A, B) with the same vernacular ("vernac"), one with two senses (A1 "gloss", A2 "glossy").
In Data Cleanup, use Merge Duplicates until A and B come up together.
Move A2 ("glossy") to a new word (the empty tile) and press Save & Continue.
Go to Data Cleanup | Review Entries and filter gloss by "glossy"; there will be an entry, but with no vernacular.

Desired behavior: the new word from A2 should inherit the vernacular of A from whence it came.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Move all the pieces of Drag'n'Drop out of `MergeDupStepComponent.tsx` and `MergeRow/` into functional components in `DragDropComponents/`.

Overhaul MergeDup state, actions, reducer.

Retire `utilities.tsx > uuid()` (replaced by `uuid > v4()`).

Layout improvement: Move buttons to left, to not be covered by sidebar; Add matching background color to sidebar and the sense it represents.

Fixes #459 
Resolves #605 
Fixes #907 

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1087)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 2 of 24 files at r2, 6 of 12 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1087)* status: 8 of 25 files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 3 of 24 files at r2, 1 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1087)* status: 12 of 25 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[src/goals/MergeDupGoal/MergeDupStep/tests/MergeDupStepReducer.test.tsx, line 18 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1087#-MWkemIy5l9Qsl5vwRFY:-MWkemIy5l9Qsl5vwRFZ:bmhwoel) ([raw file](https://github.com/sillsdev/thecombine/blob/a8387eefaf45537804c18a832426e8a6e69a2353/src/goals/MergeDupGoal/MergeDupStep/tests/MergeDupStepReducer.test.tsx#L18)):*
> ```
> assined
> ```
sp.

**Review by jasonleenaylor — CHANGES_REQUESTED** [review]
> Reviewed 8 of 24 files at r2, 4 of 12 files at r3, 7 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1087)* status: 27 of 28 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jasonleenaylor)

___
*[src/goals/MergeDupGoal/MergeDupStep/tests/MergeDupStepReducer.test.tsx, line 101 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1087#-MX7l_6E6vieqwP6nFCr:-MX7l_6E6vieqwP6nFCs:bbf0k7) ([raw file](https://github.com/sillsdev/thecombine/blob/a8387eefaf45537804c18a832426e8a6e69a2353/src/goals/MergeDupGoal/MergeDupStep/tests/MergeDupStepReducer.test.tsx#L101)):*
> ```
>     // We have to stringify for this test,
>     // because the order of the .sensesGuids matters.
> ```
This is a wonderful example of proper use of comments. I wish I had training materials that I could put this in.
___
*[src/goals/MergeDupGoal/MergeDupStep/tests/MergeDupStepReducer.test.tsx, line 299 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1087#-MX7mCws4OfSmCovRMDc:-MX7mCws4OfSmCovRMDd:b-lnyb3s) ([raw file](https://github.com/sillsdev/thecombine/blob/a8387eefaf45537804c18a832426e8a6e69a2353/src/goals/MergeDupGoal/MergeDupStep/tests/MergeDupStepReducer.test.tsx#L299)):*
> ```
>       expectedWords[destWordId].sensesGuids[nextGuid] = [srcGuid];
> ```
This line needs some explanation, the same for other places where you did this.
If I'm reading this correctly you are doing this to make the checkTreeWords test ignore the guid.
You could add a comment, or put the assignment into a named method. Or add an ignore guid to checkTreeWords.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1087)* status: 27 of 28 files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor)

___
*[src/goals/MergeDupGoal/MergeDupStep/tests/MergeDupStepReducer.test.tsx, line 101 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1087#-MX7l_6E6vieqwP6nFCr:-MX7wjW32J0l79tL2Orh:be0530r) ([raw file](https://github.com/sillsdev/thecombine/blob/a8387eefaf45537804c18a832426e8a6e69a2353/src/goals/MergeDupGoal/MergeDupStep/tests/MergeDupStepReducer.test.tsx#L101)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
>     // We have to stringify for this test,
>     // because the order of the .sensesGuids matters.
> ```
This is a wonderful example of proper use of comments. I wish I had training materials that I could put this in.
</blockquote></details>

:grin: 
___
*[src/goals/MergeDupGoal/MergeDupStep/tests/MergeDupStepReducer.test.tsx, line 299 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1087#-MX7mCws4OfSmCovRMDc:-MX7wmCK0tNGSIJ2hXdn:b-hl1esu) ([raw file](https://github.com/sillsdev/thecombine/blob/a8387eefaf45537804c18a832426e8a6e69a2353/src/goals/MergeDupGoal/MergeDupStep/tests/MergeDupStepReducer.test.tsx#L299)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
>       expectedWords[destWordId].sensesGuids[nextGuid] = [srcGuid];
> ```
This line needs some explanation, the same for other places where you did this.
If I'm reading this correctly you are doing this to make the checkTreeWords test ignore the guid.
You could add a comment, or put the assignment into a named method. Or add an ignore guid to checkTreeWords. 

</blockquote></details>

Does this comment illuminate?
```
      // A new guid is used when a sense is added to a merge word, so use the intercepted
      // nextGuid for the new sense expected from moving a sense out of a sidebar.
```

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1087)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
