### PR TITLE
Create backup/restore scripts for docker containers

### PR DESCRIPTION
**Pull request by jmgrady**
Create two scripts, `combine-backup` and `combine-restore`, that backup/restore the database and backend services for TheCombine.

`combine-backup` creates a compressed tarball that contains:
 - the `/home/app/.CombineFiles` folder from the backend container, and
 - the `dump` folder that is created by running `mongodump` to backup the database container

The tarball is pushed to an AWS S3 bucket.

`combine-restore` fetches a backup tarball from the AWS S3 bucket, unpacks it, and installs the files in the backend and database containers.  Normally the backend files are merged with the existing files.  `combine-restore` has an option to remove the files inside the backend container before the restore is done.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/826)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 12 of 15 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/826)* status: 10 of 14 files reviewed, all discussions resolved (waiting on @imnasnainaec and @jmgrady)

___
*[docker_deploy/group_vars/qa/main.yml, line 28 at r1](https://reviewable.io/reviews/sillsdev/thecombine/826#-MMqvjyF-gHJTVD0Lsfo:-MMqvjyF-gHJTVD0Lsfp:blbfmpn) ([raw file](https://github.com/sillsdev/thecombine/blob/87ec5296cc066fa0e76cdea15a4cd75b6d6df6bd/docker_deploy/group_vars/qa/main.yml#L28)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> # my_default_aws_profile: ecr_read_only
> # my_aws_profiles:
> #   - ecr_read_write
> #   - s3_read_write
> ```
</details>

Is this commented-out material being kept for anything in particular?

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/826)* status: 10 of 14 files reviewed, all discussions resolved (waiting on @imnasnainaec and @jmgrady)

___
*[docker_deploy/group_vars/qa/main.yml, line 28 at r1](https://reviewable.io/reviews/sillsdev/thecombine/826#-MMqvjyF-gHJTVD0Lsfo:-MMr-9XoDJ4rJXOt-Lsk:b-169cma) ([raw file](https://github.com/sillsdev/thecombine/blob/87ec5296cc066fa0e76cdea15a4cd75b6d6df6bd/docker_deploy/group_vars/qa/main.yml#L28)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> # my_default_aws_profile: ecr_read_only
> # my_aws_profiles:
> #   - ecr_read_write
> #   - s3_read_write
> ```
Is this commented-out material being kept for anything in particular?
</blockquote></details>

No reason.  Removed.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 15 files at r1, 1 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/826)* status: 12 of 14 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[docker_deploy/roles/combine_backup/tasks/main.yml, line 22 at r3](https://reviewable.io/reviews/sillsdev/thecombine/826#-MMr44ey-gtPcHpY02m8:-MMr44ez2IKNnucpDfZC:bsglqgs) ([raw file](https://github.com/sillsdev/thecombine/blob/e0ce15e1d44449f0145a9d7663eaf6a0ec8044e3/docker_deploy/roles/combine_backup/tasks/main.yml#L22)):*
> ```YAML
>   template:
>     src: "{{ item }}.j2"
>     dest: "{{ combine_app_dir }}/bin/{{ item }}"
> ```

Do we not need a file suffix on the destination?

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/826)* status: 12 of 14 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[docker_deploy/roles/combine_backup/tasks/main.yml, line 22 at r3](https://reviewable.io/reviews/sillsdev/thecombine/826#-MMr44ey-gtPcHpY02m8:-MMr4oKL2GLpKvvrGSAf:bvx3nus) ([raw file](https://github.com/sillsdev/thecombine/blob/e0ce15e1d44449f0145a9d7663eaf6a0ec8044e3/docker_deploy/roles/combine_backup/tasks/main.yml#L22)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Do we not need a file suffix on the destination?
</blockquote></details>

No suffix is needed.  The file has execute permissions and the shebang specifies that the script is run with the bash shell.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/826)* status: 12 of 14 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[docker_deploy/roles/combine_backup/templates/combine-backup.j2, line 66 at r4](https://reviewable.io/reviews/sillsdev/thecombine/826#-MMr93kK4AMi-Ttkg0YY:-MMr93kK4AMi-Ttkg0YZ:b-ygt09x) ([raw file](https://github.com/sillsdev/thecombine/blob/44d10837296d7d09029f7bc8a51f99071e9f54e6/docker_deploy/roles/combine_backup/templates/combine-backup.j2#L66)):*
> ```django
>   mkdir -p ${BACKUP_DIR}
> else
>   for item in ${BACKUP_DIR}/dump ${BACKUP_DIR}/.CombineFiles ${BACKUP_DIR}/${BACKUP_FILE}
> ```

Should ".CombineFiles" perhaps be an environment variable in step 1 in both templates, since it's used a number of times?

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/826)* status: 11 of 14 files reviewed, all discussions resolved (waiting on @imnasnainaec and @jmgrady)

___
*[docker_deploy/roles/combine_backup/templates/combine-backup.j2, line 66 at r4](https://reviewable.io/reviews/sillsdev/thecombine/826#-MMr93kK4AMi-Ttkg0YY:-MMrFONu7PiIZbVQ5Gkt:b3vj0n6) ([raw file](https://github.com/sillsdev/thecombine/blob/44d10837296d7d09029f7bc8a51f99071e9f54e6/docker_deploy/roles/combine_backup/templates/combine-backup.j2#L66)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Should ".CombineFiles" perhaps be an environment variable in step 1 in both templates, since it's used a number of times?
</blockquote></details>

Done.  Also did it for the sub-directory for the mongo database files, "dump".

**Review by imnasnainaec — APPROVED** [review]
I haven't tested the backup/restore nor evaluated every detail of this pr, but it generally looks good.

> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/826#-:-MMrc8zf0woX6HfO6FNo:bkbysv)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[docker_deploy/roles/combine_backup/templates/combine-backup.j2, line 109 at r5](https://reviewable.io/reviews/sillsdev/thecombine/826#-MMrZq-H2QsORLZ8guXE:-MMrZq-I2w4KR2aimA3-:brjew8n) ([raw file](https://github.com/sillsdev/thecombine/blob/c690f07df62495802865681cf833526322b063d0/docker_deploy/roles/combine_backup/templates/combine-backup.j2#L109)):*
> ```
> echo_verbose "7. create ...
> ...
> echo_verbose "9. push ...
> ```
Missing capitalization.

**Pull request merged**
