### PR TITLE
Python code improvements

### PR DESCRIPTION
**Pull request by jmgrady**
Python code improvements from John's comments from PR #1091.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1113)

### CODE REVIEW

**Comment by johnthagen** [comment]
@jmgrady Could you also take a look at this code in `combine_restore.py`?

```py
            # Get the list of backups but throw away the header
            aws_backup_list = aws.list().stdout.strip().split("\n")[1:]

            if len(aws_backup_list) == 0:
                print(f"No backups available from {config['aws_bucket']}")
                sys.exit(0)

            # Print out the list of backups to choose from.  In the process,
            # update each line in the backup list to be the AWS S3 object name
            # and its (human-friendly) size.
            print("Backup List:")
            for i, item in enumerate(aws_backup_list):
                backup_components = item.split()
                aws_backup_list[i] = (
                    humanfriendly.format_size(int(backup_components[2])),
                    aws_strip_bucket(backup_components[3]),
                )
                print(f"{i+1}: {aws_backup_list[i][1]} ({aws_backup_list[i][0]})")
            backup_num = int(
                input("Enter the number of the backup you would like to restore (0 = None):")
            )
            if backup_num == 0:
                print("No backup selected.  Exiting.")
                sys.exit(0)
            backup = aws_backup_list[backup_num - 1][1]
```

There is some type confusion because `aws_backup_list` is being reused as a different type. It is initially a `List[str]` 

```py
aws_backup_list = aws.list().stdout.strip().split("\n")[1:]
```

and then the elements are reassigned as a `Tuple` rather than a `str`:

```py
                aws_backup_list[i] = (
                    humanfriendly.format_size(int(backup_components[2])),
                    aws_strip_bucket(backup_components[3]),
                )
```

Could we use a separate variable to build up the `Tuple` second part of this process? That would appease `mypy` after I turn on some more checking later. It would also remove a warning that is shown in PyCharm.

**Comment by johnthagen** [comment]
___
*[deploy/roles/combine_maintenance/files/combine_app.py, line 59 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1113#-MYQ40Wj5sa3uIzp69oB:-MYQ40Wj5sa3uIzp69oC:b-8qgpf8) ([raw file](https://github.com/sillsdev/thecombine/blob/990051e8e7a13364fc963c2265d583017570dc37/deploy/roles/combine_maintenance/files/combine_app.py#L59)):*
> ```Python
>                      specific user to run the command.
>             check_results: Indicate if subprocess should not check for failure.
>                      (Default is True)
> ```

We can safely remove the `(Default is True)` since that is in the type signature and editors will show that to the developer.

**Review by johnthagen — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1113)* status: all files reviewed, 1 unresolved discussion (waiting on @jmgrady)

**Review by jmgrady — COMMENTED** [review]
Update combine_restore.py per comment above.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1113#-:-MYQHc_o3BWC1Jj4NQk7:bfzm8ey)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @jmgrady and @johnthagen)

___
*[deploy/roles/combine_maintenance/files/combine_app.py, line 59 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1113#-MYQ40Wj5sa3uIzp69oB:-MYQ4qt009i0flc5XPdI:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/990051e8e7a13364fc963c2265d583017570dc37/deploy/roles/combine_maintenance/files/combine_app.py#L59)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

We can safely remove the `(Default is True)` since that is in the type signature and editors will show that to the developer.
</blockquote></details>

Done.

**Review by johnthagen — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1113)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Comment by johnthagen** [comment]
Looks like `tox -e fmt` needs to be run.

**Review by johnthagen — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1113)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Pull request merged**
