### PR TITLE
Shift-Click to delete recording

### PR DESCRIPTION
**Pull request by StevesBro**
Allows Shift-Click to delete a recording. 

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/416)

### CODE REVIEW

**Comment by charjhall** [comment]
___
*[src/components/Pronunciations/AudioPlayer.tsx, line 49 at r3](https://reviewable.io/reviews/sillsdev/thecombine/416#-M9PudBl6HfqYTgj-iB9:-M9PudBl6HfqYTgj-iBA:b-etegx1) ([raw file](https://github.com/sillsdev/thecombine/blob/dcf63880bcb8c8b9b4faed553c14ffe94d6b544d/src/components/Pronunciations/AudioPlayer.tsx#L49)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>       await Backend.deleteAudio(props.wordId, props.fileName).then(
>         (newWordId) => {
>           if (props.refreshWord) {
>             props.refreshWord(props.wordId, newWordId);
>           }
>         }
>       );
> ```
</details>

This needs to be refactored in accordance with Redux. Typically you would call a prop here passed in from the [connected component](https://github.com/sillsdev/TheCombine/blob/master/src/components/Pronunciations/index.ts). You would need to implement `mapDispatchToProps()` and implement the various aspects needed for redux. See [this code](https://github.com/sillsdev/TheCombine/blob/master/src/components/ProjectScreen/ChooseProject/index.tsx) in our project and [this tutorial](https://redux.js.org/basics/basic-tutorial) if you aren't sure what I mean.

**Comment by StevesBro** [comment]
The "Undo last commit" wasn't named correctly. The tests are still there but it undid a change I made to deleteAudio in src/backend/index

**Comment by charjhall** [comment]
___
*[Backend.Tests/WordControllerTests.cs, line 189 at r16](https://reviewable.io/reviews/sillsdev/thecombine/416#-M9x_LgN1tVMNuMPmvAb:-M9x_LgN1tVMNuMPmvAc:bywv8hg) ([raw file](https://github.com/sillsdev/thecombine/blob/526edef63b3023d58ee91ae7cf79b911fb659fa5/Backend.Tests/WordControllerTests.cs#L189)):*
> ```
> var action
> ```
This is defined but unused

**Comment by charjhall** [comment]
___
*[Backend.Tests/WordControllerTests.cs, line 195 at r16](https://reviewable.io/reviews/sillsdev/thecombine/416#-M9x_kaa8q28lgKlzgG0:-M9x_kaa8q28lgKlzgG1:b-jrhkc3) ([raw file](https://github.com/sillsdev/thecombine/blob/526edef63b3023d58ee91ae7cf79b911fb659fa5/Backend.Tests/WordControllerTests.cs#L195)):*
> ```
> var wordRepo
> ```
May want to rename this to indicate it is a frontier

**Pull request merged**
