### PR TITLE
Simplify Release Process

### PR DESCRIPTION
**Pull request by jmgrady**
This PR updates the release process for _The Combine_.  The changes involve:
- The build process creates a release string from information from git, specifically, `git describe`, and stores it in a file, `release.js`.
- The `release.js` file is built into the container image for _The Combine's_ frontend component.
- The release information in `release.js` is managed by the RuntimeConfig object; the UI now fetches the release string from this object instead of the UI package version.
- `docs/release_process/README.md` is updated with instructions for the simplified release process.

In addition, the GitHub Actions for CI/CD are changed as follows:
- The docker test builds are only run when a pull request is updated; they are no longer run when a change is pushed to `master` since the components will all be built as part of installing the updated code on the QA server.
- The live server is updated when a release is published and is built off of the software that has been tagged.  This obviates the need for the `live` branch.
- _The Combine_ or its components are built using the project build script instead of the provided action, `docker/build-push-action`.  The provided action works off of the GitHub reference and not on a checked out copy so the `release.js` cannot be built for the images.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1677)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 11 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1677)* status: 11 of 30 files reviewed, 3 unresolved discussions (waiting on @jmgrady)

___
*[`package.json` line 3 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1677#-N4XJtBd8xFuuQYzjTge:-N4XJtBd8xFuuQYzjTgf:bw11hh7) ([raw file](https://github.com/sillsdev/thecombine/blob/901b0bfce05c2940b145e26d6917abb8cc54e53b/package.json#L3)):*
> ```JSON
> {
>   "name": "thecombine",
>   "version": "1.0.0",
> ```

Combine v1--this calls for a celebration!

...though I see this has no bearing on the behavior of `npm run set-release` in the branch. Is this in anticipation of a release once this branch is merged into `master`?
___
*[`docs/release_process/README.md` line 16 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1677#-N4XT_6fBhYY9UZSOzn2:-N4XT_6fBhYY9UZSOzn3:b-bsdl94) ([raw file](https://github.com/sillsdev/thecombine/blob/901b0bfce05c2940b145e26d6917abb8cc54e53b/docs/release_process/README.md#L16)):*
> ```Markdown
> - the user has write permissions for _The Combine_ project on _GitHub_.
> 
> ## Using the GitHub Interface to New Release
> ```

I feel like a verb is needed before "New Release"



_Code quote:_
```Markdown
## Using the GitHub Interface to New Release
```
___
*[`src/types/runtimeConfig.ts` line 63 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1677#-N4XZOb-3jzERr6nlDPM:-N4XZOb0-BTEvfznIABx:bjw0ap6) ([raw file](https://github.com/sillsdev/thecombine/blob/901b0bfce05c2940b145e26d6917abb8cc54e53b/src/types/runtimeConfig.ts#L63)):*
> ```XML
>       return window.release;
>     }
>     return "0.0.0-default.0";
> ```

`v`-initial to match style?

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1677)* status: 11 of 30 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`docs/release_process/README.md` line 16 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1677#-N4XT_6fBhYY9UZSOzn2:-N4XvIYEDSQOoggXKLRc:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/901b0bfce05c2940b145e26d6917abb8cc54e53b/docs/release_process/README.md#L16)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I feel like a verb is needed before "New Release"
</blockquote></details>

Done
___
*[`src/types/runtimeConfig.ts` line 63 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1677#-N4XZOb-3jzERr6nlDPM:-N4Xvfcu2oYVsgfZkOAI:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/901b0bfce05c2940b145e26d6917abb8cc54e53b/src/types/runtimeConfig.ts#L63)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`v`-initial to match style?
</blockquote></details>

Done

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1677)* status: 11 of 30 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[`package.json` line 3 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1677#-N4XJtBd8xFuuQYzjTge:-N4YPbTpCBwG8wx0YPU-:b-gey7ko) ([raw file](https://github.com/sillsdev/thecombine/blob/901b0bfce05c2940b145e26d6917abb8cc54e53b/package.json#L3)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Combine v1--this calls for a celebration!

...though I see this has no bearing on the behavior of `npm run set-release` in the branch. Is this in anticipation of a release once this branch is merged into `master`?
</blockquote></details>

A new release is not expected with the completion of this merge.  The change in the version here is intended to mark the split from using the UI version as the release name.  Once this is merged into master, the release name will come from the GitHub tag for the software.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 2 of 23 files at r1, 1 of 2 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1677)* status: 15 of 30 files reviewed, all discussions resolved (waiting on @jmgrady)

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 2 of 23 files at r1, 6 of 8 files at r2, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1677)* status: 24 of 30 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[`.github/actions/combine-build/action.yml` line 46 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1677#-N4mFMSi91tbFMIhh5TP:-N4mFMSi91tbFMIhh5TQ:b-cwkd1r) ([raw file](https://github.com/sillsdev/thecombine/blob/dcdcf093e279280d5294b8957df8c14d76592b0a/.github/actions/combine-build/action.yml#L46)):*
> ```YAML
>     - name: Build The Combine
>       run: |
>         deploy/scripts/build.py --tag ${{ env.IMAGE_TAG }} --repo ${{ inputs.image_repo }}
> ```

I'm sure this is set somewhere in this PR...



_Code quote:_
```YAML
env.IMAGE_TAG
```
___
*[`.github/workflows/backend.yml` line 69 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1677#-N4mEjaw7uXhA90_rd6i:-N4mEjaw7uXhA90_rd6j:b6f5vp3) ([raw file](https://github.com/sillsdev/thecombine/blob/dcdcf093e279280d5294b8957df8c14d76592b0a/.github/workflows/backend.yml#L69)):*
> ```YAML
> 
>   docker_build:
>     runs-on: ubuntu-22.04
> ```

Did we have problems on latest?



_Code quote:_
```YAML
ubuntu-22.04
```

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1677)* status: 17 of 31 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec, @jasonleenaylor, and @jmgrady)

___
*[`.github/workflows/python.yml` line 14 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1677#-N4nDkYQAUrZNKFpS3Qc:-N4nDkYQAUrZNKFpS3Qd:b-i02160) ([raw file](https://github.com/sillsdev/thecombine/blob/cc5cc98bce326b80decf22b209b0b488765345b5/.github/workflows/python.yml#L14)):*
> ```YAML
>     strategy:
>       matrix:
>         python-version: ["3.10", "3.9", "3.10"]
> ```

I think you meant to add back "3.8".

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1677)* status: 17 of 31 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec, @jasonleenaylor, and @jmgrady)

___
*[`.github/workflows/python.yml` line 14 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1677#-N4nDkYQAUrZNKFpS3Qc:-N4nbiBB1hC_P9E3rTmv:b-2t2agw) ([raw file](https://github.com/sillsdev/thecombine/blob/cc5cc98bce326b80decf22b209b0b488765345b5/.github/workflows/python.yml#L14)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I think you meant to add back "3.8".
</blockquote></details>

Yes, I did.  Thanks for catching that.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 8 files at r2, 1 of 2 files at r3, 2 of 11 files at r5, 7 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1677)* status: 27 of 35 files reviewed, 2 unresolved discussions (waiting on @jasonleenaylor and @jmgrady)

___
*[`deploy/scripts/setup_cluster.py` line 4 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1677#-N55xH0P3eMsBjkkYgQ4:-N55xH0QEwTljtc-bvuN:b-kcyb5q) ([raw file](https://github.com/sillsdev/thecombine/blob/5804383b9e4a41f84eb0e76974ee45be31bf0e0d/deploy/scripts/setup_cluster.py#L4)):*
> ```Python
> """Install the pre-requisite helm charts for the Combine on a k8s cluster."""
> 
> from __future__ import annotations
> ```

Which line(s] require[s) this import?
___
*[`.github/workflows/deploy_release.yml` line 26 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1677#-N56-ZmnCJ28IPhbWyzm:-N56-Zmo8qrSn8bWmGCm:b-cy085q) ([raw file](https://github.com/sillsdev/thecombine/blob/5804383b9e4a41f84eb0e76974ee45be31bf0e0d/.github/workflows/deploy_release.yml#L26)):*
> ```YAML
>           aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
>           aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
>           aws_default_region: us-east-1
> ```

Why not use `secrets.AWS_DEFAULT_REGION` here anymore?

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1677)* status: 27 of 35 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec, @jasonleenaylor, and @jmgrady)

___
*[`.github/workflows/deploy_release.yml` line 26 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1677#-N56-ZmnCJ28IPhbWyzm:-N56CnXc56azFWKd2ldd:bee4luq) ([raw file](https://github.com/sillsdev/thecombine/blob/5804383b9e4a41f84eb0e76974ee45be31bf0e0d/.github/workflows/deploy_release.yml#L26)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Because the region for the public registries is always `us-east-1` regardless of the account's default region.  See the section _To authenticate Docker to an Amazon ECR registry with get-login-password_ in https://docs.aws.amazon.com/AmazonECR/latest/public/public-registries.html
</blockquote></details>

I will add a comment to this effect in the YAML file.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 23 files at r1, 2 of 11 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1677)* status: 31 of 35 files reviewed, 2 unresolved discussions (waiting on @jasonleenaylor and @jmgrady)

___
*[`.github/actions/combine-build/action.yml` line 5 at r7](https://reviewable.io/reviews/sillsdev/thecombine/1677#-N5A_0ya1LnLANSs37tb:-N5A_0ya1LnLANSs37tc:b-up4kel) ([raw file](https://github.com/sillsdev/thecombine/blob/6d74791c6169f93a6796f20e51afcf3bfc10b5b4/.github/actions/combine-build/action.yml#L5)):*
> ```YAML
> inputs:
>   image_registry:
>     description: "Docker Image Repository"
> ```

Is "Repository" still an apt descriptor?
___
*[`.github/workflows/deploy_qa.yml` line 32 at r7](https://reviewable.io/reviews/sillsdev/thecombine/1677#-N5A_r5N5RnAKZZmHewW:-N5A_r5N5RnAKZZmHewX:b9w95cr) ([raw file](https://github.com/sillsdev/thecombine/blob/6d74791c6169f93a6796f20e51afcf3bfc10b5b4/.github/workflows/deploy_qa.yml#L32)):*
> ```YAML
>     env:
>       RM_PATTERN_1: \d+\.\d+\.\d+-master\.\d+
>       RM_PATTERN_2: \d+\.\d+\.\d+-[a-z]+\.\d+-master\.\d+
> ```

Do these not require \\ as was in `QA_IMAGE_PATTERN`?



_Code quote:_
```YAML
      RM_PATTERN_1: \d+\.\d+\.\d+-master\.\d+
      RM_PATTERN_2: \d+\.\d+\.\d+-[a-z]+\.\d+-master\.\d+
```

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1677)* status: 31 of 35 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec, @jasonleenaylor, and @jmgrady)

___
*[`.github/actions/combine-build/action.yml` line 5 at r7](https://reviewable.io/reviews/sillsdev/thecombine/1677#-N5A_0ya1LnLANSs37tb:-N5AbRJ97RyQJMMqP_cH:b-oejyp1) ([raw file](https://github.com/sillsdev/thecombine/blob/6d74791c6169f93a6796f20e51afcf3bfc10b5b4/.github/actions/combine-build/action.yml#L5)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Is "Repository" still an apt descriptor?
</blockquote></details>

No it is not.  Corrected.
___
*[`.github/workflows/deploy_qa.yml` line 32 at r7](https://reviewable.io/reviews/sillsdev/thecombine/1677#-N5A_r5N5RnAKZZmHewW:-N5Ac9F8E4FyFc5GHaww:b-2jx5t4) ([raw file](https://github.com/sillsdev/thecombine/blob/6d74791c6169f93a6796f20e51afcf3bfc10b5b4/.github/workflows/deploy_qa.yml#L32)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Do these not require \\ as was in `QA_IMAGE_PATTERN`?
</blockquote></details>

No they don't because now they are quoted on the command line.  I felt this makes the regex easier to read.
Before:
```
--remove ${{ env.QA_IMAGE_PATTERN }}
```
After:
```
--remove "${{ env.RM_PATTERN_1 }}" "${{ env.RM_PATTERN_2 }}"
```

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 2 of 11 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1677)* status: 34 of 35 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`deploy/scripts/build.py` line 91 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1677#-N5FynjbEEjndfqIPuNo:-N5FynjbEEjndfqIPuNp:bn8ly4u) ([raw file](https://github.com/sillsdev/thecombine/blob/b0f9b8c33d5a5c33f9f56776e033a2f45bc8e579/deploy/scripts/build.py#L91)):*
> ```Python
>         log_level = logging.INFO
>     else:
>         log_level = logging.WARNING
> ```

How about a 1-liner:
`log_level = logging.INFO if args.output_level != "none" else logging.WARNING`



_Code quote:_
```Python
    if args.output_level != "none":
        log_level = logging.INFO
    else:
        log_level = logging.WARNING
```

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1677)* status: 34 of 35 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[`deploy/scripts/build.py` line 91 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1677#-N5FynjbEEjndfqIPuNo:-N5G0VOIEzK54l2V4ir_:b-to7up2) ([raw file](https://github.com/sillsdev/thecombine/blob/b0f9b8c33d5a5c33f9f56776e033a2f45bc8e579/deploy/scripts/build.py#L91)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

How about a 1-liner:
`log_level = logging.INFO if args.output_level != "none" else logging.WARNING`
</blockquote></details>

Although it is one line, I find that structure harder to read and mentally parse.  I prefer to leave it as it is.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1677)* status: 34 of 35 files reviewed, 3 unresolved discussions (waiting on @jmgrady)

___
*[`deploy/scripts/app_release.py` line 21 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1677#-N5GEds58DJNIm7CGkka:-N5GEds58DJNIm7CGkkb:b-qfzgq2) ([raw file](https://github.com/sillsdev/thecombine/blob/b0f9b8c33d5a5c33f9f56776e033a2f45bc8e579/deploy/scripts/app_release.py#L21)):*
> ```Python
>     match = re.search(r"^v?(\d+\.\d+\.\d+)(-\S+\.\d+)?$", result.stdout)
>     if match:
>         return match.expand(r"v\1\2")
> ```

Since the second `(...)` is `?`'d, will this `return` have an issue if `match.lastindex = 1`?



_Code quote:_
```Python
    match = re.search(r"^v?(\d+\.\d+\.\d+)(-\S+\.\d+)?$", result.stdout)
    if match:
        return match.expand(r"v\1\2")
```
___
*[`deploy/scripts/app_release.py` line 75 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1677#-N5GFRjpAyZXsUNCXAem:-N5GFRjqBs82XUJW_7gb:b-5hifjd) ([raw file](https://github.com/sillsdev/thecombine/blob/b0f9b8c33d5a5c33f9f56776e033a2f45bc8e579/deploy/scripts/app_release.py#L75)):*
> ```Python
>     Allow calling from the command line.
> 
>     Allow calling from the command line so that node scripts can get/set the release.
> ```

Redundant?



_Code quote:_
```Python
    """
    Allow calling from the command line.

    Allow calling from the command line so that node scripts can get/set the release.
    """
```
___
*[`deploy/scripts/app_release.py` line 83 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1677#-N5GFcQX5iE_zAu1poUa:-N5GFcQX5iE_zAu1poUb:b-kcsx4n) ([raw file](https://github.com/sillsdev/thecombine/blob/b0f9b8c33d5a5c33f9f56776e033a2f45bc8e579/deploy/scripts/app_release.py#L83)):*
> ```Python
>         set_release(get_release(), Path(args.path))
>     elif args.set is not None:
>         set_release(args.set, Path(args.path))
> ```

I take it you've no interest in doing both a `--get` printout and a `--set-current` simultaneously.



_Code quote:_
```Python
    if args.get:
        print(get_release())
    elif args.set_current:
        set_release(get_release(), Path(args.path))
    elif args.set is not None:
        set_release(args.set, Path(args.path))
```

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1677)* status: 34 of 35 files reviewed, 3 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

___
*[`deploy/scripts/app_release.py` line 21 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1677#-N5GEds58DJNIm7CGkka:-N5GLhwV6Wb_NUlJ5Vd9:b-w4pkln) ([raw file](https://github.com/sillsdev/thecombine/blob/b0f9b8c33d5a5c33f9f56776e033a2f45bc8e579/deploy/scripts/app_release.py#L21)):*
It should be fine.  From the Python documentation for `re`:
> Match.expand(template)
Return the string obtained by doing backslash substitution on the template string template, as done by the sub() method. Escapes such as \n are converted to the appropriate characters, and numeric backreferences (\1, \2) and named backreferences (\g<1>, \g<name>) are replaced by the contents of the corresponding group.

> Changed in version 3.5: Unmatched groups are replaced with an empty string.
___
*[`deploy/scripts/app_release.py` line 75 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1677#-N5GFRjpAyZXsUNCXAem:-N5GN9SG0LuRqleRtyHF:blbb0yp) ([raw file](https://github.com/sillsdev/thecombine/blob/b0f9b8c33d5a5c33f9f56776e033a2f45bc8e579/deploy/scripts/app_release.py#L75)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Redundant?
</blockquote></details>

Corrected docstring.
___
*[`deploy/scripts/app_release.py` line 83 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1677#-N5GFcQX5iE_zAu1poUa:-N5GP3Dq4m4O1mNRlc4S:b-t7jcrt) ([raw file](https://github.com/sillsdev/thecombine/blob/b0f9b8c33d5a5c33f9f56776e033a2f45bc8e579/deploy/scripts/app_release.py#L83)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I take it you've no interest in doing both a `--get` printout and a `--set-current` simultaneously.
</blockquote></details>

Do you think it is useful?  So far, the only use for the command line is `--get` in the GitHub Actions and `--set-current` in the node.js script when it is called from `npm start` and others.  The build script for the docker containers uses the `git` calls and not the current contents of the `release.js`, so I don't know how useful that would be.  In fact, perhaps the `--set` option should be removed.

I have pushed a change that makes the options mutually exclusive so that the help prints out:
```
usage: app_release.py [-h] [--get | --set SET | --set-current] [--path PATH]
```
Let me know if you would prefer that I back the change out.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1677)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Pull request merged**
