### PR TITLE
Add documentation for Backup/Restore

### PR DESCRIPTION
**Pull request by jmgrady**
Add documentation to `./docs/docker_deploy/README.md` on how to backup/restore _TheCombine_ database and backend files.  In addition, 
 - the capitalization & punctuation of messages in the backup/restore scripts was fixed; and
 - no longer install an `uploads` folder - that is a vestige from when TeamCity updated the QA server with an SSH Upload.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/828)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/828)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[docs/docker_deploy/README.md, line 44 at r1](https://reviewable.io/reviews/sillsdev/thecombine/828#-MN-6KS42qKjklwLzQCU:-MN-6KS42qKjklwLzQCV:b-1wnx4h) ([raw file](https://github.com/sillsdev/thecombine/blob/3beba69ed6ff1fd6c941d2dfd8fd43a46882a896/docs/docker_deploy/README.md#L44)):*
> ```Markdown
>    3. [Updating Packages](#updating-packages)
> 
> ## Step-by-step Instructions
> ```

## -> #
___
*[docs/docker_deploy/README.md, line 152 at r1](https://reviewable.io/reviews/sillsdev/thecombine/828#-MN-60Oq3wMwszCxZxFQ:-MN-60Oq3wMwszCxZxFR:b-34d7zn) ([raw file](https://github.com/sillsdev/thecombine/blob/3beba69ed6ff1fd6c941d2dfd8fd43a46882a896/docs/docker_deploy/README.md#L152)):*
> ```Markdown
> # Backups
> 
> # Automated Backups
> ```

# -> ##

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/828)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[docs/docker_deploy/README.md, line 44 at r1](https://reviewable.io/reviews/sillsdev/thecombine/828#-MN-6KS42qKjklwLzQCU:-MN-7FCi748l9w387pC8:b-n8qyuy) ([raw file](https://github.com/sillsdev/thecombine/blob/3beba69ed6ff1fd6c941d2dfd8fd43a46882a896/docs/docker_deploy/README.md#L44)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

## -> #
</blockquote></details>

To match the sections below, "Step-by-step Instructions" and its subheadings could each use one less \#.
___
*[docs/docker_deploy/README.md, line 152 at r1](https://reviewable.io/reviews/sillsdev/thecombine/828#-MN-60Oq3wMwszCxZxFQ:-MN-6z_c5WolQhnHl62C:by2t3k1) ([raw file](https://github.com/sillsdev/thecombine/blob/3beba69ed6ff1fd6c941d2dfd8fd43a46882a896/docs/docker_deploy/README.md#L152)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

# -> ##
</blockquote></details>

(Oops, forgot to preview that and used \#s, which just did formatting.)
"Automated Backups" needs another \#

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/828)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/828)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[docs/docker_deploy/README.md, line 152 at r1](https://reviewable.io/reviews/sillsdev/thecombine/828#-MN-60Oq3wMwszCxZxFQ:-MN-Cxay6IweYMyvkIRC:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/3beba69ed6ff1fd6c941d2dfd8fd43a46882a896/docs/docker_deploy/README.md#L152)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

(Oops, forgot to preview that and used \#s, which just did formatting.)
"Automated Backups" needs another \#
</blockquote></details>

Done

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/828)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[docs/docker_deploy/README.md, line 152 at r1](https://reviewable.io/reviews/sillsdev/thecombine/828#-MN-60Oq3wMwszCxZxFQ:-MN-yayi7xBQI31_6yOs:bshx8yv) ([raw file](https://github.com/sillsdev/thecombine/blob/3beba69ed6ff1fd6c941d2dfd8fd43a46882a896/docs/docker_deploy/README.md#L152)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Done
</blockquote></details>

The first section is fixed, but "Automated Backups" still needs another \#. Then you can go ahead and "Mark all changes as reviewed, since I've already approved the pr.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/828)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
