### PR TITLE
Remove temporary .zip files generated during Lift import and export

### LINKED ISSUE #786: Backend should remove temporary files created during export and import
Relates to #656

The backend currently leaks disk space when processing exports and imports. It should delete the temporary files and folders it creates when it is done with them.

- `.CombineFiles/<project-id>/Export/*` 
- `.CombineFiles/<project-id>/Import/*`

Persistent files (so that they are not removed) are:

- Avatars
- Audio files
  - From a frontend user
  - From a lift import

### PR DESCRIPTION
**Pull request by johnthagen**
Closes #786

Should help some with #656

- The fix for LIFT export fixes a true disk space leak.
- Since Lift import can only be performed once, there is no recurring leak fixed on the import side, but the temporary file is still removed

The following files will no longer persist after an import in `.CombineFiles/<ProjectID>/Import`:
- `<temp-name-with-date>.zip`

Or after an export in `.CombineFiles/<ProjectID>/Export`:
- `<temp-name>.zip`
- `LiftExport`

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/791)

### CODE REVIEW

**Review by imnasnainaec — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/791)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @johnthagen)

___
*[Backend/Services/LiftApiServices.cs, line 271 at r1](https://reviewable.io/reviews/sillsdev/thecombine/791#-MKv4FNv40TeNQxy2X7P:-MKv4FNv40TeNQxy2X7Q:b32nqzt) ([raw file](https://github.com/sillsdev/thecombine/blob/2329884c06a73731752de9d063feb1500b8f1ba7/Backend/Services/LiftApiServices.cs#L271)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>             // Compress everything
>             var destinationFileName = Path.Combine(exportDir,
>                 Path.Combine($"LiftExportCompressed-{proj.Id}_{DateTime.Now:yyyy-MM-dd_hh-mm-ss}.zip"));
>             ZipFile.CreateFromDirectory(Path.GetDirectoryName(zipDir), destinationFileName);
>
>             // Clean up the temporary folder structure that was compressed.
>             Directory.Delete(Path.Combine(exportDir, "LiftExport"), true);
> ```
</details>

It looks like the zip file is created into `exportDir`, which is then immediately deleted. Shouldn't `zipDir` be deleted instead?

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/791)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[Backend/Services/LiftApiServices.cs, line 271 at r1](https://reviewable.io/reviews/sillsdev/thecombine/791#-MKv4FNv40TeNQxy2X7P:-MKv52hvBcvk27AmgT4m:b-zb8qad) ([raw file](https://github.com/sillsdev/thecombine/blob/2329884c06a73731752de9d063feb1500b8f1ba7/Backend/Services/LiftApiServices.cs#L271)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>             // Compress everything
>             var destinationFileName = Path.Combine(exportDir,
>                 Path.Combine($"LiftExportCompressed-{proj.Id}_{DateTime.Now:yyyy-MM-dd_hh-mm-ss}.zip"));
>             ZipFile.CreateFromDirectory(Path.GetDirectoryName(zipDir), destinationFileName);
>
>             // Clean up the temporary folder structure that was compressed.
>             Directory.Delete(Path.Combine(exportDir, "LiftExport"), true);
> ```
It looks like the zip file is created into `exportDir`, which is then immediately deleted. Shouldn't `zipDir` be deleted instead?
</blockquote></details>

Sorry, never mind, I see that it's a subfolder of `exportDir` (which contains `zipDir`) that is being deleted.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/791)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @johnthagen)

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/791)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Pull request merged**
