### PR TITLE
Add Arabic and rtl lang support

### LINKED ISSUE #2075: Implement formatted translations
Especially in preparation for right-to-left languages, some of our strings need to make use of https://www.i18next.com/translation-function/formatting

In the project statistics ProgressBar, we have (e.g.)`Domains Collected: 1294` which is implemented with
```
        <ListItemText primary={t("statistics.wordsCollected")} />
        <Typography>{totalWordCount}</Typography>
```
but should probably be something like 
```
 <ListItemText primary={t("statistics.wordsCollected", {val: totalWordCount})} />
```

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #2075
Also fixes the third part of #2048 

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2084)

### CODE REVIEW

**Comment by imnasnainaec** [comment]
Setting "dir="rtl" makes the footer of the MaterialTable very confusing: https://github.com/material-table-core/core/issues/760

**Review by jasonleenaylor — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 1 of 8 files at r2, 2 of 34 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2084)* status: 5 of 44 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[`public/locales/es/translation.json` line 221 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2084#-NTzlv7ZCB0VkTb8JUuc:-NTzlv7ZCB0VkTb8JUud:b7f6hdr) ([raw file](https://github.com/sillsdev/TheCombine/blob/595288587af47ff4bab5ff0f14d924c329034653/public/locales/es/translation.json#L221)):*
> ```JSON
>       "stepMerge": "Merge Set",
>       "of": "de"
>     }
> ```

Not current with English.



_Code quote:_
```JSON
    "progress": {
      "step": "Paso",
      "stepMerge": "Merge Set",
      "of": "de"
    }
```

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2084)* status: 5 of 44 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jasonleenaylor)

___
*[`public/locales/es/translation.json` line 221 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/2084#-NTzlv7ZCB0VkTb8JUuc:-NU1cpDNCnHgOCq0b_pZ:b1qgzr4) ([raw file](https://github.com/sillsdev/TheCombine/blob/595288587af47ff4bab5ff0f14d924c329034653/public/locales/es/translation.json#L221)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Not current with English.
</blockquote></details>

Anything not present in another language will default to English, and this will get updated correctly when we cycle everything through Crowdin.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 3 of 8 files at r2, 21 of 34 files at r3, 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2084)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2084)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[`src/i18n.ts` line 34 at r5](https://reviewable.io/reviews/sillsdev/TheCombine/2084#-NUN3JpJ1gJQCadRYPvt:-NUN3JpJ1gJQCadRYPvu:b-600ytk) ([raw file](https://github.com/sillsdev/TheCombine/blob/9e8aa5b8f82ec422f7fccd3559dff33fb593d1e4/src/i18n.ts#L34)):*
> ```XML
>       interpolation: { escapeValue: false },
>     },
>     setDir
> ```

comment here that this is a callback would be good.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2084)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
