### PR TITLE
Reduce backend memory leak in Lift export

### LINKED ISSUE #688: Memory leak on server when project is exported
When the project is exported, there is a memory leak on the server.  This was observed during the Haisla Rapid Word Collection workshop.  The following measurements were made on an Ubuntu 18.04 Server with 4 GB RAM.  The memory usage was measured using `glances`.

- TheCombine server first starts up (backend running): 470MB of RAM
- Login & navigate to site settings: 511 MB
- Export Haisla_RWC: 979MB
- The memory usage only drops back to 966MB when the export is complete
- Export Haisla_RWC a second time: 1.2 GB
- Export Haisla_RWC a third time: 1.54 GB

The Haisla_RWC export file was about 60 MB.

### PR DESCRIPTION
**Pull request by johnthagen**
Closes #688

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/694)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/694)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[Backend/Services/LiftApiServices.cs, line 53 at r1](https://reviewable.io/reviews/sillsdev/thecombine/694#-MGPXZLBEDx0u_3KSecz:-MGPXZLCCRnCRbxo_ehj:b-8xe68h) ([raw file](https://github.com/sillsdev/thecombine/blob/f0afe11be92bb0bdbb13146cb156716a50efc1f0/Backend/Services/LiftApiServices.cs#L53)):*
> ```Smalltalk
>             //    fixed to properly to avoid needing to override its Dispose method.
>             //    https://github.com/sillsdev/libpalaso/blob/master/SIL.DictionaryServices/Lift/LiftWriter.cs
>             Writer.Close();
> ```

Hmm, I think calling the base.Dispose() here will cause a problem. I think it does try to call Writer.Close() and that might throw if the Writer has been disposed. I think you can safely skip the call to base.Dispose().

**Comment by johnthagen** [comment]
___
*[Backend/Services/LiftApiServices.cs, line 53 at r1](https://reviewable.io/reviews/sillsdev/thecombine/694#-MGPXZLBEDx0u_3KSecz:-MGPb98K-Pjb-a4-c1-L:bvtqxxp) ([raw file](https://github.com/sillsdev/thecombine/blob/f0afe11be92bb0bdbb13146cb156716a50efc1f0/Backend/Services/LiftApiServices.cs#L53)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Hmm, I think calling the base.Dispose() here will cause a problem. I think it does try to call Writer.Close() and that might throw if the Writer has been disposed. I think you can safely skip the call to base.Dispose().
</blockquote></details>

I had similar concerns and was surprised when it didn't throw. Seems that `Close()` must check if it's been disposed. 

I will still go ahead and remove `base.Dispose()`. I was worried that if the base class got updated in the future and this code was still in, that we'd miss freeing other resources in the base class. Hopefully the TODO is enough of a warning about that.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 3 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/694)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[Backend/Services/LiftApiServices.cs, line 51 at r5](https://reviewable.io/reviews/sillsdev/thecombine/694#-MGtRp8IDMFsyldpcPxU:-MGtRp8IDMFsyldpcPxV:b-dui5an) ([raw file](https://github.com/sillsdev/thecombine/blob/8d709b40cf9263bdc5832a002cda0089c12503ff/Backend/Services/LiftApiServices.cs#L51)):*
> ```Smalltalk
>         {
>             // TODO: When updating the LiftWriter dependency, check to see if its Dispose() implementation has been
>             //    fixed to properly to avoid needing to override its Dispose method.
> ```

"... to properly to avoid needing to override..."?
___
*[Backend/Services/LiftApiServices.cs, line 407 at r5](https://reviewable.io/reviews/sillsdev/thecombine/694#-MGtVV0o42kFtsbaFQHZ:-MGtVV0o42kFtsbaFQH_:bxrwpu1) ([raw file](https://github.com/sillsdev/thecombine/blob/807020f2a939c2ca8deed2c3dce64171ce20c555/Backend/Services/LiftApiServices.cs#L407)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>             // Only used when importing semantic domains from a lift-ranges file
>             if (_sdList.Count != 0 && proj.SemanticDomains.Count == 0)
>             {
>                 proj.SemanticDomains = _sdList;
>                 await _projService.Update(_projectId, proj);
>             }
> ```
</details>

I don't know what this was for so I cannot confirm that its removal is good.

**Comment by johnthagen** [comment]
___
*[Backend/Services/LiftApiServices.cs, line 51 at r5](https://reviewable.io/reviews/sillsdev/thecombine/694#-MGtRp8IDMFsyldpcPxU:-MGwwk9k8sj8w8bFmA1u:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/8d709b40cf9263bdc5832a002cda0089c12503ff/Backend/Services/LiftApiServices.cs#L51)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

"... to properly to avoid needing to override..."?
</blockquote></details>

Done

**Comment by johnthagen** [comment]
___
*[Backend/Services/LiftApiServices.cs, line 407 at r5](https://reviewable.io/reviews/sillsdev/thecombine/694#-MGtVV0o42kFtsbaFQHZ:-MGwwpS54eKOtHYm0KR4:b-yxzmh7) ([raw file](https://github.com/sillsdev/thecombine/blob/807020f2a939c2ca8deed2c3dce64171ce20c555/Backend/Services/LiftApiServices.cs#L407)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>             // Only used when importing semantic domains from a lift-ranges file
>             if (_sdList.Count != 0 && proj.SemanticDomains.Count == 0)
>             {
>                 proj.SemanticDomains = _sdList;
>                 await _projService.Update(_projectId, proj);
>             }
> ```
I don't know what this was for so I cannot confirm that its removal is good.
</blockquote></details>

@jasonleenaylor removed these, and is primary author on the Lift Export, so I presume this was intentional.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/694)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by jasonleenaylor** [comment]
___
*[Backend/Services/LiftApiServices.cs, line 407 at r5](https://reviewable.io/reviews/sillsdev/thecombine/694#-MGtVV0o42kFtsbaFQHZ:-MGxYjj35-p31yJfM4R1:bjh6blj) ([raw file](https://github.com/sillsdev/thecombine/blob/807020f2a939c2ca8deed2c3dce64171ce20c555/Backend/Services/LiftApiServices.cs#L407)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

@jasonleenaylor removed these, and is primary author on the Lift Export, so I presume this was intentional.
</blockquote></details>

This code wasn't currently useful and complicated the refactor. In the future in order to handle custom semantic domains we will need to have a different design.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/694)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
