### PR TITLE
Obliviate goal/edit index

### LINKED ISSUE #1541: Change UpdateUserEditStep to use a Edit GUID rather than a Goal index
Rather than indexing a `List<Edit>`  in `UpdateUserEditStep()` to select which `Edit`  based on a `GoalIndex` use a, reference the `Edit` but it's `Guid`.

This would allow removing `goal.index` and obliviate the need to do #1539

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #1541

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2793)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 6 of 12 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2793)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[`Backend/Models/UserEdit.cs` line 78 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2793#-NkphLqsES6Ypu3D9LBi:-NkphLqsES6Ypu3D9LBj:b389pro) ([raw file](https://github.com/sillsdev/TheCombine/blob/3da0b1adcd4eb52f254e4241ebe0e693d956fafd/Backend/Models/UserEdit.cs#L78)):*
> ```Smalltalk
>         [Required]
>         [BsonElement("editGuid")]
>         public Guid EditGuid { get; set; }
> ```

Won't this new Required element require a db migration?

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2793)* status: 12 of 13 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

___
*[`Backend/Models/UserEdit.cs` line 78 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2793#-NkphLqsES6Ypu3D9LBi:-NkqLn5CBRujgN3OHxeL:bj6qqul) ([raw file](https://github.com/sillsdev/TheCombine/blob/be8911f4ed30dd7d2e8c031469bf4ccda150680b/Backend/Models/UserEdit.cs#L78)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Won't this new Required element require a db migration?
</blockquote></details>

No, that object doesn't appear in the database. I believe the `[required]` attribute from `using System.ComponentModel.DataAnnotations` is for the controller function to use `BindRequired` :
```
        /// <summary> Adds/updates a step to/in specified goal </summary>
        /// <returns> Index of added/modified step in specified goal </returns>
        [HttpPut("{userEditId}", Name = "UpdateUserEditStep")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        public async Task<IActionResult> UpdateUserEditStep(string projectId, string userEditId,
            [FromBody, BindRequired] UserEditStepWrapper stepEdit)
```

That said, the `[Bson...]` attributes were unnecessary with `UserEditStepWrapper`, so I removed them.

**Review by jasonleenaylor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2793)* status: 12 of 13 files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 5 of 12 files at r1, 7 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2793)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
