### PR TITLE
Bump dotnet global tools

### LINKED ISSUE #1568: Update dotnet global version installs in README

### PR DESCRIPTION
**Pull request by johnthagen**
Closes #1568

Bump the prescribed/tested versions of `dotnet-format` and `dotnet-reportgenerator-globaltool`

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1571)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1571)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[scripts/genBackendCoverageReport.ts, line 38 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1571#-MwCQ9tF5ugffXw-y-V8:-MwCQ9tF5ugffXw-y-V9:b-k2pczf) ([raw file](https://github.com/sillsdev/thecombine/blob/076c847fb1348a710a525560bd1dc1a544029630/scripts/genBackendCoverageReport.ts#L38)):*
> ```XML
> } else {
>   console.log(
>     `${coverageInfoFile} does not exist. First run: npm run coverage.`
> ```

Here too.

**Comment by johnthagen** [comment]
___
*[scripts/genBackendCoverageReport.ts, line 38 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1571#-MwCQ9tF5ugffXw-y-V8:-MwCR3coBjTwq3cFaRA2:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/851162501d1e0b752bbcf89497a3ad64bbad2086/scripts/genBackendCoverageReport.ts#L38)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Here too.
</blockquote></details>

Done.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1571)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @johnthagen)

___
*[scripts/genBackendCoverageReport.ts, line 38 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1571#-MwCQ9tF5ugffXw-y-V8:-MwCRVIzBKKuoEu-bLtB:bvo26bx) ([raw file](https://github.com/sillsdev/thecombine/blob/851162501d1e0b752bbcf89497a3ad64bbad2086/scripts/genBackendCoverageReport.ts#L38)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Done.
</blockquote></details>

For the sake of a user copy-pasting, we may not want the final ".".

**Comment by johnthagen** [comment]
___
*[scripts/genBackendCoverageReport.ts, line 38 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1571#-MwCQ9tF5ugffXw-y-V8:-MwCWTaB1fSup5wrueeo:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/851162501d1e0b752bbcf89497a3ad64bbad2086/scripts/genBackendCoverageReport.ts#L38)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

For the sake of a user copy-pasting, we may not want the final ".".
</blockquote></details>

Done.

**Pull request merged**
