### PR TITLE
Determine different permissions for different goals

### LINKED ISSUE #1472: Non-admin users cannot update character inventory
Non-admin users have access to all goals (Merge Duplicates, Review Entries, Create Character Inventory), but are prevented from submitting changes in the Character Inventory.

**To Reproduce**

1. Open/create a project with at least one entry.
2. Go to user settings and invite another user to the project.
3. Log in as the other user.
4. Click on Data Cleanup > Create Character Inventory.
5. Select one of the characters, press the "Accept" button, then the "Save".
6. See the 403 error pop up.

**Expected behavior**

One of two options:
* ~Allow users to update character inventory;~
* For users who can't update character inventory, don't allow access this goal in the first place.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #1472

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1478)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[src/components/GoalTimeline/GoalTimelineComponent.tsx, line 78 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1478#-Mq-b5B-3OBt5eh9JeV6:-Mq-b5B00oFf95WjV5_K:b9jy6dy) ([raw file](https://github.com/sillsdev/thecombine/blob/594ed1fc77e8b94093a0e71bd86b63457f791565/src/components/GoalTimeline/GoalTimelineComponent.tsx#L78)):*
> ```XML
>   componentDidMount() {
>     window.addEventListener("resize", this.handleWindowSizeChange);
>     this.getSuggestionsWithPermission();
> ```

Rider flagged that the Promise here is ignored. Is it safe to do that?

**Comment by johnthagen** [comment]
___
*[src/components/GoalTimeline/GoalTimelineComponent.tsx, line 111 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1478#-Mq-bNC1AF23INQXznOa:-Mq-bNC1AF23INQXznOb:bwqmd29) ([raw file](https://github.com/sillsdev/thecombine/blob/594ed1fc77e8b94093a0e71bd86b63457f791565/src/components/GoalTimeline/GoalTimelineComponent.tsx#L111)):*
> ```XML
>       availableGoalTypes.includes(t)
>     );
>     if (!suggestions?.length) {
> ```

It seems that `suggestions` cannot be `undefined` or `null`. Should this `?` be removed?

**Comment by johnthagen** [comment]
___
*[src/components/GoalTimeline/GoalTimelineComponent.tsx, line 106 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1478#-Mq-bw0rAjA_xcUmospF:-Mq-bw0rAjA_xcUmospG:b1lf30e) ([raw file](https://github.com/sillsdev/thecombine/blob/594ed1fc77e8b94093a0e71bd86b63457f791565/src/components/GoalTimeline/GoalTimelineComponent.tsx#L106)):*
> ```XML
>   // Creates a list of suggestions, with non-suggested goals at the end and
>   // our main suggestion absent (to be displayed on the suggestions button).
>   // Avoids referencing this.state for testing purposes.
> ```

It could also be argued that developing using more pure functions in general (avoiding implicit inputs via `this`, etc.) is a good practice anyway. So I think this change is probably good on its own.

Though, React Components are littered with state, so it's not unexpected we have many such functions.

**Comment by johnthagen** [comment]
___
*[src/types/goalUtilities.ts, line 21 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1478#-Mq-dC8l9cpv38G9Q4jq:-Mq-dC8m7Tzm2qfNrbEX:b-2iifbg) ([raw file](https://github.com/sillsdev/thecombine/blob/594ed1fc77e8b94093a0e71bd86b63457f791565/src/types/goalUtilities.ts#L21)):*
> ```XML
> }
> 
> export function requiredPermission(type: GoalType): Permission {
> ```

I think a doc comment could help this function. It took me a little bit to understand it's purpose.

**Comment by johnthagen** [comment]
___
*[src/types/goalUtilities.ts, line 29 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1478#-Mq-dPv09FVdoGpcn1ti:-Mq-dPv09FVdoGpcn1tj:b-qr8kri) ([raw file](https://github.com/sillsdev/thecombine/blob/594ed1fc77e8b94093a0e71bd86b63457f791565/src/types/goalUtilities.ts#L29)):*
> ```XML
>       return Permission.DeleteEditSettingsAndUsers;
>     default:
>       return Permission.Unused;
> ```

It struck me a little odd that if we haven't listed a `GoalType` explicitly in this function, it defaults to needing `Unused`.

We are adding the `Unused` Permission in a lot of areas throughout the codebase. Should we assign a better name to this that would help express what it's actual meaning is?

**Review by johnthagen — CHANGES_REQUESTED** [review]
> Reviewed 12 of 13 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1478)* status: all files reviewed, 5 unresolved discussions (waiting on @imnasnainaec)

**Comment by johnthagen** [comment]
When I loaded up this branch and tried to add a new user to an existing project, I got the following backend exception:

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.ArgumentNullException: Value cannot be null. (Parameter 'collection')
         at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
         at BackendFramework.Controllers.UserRoleController.UpdateUserRolePermissions(String projectId, String userId, Permission[] permissions) in C:\Users\User\GitHub\TheCombine\Backend\Controllers\UserRoleController.cs:line 203
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 PUT http://localhost:5000/v1/projects/61aa2dc69e19e78e9896e630/userroles/61aa2df49e19e78e9896f536 application/json 40 - 500 - text/plain 38.4793ms
```

**Comment by johnthagen** [comment]
After resetting my database and trying again, I can't reproduce this stacktrace.

**Comment by johnthagen** [comment]
This PR correctly does not show the character inventory goal for invited users.

Screenshot 2021-12-03 095858

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1478)* status: 14 of 25 files reviewed, 4 unresolved discussions (waiting on @imnasnainaec and @johnthagen)

___
*[src/components/GoalTimeline/GoalTimelineComponent.tsx, line 78 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1478#-Mq-b5B-3OBt5eh9JeV6:-Mq0Q3rE6_FT9ETZvJjA:b-bjpj7a) ([raw file](https://github.com/sillsdev/thecombine/blob/594ed1fc77e8b94093a0e71bd86b63457f791565/src/components/GoalTimeline/GoalTimelineComponent.tsx#L78)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Rider flagged that the Promise here is ignored. Is it safe to do that?
</blockquote></details>

Better?
___
*[src/components/GoalTimeline/GoalTimelineComponent.tsx, line 111 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1478#-Mq-bNC1AF23INQXznOa:-Mq0QttrDyAZrq1vLzdF:boag87p) ([raw file](https://github.com/sillsdev/thecombine/blob/594ed1fc77e8b94093a0e71bd86b63457f791565/src/components/GoalTimeline/GoalTimelineComponent.tsx#L111)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

It seems that `suggestions` cannot be `undefined` or `null`. Should this `?` be removed?
</blockquote></details>

Commented.
___
*[src/types/goalUtilities.ts, line 21 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1478#-Mq-dC8l9cpv38G9Q4jq:-Mq0QwKn41UN2DQ-TNMz:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/594ed1fc77e8b94093a0e71bd86b63457f791565/src/types/goalUtilities.ts#L21)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I think a doc comment could help this function. It took me a little bit to understand it's purpose.
</blockquote></details>

Done.
___
*[src/types/goalUtilities.ts, line 29 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1478#-Mq-dPv09FVdoGpcn1ti:-Mq0PsqpCXi5SM-fUe8A:byshwbn) ([raw file](https://github.com/sillsdev/thecombine/blob/594ed1fc77e8b94093a0e71bd86b63457f791565/src/types/goalUtilities.ts#L29)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

It struck me a little odd that if we haven't listed a `GoalType` explicitly in this function, it defaults to needing `Unused`.

We are adding the `Unused` Permission in a lot of areas throughout the codebase. Should we assign a better name to this that would help express what it's actual meaning is?
</blockquote></details>

At least here, we can restrict the permission to owner unless specified otherwise.

**Review by johnthagen — APPROVED** [review]
> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1478)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
