### PR TITLE
[GoalsActions] Fix user updating during project creation

### LINKED ISSUE #691: Project not loaded after creation: 403 returned when browsing to Data Entry
1. Register a new user
2. Create a new project: Test | fr | en
3. Data Entry | Universe | Universe

```
info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      Executing ObjectResult, writing value of type 'BackendFramework.Models.User'.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action BackendFramework.Controllers.UserController.Get (BackendFramework) in 1.7774ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'BackendFramework.Controllers.UserController.Get (BackendFramework)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 2.299ms 200 application/json; charset=utf-8
info: Microsoft.AspNetCore.Mvc.ForbidResult[1]
      Executing ForbidResult with authentication schemes ().
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[13]
      AuthenticationScheme: Bearer was forbidden.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action BackendFramework.Controllers.FrontierController.GetFrontier (BackendFramework) in 5.6275ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'BackendFramework.Controllers.FrontierController.GetFrontier (BackendFramework)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 13.7056ms 403
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:5001/v1/projects/5f5275d5813f55405c8e0b8c/words/frontier
info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
      CORS policy execution successful.
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
      Successfully validated the token.
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'BackendFramework.Controllers.FrontierController.GetFrontier (BackendFramework)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "GetFrontier", controller = "Frontier"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] GetFrontier(System.String) on controller BackendFramework.Controllers.FrontierController (BackendFramework).
info: Microsoft.AspNetCore.Mvc.ForbidResult[1]
      Executing ForbidResult with authentication schemes ().
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[13]
      AuthenticationScheme: Bearer was forbidden.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action BackendFramework.Controllers.FrontierController.GetFrontier (BackendFramework) in 4.4209ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'BackendFramework.Controllers.FrontierController.GetFrontier (BackendFramework)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 5.825ms 403
```

### LINKED ISSUE #692: On creation of new project, the userRole created for the project is added to the user but not persisting
Creating a new project successfully creates a new userRole and applies that to the user (https://github.com/sillsdev/TheCombine/blob/master/Backend/Controllers/ProjectController.cs#L133-L135). A debugging run showed the new userRole present at the end of that controller function. Once the project is created, userEdits are setup for the project (https://github.com/sillsdev/TheCombine/blob/master/src/components/ProjectScreen/CreateProject/CreateProjectActions.tsx#L75) which may update the user overwriting the userRole just added (https://github.com/sillsdev/TheCombine/blob/1cbc32cff95473095365741619daccc5a1b834f9/src/components/GoalTimeline/GoalsActions.tsx#L82-L96).

### PR DESCRIPTION
**Pull request by imnasnainaec**
* Fix Axios response interceptor
* Move update of user with a new userEdit from GoalsActions in the frontend to UserEditController in the backend

Fixes #691 , Fixes #692

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/693)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[src/components/GoalTimeline/GoalsActions.tsx, line 73 at r1](https://reviewable.io/reviews/sillsdev/thecombine/693#-MGPNQXNCQiOqsGWxSfS:-MGPNQXNCQiOqsGWxSfT:b-fewk62) ([raw file](https://github.com/sillsdev/thecombine/blob/b274c19e414e6530c5c19fdc195645ec95893dab/src/components/GoalTimeline/GoalsActions.tsx#L73)):*
> ```XML
>     await Backend.createUserEdit()
>       .then(async (userEditId: string) => {
>         const LocalUser = LocalStorage.getCurrentUser();
> ```

`localUser` to match style guide.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/693)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @johnthagen)

___
*[src/components/GoalTimeline/GoalsActions.tsx, line 73 at r1](https://reviewable.io/reviews/sillsdev/thecombine/693#-MGPNQXNCQiOqsGWxSfS:-MGPOG-P0xmwz-w59CQD:b-e7hr3z) ([raw file](https://github.com/sillsdev/thecombine/blob/b274c19e414e6530c5c19fdc195645ec95893dab/src/components/GoalTimeline/GoalsActions.tsx#L73)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

`localUser` to match style guide.
</blockquote></details>

But I was 2 for 2: https://github.com/sillsdev/TheCombine/issues/692#issuecomment-687302305

Fixed.

**Comment by johnthagen** [comment]
@imnasnainaec I am still getting a forbidden when I execute the steps in #691 from a clean database

**Comment by imnasnainaec** [comment]
> @imnasnainaec I am still getting a forbidden when I execute the steps in #691 from a clean database
@johnthagen Ah, I forgot to check the fix with a new user.

**Comment by imnasnainaec** [comment]
> > @imnasnainaec I am still getting a forbidden when I execute the steps in #691 from a clean database
> 
> @johnthagen Ah, I forgot to check the fix with a new user.

@johnthagen Rather, I didn't see the error because I was testing with an admin user.

**Comment by johnthagen** [comment]
___
*[src/backend/index.tsx, line 23 at r4](https://reviewable.io/reviews/sillsdev/thecombine/693#-MGZUD9v2l1s7xN3VS7x:-MGZUD9v2l1s7xN3VS7y:bj5iwv4) ([raw file](https://github.com/sillsdev/thecombine/blob/ccfe18102ac0696654fdf4b6acefde99f6c51c4a/src/backend/index.tsx#L23)):*
> ```XML
> backendServer.interceptors.response.use(
>   (resp) => {
>     if (resp.data.__UpdatedUser) {
> ```

This is where silent conversion to `boolean` really bit us. I bet this was set to `undefined` rather than `null` or something, and so we never took this code path even though we meant to check for `null` rather than `undefined`?

**Comment by johnthagen** [comment]
___
*[src/components/GoalTimeline/GoalsActions.tsx, line 72 at r4](https://reviewable.io/reviews/sillsdev/thecombine/693#-MGZUkbl-C05Iy95bEaX:-MGZUkbl-C05Iy95bEaY:b464vev) ([raw file](https://github.com/sillsdev/thecombine/blob/48e79b9ac1119021ad8580336c7ed89d5f1480d5/src/components/GoalTimeline/GoalsActions.tsx#L72)):*
> ```XML
>   return async (dispatch: ThunkDispatch<StoreState, any, GoalAction>) => {
>     const user: User | null = LocalStorage.getCurrentUser();
>     const projectId: string = LocalStorage.getProjectId();
> ```

Could we strip away these extra type annotations that can be inferred by the compiler/IDE per our style guide?

**Review by johnthagen — APPROVED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/693)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

**Comment by johnthagen** [comment]
I have confirmed that this solves the issue I reported in #691

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/693)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @johnthagen)

___
*[src/components/GoalTimeline/GoalsActions.tsx, line 72 at r4](https://reviewable.io/reviews/sillsdev/thecombine/693#-MGZUkbl-C05Iy95bEaX:-MGi04FS3smKmmzT13B_:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/48e79b9ac1119021ad8580336c7ed89d5f1480d5/src/components/GoalTimeline/GoalsActions.tsx#L72)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Could we strip away these extra type annotations that can be inferred by the compiler/IDE per our style guide?
</blockquote></details>

Done

**Pull request merged**
