### PR TITLE
Add Definition model, import, export.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Parts 1-2 of #1226 and invisibly preserve definitions through merging.

Also, clean up various frontend `if`, `find`, `map`, and `filter` instances. 

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1244)

### CODE REVIEW

**Review by jasonleenaylor — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, 6 of 13 files at r2, 2 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1244)* status: 17 of 22 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jasonleenaylor)

___
*[src/goals/MergeDupGoal/Redux/tests/MergeDupActions.test.tsx, line 347 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1244#-Me750tY8MnQ1pH-FVqH:-Me750tY8MnQ1pH-FVqI:bletun8) ([raw file](https://github.com/sillsdev/thecombine/blob/dc3e771568d31a0c48c5bbed4118e485ff31db69/src/goals/MergeDupGoal/Redux/tests/MergeDupActions.test.tsx#L347)):*
> ```
> expect(sense.definitions).toHaveLength(2);
> ```
Ok, I would expect this to be length 1, unless you are relying on the previous test to have been run. It is bad practice to expect the tests to be run in any particular order. I'd recommend using `let sense` in the describe and add a `beforeEach()` with `sense = newSense()` and adjust the test content to make sure.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1244)* status: 17 of 22 files reviewed, 1 unresolved discussion (waiting on @JacobHaimes, @jasonleenaylor, and @WeJamUS)

___
*[src/goals/MergeDupGoal/Redux/tests/MergeDupActions.test.tsx, line 347 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1244#-Me750tY8MnQ1pH-FVqH:-Me78z6G2mf5Kz_VvdU7:b-twu1to) ([raw file](https://github.com/sillsdev/thecombine/blob/dc3e771568d31a0c48c5bbed4118e485ff31db69/src/goals/MergeDupGoal/Redux/tests/MergeDupActions.test.tsx#L347)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> expect(sense.definitions).toHaveLength(2);
> ```
Ok, I would expect this to be length 1, unless you are relying on the previous test to have been run. It is bad practice to expect the tests to be run in any particular order. I'd recommend using `let sense` in the describe and add a `beforeEach()` with `sense = newSense()` and adjust the test content to make sure.

</blockquote></details>

Ah, definitely!

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 4 of 13 files at r2, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1244)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JacobHaimes and @WeJamUS)

**Comment by johnthagen** [comment]
___
*[Backend/Helper/DuplicateFinder.cs, line 217 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1244#-MeBe25y47BoMb5ote_B:-MeBe25y47BoMb5ote_C:be23qg5) ([raw file](https://github.com/sillsdev/thecombine/blob/ece580be397f67445868e417579b858c91269cf6/Backend/Helper/DuplicateFinder.cs#L217)):*
> ```Smalltalk
>         /// Check if two <see cref="Word"/>s have <see cref="Definition"/>s with identical Language and nonempty Text.
>         /// </summary>
>         public static bool HaveIdenticalDefinition(Word wordA, Word wordB)
> ```

At first blush this could maybe be a method on `Word` itself, similar to `Equals`? Not sure how niche this functionality is though.

**Comment by johnthagen** [comment]
___
*[Backend/Helper/DuplicateFinder.cs, line 218 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1244#-MeBg1zg2cKMz9Iam6jJ:-MeBg1zg2cKMz9Iam6jK:b2mie7v) ([raw file](https://github.com/sillsdev/thecombine/blob/ece580be397f67445868e417579b858c91269cf6/Backend/Helper/DuplicateFinder.cs#L218)):*
> ```Smalltalk
>         /// </summary>
>         public static bool HaveIdenticalDefinition(Word wordA, Word wordB)
>         {
> ```

Could we add a unit test for this function (wherever it ends up)?

**Comment by johnthagen** [comment]
___
*[Backend/Services/LiftService.cs, line 392 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1244#-MeBgBoK4jKqMbo2xtsh:-MeBgBoK4jKqMbo2xtsi:bb69y0z) ([raw file](https://github.com/sillsdev/thecombine/blob/ece580be397f67445868e417579b858c91269cf6/Backend/Services/LiftService.cs#L392)):*
> ```Smalltalk
>             {
>                 // Merge in senses
>                 const string sep = ";";
> ```

Do any of the existing `LiftService` unit tests exercise this functionality? If not, could test(s) be added?

**Pull request merged**
