### PR TITLE
Add site-wide banners

### LINKED ISSUE #1297: Add maintenance/admin messages to frontend
Add the ability to display maintenance and administration messages to the user, such as planned downtime for backups and upgrades.

The [GitLab Broadcast Messages](https://docs.gitlab.com/ee/user/admin_area/broadcast_messages.html) are an example implementation.
See also GitLab's documentation on how to [Customize the Help and sign-in page messages](https://docs.gitlab.com/ee/user/admin_area/settings/help_page.html).

### PR DESCRIPTION
**Pull request by johnthagen**
Closes #1297

Also: enable `attr_list` Markdown extension in the user guide and center images.

### TODO

- [x] Display `Banner.Login` on the login page
- [x] Display `Banner.Announcement` at the top of all pages
- [x] Update Site Settings to allow admin users to update the `Banner`
- [x] Fix `useEffect` `getBanner()` calls to not ignore returned promises
- [x] Fix unit test (related to ignored promise)
- [x] Fix styling on new UI elements (margins, etc)
- [x] Add button for user to close a banner

Ideally for the announcement banner we could use https://github.com/alexplumb/material-ui-banner, but it does not support compiling under TypeScript: https://github.com/alexplumb/material-ui-banner/issues/8

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1319)

### CODE REVIEW

**Review by jmgrady — COMMENTED** [review]
> Reviewed 27 of 38 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1319)* status: 29 of 39 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @johnthagen)

___
*[src/components/TreeView/TreeViewComponent.tsx, line 56 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1319#-MkD0CgU69qGwgoB_iv_:-MkD0CgVEo-bzhpc8zhu:b-4x0xvg) ([raw file](https://github.com/sillsdev/thecombine/blob/ac8420c6bd010254d49178935e90a76f62dcea93/src/components/TreeView/TreeViewComponent.tsx#L56)):*
> ```
> this.props.currentDomain.name
> ```
In other updates in this PR, a test of `some_string != ""` was replaced with `!!some_string`.  Why is there no double-negation operator this time?

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 38 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1319)* status: 29 of 39 files reviewed, all discussions resolved (waiting on @imnasnainaec and @johnthagen)

___
*[src/components/TreeView/TreeViewComponent.tsx, line 56 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1319#-MkD0CgU69qGwgoB_iv_:-MkDMRWD8FxZJsOJ5A-s:b-boiqao) ([raw file](https://github.com/sillsdev/thecombine/blob/ac8420c6bd010254d49178935e90a76f62dcea93/src/components/TreeView/TreeViewComponent.tsx#L56)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

> ```
> this.props.currentDomain.name
> ```
In other updates in this PR, a test of `some_string != ""` was replaced with `!!some_string`.  Why is there no double-negation operator this time?
</blockquote></details>

Because this one's in `if (...)`, it is cast as a bool without needing to `!!`.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 14 of 38 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1319)* status: 36 of 47 files reviewed, all discussions resolved (waiting on @johnthagen)

**Review by jmgrady — COMMENTED** [review]
> Reviewed 8 of 8 files at r4, 2 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1319)* status: 42 of 47 files reviewed, all discussions resolved (waiting on @imnasnainaec and @johnthagen)

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 3 of 38 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1319)* status: 44 of 47 files reviewed, all discussions resolved (waiting on @imnasnainaec, @jmgrady, and @johnthagen)

**Review by jmgrady — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1319)* status: 42 of 47 files reviewed, all discussions resolved (waiting on @imnasnainaec and @johnthagen)

**Review by jmgrady — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1319)* status: 42 of 47 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @johnthagen)

___
*[Backend/Models/Banner.cs, line 54 at r7](https://reviewable.io/reviews/sillsdev/thecombine/1319#-MkHFjyRBWz2Fk3vLVgS:-MkHFjySCkGQNjMVsDSB:b-56mg62) ([raw file](https://github.com/sillsdev/thecombine/blob/3f740c7f5c1b0931b9bc2e4ad9d2236f51992e27/Backend/Models/Banner.cs#L54)):*
<details><summary><i alt="summary">Quoted 28 lines of code…</i></summary>

> ```
>     public class SiteBanner
>     {
>         [Required]
>         public string Login { get; set; }
>         [Required]
>         public string Announcement { get; set; }
> 
>         public SiteBanner()
>         {
>             Login = "";
>             Announcement = "";
>         }
> 
>         public override bool Equals(object? obj)
>         {
>             if (obj is not SiteBanner other || GetType() != obj.GetType())
>             {
>                 return false;
>             }
> 
>             return Login.Equals(other.Login) && Announcement.Equals(other.Announcement);
>         }
> 
>         public override int GetHashCode()
>         {
>             return HashCode.Combine(Login, Announcement);
>         }
>     }
> ```
</details>


I think this API should be improved.  The current implementation is hard to extend.  The `BannerCollection` is not a collection at all but a single document.  It would be better to have a single banner per document, such as:
```
{
  "_id" : "12345...",
  "name" :  "login",
  "value" :  "",
}
```
Then each banner message can be found by using the `name` as the key and it is easy to add banners without changing the API/structure of the database document.  This means no requirement to update the database when a new message type is added.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1319)* status: 29 of 49 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec, @jmgrady, and @johnthagen)

___
*[Backend/Models/Banner.cs, line 54 at r7](https://reviewable.io/reviews/sillsdev/thecombine/1319#-MkHFjyRBWz2Fk3vLVgS:-MkIn-zo2PpihpACoCDM:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/3f740c7f5c1b0931b9bc2e4ad9d2236f51992e27/Backend/Models/Banner.cs#L54)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

> ```
>     public class SiteBanner
>     {
>         [Required]
>         public string Login { get; set; }
>         [Required]
>         public string Announcement { get; set; }
> 
>         public SiteBanner()
>         {
>             Login = "";
>             Announcement = "";
>         }
> 
>         public override bool Equals(object? obj)
>         {
>             if (obj is not SiteBanner other || GetType() != obj.GetType())
>             {
>                 return false;
>             }
> 
>             return Login.Equals(other.Login) && Announcement.Equals(other.Announcement);
>         }
> 
>         public override int GetHashCode()
>         {
>             return HashCode.Combine(Login, Announcement);
>         }
>     }
> ```

I think this API should be improved.  The current implementation is hard to extend.  The `BannerCollection` is not a collection at all but a single document.  It would be better to have a single banner per document, such as:
```
{
  "_id" : "12345...",
  "name" :  "login",
  "value" :  "",
}
```
Then each banner message can be found by using the `name` as the key and it is easy to add banners without changing the API/structure of the database document.  This means no requirement to update the database when a new message type is added.
</blockquote></details>

Done.

**Review by jmgrady — CHANGES_REQUESTED** [review]
> Reviewed 5 of 16 files at r8, 7 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1319)* status: 41 of 49 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @johnthagen)

___
*[src/api/api/banner-api.ts, line 77 at r9](https://reviewable.io/reviews/sillsdev/thecombine/1319#-MkItH6FEQ7ktpHjP0UH:-MkItH6FEQ7ktpHjP0UI:bacmb0n) ([raw file](https://github.com/sillsdev/thecombine/blob/6f536ff15828e1fb9b5d5814422ef35f76a07cec/src/api/api/banner-api.ts#L77)):*
> ```
> type !== undefined
> ```
Should it also check for `BannerType.None`?

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1319)* status: 40 of 49 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec, @jmgrady, and @johnthagen)

___
*[src/api/api/banner-api.ts, line 77 at r9](https://reviewable.io/reviews/sillsdev/thecombine/1319#-MkItH6FEQ7ktpHjP0UH:-MkJ3dQAAtsG0bSdqbBK:b-fbjqfh) ([raw file](https://github.com/sillsdev/thecombine/blob/6f536ff15828e1fb9b5d5814422ef35f76a07cec/src/api/api/banner-api.ts#L77)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

> ```
> type !== undefined
> ```
Should it also check for `BannerType.None`?
</blockquote></details>

Everything in `/api/` is auto-generated from the backend. If we want a check against `BannerType.None`, we'd need to add that in the backend, but I'm not sure we need it.

**Review by jmgrady — COMMENTED** [review]
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1319)* status: 41 of 49 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec, @jmgrady, and @johnthagen)

**Comment by johnthagen** [comment]
___
*[-- commits, line 102 at r10](https://reviewable.io/reviews/sillsdev/thecombine/1319#-MkMtldL5mjEOyOYhOyF):*
@imnasnainaec I'd originally imagined that the Login banner would be a less-warning looking banner, designed for long term use and provide information about a specific server instance (such as who manages support /etc.).

As such, do you think it would look nicer if we had a blue background instead of orange for the login banner?



The Login banner purpose is inspired by GitLab's custom help and sign-in messages: https://docs.gitlab.com/ee/user/admin_area/settings/help_page.html

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1319)* status: 41 of 51 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @johnthagen)

___
*[-- commits, line 102 at r10](https://reviewable.io/reviews/sillsdev/thecombine/1319#-MkMtldL5mjEOyOYhOyF):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

@imnasnainaec I'd originally imagined that the Login banner would be a less-warning looking banner, designed for long term use and provide information about a specific server instance (such as who manages support /etc.).

As such, do you think it would look nicer if we had a blue background instead of orange for the login banner?



The Login banner purpose is inspired by GitLab's custom help and sign-in messages: https://docs.gitlab.com/ee/user/admin_area/settings/help_page.html
</blockquote></details>

I agree.  I noticed that the `src/types/theme.ts` defines `warn` as orange.  Perhaps we can define a color for `info`.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1319)* status: 41 of 51 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @johnthagen)

___
*[-- commits, line 102 at r10](https://reviewable.io/reviews/sillsdev/thecombine/1319#-MkMtldL5mjEOyOYhOyF):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

I agree.  I noticed that the `src/types/theme.ts` defines `warn` as orange.  Perhaps we can define a color for `info`.
</blockquote></details>

@johnthagen Ah, that makes sense. How about white bg with a border like you originally had?

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1319)* status: 41 of 51 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @johnthagen)

___
*[-- commits, line 102 at r10](https://reviewable.io/reviews/sillsdev/thecombine/1319#-MkMtldL5mjEOyOYhOyF):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

@johnthagen Ah, that makes sense. How about white bg with a border like you originally had?
</blockquote></details>

How about white with no border?  A border will add an unnecessary visual element. With a box-in-a-box it creates a hall of mirrors effect.

**Comment by johnthagen** [comment]
___
*[-- commits, line 102 at r10](https://reviewable.io/reviews/sillsdev/thecombine/1319#-MkMtldL5mjEOyOYhOyF):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

How about white with no border?  A border will add an unnecessary visual element. With a box-in-a-box it creates a hall of mirrors effect.
</blockquote></details>

Done.

This looks nice without any color or border.

**Comment by johnthagen** [comment]
___
*[src/backend/localStorage.ts, line 25 at r15](https://reviewable.io/reviews/sillsdev/thecombine/1319#-MkNAvNw6CJVwZPrw-no:-MkNAvNw6CJVwZPrw-np:b-xa41s3) ([raw file](https://github.com/sillsdev/thecombine/blob/fc1b9564e861119eb64a43f062b2bc472b0b360b/src/backend/localStorage.ts#L25)):*
> ```XML
> }
> 
> export function getClosedBanner(): string {
> ```

Should `localStorage.test.tsx` be updated at all for these changes?

**Comment by johnthagen** [comment]
___
*[src/backend/localStorage.ts, line 28 at r15](https://reviewable.io/reviews/sillsdev/thecombine/1319#-MkNBFJx7MjE4YXuvpjs:-MkNBFJx7MjE4YXuvpjt:bhrnllp) ([raw file](https://github.com/sillsdev/thecombine/blob/fc1b9564e861119eb64a43f062b2bc472b0b360b/src/backend/localStorage.ts#L28)):*
> ```XML
>   return localStorage.getItem(LocalStorageKey.ClosedBanner) || "";
> }
> export function setClosedBanner(src?: string) {
> ```

The only usage I see of `setClosedBanner` uses a non-nullable string as input. Should we simply make this function require a non-nullable string to tighten its API?

**Comment by johnthagen** [comment]
___
*[src/components/AnnouncementBanner/AnnouncementBanner.tsx, line 16 at r15](https://reviewable.io/reviews/sillsdev/thecombine/1319#-MkNBUkd0b2Nnybl5wOP:-MkNBUkd0b2Nnybl5wOQ:b6p8eu8) ([raw file](https://github.com/sillsdev/thecombine/blob/fc1b9564e861119eb64a43f062b2bc472b0b360b/src/components/AnnouncementBanner/AnnouncementBanner.tsx#L16)):*
> ```XML
>   const [banner, setBanner] = useState<string>("");
> 
>   // Adust the margins depending on whether there is an AppBar.
> ```

Typo: `adjust`

**Comment by johnthagen** [comment]
___
*[src/components/AnnouncementBanner/AnnouncementBanner.tsx, line 29 at r15](https://reviewable.io/reviews/sillsdev/thecombine/1319#-MkNCJoVBbxwP5G_oVhn:-MkNBrNjEA0el3oy4QzC:bgbtyuc) ([raw file](https://github.com/sillsdev/thecombine/blob/fc1b9564e861119eb64a43f062b2bc472b0b360b/src/components/AnnouncementBanner/AnnouncementBanner.tsx#L29)):*
> ```XML
>         setBanner(text);
>       }
>     }); // eslint-disable-next-line react-hooks/exhaustive-deps
> ```

Why is this suppression needed? There seems to be some discussion back and forth about if this is generally a code smell or not.

https://github.com/facebook/create-react-app/issues/6880

Perhaps we should at least add a note about why this needed to be suppressed?

**Comment by johnthagen** [comment]
___
*[src/components/AppBar/AppBarComponent.tsx, line 32 at r15](https://reviewable.io/reviews/sillsdev/thecombine/1319#-MkNCwTr3VdSbmw45h9f:-MkNCwTr3VdSbmw45h9g:b-1v2ns1) ([raw file](https://github.com/sillsdev/thecombine/blob/fc1b9564e861119eb64a43f062b2bc472b0b360b/src/components/AppBar/AppBarComponent.tsx#L32)):*
> ```XML
>             <Grid item xs={7} md={5} lg={4}>
>               <Logo />
>               {!!getProjectId() && (
> ```

I personally think this change reduces readability. I had to read a blog post about what JS devs used `!!` for. I personally think implicit bool conversions make code harder to read. In the previous version it was clear that the result of `getProjectId()` is a `string` and we are checking if it's empty. With `!!` I have to go through mental checks in my head of what kind of type it is, what the implicit `boolean` rules are in JS, and see that it's double negation.

This is just my personal opinion.

**Comment by johnthagen** [comment]
___
*[src/components/Login/RegisterPage/RegisterComponent.tsx, line 287 at r15](https://reviewable.io/reviews/sillsdev/thecombine/1319#-MkNDUfBED18UxP6Mt6C:-MkNDUfBED18UxP6Mt6D:b5ev56s) ([raw file](https://github.com/sillsdev/thecombine/blob/fc1b9564e861119eb64a43f062b2bc472b0b360b/src/components/Login/RegisterPage/RegisterComponent.tsx#L287)):*
> ```XML
> 
>               {/* "Failed to register" */}
>               {!!this.props.failureMessage && (
> ```

Similar to previous comment. We should probably discuss what our preferred style is relative to implicit `boolean` checks are.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1319)* status: 38 of 57 files reviewed, 4 unresolved discussions (waiting on @imnasnainaec, @jmgrady, and @johnthagen)

___
*[src/backend/localStorage.ts, line 25 at r15](https://reviewable.io/reviews/sillsdev/thecombine/1319#-MkNAvNw6CJVwZPrw-no:-MkNTY0_AoM43aXIeFy8:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/fc1b9564e861119eb64a43f062b2bc472b0b360b/src/backend/localStorage.ts#L25)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Should `localStorage.test.tsx` be updated at all for these changes?
</blockquote></details>

Done.
___
*[src/backend/localStorage.ts, line 28 at r15](https://reviewable.io/reviews/sillsdev/thecombine/1319#-MkNBFJx7MjE4YXuvpjs:-MkNTYiZ4gwI0N3WP7_8:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/fc1b9564e861119eb64a43f062b2bc472b0b360b/src/backend/localStorage.ts#L28)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

The only usage I see of `setClosedBanner` uses a non-nullable string as input. Should we simply make this function require a non-nullable string to tighten its API?
</blockquote></details>

Done.
___
*[src/components/AnnouncementBanner/AnnouncementBanner.tsx, line 16 at r15](https://reviewable.io/reviews/sillsdev/thecombine/1319#-MkNBUkd0b2Nnybl5wOP:-MkNTZydDQrU8lKwKR-s:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/fc1b9564e861119eb64a43f062b2bc472b0b360b/src/components/AnnouncementBanner/AnnouncementBanner.tsx#L16)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Typo: `adjust`
</blockquote></details>

Done.
___
*[src/components/AnnouncementBanner/AnnouncementBanner.tsx, line 29 at r15](https://reviewable.io/reviews/sillsdev/thecombine/1319#-MkNCJoVBbxwP5G_oVhn:-MkNTMxbC--ZXVMWR9fc:b-4pvfa6) ([raw file](https://github.com/sillsdev/thecombine/blob/fc1b9564e861119eb64a43f062b2bc472b0b360b/src/components/AnnouncementBanner/AnnouncementBanner.tsx#L29)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Why is this suppression needed? There seems to be some discussion back and forth about if this is generally a code smell or not.

https://github.com/facebook/create-react-app/issues/6880

Perhaps we should at least add a note about why this needed to be suppressed?
</blockquote></details>

Good to re-evaluate. I'll make a new issue.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1319)* status: 38 of 57 files reviewed, all discussions resolved (waiting on @imnasnainaec, @jmgrady, and @johnthagen)

**Review by johnthagen — COMMENTED** [review]
> Reviewed 18 of 38 files at r1, 1 of 1 files at r2, 8 of 8 files at r4, 1 of 4 files at r5, 1 of 3 files at r7, 12 of 16 files at r8, 3 of 7 files at r9, 1 of 1 files at r10, 1 of 2 files at r12, 1 of 1 files at r14, 6 of 6 files at r15, 3 of 3 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1319)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Review by jmgrady — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1319)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Review by johnthagen — COMMENTED** [review]
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1319)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Pull request merged**
