### PR TITLE
[DataEntry] Overhaul vernacular, duplicates

### PR DESCRIPTION
**Pull request by imnasnainaec**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/585)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[package.json, line 26 at r1](https://reviewable.io/reviews/sillsdev/thecombine/585#-MEhlQWt4jZ6zHYlPiZY:-MEhlQWuDJFlPkCGk3JI:b-hb4wam) ([raw file](https://github.com/sillsdev/thecombine/blob/55ed3d6efde06336f1cc815c6b4f74f2eafdf26c/package.json#L26)):*
> ```JSON
>     "set-admin-user": "tsc setAdminUser.ts && node setAdminUser.js",
>     "start": "npm install && npm-run-all --parallel frontend database api",
>     "test": "dotnet test Backend.Tests/Backend.Tests.csproj && react-scripts test",
> ```

Was this an accidental check in, or did you mean to pull backend unit tests out of `npm test`?

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryComponent.tsx, line 87 at r1](https://reviewable.io/reviews/sillsdev/thecombine/585#-MEhlldk2oMbj41dsUQM:-MEhlldk2oMbj41dsUQN:b-yz97in) ([raw file](https://github.com/sillsdev/thecombine/blob/672d79b53b9c346ecaca21b8e5fe117350224743/src/components/DataEntry/DataEntryComponent.tsx#L87)):*
> ```XML
> ): DomainWord[] {
>   let domainWords: DomainWord[] = filterWordsByDomain(existingWords, domain);
>   console.log(domainWords);
> ```

Did you mean to check in this `console.log` command?

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/DataEntryTable.tsx, line 85 at r1](https://reviewable.io/reviews/sillsdev/thecombine/585#-MEhmOVJ00o35pTnfqMx:-MEhmOVJ00o35pTnfqMy:b-wcls7r) ([raw file](https://github.com/sillsdev/thecombine/blob/672d79b53b9c346ecaca21b8e5fe117350224743/src/components/DataEntry/DataEntryTable/DataEntryTable.tsx#L85)):*
> ```XML
> 
>   async componentDidMount() {
>     this.updateExisting();
> ```

This statement may be missing an `await`.

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/DataEntryTable.tsx, line 98 at r1](https://reviewable.io/reviews/sillsdev/thecombine/585#-MEhmWvg2C--WDaNWVWQ:-MEhmWvg2C--WDaNWVWR:bxcys7w) ([raw file](https://github.com/sillsdev/thecombine/blob/672d79b53b9c346ecaca21b8e5fe117350224743/src/components/DataEntry/DataEntryTable/DataEntryTable.tsx#L98)):*
> ```XML
>     let wordId: string = await addAudiosToBackend(newWord.id, audioURLs);
>     let newWordWithAudio: Word = await Backend.getWord(wordId);
>     this.updateExisting();
> ```

Similar to before, I think this statement should have an `await`.

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/DataEntryTable.tsx, line 197 at r1](https://reviewable.io/reviews/sillsdev/thecombine/585#-MEhmx6R73FKSAUrhg7S:-MEhmx6R73FKSAUrhg7T:b4h1jaq) ([raw file](https://github.com/sillsdev/thecombine/blob/672d79b53b9c346ecaca21b8e5fe117350224743/src/components/DataEntry/DataEntryTable/DataEntryTable.tsx#L197)):*
> ```XML
>   async updateWordInBackend(wordToUpdate: Word): Promise<Word> {
>     let updatedWord: Word = await Backend.updateWord(wordToUpdate);
>     this.updateExisting();
> ```

I believe this should have an `await`.

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/DataEntryTable.tsx, line 233 at r1](https://reviewable.io/reviews/sillsdev/thecombine/585#-MEhnLTKB5INfDYNaTNJ:-MEhnLTKB5INfDYNaTNK:bpvjmg6) ([raw file](https://github.com/sillsdev/thecombine/blob/672d79b53b9c346ecaca21b8e5fe117350224743/src/components/DataEntry/DataEntryTable/DataEntryTable.tsx#L233)):*
> ```XML
>         semanticDomains: updatedSemanticDomains,
>       };
>       this.updateSense(recentWord, senseIndex, updatedSense);
> ```

Add `await`

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/DataEntryTable.tsx, line 236 at r1](https://reviewable.io/reviews/sillsdev/thecombine/585#-MEhnQ-853E40GsEENOz:-MEhnQ-853E40GsEENP-:bpvjmg6) ([raw file](https://github.com/sillsdev/thecombine/blob/672d79b53b9c346ecaca21b8e5fe117350224743/src/components/DataEntry/DataEntryTable/DataEntryTable.tsx#L236)):*
> ```XML
>     } else if (senseCount > 1) {
>       // If there is more than one sense in this word, only remove this sense.
>       this.removeSense(recentWord, senseIndex);
> ```

Add `await`

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/DataEntryTable.tsx, line 296 at r1](https://reviewable.io/reviews/sillsdev/thecombine/585#-MEhoWGr7urKRvf8muB6:-MEhoWGr7urKRvf8muB7:b6725ze) ([raw file](https://github.com/sillsdev/thecombine/blob/672d79b53b9c346ecaca21b8e5fe117350224743/src/components/DataEntry/DataEntryTable/DataEntryTable.tsx#L296)):*
> ```XML
>   }
> 
>   deleteWord(word: Word) {
> ```

Could this function become `async`?

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/DataEntryTable.tsx, line 97 at r1](https://reviewable.io/reviews/sillsdev/thecombine/585#-MEhpoFEAmug5VxOcGeO:-MEhpoFEAmug5VxOcGeP:b-b17fc5) ([raw file](https://github.com/sillsdev/thecombine/blob/672d79b53b9c346ecaca21b8e5fe117350224743/src/components/DataEntry/DataEntryTable/DataEntryTable.tsx#L97)):*
> ```XML
>     let newWord: Word = await Backend.createWord(wordToAdd);
>     let wordId: string = await addAudiosToBackend(newWord.id, audioURLs);
>     let newWordWithAudio: Word = await Backend.getWord(wordId);
> ```

Could all of these variables be declared as `const`?

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/DataEntryTable.tsx, line 180 at r1](https://reviewable.io/reviews/sillsdev/thecombine/585#-MEhq43nEooLLJxKf2VR:-MEhq43nEooLLJxKf2VS:b-esok1j) ([raw file](https://github.com/sillsdev/thecombine/blob/672d79b53b9c346ecaca21b8e5fe117350224743/src/components/DataEntry/DataEntryTable/DataEntryTable.tsx#L180)):*
> ```XML
>       ? senseIndex
>       : updatedWord.senses.length - 1;
>     let updatedWordAccess: WordAccess = {
> ```

Could this be declared `const`?

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/NewEntry/NewEntry.tsx, line 114 at r1](https://reviewable.io/reviews/sillsdev/thecombine/585#-MEhrMKt5-4CN9CfcMpM:-MEhrMKt5-4CN9CfcMpN:bsfor8x) ([raw file](https://github.com/sillsdev/thecombine/blob/672d79b53b9c346ecaca21b8e5fe117350224743/src/components/DataEntry/DataEntryTable/NewEntry/NewEntry.tsx#L114)):*
> ```XML
>     this.props.updateWord(
>       updatedWord,
>       updatedWord.senses.length - 1,
> ```

Might be worth a comment about why a `- 1` is needed here?

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/NewEntry/NewEntry.tsx, line 147 at r1](https://reviewable.io/reviews/sillsdev/thecombine/585#-MEhrTf8CWSXpipCdJ8T:-MEhrTf8CWSXpipCdJ8U:bvrikx2) ([raw file](https://github.com/sillsdev/thecombine/blob/672d79b53b9c346ecaca21b8e5fe117350224743/src/components/DataEntry/DataEntryTable/NewEntry/NewEntry.tsx#L147)):*
> ```XML
>   updateVernField(newValue: string): Word[] {
>     var dupVernWords: Word[] = [];
>     var isDupVern: boolean = false;
> ```

Can these two variables be declared with `let` instead of `var` to limit their scope?

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/RecentEntry/RecentEntry.tsx, line 59 at r1](https://reviewable.io/reviews/sillsdev/thecombine/585#-MEhsz_Z-gLFi8YTvyH4:-MEhsz_Z-gLFi8YTvyH5:bb0sshp) ([raw file](https://github.com/sillsdev/thecombine/blob/672d79b53b9c346ecaca21b8e5fe117350224743/src/components/DataEntry/DataEntryTable/RecentEntry/RecentEntry.tsx#L59)):*
> ```XML
>   let updatedWord: Word = { ...existingWord };
> 
>   let newGloss: Gloss = {
> ```

Declare `const`?

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/RecentEntry/RecentEntry.tsx, line 64 at r1](https://reviewable.io/reviews/sillsdev/thecombine/585#-MEht0ewB5hCxN7QJ4ye:-MEht0ex55cYxIQHpawW:bb0sshp) ([raw file](https://github.com/sillsdev/thecombine/blob/672d79b53b9c346ecaca21b8e5fe117350224743/src/components/DataEntry/DataEntryTable/RecentEntry/RecentEntry.tsx#L64)):*
> ```XML
>   };
> 
>   let newSense: Sense = {
> ```

Declare `const`?

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/RecentEntry/RecentEntry.tsx, line 80 at r1](https://reviewable.io/reviews/sillsdev/thecombine/585#-MEht7vf2MO6OUBQmgxL:-MEht7vg15dhIUSaBcVO:bc1d06z) ([raw file](https://github.com/sillsdev/thecombine/blob/672d79b53b9c346ecaca21b8e5fe117350224743/src/components/DataEntry/DataEntryTable/RecentEntry/RecentEntry.tsx#L80)):*
> ```XML
> ): Word {
>   if (senseIndex >= existingWord.senses.length) {
>     throw new Error("senseIndex too large");
> ```

I'm not what (if any) policy we have on error handling, but we could potentially try to throw a more specific exception (`ValueOutOfRangeError`, or something else we create).

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/RecentEntry/RecentEntry.tsx, line 126 at r1](https://reviewable.io/reviews/sillsdev/thecombine/585#-MEhtfZnAWHt0kEMHtiH:-MEhtfZnAWHt0kEMHtiI:bfak3j8) ([raw file](https://github.com/sillsdev/thecombine/blob/672d79b53b9c346ecaca21b8e5fe117350224743/src/components/DataEntry/DataEntryTable/RecentEntry/RecentEntry.tsx#L126)):*
> ```XML
>     var vernacular: string = "";
>     var dupVernWords: Word[] = [];
>     var isDupVern: boolean = false;
> ```

Can these fields be declared with `let` to limit their scope?

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/RecentEntry/RecentEntry.tsx, line 147 at r1](https://reviewable.io/reviews/sillsdev/thecombine/585#-MEhtmi9CcC5lWhNWq5N:-MEhtmi9CcC5lWhNWq5O:b1apjk9) ([raw file](https://github.com/sillsdev/thecombine/blob/672d79b53b9c346ecaca21b8e5fe117350224743/src/components/DataEntry/DataEntryTable/RecentEntry/RecentEntry.tsx#L147)):*
> ```XML
>   conditionallyUpdateWord() {
>     if (this.isSenseUpdated()) {
>       //this.props.updateWord(this.props.entry, this.state.sense);
> ```

Dead code that can potentially be removed.

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/RecentEntry/RecentEntry.tsx, line 166 at r1](https://reviewable.io/reviews/sillsdev/thecombine/585#-MEhu5uK47nrSUfO2AEG:-MEhu5uK47nrSUfO2AEH:bc63uqt) ([raw file](https://github.com/sillsdev/thecombine/blob/672d79b53b9c346ecaca21b8e5fe117350224743/src/components/DataEntry/DataEntryTable/RecentEntry/RecentEntry.tsx#L166)):*
> ```XML
>       return true;
>     if (this.state.wordId) return true;
>     return false;
> ```

I believe these two lines could be simplified to return a `boolean` directly

```
return !!this.state.wordId;
```

There may be debate over if that is clearer though (`!!` usage).

**Comment by charjhall** [comment]
___
*[package.json, line 26 at r1](https://reviewable.io/reviews/sillsdev/thecombine/585#-MEhlQWt4jZ6zHYlPiZY:-MEij0f72o_8ffSFXcey:b-896fjx) ([raw file](https://github.com/sillsdev/thecombine/blob/55ed3d6efde06336f1cc815c6b4f74f2eafdf26c/package.json#L26)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Was this an accidental check in, or did you mean to pull backend unit tests out of `npm test`?
</blockquote></details>

Done

**Comment by charjhall** [comment]
___
*[src/components/DataEntry/DataEntryTable/DataEntryTable.tsx, line 97 at r1](https://reviewable.io/reviews/sillsdev/thecombine/585#-MEhpoFEAmug5VxOcGeO:-MEj-Z4n2h_YVEmYybp4:bvkmiev) ([raw file](https://github.com/sillsdev/thecombine/blob/672d79b53b9c346ecaca21b8e5fe117350224743/src/components/DataEntry/DataEntryTable/DataEntryTable.tsx#L97)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Will look into that later.
</blockquote></details>

Resloved

**Comment by imnasnainaec** [comment]
Unfinished things for future prs: https://docs.google.com/document/d/1vO2zbWEvNoQfq_uL6US9mAYktjmkTskJoo1El3_BiEc

**Comment by johnthagen** [comment]
⚠️  @imnasnainaec @charjhall @jmgrady I approved the changes to make sure none of my comments were blocking, but someone else (@jasonleenaylor ?) should still review this overall before merging.

**Comment by johnthagen** [comment]
@imnasnainaec 
> Unfinished things for future prs: https://docs.google.com/document/d/1vO2zbWEvNoQfq_uL6US9mAYktjmkTskJoo1El3_BiEc

Perhaps this should be put into a GitHub issue(s)?

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/RecentEntry/RecentEntry.tsx, line 31 at r17](https://reviewable.io/reviews/sillsdev/thecombine/585#-MEmGvKVEgzG_NXS7HWv:-MEmGvKVEgzG_NXS7HWw:bsbqzq0) ([raw file](https://github.com/sillsdev/thecombine/blob/b34fb21e5f5adb5a760ff028539241be961c4300/src/components/DataEntry/DataEntryTable/RecentEntry/RecentEntry.tsx#L31)):*
> ```XML
>   gloss: string;
>   //isDupVern: boolean;
>   //wordId?: string;
> ```

Can this dead code be removed?

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/RecentEntry/RecentEntry.tsx, line 51 at r17](https://reviewable.io/reviews/sillsdev/thecombine/585#-MEmHBM-CYKk6zm1teh6:-MEmHBM-CYKk6zm1teh7:bsbqzq0) ([raw file](https://github.com/sillsdev/thecombine/blob/b34fb21e5f5adb5a760ff028539241be961c4300/src/components/DataEntry/DataEntryTable/RecentEntry/RecentEntry.tsx#L51)):*
> ```XML
>       vernacular: props.entry.vernacular,
>       gloss: sense.glosses.length > 0 ? sense.glosses[0].def : "",
>       //isDupVern: false,
> ```

Can this dead code be removed?

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/RecentEntry/RecentEntry.tsx, line 63 at r17](https://reviewable.io/reviews/sillsdev/thecombine/585#-MEmHHwQ-Sx20m4eTgeR:-MEmHHwQ-Sx20m4eTgeS:b-sioqwj) ([raw file](https://github.com/sillsdev/thecombine/blob/b34fb21e5f5adb5a760ff028539241be961c4300/src/components/DataEntry/DataEntryTable/RecentEntry/RecentEntry.tsx#L63)):*
> ```XML
>     let vernacular: string = "";
>     let dupVernWords: Word[] = [];
>     //let isDupVern: boolean = false;
> ```

Remove dead code?

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/RecentEntry/RecentEntry.tsx, line 69 at r17](https://reviewable.io/reviews/sillsdev/thecombine/585#-MEmHKa6--JrT0GaY00u:-MEmHKa6--JrT0GaY00v:b-sioqwj) ([raw file](https://github.com/sillsdev/thecombine/blob/b34fb21e5f5adb5a760ff028539241be961c4300/src/components/DataEntry/DataEntryTable/RecentEntry/RecentEntry.tsx#L69)):*
> ```XML
>         (word: Word) => word.vernacular === newValue
>       );
>       isDupVern = dupVernWords.length > 0;*/
> ```

Remove dead code?

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/RecentEntry/RecentEntry.tsx, line 80 at r17](https://reviewable.io/reviews/sillsdev/thecombine/585#-MEmHNp45i00ts2iszEE:-MEmHNp45i00ts2iszEF:b-sioqwj) ([raw file](https://github.com/sillsdev/thecombine/blob/b34fb21e5f5adb5a760ff028539241be961c4300/src/components/DataEntry/DataEntryTable/RecentEntry/RecentEntry.tsx#L80)):*
> ```XML
>   /*updateWordId(wordId?: string) {
>     this.setState({ wordId });
>   }*/
> ```

Remove dead code?

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/RecentEntry/RecentEntry.tsx, line 100 at r17](https://reviewable.io/reviews/sillsdev/thecombine/585#-MEmHSk_DvaDYB7yrddC:-MEmHSk_DvaDYB7yrddD:b-wrdi25) ([raw file](https://github.com/sillsdev/thecombine/blob/b34fb21e5f5adb5a760ff028539241be961c4300/src/components/DataEntry/DataEntryTable/RecentEntry/RecentEntry.tsx#L100)):*
> ```XML
>   focusOnNewEntry = () => {
>     this.props.focusNewEntry();
>     //reference NewEntry's focus thing here
> ```

Is this comment obsolete (see previous line)?

**Pull request merged**
