### PR TITLE
Refactor Redux Code for components that use history

### PR DESCRIPTION
**Pull request by jasonleenaylor**
* Move Redux Actions and Reducer files into Redux
  folder in components
* Split Redux related types into a separate file
* Use store in browserHistory.ts and move currentPage
  into redux

Related to #664

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1117)

### CODE REVIEW

**Comment by johnthagen** [comment]
Comparing `npm run test-frontend` from `master` to this PR, the following `No reduced provided` console errors are **new** in this branch:

```
 PASS  src/components/ProjectSettings/ProjectLanguages/tests/ProjectLangauges.test.tsx (10.794 s)
  ● Console

    console.error
      No reducer provided for key "exportProjectState"

      16 | import { StoreState } from "types";
      17 |
    > 18 | export const rootReducer: Reducer<StoreState> = combineReducers<StoreState>({
         |                                                 ^
      19 |   //analytics state
      20 |   analyticsState: analyticsReducer,
      21 |

      at warning (node_modules/redux/lib/redux.js:325:13)
      at combineReducers (node_modules/redux/lib/redux.js:415:9)
      at Object.<anonymous> (src/rootReducer.tsx:18:49)
      at Object.<anonymous> (src/store.tsx:7:1)
...
 PASS  src/components/Pronunciations/tests/Pronunciations.test.tsx (10.924 s)
  ● Console

    console.error
      No reducer provided for key "exportProjectState"

      16 | import { StoreState } from "types";
      17 |
    > 18 | export const rootReducer: Reducer<StoreState> = combineReducers<StoreState>({
         |                                                 ^
      19 |   //analytics state
      20 |   analyticsState: analyticsReducer,
      21 |

      at warning (node_modules/redux/lib/redux.js:325:13)
      at combineReducers (node_modules/redux/lib/redux.js:415:9)
      at Object.<anonymous> (src/rootReducer.tsx:18:49)
      at Object.<anonymous> (src/store.tsx:7:1)
...
 PASS  src/components/DataEntry/DataEntryTable/NewEntry/tests/NewEntry.test.tsx
  ● Console

    console.error
      No reducer provided for key "exportProjectState"

      16 | import { StoreState } from "types";
      17 |
    > 18 | export const rootReducer: Reducer<StoreState> = combineReducers<StoreState>({
         |                                                 ^
      19 |   //analytics state
      20 |   analyticsState: analyticsReducer,
      21 |

      at warning (node_modules/redux/lib/redux.js:325:13)
      at combineReducers (node_modules/redux/lib/redux.js:415:9)
      at Object.<anonymous> (src/rootReducer.tsx:18:49)
      at Object.<anonymous> (src/store.tsx:7:1)
...
 PASS  src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/tests/DomainCell.test.tsx
  ● Console

    console.error
      No reducer provided for key "exportProjectState"

      16 | import { StoreState } from "types";
      17 |
    > 18 | export const rootReducer: Reducer<StoreState> = combineReducers<StoreState>({
         |                                                 ^
      19 |   //analytics state
      20 |   analyticsState: analyticsReducer,
      21 |

      at warning (node_modules/redux/lib/redux.js:325:13)
      at combineReducers (node_modules/redux/lib/redux.js:415:9)
      at Object.<anonymous> (src/rootReducer.tsx:18:49)
      at Object.<anonymous> (src/store.tsx:7:1)
...
 PASS  src/components/UserSettings/tests/AvatarUpload.test.tsx
  ● Console

    console.error
      No reducer provided for key "exportProjectState"

      16 | import { StoreState } from "types";
      17 |
    > 18 | export const rootReducer: Reducer<StoreState> = combineReducers<StoreState>({
         |                                                 ^
      19 |   //analytics state
      20 |   analyticsState: analyticsReducer,
      21 |

      at warning (node_modules/redux/lib/redux.js:325:13)
      at combineReducers (node_modules/redux/lib/redux.js:415:9)
      at Object.<anonymous> (src/rootReducer.tsx:18:49)
      at Object.<anonymous> (src/store.tsx:7:1)
...
 PASS  src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/tests/DeleteCell.test.tsx
  ● Console

    console.error
      No reducer provided for key "exportProjectState"

      16 | import { StoreState } from "types";
      17 |
    > 18 | export const rootReducer: Reducer<StoreState> = combineReducers<StoreState>({
         |                                                 ^
      19 |   //analytics state
      20 |   analyticsState: analyticsReducer,
      21 |

      at warning (node_modules/redux/lib/redux.js:325:13)
      at combineReducers (node_modules/redux/lib/redux.js:415:9)
      at Object.<anonymous> (src/rootReducer.tsx:18:49)
      at Object.<anonymous> (src/store.tsx:7:1)
...
 PASS  src/components/DataEntry/ExistingDataTable/tests/ExistingDataTable.test.tsx
  ● Console

    console.error
      No reducer provided for key "exportProjectState"

      16 | import { StoreState } from "types";
      17 |
    > 18 | export const rootReducer: Reducer<StoreState> = combineReducers<StoreState>({
         |                                                 ^
      19 |   //analytics state
      20 |   analyticsState: analyticsReducer,
      21 |

      at warning (node_modules/redux/lib/redux.js:325:13)
      at combineReducers (node_modules/redux/lib/redux.js:415:9)
      at Object.<anonymous> (src/rootReducer.tsx:18:49)
      at Object.<anonymous> (src/store.tsx:7:1)
...
 PASS  src/components/PasswordReset/tests/ResetPage.test.tsx
  ● Console

    console.error
      No reducer provided for key "exportProjectState"

      16 | import { StoreState } from "types";
      17 |
    > 18 | export const rootReducer: Reducer<StoreState> = combineReducers<StoreState>({
         |                                                 ^
      19 |   //analytics state
      20 |   analyticsState: analyticsReducer,
      21 |

      at warning (node_modules/redux/lib/redux.js:325:13)
      at combineReducers (node_modules/redux/lib/redux.js:415:9)
      at Object.<anonymous> (src/rootReducer.tsx:18:49)
      at Object.<anonymous> (src/store.tsx:7:1)
...
 PASS  src/components/Project/tests/ProjectReducer.test.tsx
  ● Console

    console.error
      No reducer provided for key "currentProject"

      16 | import { StoreState } from "types";
      17 |
    > 18 | export const rootReducer: Reducer<StoreState> = combineReducers<StoreState>({
         |                                                 ^
      19 |   //analytics state
      20 |   analyticsState: analyticsReducer,
      21 |

      at warning (node_modules/redux/lib/redux.js:325:13)
      at combineReducers (node_modules/redux/lib/redux.js:415:9)
      at Object.<anonymous> (src/rootReducer.tsx:18:49)
      at Object.<anonymous> (src/store.tsx:7:1)
```

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 9 of 74 files at r1, 18 of 71 files at r2, 68 of 83 files at r4, 31 of 33 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1117)* status: 104 of 112 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1117)* status: 107 of 112 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 71 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1117)* status: 107 of 112 files reviewed, all discussions resolved (waiting on @imnasnainaec and @jasonleenaylor)

___
*[src/goals/MergeDupGoal/MergeDupStep/DragDropComponents/DragSense.tsx, line 83 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1117#-MZPI7DxDGt1uZUk4RJY:-MZPI7DxDGt1uZUk4RJZ:b3mamfp) ([raw file](https://github.com/sillsdev/thecombine/blob/32f7e093066790581a0497d558f7a0b799e7d817/src/goals/MergeDupGoal/MergeDupStep/DragDropComponents/DragSense.tsx#L83)):*
> ```XML
>     isInSidebar &&
>     !arraysEqual(
>       sidebar.senses.map((s: { guid: any }) => s.guid),
> ```

(Why) Is `: { guid: any }` necessary here?

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1117)* status: 109 of 112 files reviewed, all discussions resolved (waiting on @imnasnainaec and @jasonleenaylor)

**Review by jasonleenaylor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1117)* status: 109 of 112 files reviewed, all discussions resolved (waiting on @imnasnainaec and @jasonleenaylor)

___
*[src/goals/MergeDupGoal/MergeDupStep/DragDropComponents/DragSense.tsx, line 83 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1117#-MZPI7DxDGt1uZUk4RJY:-MZPOwus4xkE93GOTMkF:b-pwna6q) ([raw file](https://github.com/sillsdev/thecombine/blob/32f7e093066790581a0497d558f7a0b799e7d817/src/goals/MergeDupGoal/MergeDupStep/DragDropComponents/DragSense.tsx#L83)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

(Why) Is `: { guid: any }` necessary here?
</blockquote></details>

Since it wasn't required on the line below I suspect I was dealing with some VS Code prompted nonsense and adjusted it unnecessarily. We should compare notes on development environments at some point. I get a good deal of noise out of VS Code that vanishes once I load the files it complains about into the editor.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 2 files at r7, 1 of 1 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1117)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jasonleenaylor)

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 33 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1117)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jasonleenaylor)

**Comment by johnthagen** [comment]
___
*[src/components/Login/Redux/LoginReducer.tsx, line 67 at r10](https://reviewable.io/reviews/sillsdev/thecombine/1117#-MZXwSoW-75endBWrs09:-MZXwSoW-75endBWrs0A:bbelipq) ([raw file](https://github.com/sillsdev/thecombine/blob/d8973536f63d7fea689fddda5a5949dc9845b6b2/src/components/Login/Redux/LoginReducer.tsx#L67)):*
> ```XML
>         registerSuccess: false,
>       };
>     case LoginActionTypes.LOGIN_RESET:
> ```

Since these all return the `defaultState` should we simply stack them and allow fallthrough?

I tested this locally, and ESLint will catch the case where we fallthrough unintentionally (if there are any statements in a `case` and it fallsthrough, there is a warning thrown and CI would fail), so this should be a safe simplification.

```ts
    case LoginActionTypes.LOGIN_RESET:
    case LoginActionTypes.LOGOUT:
    case StoreActionTypes.RESET:
    case LoginActionTypes.REGISTER_RESET:
      return defaultState;
```

**Comment by johnthagen** [comment]
___
*[src/goals/CharInventoryCreation/Redux/CharacterInventoryReduxTypes.ts, line 6 at r10](https://reviewable.io/reviews/sillsdev/thecombine/1117#-MZXzVd65QhiMvVeeDJY:-MZXzVd65QhiMvVeeDJZ:bcnj4q6) ([raw file](https://github.com/sillsdev/thecombine/blob/d8973536f63d7fea689fddda5a5949dc9845b6b2/src/goals/CharInventoryCreation/Redux/CharacterInventoryReduxTypes.ts#L6)):*
> ```XML
>   ADD_TO_VALID_CHARACTERS = "ADD_TO_VALID_CHARACTERS",
>   ADD_TO_REJECTED_CHARACTERS = "ADD_TO_REJECTED_CHARACTERS",
>   SET_ALL_WORDS = "CHARINV_SET_ALL_WORDS",
> ```

Why does this `enum` member have `CHARINV_` prefixed to it? Isn't that implied by the type name? Same with `RESET`.

**Comment by johnthagen** [comment]
___
*[src/goals/CharInventoryCreation/Redux/CharacterInventoryReduxTypes.ts, line 49 at r10](https://reviewable.io/reviews/sillsdev/thecombine/1117#-MZXzgKiCqfU4QWttrpP:-MZXzgKiCqfU4QWttrpQ:bpu9w4v) ([raw file](https://github.com/sillsdev/thecombine/blob/d8973536f63d7fea689fddda5a5949dc9845b6b2/src/goals/CharInventoryCreation/Redux/CharacterInventoryReduxTypes.ts#L49)):*
> ```XML
> }
> 
> /** A character with its occurrences and status, for sorting and filtering in a list */
> ```

Should ideally wrap this line at 80 characters.

**Review by johnthagen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1117)* status: all files reviewed, 4 unresolved discussions (waiting on @jasonleenaylor)

**Review by jasonleenaylor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1117)* status: all files reviewed, 2 unresolved discussions (waiting on @johnthagen)

___
*[src/goals/CharInventoryCreation/Redux/CharacterInventoryReduxTypes.ts, line 6 at r10](https://reviewable.io/reviews/sillsdev/thecombine/1117#-MZXzVd65QhiMvVeeDJY:-MZY_6qmAv39XOIQmrH6:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/d8973536f63d7fea689fddda5a5949dc9845b6b2/src/goals/CharInventoryCreation/Redux/CharacterInventoryReduxTypes.ts#L6)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Why does this `enum` member have `CHARINV_` prefixed to it? Isn't that implied by the type name? Same with `RESET`.
</blockquote></details>

Done.
___
*[src/goals/CharInventoryCreation/Redux/CharacterInventoryReduxTypes.ts, line 49 at r10](https://reviewable.io/reviews/sillsdev/thecombine/1117#-MZXzgKiCqfU4QWttrpP:-MZY_UyE96LoxNZZKpHO:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/d8973536f63d7fea689fddda5a5949dc9845b6b2/src/goals/CharInventoryCreation/Redux/CharacterInventoryReduxTypes.ts#L49)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Should ideally wrap this line at 80 characters.
</blockquote></details>

Done.
___
*[src/components/Login/Redux/LoginReducer.tsx, line 67 at r10](https://reviewable.io/reviews/sillsdev/thecombine/1117#-MZXwSoW-75endBWrs09:-MZYZP_d8TnXMpDzQI41:b772of9) ([raw file](https://github.com/sillsdev/thecombine/blob/d8973536f63d7fea689fddda5a5949dc9845b6b2/src/components/Login/Redux/LoginReducer.tsx#L67)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Since these all return the `defaultState` should we simply stack them and allow fallthrough?

I tested this locally, and ESLint will catch the case where we fallthrough unintentionally (if there are any statements in a `case` and it fallsthrough, there is a warning thrown and CI would fail), so this should be a safe simplification.

```ts
    case LoginActionTypes.LOGIN_RESET:
    case LoginActionTypes.LOGOUT:
    case StoreActionTypes.RESET:
    case LoginActionTypes.REGISTER_RESET:
      return defaultState;
```
</blockquote></details>

Seems good.

**Pull request merged**
