### PR TITLE
Keep login from failing due to avatar error.

### LINKED ISSUE #1213: Login fails with missing avatar
Logging into _The Combine_ will fail if the `hasAvatar` field for the specified is set to `true` but the file does not exist in the backend data.

The login should succeed and update the document in the UsersCollection to set `hasAvatar` to `false` and clear the `avatar` field.

@jasonleenaylor - Please advise on whether there should be a message box alerting the user to the change or if it should be silent and just display the default avatar.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Fixes #1213

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1228)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
This does thoroughly protect login, but could the crash be avoided in the `LocalStorage.setAvatar` method?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1228#-:-MdN9xdu7ig-qeNr7nVH:bg1k1qh)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1228)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JacobHaimes and @WeJamUS)

**Review by WeJamUS — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1228)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JacobHaimes)

**Review by JacobHaimes — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1228)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
