### PR TITLE
Add localization, license, contributors badges

### PR DESCRIPTION
**Pull request by imnasnainaec**
Before:
image

After:
image

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/726)

### CODE REVIEW

**Review by jmgrady — CHANGES_REQUESTED** [review]
One typo, and a couple non-blocking questions.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/726#-:-MHllYss8DVr_mPB-nl1:bpf6myz)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[README.md, line 247 at r1](https://reviewable.io/reviews/sillsdev/thecombine/726#-MHlkTFD9XIqB_Ln9Ezv:-MHlkTFD9XIqB_Ln9Ezw:buw2pn9) ([raw file](https://github.com/sillsdev/thecombine/blob/d9d59a3ea622aa8feb507d4d61e9cb9b7f2f4bcd/README.md#L247)):*
> ```
> updated
> ```
should be "update"
___
*[README.md, line 268 at r1](https://reviewable.io/reviews/sillsdev/thecombine/726#-MHlktw_CrlcStPPWDnP:-MHlktw_CrlcStPPWDnQ:b-tn8pg8) ([raw file](https://github.com/sillsdev/thecombine/blob/d9d59a3ea622aa8feb507d4d61e9cb9b7f2f4bcd/README.md#L268)):*
> ```
> _TheCombine_ 
> ```
*TheCombine* and _TheCombine_ are equivalent
___
*[README.md, line 272 at r1](https://reviewable.io/reviews/sillsdev/thecombine/726#-MHlkb6XCq0y7ZV-2Bn3:-MHlkb6XCq0y7ZV-2Bn4:b-lrwq1u) ([raw file](https://github.com/sillsdev/thecombine/blob/d9d59a3ea622aa8feb507d4d61e9cb9b7f2f4bcd/README.md#L272)):*
> ```Markdown
> ##### Windows Only
> 
> - Navigate to the [Python 3.8.5 Downloads](https://www.python.org/downloads/release/python-385/) page.
> ```

I don't see the difference (and on some others, too).  Line endings?

**Review by jmgrady — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/726#-:-MHlq4io1PK-6hYjNPga:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/726)* status: all files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[README.md, line 247 at r1](https://reviewable.io/reviews/sillsdev/thecombine/726#-MHlkTFD9XIqB_Ln9Ezv:-MHlq18s0UCi7zGaXm5t:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/d9d59a3ea622aa8feb507d4d61e9cb9b7f2f4bcd/README.md#L247)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

> ```
> updated
> ```
should be "update"
</blockquote></details>

Done
___
*[README.md, line 268 at r1](https://reviewable.io/reviews/sillsdev/thecombine/726#-MHlktw_CrlcStPPWDnP:-MHlq80xDdx4MxnmgqAV:b5aksce) ([raw file](https://github.com/sillsdev/thecombine/blob/d9d59a3ea622aa8feb507d4d61e9cb9b7f2f4bcd/README.md#L268)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

> ```
> _TheCombine_ 
> ```
*TheCombine* and _TheCombine_ are equivalent
</blockquote></details>

Auto-formatting
___
*[README.md, line 272 at r1](https://reviewable.io/reviews/sillsdev/thecombine/726#-MHlkb6XCq0y7ZV-2Bn3:-MHlq9fXAqSFi2iAKx23:b5aksce) ([raw file](https://github.com/sillsdev/thecombine/blob/d9d59a3ea622aa8feb507d4d61e9cb9b7f2f4bcd/README.md#L272)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

I don't see the difference (and on some others, too).  Line endings?
</blockquote></details>

Auto-formatting

**Review by jmgrady — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/726)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
