### PR TITLE
Refactor Maintenance scripts

### PR DESCRIPTION
**Pull request by jmgrady**
Refactor the Combine's Maintenance scripts to:
- Change `docker-compose` commands to use the `-f` option to specify the `docker-compose.yml` file.  This means that the scripts can be run from any directory, not only from the directory with the `docker-compose.yml` file;
- Created a CombineApp Python class that maintains the location of the `docker-compose.yml` script and provides methods for running a command in one of the Combine's containers, running a database query, starting/stopping services, and various lookup functions.
- Created a AwsBackup Python class that implements push/pull of a file to/from the AWS `backups` bucket.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1091)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 4 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1091)* status: 4 of 13 files reviewed, 3 unresolved discussions (waiting on @jmgrady)

___
*[.gitignore, line 23 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MX7QpEF4vqh_Zp8EowQ:-MX7QpEF4vqh_Zp8EowR:bs1zpfp) ([raw file](https://github.com/sillsdev/thecombine/blob/04de17e705b365e75301680d229a3280cdd3cc7e/.gitignore#L23)):*
> ```
> script_conf.json
> backup_conf.json
> ```
Do we remove `backup_conf.json` from here in a later pr?
___
*[deploy/roles/combine_maintenance/files/aws_backup.py, line 9 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MX7P8PB1fLA4HFkG5Jb:-MX7P8PC2vHOyeXK5teb:b-osm91h) ([raw file](https://github.com/sillsdev/thecombine/blob/04de17e705b365e75301680d229a3280cdd3cc7e/deploy/roles/combine_maintenance/files/aws_backup.py#L9)):*
> ```Python
> 
> 
> class AwsBackup:
> ```

Will a python script using this class eventually replace the `combine-clean-aws.j3` script?
___
*[deploy/roles/combine_maintenance/files/make_user_admin.py, line 34 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MX7UQW_7ePKMcAeLJcm:-MX7UQW_7ePKMcAeLJcn:b-oyk5ga) ([raw file](https://github.com/sillsdev/thecombine/blob/04de17e705b365e75301680d229a3280cdd3cc7e/deploy/roles/combine_maintenance/files/make_user_admin.py#L34)):*
> ```
> config: Dict[str, str] = json.loads(args.config.read_text())
> ```
The `default_config` is a `Path`, but if a path string is given as the `--config` argument, will that be able to `.read_text()`?

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1091)* status: 3 of 13 files reviewed, 3 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

___
*[.gitignore, line 23 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MX7QpEF4vqh_Zp8EowQ:-MX7VmzLEWAVIADn3JMM:bnauqah) ([raw file](https://github.com/sillsdev/thecombine/blob/04de17e705b365e75301680d229a3280cdd3cc7e/.gitignore#L23)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> script_conf.json
> backup_conf.json
> ```
Do we remove `backup_conf.json` from here in a later pr?
</blockquote></details>

We can.  The updates to the ansible playbooks will remove it from the targets.  I left it here so that we would not accidentally commit any developer's copy (if anyone has run `scripts/docker_setup.py` since I updated it to create the configuration file).
___
*[deploy/roles/combine_maintenance/files/aws_backup.py, line 9 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MX7P8PB1fLA4HFkG5Jb:-MX7WDQ87NX_Bbp6KxsH:bskr6il) ([raw file](https://github.com/sillsdev/thecombine/blob/04de17e705b365e75301680d229a3280cdd3cc7e/deploy/roles/combine_maintenance/files/aws_backup.py#L9)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Will a python script using this class eventually replace the `combine-clean-aws.j3` script?
</blockquote></details>

I had not planned on that since the combine-clean-aws script is only designed to be run as part of the backup.  My expectation is that the backup script will not be used much by developers and that any backups that are created that way are best managed manually by running the `aws` command to list, remove, copy backups.
___
*[deploy/roles/combine_maintenance/files/make_user_admin.py, line 34 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MX7UQW_7ePKMcAeLJcm:-MX7Z_GR8bFN7F7aQSLj:b4dhqk2) ([raw file](https://github.com/sillsdev/thecombine/blob/04de17e705b365e75301680d229a3280cdd3cc7e/deploy/roles/combine_maintenance/files/make_user_admin.py#L34)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> config: Dict[str, str] = json.loads(args.config.read_text())
> ```
The `default_config` is a `Path`, but if a path string is given as the `--config` argument, will that be able to `.read_text()`?
</blockquote></details>

No, it won't.  Good catch.
Done.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 3 of 13 files at r1, 3 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1091)* status: 9 of 13 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

___
*[deploy/roles/combine_maintenance/files/combine_app.py, line 61 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MX7hCbL-qpO34znbxJT:-MX7hCbMCfxcba4lNZgA:b-p3hjf4) ([raw file](https://github.com/sillsdev/thecombine/blob/82c276536a2f2417580b9b6d68a517a2e5a5f3c4/deploy/roles/combine_maintenance/files/combine_app.py#L61)):*
> ```
>         exec_opts: Optional[List[str]] = None,
> ...
>         exec_opts = exec_opts or []
> ```
Why not define the function argument `exec_opts: List[str] = []`?
___
*[deploy/roles/combine_maintenance/files/combine_restore.py, line 160 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MX7iSi9DoDpKaAtfsXs:-MX7iSi9DoDpKaAtfsXt:b-xrypvo) ([raw file](https://github.com/sillsdev/thecombine/blob/82c276536a2f2417580b9b6d68a517a2e5a5f3c4/deploy/roles/combine_maintenance/files/combine_restore.py#L160)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>         db_container = CombineApp.get_container_name("database")
>         if db_container is None:
>             print("Cannot find the database container.", file=sys.stderr)
>             sys.exit(1)
>...
>         backend_container = CombineApp.get_container_name("backend")
>         if backend_container is None:
>             print("Cannot find the backend container.", file=sys.stderr)
>             sys.exit(1)
> ```
</details>

These errors are absent in `combine_backup.py`.

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1091)* status: 9 of 13 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

___
*[deploy/roles/combine_maintenance/files/combine_app.py, line 61 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MX7hCbL-qpO34znbxJT:-MX7jhlf0voZWXrY-iEY:baz7256) ([raw file](https://github.com/sillsdev/thecombine/blob/82c276536a2f2417580b9b6d68a517a2e5a5f3c4/deploy/roles/combine_maintenance/files/combine_app.py#L61)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>         exec_opts: Optional[List[str]] = None,
> ...
>         exec_opts = exec_opts or []
> ```
Why not define the function argument `exec_opts: List[str] = []`?
</blockquote></details>

That's what I had originally but `pylint` tells me:
```
[dangerous-default-value] Dangerous default value [] as argument
```
see https://stackoverflow.com/questions/101268/hidden-features-of-python#113198
___
*[deploy/roles/combine_maintenance/files/combine_restore.py, line 160 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MX7iSi9DoDpKaAtfsXs:-MX7ka9K3hbYSiiwpGfh:b-q8nazg) ([raw file](https://github.com/sillsdev/thecombine/blob/82c276536a2f2417580b9b6d68a517a2e5a5f3c4/deploy/roles/combine_maintenance/files/combine_restore.py#L160)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>         db_container = CombineApp.get_container_name("database")
>         if db_container is None:
>             print("Cannot find the database container.", file=sys.stderr)
>             sys.exit(1)
>...
>         backend_container = CombineApp.get_container_name("backend")
>         if backend_container is None:
>             print("Cannot find the backend container.", file=sys.stderr)
>             sys.exit(1)
> ```
These errors are absent in `combine_backup.py`.
</blockquote></details>

That is correct.  The restore script is designed to be run interactively so I wanted to provide information to the user.

That said, the backup is not complete if there is an error finding the containers so it should probably exit as well.  I will change that.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 13 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1091)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[deploy/roles/combine_maintenance/files/combine_app.py, line 61 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MX7hCbL-qpO34znbxJT:-MX7lX4O98tvDIxFf3MH:bnjriky) ([raw file](https://github.com/sillsdev/thecombine/blob/82c276536a2f2417580b9b6d68a517a2e5a5f3c4/deploy/roles/combine_maintenance/files/combine_app.py#L61)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

That's what I had originally but `pylint` tells me:
```
[dangerous-default-value] Dangerous default value [] as argument
```
see https://stackoverflow.com/questions/101268/hidden-features-of-python#113198
</blockquote></details>

Oh! That's a good point.

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1091)* status: 11 of 13 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[deploy/roles/combine_maintenance/files/combine_restore.py, line 160 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MX7iSi9DoDpKaAtfsXs:-MX7lsBD1EYxIYMwFv-I:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/82c276536a2f2417580b9b6d68a517a2e5a5f3c4/deploy/roles/combine_maintenance/files/combine_restore.py#L160)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

That is correct.  The restore script is designed to be run interactively so I wanted to provide information to the user.

That said, the backup is not complete if there is an error finding the containers so it should probably exit as well.  I will change that.
</blockquote></details>

Done.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 5 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1091)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Comment by johnthagen** [comment]
___
*[deploy/roles/combine_maintenance/files/combine_app.py, line 30 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MYPVM6L4tUmL1R4P6tN:-MYPVM6L4tUmL1R4P6tO:b-t5abkv) ([raw file](https://github.com/sillsdev/thecombine/blob/72843e2b7d020a7b4069322f6e9e5d7f4de4b9f8/deploy/roles/combine_maintenance/files/combine_app.py#L30)):*
> ```Python
>     def __init__(self, compose_file_path: Path) -> None:
>         """Initialize the CombineApp from the configuration file."""
>         if compose_file_path:
> ```

Can this branch be removed? I would suggest if you want to express that this parameter is optional to use `Optional[Path]`.

From all of the usages I see, this parameter is always filled. If the config key is missing, wouldn't that through a missing key error when `config["docker_compose_file"]` is called?

As far as I can tell, `Path` doesn't seem to have any obvious `bool` conversions that evaluate to false. What was the intention with this check?

**Comment by johnthagen** [comment]
___
*[deploy/roles/combine_maintenance/files/combine_app.py, line 58 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MYPWT04-LMFCDz1HFAr:-MYPWT057BYBu1HPdPYE:b5u6n6y) ([raw file](https://github.com/sillsdev/thecombine/blob/72843e2b7d020a7b4069322f6e9e5d7f4de4b9f8/deploy/roles/combine_maintenance/files/combine_app.py#L58)):*
> ```Python
>                      command, for example, to specify a working directory or a
>                      specific user to run the command.
> ```

Missing `check_results` in docstring. If you setup PyCharm Docstrings according to https://github.com/johnthagen/python-blueprint#pycharm-configuration, it will check this for you in Google style docstrings automatically.

**Comment by johnthagen** [comment]
___
*[deploy/roles/combine_maintenance/files/combine_app.py, line 89 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MYPZ--KB6ycN2T-8dDp:-MYPZ--KB6ycN2T-8dDq:bs74med) ([raw file](https://github.com/sillsdev/thecombine/blob/72843e2b7d020a7b4069322f6e9e5d7f4de4b9f8/deploy/roles/combine_maintenance/files/combine_app.py#L89)):*
> ```Python
>             ["docker", "ps", "--filter", f"name={service}", "--format", "{{.Names}}"]
>         ).stdout.strip()
>         if not container_id:
> ```

I personally find it easier to maintain Python code by avoiding many implicit `bool` conversions. This is due to its dynamic nature and not always 100% type checked nature.

I would personally find it easier to read if this was set to (what I think you intended):

```py
if container_id == b""
```

This can help avoid different types like `None` silently sneaking through and changing behavior in subtle ways.

**Comment by johnthagen** [comment]
___
*[deploy/roles/combine_maintenance/files/combine_app.py, line 105 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MYPZjzL0QTpurQJbxJV:-MYPZjzMDIudBXn0zmPi:ba13gu8) ([raw file](https://github.com/sillsdev/thecombine/blob/72843e2b7d020a7b4069322f6e9e5d7f4de4b9f8/deploy/roles/combine_maintenance/files/combine_app.py#L105)):*
> ```Python
>         )
>         result_str = self.object_id_to_str(db_results.stdout)
>         if result_str:
> ```

I similarly personally find this to read more clearly as:

```py
if result_str != ""
```

It's clear to the reader what the intended type is. IDEs can also give some more precise help if the variable type ever accidently changes away from `str`.

**Comment by johnthagen** [comment]
___
*[deploy/roles/combine_maintenance/files/combine_app.py, line 15 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MYP_IsmDNAlEYvh1-SI:-MYP_IsmDNAlEYvh1-SJ:bvubej4) ([raw file](https://github.com/sillsdev/thecombine/blob/72843e2b7d020a7b4069322f6e9e5d7f4de4b9f8/deploy/roles/combine_maintenance/files/combine_app.py#L15)):*
> ```Python
> 
> @enum.unique
> class Permission(enum.IntEnum):
> ```

All of the usages of this `Enum` are wrapped in `int()` checks. A more type safe way to work with `Enum`'s is to use the normal `Enum` class and then use `.value`.

For example this would become:

```py
@enum.unique
class Permission(enum.Enum):
    """Define enumerated type for Combine user permissions."""

    WordEntry = 1
    Unused = 2
    MergeAndCharSet = 3
    ImportExport = 4
    DeleteEditSettingsAndUsers = 5
```

And it's usages would look like:

```py
        if args.admin:
            user_permissions = [
                Permission.DeleteEditSettingsAndUsers.value,
                Permission.ImportExport.value
                Permission.MergeAndCharSet.value,
                Permission.Unused.value,
                Permission.WordEntry.value,
            ]
```

What this does is open up a type safe way to use this `Enum` in other places. Imagine a function:

```py
def check_user_perms(username: str, permission: Permission) -> bool:
   ...
```

When using an `IntEnum`, the `Enum` is automatically subclassed from `int` as well, this would make the following invocation valid type checked:

```py
check_user_perms("tony_stark", 99999) 
```

But  if`Permission` is a subclass of `Enum`, only the following invocations would be allowed by the type checker:

```py
check_user_perms("tony_stark", Permission.MergeAndCharSet)
```

In general, always use `Enum` unless there is a very specific need to trade away the type safety for the convenience of converting to `int` (this is rare). `IntEnum` shouldn't be used just because the values are `int` (though I see how this could be assumed based on the name).

**Comment by johnthagen** [comment]
___
*[deploy/roles/combine_maintenance/files/aws_backup.py, line 12 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MYPcZ7eEIKlyvYCQkmu:-MYPcZ7eEIKlyvYCQkmv:bjfnt6n) ([raw file](https://github.com/sillsdev/thecombine/blob/72843e2b7d020a7b4069322f6e9e5d7f4de4b9f8/deploy/roles/combine_maintenance/files/aws_backup.py#L12)):*
> ```Python
>     """Simple interface for managing backups in AWS S3 bucket."""
> 
>     def __init__(self, *, bucket: str, profile: str):
> ```

Missing return type: `-> None`

I'm not sure why `mypy` didn't catch this.

**Comment by johnthagen** [comment]
___
*[deploy/roles/combine_maintenance/files/combine_app.py, line 55 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MYPdcpD8m_vV6XpzZD3:-MYPdcpD8m_vV6XpzZD4:be4v0nc) ([raw file](https://github.com/sillsdev/thecombine/blob/72843e2b7d020a7b4069322f6e9e5d7f4de4b9f8/deploy/roles/combine_maintenance/files/combine_app.py#L55)):*
> ```Python
>             cmd: A list of strings that specifies the command to be run in the
>                      container.
>             exec_opts: A list of addtional options for the docker-compose exec
> ```

Typo: `additional`

**Comment by johnthagen** [comment]
___
*[deploy/roles/combine_maintenance/files/combine_app.py, line 89 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MYPZ--KB6ycN2T-8dDp:-MYPkC7xAiOTfheXZGUW:b-66arud) ([raw file](https://github.com/sillsdev/thecombine/blob/72843e2b7d020a7b4069322f6e9e5d7f4de4b9f8/deploy/roles/combine_maintenance/files/combine_app.py#L89)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I personally find it easier to maintain Python code by avoiding many implicit `bool` conversions. This is due to its dynamic nature and not always 100% type checked nature.

I would personally find it easier to read if this was set to (what I think you intended):

```py
if container_id == b""
```

This can help avoid different types like `None` silently sneaking through and changing behavior in subtle ways.
</blockquote></details>

This might be `== ""`. I thought `CompletedProcess.stdout` was `bytes`, but I haven't been able to double check  yet.

**Comment by johnthagen** [comment]
___
*[deploy/roles/combine_maintenance/files/combine_app.py, line 89 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MYPZ--KB6ycN2T-8dDp:-MYPlmCX3fgaPPCSIWHk:bzfupht) ([raw file](https://github.com/sillsdev/thecombine/blob/72843e2b7d020a7b4069322f6e9e5d7f4de4b9f8/deploy/roles/combine_maintenance/files/combine_app.py#L89)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This might be `== ""`. I thought `CompletedProcess.stdout` was `bytes`, but I haven't been able to double check  yet.
</blockquote></details>

Yes, it looks like `stdout` will always be `bytes`, so `b""` is appropriate.

**Comment by johnthagen** [comment]
___
*[deploy/roles/combine_maintenance/files/combine_app.py, line 89 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MYPZ--KB6ycN2T-8dDp:-MYPsTwZ5W4AnGN6q8H2:bpdp1tr) ([raw file](https://github.com/sillsdev/thecombine/blob/72843e2b7d020a7b4069322f6e9e5d7f4de4b9f8/deploy/roles/combine_maintenance/files/combine_app.py#L89)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Yes, it looks like `stdout` will always be `bytes`, so `b""` is appropriate.
</blockquote></details>

Okay, no this is a `str` if `universal_newlines=True`, so it should be a `""`.

**Review by jmgrady — COMMENTED** [review]
Improvements from John's post-merge comments are in PR #1113.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1091#-:-MYPvoky1rJIKvRqdaUW:bwpv5ts)* status: all files reviewed, 5 unresolved discussions

___
*[deploy/roles/combine_maintenance/files/aws_backup.py, line 12 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MYPcZ7eEIKlyvYCQkmu:-MYPk85O9fDVIwdj4nRs:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/72843e2b7d020a7b4069322f6e9e5d7f4de4b9f8/deploy/roles/combine_maintenance/files/aws_backup.py#L12)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Missing return type: `-> None`

I'm not sure why `mypy` didn't catch this.
</blockquote></details>

Done.
___
*[deploy/roles/combine_maintenance/files/combine_app.py, line 15 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MYP_IsmDNAlEYvh1-SI:-MYPlV-o9FtcyULGdkEV:b-sbzutj) ([raw file](https://github.com/sillsdev/thecombine/blob/72843e2b7d020a7b4069322f6e9e5d7f4de4b9f8/deploy/roles/combine_maintenance/files/combine_app.py#L15)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

All of the usages of this `Enum` are wrapped in `int()` checks. A more type safe way to work with `Enum`'s is to use the normal `Enum` class and then use `.value`.

For example this would become:

```py
@enum.unique
class Permission(enum.Enum):
    """Define enumerated type for Combine user permissions."""

    WordEntry = 1
    Unused = 2
    MergeAndCharSet = 3
    ImportExport = 4
    DeleteEditSettingsAndUsers = 5
```

And it's usages would look like:

```py
        if args.admin:
            user_permissions = [
                Permission.DeleteEditSettingsAndUsers.value,
                Permission.ImportExport.value
                Permission.MergeAndCharSet.value,
                Permission.Unused.value,
                Permission.WordEntry.value,
            ]
```

What this does is open up a type safe way to use this `Enum` in other places. Imagine a function:

```py
def check_user_perms(username: str, permission: Permission) -> bool:
   ...
```

When using an `IntEnum`, the `Enum` is automatically subclassed from `int` as well, this would make the following invocation valid type checked:

```py
check_user_perms("tony_stark", 99999) 
```

But  if`Permission` is a subclass of `Enum`, only the following invocations would be allowed by the type checker:

```py
check_user_perms("tony_stark", Permission.MergeAndCharSet)
```

In general, always use `Enum` unless there is a very specific need to trade away the type safety for the convenience of converting to `int` (this is rare). `IntEnum` shouldn't be used just because the values are `int` (though I see how this could be assumed based on the name).
</blockquote></details>

Done.

Although, I am curious as to why we are setting "Permission.Unused".  I put it in there because it exists in all the new users that are created by the app.  Sounds like a question for Jason and a probably Issue to be resolved here and in the Backend.
___
*[deploy/roles/combine_maintenance/files/combine_app.py, line 30 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MYPVM6L4tUmL1R4P6tN:-MYPmT975id4t7a_hJNc:b-rvb47v) ([raw file](https://github.com/sillsdev/thecombine/blob/72843e2b7d020a7b4069322f6e9e5d7f4de4b9f8/deploy/roles/combine_maintenance/files/combine_app.py#L30)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Can this branch be removed? I would suggest if you want to express that this parameter is optional to use `Optional[Path]`.

From all of the usages I see, this parameter is always filled. If the config key is missing, wouldn't that through a missing key error when `config["docker_compose_file"]` is called?

As far as I can tell, `Path` doesn't seem to have any obvious `bool` conversions that evaluate to false. What was the intention with this check?

</blockquote></details>

If the configuration file has a blank path (legal) for the docker_compose_file, it will not append the '-f' option to all of the docker-compose commands.  From your other comments, I will improve this by explicitly checking against an empty string.
___
*[deploy/roles/combine_maintenance/files/combine_app.py, line 55 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MYPdcpD8m_vV6XpzZD3:-MYPnBZZ1fFpxCjZzCVr:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/72843e2b7d020a7b4069322f6e9e5d7f4de4b9f8/deploy/roles/combine_maintenance/files/combine_app.py#L55)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Typo: `additional`
</blockquote></details>

Done.
___
*[deploy/roles/combine_maintenance/files/combine_app.py, line 58 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MYPWT04-LMFCDz1HFAr:-MYPuLIw8MTwe50fkIUW:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/72843e2b7d020a7b4069322f6e9e5d7f4de4b9f8/deploy/roles/combine_maintenance/files/combine_app.py#L58)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Missing `check_results` in docstring. If you setup PyCharm Docstrings according to https://github.com/johnthagen/python-blueprint#pycharm-configuration, it will check this for you in Google style docstrings automatically.
</blockquote></details>

Done.
___
*[deploy/roles/combine_maintenance/files/combine_app.py, line 89 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MYPZ--KB6ycN2T-8dDp:-MYPukru5215NxFu-JcG:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/72843e2b7d020a7b4069322f6e9e5d7f4de4b9f8/deploy/roles/combine_maintenance/files/combine_app.py#L89)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Okay, no this is a `str` if `universal_newlines=True`, so it should be a `""`.
</blockquote></details>

Done.
___
*[deploy/roles/combine_maintenance/files/combine_app.py, line 105 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1091#-MYPZjzL0QTpurQJbxJV:-MYPutRVDxWE4iEWHL4-:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/72843e2b7d020a7b4069322f6e9e5d7f4de4b9f8/deploy/roles/combine_maintenance/files/combine_app.py#L105)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I similarly personally find this to read more clearly as:

```py
if result_str != ""
```

It's clear to the reader what the intended type is. IDEs can also give some more precise help if the variable type ever accidently changes away from `str`.
</blockquote></details>

Done.

**Pull request merged**
