### PR TITLE
[ReviewEntries] Wait until words loaded to show table

### PR DESCRIPTION
**Pull request by imnasnainaec**
ReviewEntries tries to load with data from the previous project, resulting in console errors and sometimes a mis-sized table. This holds the show until the active projects words are loaded.

To reproduce:

> Make project 1 have fewer words than min(10, # in project 2) and the table will be too small when it first loads.
> Have a few audio files in project 1 and you may see console errors when you switch to project 2.
> For example, Project 1 has 5 words and Project 2 as 12 words.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/653)

### CODE REVIEW

**Comment by johnthagen** [comment]
As an FYI #661 fixes up the out-of-sync `package-lock.json` file. So depending on which of these PR's is merged first, we can deal with the conflict afterwards.

**Comment by johnthagen** [comment]
___
*[package-lock.json, line 2029 at r1](https://reviewable.io/reviews/sillsdev/thecombine/653#-MFp2ToQDGo5zGH__Oyn:-MFp2ToQDGo5zGH__Oyo:b-62cian) ([raw file](https://github.com/sillsdev/thecombine/blob/8b8a5dc4984d50b225186a0a5180e8cab1cb5795/package-lock.json#L2029)):*
> ```JSON
>       "resolved": "https://registry.npmjs.org/@types/recordrtc/-/recordrtc-5.6.0.tgz",
>       "integrity": "sha512-GKrAo5X0yT+iIeKHVhN52h0+3bRenLhv1oOgaCDgIR7KsxvtsX391jIImaKPJQXaOi8Fif609I79G0eM0QGhwA==",
>       "dev": true
> ```

FYI, this change is also in the self-contained https://github.com/sillsdev/TheCombine/pull/661

**Comment by johnthagen** [comment]
___
*[src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesComponent.tsx, line 87 at r1](https://reviewable.io/reviews/sillsdev/thecombine/653#-MFp2h3t53dteJwmSJSE:-MFp2h3t53dteJwmSJSF:b-7l1hef) ([raw file](https://github.com/sillsdev/thecombine/blob/8b8a5dc4984d50b225186a0a5180e8cab1cb5795/src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesComponent.tsx#L87)):*
> ```XML
>   render() {
>     return (
>       this.state.loaded && (
> ```

Can we add a unit test for this bug?

**Comment by johnthagen** [comment]
___
*[src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesComponent.tsx, line 36 at r1](https://reviewable.io/reviews/sillsdev/thecombine/653#-MFp2t0L36q-bDZB6srz:-MFp2t0L36q-bDZB6ss-:b-790swd) ([raw file](https://github.com/sillsdev/thecombine/blob/8b8a5dc4984d50b225186a0a5180e8cab1cb5795/src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesComponent.tsx#L36)):*
> ```XML
> interface ReviewEntriesState {
>   editingField: boolean;
>   errorMsg: string | undefined;
> ```

Purely curiosity on my point, but do we have any conventions for when we use `type | undefined` vs `type | null`? Coming from other languages I'd tend to default to `type | null`, but I'm relatively new to TypeScript.

Looks like features like Optional Chaining work on both, so perhaps it's not a really  a big issue. https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining

**Comment by johnthagen** [comment]
@imnasnainaec While testing this PR on `master` to try to reproduce, I created a project, added entries, created another project and switched to it, clicked review entries, and then hit the browser back button and I got this error in the browser:

```
Unhandled Rejection (TypeError): Cannot read property 'goalType' of undefined
updateStepData
C:/Users/User/GitHub/TheCombine/src/components/GoalTimeline/GoalsActions.tsx:178
  175 | }
  176 | 
  177 | export function updateStepData(goal: Goal): Goal {
> 178 |   switch (goal.goalType) {
  179 |     case GoalType.MergeDups: {
  180 |       let currentGoalData: MergeDupData = JSON.parse(
  181 |         JSON.stringify(goal.data as MergeDupData)
View compiled
(anonymous function)
C:/Users/User/GitHub/TheCombine/src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx:219
  216 |   state: GoalHistoryState
  217 | ): Promise<void> {
  218 |   return new Promise((resolve, reject) => {
> 219 |     let updatedGoal = updateStepData(goal);
  220 |     dispatch(updateGoal(updatedGoal));
  221 |     let indexInHistory: number = getIndexInHistory(state.history, goal);
  222 |     addStepToGoal(state.history[indexInHistory], indexInHistory);
View compiled
updateStep
C:/Users/User/GitHub/TheCombine/src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx:218
  215 |   goal: Goal,
  216 |   state: GoalHistoryState
  217 | ): Promise<void> {
> 218 |   return new Promise((resolve, reject) => {
  219 |     let updatedGoal = updateStepData(goal);
  220 |     dispatch(updateGoal(updatedGoal));
  221 |     let indexInHistory: number = getIndexInHistory(state.history, goal);
View compiled
(anonymous function)
C:/Users/User/GitHub/TheCombine/src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx:195
  192 |    let goal: Goal = historyState.history[historyState.history.length - 1];
  193 | 
  194 |    // Push the current step into the history state and load the data.
> 195 |    await updateStep(dispatch, goal, historyState).then(() => {
      | ^  196 |      historyState = getState().goalsState.historyState;
  197 |      goal = historyState.history[historyState.history.length - 1];
  198 |      if (goal.currentStep < goal.numSteps) {
View compiled
▶ 2 stack frames were collapsed.
(anonymous function)
C:/Users/User/GitHub/TheCombine/src/components/GoalTimeline/GoalsActions.tsx:165
  162 |        goal.currentStep = 0;
  163 |        goal.steps = [];
  164 | 
> 165 |        await dispatch(refreshWords());
      | ^  166 | 
  167 |        break;
  168 |      case GoalType.CreateCharInv:
```

Is this the bug related to this MR, or a separate bug that should be filed?

**Comment by imnasnainaec** [comment]
> @imnasnainaec While testing this PR on `master` to try to reproduce, I created a project, added entries, created another project and switched to it, clicked review entries, and then hit the browser back button and I got this error in the browser:
> 
> ```
> Unhandled Rejection (TypeError): Cannot read property 'goalType' of undefined
> updateStepData
> C:/Users/User/GitHub/TheCombine/src/components/GoalTimeline/GoalsActions.tsx:178
>   175 | }
>   176 | 
>   177 | export function updateStepData(goal: Goal): Goal {
> > 178 |   switch (goal.goalType) {
>   179 |     case GoalType.MergeDups: {
>   180 |       let currentGoalData: MergeDupData = JSON.parse(
>   181 |         JSON.stringify(goal.data as MergeDupData)
> View compiled
> (anonymous function)
> C:/Users/User/GitHub/TheCombine/src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx:219
>   216 |   state: GoalHistoryState
>   217 | ): Promise<void> {
>   218 |   return new Promise((resolve, reject) => {
> > 219 |     let updatedGoal = updateStepData(goal);
>   220 |     dispatch(updateGoal(updatedGoal));
>   221 |     let indexInHistory: number = getIndexInHistory(state.history, goal);
>   222 |     addStepToGoal(state.history[indexInHistory], indexInHistory);
> View compiled
> updateStep
> C:/Users/User/GitHub/TheCombine/src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx:218
>   215 |   goal: Goal,
>   216 |   state: GoalHistoryState
>   217 | ): Promise<void> {
> > 218 |   return new Promise((resolve, reject) => {
>   219 |     let updatedGoal = updateStepData(goal);
>   220 |     dispatch(updateGoal(updatedGoal));
>   221 |     let indexInHistory: number = getIndexInHistory(state.history, goal);
> View compiled
> (anonymous function)
> C:/Users/User/GitHub/TheCombine/src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx:195
>   192 |    let goal: Goal = historyState.history[historyState.history.length - 1];
>   193 | 
>   194 |    // Push the current step into the history state and load the data.
> > 195 |    await updateStep(dispatch, goal, historyState).then(() => {
>       | ^  196 |      historyState = getState().goalsState.historyState;
>   197 |      goal = historyState.history[historyState.history.length - 1];
>   198 |      if (goal.currentStep < goal.numSteps) {
> View compiled
> ▶ 2 stack frames were collapsed.
> (anonymous function)
> C:/Users/User/GitHub/TheCombine/src/components/GoalTimeline/GoalsActions.tsx:165
>   162 |        goal.currentStep = 0;
>   163 |        goal.steps = [];
>   164 | 
> > 165 |        await dispatch(refreshWords());
>       | ^  166 | 
>   167 |        break;
>   168 |      case GoalType.CreateCharInv:
> ```
> 
> Is this the bug related to this MR, or a separate bug that should be filed?

@johnthagen The back button generally misbehaves with our goal routing (e.g., https://github.com/sillsdev/TheCombine/issues/393).

**Comment by johnthagen** [comment]
I have reproduced this issue on `master` by creating Project 1 with 5 entries and Project 2 with 12 entries. The table is indeed too small and the following console warning is printed:

table

<details><summary>Error:</summary>

```
react_devtools_backend.js:2273 Material-UI: You have provided an out-of-range value `5` for the select component.
Consider providing a value that matches one of the available options or ''.
The available values are `10`, `12`. 
    at SelectInput (http://localhost:3000/static/js/0.chunk.js:24148:24)
    at div
    at InputBase (http://localhost:3000/static/js/0.chunk.js:16539:30)
    at WithStyles (http://localhost:3000/static/js/0.chunk.js:194658:31)
    at Select (http://localhost:3000/static/js/0.chunk.js:23849:32)
    at WithStyles (http://localhost:3000/static/js/0.chunk.js:194658:31)
    at div
    at Toolbar (http://localhost:3000/static/js/0.chunk.js:32972:23)
    at WithStyles (http://localhost:3000/static/js/0.chunk.js:194658:31)
    at td
    at TableCell (http://localhost:3000/static/js/0.chunk.js:30220:28)
    at WithStyles (http://localhost:3000/static/js/0.chunk.js:194658:31)
    at TablePagination (http://localhost:3000/static/js/0.chunk.js:30764:37)
    at WithStyles (http://localhost:3000/static/js/0.chunk.js:194658:31)
    at tr
    at TableRow (http://localhost:3000/static/js/0.chunk.js:31181:23)
    at WithStyles (http://localhost:3000/static/js/0.chunk.js:194658:31)
    at tfoot
    at TableFooter (http://localhost:3000/static/js/0.chunk.js:30483:23)
    at WithStyles (http://localhost:3000/static/js/0.chunk.js:194658:31)
    at table
    at Table (http://localhost:3000/static/js/0.chunk.js:29839:23)
    at WithStyles (http://localhost:3000/static/js/0.chunk.js:194658:31)
    at div
    at Paper (http://localhost:3000/static/js/0.chunk.js:21899:23)
    at WithStyles (http://localhost:3000/static/js/0.chunk.js:194658:31)
    at Container
    at Provider (http://localhost:3000/static/js/0.chunk.js:368691:20)
    at App (http://localhost:3000/static/js/0.chunk.js:260044:25)
    at ErrorBoundary (http://localhost:3000/static/js/0.chunk.js:253244:35)
    at DragDropContext (http://localhost:3000/static/js/0.chunk.js:260176:19)
    at MaterialTable (http://localhost:3000/static/js/0.chunk.js:249877:37)
    at http://localhost:3000/static/js/0.chunk.js:249761:16
    at WithStyles (http://localhost:3000/static/js/0.chunk.js:194658:31)
    at h1
    at Typography (http://localhost:3000/static/js/0.chunk.js:33927:28)
    at WithStyles (http://localhost:3000/static/js/0.chunk.js:194658:31)
    at WrappedTranslate (http://localhost:3000/static/js/0.chunk.js:366218:5)
    at Translate
    at ReviewEntriesComponent (http://localhost:3000/static/js/main.chunk.js:20290:5)
    at LocalizedComponent (http://localhost:3000/static/js/0.chunk.js:367052:7)
    at ConnectFunction (http://localhost:3000/static/js/0.chunk.js:368978:75)
    at div
    at div
    at BaseGoalScreen (http://localhost:3000/static/js/main.chunk.js:16778:1)
    at LocalizedComponent (http://localhost:3000/static/js/0.chunk.js:367052:7)
    at ConnectFunction (http://localhost:3000/static/js/0.chunk.js:368978:75)
    at Route (http://localhost:3000/static/js/0.chunk.js:372120:29)
    at PrivateRoute (http://localhost:3000/static/js/main.chunk.js:7737:14)
    at Switch (http://localhost:3000/static/js/0.chunk.js:372322:29)
    at div
    at GoalRoute (http://localhost:3000/static/js/main.chunk.js:4355:1)
    at Route (http://localhost:3000/static/js/0.chunk.js:372120:29)
    at PrivateRoute (http://localhost:3000/static/js/main.chunk.js:7737:14)
    at Switch (http://localhost:3000/static/js/0.chunk.js:372322:29)
    at div
    at App (http://localhost:3000/static/js/main.chunk.js:629:1)
    at PersistGate (http://localhost:3000/static/js/0.chunk.js:384958:5)
    at Router (http://localhost:3000/static/js/0.chunk.js:371755:30)
    at LocalizeProvider (http://localhost:3000/static/js/0.chunk.js:366012:5)
    at Provider (http://localhost:3000/static/js/0.chunk.js:368691:20)
    at ThemeProvider (http://localhost:3000/static/js/0.chunk.js:193362:24)
```

</details>

**Comment by johnthagen** [comment]
I confirmed that with this branch, the bug is no longer present.

**Comment by johnthagen** [comment]
___
*[src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesComponent.tsx, line 87 at r1](https://reviewable.io/reviews/sillsdev/thecombine/653#-MFp2h3t53dteJwmSJSE:-MFqepw42PGnuJTVG0io:b73ja77) ([raw file](https://github.com/sillsdev/thecombine/blob/8b8a5dc4984d50b225186a0a5180e8cab1cb5795/src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesComponent.tsx#L87)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Anything particular in mind?
</blockquote></details>

Unsure exactly what it would look like, but something that simulated having two projects and stimulated the bug we saw where things weren't loaded properly before the table was shown. If that's too high level / involves too many parts, then maybe we can pass on a test for this PR?

**Pull request merged**
