### PR TITLE
Fixed onblur crashing page if field is left empty

### LINKED ISSUE #1197: Pressing Shift-Tab to move back to edit the username causes frontend to try to log in
Maybe related to #1187 

1. Open Register Page
2. For Your Name type: user
3. Press Tab
4. Press Shift-Tab to go back to try to edit "Your Name" field
5. Registration page is redirected to login page before being able to do anything

## TODO

- [ ] The backend should be able to handle a blank string (`""`) sent to check if a username or email exists 
- [ ] The frontend should not send a request to check if a username or email exists if the input field is blank (`""`)

### PR DESCRIPTION
**Pull request by JacobHaimes**
Added a length check to the username and email fields in onBlur to prevent empty strings from being passed into the validity checks.

Fixes #1197

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1308)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1308)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @JacobHaimes and @WeJamUS)

___
*[src/components/Login/RegisterPage/RegisterComponent.tsx, line 131 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1308#-MhOuacW6rxA8QgRtWp5:-MhOuacW6rxA8QgRtWp6:blvqeki) ([raw file](https://github.com/sillsdev/thecombine/blob/ca10bc5cf915deb72261082d6407f6bddea176a1/src/components/Login/RegisterPage/RegisterComponent.tsx#L131)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     this.checkEmail(this.state.email);
>     this.checkUsername(this.state.username);
>     error.name = name === "";
>     error.username = !usernameRequirements(username);
>     error.email = email === "";
> ```
</details>

Since the process within `register` is setting the state, we don't want to call on `checkEmail` in the middle of it (which does its own state update), but rather modify the `error.email = ...` line to incorporate the backend check: `error.email = email === "" || await isEmailTaken(email);`.

Same for username.
___
*[src/components/Login/RegisterPage/RegisterComponent.tsx, line 196 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1308#-MhOwHHS2sPRadKoD5nR:-MhOwHHS2sPRadKoD5nS:b-2a9q5) ([raw file](https://github.com/sillsdev/thecombine/blob/ca10bc5cf915deb72261082d6407f6bddea176a1/src/components/Login/RegisterPage/RegisterComponent.tsx#L196)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>                 onBlur={() =>
>                   usernameRequirements(this.state.username)
>                     ? this.checkUsername(this.state.username)
>                     : this.setState((prevState) => ({
>                         error: { ...prevState.error, username: true },
>                       }))
>                 }
> ```
</details>

Rather than adding the conditional here, it would be more robust to include the `usernameRequirements(this.state.username)`-check within the function `checkUsername` function.

**Review by WeJamUS — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1308)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @JacobHaimes)

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1308)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @JacobHaimes)

___
*[src/components/Login/RegisterPage/RegisterComponent.tsx, line 101 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1308#-MhTwhJDEpZVoFS225ij:-MhTwhJDEpZVoFS225ik:b6srel0) ([raw file](https://github.com/sillsdev/thecombine/blob/c685ffc64ee0651c75aa14a1d6de48e97c68ebf9/src/components/Login/RegisterPage/RegisterComponent.tsx#L101)):*
> ```XML
>   async checkUsername(username: string) {
>     if (usernameRequirements(this.state.username)) {
>       const usernameTaken: boolean = await isUsernameTaken(username);
> ```

I think this `: boolean` is unnecessary.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1308)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @JacobHaimes)

*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/1308#-MhTxiwx1_hHXdz4kCwu:-MhTxiwx1_hHXdz4kCwv:bppat68) (no related file):*
Ah, frontend tests now fail with the updated logic. It looks like we need to mock `isEmailTaken` and `isUsernameTaken` in the tests file.

---

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1308)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @JacobHaimes)

*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/1308#-MhTxiwx1_hHXdz4kCwu:-MhUXY9CDmkJpeBePMhK:btn3f21) (no related file):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Ah, frontend tests now fail with the updated logic. It looks like we need to mock `isEmailTaken` and `isUsernameTaken` in the tests file.
</blockquote></details>

This may do it:
```
jest.mock("backend", () => {
  return {
    isEmailTaken: () => false,
    isUsernameTaken: () => false,
  };
});
```

---

**Comment by johnthagen** [comment]
___
*[-- commits, line 1 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1308#-MhYSJV11m1Fs7dHNzbN:-MhYSJV11m1Fs7dHNzbO:b-lpixm9) ([raw file](https://github.com/sillsdev/thecombine/blob/c685ffc64ee0651c75aa14a1d6de48e97c68ebf9/-- commits#L1)):*
Since the PR title is used in the final squashed commit, I'd recommend upper casing the first word of the PR title so that the final commit message is consistent with our other PRs.

**Comment by johnthagen** [comment]
___
*[src/components/Login/RegisterPage/RegisterComponent.tsx, line 100 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1308#-MhYUfhx8IpUbTg0P0_i:-MhYUfhx8IpUbTg0P0_j:by6cvfu) ([raw file](https://github.com/sillsdev/thecombine/blob/c685ffc64ee0651c75aa14a1d6de48e97c68ebf9/src/components/Login/RegisterPage/RegisterComponent.tsx#L100)):*
> ```XML
> 
>   async checkUsername(username: string) {
>     if (usernameRequirements(this.state.username)) {
> ```

While we are here, I feel like the `usernameRequirements` and `passwordRequirements` functions should be renamed. 

I think functions should generally be verbs. @imnasnainaec what do you think of `meetsUsernameRequirements`?

**Comment by johnthagen** [comment]
___
*[src/components/Login/RegisterPage/RegisterComponent.tsx, line 115 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1308#-MhYVb7E4WVLpzO59dbn:-MhYVb7E4WVLpzO59dbo:b-uz0kf4) ([raw file](https://github.com/sillsdev/thecombine/blob/c685ffc64ee0651c75aa14a1d6de48e97c68ebf9/src/components/Login/RegisterPage/RegisterComponent.tsx#L115)):*
> ```XML
> 
>   async checkEmail(username: string) {
>     const emailTaken: boolean = await isEmailTaken(username);
> ```

This `: boolean` can be removed as well.

**Review by johnthagen — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1308)* status: all files reviewed, 4 unresolved discussions (waiting on @JacobHaimes)

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1308)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @JacobHaimes and @johnthagen)

___
*[src/components/Login/RegisterPage/RegisterComponent.tsx, line 113 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1308#-Mhshkbe4GHYJK6dE034:-Mhshkbf3ge9jgs7uMmS:b-bwjed6) ([raw file](https://github.com/sillsdev/thecombine/blob/85d5da605f98ae0090b858f4c9536b88f2233517/src/components/Login/RegisterPage/RegisterComponent.tsx#L113)):*
> ```
>       this.setState((prevState) => ({
>         error: { ...prevState.error, username: true },
>       }));
> ```
To only have this once, you can replace all the logic before it with:
`if (!meetsUsernameRequirements(this.state.username) || await isUsernameTaken(username)) {`

Since JavaScript does short-circuit evaluation of `||`, if the first condition is true, it doesn't have to check the second one, so we know that the `await` will only happen if necessary.

**Review by JacobHaimes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1308)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @JacobHaimes and @johnthagen)

___
*[-- commits, line 1 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1308#-MhYSJV11m1Fs7dHNzbN):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Since the PR title is used in the final squashed commit, I'd recommend upper casing the first word of the PR title so that the final commit message is consistent with our other PRs.
</blockquote></details>

Done.
___
*[src/components/Login/RegisterPage/RegisterComponent.tsx, line 100 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1308#-MhYUfhx8IpUbTg0P0_i:-Mhtge1O60SGwzLBGXLi:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/c685ffc64ee0651c75aa14a1d6de48e97c68ebf9/src/components/Login/RegisterPage/RegisterComponent.tsx#L100)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

While we are here, I feel like the `usernameRequirements` and `passwordRequirements` functions should be renamed. 

I think functions should generally be verbs. @imnasnainaec what do you think of `meetsUsernameRequirements`?
</blockquote></details>

Done.
___
*[src/components/Login/RegisterPage/RegisterComponent.tsx, line 115 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1308#-MhYVb7E4WVLpzO59dbn:-Mhtgfyt2q8uFrBHqc9w:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/c685ffc64ee0651c75aa14a1d6de48e97c68ebf9/src/components/Login/RegisterPage/RegisterComponent.tsx#L115)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This `: boolean` can be removed as well.
</blockquote></details>

Done.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1308)* status: all files reviewed, 3 unresolved discussions (waiting on @johnthagen)

**Review by johnthagen — APPROVED** [review]
> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1308)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JacobHaimes)

**Pull request merged**
