### PR TITLE
Add Word.note field

### LINKED ISSUE #755: Add Notes field to Word
### Backend

- [x] Extend `Word` `Model` to support saving a `string` note field in addition to the note's language (bcp-47 code `string`).
- [ ] Round trip the note content with the Lift import & export.

### Frontend

- [x] Extend `Word` and `ReviewEntriewWord` to support a note field.
- [x] Do not expose selecting the note's language, instead default to the project's current analysis language.
- [x] In Review Entries, add a note column, where notes can be added, viewed, edited.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #755

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/756)

### CODE REVIEW

**Comment by johnthagen** [comment]
@imnasnainaec Is there a way if a Note is entered that we give it more space? Either vertically or horizontally?

review

**Comment by johnthagen** [comment]
@imnasnainaec When I add a note, confirm and then edit again, the previous note contents are not shown.

step1

step2

**Comment by imnasnainaec** [comment]
> @imnasnainaec Is there a way if a Note is entered that we give it more space? Either vertically or horizontally?

@johnthagen Just pushed a fix for that.

**Comment by imnasnainaec** [comment]
> @imnasnainaec When I add a note, confirm and then edit again, the previous note contents are not shown.

@johnthagen Curious. I'm not experiencing the same behavior.

**Comment by johnthagen** [comment]
> Just pushed a fix for that.

Confirmed fixed.

**Comment by johnthagen** [comment]
> Curious. I'm not experiencing the same behavior.

I am no longer able to reproduce it either.

**Comment by johnthagen** [comment]
___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx, line 15 at r8](https://reviewable.io/reviews/sillsdev/thecombine/756#-MJDuEUV6b7VGs7X7-7Z:-MJDuEUV6b7VGs7X7-7_:b-g6yt0e) ([raw file](https://github.com/sillsdev/thecombine/blob/0df3cd00175aaa2be2ed183eec1acb711f328be8/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx#L15)):*
> ```XML
> enum SortStyle {
>   // vernacular, noteText: neither have a customSort defined,
>   // so there is currently no way to trigger their SortStyles.
> ```

Is this the column sort option in the table? I am able to click the arrow next to Note and have it sort. Should this not work?

**Comment by johnthagen** [comment]
___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx, line 11 at r8](https://reviewable.io/reviews/sillsdev/thecombine/756#-MJDutaTBL0QvAAZdQsR:-MJDutaTBL0QvAAZdQsS:b-77tcap) ([raw file](https://github.com/sillsdev/thecombine/blob/0df3cd00175aaa2be2ed183eec1acb711f328be8/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx#L11)):*
> ```XML
> import SenseCell from "./SenseCell";
> import { Column } from "material-table";
> import PronunciationsCell from "./PronunciationsCell";
> ```

There are a lot of uses of `: any` in this file. Can any of them be converted to a stronger type?

**Comment by johnthagen** [comment]
___
*[src/types/word.tsx, line 39 at r8](https://reviewable.io/reviews/sillsdev/thecombine/756#-MJDvZJO3ymD0nWScJ-A:-MJDvZJO3ymD0nWScJ-B:bnx3x77) ([raw file](https://github.com/sillsdev/thecombine/blob/0df3cd00175aaa2be2ed183eec1acb711f328be8/src/types/word.tsx#L39)):*
> ```XML
> 
> export function makeNote(text?: string, lang?: string): Note {
>   return { text: text ? text : "", language: lang ? lang : "en" };
> ```

Is it safe for this to default to `"en"`? Shouldn't this default to the Project's analysis language or `""`?

**Comment by johnthagen** [comment]
___
*[src/types/word.tsx, line 39 at r8](https://reviewable.io/reviews/sillsdev/thecombine/756#-MJDvZJO3ymD0nWScJ-A:-MJDvmfxCups-GpDo0cR:byty8yn) ([raw file](https://github.com/sillsdev/thecombine/blob/0df3cd00175aaa2be2ed183eec1acb711f328be8/src/types/word.tsx#L39)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Is it safe for this to default to `"en"`? Shouldn't this default to the Project's analysis language or `""`?
</blockquote></details>

(I could be mistaken about the purpose/function of this function).

**Comment by johnthagen** [comment]
___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx, line 15 at r8](https://reviewable.io/reviews/sillsdev/thecombine/756#-MJDuEUV6b7VGs7X7-7Z:-MJDvsfo9SpCwtSCYqeP:bxoca9c) ([raw file](https://github.com/sillsdev/thecombine/blob/0df3cd00175aaa2be2ed183eec1acb711f328be8/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx#L15)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

They both use the default sort. 
</blockquote></details>

Ah, this is for a "custom sort". Got it.

**Review by johnthagen — COMMENTED** [review]
> Reviewed 3 of 19 files at r7, 19 of 19 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/756)* status: all files reviewed, 2 unresolved discussions (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/756)* status: 20 of 22 files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx, line 11 at r8](https://reviewable.io/reviews/sillsdev/thecombine/756#-MJDutaTBL0QvAAZdQsR:-MJDxw4S90hnX8dJeFxq:bubkiz5) ([raw file](https://github.com/sillsdev/thecombine/blob/0df3cd00175aaa2be2ed183eec1acb711f328be8/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx#L11)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

There are a lot of uses of `: any` in this file. Can any of them be converted to a stronger type?
</blockquote></details>

Improved
___
*[src/types/word.tsx, line 39 at r8](https://reviewable.io/reviews/sillsdev/thecombine/756#-MJDvZJO3ymD0nWScJ-A:-MJDyVP509-dwXb2QX2D:bev534z) ([raw file](https://github.com/sillsdev/thecombine/blob/0df3cd00175aaa2be2ed183eec1acb711f328be8/src/types/word.tsx#L39)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

(I could be mistaken about the purpose/function of this function).
</blockquote></details>

For the bare type definitions, "" is best.

**Review by johnthagen — COMMENTED** [review]
> Reviewed 2 of 2 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/756)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jasonleenaylor — COMMENTED** [review]
At first glance it looks good (might give it a more thorough look_. Should we handle the Lift Import/Export in a second PR?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/756#-:-MJE5B1YBcXrGeMKN2sI:b-29xnd1)* status: 16 of 22 files reviewed, all discussions resolved (waiting on @johnthagen)

**Review by jasonleenaylor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/756)* status: 16 of 22 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @johnthagen)

___
*[Backend/Models/Word.cs, line 187 at r11](https://reviewable.io/reviews/sillsdev/thecombine/756#-MJE6zS00mlKPbB8kTi3:-MJE6zS00mlKPbB8kTi4:b-cizeft) ([raw file](https://github.com/sillsdev/thecombine/blob/01ce5e79c197e1e02b0b54d61cd8cbaf91d42468/Backend/Models/Word.cs#L187)):*
> ```
> The language used the note is written in.
> ```
I'd probably write it as:
The bcp-47 code for the language the note is written in.
___
*[src/resources/translations.json, line 439 at r11](https://reviewable.io/reviews/sillsdev/thecombine/756#-MJE86sGAH2plu-ZbFJP:-MJE86sHAEOlLRdCGQ6z:b-d5tj3u) ([raw file](https://github.com/sillsdev/thecombine/blob/01ce5e79c197e1e02b0b54d61cd8cbaf91d42468/src/resources/translations.json#L439)):*
> ```
> noNot
> ```
Changing ids isn't kind to Crowdin translators, so we should avoid it in the future. Now is probably a good time for this though. :)

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 8 of 9 files at r12, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/756)* status: all files reviewed, 2 unresolved discussions (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/756)* status: 21 of 23 files reviewed, all discussions resolved (waiting on @jasonleenaylor and @johnthagen)

___
*[Backend/Models/Word.cs, line 187 at r11](https://reviewable.io/reviews/sillsdev/thecombine/756#-MJE6zS00mlKPbB8kTi3:-MJF6wH9-z0uag25-dnt:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/01ce5e79c197e1e02b0b54d61cd8cbaf91d42468/Backend/Models/Word.cs#L187)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> The language used the note is written in.
> ```
I'd probably write it as:
The bcp-47 code for the language the note is written in.
</blockquote></details>

Done.
___
*[src/resources/translations.json, line 439 at r11](https://reviewable.io/reviews/sillsdev/thecombine/756#-MJE86sGAH2plu-ZbFJP:-MJF4ylD4YMLmIqRwu9i:bk9pzdd) ([raw file](https://github.com/sillsdev/thecombine/blob/01ce5e79c197e1e02b0b54d61cd8cbaf91d42468/src/resources/translations.json#L439)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> noNot
> ```
Changing ids isn't kind to Crowdin translators, so we should avoid it in the future. Now is probably a good time for this though. :)
</blockquote></details>

Affirmative.

**Review by johnthagen — COMMENTED** [review]
> Reviewed 2 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/756)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by johnthagen** [comment]
@jasonleenaylor 

> Should we handle the Lift Import/Export in a second PR?

I looked into `LiftMerger.FinishEntry` and when I use the example you sent us, the `entry.Notes` field wasn't filled in. I'm not super familiar with the SIL Lift parsing stack, so I think you'll probably need to take a look at this one. I would enjoy reviewing what you do to learn from though.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 3 of 3 files at r15.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/756)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 19 files at r7, 10 of 19 files at r8, 1 of 2 files at r10, 1 of 1 files at r11, 7 of 9 files at r12, 1 of 1 files at r13, 2 of 2 files at r14, 2 of 3 files at r15, 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/756)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
