### PR TITLE
Enable eslint-plugin-import

### LINKED ISSUE #1364: Automatically sort Typescript imports
Consider using `eslint --fix` to automatically sort Typescript imports to reduce the burden of this task for developers.

- https://eslint.org/docs/rules/sort-imports

### PR DESCRIPTION
**Pull request by johnthagen**
Closes #1364

To automatically group and sort TS imports:

```
npm run lint:fix-layout
```

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1434)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 8 files at r4, 57 of 59 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1434)* status: 64 of 65 files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[src/components/SiteSettings/SiteSettingsComponent.tsx, line 6 at r7](https://reviewable.io/reviews/sillsdev/thecombine/1434#-MnCOE8W04UQ6B0S38wQ:-MnCOE8W04UQ6B0S38wR:btt24dw) ([raw file](https://github.com/sillsdev/thecombine/blob/a042a9390cbd50ef4bb72fadf336773e78cf16ac/src/components/SiteSettings/SiteSettingsComponent.tsx#L6)):*
> ```
> import UserManagement from "components/SiteSettings//UserManagement/UserManagement";
> ```
There's a double-/ here that shouldn't be (due to no fault of your own).

**Comment by johnthagen** [comment]
___
*[src/components/SiteSettings/SiteSettingsComponent.tsx, line 6 at r7](https://reviewable.io/reviews/sillsdev/thecombine/1434#-MnCOE8W04UQ6B0S38wQ:-MnCScUyBRfJV3Qd1UX2:bgyl7aw) ([raw file](https://github.com/sillsdev/thecombine/blob/a042a9390cbd50ef4bb72fadf336773e78cf16ac/src/components/SiteSettings/SiteSettingsComponent.tsx#L6)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> import UserManagement from "components/SiteSettings//UserManagement/UserManagement";
> ```
There's a double-/ here that shouldn't be (due to no fault of your own).
</blockquote></details>

Done.

I'm a little surprised TS didn't complain about that.

**Review by johnthagen — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 4 of 8 files at r4, 1 of 2 files at r5, 57 of 59 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1434)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Review by imnasnainaec — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1434)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Pull request merged**
