### PR TITLE
Port CharInv goal to use redux-toolkit 

### PR DESCRIPTION
**Pull request by imnasnainaec**
Part of https://github.com/sillsdev/TheCombine/issues/1953

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2749)

### CODE REVIEW

**Review by jmgrady — CHANGES_REQUESTED** [review]
> Reviewed 4 of 11 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2749)* status: 9 of 12 files reviewed, 4 unresolved discussions (waiting on @imnasnainaec)

___
*[`src/goals/CharacterInventory/Redux/CharacterInventoryActions.ts` line 161 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2749#-NieYKe0ChQ4WEv91TMa:-NieYKe0ChQ4WEv91TMb:bbcom79) ([raw file](https://github.com/sillsdev/TheCombine/blob/a666aef5af51b46c6acf823235ef6ec8a0792a0c/src/goals/CharacterInventory/Redux/CharacterInventoryActions.ts#L161)):*
> ```XML
>     console.error(`countOccurrences expects length 1 char, but got: ${char}`);
>   }
>   let count = 0;
> ```

This adds the test to verify that the "character" is a single character but does nothing to alert the user that there is a problem.  Presumably this was added because there have been problems with incorrect `char` inputs.  Can that be prevented?
___
*[`src/goals/CharacterInventory/Redux/CharacterInventoryActions.ts` line 239 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2749#-NieZbt8ETj9CtJh_-7U:-NieZbt8ETj9CtJh_-7V:b-8tv86s) ([raw file](https://github.com/sillsdev/TheCombine/blob/a666aef5af51b46c6acf823235ef6ec8a0792a0c/src/goals/CharacterInventory/Redux/CharacterInventoryActions.ts#L239)):*
> ```XML
>   project.rejectedCharacters = state.characterInventoryState.rejectedCharacters;
>   return project;
> }
> ```

This would be cleaner as a `dispatch` to the reducer for the `currentProjectState` with the `validCharacters` and `rejectedCharacters` as the payload.  For one, there would be no need to make a copy of the project when using the `redux-toolkit`.



_Code quote:_
```XML
function updateCurrentProject(state: StoreState): Project {
  const project = { ...state.currentProjectState.project };
  project.validCharacters = state.characterInventoryState.validCharacters;
  project.rejectedCharacters = state.characterInventoryState.rejectedCharacters;
  return project;
}
```
___
*[`src/goals/CharacterInventory/Redux/CharacterInventoryReducer.ts` line 57 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2749#-NiemEOuDuaMQVJbKubO:-NiemEOuDuaMQVJbKubP:b-v85k4l) ([raw file](https://github.com/sillsdev/TheCombine/blob/a666aef5af51b46c6acf823235ef6ec8a0792a0c/src/goals/CharacterInventory/Redux/CharacterInventoryReducer.ts#L57)):*
> ```XML
>       }
>     },
>     resetAction: () => defaultState,
> ```

This is too easy to confuse with the global `reset` action.  The name should be more specific, such as `clearCharInventory` or `resetCharInventory`.  Same goes for the `reset()` function in `CharacterInventoryActions.ts`



_Code quote:_
```XML
resetAction: () => defaultState,
```
___
*[`src/goals/CharacterInventory/Redux/CharacterInventoryReducer.ts` line 67 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2749#-Nif7T3I9nRf-bvlslkc:-Nif7T3J4cen6v4f8KjS:bks6izb) ([raw file](https://github.com/sillsdev/TheCombine/blob/a666aef5af51b46c6acf823235ef6ec8a0792a0c/src/goals/CharacterInventory/Redux/CharacterInventoryReducer.ts#L67)):*
> ```XML
>     },
>     setRejectedCharactersAction: (state, action) => {
>       state.rejectedCharacters = [...new Set(action.payload as string)];
> ```

I do not believe `as string` is necessary.  I added the following to `setValidCharactersAction` which uses the same construct:

```
const validCharArray = [...new Set(action.payload)];
console.log(`payload: ${JSON.stringify(validCharArray, null, 2)}`);
const validCharSpread = [...new Set(action.payload as string)];
console.log(
   `payload as string: ${JSON.stringify(validCharSpread, null, 2)}`
);
```
and the output is the same.  (The structures are the same in the debugger, too).



_Code quote:_
```XML
      state.rejectedCharacters = [...new Set(action.payload as string)];
```

**Review by jmgrady — COMMENTED** [review]
> Reviewed 3 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2749)* status: all files reviewed, 7 unresolved discussions (waiting on @imnasnainaec)

___
*[`src/goals/CharacterInventory/Redux/tests/CharacterInventoryActions.test.tsx` line 149 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2749#-NifMWcB-BHZHSDByh3z:-NifMWcB-BHZHSDByh4-:b-grtlf3) ([raw file](https://github.com/sillsdev/TheCombine/blob/a666aef5af51b46c6acf823235ef6ec8a0792a0c/src/goals/CharacterInventory/Redux/tests/CharacterInventoryActions.test.tsx#L149)):*
> ```XML
>       await store.dispatch(fetchWords());
>       const { allWords } = store.getState().characterInventoryState;
>       expect(allWords).toHaveLength(words.length);
> ```

Why not verify that the right 2 words were fetched?



_Code quote:_
```XML
      expect(allWords).toHaveLength(words.length);
```
___
*[`src/goals/CharacterInventory/Redux/tests/CharacterInventoryActions.test.tsx` line 164 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2749#-NifN4vB55UEAlK23XRO:-NifN4vB55UEAlK23XRP:b-tjtymx) ([raw file](https://github.com/sillsdev/TheCombine/blob/a666aef5af51b46c6acf823235ef6ec8a0792a0c/src/goals/CharacterInventory/Redux/tests/CharacterInventoryActions.test.tsx#L164)):*
> ```XML
>       await store.dispatch(getAllCharacters());
>       const { characterSet } = store.getState().characterInventoryState;
>       expect(characterSet).toHaveLength(9);
> ```

As in `fetchWords` why not check that the correct character set was created?



_Code quote:_
```XML
      expect(characterSet).toHaveLength(9);
```
___
*[`src/goals/CharacterInventory/Redux/tests/CharacterInventoryActions.test.tsx` line 187 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2749#-NifNkepBphQEGBSKnTX:-NifNkepBphQEGBSKnTY:byfjlom) ([raw file](https://github.com/sillsdev/TheCombine/blob/a666aef5af51b46c6acf823235ef6ec8a0792a0c/src/goals/CharacterInventory/Redux/tests/CharacterInventoryActions.test.tsx#L187)):*
> ```XML
>       expect(state.characterSet).toHaveLength(mockWord.vernacular.length);
>       expect(state.rejectedCharacters).toHaveLength(rejectedCharacters.length);
>       expect(state.validCharacters).toHaveLength(validCharacters.length);
> ```

... and here - check values rather than just length.



_Code quote:_
```XML
      expect(state.allWords).toHaveLength(1);
      expect(state.characterSet).toHaveLength(mockWord.vernacular.length);
      expect(state.rejectedCharacters).toHaveLength(rejectedCharacters.length);
      expect(state.validCharacters).toHaveLength(validCharacters.length);
```

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2749)* status: all files reviewed, 7 unresolved discussions (waiting on @imnasnainaec)

___
*[`src/goals/CharacterInventory/Redux/CharacterInventoryReducer.ts` line 57 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2749#-NiemEOuDuaMQVJbKubO:-NijCH9F2puthiZHWZLa:b9dwn5o) ([raw file](https://github.com/sillsdev/TheCombine/blob/a666aef5af51b46c6acf823235ef6ec8a0792a0c/src/goals/CharacterInventory/Redux/CharacterInventoryReducer.ts#L57)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

This is too easy to confuse with the global `reset` action.  The name should be more specific, such as `clearCharInventory` or `resetCharInventory`.  Same goes for the `reset()` function in `CharacterInventoryActions.ts`
</blockquote></details>

In addition, this is only called when the component unmounts.  This suggests to me that `redux` is not the correct technology for this problem.  The `useState` (or `useContext` if the info needs to be propagated to child elements) should be used here instead.

This does not need to be resolved in this PR.  I will create an issue for it where we can track our decision whether or not to change it.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2749)* status: 8 of 13 files reviewed, 3 unresolved discussions (waiting on @jmgrady)

___
*[`src/goals/CharacterInventory/Redux/CharacterInventoryActions.ts` line 161 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2749#-NieYKe0ChQ4WEv91TMa:-NijSiAJ05I7h22CzM1D:by6e3fj) ([raw file](https://github.com/sillsdev/TheCombine/blob/a666aef5af51b46c6acf823235ef6ec8a0792a0c/src/goals/CharacterInventory/Redux/CharacterInventoryActions.ts#L161)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

This adds the test to verify that the "character" is a single character but does nothing to alert the user that there is a problem.  Presumably this was added because there have been problems with incorrect `char` inputs.  Can that be prevented?
</blockquote></details>

It's more a safe-guard against future changes. This function shouldn't be directly accessible from user-input so I wasn't worried about user feedback.
___
*[`src/goals/CharacterInventory/Redux/CharacterInventoryActions.ts` line 239 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2749#-NieZbt8ETj9CtJh_-7U:-NijT802BAwHSbsmhq0n:b8lf9xj) ([raw file](https://github.com/sillsdev/TheCombine/blob/a666aef5af51b46c6acf823235ef6ec8a0792a0c/src/goals/CharacterInventory/Redux/CharacterInventoryActions.ts#L239)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

This would be cleaner as a `dispatch` to the reducer for the `currentProjectState` with the `validCharacters` and `rejectedCharacters` as the payload.  For one, there would be no need to make a copy of the project when using the `redux-toolkit`.
</blockquote></details>

The result of this is passed to a generic update-project action and uses the project in `state.currentProjectState` that is required anyway for `getChanges`. Adding a project action specific to this scenario requires introducing char-inv types to the project redux.
___
*[`src/goals/CharacterInventory/Redux/CharacterInventoryReducer.ts` line 57 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2749#-NiemEOuDuaMQVJbKubO:-NijTjm77jEp31YnMGnZ:bwx0xmf) ([raw file](https://github.com/sillsdev/TheCombine/blob/a666aef5af51b46c6acf823235ef6ec8a0792a0c/src/goals/CharacterInventory/Redux/CharacterInventoryReducer.ts#L57)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

In addition, this is only called when the component unmounts.  This suggests to me that `redux` is not the correct technology for this problem.  The `useState` (or `useContext` if the info needs to be propagated to child elements) should be used here instead.

This does not need to be resolved in this PR.  I will create an issue for it where we can track our decision whether or not to change it.
</blockquote></details>

Changed `reset()` to `resetCharInv()`.
___
*[`src/goals/CharacterInventory/Redux/CharacterInventoryReducer.ts` line 67 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/2749#-Nif7T3I9nRf-bvlslkc:-NijTpr_1SA-q4apMScT:bd4uxr7) ([raw file](https://github.com/sillsdev/TheCombine/blob/a666aef5af51b46c6acf823235ef6ec8a0792a0c/src/goals/CharacterInventory/Redux/CharacterInventoryReducer.ts#L67)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

I do not believe `as string` is necessary.  I added the following to `setValidCharactersAction` which uses the same construct:

```
const validCharArray = [...new Set(action.payload)];
console.log(`payload: ${JSON.stringify(validCharArray, null, 2)}`);
const validCharSpread = [...new Set(action.payload as string)];
console.log(
   `payload as string: ${JSON.stringify(validCharSpread, null, 2)}`
);
```
and the output is the same.  (The structures are the same in the debugger, too).
</blockquote></details>

Having just `state.rejectedCharacters = [...new Set(action.payload)];` gives TS error `Type 'unknown[]' is not assignable to type 'string[]'.` But I did change it from `as string` to `as string[]`. The former satisfied TS linting but wasn't correct.

**Review by jmgrady — APPROVED** [review]
> Reviewed 5 of 5 files at r3, 1 of 1 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2749)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
