### PR TITLE
Fix uncalled/impotent test functions

### PR DESCRIPTION
**Pull request by imnasnainaec**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2945)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2945)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[`src/components/DataEntry/DataEntryTable/tests/index.test.tsx` line 154 at r1](https://reviewable.io/reviews/sillsdev/TheCombine/2945#-NrHsnLa8NDx89TvBbu5:-NrHsnLa8NDx89TvBbu6:b44dn77) ([raw file](https://github.com/sillsdev/TheCombine/blob/854c085713bdfc853bcfb571157d60dd877d0b0d/src/components/DataEntry/DataEntryTable/tests/index.test.tsx#L154)):*
> ```XML
>       expect(mockCreateWord).not.toHaveBeenCalled();
>       testHandle = testRenderer.root.findByType(NewEntry);
>       expect(testHandle).not.toBeNull;
> ```

Why is this not useful?



_Code quote:_
```XML
expect(testHandle).not.toBeNull;
```

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2945)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

___
*[`src/components/DataEntry/DataEntryTable/tests/index.test.tsx` line 154 at r1](https://reviewable.io/reviews/sillsdev/TheCombine/2945#-NrHsnLa8NDx89TvBbu5:-NrKyPbEDGMrREYTn5tf:b-lb8s5w) ([raw file](https://github.com/sillsdev/TheCombine/blob/854c085713bdfc853bcfb571157d60dd877d0b0d/src/components/DataEntry/DataEntryTable/tests/index.test.tsx#L154)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Why is this not useful?
</blockquote></details>

`findByType()` above will just throw an error if one isn't found, and `toBeNull` needed `()`, and we have tests below that will fail if`testHandle` is not what it's supposed to be.

**Comment by jasonleenaylor** [comment]
*[`src/components/DataEntry/DataEntryTable/tests/index.test.tsx` line 154 at r1](https://reviewable.io/reviews/sillsdev/TheCombine/2945#-NrHsnLa8NDx89TvBbu5:-NrMAWnA9i7Znef2XUDE:b-8fx2u7) ([raw file](https://github.com/sillsdev/TheCombine/blob/854c085713bdfc853bcfb571157d60dd877d0b0d/src/components/DataEntry/DataEntryTable/tests/index.test.tsx#L154)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`findByType()` above will just throw an error if one isn't found, and `toBeNull` needed `()`, and we have tests below that will fail if`testHandle` is not what it's supposed to be.
</blockquote></details>

:+1:

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2945)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
