### PR TITLE
Add a workshop schedule option to the project settings page

### PR DESCRIPTION
**Pull request by fuencui**
Add a workshop schedule component to the project settings page that allows users to set the days for the workshop and stores the information in the project settings data. Additionally, provide a calendar that highlights the selected days

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/1987)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 4 of 9 files at r1, 2 of 2 files at r2, 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/1987)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @fuencui)

___
*[`public/locales/en/translation.json` line 192 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/1987#-NSHz-pvAC8aQCAhkye6:-NSHz-pw7y7L_Z01Wp_h:b-g3d9jt) ([raw file](https://github.com/sillsdev/TheCombine/blob/77df7337cfd35cde9709ae87c2ff2abca1ee82e7/public/locales/en/translation.json#L192)):*
> ```JSON
>       "editDays": "Flexibly adjust the workshop schedule",
>       "removeDays": "Remove all days from workshop",
>       "removeAll": "Are you sure you want to remove all the dates",
> ```

I think this might need a '?'
___
*[`src/components/ProjectSettings/ProjectSchedule/DateScheduleEdit.tsx` line 23 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/1987#-NSI-LTmBoyZuIXxQpF1:-NSI-LTmBoyZuIXxQpF2:b-ihm5sm) ([raw file](https://github.com/sillsdev/TheCombine/blob/77df7337cfd35cde9709ae87c2ff2abca1ee82e7/src/components/ProjectSettings/ProjectSchedule/DateScheduleEdit.tsx#L23)):*
> ```XML
> export default function DateScheduleEdit(Props: DateScheduleEditProps) {
>   const [projectSchedule, setProjectSchedule] = useState<Date[]>();
>   // The value is not being used, but it helps trigger the render
> ```

Hmm, I think I see what you are doing here. I wonder why setting the projectSchedule was not enough?



_Code quote:_
```XML
  // The value is not being used, but it helps trigger the render
  const [value, setValue] = useState<Dayjs | null>();
```

**Review by fuencui — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/1987)* status: 6 of 11 files reviewed, 2 unresolved discussions (waiting on @jasonleenaylor)

___
*[`public/locales/en/translation.json` line 192 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/1987#-NSHz-pvAC8aQCAhkye6:-NSgFD6y6vildswAFReq:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/77df7337cfd35cde9709ae87c2ff2abca1ee82e7/public/locales/en/translation.json#L192)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

I think this might need a '?'
</blockquote></details>

Done.

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 1 of 5 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/1987)* status: all files reviewed, 1 unresolved discussion (waiting on @fuencui)

___
*[`public/locales/en/translation.json` line 192 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/1987#-NSHz-pvAC8aQCAhkye6:-NShFKye-dmYwsJ_eELA:bo48bxe) ([raw file](https://github.com/sillsdev/TheCombine/blob/77df7337cfd35cde9709ae87c2ff2abca1ee82e7/public/locales/en/translation.json#L192)):*
<details><summary><i>Previously, fuencui (fuencui) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't know if it is the reviewable diff, but it looks like there is a space between the 's' and the '?' if there is please remove it.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/1987)* status: all files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor)

___
*[`public/locales/en/translation.json` line 192 at r6](https://reviewable.io/reviews/sillsdev/TheCombine/1987#-NSwKrot3LRmPQg6teCD:-NSwKrou4GlSqppW6BCa:b293rjf) ([raw file](https://github.com/sillsdev/TheCombine/blob/97f571271131b8f2a313dde5dfa5cfd3a8f774cb/public/locales/en/translation.json#L192)):*
> ```JSON
>       "editDays": "Flexibly adjust the workshop schedule",
>       "removeDays": "Remove all days from workshop",
>       "removeAll": "Are you sure you want to remove all the dates ?",
> ```

Please remove the space before the ?.



_Code quote:_
```JSON
dates ?"
```

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/1987)* status: all files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor)

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/1987)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @fuencui)

**Pull request closed without merging**
