### PR TITLE
Maintenance scripts to manage project owner permissions

### PR DESCRIPTION
**Pull request by jmgrady**
In order to support the changes to be made with PRs #1253 and #1257, this PR updates the role, `combine_maintenance` as follows:
- add `set_proj_owner.py` script which iterates through each project to set a project owner.
   - If there is a project owner, it does nothing.
   - If there is a single administrator (has permission `Permission.DeleteEditSettingsAndUsers`) the administrator is made the project owner.
   - If there are multiple administrators, the user is prompted to choose an owner from the current administrators.
- update `add_user_to_proj.py` so that if the user is already a member of the project, the current permissions are merged with the requested (admin or basic user) permissions.  If the result does not show any change, then the document in the UserRolesCollection is not updated.  This will also prevent the ProjectOwner permission from being lost if the requested user is already a member of the project.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1259)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1259)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[deploy/roles/combine_maintenance/files/add_user_to_proj.py, line 104 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1259#-Mf3pgEr6xv17DF_vT3M:-Mf3pgEr6xv17DF_vT3N:bmy5w25) ([raw file](https://github.com/sillsdev/thecombine/blob/73aa32bcaca75f0a9cbb11a21962ad5ef3cc8601/deploy/roles/combine_maintenance/files/add_user_to_proj.py#L104)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>         user_role_id = result[0]["projectRoles"][proj_id]
>         select_role = f'{{ _id: ObjectId("{user_role_id}")}}'
>         # Look up the current permissions
>         user_role = combine.db_query("UserRolesCollection", select_role)
>         if args.verbose:
>             print(f"UserRole ID: {user_role_id}")
> ```
</details>

It seems odd to have a query between when `user_role_id` is defined and when it's printed.
___
*[deploy/roles/combine_maintenance/files/add_user_to_proj.py, line 132 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1259#-Mf3qar29_KyN8EwBtDQ:-Mf3qar29_KyN8EwBtDR:b-zhxt79) ([raw file](https://github.com/sillsdev/thecombine/blob/73aa32bcaca75f0a9cbb11a21962ad5ef3cc8601/deploy/roles/combine_maintenance/files/add_user_to_proj.py#L132)):*
> ```
>             if add_role_result is None:
>                 print(f"Could not add new role to {args.user}.", file=sys.stderr)
>                 sys.exit(1)
> ```
Might we want an analogous check in the update case above?
___
*[deploy/roles/combine_maintenance/files/add_user_to_proj.py, line 142 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1259#-Mf3p73y1MlM7EKBPvwY:-Mf3p73z4CTUYYAvNS7f:b-lp06a7) ([raw file](https://github.com/sillsdev/thecombine/blob/73aa32bcaca75f0a9cbb11a21962ad5ef3cc8601/deploy/roles/combine_maintenance/files/add_user_to_proj.py#L142)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     else:
>         print(
>             f"Too many documents in UserRolesCollection for User {args.user}"
>             f" in Project {args.project}"
>         )
> ```
</details>

I don't think there's any reason for a user to have multiple roles for a single project, but can you run a query to check that that isn't currently the case?
___
*[deploy/roles/combine_maintenance/files/combine_app.py, line 96 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1259#-Mf3uvyZB4oMqe9Gn4zT:-Mf3uvyZB4oMqe9Gn4zU:b-ffxnyo) ([raw file](https://github.com/sillsdev/thecombine/blob/73aa32bcaca75f0a9cbb11a21962ad5ef3cc8601/deploy/roles/combine_maintenance/files/combine_app.py#L96)):*
> ```
> Optional[Dict[str, Any]]
> ```
It's curious to me that most uses of the returned value from this function (aside from `None` checks) expect a different type and thus require `# type: ignore`.
___
*[deploy/roles/combine_maintenance/files/combine_app.py, line 125 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1259#-Mf4-7py2iTSWCUgrxTd:-Mf4-7pzCKfiFTahcifk:b-j5h3r6) ([raw file](https://github.com/sillsdev/thecombine/blob/73aa32bcaca75f0a9cbb11a21962ad5ef3cc8601/deploy/roles/combine_maintenance/files/combine_app.py#L125)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>         db_results = self.exec(
>             "database", ["/usr/bin/mongo", "--quiet", "CombineDatabase", "--eval", cmd]
>         )
>         result_str = self.object_id_to_str(db_results.stdout)
>         if result_str != "":
>             result_array: List[Dict[str, Any]] = json.loads(result_str)
>             return result_array
>         return []
> ```
</details>

Might it work (perhaps with type coercion) to use `this.db_cmd` for the bulk of `db_query`?
___
*[deploy/roles/combine_maintenance/files/set_proj_owner.py, line 56 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1259#-Mf3r4898xfYqVhwJn9v:-Mf3r4898xfYqVhwJn9w:bdm5vxt) ([raw file](https://github.com/sillsdev/thecombine/blob/73aa32bcaca75f0a9cbb11a21962ad5ef3cc8601/deploy/roles/combine_maintenance/files/set_proj_owner.py#L56)):*
> ```Python
>             print(f"Checking project: {proj['name']} ({proj['_id']})")
>         # get the admin user roles (roles that have Permission.DeleteEditSettingsAndUsers set)
>         proj_id = proj["_id"]
> ```

Why not define `proj_id = proj["_id"]` right off the bat so it can be used in the print statement?
___
*[deploy/roles/combine_maintenance/files/set_proj_owner.py, line 62 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1259#-Mf3qrsR2kDnpM8rYbWD:-Mf3qrsR2kDnpM8rYbWE:b-41yi01) ([raw file](https://github.com/sillsdev/thecombine/blob/73aa32bcaca75f0a9cbb11a21962ad5ef3cc8601/deploy/roles/combine_maintenance/files/set_proj_owner.py#L62)):*
> ```
>         # get the admin user roles (roles that have Permission.DeleteEditSettingsAndUsers set)
> ...
>             # there is only one admin role, set as selected user role
> ```
Capital-initial comments?

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1259)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[deploy/roles/combine_maintenance/files/add_user_to_proj.py, line 104 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1259#-Mf3pgEr6xv17DF_vT3M:-Mf40tdD7QK5dj75lB5i:b-wcb1b7) ([raw file](https://github.com/sillsdev/thecombine/blob/73aa32bcaca75f0a9cbb11a21962ad5ef3cc8601/deploy/roles/combine_maintenance/files/add_user_to_proj.py#L104)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>         user_role_id = result[0]["projectRoles"][proj_id]
>         select_role = f'{{ _id: ObjectId("{user_role_id}")}}'
>         # Look up the current permissions
>         user_role = combine.db_query("UserRolesCollection", select_role)
>         if args.verbose:
>             print(f"UserRole ID: {user_role_id}")
> ```
It seems odd to have a query between when `user_role_id` is defined and when it's printed.
</blockquote></details>

Actually, the print statement was there from initial debugging (a place to put a breakpoint).  I don't think it's all that useful and will remove it.
___
*[deploy/roles/combine_maintenance/files/add_user_to_proj.py, line 132 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1259#-Mf3qar29_KyN8EwBtDQ:-Mf42lLw9PUPABPADMEP:b-brmgad) ([raw file](https://github.com/sillsdev/thecombine/blob/73aa32bcaca75f0a9cbb11a21962ad5ef3cc8601/deploy/roles/combine_maintenance/files/add_user_to_proj.py#L132)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>             if add_role_result is None:
>                 print(f"Could not add new role to {args.user}.", file=sys.stderr)
>                 sys.exit(1)
> ```
Might we want an analogous check in the update case above?
</blockquote></details>

Done. Also removed the superfluous `elif` (following line) since the `if` path exits the program.
___
*[deploy/roles/combine_maintenance/files/add_user_to_proj.py, line 142 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1259#-Mf3p73y1MlM7EKBPvwY:-Mf426xn29ETCm7vqHBG:b-hyu916) ([raw file](https://github.com/sillsdev/thecombine/blob/73aa32bcaca75f0a9cbb11a21962ad5ef3cc8601/deploy/roles/combine_maintenance/files/add_user_to_proj.py#L142)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>     else:
>         print(
>             f"Too many documents in UserRolesCollection for User {args.user}"
>             f" in Project {args.project}"
>         )
> ```
I don't think there's any reason for a user to have multiple roles for a single project, but can you run a query to check that that isn't currently the case?
</blockquote></details>

I do not think so either but there is nothing that I can see in the database structure that guarantees it (but I am no expert).  I don't know of any straight-forward query that we can run to confirm that.
___
*[deploy/roles/combine_maintenance/files/combine_app.py, line 96 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1259#-Mf3uvyZB4oMqe9Gn4zT:-Mf43xeo9z2W-_T94aGX:bd3o83s) ([raw file](https://github.com/sillsdev/thecombine/blob/73aa32bcaca75f0a9cbb11a21962ad5ef3cc8601/deploy/roles/combine_maintenance/files/combine_app.py#L96)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> Optional[Dict[str, Any]]
> ```
It's curious to me that most uses of the returned value from this function (aside from `None` checks) expect a different type and thus require `# type: ignore`.
</blockquote></details>

That is part of the reason I added the `db_query()` function.  In order to get a Mongo `find` command to work without iterating over the cursor that is returned, I need to call `toArray()` on the find results.  That means that a list of dictionaries is returned.  By pulling that out separately we can have a known return type and a cleaner api.

I think that there will be a PR in the future to refactor this but that should wait until we create the Kubernetes container to do this since these scripts will not be long-lived.
___
*[deploy/roles/combine_maintenance/files/combine_app.py, line 125 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1259#-Mf4-7py2iTSWCUgrxTd:-Mf46_dE-IUAyzyCFt3f:bynejek) ([raw file](https://github.com/sillsdev/thecombine/blob/73aa32bcaca75f0a9cbb11a21962ad5ef3cc8601/deploy/roles/combine_maintenance/files/combine_app.py#L125)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>         db_results = self.exec(
>             "database", ["/usr/bin/mongo", "--quiet", "CombineDatabase", "--eval", cmd]
>         )
>         result_str = self.object_id_to_str(db_results.stdout)
>         if result_str != "":
>             result_array: List[Dict[str, Any]] = json.loads(result_str)
>             return result_array
>         return []
> ```
Might it work (perhaps with type coercion) to use `this.db_cmd` for the bulk of `db_query`?
</blockquote></details>

I tried it without type coercion and `tox` was very unhappy.  I think the current, small amount of duplicated code is preferable to type coercion.  As I suggested in an earlier comment, I think this could all be improved in the future by expanding the db_xxx interface so that the different database operation types return the expected data structures.
___
*[deploy/roles/combine_maintenance/files/set_proj_owner.py, line 56 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1259#-Mf3r4898xfYqVhwJn9v:-Mf450tW-TYcDZS3iBcU:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/73aa32bcaca75f0a9cbb11a21962ad5ef3cc8601/deploy/roles/combine_maintenance/files/set_proj_owner.py#L56)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Why not define `proj_id = proj["_id"]` right off the bat so it can be used in the print statement?
</blockquote></details>

Done.
___
*[deploy/roles/combine_maintenance/files/set_proj_owner.py, line 62 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1259#-Mf3qrsR2kDnpM8rYbWD:-Mf45Bh_0Iigwb65qqg4:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/73aa32bcaca75f0a9cbb11a21962ad5ef3cc8601/deploy/roles/combine_maintenance/files/set_proj_owner.py#L62)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>         # get the admin user roles (roles that have Permission.DeleteEditSettingsAndUsers set)
> ...
>             # there is only one admin role, set as selected user role
> ```
Capital-initial comments?
</blockquote></details>

Done.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1259)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @imnasnainaec and @jmgrady)

___
*[deploy/roles/combine_maintenance/files/add_user_to_proj.py, line 142 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1259#-Mf3p73y1MlM7EKBPvwY:-Mf4ELxB0iWwrdVSIpkw:b-kx9hw0) ([raw file](https://github.com/sillsdev/thecombine/blob/73aa32bcaca75f0a9cbb11a21962ad5ef3cc8601/deploy/roles/combine_maintenance/files/add_user_to_proj.py#L142)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

I do not think so either but there is nothing that I can see in the database structure that guarantees it (but I am no expert).  I don't know of any straight-forward query that we can run to confirm that.
</blockquote></details>

No worries. We can deal with it if this script reveals that the unexpected has occurred.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1259)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

___
*[deploy/roles/combine_maintenance/files/set_proj_owner.py, line 17 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1259#-Mf4GkRY7uRcRLambCJS:-Mf4GkRY7uRcRLambCJT:bqjtdzj) ([raw file](https://github.com/sillsdev/thecombine/blob/fd40f14e76e4f2dc1f41f3ff74d76e4b7545bad2/deploy/roles/combine_maintenance/files/set_proj_owner.py#L17)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>     already a member and the --admin argument is used, set the permissions to
>     [5,4,3,2,1], otherwise do nothing.
>  3. If the user is not in the project:
>  ...
>      c. set the permissions field in the user role to [5,4,3,2,1] if the
>         --admin argument is used, [3,2,1] otherwise.
> ```
</details>

I think these descriptions need updating.

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1259)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

___
*[deploy/roles/combine_maintenance/files/set_proj_owner.py, line 17 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1259#-Mf4GkRY7uRcRLambCJS:-Mf4JDQc3clZ2MewcAPD:bt70aj6) ([raw file](https://github.com/sillsdev/thecombine/blob/fd40f14e76e4f2dc1f41f3ff74d76e4b7545bad2/deploy/roles/combine_maintenance/files/set_proj_owner.py#L17)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>     already a member and the --admin argument is used, set the permissions to
>     [5,4,3,2,1], otherwise do nothing.
>  3. If the user is not in the project:
>  ...
>      c. set the permissions field in the user role to [5,4,3,2,1] if the
>         --admin argument is used, [3,2,1] otherwise.
> ```
I think these descriptions need updating.
</blockquote></details>

I think I need to configure my editor to disable copy/paste of comments.
Done.
___
*[deploy/roles/combine_maintenance/files/set_proj_owner.py, line 57 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1259#-Mf4GVKQAJ5_MtFOHMoY:-Mf4KF76-nypeynWzWYo:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/fd40f14e76e4f2dc1f41f3ff74d76e4b7545bad2/deploy/roles/combine_maintenance/files/set_proj_owner.py#L57)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`.ProjectOwner` -> `.Owner` here too.
</blockquote></details>

Done.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1259)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[deploy/roles/combine_maintenance/files/add_user_to_proj.py, line 17 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1259#-Mf4Lj289tNcDU2FOV4v:-Mf4Lj293N-T9zK7i5Nr:b-82gynm) ([raw file](https://github.com/sillsdev/thecombine/blob/9700b76e30ff818ff3978611880da11934d530e8/deploy/roles/combine_maintenance/files/add_user_to_proj.py#L17)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>  2. Check to see if the user is already in the project.  If he/she is
>     already a member and the --admin argument is used, set the permissions to
>     [5,4,3,2,1], otherwise do nothing.
>  3. If the user is not in the project:
>      a. create a document in the UserRolesCollection,
>      b. add the new role to the user's document in the UsersCollection
>      c. set the permissions field in the user role to [5,4,3,2,1] if the
>         --admin argument is used, [3,2,1] otherwise.
> ```
</details>

These probably need updating too, as "set to" no longer accurately describes the process.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1259)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1259)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[deploy/roles/combine_maintenance/files/add_user_to_proj.py, line 17 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1259#-Mf4Lj289tNcDU2FOV4v:-Mf4O-1VE1CjT7uipCow:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/9700b76e30ff818ff3978611880da11934d530e8/deploy/roles/combine_maintenance/files/add_user_to_proj.py#L17)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>  2. Check to see if the user is already in the project.  If he/she is
>     already a member and the --admin argument is used, set the permissions to
>     [5,4,3,2,1], otherwise do nothing.
>  3. If the user is not in the project:
>      a. create a document in the UserRolesCollection,
>      b. add the new role to the user's document in the UsersCollection
>      c. set the permissions field in the user role to [5,4,3,2,1] if the
>         --admin argument is used, [3,2,1] otherwise.
> ```
These probably need updating too, as "set to" no longer accurately describes the process.
</blockquote></details>

Done.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1259)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[deploy/roles/combine_maintenance/files/add_user_to_proj.py, line 17 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1259#-Mf4Lj289tNcDU2FOV4v:-Mf4PqoM8AgwfaJpf3DD:b-btd562) ([raw file](https://github.com/sillsdev/thecombine/blob/9700b76e30ff818ff3978611880da11934d530e8/deploy/roles/combine_maintenance/files/add_user_to_proj.py#L17)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

1... 2... 2... 3. :)

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1259)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[deploy/roles/combine_maintenance/files/add_user_to_proj.py, line 17 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1259#-Mf4Lj289tNcDU2FOV4v:-Mf4ZLGNC2qa_PjYZzOX:bm51tw5) ([raw file](https://github.com/sillsdev/thecombine/blob/9700b76e30ff818ff3978611880da11934d530e8/deploy/roles/combine_maintenance/files/add_user_to_proj.py#L17)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

1... 2... 2... 3. :)
</blockquote></details>

Done.  (I think.)

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1259)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Pull request merged**
