### PR TITLE
Functionalize ReviewEntries' CellComponents

### PR DESCRIPTION
**Pull request by imnasnainaec**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/834)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 12 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/834)* status: 12 of 19 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

**Review by jasonleenaylor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/834)* status: 12 of 19 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jasonleenaylor)

___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/DomainCell.tsx, line 21 at r1](https://reviewable.io/reviews/sillsdev/thecombine/834#-MNVZFj_EaSNFFEmR3k7:-MNVZFj_EaSNFFEmR3k8:b-de10x8) ([raw file](https://github.com/sillsdev/thecombine/blob/5143553d963628a7e576127ecb45c00108c0996f/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/DomainCell.tsx#L21)):*
> ```
> So
> ```
I think this is a typo, unless you were abbreviation 'SemanticDomains' to Somains... in which case, it is a bad abbreviation.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/834)* status: 12 of 19 files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/DomainCell.tsx, line 21 at r1](https://reviewable.io/reviews/sillsdev/thecombine/834#-MNVZFj_EaSNFFEmR3k7:-MNV_LkQENs5HGB8_vbQ:bt2vr1b) ([raw file](https://github.com/sillsdev/thecombine/blob/5143553d963628a7e576127ecb45c00108c0996f/src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/DomainCell.tsx#L21)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> So
> ```
I think this is a typo, unless you were abbreviation 'SemanticDomains' to Somains... in which case, it is a bad abbreviation.
</blockquote></details>

Fixed.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 6 of 19 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/834)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
