### PR TITLE
Semantic domain model/type update

### PR DESCRIPTION
**Pull request by imnasnainaec**
One step in #1721, a refactor of how we store, query, and fetch semantic domain information, particularly for Data Entry and Tree View.

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1718)

### CODE REVIEW

**Review by jmgrady — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1718)* status: 0 of 46 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[`Backend/Models/SemanticDomain.cs` line 114 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1718#-NAPXpxH444wuF_wRXGt:-NAPXpxH444wuF_wRXGu:b-wpae0x) ([raw file](https://github.com/sillsdev/thecombine/blob/fd7de40df7a099eb3a3b6dedac334433085443a4/Backend/Models/SemanticDomain.cs#L114)):*
> ```Smalltalk
>         [Required]
>         public SemanticDomain Right { get; set; }
>         [Required]
> ```

I am not sure that we want "Left" and "Right" in the data model.  That is a UI presentation property - it is not inherent in the structure of the data.  For example, if we were to present the Semantic Domains in the standard tree view, "left" and "right" are not really meaningful.



_Code quote:_
```Smalltalk
        [Required]
        public SemanticDomain Left { get; set; }
        [Required]
        public SemanticDomain Right { get; set; }
```

**Review by jmgrady — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1718)* status: 0 of 46 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec)

___
*[`Backend/Models/SemanticDomain.cs` line 56 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1718#-NAPYoN560embXwOzYkc:-NAPYoN560embXwOzYkd:b2p00eu) ([raw file](https://github.com/sillsdev/thecombine/blob/fd7de40df7a099eb3a3b6dedac334433085443a4/Backend/Models/SemanticDomain.cs#L56)):*
> ```Smalltalk
>         [Required]
>         public List<string> Questions { get; set; }
> ```

The XML input files also have `ExampleWords` elements.  I think this would be a simple string.

**Review by jmgrady — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1718)* status: 0 of 46 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec)

___
*[`Backend/Models/SemanticDomain.cs` line 56 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1718#-NAPYoN560embXwOzYkc:-NAPZqV45qtcgU1hRowW:b4hc0bg) ([raw file](https://github.com/sillsdev/thecombine/blob/fd7de40df7a099eb3a3b6dedac334433085443a4/Backend/Models/SemanticDomain.cs#L56)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

The XML input files also have `ExampleWords` elements.  I think this would be a simple string.
</blockquote></details>

... and `ExampleSentences`.  It looks like these are part of the `CmDomainQ` element.  Are we expecting that these are merged with the `Question` element in _The Combine_ since we don't present these separately/differently?

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1718)* status: 0 of 46 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

___
*[`Backend/Models/SemanticDomain.cs` line 56 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1718#-NAPYoN560embXwOzYkc:-NAQ18r17c1NmQFjgWGU:bxqxs0i) ([raw file](https://github.com/sillsdev/thecombine/blob/fd7de40df7a099eb3a3b6dedac334433085443a4/Backend/Models/SemanticDomain.cs#L56)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

... and `ExampleSentences`.  It looks like these are part of the `CmDomainQ` element.  Are we expecting that these are merged with the `Question` element in _The Combine_ since we don't present these separately/differently?
</blockquote></details>

Let's keep ExampleWords, ExampleSentences, and Questions separate in the database--we'll ignore them in our queries for now as we're not using them in the app yet but might in the future.
___
*[`Backend/Models/SemanticDomain.cs` line 114 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1718#-NAPXpxH444wuF_wRXGt:-NAQ12YE7BF4MOoT0pPZ:b-886gsx) ([raw file](https://github.com/sillsdev/thecombine/blob/fd7de40df7a099eb3a3b6dedac334433085443a4/Backend/Models/SemanticDomain.cs#L114)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

I am not sure that we want "Left" and "Right" in the data model.  That is a UI presentation property - it is not inherent in the structure of the data.  For example, if we were to present the Semantic Domains in the standard tree view, "left" and "right" are not really meaningful.
</blockquote></details>

Fixed

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1718)* status: 2 of 46 files reviewed, 5 unresolved discussions (waiting on @imnasnainaec)

___
*[`Backend/Models/SemanticDomain.cs` line 32 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1718#-NAjCWmi4oLL4wBk3ibr:-NAjLcKS8-OtrcK0Q_Nx:b-n8mfry) ([raw file](https://github.com/sillsdev/thecombine/blob/b2bfb7767973b88f7bd54bf5562362ead10463a3/Backend/Models/SemanticDomain.cs#L32)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

This is my C# ignorance.  What is "other"?  I can understand that `Equals` fails if `obj` is not an instance of a `SemanticDomain` or if the lhs object has a different type than the  rhs but the `other` is throwing me for a loop.
</blockquote></details>

Looking at https://stackoverflow.com/questions/9317582/correct-way-to-override-equals-and-gethashcode, is this equivalent to:
```
public override bool Equals(object obj)
{
    var other = obj as SemanticDomain;

    if (other == null)
    {
        return false;
    }

    return Name.Equals(other.Name) && Id.Equals(other.Id);
```

**Review by jmgrady — COMMENTED** [review]
> Reviewed 14 of 46 files at r1, 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1718)* status: 18 of 46 files reviewed, 5 unresolved discussions (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1718)* status: 18 of 46 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec)

___
*[`Backend/Controllers/SemanticDomainController.cs` line 46 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1718#-NAjAutr-3GK0WidRYCk:-NAjTsUu8je6WEL66pmz:b-hpvhbp) ([raw file](https://github.com/sillsdev/thecombine/blob/b2bfb7767973b88f7bd54bf5562362ead10463a3/Backend/Controllers/SemanticDomainController.cs#L46)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Remove UNUSED comment?
</blockquote></details>

I think this whole function is on the chopping block, but I want to leave its removal for the backend API work.
___
*[`Backend/Models/SemanticDomain.cs` line 32 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1718#-NAjCWmi4oLL4wBk3ibr:-NAjV0it-KdvqZFT8FUJ:bema71p) ([raw file](https://github.com/sillsdev/thecombine/blob/b2bfb7767973b88f7bd54bf5562362ead10463a3/Backend/Models/SemanticDomain.cs#L32)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Looking at https://stackoverflow.com/questions/9317582/correct-way-to-override-equals-and-gethashcode, is this equivalent to:
```
public override bool Equals(object obj)
{
    var other = obj as SemanticDomain;

    if (other == null)
    {
        return false;
    }

    return Name.Equals(other.Name) && Id.Equals(other.Id);
```

</blockquote></details>

I think that is a question for John. This is copied from how we override `Equals` in all our models.
___
*[`Backend/Models/SemanticDomain.cs` line 73 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1718#-NAjF4_k249KffjsK21R:-NAjVHY4BCrM4k6bZkTI:bodce1n) ([raw file](https://github.com/sillsdev/thecombine/blob/b2bfb7767973b88f7bd54bf5562362ead10463a3/Backend/Models/SemanticDomain.cs#L73)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

If I understand https://www.techiedelight.com/clone-list-in-csharp/ correctly, you can clone the questions with:
```
Questions = new List<string>(Questions)
```
and skip the for loop.
</blockquote></details>

I think we need this for a deep copy.

**Review by jmgrady — APPROVED** [review]
> Reviewed 26 of 46 files at r1, 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1718)* status: all files reviewed, 2 unresolved discussions (waiting on @imnasnainaec)

**Review by jmgrady — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1718)* status: all files reviewed, 2 unresolved discussions (waiting on @imnasnainaec)

**Pull request merged**
