### PR TITLE
[DataEntry > NewEntry] Don't tag as duplicate if gloss is blank

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves: #1585 

Only mark it as a duplicate if a word with the same vernacular *also* has a blank gloss *and* has the same semantic domain.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1591)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
Is there a test for WordIsUnique? If so we definitely want to add some assertions.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1591#-:-MwbLJpe0N-tHTFW1aD6:b7k60dy)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
https://github.com/sillsdev/TheCombine/issues/1592

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1591#-:-MwbMic29G7kosni9X9W:bz2twkj)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by jasonleenaylor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1591)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Review by jasonleenaylor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1591#-:-MwbZcGc7lC8PjqbTcSZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
