### PR TITLE
[installer] Use --dependency-update; Fix debugging; Remove junk dirs

### PR DESCRIPTION
**Pull request by imnasnainaec**
Fixes a duplicate `--debug` arg issue from #3391

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3402)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
*[`deploy/scripts/setup_combine.py` line 190 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/3402#-O9G8G3pBIwzRurpEvvV:-O9G8G3qBPPSZ83bzr_P:b-z7xh2s) ([raw file](https://github.com/sillsdev/TheCombine/blob/c654e0b608f7f78a20bcadbffeda56b6f02c241e/deploy/scripts/setup_combine.py#L190)):*
> ```Python
>                 if args.clean:
>                     # Delete existing chart if --clean specified
>                     delete_cmd = helm_cmd + [f"--namespace={chart_namespace}", "delete", chart]
> ```

Don't know if it matters, but no debugging flag is being optionally added here.

**Comment by jasonleenaylor** [comment]
*[`deploy/scripts/setup_combine.py` line 190 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/3402#-O9G8G3pBIwzRurpEvvV:-O9G8Zwg-t1D5mM8WBhl:b-4fd2gd) ([raw file](https://github.com/sillsdev/TheCombine/blob/c654e0b608f7f78a20bcadbffeda56b6f02c241e/deploy/scripts/setup_combine.py#L190)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Don't know if it matters, but no debugging flag is being optionally added here.
</blockquote></details>

Or in the other commands below.

**Review by jasonleenaylor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3402#-:-O9G8v6EDcKBFdEUnwsa:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Comment by imnasnainaec** [comment]
> _[`deploy/scripts/setup_combine.py` line 190 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/3402#-O9G8G3pBIwzRurpEvvV:-O9G8G3qBPPSZ83bzr_P:b-z7xh2s) ([raw file](https://github.com/sillsdev/TheCombine/blob/c654e0b608f7f78a20bcadbffeda56b6f02c241e/deploy/scripts/setup_combine.py#L190)):_
> 
> > ```python
> >                 if args.clean:
> >                     # Delete existing chart if --clean specified
> >                     delete_cmd = helm_cmd + [f"--namespace={chart_namespace}", "delete", chart]
> > ```
> 
> Don't know if it matters, but no debugging flag is being optionally added here.

It was hiding inside the `helm_cmd`.

**Pull request merged**
