### PR TITLE
Use InsertManyAsync() on import to reduce connections to mongo.

### PR DESCRIPTION
**Pull request by imnasnainaec**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1054)

### CODE REVIEW

**Review by jasonleenaylor — APPROVED** [review]
:LGTM:

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1054#-:-MV-JxCS7p-EQmYioQ07:bmxilld)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Comment by johnthagen** [comment]
___
*[Backend/Services/WordRepository.cs, line 117 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1054#-MV1NDfU3Ur-21v-cMTr:-MV1NDfU3Ur-21v-cMTs:b-jc2c8h) ([raw file](https://github.com/sillsdev/thecombine/blob/f8ce6a9e3399bce91ff2cd9fee9d2c352acbbe90/Backend/Services/WordRepository.cs#L117)):*
> ```Smalltalk
>         }
> 
>         /// <summary> Adds a <see cref="Word"/> (or list of words) only to the Frontier </summary>
> ```

Technically, this doc string is only applied to the first `Create(Word word)` not the second. If someone looks up quick doc in their editor on the second method (`Create(List<Word> words)`) they won't get any docs.

**Comment by johnthagen** [comment]
___
*[Backend/Services/WordRepository.cs, line 117 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1054#-MV1NDfU3Ur-21v-cMTr:-MV1NTnbA6ufaIfYBG7y:b-g08jiy) ([raw file](https://github.com/sillsdev/thecombine/blob/f8ce6a9e3399bce91ff2cd9fee9d2c352acbbe90/Backend/Services/WordRepository.cs#L117)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Technically, this doc string is only applied to the first `Create(Word word)` not the second. If someone looks up quick doc in their editor on the second method (`Create(List<Word> words)`) they won't get any docs.
</blockquote></details>

This also applies to `AddFrontier(List<Word> word)`

**Comment by johnthagen** [comment]
___
*[Backend/Services/LiftApiServices.cs, line 535 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1054#-MV1OpqdBjh9SIpxbPp6:-MV1Opqe1ZpRcrsopqvL:btztq46) ([raw file](https://github.com/sillsdev/thecombine/blob/f8ce6a9e3399bce91ff2cd9fee9d2c352acbbe90/Backend/Services/LiftApiServices.cs#L535)):*
> ```Smalltalk
>             /// <summary>
>             /// The meat of lift import is done here.
>             /// This reads in all necessary attributes of a word and adds it to the database.
> ```

This is no longer accurate. We need to mention that `SaveImportEntries` is now an implicit required side effect that needs to be run.

Ideally it would be nice if we could hook into something in `ILiftMerger` "Finalize" or similar so that the database saving would automatically happen when import is complete rather than requiring an implicit method to be called afterwards.

**Comment by johnthagen** [comment]
___
*[Backend/Services/LiftApiServices.cs, line 528 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1054#-MV1PSShAH9o_t8kLEkq:-MV1PSShAH9o_t8kLEkr:b5mg0vj) ([raw file](https://github.com/sillsdev/thecombine/blob/f8ce6a9e3399bce91ff2cd9fee9d2c352acbbe90/Backend/Services/LiftApiServices.cs#L528)):*
> ```Smalltalk
>             }
> 
>             public async Task<List<Word>> SaveImportEntries()
> ```

This method needs a doc string stating what it does and also that it has a dependency on internal state (`_importEntries`) that must be set up implicitly somewhere else before calling this method.

**Comment by johnthagen** [comment]
___
*[Backend/Interfaces/ILiftService.cs, line 10 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1054#-MV1QDcfEU4E2hp--SND:-MV1QDcfEU4E2hp--SNE:b-s5p14v) ([raw file](https://github.com/sillsdev/thecombine/blob/f8ce6a9e3399bce91ff2cd9fee9d2c352acbbe90/Backend/Interfaces/ILiftService.cs#L10)):*
> ```Smalltalk
>     public interface ILiftService
>     {
>         ILexiconMerger<LiftObject, LiftEntry, LiftSense, LiftExample> GetLiftImporterExporter(
> ```

Any reason we shouldn't return `ILiftMerger` from this to avoid the need to cast later on usage?

**Comment by johnthagen** [comment]
___
*[Backend/Services/LiftApiServices.cs, line 530 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1054#-MV1Qece4PInXhFcdca9:-MV1Qece4PInXhFcdcaA:b-x75y0f) ([raw file](https://github.com/sillsdev/thecombine/blob/f8ce6a9e3399bce91ff2cd9fee9d2c352acbbe90/Backend/Services/LiftApiServices.cs#L530)):*
> ```Smalltalk
>             public async Task<List<Word>> SaveImportEntries()
>             {
>                 return await _wordRepo.Create(_importEntries);
> ```

Should this method also clear out `_importEntries` after it's saved to the database? I worry that if someone was to ever reuse an instance of this class, they'd keep adding `Word`s to the same `List` and it'd never get cleared.

**Review by johnthagen — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1054)* status: all files reviewed, 5 unresolved discussions (waiting on @imnasnainaec)

**Comment by johnthagen** [comment]
___
*[Backend/Services/LiftApiServices.cs, line 535 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1054#-MV1OpqdBjh9SIpxbPp6:-MV1kP4KDzRBzlpRa0P3:blw4lkp) ([raw file](https://github.com/sillsdev/thecombine/blob/f8ce6a9e3399bce91ff2cd9fee9d2c352acbbe90/Backend/Services/LiftApiServices.cs#L535)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This is no longer accurate. We need to mention that `SaveImportEntries` is now an implicit required side effect that needs to be run.

Ideally it would be nice if we could hook into something in `ILiftMerger` "Finalize" or similar so that the database saving would automatically happen when import is complete rather than requiring an implicit method to be called afterwards.
</blockquote></details>

I couldn't find any methods in `ILexiconMerger` that looks like a "Finalize" or similar where we could put this so that things are saved automatically.

**Comment by johnthagen** [comment]
___
*[Backend/Interfaces/ILiftService.cs, line 10 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1054#-MV1QDcfEU4E2hp--SND:-MV1rUC8CPORmSf90h8r:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/f8ce6a9e3399bce91ff2cd9fee9d2c352acbbe90/Backend/Interfaces/ILiftService.cs#L10)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Any reason we shouldn't return `ILiftMerger` from this to avoid the need to cast later on usage?
</blockquote></details>

Done

**Comment by johnthagen** [comment]
___
*[Backend/Services/LiftApiServices.cs, line 528 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1054#-MV1PSShAH9o_t8kLEkq:-MV1r_ke2x9OFSkYtFuX:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/f8ce6a9e3399bce91ff2cd9fee9d2c352acbbe90/Backend/Services/LiftApiServices.cs#L528)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This method needs a doc string stating what it does and also that it has a dependency on internal state (`_importEntries`) that must be set up implicitly somewhere else before calling this method.
</blockquote></details>

Done

**Comment by johnthagen** [comment]
___
*[Backend/Services/LiftApiServices.cs, line 530 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1054#-MV1Qece4PInXhFcdca9:-MV1rasmDeBjDkL-ARLe:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/f8ce6a9e3399bce91ff2cd9fee9d2c352acbbe90/Backend/Services/LiftApiServices.cs#L530)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Should this method also clear out `_importEntries` after it's saved to the database? I worry that if someone was to ever reuse an instance of this class, they'd keep adding `Word`s to the same `List` and it'd never get cleared.
</blockquote></details>

Done.

**Comment by johnthagen** [comment]
___
*[Backend/Services/LiftApiServices.cs, line 535 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1054#-MV1OpqdBjh9SIpxbPp6:-MV1rjxX8wQaHzKJvWfH:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/f8ce6a9e3399bce91ff2cd9fee9d2c352acbbe90/Backend/Services/LiftApiServices.cs#L535)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I couldn't find any methods in `ILexiconMerger` that looks like a "Finalize" or similar where we could put this so that things are saved automatically.
</blockquote></details>

Done

**Comment by johnthagen** [comment]
___
*[Backend/Services/WordRepository.cs, line 117 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1054#-MV1NDfU3Ur-21v-cMTr:-MV1rtWeAKntQUTeSUX9:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/f8ce6a9e3399bce91ff2cd9fee9d2c352acbbe90/Backend/Services/WordRepository.cs#L117)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This also applies to `AddFrontier(List<Word> word)`
</blockquote></details>

Done

**Comment by johnthagen** [comment]
___
*[Backend/Controllers/LiftController.cs, line 155 at r1](https://reviewable.io/reviews/sillsdev/thecombine/1054#-MV1s0RY73Fa7aivitvN:-MV1s0RY73Fa7aivitvO:brq1srb) ([raw file](https://github.com/sillsdev/thecombine/blob/f8ce6a9e3399bce91ff2cd9fee9d2c352acbbe90/Backend/Controllers/LiftController.cs#L155)):*
> ```Smalltalk
>             {
>                 // Sets the projectId of our parser to add words to that project
>                 var liftMerger = (ILiftMerger)_liftService.GetLiftImporterExporter(projectId, _projectService, _wordRepo);
> ```

We should be able to remove this cast now.

**Review by johnthagen — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1054)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

**Review by johnthagen — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1054)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
