### PR TITLE
Add .github, docker_deploy folders and .yml files to fmt-frontend.

### PR DESCRIPTION
**Pull request by imnasnainaec**
The meat of this pr is the change to `fmt-frontend` and `fmt-frontend-check` in `package.json` and the addition to `.vscode/settings.json`--the other files were modified as a consequence.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/856)

### CODE REVIEW

**Review by jmgrady — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/856)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[docker_deploy/group_vars/server/main.yml, line 38 at r1](https://reviewable.io/reviews/sillsdev/thecombine/856#-MO2GwIB90kZaKnWZLTu:-MO2GwIB90kZaKnWZLTv:b-fxx83o) ([raw file](https://github.com/sillsdev/thecombine/blob/ee0049c684edd324a2f13b2f3902b1d0c0937dcf/docker_deploy/group_vars/server/main.yml#L38)):*
> ```
> backup_hour: "3"
> backup_minute: "15"
> num_backups: "3"
> ```
I think that in this case, and others like it, the code is harder to read once prettier has reformatted it.  Let's discuss.

**Comment by imnasnainaec** [comment]
This change is not helpful at this time.

**Comment by imnasnainaec** [comment]
... but it's reasonable.

**Review by jmgrady — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/856#-:-MO3SMuX2yHS-91DrnPF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
