### PR TITLE
[CharInv] Track words changed with find-and-replace

### LINKED ISSUE #2333: Create Character Inventory does not show all changes in history
**Describe the bug**

When an existing character inventory is modified using _find-and-replace_ the goal history says no changes were made.

**To Reproduce**

1. Open a project;
2. Click on 'Data Cleanup';
3. Click on 'Create Character Inventory';
4. Select a character in the inventory;
5. Enter an unused character in the _Replace with_ field;
6. Click _APPLY_ & _CONFIRM_;
7. Click _SAVE_;
8. Goal history shows _CREATE CHARACTER INVENTORY_ with _NO CHANGES MADE IN THIS GOAL._;
9. Reopen the _CREATE CHARACTER INVENTORY_ goal;
10. Observe that changes were actually made.

**Expected behavior**

The goal history should indicate the number of changes made or at least that some changes were made.

**Environment:**

- OS: Ubuntu 22.04.2
- Browser Version: Version 1.52.126 Chromium: 114.0.5735.133

### PR DESCRIPTION
**Pull request by imnasnainaec**
Follows #2964
Resolves #2333

Also, fixed a bug in https://github.com/sillsdev/TheCombine/pull/2962 that the CancelConfirmDialog gets stuck in loading after its first use.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2955)

### CODE REVIEW

**Comment by imnasnainaec** [comment]
To-do:
- [ ] Add tests for `WordController` > `AreInFrontier()`
- [ ] Add `WordController` function for updating multiple words
- [ ] Update goal changes when words reverted

**Review by jmgrady — CHANGES_REQUESTED** [review]
> Reviewed 2 of 16 files at r2, 15 of 19 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2955)* status: all files reviewed, 3 unresolved discussions (waiting on @imnasnainaec)

___
*[`public/locales/en/translation.json` line 374 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2955#-Nu-QbZi2ZYHS0VmFIzP:-Nu-QbZi2ZYHS0VmFIzQ:b-8d7uzi) ([raw file](https://github.com/sillsdev/TheCombine/blob/cfa293e20185534e6d4257cb20b28258abe2ce06/public/locales/en/translation.json#L374)):*
> ```JSON
>       "noWordChanges": "No words changed by find-and-replace.",
>       "wordChanges": "Words changed by find-and-replace:",
>       "wordChangesWithStrings": "Words changed by find-and-replace ({{ val1 }} → {{ val2 }}):"
> ```

A little wordy.  Why not just "Words changed"?



_Code quote:_
```JSON
      "noWordChanges": "No words changed by find-and-replace.",
      "wordChanges": "Words changed by find-and-replace:",
      "wordChangesWithStrings": "Words changed by find-and-replace ({{ val1 }} → {{ val2 }}):"
```
___
*[`src/goals/CharacterInventory/Redux/tests/CharacterInventoryActions.test.tsx` line 230 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2955#-Nu0MjMt9-xcj536efST:-Nu0MjMuAe1o7u1D3-IV:b-9867fz) ([raw file](https://github.com/sillsdev/TheCombine/blob/cfa293e20185534e6d4257cb20b28258abe2ce06/src/goals/CharacterInventory/Redux/tests/CharacterInventoryActions.test.tsx#L230)):*
> ```XML
>       mockGetFrontierWords.mockResolvedValue([]);
> 
>       await store.dispatch(findAndReplace("A", "a"));
> ```

I think this test would be more convincing if there was a word in the Frontier with no `A` in it.
___
*[`src/goals/CharacterInventory/tests/CharInvCompleted.test.tsx` line 110 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2955#-Nu0Qu8T0rNOG3pJTLWY:-Nu0Qu8T0rNOG3pJTLWZ:bkfx02b) ([raw file](https://github.com/sillsdev/TheCombine/blob/cfa293e20185534e6d4257cb20b28258abe2ce06/src/goals/CharacterInventory/tests/CharInvCompleted.test.tsx#L110)):*
> ```XML
>       root.findByProps({ id: CharInvCompletedId.TypographyNoWordChanges })
>     ).toThrow();
>     root.findByProps({ id: CharInvCompletedId.TypographyWordChanges });
> ```

Shouldn't there be an `expect` after calling `findByProps`? Am I missing something?



_Code quote:_
```XML
root.findByProps
```
___
*[`src/goals/CharacterInventory/tests/CharInvCompleted.test.tsx` line 145 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2955#-Nu0SYrK3L3AycoGgK-P:-Nu0SYrK3L3AycoGgK-Q:b-zal5oe) ([raw file](https://github.com/sillsdev/TheCombine/blob/cfa293e20185534e6d4257cb20b28258abe2ce06/src/goals/CharacterInventory/tests/CharInvCompleted.test.tsx#L145)):*
> ```XML
>     });
>     expect(root.findAllByType(CharChange)).toHaveLength(2);
>   });
> ```

Why does passing a list of 3 character changes expects the length to be 3 but when a list of 6 is passed the expected value is 2?



_Code quote:_
```XML
  it("doesn't render more than 3 char changes", async () => {
    await renderCharInvChangesGoalList({
      ...defaultCharInvChanges,
      charChanges: mockCharChanges,
    });
    expect(root.findAllByType(CharChange)).toHaveLength(2);
  });
```

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2955)* status: 16 of 22 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

___
*[`src/goals/CharacterInventory/tests/CharInvCompleted.test.tsx` line 110 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2955#-Nu0Qu8T0rNOG3pJTLWY:-Nu0rNON0ZsnWeIbK0gD:bbg7ue7) ([raw file](https://github.com/sillsdev/TheCombine/blob/cfa293e20185534e6d4257cb20b28258abe2ce06/src/goals/CharacterInventory/tests/CharInvCompleted.test.tsx#L110)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Shouldn't there be an `expect` after calling `findByProps`? Am I missing something?
</blockquote></details>

It will throw if it fails. I could add `expect(() => ...).not.toThrow();` if you think that helps.
___
*[`src/goals/CharacterInventory/tests/CharInvCompleted.test.tsx` line 145 at r4](https://reviewable.io/reviews/sillsdev/TheCombine/2955#-Nu0SYrK3L3AycoGgK-P:-Nu0rbTD6odZNqa6_JVQ:b-rwwkgm) ([raw file](https://github.com/sillsdev/TheCombine/blob/cfa293e20185534e6d4257cb20b28258abe2ce06/src/goals/CharacterInventory/tests/CharInvCompleted.test.tsx#L145)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Why does passing a list of 3 character changes expects the length to be 3 but when a list of 6 is passed the expected value is 2?
</blockquote></details>

Clarifying comment added.

**Review by jmgrady — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2955)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
