### PR TITLE
Displays part of autocomplete when typing in entry

### PR DESCRIPTION
**Pull request by shyung18**
Only shows the first item of the list.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/449)

### CODE REVIEW

**Comment by shyung18** [comment]
When typing into data entry, it automatically scrolls so that the user can see the list of the autocomplete words.

**Comment by charjhall** [comment]
*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/449#-MAawYgQ4Nr7PQxYcVtP:-MAawYgRDoSKUOQHtV-Z:bynm1ef) (no related file):*
Similar to Jason's suggestion, the new entry that the user currently types in does not stay in the same place as the user types. The initial moving of the new entry is good to show the autocomplete, but once the autocomplete list length is less than the bottom of the screen, the entry moves on every key press which is rather jarring. See the attached gif. 


---

**Comment by charjhall** [comment]
*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/449#-MAawYgQ4Nr7PQxYcVtP:-MAbHQxh6amLgcODSnyI:b-kct645) (no related file):*
<details><summary><i>Previously, charjhall (Charles Hall) wrote…</i></summary><blockquote>

Similar to Jason's suggestion, the new entry that the user currently types in does not stay in the same place as the user types. The initial moving of the new entry is good to show the autocomplete, but once the autocomplete list length is less than the bottom of the screen, the entry moves on every key press which is rather jarring. See the attached gif. 


</blockquote></details>

After taking a look at the code, I think this would involve allowing the `DataEntryComponent` to resize, maintaining the location of the `NewEntry` at a designated location on the screen (vertically centered or similar). Then based on the length of the duplicates, the bottom of the `DataEntryComponent` would resize.

---

**Comment by charjhall** [comment]
___
*[src/components/DataEntry/DataEntryTable/NewEntry/NewEntry.tsx, line 303 at r2](https://reviewable.io/reviews/sillsdev/thecombine/449#-MAbYnw66QMV24jRTVWc:-MAbYnw66QMV24jRTVWd:b-q819l0) ([raw file](https://github.com/sillsdev/thecombine/blob/20dbbf0c142f56d48a2cf4449032a649afecbb66/src/components/DataEntry/DataEntryTable/NewEntry/NewEntry.tsx#L303)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>   focusAutoScroll = () => {
>     if (this.duplicateInput.current) {
>       this.duplicateInput.current.scrollIntoView({
>         block: "nearest",
>       });
>     }
>   };
> ```
</details>

This is the function that would probably need to be modified to alter the aforementioned issue of the `NewEntry` moving on every keypress.

**Comment by charjhall** [comment]
*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/449#-MAawYgQ4Nr7PQxYcVtP:-MAg9Vtb8cMxtBYNEsSW:btdu1lb) (no related file):*
<details><summary><i>Previously, charjhall (Charles Hall) wrote…</i></summary><blockquote>

After taking a look at the code, I think this would involve allowing the `DataEntryComponent` to resize, maintaining the location of the `NewEntry` at a designated location on the screen (vertically centered or similar). Then based on the length of the duplicates, the bottom of the `DataEntryComponent` would resize.
</blockquote></details>

This will be handled in a later issue

---

**Comment by charjhall** [comment]
___
*[src/components/DataEntry/DataEntryTable/NewEntry/NewEntry.tsx, line 303 at r2](https://reviewable.io/reviews/sillsdev/thecombine/449#-MAbYnw66QMV24jRTVWc:-MAg9_XO9IQrsnAcqMEH:b-su7p5x) ([raw file](https://github.com/sillsdev/thecombine/blob/20dbbf0c142f56d48a2cf4449032a649afecbb66/src/components/DataEntry/DataEntryTable/NewEntry/NewEntry.tsx#L303)):*
<details><summary><i>Previously, charjhall (Charles Hall) wrote…</i></summary><blockquote>

> ```
>   focusAutoScroll = () => {
>     if (this.duplicateInput.current) {
>       this.duplicateInput.current.scrollIntoView({
>         block: "nearest",
>       });
>     }
>   };
> ```
This is the function that would probably need to be modified to alter the aforementioned issue of the `NewEntry` moving on every keypress.
</blockquote></details>

This will be handled in a later issue

**Pull request merged**
