### PR TITLE
Add users to current project state, and refresh when project is updated

### LINKED ISSUE #1260: [ProjectSettings] Re-render after a user in the project is updated
Currently the page does not change after updating a user even though the user update did take effect. It would be nice for users to see the effects of their change immediately without having to refresh the page.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #1260

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1277)

### CODE REVIEW

**Review by WeJamUS — COMMENTED** [review]
> Reviewed 6 of 39 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1277)* status: 6 of 39 files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Comment by WeJamUS** [comment]
___
*[src/components/Project/ProjectActions.ts, line 43 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1277#-MfiydIj8UZsqhExiWeM:-MfiyAZB0WOioJouW-7_:b3gaym9) ([raw file](https://github.com/sillsdev/thecombine/blob/82b2cbf3c8b48e7a63b4d3d976c377831707e0a4/src/components/Project/ProjectActions.ts#L43)):*
> ```XML
> }
> 
> export function asyncSetCurrentProject(project?: Project) {
> ```

Why is it necessary to have both an async and a non-async setCurrentProject?

**Review by WeJamUS — COMMENTED** [review]
> Reviewed 27 of 39 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1277)* status: 34 of 39 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1277)* status: 31 of 39 files reviewed, all discussions resolved (waiting on @imnasnainaec and @WeJamUS)

___
*[src/components/Project/ProjectActions.ts, line 43 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1277#-MfiydIj8UZsqhExiWeM:-MfmX4oz1XPt-F4bGFmY:b-r06lu6) ([raw file](https://github.com/sillsdev/thecombine/blob/82b2cbf3c8b48e7a63b4d3d976c377831707e0a4/src/components/Project/ProjectActions.ts#L43)):*
<details><summary><i>Previously, WeJamUS (James Wu) wrote…</i></summary><blockquote>

Why is it necessary to have both an async and a non-async setCurrentProject?
</blockquote></details>

Your question highlights the fact that I named those two functions too similarly. `setCurrentProject` is a sort of atomic function for Redux who's only purpose is creating the action that the reducer will recognize for setting the current project. `asyncSetNewCurrentProject` (with "New" just added) is a bigger function that (can also be `dispatch`ed, but) is intended for situations when current project is not just being updated, but being switch. In such cases, we also want the list of users of the current project to be automatically updated in the state.

**Review by WeJamUS — COMMENTED** [review]
> Reviewed 1 of 39 files at r1, 23 of 32 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1277)* status: 48 of 63 files reviewed, all discussions resolved (waiting on @imnasnainaec and @WeJamUS)

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 5 of 39 files at r1, 4 of 4 files at r3, 9 of 32 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1277)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
