### PR TITLE
Created warning box when finding and replacing characters

### PR DESCRIPTION
**Pull request by JacobHaimes**
Added a new warning box when clicking the apply button under find and replace. Warning displays the found characters and the new replacing characters so the user has a better grasp as to what they are modifying. Future work would be to include the number of occurrences in the warning box.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1209)

### CODE REVIEW

**Comment by johnthagen** [comment]
@JacobHaimes There is a small typo in the PR title

> reaplacing

Since GitHub puts the title into the final squashed commit message it will be saved in history. Could you edit the PR title and fix the typo?

**Comment by johnthagen** [comment]
___
*[src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx, line 1 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1209#-Md2-r0nCnpUrsqSEQ_f:-Md2-r0nCnpUrsqSEQ_g:boj9y45) ([raw file](https://github.com/sillsdev/thecombine/blob/c2bdade69863fc2e3f7dd1a560f80f3a3fe2f168/src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx#L1)):*
> Future work would be to include the number of occurrences in the warning box.

Do we want to open a follow on issue to track this?

**Comment by johnthagen** [comment]
___
*[src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx, line 2 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1209#-Md21wO79-940Y0_lDK4:-Md21wO79-940Y0_lDK5:b-u1sd0l) ([raw file](https://github.com/sillsdev/thecombine/blob/c2bdade69863fc2e3f7dd1a560f80f3a3fe2f168/src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx#L2)):*
> ```XML
> import {
>   Button,
> ```

Since this PR closes https://github.com/sillsdev/TheCombine/issues/1111, the flow we use it to put "Closes #1111" in the description of the PR. When this PR is merged, GitHub will automatically close that issue then.

**Comment by johnthagen** [comment]
___
*[src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx, line 31 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1209#-Md22nlfD4LTvqhUGfuk:-Md22nlfD4LTvqhUGful:bjy9rxq) ([raw file](https://github.com/sillsdev/thecombine/blob/c2bdade69863fc2e3f7dd1a560f80f3a3fe2f168/src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx#L31)):*
> ```XML
>       aria-describedby="alert-dialog-description"
>     >
>       <DialogTitle id="alert-dialog-title">
> ```

This is just an observation @imnasnainaec would probably know best about theming. But for a warning dialogue like this I would personally expect some red or orange color to help highlight the gravity of this warning.

**Comment by johnthagen** [comment]
___
*[src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/FindAndReplaceComponent.tsx, line 106 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1209#-Md23b8t3JvRB_8RIjIr:-Md23b8uDJj4dc_fbjSJ:baqjx8n) ([raw file](https://github.com/sillsdev/thecombine/blob/c2bdade69863fc2e3f7dd1a560f80f3a3fe2f168/src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/FindAndReplaceComponent.tsx#L106)):*
> ```XML
>             );
>           }}
>         ></CharacterReplaceDialog>
> ```

Since this tag is empty, it can be simplified to:

```tsx
        <CharacterReplaceDialog
          open={this.state.warningDialogOpen}
          dialogFindValue={this.state.findValue}
          dialogReplaceValue={this.state.replaceValue}
          handleCancel={() => {
            this.setState(() => ({
              warningDialogOpen: false,
            }));
          }}
          handleAccept={() => {
            this.setState(() => ({
              warningDialogOpen: false,
            }));
            this.props.findAndReplace(
              this.state.findValue,
              this.state.replaceValue
            );
          }}
        />
```

**Review by johnthagen — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1209)* status: all files reviewed, 4 unresolved discussions (waiting on @JacobHaimes)

**Comment by johnthagen** [comment]
___
*[src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx, line 2 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1209#-Md21wO79-940Y0_lDK4:-Md25BOzAUOvsWw60Otw:b3smj0c) ([raw file](https://github.com/sillsdev/thecombine/blob/c2bdade69863fc2e3f7dd1a560f80f3a3fe2f168/src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx#L2)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Since this PR closes https://github.com/sillsdev/TheCombine/issues/1111, the flow we use it to put "Closes #1111" in the description of the PR. When this PR is merged, GitHub will automatically close that issue then.
</blockquote></details>

See: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1209)* status: all files reviewed, 3 unresolved discussions (waiting on @JacobHaimes)

___
*[src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx, line 31 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1209#-Md22nlfD4LTvqhUGfuk:-Md2MHIY0VOrYHEp0UIa:b-fkshdn) ([raw file](https://github.com/sillsdev/thecombine/blob/c2bdade69863fc2e3f7dd1a560f80f3a3fe2f168/src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx#L31)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This is just an observation @imnasnainaec would probably know best about theming. But for a warning dialogue like this I would personally expect some red or orange color to help highlight the gravity of this warning.
</blockquote></details>

Since we don't have that in our other warning dialogues, let's open that as a separate issue.

**Comment by johnthagen** [comment]
___
*[src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx, line 31 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1209#-Md22nlfD4LTvqhUGfuk:-Md2O411-uhdPTvpu57J:bz2tu5k) ([raw file](https://github.com/sillsdev/thecombine/blob/c2bdade69863fc2e3f7dd1a560f80f3a3fe2f168/src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx#L31)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Since we don't have that in our other warning dialogues, let's open that as a separate issue.
</blockquote></details>

https://github.com/sillsdev/TheCombine/issues/1212

**Review by JacobHaimes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1209)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @JacobHaimes and @johnthagen)

___
*[src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx, line 1 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1209#-Md2-r0nCnpUrsqSEQ_f:-Md3t6uA-w9q-4mhjmwg:b-lmw2d1) ([raw file](https://github.com/sillsdev/thecombine/blob/48cc4d1f557f29e28243c95b731760ccf32e32bb/src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx#L1)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

> Future work would be to include the number of occurrences in the warning box.

Do we want to open a follow on issue to track this?
</blockquote></details>

It might be good to make one if the number of occurrences is needed in the warning.
___
*[src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/FindAndReplaceComponent.tsx, line 106 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1209#-Md23b8t3JvRB_8RIjIr:-Md3tmDvD0fKa_L7R5oN:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/48cc4d1f557f29e28243c95b731760ccf32e32bb/src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/FindAndReplaceComponent.tsx#L106)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Since this tag is empty, it can be simplified to:

```tsx
        <CharacterReplaceDialog
          open={this.state.warningDialogOpen}
          dialogFindValue={this.state.findValue}
          dialogReplaceValue={this.state.replaceValue}
          handleCancel={() => {
            this.setState(() => ({
              warningDialogOpen: false,
            }));
          }}
          handleAccept={() => {
            this.setState(() => ({
              warningDialogOpen: false,
            }));
            this.props.findAndReplace(
              this.state.findValue,
              this.state.replaceValue
            );
          }}
        />
```
</blockquote></details>

Done.

**Review by imnasnainaec — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1209)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @JacobHaimes and @johnthagen)

___
*[src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx, line 1 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1209#-Md2-r0nCnpUrsqSEQ_f:-MdJGXkY3x7oBQVuALhg:baljzro) ([raw file](https://github.com/sillsdev/thecombine/blob/48cc4d1f557f29e28243c95b731760ccf32e32bb/src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx#L1)):*
<details><summary><i>Previously, JacobHaimes wrote…</i></summary><blockquote>

It might be good to make one if the number of occurrences is needed in the warning.
</blockquote></details>

Yes, please open a new issue for that.
___
*[src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx, line 13 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1209#-MdJGQTt0nEG2AOI9X3t:-MdJGQTt0nEG2AOI9X3u:ba4vpvs) ([raw file](https://github.com/sillsdev/thecombine/blob/adfcf6cf0754a6b6de487efaea784979c00add11/src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx#L13)):*
> ```XML
> interface ReplaceDialogProps {
>   open: boolean;
>   textId?: string;
> ```

Delete unused property`textId?: string;`

**Review by JacobHaimes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1209)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @imnasnainaec, @JacobHaimes, and @johnthagen)

___
*[src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx, line 13 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1209#-MdJGQTt0nEG2AOI9X3t:-MdJI0oC7d4xUXzHoLtt:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/adfcf6cf0754a6b6de487efaea784979c00add11/src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx#L13)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Delete unused property`textId?: string;`
</blockquote></details>

Done.

**Review by imnasnainaec — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1209)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @JacobHaimes and @johnthagen)

___
*[src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/FindAndReplaceComponent.tsx, line 83 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1209#-MdJJSK_EO9KnB5Sv-2c:-MdJJSK_EO9KnB5Sv-2d:b-w43x41) ([raw file](https://github.com/sillsdev/thecombine/blob/441637c3208cf4d2660bfa2f8515ad3bbba67a82/src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/FindAndReplaceComponent.tsx#L83)):*
> ```
>             this.setState(() => ({
>               warningDialogOpen: true,
>             }));
> ```
A function is only needed inside `setState` when you are using a value in the previous state, such as `this.setState((prevState)=>({count: prevState.count+1})`. For this case (and likewise below), you can use an object instead of a function. `this.setState({warningDialogOpen: true))`.

**Review by JacobHaimes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1209)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @imnasnainaec, @JacobHaimes, and @johnthagen)

___
*[src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/FindAndReplaceComponent.tsx, line 83 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1209#-MdJJSK_EO9KnB5Sv-2c:-MdJYX7-2XHofSPOAMYk:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/441637c3208cf4d2660bfa2f8515ad3bbba67a82/src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/FindAndReplaceComponent.tsx#L83)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>             this.setState(() => ({
>               warningDialogOpen: true,
>             }));
> ```
A function is only needed inside `setState` when you are using a value in the previous state, such as `this.setState((prevState)=>({count: prevState.count+1})`. For this case (and likewise below), you can use an object instead of a function. `this.setState({warningDialogOpen: true))`.
</blockquote></details>

Done.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 1 of 3 files at r4, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1209)* status: all files reviewed, 2 unresolved discussions (waiting on @JacobHaimes and @johnthagen)

**Review by jasonleenaylor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1209)* status: all files reviewed, 2 unresolved discussions (waiting on @JacobHaimes and @johnthagen)

**Review by jasonleenaylor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1209)* status: all files reviewed, 2 unresolved discussions (waiting on @JacobHaimes and @johnthagen)

**Review by JacobHaimes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1209)* status: all files reviewed, 2 unresolved discussions (waiting on @JacobHaimes and @johnthagen)

___
*[src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx, line 2 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1209#-Md21wO79-940Y0_lDK4:-MdJbInm4716hvrYeUKf:bebrt1w) ([raw file](https://github.com/sillsdev/thecombine/blob/48cc4d1f557f29e28243c95b731760ccf32e32bb/src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx#L2)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

See: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
</blockquote></details>

Will do

**Review by JacobHaimes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1209)* status: all files reviewed, 2 unresolved discussions (waiting on @johnthagen)

___
*[src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx, line 2 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1209#-Md21wO79-940Y0_lDK4:-MdJbZUk3n3DbXRpPJax:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/48cc4d1f557f29e28243c95b731760ccf32e32bb/src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx#L2)):*
<details><summary><i>Previously, JacobHaimes wrote…</i></summary><blockquote>

Will do
</blockquote></details>

Done.

**Pull request merged**
