### PR TITLE
Improve backend test coverage of Project

### PR DESCRIPTION
**Pull request by imnasnainaec**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/750)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[Backend/Models/Project.cs, line 82 at r1](https://reviewable.io/reviews/sillsdev/thecombine/750#-MJCDQCu75hlPqT9rzzt:-MJCDQCu75hlPqT9rzzu:bpnh10t) ([raw file](https://github.com/sillsdev/thecombine/blob/7f0652169b524addf25b3157be6dcb2c02f5ce5d/Backend/Models/Project.cs#L82)):*
> ```Smalltalk
>                 Name = Name.Clone() as string,
>                 IsActive = IsActive,
>                 AutocompleteSetting = AutocompleteSetting,
> ```

Yikes, this was actually a bug.

A huge part of our `Model`s are these  boilerplate constructors, `Clone`, and `Hash` methods that are brittle and really easy to subtly mess up. I'm going to do a little research to see if there is a way for C# to just autogenerate these, similar to a [Python `dataclass`](https://docs.python.org/3/library/dataclasses.html).

**Comment by johnthagen** [comment]
___
*[Backend/Models/Project.cs, line 179 at r1](https://reviewable.io/reviews/sillsdev/thecombine/750#-MJCE8YHEFnlyPWH49xY:-MJCE8YHEFnlyPWH49xZ:b-usqnu5) ([raw file](https://github.com/sillsdev/thecombine/blob/7f0652169b524addf25b3157be6dcb2c02f5ce5d/Backend/Models/Project.cs#L179)):*
> ```Smalltalk
>             hash.Add(Name);
>             hash.Add(IsActive);
>             hash.Add(SemanticDomains);
> ```

`AutoCompleteSetting` is missing from `GetHashCode()`.

**Review by johnthagen — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/750)* status: all files reviewed, 2 unresolved discussions (waiting on @imnasnainaec)

**Comment by johnthagen** [comment]
___
*[Backend/Models/Project.cs, line 82 at r1](https://reviewable.io/reviews/sillsdev/thecombine/750#-MJCDQCu75hlPqT9rzzt:-MJCMWmo8JmVPbucf6OG:b-dn67my) ([raw file](https://github.com/sillsdev/thecombine/blob/7f0652169b524addf25b3157be6dcb2c02f5ce5d/Backend/Models/Project.cs#L82)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Yikes, this was actually a bug.

A huge part of our `Model`s are these  boilerplate constructors, `Clone`, and `Hash` methods that are brittle and really easy to subtly mess up. I'm going to do a little research to see if there is a way for C# to just autogenerate these, similar to a [Python `dataclass`](https://docs.python.org/3/library/dataclasses.html).
</blockquote></details>

One thing I read is that since our `Model`s are mutable, overriding `GetHashCode` in the way we are doing it could be dangerous if these `Model`s are used as keys to a `Dictionary`.

From looking at the codebase and ASP.NET Core tutorials, it doesn't look like ASP.NET Core needs `Clone`, `Equals`, or `GetHashCode` to work properly. It looks like they are used in our unit tests (which makes sense).

Here is some discussion on why it's important to implement `GetHashCode` if you implement `Equals`: https://stackoverflow.com/a/371348

I don't think there is anything we need to do here, just wanted to share a bit of what I learned.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/750)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[Backend/Models/Project.cs, line 82 at r1](https://reviewable.io/reviews/sillsdev/thecombine/750#-MJCDQCu75hlPqT9rzzt:-MJCjtm_1MIEF8NbJMwr:bh75f5f) ([raw file](https://github.com/sillsdev/thecombine/blob/b1942dab2c4530dac3bfca07f4ceb4dd9e64b3dd/Backend/Models/Project.cs#L82)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

One thing I read is that since our `Model`s are mutable, overriding `GetHashCode` in the way we are doing it could be dangerous if these `Model`s are used as keys to a `Dictionary`.

From looking at the codebase and ASP.NET Core tutorials, it doesn't look like ASP.NET Core needs `Clone`, `Equals`, or `GetHashCode` to work properly. It looks like they are used in our unit tests (which makes sense).

Here is some discussion on why it's important to implement `GetHashCode` if you implement `Equals`: https://stackoverflow.com/a/371348

I don't think there is anything we need to do here, just wanted to share a bit of what I learned.
</blockquote></details>

It was a bug that I caught writing simple, silly unit tests. :)
___
*[Backend/Models/Project.cs, line 179 at r1](https://reviewable.io/reviews/sillsdev/thecombine/750#-MJCE8YHEFnlyPWH49xY:-MJCjzO_2EiFhs_KzjLW:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/b1942dab2c4530dac3bfca07f4ceb4dd9e64b3dd/Backend/Models/Project.cs#L179)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

`AutoCompleteSetting` is missing from `GetHashCode()`.
</blockquote></details>

Done

**Review by johnthagen — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/750)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
