### PR TITLE
Require that Words and Senses have a GUID

### LINKED ISSUE #896: Refactor Word.Guid & Sense.Guid to disallow null
We should update the backend to enforce non-nullness on `Word.Guid` when we are satisfied that all projects have been migrated.

```c#
        /// <summary>
        /// This Guid is important for Lift round-tripping with other applications and must remain stable through Word edits.
        /// </summary>
        /// <remarks>Only nullable for legacy, can be removed once all projects are updated.</remarks>
        [BsonElement("guid")]
        public Guid? Guid { get; set; }
```

https://github.com/sillsdev/TheCombine/blob/632ef2cc090ebf1216c048a692c4cf544ea7cfb7/Backend/Models/Word.cs#L248-L253

Also remove `FrontierController.GetAndRepairFrontier`:

https://github.com/sillsdev/TheCombine/blob/632ef2cc090ebf1216c048a692c4cf544ea7cfb7/Backend/Controllers/FrontierController.cs#L52-L57

Also `WordRepository.PopulateWordGuids`:

https://github.com/sillsdev/TheCombine/blob/632ef2cc090ebf1216c048a692c4cf544ea7cfb7/Backend/Services/WordRepository.cs#L68

- Related to #882
- Need to revert part of #665

### PR DESCRIPTION
**Pull request by johnthagen**
Closes #896 

Undoes most of #1037

The original work around to add GUIDs dynamically to the database was added in #665 in Aug 2019.

The first release to include this was: https://github.com/sillsdev/TheCombine/releases/tag/0.1.0.200903, which is before started numbering releases (pre-0.3.0).

Also, frontend refactor to enforce and preserve word and sense guids.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1013)

### CODE REVIEW

**Comment by johnthagen** [comment]
Database checking script tracked in #1014

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1013)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jasonleenaylor)

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 10 of 11 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1013)* status: 17 of 18 files reviewed, all discussions resolved (waiting on @johnthagen)

___
*[src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesTypes.ts, line 52 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1013#-MTrVbTmDewbtlrkynF1:-MTrVbTmDewbtlrkynF2:b-b6zb6s) ([raw file](https://github.com/sillsdev/thecombine/blob/3700e9b2986d8cdfb3b6ddea4f78a7cee01caecb/src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesTypes.ts#L52)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>   static getGuid(sense: ReviewEntriesSense) {
>     const id = sense.senseId;
>     if (id.endsWith(ReviewEntriesSense.OLD_SENSE)) {
>       return id.slice(0, -ReviewEntriesSense.OLD_SENSE.length);
>     }
>     return id;
>   }
> ```
</details>

The ReviewEntriesAction tests may need a new test that verifies we find an existing sense. One that will result in coverage for this method.

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1013)* status: 14 of 29 files reviewed, all discussions resolved (waiting on @jasonleenaylor and @johnthagen)

___
*[src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesTypes.ts, line 52 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1013#-MTrVbTmDewbtlrkynF1:-MTvrYDPCeqylKbGDbD2:b-eapff3) ([raw file](https://github.com/sillsdev/thecombine/blob/3700e9b2986d8cdfb3b6ddea4f78a7cee01caecb/src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesTypes.ts#L52)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
>   static getGuid(sense: ReviewEntriesSense) {
>     const id = sense.senseId;
>     if (id.endsWith(ReviewEntriesSense.OLD_SENSE)) {
>       return id.slice(0, -ReviewEntriesSense.OLD_SENSE.length);
>     }
>     return id;
>   }
> ```
The ReviewEntriesAction tests may need a new test that verifies we find an existing sense. One that will result in coverage for this method.
</blockquote></details>

Resolved.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 15 of 15 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1013)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Comment by imnasnainaec** [comment]
Waiting on #1013 to merge.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1013)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnthagen)

**Comment by imnasnainaec** [comment]
Awaiting #1043 to update and merge.

**Review by johnthagen — COMMENTED** [review]
> Reviewed 4 of 7 files at r1, 1 of 2 files at r4, 7 of 11 files at r5, 15 of 15 files at r6, 1 of 2 files at r7, 5 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1013)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
