### PR TITLE
Dependabot updates for 02/14/2023

### PR DESCRIPTION
**Pull request by jmgrady**
Update the following packages:

**JavaScript:**

- axios 1.3.3 - this change requires:
   - update to `./src/backend/index.ts` to test for undefined `config`
   - configure Jest to transform `node_modules/axios` (normally `node_modules` is not transformed by `babel-jest`)
- js-base64 3.7.5
- react-modal 3.16.1
- react-toastify 9.1.1
- redux 4.2.1

**.NET:**

- SIL.DictionaryServices 12.0.0
- SIL.WritingSystems 12.0.0
- SIL.Lift 12.0.0
- SIL.Core 12.0.0
- SIL.Core.Desktop 12.0.0
- icu.net 2.9.0

**Python:**

- flake8-bugbear 23.2.13
- kubernetes 26.1.0
- mkdocs-material 9.0.12
- soupsieve 2.4
- types-pyopenssl 23.0.0.3
- types-python-dateutil 2.8.19.7
- types-pyyaml 6.0.12.6
- types-requests 2.28.11.13
- types-urllib3 1.26.25.6
- typing-extensions 4.5.0

**GitHub Actions**

- aws-actions/configure-aws-credentials 1.7.0 (correct SHA checksum)
- step-security/harden-runner 2.2.0

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/1894)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/1894)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor and @jmgrady)

*[a discussion](https://reviewable.io/reviews/sillsdev/TheCombine/1894#-NOKcUVKE6_CDz4Vtmb1:-NOKcUVKE6_CDz4Vtmb2:b-5i8zre) (no related file):*
And don't forget `npm run license-report-frontend`

___

**Comment by jmgrady** [comment]
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/1894)_ status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor and @jmgrady)
> 
> _[a discussion](https://reviewable.io/reviews/sillsdev/TheCombine/1894#-NOKcUVKE6_CDz4Vtmb1:-NOKcUVKE6_CDz4Vtmb2:b-5i8zre) (no related file):_ And don't forget `npm run license-report-frontend`

Thank you.  Done.

Looks like a good candidate for a GitHub Action...

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 3 of 4 files at r3, 1 of 33 files at r4, 37 of 37 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/1894)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[`package.json` line 183 at r5](https://reviewable.io/reviews/sillsdev/TheCombine/1894#-NOV7bdyDQ5hV3J0cxrs:-NOV7bdz9M8pPpVwhcP3:b-1mix5j) ([raw file](https://github.com/sillsdev/TheCombine/blob/a5211fcb12146ac18228915027e33dd17c3f24b8/package.json#L183)):*
> ```JSON
>   },
>   "jest": {
>     "transformIgnorePatterns": ["/node_modules/(!${axios})"]
> ```

Huh, so what is this exactly?



_Code quote:_
```JSON
  "jest": {
    "transformIgnorePatterns": ["/node_modules/(!${axios})"]
  },
```
___
*[`.github/workflows/deploy_qa.yml` line 79 at r5](https://reviewable.io/reviews/sillsdev/TheCombine/1894#-NOV7l9B4lLM13VnJWA8:-NOV7l9B4lLM13VnJWA9:bmnem5w) ([raw file](https://github.com/sillsdev/TheCombine/blob/a5211fcb12146ac18228915027e33dd17c3f24b8/.github/workflows/deploy_qa.yml#L79)):*
> ```YAML
>       - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
>       - name: Configure AWS credentials
>         uses: aws-actions/configure-aws-credentials@4f2f92e5ab58e748e0c4c845528ecf8c646d8373 # v1.7.0
> ```

Did the version change too? (same above) If we have a comment, it should be correct. :-)



_Code quote:_
```YAML
v1.7.0
```
___
*[`docs/user_guide/docs/licenses/backend_licenses.txt` line 19 at r5](https://reviewable.io/reviews/sillsdev/TheCombine/1894#-NOV8S3L4qKqgExnd7Ns:-NOV8S3L4qKqgExnd7Nt:bvtlgvu) ([raw file](https://github.com/sillsdev/TheCombine/blob/a5211fcb12146ac18228915027e33dd17c3f24b8/docs/user_guide/docs/licenses/backend_licenses.txt#L19)):*
> ```help
> ####################################################################################################
> Package:icu.net
> Version:2.8.1
> ```

Isn't this 2.9 now?



_Code quote:_
```help
2.8.1
```

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/1894)* status: 40 of 44 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec, @jasonleenaylor, and @jmgrady)

___
*[`.github/workflows/deploy_qa.yml` line 79 at r5](https://reviewable.io/reviews/sillsdev/TheCombine/1894#-NOV7l9B4lLM13VnJWA8:-NOVHl6QEbeLZ-P-s2WO:bikjetf) ([raw file](https://github.com/sillsdev/TheCombine/blob/a5211fcb12146ac18228915027e33dd17c3f24b8/.github/workflows/deploy_qa.yml#L79)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Did the version change too? (same above) If we have a comment, it should be correct. :-)
</blockquote></details>

Corrected the SHA commit to be the correct on for 1.7.0.  I will close the dependabot PR separately.
___
*[`docs/user_guide/docs/licenses/backend_licenses.txt` line 19 at r5](https://reviewable.io/reviews/sillsdev/TheCombine/1894#-NOV8S3L4qKqgExnd7Ns:-NOVHvrb21f16lWUHG0g:b7lfu46) ([raw file](https://github.com/sillsdev/TheCombine/blob/a5211fcb12146ac18228915027e33dd17c3f24b8/docs/user_guide/docs/licenses/backend_licenses.txt#L19)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Isn't this 2.9 now?
</blockquote></details>

Updated the backend license report.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 2 of 4 files at r6, 11 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/1894)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Pull request merged**
