### PR TITLE
Support custom semantic domains ending in 0

### LINKED ISSUE #741: Add/edit semantic domains
The existing tree of semantic domains is not a good fit for all languages and cultures. It would be useful for project managers to be able to add new domains and possibly edit/delete existing domains.

----

Proposal to allow custom semantic domains while (a) using only 1-digit numbers and (b) not conflicting with established domains:
> Use a single 0 for custom domains:
>    - Standard: 1, 2, 9, 3.1, 4.1.2, etc.
>    - Custom: 0, 0.1, 0.2, 0.1.1, 1.0, 1.0.1, 3.4.0.1.1, etc.
>    - Invalid: 10, 3.11, 0.0, 4.0.1.0, 0.1.20, etc.

Then imported domains, if designated as custom on import, can be prefixed with `0.`.
This also allows custom domains created in The Combine to be added under any existing domain.
Restricting to 1-digit numbers maintains typing (e.g.) 113 for 1.1.3 and prevents confusion between (e.g.) 11.3 and 1.1.3.

----

An alternate/additional idea:
Allow adding custom questions to existing domains. (By default this would not be exported, but would help with the gathering within The Combine.)

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #741

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3081)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
*[`Backend/Services/LiftService.cs` line 661 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/3081#-O0j6Mcc85d5DUzAAf5_:-O0j6Mcc85d5DUzAAf5a:b-gku4ns) ([raw file](https://github.com/sillsdev/TheCombine/blob/8b230fde109e497d258d09b137e8e3bc68d96951/Backend/Services/LiftService.cs#L661)):*
> ```Smalltalk
>         {
>             private readonly string _projectId;
>             private readonly List<SemanticDomainFull> _semDoms = new();
> ```

I think this variable needs renaming to capture its use.

**Comment by jasonleenaylor** [comment]
*[`src/components/TreeView/tests/utilities.test.ts` line 59 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/3081#-O0jIcJxDbP3c-dH5yre:-O0jIcJxDbP3c-dH5yrf:b-lx4rrx) ([raw file](https://github.com/sillsdev/TheCombine/blob/8b230fde109e497d258d09b137e8e3bc68d96951/src/components/TreeView/tests/utilities.test.ts#L59)):*
> ```XML
>     ).not.toBeUndefined();
> 
>     expect(mockGetSemanticDomainTreeNode).toHaveBeenCalledTimes(1);
> ```

This feels like it is getting too far past the unit, into the specifics of the implementation.
Are the types of calls made to find the parent an implementation detail, or critical to the methods correct behavior?

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3081)* status: 0 of 34 files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[`src/components/TreeView/tests/utilities.test.ts` line 59 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/3081#-O0jIcJxDbP3c-dH5yre:-O0jdsTk96tQ6dY7rzqm:bh9do5g) ([raw file](https://github.com/sillsdev/TheCombine/blob/8b230fde109e497d258d09b137e8e3bc68d96951/src/components/TreeView/tests/utilities.test.ts#L59)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

This feels like it is getting too far past the unit, into the specifics of the implementation.
Are the types of calls made to find the parent an implementation detail, or critical to the methods correct behavior?
</blockquote></details>

Somewhat implementation detail. I mocked out those functions to better test method behavior.

**Review by jasonleenaylor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, 33 of 33 files at r2, 4 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3081#-:-O0jiyh9CpJLNthSzpym:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
