### PR TITLE
Dependabot updates for June 2024

### PR DESCRIPTION
**Pull request by jmgrady**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3148)

### CODE REVIEW

**Review by imnasnainaec — CHANGES_REQUESTED** [review]
> Reviewed 15 of 17 files at r1, 3 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3148)* status: 20 of 24 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`Dockerfile` line 19 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/3148#-NzZEGRV8Qzz0hYPbvt0:-NzZEGRV8Qzz0hYPbvt1:b-s40had) ([raw file](https://github.com/sillsdev/TheCombine/blob/792170a09ff5627e7d185eeaed1f2b9684ba8992/Dockerfile#L19)):*
> ```Dockerfile
> 
> # Frontend build environment.
> FROM node:20.14.0-bookworm-slim AS frontend_builder
> ```

This is a mismatch with `.github/workflows/frontend.yml` which still has `node-version: [18]` for two of its jobs. Also, the `"volta":` bit in `packages.json` should match this (or be deleted, since I don't think we're using it).

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3148)* status: 16 of 24 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[`Dockerfile` line 19 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/3148#-NzZEGRV8Qzz0hYPbvt0:-NzZf2NJ4O2V-_Rb1sg6:bkbom3y) ([raw file](https://github.com/sillsdev/TheCombine/blob/792170a09ff5627e7d185eeaed1f2b9684ba8992/Dockerfile#L19)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

This is a mismatch with `.github/workflows/frontend.yml` which still has `node-version: [18]` for two of its jobs. Also, the `"volta":` bit in `packages.json` should match this (or be deleted, since I don't think we're using it).
</blockquote></details>

I have changed the workflow to use Node 20 - it is my understanding that is what you have been using and I have started using it for development builds as well.  As for `volta`, I am using it.  It is very helpful to enable different projects/branches to use different versions of `node`.  I recommend it.

**Review by imnasnainaec — CHANGES_REQUESTED** [review]
> Reviewed 2 of 17 files at r1, 2 of 5 files at r2, 3 of 3 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3148)* status: all files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`Dockerfile` line 19 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/3148#-NzZEGRV8Qzz0hYPbvt0:-NzZiwtL7UxS6FJv7fhl:b17bpsw) ([raw file](https://github.com/sillsdev/TheCombine/blob/792170a09ff5627e7d185eeaed1f2b9684ba8992/Dockerfile#L19)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

I have changed the workflow to use Node 20 - it is my understanding that is what you have been using and I have started using it for development builds as well.  As for `volta`, I am using it.  It is very helpful to enable different projects/branches to use different versions of `node`.  I recommend it.
</blockquote></details>

Yes, it is, and I'm glad you're updating it. Two more changes:
* The `README` still instructs installing Node 18
* You have `20.14.0` here but the volta line in `packages.json` has `20.12.2`

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3148)* status: 23 of 25 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[`Dockerfile` line 19 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/3148#-NzZEGRV8Qzz0hYPbvt0:-NzZrOAZ8hGkzV2WFfoi:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/792170a09ff5627e7d185eeaed1f2b9684ba8992/Dockerfile#L19)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Yes, it is, and I'm glad you're updating it. Two more changes:
* The `README` still instructs installing Node 18
* You have `20.14.0` here but the volta line in `packages.json` has `20.12.2`
</blockquote></details>

Done.

**Review by imnasnainaec — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3148)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Pull request merged**
