### PR TITLE
K3s engine

### PR DESCRIPTION
**Pull request by jmgrady**
Migrate from using `microk8s` to `k3s` as the lightweight Kubernetes engine used on the NUCs.  `k3s` is from _Rancher_ so that deploying _The Combine_ is more consistent with the Rancher Kubernetes cluster that will be used for the live and QA servers.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1382)

### CODE REVIEW

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 8 of 23 files at r1, 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1382)* status: 10 of 23 files reviewed, all discussions resolved (waiting on @jmgrady)

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1382)* status: 11 of 23 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[deploy/group_vars/nuc/main.yml, line 56 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1382#-MkN7nGp8OjqiLIPyBLV:-MkN7nGp8OjqiLIPyBLW:b-7ww5qb) ([raw file](https://github.com/sillsdev/thecombine/blob/f5885067f6507cba777f978810fff4c61e5baa27/deploy/group_vars/nuc/main.yml#L56)):*
> ```YAML
> k8s_components:
>   - microk8s
>   - cert_manager
> ```

There are a couple instances of `when: '"cert_manager" in k8s_components'` and `{% if "cert_manager" in k8s_components %}` in `deploy/`. Are those still relevant with the deletion of this line?

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1382)* status: 11 of 23 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[deploy/group_vars/nuc/main.yml, line 56 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1382#-MkN7nGp8OjqiLIPyBLV:-MkN8PoVArkZrvWFg_o5:bcq3o5t) ([raw file](https://github.com/sillsdev/thecombine/blob/f5885067f6507cba777f978810fff4c61e5baa27/deploy/group_vars/nuc/main.yml#L56)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

There are a couple instances of `when: '"cert_manager" in k8s_components'` and `{% if "cert_manager" in k8s_components %}` in `deploy/`. Are those still relevant with the deletion of this line?
</blockquote></details>

Yes.  The deployment for the server sandbox uses `cert_manager`.  This does not really show up in the files managed by `git` - I have a `dev.hosts.yml` file for defining development configurations.  The reason we do not include the `cert_manager` in the server implementation is that Greg Mackay manages that - we do not have permissions for altering that namespace on the production cluster.  (which is a good thing since there are other projects sharing the resources)

The `cert_manager` is used to fetch Let's Encrypt certificates so it only makes sense on a system that is reachable from the internet.

**Review by imnasnainaec — COMMENTED** [review]
> Reviewed 3 of 23 files at r1, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1382)* status: 17 of 26 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

**Comment by johnthagen** [comment]
___
*[scripts/kube_setup.py, line 1 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1382#-MkNZUlMCL3xs8cG9CQY:-MkNZUlMCL3xs8cG9CQZ:bc6z7wa) ([raw file](https://github.com/sillsdev/thecombine/blob/f5885067f6507cba777f978810fff4c61e5baa27/scripts/kube_setup.py#L1)):*
> ```Python
> #!/usr/bin/env python3
> ```

Are we planning to add an equivalent for `k3s` later?

**Review by johnthagen — COMMENTED** [review]
> Reviewed 19 of 23 files at r1, 4 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1382)* status: all files reviewed, 2 unresolved discussions (waiting on @jmgrady)

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1382)* status: all files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[deploy/roles/k3s/tasks/main.yml, line 63 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1382#-MkNYRUvAKKWwnBSLjJX:-MkNdbG84cWlQMFP2h--:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/f43ba924299fb8a3a42d3a5cc2af2ccf280f73d5/deploy/roles/k3s/tasks/main.yml#L63)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

An example before/after for this regex might make it easier to review. Does this run over port`6443`?
</blockquote></details>

Done.
___
*[scripts/kube_setup.py, line 1 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1382#-MkNZUlMCL3xs8cG9CQY:-MkNdfyACdmGaVTF3_yk:b9vjms1) ([raw file](https://github.com/sillsdev/thecombine/blob/f5885067f6507cba777f978810fff4c61e5baa27/scripts/kube_setup.py#L1)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Are we planning to add an equivalent for `k3s` later?
</blockquote></details>

This file has been removed until the version for development machines is ready to use.

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1382)* status: 22 of 26 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @johnthagen)

___
*[scripts/kube_setup.py, line 1 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1382#-MkNZUlMCL3xs8cG9CQY:-MkNiZ8p6UnN1S7S74yA:bhb2rri) ([raw file](https://github.com/sillsdev/thecombine/blob/f5885067f6507cba777f978810fff4c61e5baa27/scripts/kube_setup.py#L1)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

This file has been removed until the version for development machines is ready to use.
</blockquote></details>

I re-read your question - I think the correct answer is "Yes.  When I put together a method to run The Combine under kubernetes on a development machine, this file or an equivalent will be added to the scripts."

**Review by johnthagen — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1382)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Pull request merged**
