### PR TITLE
Improve ids for automated testing

### PR DESCRIPTION
**Pull request by imnasnainaec**
Follow-up on #1310 
Related to #1185 

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1377)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[-- commits, line 1 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1377#-MjoR8w5C6bITGSWciP8):*
For consistency, can we not add periods at the end of PR titles? That is the standard I've seen used most and they do end up in the squashed commit message.

**Comment by johnthagen** [comment]
___
*[src/components/AppBar/UserMenu.tsx, line 115 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1377#-MjoS6-V0PMLV91hbUNR:-MjoS6-V0PMLV91hbUNS:b-npu5n1) ([raw file](https://github.com/sillsdev/thecombine/blob/1109702c09741fc8fa0525549cdfa731d7068784/src/components/AppBar/UserMenu.tsx#L115)):*
> ```XML
>       {props.isAdmin && (
>         <MenuItem
>           id="user-menu-admin"
> ```

This is a broader observation, but should we use prefixes and string interpolation to make it easier to manage these `id`s?

For example:

```ts
const idPrefix = "user-menu";
...

        <MenuItem
          id={`${idPrefix}-admin`}
```

**Comment by johnthagen** [comment]
___
*[src/components/DataEntry/DataEntryTable/tests/DataEntryTable.test.tsx, line 91 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1377#-MjoTIlqEQ8pcMK-sUSA:-MjoTIlqEQ8pcMK-sUSB:bly84f7) ([raw file](https://github.com/sillsdev/thecombine/blob/1109702c09741fc8fa0525549cdfa731d7068784/src/components/DataEntry/DataEntryTable/tests/DataEntryTable.test.tsx#L91)):*
> ```XML
>         // Get exit button and push it
>         testRenderer.root
>           .findByProps({ id: "exit-to-domain-tree" })
> ```

This magic string is repeated. Can it be defined a single time as a `const`?

**Review by johnthagen — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1377)* status: all files reviewed, 3 unresolved discussions (waiting on @imnasnainaec)

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1377)* status: 8 of 18 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @johnthagen)

___
*[-- commits, line 1 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1377#-MjoR8w5C6bITGSWciP8):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

For consistency, can we not add periods at the end of PR titles? That is the standard I've seen used most and they do end up in the squashed commit message.
</blockquote></details>

Affirmative.
___
*[src/components/DataEntry/DataEntryTable/tests/DataEntryTable.test.tsx, line 91 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1377#-MjoTIlqEQ8pcMK-sUSA:-MjokM6WCClXObDW0Max:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/1109702c09741fc8fa0525549cdfa731d7068784/src/components/DataEntry/DataEntryTable/tests/DataEntryTable.test.tsx#L91)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This magic string is repeated. Can it be defined a single time as a `const`?
</blockquote></details>

Done.

**Review by johnthagen — APPROVED** [review]
> Reviewed 9 of 9 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1377)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)

**Pull request merged**
